[package]
name = "manbow-fetcher"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
scraper = { workspace = true }
toml = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
encoding_rs = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
clap = { workspace = true }