[[entries]]
no = "1"
name = "MISS / 642"
title = "Crisis"
size = "17300 KB"
addr = ["http://www.geocities.co.jp/NeverLand-Homeroom/1819/642_cri_bga.exe.zip"]
genre = "Techno"
impr = "7"
total = "8"
avg = "1.14"
regist = "20020720"
update = "20020729"

[[entries]]
no = "2"
name = "6yen / G"
title = "Cynic"
size = "5881 KB"
addr = ["http://www.geocities.co.jp/HeartLand-Poplar/4130/bga.html"]
genre = "techno"
impr = "20"
total = "40"
avg = "2"
regist = "20020721"
update = "20020729"

[[entries]]
no = "3"
name = "parakeet41 / RainbowColors"
title = "NeXt!!"
size = "12900 KB"
addr = ["http://www1.linkclub.or.jp/~is-m/bms/data/next.rar"]
genre = "ALL MIX"
impr = "20"
total = "27"
avg = "1.35"
regist = "20020721"
update = "20020729"

[[entries]]
no = "4"
name = "beat MARIO / tomsfir"
title = "Last! Least! Regrets!!"
size = "5876 KB"
addr = ["http://www.asahi-net.or.jp/~cx8t-adc/llr_bga.zip"]
genre = "HyperEuroBeat"
impr = "23"
total = "42"
avg = "1.82"
regist = "20020722"
update = "20020729"
