[[entries]]
no = "1"
name = "美月 正"
title = "E reviver -imaging you-"
size = "9114 KB"
addr = ["http://masa-ino.hp.infoseek.co.jp/E%20rev_m.zip"]
genre = "Romantix"
impr = "94645"
total = "94763"
avg = "1"
update = "2003/08/10 23:29"

[[entries]]
no = "2"
name = "ridis"
title = "heartless wind -ceres remix-"
size = "6303 KB"
addr = ["http://liz.nothing.sh/ridis/ceres_r.rar"]
genre = "Instrumental"
impr = "94913"
total = "95024"
avg = "1"
update = "2003/08/10 23:30"

[[entries]]
no = "3"
name = "yxckw@oyykgor.com"
title = "searoad tracks =side blue="
size = "12288 KB"
addr = ["http://sound.jp/sasakure_6/searemix.rar"]
genre = "Intelligence"
impr = "104015"
total = "104137"
avg = "1"
update = "2003/08/10 22:02"

[[entries]]
no = "4"
name = "groum@cnlqwjt.com"
title = "raise"
size = "589 KB"
addr = ["http://white.sakura.ne.jp/~s-jam/raise.zip"]
genre = "House"
impr = "42637"
total = "42708"
avg = "1"
update = "2003/08/10 23:38"

[[entries]]
no = "5"
name = "xcgmd@ioiuhdc.com"
title = "雪舞"
size = "3008 KB"
addr = ["http://www.eonet.ne.jp/~ciel-son-terre/yukimai.zip"]
genre = "easy listening"
impr = "47041"
total = "47107"
avg = "1"
update = "2003/08/10 22:08"

[[entries]]
no = "6"
name = "fjvvs@slhshdk.com"
title = "D-Impact"
size = "2610 KB"
addr = ["http://www.remarkablesense.org/~ariake/music/DI.zip"]
genre = "Jazzy Tap"
impr = "54460"
total = "54532"
avg = "1"
update = "2003/08/10 23:44"

[[entries]]
no = "7"
name = "precis fan"
title = "Britain Love"
size = "8531 KB"
addr = ["http://www.ismusic.ne.jp/08294432/trance_rave_bl.zip"]
genre = "TRANCE RAVE"
impr = "60967"
total = "61044"
avg = "1"
update = "2003/08/10 22:21"

[[entries]]
no = "8"
name = "fether"
title = "☆ twinklesky ☆"
size = "4789 KB"
addr = ["http://www.kcnet.ne.jp/~hyuri/f-6th/"]
genre = "kirby pop"
impr = "112448"
total = "112574"
avg = "1"
update = "2003/08/11 00:22"

[[entries]]
no = "9"
name = "SHIKI"
title = "Synthesized Girl's Heart"
size = "8788 KB"
addr = ["http://www.remarkablesense.org/~shiki/girl.exe"]
genre = "Digital Rock Beat"
impr = "90003"
total = "90123"
avg = "1"
update = "2003/08/10 23:36"

[[entries]]
no = "10"
name = "qmlia@mvbcbqs.com"
title = "Subversive Attack"
size = "4350 KB"
addr = ["http://olive.zero.ad.jp/~zaw11779/siromaroom/bms/si_subversive.rar"]
genre = "Hard Techno"
impr = "52452"
total = "52517"
avg = "1"
update = "2003/08/10 23:56"

[[entries]]
no = "11"
name = "AM"
title = "THE FIRST STAGE ～SM2&GG～"
size = "15290 KB"
addr = ["http://manbow.nothing.sh/bms/AM_first.rar"]
genre = "GameMusic Arr."
impr = "33969"
total = "34014"
avg = "1"
update = "2003/08/10 22:44"

[[entries]]
no = "12"
name = "霧原由羽"
title = "Elttab Tsal"
size = "6650 KB"
addr = ["http://www5a.biglobe.ne.jp/~o-3a/k-lb.rar"]
genre = "HR/HM"
impr = "48347"
total = "48411"
avg = "1"
update = "2003/08/10 23:55"

[[entries]]
no = "13"
name = "wint"
title = 'REWD "B159 mix"'
size = "8657 KB"
addr = ["http://www.bmsjournal.net/lvo/"]
genre = "RAVE"
impr = "71724"
total = "71807"
avg = "1"
update = "2003/08/10 23:56"

[[entries]]
no = "14"
name = "prqtf@ullcjum.com"
title = "in the starlight"
size = "6420 KB"
addr = ["http://liz.nothing.sh/wolf/wolf_starlight.rar"]
genre = "Hyper Eurobeat"
impr = "37374"
total = "37423"
avg = "1"
update = "2003/08/10 22:43"

[[entries]]
no = "15"
name = "prrbg@jbunucc.com"
title = "I believe"
size = "9060 KB"
addr = ["http://www.remarkablesense.org/~hal/bms/believe_bms.lzh"]
genre = "HI-NRG"
impr = "69098"
total = "69181"
avg = "1"
update = "2003/08/10 22:41"

[[entries]]
no = "16"
name = "apiih@tdoyffi.com"
title = "那由多の刻"
size = "8610 KB"
addr = ["http://www.ismusic.ne.jp/e-music/nayuta.rar"]
genre = "Classcal Element"
impr = "37128"
total = "37184"
avg = "1"
update = "2003/08/10 23:11"

[[entries]]
no = "17"
name = "anyfi@zqfbxcm.com"
title = "小さなトリカゴ"
size = "4602 KB"
addr = ["http://liz.nothing.sh/ari/b/torikago.zip"]
genre = "---"
impr = "71775"
total = "71861"
avg = "1"
update = "2003/09/08 05:29"

[[entries]]
no = "18"
name = "rnaod@kotypbb.com"
title = "Sicilian kiss"
size = "7955 KB"
addr = ["http://www.remarkablesense.org/~snowdrop/snow_sicilian.rar"]
genre = "progressive jazz"
impr = "60269"
total = "60340"
avg = "1"
update = "2003/08/10 23:18"

[[entries]]
no = "19"
name = "Nao Shimamura"
title = "MUSASHINO.205"
size = "1198 KB"
addr = ["http://naos.dmz-plus.com/m205_d.zip"]
genre = "Iron Hardcore Minimal"
impr = "20994"
total = "21037"
avg = "1"
update = "2003/08/10 23:02"

[[entries]]
no = "20"
name = "MASAKI"
title = "regain one's power"
size = "6436 KB"
addr = ["http://bucho.hp.infoseek.co.jp/BMS/rop_lq.zip"]
genre = "Arabian Rock"
impr = "17296"
total = "17318"
avg = "1"
update = "2003/08/10 23:50"

[[entries]]
no = "21"
name = "maklow"
title = "Resolution"
size = "2721 KB"
addr = ["http://www.remarkablesense.org/~maklow/reso.rar"]
genre = "artcore"
impr = "29693"
total = "29738"
avg = "1"
update = "2003/08/11 01:58"

[[entries]]
no = "22"
name = "ihbif@dftcmyk.com"
title = "cure-all"
size = "5992 KB"
addr = ["http://www.ismusic.ne.jp/psypha/lizvsomt.html"]
genre = "PSYCHEDELIC"
impr = "48021"
total = "48076"
avg = "1"
update = "2003/08/10 23:29"

[[entries]]
no = "23"
name = "narve"
title = "osmosis"
size = "4001 KB"
addr = ["http://liz.nothing.sh/narve/index.html"]
genre = "psychedelic trance"
impr = "68234"
total = "68310"
avg = "1"
update = "2003/08/10 23:32"

[[entries]]
no = "24"
name = "Raynoa"
title = "Loveless"
size = "5504 KB"
addr = ["http://www.remarkablesense.org/~raynoa/LiZvsOMT/"]
genre = "Dutch trance"
impr = "33337"
total = "33384"
avg = "1"
update = "2003/08/10 23:36"

[[entries]]
no = "25"
name = "mocoro"
title = "Determination"
size = "2571 KB"
addr = ["http://www.ismusic.ne.jp/koji2000/temp/mocoro_Determination.rar"]
genre = "TRANCE"
impr = "41617"
total = "41668"
avg = "1"
update = "2003/08/10 23:11"

[[entries]]
no = "26"
name = "pccuz@vyeslqg.com"
title = "G e n g a o z o"
size = "4118 KB"
addr = ["http://www.malie.p-visual.com/box2/archive/gengaozo_.rar"]
genre = "P s y"
impr = "53858"
total = "53921"
avg = "1"
update = "2003/08/10 23:39"

[[entries]]
no = "27"
name = "zocuu@jljnrqt.com"
title = "追憶の森 -Voices of the Earth-"
size = "9273 KB"
addr = ["http://www.remarkablesense.org/~akito/akito_tuioku_lq.rar"]
genre = "Celtic"
impr = "84289"
total = "84380"
avg = "1"
update = "2003/08/10 23:59"

[[entries]]
no = "28"
name = "amziy@spkvnlp.com"
title = "Bundles of flowers"
size = "11078 KB"
addr = ["http://www.ismusic.ne.jp/gun-seki/bundles_of_flowers.rar"]
genre = "Instrumental"
impr = "35261"
total = "35305"
avg = "1"
update = "2003/08/10 23:52"

[[entries]]
no = "29"
name = "Pinky feat. L'Ile"
title = "Stay with me"
size = "4173 KB"
addr = ["http://www.ismusic.ne.jp/pinky/bms/swm.html"]
genre = "DANCE POP"
impr = "39493"
total = "39538"
avg = "1"
update = "2003/08/10 23:58"

[[entries]]
no = "30"
name = "caegt@fqbwwsv.com"
title = "CELL (the 4th dimension)"
size = "868 KB"
addr = ["http://trsh.cside.ne.jp/c_e_l_l.html"]
genre = "STYLISH"
impr = "34021"
total = "34063"
avg = "1"
update = "2003/08/10 23:53"
