[[entries]]
no = "1"
name = "asahi"
title = "AGNM"
size = "904 KB"
addr = ["https://dl.dropboxusercontent.com/s/ipzxsonhfarhw0x/%5Basahi%5DAGNM.rar?dl=0"]
genre = "ハードテクノ"
impr = "16"
total = "26"
median = "2"
avg = "1.62"
regist = "2015/01/24 00:01"
update = "2015/02/16 00:25"

[[entries]]
no = "2"
name = "sound piercer / mov : [IX]"
title = "死んだ子の影の上で踊る"
size = "35385 KB"
addr = ["http://1drv.ms/1Ctc1Sm"]
genre = "とりゃんせ 裏編"
impr = "17"
total = "43"
median = "3"
avg = "2.52"
regist = "2015/01/24 00:01"
update = "2015/02/15 18:04"

[[entries]]
no = "3"
name = "momo★yama"
title = "聖者龍"
size = "13463 KB"
addr = ["https://dl.dropboxusercontent.com/u/59483835/fhb.rar"]
genre = "ファンタジーハードバロック"
impr = "15"
total = "34"
median = "2"
avg = "2.26"
regist = "2015/01/24 00:02"
update = "2015/02/15 23:59"

[[entries]]
no = "4"
name = "w_tre"
title = "Shannon's Theorem"
size = "51300 KB"
addr = ["http://db.tt/4QYYAv2A"]
genre = "代数トリオ"
impr = "23"
total = "68"
median = "3"
avg = "2.95"
regist = "2015/01/24 00:17"
update = "2015/02/16 00:03"

[[entries]]
no = "5"
name = "ROKINA"
title = "Icicle Stinger"
size = "10322 KB"
addr = ["https://dl.dropboxusercontent.com/s/x4wt7tcjs7tep6l/LNB54-icicle.rar"]
genre = "パニコア"
impr = "14"
total = "39"
median = "3"
avg = "2.78"
regist = "2015/01/24 00:44"
update = "2020/06/11 23:42"

[[entries]]
no = "6"
name = "RYO-K"
title = "落葉斜陽"
size = "21380 KB"
addr = ["https://www.dropbox.com/s/58hfrt1qx05h9am/%E3%80%90RYO-K%E3%80%91%E8%90%BD%E8%91%89%E6%96%9C%E9%99%BD.zip?dl=1"]
genre = "J-2ステップハウス"
impr = "13"
total = "32"
median = "3"
avg = "2.46"
regist = "2015/01/24 01:00"
update = "2015/02/15 23:58"

[[entries]]
no = "7"
name = "戒斗"
title = "SUPERFLUIDITY"
size = "13397 KB"
addr = ["http://yahoo.jp/box/IrREVT"]
genre = "アブソリュートゼロ"
impr = "11"
total = "24"
median = "2"
avg = "2.18"
regist = "2015/01/24 01:31"
update = "2015/02/15 23:05"

[[entries]]
no = "8"
name = "litmus*"
title = "Lapis Lazuli Stern"
size = "1791 KB"
addr = ["https://drive.google.com/file/d/0B0a6-fXyD9ZEZkhCUHBpWTV6dDA/view?usp=sharing"]
genre = "エレクトロ ハウス"
impr = "15"
total = "41"
median = "3"
avg = "2.73"
regist = "2015/01/24 02:24"
update = "2015/11/12 18:41"

[[entries]]
no = "9"
name = "KA-KU feat.春歌ナナ"
title = "新時代的☆まじかるがーる！"
size = "17300 KB"
addr = ["http://dl.dropboxusercontent.com/u/87297315/150124_magical/magical.zip"]
genre = "Aスピードポップ"
impr = "14"
total = "32"
median = "2"
avg = "2.28"
regist = "2015/01/24 06:26"
update = "2015/02/15 23:05"

[[entries]]
no = "10"
name = "アオ+fkRadish(紫翠)"
title = "ハロミー"
size = "8533 KB"
addr = ["http://fuki1755.starfree.jp/bms/hellome_ogg.rar"]
genre = "ボカロック"
impr = "10"
total = "24"
median = "2.5"
avg = "2.4"
regist = "2015/01/25 05:00"
update = "2020/02/13 17:33"

[[entries]]
no = "11"
name = "yoa feat.にゃし"
title = "温舞 雪の章"
size = "10645 KB"
addr = ["http://docs.google.com/uc?id=0ByS9Wlo7KZbxc2JwVm8zSnpHTWM&export=download"]
genre = "コトロニカ"
impr = "14"
total = "37"
median = "3"
avg = "2.64"
regist = "2015/01/25 23:43"
update = "2015/02/15 23:41"

[[entries]]
no = "12"
name = "abysalla vs DaDass"
title = "limbo"
size = "11193 KB"
addr = [
    "http://pan.baidu.com/s/1jGstbxG#path=%252FSymphonian%2520BMS",
    "limbo.rar",
]
genre = "アグロテック"
impr = "12"
total = "22"
median = "2"
avg = "1.83"
regist = "2015/01/26 04:53"
update = "2015/02/15 19:39"

[[entries]]
no = "13"
name = "daisan"
title = "微睡み色ディプラヴィティ"
size = "13533 KB"
addr = ["http://clockxellox.sakura.ne.jp/BMS/daisan_Madoromi.zip"]
genre = "ニヒルアート"
impr = "13"
total = "34"
median = "3"
avg = "2.61"
regist = "2015/01/26 22:03"
update = "2015/02/15 23:58"

[[entries]]
no = "14"
name = "ume"
title = "Ma shi ro"
size = "25000 KB"
addr = ["http://www42.tok2.com/home/umeboz/mashiropms.zip"]
genre = "スノウハウス"
impr = "10"
total = "24"
median = "2"
avg = "2.4"
regist = "2015/01/27 00:17"
update = "2015/02/15 23:28"

[[entries]]
no = "15"
name = "空見沢佳奈(CV:Alisa.T) RMX by nmk"
title = "SkyGazer(nmk Eurobeat remix)"
size = "15938 KB"
addr = ["https://docs.google.com/uc?id=0B97xj9Ow1Tu8LUlOSFhZcUlTUmM&export=download"]
genre = "アニポップユーロREMIX"
impr = "12"
total = "26"
median = "2.5"
avg = "2.16"
regist = "2015/01/28 01:30"
update = "2015/02/15 23:07"

[[entries]]
no = "16"
name = "gransear"
title = "この街が見せる幻想"
size = "18439 KB"
addr = [
    "http://gransear.noor.jp/hscolors/bpms/gransear_konomachi_ogg.zip",
    "通常版です。パッケージにはこちらをお願い致します。",
    "http://gransear.noor.jp/hscolors/bpms/gransear_konomachi_dekai_ogg.zip",
    "音割れ気味な音量大きめバージョンです。音量以外中身は一緒です。",
]
genre = "メモリーオブザタウン"
impr = "12"
total = "32"
median = "3"
avg = "2.66"
regist = "2015/01/28 09:24"
update = "2015/02/19 03:55"

[[entries]]
no = "17"
name = "風鈴奏"
title = "Rhadamanthys"
size = "8844 KB"
addr = ["https://www.dropbox.com/s/2kejd7bmlwjvlgh/%E3%82%A8%E3%83%AA%E3%83%A5%E3%82%B7%E3%82%AA%E3%83%B3.zip?dl=1"]
genre = "エリュシオン"
impr = "10"
total = "17"
median = "2"
avg = "1.7"
regist = "2015/01/29 18:49"
update = "2015/02/15 23:09"

[[entries]]
no = "18"
name = "かゆき"
title = "白色の約束"
size = "6000 KB"
addr = ["http://docs.google.com/uc?id=0B0VmuCNXc4xYSFFQQzA2dTA4cnc&export=download"]
genre = "スノウドロップ"
impr = "12"
total = "31"
median = "3"
avg = "2.58"
regist = "2015/01/29 21:12"
update = "2015/02/15 23:58"

[[entries]]
no = "19"
name = "Neun_jack"
title = "La bandiera della Pace"
size = "17613 KB"
addr = ["http://dl.dropboxusercontent.com/u/60346274/Neunjack/Peace_of_all_world_ogg.rar"]
genre = "ハードスタイルフィナーレ"
impr = "11"
total = "19"
median = "2"
avg = "1.72"
regist = "2015/01/30 21:20"
update = "2015/02/15 23:57"

[[entries]]
no = "20"
name = "Yie Ar Kung-Fu"
title = "技術舞"
size = "97585 KB"
addr = ["https://dl.dropboxusercontent.com/s/iyhox7ieazyczc1/jishu_wu.zip?dl=1"]
genre = "イミテイションチャイニーズ"
impr = "10"
total = "23"
median = "2"
avg = "2.3"
regist = "2015/01/31 04:02"
update = "2015/02/23 22:14"

[[entries]]
no = "21"
name = "sijima vs ジーニアスかわいい！！"
title = "PATCH"
size = "30900 KB"
addr = ["https://dl.dropboxusercontent.com/u/30720469/bms/PATCH_pms.zip"]
genre = "ロココテック"
impr = "10"
total = "16"
median = "2"
avg = "1.6"
regist = "2015/01/31 15:23"
update = "2015/02/21 12:02"

[[entries]]
no = "22"
name = "Y.W"
title = "ふゆいろ ドリーマー"
size = "14580 KB"
addr = ["http://www.yw-works.com/data/bm/huyuiro_dreamer_ogg.zip"]
genre = "ポップリスニング4"
impr = "16"
total = "46"
median = "3"
avg = "2.87"
regist = "2015/01/31 16:05"
update = "2015/02/15 23:59"

[[entries]]
no = "23"
name = "o.s.gate"
title = "Unknown B O X"
size = "1070 KB"
addr = ["https://www.dropbox.com/s/onwvlibt23w0vl5/U_box.zip?dl=0"]
genre = "エクスペリメンタルビート"
impr = "10"
total = "17"
median = "2"
avg = "1.7"
regist = "2015/02/01 03:45"
update = "2015/02/15 23:10"

[[entries]]
no = "24"
name = "ドルフィン"
title = "Luminos"
size = "18842 KB"
addr = ["https://dl.dropboxusercontent.com/u/50992731/BMS%20Original/Luminos_ogg.rar"]
genre = "プログレッシブトランス"
impr = "10"
total = "17"
median = "2"
avg = "1.7"
regist = "2015/02/01 04:38"
update = "2015/02/15 23:11"

[[entries]]
no = "25"
name = "落雁"
title = "雪に沈む"
size = "3901 KB"
addr = ["http://fantasicnotes.net/bms/LUCK19_sr.zip"]
genre = "スノウリコレクション"
impr = "10"
total = "16"
median = "1.5"
avg = "1.6"
regist = "2015/02/01 10:52"
update = "2015/02/22 16:20"

[[entries]]
no = "26"
name = "P4koo"
title = "Midnight Rave Night"
size = "8950 KB"
addr = ["http://1drv.ms/18EqM9J"]
genre = "ミッドナイトレイヴ"
impr = "10"
total = "25"
median = "3"
avg = "2.5"
regist = "2015/02/01 17:24"
update = "2015/02/15 23:13"

[[entries]]
no = "27"
name = "ccgc"
title = "accelerate"
size = "16540 KB"
addr = ["https://www.dropbox.com/s/8pka76z1mr2rjg0/c05_dgm.rar?dl=0"]
genre = "DIGI-MIXTURE"
impr = "12"
total = "32"
median = "3"
avg = "2.66"
regist = "2015/02/01 22:49"
update = "2015/02/15 23:52"

[[entries]]
no = "28"
name = "Yosk!"
title = "ジオラマの夏"
size = "25267 KB"
addr = ["https://drive.google.com/open?id=0B7qCw4hNijr4aWJtT2w4ZlBpc1U"]
genre = "ソーダフロート"
impr = "13"
total = "33"
median = "3"
avg = "2.53"
regist = "2015/02/01 23:39"
update = "2018/02/14 04:02"

[[entries]]
no = "29"
name = "TKR"
title = "木管楽器と打楽器アンサンブルの為の小奏鳴曲第一番 アッサイモデラート"
size = "11824 KB"
addr = [
    "https://dl.dropboxusercontent.com/s/en9335ys6vxeuvb/%5BTKR%5Dassaimoderato.zip?dl=0",
    "※N譜面を微調整、H譜面とEX譜面を新しく追加いたしました。",
    "25/38/50",
]
genre = "トランセンデンタルソナチネ"
impr = "11"
total = "30"
median = "3"
avg = "2.72"
regist = "2015/02/01 23:49"
update = "2015/02/15 23:56"

[[entries]]
no = "30"
name = "Ino"
title = "コケシネコ☆クライシス"
size = "89000 KB"
addr = [
    "https://dl.dropboxusercontent.com/u/53751238/ino_kokeshineko2_pms.zip",
    "---2015/02/07/03:24までにDLされた方はこちらも導入して下さい---",
    "https://dl.dropboxusercontent.com/u/53751238/ino_kokeshineko2_sabun_2_7.zip",
]
genre = "ブレイクコア"
impr = "24"
total = "70"
median = "3"
avg = "2.91"
regist = "2015/02/01 23:55"
update = "2015/02/17 00:33"

[[entries]]
no = "31"
name = "kagerow"
title = "Starry Story!"
size = "29065 KB"
addr = [
    "★",
    "http://kagerow.net/bms/starry_story.zip",
    "（2015/02/16 16 00：06 修正版）",
    "◆ 2015/02/16 16 00：06 以前にDLした方は↓のファイルを上書きして下さい",
    "http://kagerow.net/bms/starry_story_sabun.zip",
    "◆ 公開当初のファイル 評価は↓のものでお願いします",
    "http://kagerow.net/bms/starry_story_beta.zip",
]
genre = "ドリーミーポップロック"
impr = "10"
total = "29"
median = "3"
avg = "2.9"
regist = "2015/02/01 23:59"
update = "2015/02/16 00:21"
