[[entries]]
no = "1"
name = "Jun Kuroda"
title = "Terpsichore"
size = "72192 KB"
addr = ["https://docs.google.com/uc?export=download&confirm=nFgd&id=0B4SYfvnYPRSXbE52UHd3NG9rX2s"]
genre = "Artcore"
impr = "71"
total = "318"
median = "5"
avg = "4.47"
regist = "2015/06/01 00:02"
update = "2015/06/28 23:53"

[[entries]]
no = "2"
name = "きるは"
title = "gean"
size = "10600 KB"
addr = [
    "http://www1.axfc.net/u/3477319.zip",
    "https://dl.dropboxusercontent.com/s/txo9oeft1mn1d7z/Gean_kiruha.zip",
]
genre = "peripeteia"
impr = "55"
total = "190"
median = "3"
avg = "3.45"
regist = "2015/06/01 00:02"
update = "2015/06/30 18:38"

[[entries]]
no = "3"
name = "はがね"
title = "Mirage Imitation"
size = "38388 KB"
addr = ["https://drive.google.com/file/d/0B8Buw0z19S9DM3lKbHpCRFZnN1E/view?usp=sharing"]
genre = "Progressive"
impr = "94"
total = "445"
median = "5"
avg = "4.73"
regist = "2015/06/01 00:03"
update = "2015/06/29 00:34"

[[entries]]
no = "4"
name = "Re:gats&"
title = "Lucid Quartz"
size = "31309 KB"
addr = ["https://www.dropbox.com/s/pxwbrmfhb8lecq4/%5BRegats_and%5DLucid%20Quartz.zip?dl=0"]
genre = "Progressive House"
impr = "63"
total = "274"
median = "4"
avg = "4.34"
regist = "2015/06/01 00:03"
update = "2015/06/28 23:55"

[[entries]]
no = "5"
name = "SM-NX"
title = "過去の幸福"
size = "17446 KB"
addr = ["https://dl.dropboxusercontent.com/s/h573lcxcz011pig/sm-nx_kouhuku.zip"]
genre = "ambient"
impr = "48"
total = "155"
median = "3"
avg = "3.22"
regist = "2015/06/01 00:06"
update = "2015/07/27 02:25"

[[entries]]
no = "6"
name = "NA7"
title = "Srutr"
size = "52875 KB"
addr = ["https://drive.google.com/open?id=0B0cIMin-PyHXdFprT0RvZXp2WUU&authuser=0"]
genre = "WorldEnd Core"
impr = "46"
total = "137"
median = "3"
avg = "2.97"
regist = "2015/06/01 00:14"
update = "2015/06/28 23:52"

[[entries]]
no = "7"
name = "tanacoro"
title = "Q"
size = "55347 KB"
addr = [
    "http://www1.axfc.net/u/3477859",
    "(変更がありました。6/1以前にDLされた方は再度DLを推奨します。)",
    "追加差分譜面はコメント欄のリンクから",
]
genre = "electro trance"
impr = "79"
total = "349"
median = "5"
avg = "4.41"
regist = "2015/06/01 00:20"
update = "2015/09/18 17:24"

[[entries]]
no = "8"
name = "すてらべえ"
title = "Upside-down"
size = "55000 KB"
addr = ["https://www.dropbox.com/s/wov3knjimbiwqnc/Stellabee%20Upside-down%20%5Bogg%5D.zip?dl=1"]
genre = "Breakcore / Cutbreak"
impr = "51"
total = "200"
median = "4"
avg = "3.92"
regist = "2015/06/01 00:54"
update = "2015/06/28 23:59"

[[entries]]
no = "9"
name = "Velpion"
title = "Climaxx Plan from Anonymous"
size = "4710 KB"
addr = [
    "BMSファイル：",
    "https://docs.google.com/uc?authuser=0&id=0B2dL_bSQHreWRWZ5eTdhSWJzVjQ&export=download",
    "ビギナー譜面：",
    "https://docs.google.com/uc?authuser=0&id=0B2dL_bSQHreWLUlydjJuTmtodEk&export=download",
]
genre = "HAPPY GABBA / SPEED CORE"
impr = "47"
total = "99"
median = "2"
avg = "2.1"
regist = "2015/06/01 01:21"
update = "2015/06/29 03:19"

[[entries]]
no = "10"
name = "Lemon beads"
title = "街に色づく夕陽のヒカリ -celestial sprite florist-"
size = "9146 KB"
addr = ["https://www.dropbox.com/s/htw6t0ch1oubq2k/lemon_florist_ogg.zip?dl=0"]
genre = "shuffle pop'n"
impr = "58"
total = "247"
median = "4"
avg = "4.25"
regist = "2015/06/01 01:33"
update = "2015/10/23 18:44"

[[entries]]
no = "11"
name = "Glit"
title = "Cheap-Crystal"
size = "15500 KB"
addr = [
    "http://www1.axfc.net/u/3477421",
    "https://www.dropbox.com/s/hb83r38yb4pji1k/C.Crystal_ogg.zip?dl=0",
]
genre = "HAPPYHARDCORE"
impr = "44"
total = "151"
median = "3"
avg = "3.43"
regist = "2015/06/01 02:06"
update = "2015/06/28 23:39"

[[entries]]
no = "12"
name = "apca*"
title = "- Galaxy Blade -"
size = "78188 KB"
addr = [
    "https://www.dropbox.com/s/rmby337qi4zsiws/-%20Galaxy%20Blade%20-%20ot.zip?dl=0",
    "(TOTAL値修正済)",
]
genre = "ART CORE"
impr = "62"
total = "241"
median = "4"
avg = "3.88"
regist = "2015/06/01 09:35"
update = "2015/06/28 23:53"

[[entries]]
no = "13"
name = "L.M."
title = "stardust carnival"
size = "12320 KB"
addr = ["http://www1.axfc.net/u/3477530.zip"]
genre = "Hi-Speed Galaxy Core"
impr = "42"
total = "162"
median = "4"
avg = "3.85"
regist = "2015/06/01 13:09"
update = "2015/06/28 23:52"

[[entries]]
no = "14"
name = "Sena"
title = "Life Destructor"
size = "39746 KB"
addr = [
    "https://www.dropbox.com/s/0twis549aimlp8v/Life_Destructor.zip?dl=1",
    "http://www1.axfc.net/u/3477575",
]
genre = "Hard Core"
impr = "53"
total = "227"
median = "4"
avg = "4.28"
regist = "2015/06/01 16:12"
update = "2015/07/01 15:19"

[[entries]]
no = "15"
name = "yuyuyu"
title = "night seeker"
size = "27600 KB"
addr = ["https://www.dropbox.com/s/qydg3u7iqk8nrb0/night%2Bseeker_ogg.zip?dl=0"]
genre = "Trance"
impr = "43"
total = "167"
median = "4"
avg = "3.88"
regist = "2015/06/01 21:37"
update = "2015/06/28 23:48"

[[entries]]
no = "16"
name = "M+C/S"
title = "Traumwelt ~Last Moment des Schlafes~"
size = "18272 KB"
addr = ["http://www.dropbox.com/s/0suu00l6hndgaov/Traumwelt.zip?dl=0"]
genre = "Piano instrumental"
impr = "47"
total = "155"
median = "3"
avg = "3.29"
regist = "2015/06/01 23:28"
update = "2015/07/22 22:16"

[[entries]]
no = "17"
name = ".k"
title = "新しいフォルダー「.white」"
size = "70000 KB"
addr = ["https://dl.dropboxusercontent.com/u/29574774/%E6%96%B0%E3%81%97%E3%81%84%E3%83%95%E3%82%A9%E3%83%AB%E3%83%80%E3%83%BC%E3%80%8C.white%E3%80%8D.zip"]
genre = "Progressive_House"
impr = "55"
total = "139"
median = "2"
avg = "2.52"
regist = "2015/06/02 00:43"
update = "2015/06/28 23:57"

[[entries]]
no = "18"
name = "琥珀"
title = "Dahlia"
size = "80000 KB"
addr = ["https://docs.google.com/uc?id=0B2vgozUinbQBZERfTkZjeVVQTlU&export=download"]
genre = "UK Hardcore"
impr = "45"
total = "158"
median = "3"
avg = "3.51"
regist = "2015/06/02 20:38"
update = "2015/06/28 23:56"

[[entries]]
no = "19"
name = "FTA"
title = "IRIS_DREAMER"
size = "65940 KB"
addr = ["https://www.dropbox.com/s/nhnqkxty2fhbbdv/IRISDREAMERver1.1.zip?dl=0"]
genre = "HAPPY_CORE"
impr = "46"
total = "150"
median = "3"
avg = "3.26"
regist = "2015/06/02 23:36"
update = "2015/06/28 23:44"

[[entries]]
no = "20"
name = "minter"
title = "blue star"
size = "18530 KB"
addr = ["https://www.dropbox.com/s/pvvlvadzlepjzzo/blst_ogg.zip?dl=0"]
genre = "LIFETRANCE"
impr = "50"
total = "181"
median = "4"
avg = "3.62"
regist = "2015/06/02 23:55"
update = "2015/06/28 23:41"

[[entries]]
no = "21"
name = "Orphex"
title = "Lumiere"
size = "22700 KB"
addr = ["https://www.dropbox.com/s/d44bl23noowgxag/Lumiere.zip?dl=1"]
genre = "Mainstream Hardcore"
impr = "49"
total = "223"
median = "5"
avg = "4.55"
regist = "2015/06/03 03:27"
update = "2015/06/28 23:47"

[[entries]]
no = "22"
name = "おみー"
title = "白い星光-Свет белой звезды-"
size = "82534 KB"
addr = ["https://www.dropbox.com/s/2wnpq7ydp91520l/%D0%A1%D0%B2%D0%B5%D1%82%20%D0%B1%D0%B5%D0%BB%D0%BE%D0%B9%20%D0%B7%D0%B2%D0%B5%D0%B7%D0%B4%D1%8B.zip?dl=0"]
genre = "SYMPHONIC SCHRANZ"
impr = "61"
total = "275"
median = "5"
avg = "4.5"
regist = "2015/06/03 22:15"
update = "2015/06/28 23:57"

[[entries]]
no = "23"
name = "HALLPBESTUDIO"
title = "Apostle"
size = "14748 KB"
addr = ["https://www.dropbox.com/s/bee2ggw4crvjt7y/Apostle.zip?dl=0"]
genre = "Industrial"
impr = "51"
total = "182"
median = "4"
avg = "3.56"
regist = "2015/06/04 20:18"
update = "2015/06/28 23:42"

[[entries]]
no = "24"
name = "mossari"
title = "Le Reve"
size = "58000 KB"
addr = [
    "https://dl.dropboxusercontent.com/u/59367462/Le%20Reve.rar",
    "http://www1.axfc.net/u/3479719",
    "https://dl.dropboxusercontent.com/u/59367462/sabun.rar",
    "TOTAL値の入力ミスの修正差分です。TOTAL値が空になっていた方はこちらのbmsファイルに差し替えてください。",
]
genre = "Neon"
impr = "105"
total = "520"
median = "5"
avg = "4.95"
regist = "2015/06/04 23:33"
update = "2015/06/28 23:59"

[[entries]]
no = "25"
name = "風上ユウオン"
title = "暁の星"
size = "77861 KB"
addr = ["https://www.dropbox.com/s/u8oblkr1ozyxpc4/akatsuki3.zip?dl=0"]
genre = "LOST FANTASIA"
impr = "53"
total = "216"
median = "4"
avg = "4.07"
regist = "2015/06/05 02:00"
update = "2015/07/07 16:43"

[[entries]]
no = "26"
name = "HUYU"
title = "season or truth"
size = "89949 KB"
addr = ["https://www.dropbox.com/s/aenzbblvu7t1moj/season%20or%20truth.7z?dl=0"]
genre = "90's pops rock"
impr = "39"
total = "100"
median = "3"
avg = "2.56"
regist = "2015/06/05 22:06"
update = "2015/06/28 23:51"

[[entries]]
no = "27"
name = "海秋"
title = "星の海に照らされて"
size = "39000 KB"
addr = ["http://seapulse.net/sakuzyokinsi/mumeisen12/Hoshinouminiterasarete.zip"]
genre = "Short story"
impr = "54"
total = "219"
median = "4"
avg = "4.05"
regist = "2015/06/06 21:28"
update = "2015/06/28 23:57"

[[entries]]
no = "28"
name = "mrt"
title = "outbreak"
size = "8664 KB"
addr = ["http://www1.axfc.net/u/3481349"]
genre = "PROGRESSIVE ROCK / FUSION"
impr = "40"
total = "149"
median = "4"
avg = "3.72"
regist = "2015/06/06 21:28"
update = "2015/06/28 23:49"

[[entries]]
no = "29"
name = "BJ.chika"
title = "OUTmaneuVER"
size = "41986 KB"
addr = ["https://www.dropbox.com/s/3tac41yvq5524z7/%5BBJ_chika%5DOUTmaneuVER.zip?dl=0"]
genre = "TRANCESTEP"
impr = "42"
total = "156"
median = "4"
avg = "3.71"
regist = "2015/06/06 22:47"
update = "2015/06/28 23:59"

[[entries]]
no = "30"
name = "Renpul"
title = "Detour"
size = "42291 KB"
addr = ["https://www.dropbox.com/s/l3hkocggrwkek61/%5BRenpul%5DDetour.rar?dl=1"]
genre = "Glitch hop"
impr = "61"
total = "242"
median = "4"
avg = "3.96"
regist = "2015/06/06 22:56"
update = "2015/06/29 01:55"

[[entries]]
no = "31"
name = "5argon vs encX (obj:flicknote)"
title = "Exargon"
size = "55736 KB"
addr = [
    "Dropbox",
    "https://dl.dropboxusercontent.com/u/25097375/BMS/2015/%5B5argon_vs_encx%5Dexargon.zip",
    "Mirror",
    "http://flicknote.bemuse.ninja/bms/2015/",
    "[5argon_vs_encX]Exargon.zip",
    "(md5 56c0733f2ff07eb9b7c052a9a5175f63)",
]
genre = "DnB"
impr = "71"
total = "296"
median = "4"
avg = "4.16"
regist = "2015/06/07 03:51"
update = "2015/06/28 23:55"

[[entries]]
no = "32"
name = "みゃーかい"
title = "sognare"
size = "5794 KB"
addr = ["https://www.dropbox.com/s/rin4uivnav4tezq/%5B%E3%81%BF%E3%82%83%E3%83%BC%E3%81%8B%E3%81%84%5Dsognare.zip?dl=0"]
genre = "創作"
impr = "39"
total = "106"
median = "3"
avg = "2.71"
regist = "2015/06/07 18:06"
update = "2015/06/28 23:52"

[[entries]]
no = "33"
name = "emulu"
title = "STAR DUSTING COASTER"
size = "67539 KB"
addr = ["https://www.dropbox.com/s/sqybkuwq1ol1078/%5Bemulu%5DS_D_COASTER_wav.zip?dl=0"]
genre = "Trancecore"
impr = "37"
total = "112"
median = "3"
avg = "3.02"
regist = "2015/06/07 18:59"
update = "2015/06/28 23:52"

[[entries]]
no = "34"
name = "kumorin"
title = "Ruins"
size = "20400 KB"
addr = ["https://www.dropbox.com/s/92ca11m0wc184v8/Ruins_ogg.rar?dl=1"]
genre = "house"
impr = "39"
total = "130"
median = "3"
avg = "3.33"
regist = "2015/06/07 19:20"
update = "2015/06/28 23:51"

[[entries]]
no = "35"
name = "dj.a meets TEA"
title = "hello,again."
size = "20 KB"
addr = ["https://www.dropbox.com/s/irddxt9ns85cb4l/hello%2Cagain.rar?raw=1"]
genre = "POP MUSIC"
impr = "51"
total = "169"
median = "3"
avg = "3.31"
regist = "2015/06/07 21:34"
update = "2015/06/28 23:55"

[[entries]]
no = "36"
name = "sky I"
title = "不知火"
size = "26533 KB"
addr = [
    "フルver(ogg)(SPA含む)",
    "https://www.dropbox.com/s/2wiscqxmmu5o7ul/shiranui%28ogg%29.rar?dl=0",
    "SPA譜面のみのDL:",
    "https://www.dropbox.com/s/ok61v1qr7txhb3t/1data%28Another%29.bms?dl=0",
]
genre = "Oriental Epic"
impr = "54"
total = "241"
median = "5"
avg = "4.46"
regist = "2015/06/07 21:48"
update = "2015/06/28 23:59"

[[entries]]
no = "37"
name = "TKR"
title = "A-Y-B"
size = "10158 KB"
addr = ["http://www1.axfc.net/u/3481427.zip"]
genre = "DEEP TECHNO"
impr = "49"
total = "178"
median = "4"
avg = "3.63"
regist = "2015/06/07 22:14"
update = "2015/06/28 23:47"

[[entries]]
no = "38"
name = "69 de 74"
title = "Overflowing Power"
size = "23683 KB"
addr = ["https://www.dropbox.com/s/s7fccgrgrvr4byn/%5B69%20de%2074%5DOverflowing%20Power.zip?dl=1"]
genre = "UK HARDCORE"
impr = "46"
total = "180"
median = "4"
avg = "3.91"
regist = "2015/06/07 22:25"
update = "2020/05/31 10:04"

[[entries]]
no = "39"
name = "sukuramu42"
title = "Exploring the blue sky"
size = "15700 KB"
addr = ["https://www.dropbox.com/s/8yvopo10ou0t34h/Exploring%20the%20Blue%20sky.rar?dl=1"]
genre = "Trance"
impr = "85"
total = "382"
median = "5"
avg = "4.49"
regist = "2015/06/07 22:36"
update = "2022/05/24 22:02"

[[entries]]
no = "40"
name = "Ra E-Li"
title = "腕二本"
size = "36603 KB"
addr = ["https://www.dropbox.com/s/hdq7lfns0aptqem/%5BRa%20E-Li%5D%20udenihon_bms_.zip?dl=0"]
genre = "Piano Progressive"
impr = "54"
total = "228"
median = "4"
avg = "4.22"
regist = "2015/06/07 23:01"
update = "2015/06/28 23:58"

[[entries]]
no = "41"
name = "mak4026"
title = "D0nt Sink Feer"
size = "32074 KB"
addr = ["https://docs.google.com/uc?id=0BzF6Mf0lcB60aFZKN0lkY1o0dVU&export=download"]
genre = "HAPPYHARDCORE"
impr = "43"
total = "156"
median = "4"
avg = "3.62"
regist = "2015/06/07 23:03"
update = "2015/06/28 23:48"

[[entries]]
no = "42"
name = "FIG"
title = "悠奏線上のアスタルテ"
size = "59802 KB"
addr = ["https://www.dropbox.com/s/elxczu4t17wo64o/%E6%82%A0%E5%A5%8F%E7%B7%9A%E4%B8%8A%E3%81%AE%E3%82%A2%E3%82%B9%E3%82%BF%E3%83%AB%E3%83%86.zip?dl=0"]
genre = "LOST PIECE NOCTURNE"
impr = "67"
total = "315"
median = "5"
avg = "4.7"
regist = "2015/06/07 23:34"
update = "2015/07/26 18:56"

[[entries]]
no = "43"
name = "SHIONY"
title = "Skyscraper"
size = "13320 KB"
addr = [
    "https://www.dropbox.com/s/68r7cysf6sbkg5s/Skycraper.rar?dl=0",
    "https://www.dropbox.com/s/h9ke0fltw3clsya/Skyscraper_sabun.rar?dl=0",
]
genre = "DnB"
impr = "44"
total = "163"
median = "4"
avg = "3.7"
regist = "2015/06/07 23:41"
update = "2015/06/28 23:58"

[[entries]]
no = "44"
name = "Takeshita"
title = "ViViDNESS"
size = "8400 KB"
addr = ["---"]
genre = "Breakcore / Mashcore / Lolicore"
impr = "63"
total = "250"
median = "4"
avg = "3.96"
regist = "2015/06/07 23:43"
update = "2016/06/07 02:51"

[[entries]]
no = "45"
name = "hyneq"
title = "Ape Maniax"
size = "46000 KB"
addr = ["http://www1.axfc.net/u/3481576"]
genre = "HARDTEK (RUNESSANCE)"
impr = "45"
total = "125"
median = "3"
avg = "2.77"
regist = "2015/06/07 23:57"
update = "2015/07/10 01:33"

[[entries]]
no = "46"
name = "C_N-extage"
title = "Glidin' in the sky (for BMS edit.)"
size = "11600 KB"
addr = [
    "↓.wav版",
    "http://u999u.info/lApg",
    "↓.ogg版",
    "http://u999u.info/lApd",
    "Dropboxにアップしているため、",
    "鯖落ちか何かでDLできない現象が発生している事がございます。",
    "現在公開されている全曲パッケージと内容は同一ですので(.ogg版)",
    ".wav形式で落としたい場合は時間を空けていただくか",
    "再度御アクセスください。お手数おかけします。",
    "(イベント終了直後にさりげなく追加データが入りますがまぁ、アレです",
]
genre = "BALEARIC BEATS"
impr = "41"
total = "146"
median = "4"
avg = "3.56"
regist = "2015/06/07 23:59"
update = "2015/06/29 14:49"

[[entries]]
no = "47"
name = "fffff"
title = "THE Crystal"
size = "76279 KB"
addr = [
    "The crystal.zip,",
    "http://www1.axfc.net/u/3481565",
]
genre = "synth"
impr = "43"
total = "165"
median = "4"
avg = "3.83"
regist = "2015/06/07 23:59"
update = "2015/06/28 23:56"

[[entries]]
no = "48"
name = "dosugoge"
title = "街商セレモニー"
size = "40190 KB"
addr = [
    "https://www.dropbox.com/s/0z3lxkfwnxjdxz5/%5Bdosugoge%5Dmati-ceremony_v2.zip?dl=0",
    "（パッケージ版をプレイされた方は上書き推奨です）",
]
genre = "RHYTHMIC POPS"
impr = "41"
total = "102"
median = "2"
avg = "2.48"
regist = "2015/06/07 23:59"
update = "2015/08/10 19:24"

[[entries]]
no = "49"
name = "すとろ～"
title = "Lunar base(BMS Edit)"
size = "58520 KB"
addr = ["https://www.dropbox.com/s/fvt1ew03lsnb1v9/Lunar%20base%28BMS%20Edit%29.zip?dl=0"]
genre = "Psychedelic trance"
impr = "45"
total = "155"
median = "3"
avg = "3.44"
regist = "2015/06/08 00:01"
update = "2015/06/29 02:53"

[[entries]]
no = "50"
name = "Myshrd"
title = "AMEZING SCRATCHI!!"
size = "84400 KB"
addr = ["-"]
genre = "SCRATCHI"
impr = "52"
total = "136"
median = "3"
avg = "2.61"
regist = "2015/06/08 00:04"
update = "2016/03/29 19:53"
