[[entries]]
no = "1"
name = "Kanata.S"
title = "Hybrid rabbit"
size = "5746 KB"
addr = ["https://www.dropbox.com/s/bt4gieqkoh8c9x4/hybrid%20rabbit.zip?dl=0"]
genre = "Hands Up"
impr = "28"
total = "197"
median = "7"
avg = "7.03"
regist = "2015/07/03 00:00"
update = "2015/07/26 23:44"

[[entries]]
no = "2"
name = "YUKI"
title = "QUARTZ"
size = "36000 KB"
addr = ["http://xexex-musiq.org/yuki_quartz.zip"]
genre = "electro"
impr = "24"
total = "186"
median = "8"
avg = "7.75"
regist = "2015/07/03 00:01"
update = "2015/08/28 10:48"

[[entries]]
no = "3"
name = "ROKINA"
title = "Reinforced Soul"
size = "10701 KB"
addr = ["https://dl.dropboxusercontent.com/s/dl0e7o24osweupi/LNB56-reinforced.rar"]
genre = "HARD BREAKS"
impr = "31"
total = "264"
median = "9"
avg = "8.51"
regist = "2015/07/03 00:01"
update = "2020/06/11 23:43"

[[entries]]
no = "4"
name = "momo★yama"
title = "JUMMER"
size = "34513 KB"
addr = [
    "https://dl.dropboxusercontent.com/u/59483835/BMS/JUMMER.rar",
    "https://dl.dropboxusercontent.com/u/59483835/BMS/JUMMER_bga.rar",
    "(高画質BGA差分)",
]
genre = "ENERGETIC TRANCE"
impr = "25"
total = "180"
median = "7"
avg = "7.2"
regist = "2015/07/03 00:01"
update = "2015/07/26 23:45"

[[entries]]
no = "5"
name = "Neun_jack"
title = "Chatter Growl"
size = "10855 KB"
addr = ["http://dl.dropboxusercontent.com/u/60346274/Neunjack/Neun_jack-Chatter_growl_ogg.zip"]
genre = "Hardtek / Darkstep"
impr = "26"
total = "186"
median = "7"
avg = "7.15"
regist = "2015/07/03 00:01"
update = "2015/07/26 23:57"

[[entries]]
no = "6"
name = "litmus*"
title = "Urban Nights"
size = "10495 KB"
addr = ["https://drive.google.com/file/d/0B0a6-fXyD9ZEZXNESDJpalcyUVU/view?usp=sharing"]
genre = "Progressive House"
impr = "32"
total = "249"
median = "8"
avg = "7.78"
regist = "2015/07/03 00:02"
update = "2015/07/26 23:45"

[[entries]]
no = "7"
name = "うまるつふり"
title = "月花"
size = "32767 KB"
addr = ["http://1drv.ms/1HxyXTi"]
genre = "夜天"
impr = "23"
total = "162"
median = "7"
avg = "7.04"
regist = "2015/07/03 00:03"
update = "2015/07/26 23:55"

[[entries]]
no = "8"
name = "Warp-E / BURST"
title = "New Island (Feat. Ruriling)"
size = "17111 KB"
addr = ["https://drive.google.com/file/d/0BzpImzMWXQ46Nm5tZXFrVk5hek0/view?usp=sharing"]
genre = "Epic Trance"
impr = "32"
total = "237"
median = "8"
avg = "7.4"
regist = "2015/07/03 00:04"
update = "2015/07/26 23:56"

[[entries]]
no = "9"
name = "q/stol"
title = "UNITARY BONDS"
size = "41755 KB"
addr = ["https://www.dropbox.com/s/2qe0gqyh8hpy0b2/unitary_bonds_ogg.zip?dl=1"]
genre = "EDM"
impr = "45"
total = "387"
median = "9"
avg = "8.6"
regist = "2015/07/03 00:04"
update = "2015/07/26 23:53"

[[entries]]
no = "10"
name = "Centain"
title = "PROGRESS"
size = "11925 KB"
addr = ["http://docs.google.com/uc?id=0B_ACOCjd9IgBUENBbnA2Vk1INFk"]
genre = "EUROBEAT"
impr = "19"
total = "130"
median = "7"
avg = "6.84"
regist = "2015/07/03 00:04"
update = "2015/07/26 23:31"

[[entries]]
no = "11"
name = "有栖川 悠"
title = "Necromancer"
size = "29874 KB"
addr = ["http://1drv.ms/1GQ5Jvk"]
genre = "HARDCORE RAVE"
impr = "19"
total = "116"
median = "6"
avg = "6.1"
regist = "2015/07/03 00:07"
update = "2015/07/26 23:58"

[[entries]]
no = "12"
name = "KV.S"
title = "おもちゃのバンド隊"
size = "9597 KB"
addr = ["https://www.dropbox.com/s/1zl35spr2rlktu6/omocha_no_bandtai.zip?dl=0"]
genre = "Kiddy Jazz"
impr = "25"
total = "188"
median = "8"
avg = "7.52"
regist = "2015/07/03 00:13"
update = "2015/07/27 23:13"

[[entries]]
no = "13"
name = "Kanata.S"
title = "Shade and Nowhere"
size = "8892 KB"
addr = ["https://www.dropbox.com/s/5vrlfwtqnmal5pd/Shade%20and%20Nowhere.zip?dl=0"]
genre = "Trap"
impr = "22"
total = "133"
median = "6"
avg = "6.04"
regist = "2015/07/03 00:13"
update = "2015/07/26 23:58"

[[entries]]
no = "14"
name = "アクジ"
title = "Fun GABBAKICK"
size = "1007 KB"
addr = ["https://dl.dropboxusercontent.com/u/272956039/Fun%20GABBAKICK.zip"]
genre = "たのしいガバキック"
impr = "35"
total = "253"
median = "7"
avg = "7.22"
regist = "2015/07/03 00:19"
update = "2015/07/26 23:46"

[[entries]]
no = "15"
name = "ドルフィン"
title = "Minute"
size = "7680 KB"
addr = ["https://dl.dropboxusercontent.com/u/50992731/BMS%20Original/Minute_ogg.rar"]
genre = "Piano"
impr = "26"
total = "166"
median = "6"
avg = "6.38"
regist = "2015/07/03 00:26"
update = "2015/07/26 23:49"

[[entries]]
no = "16"
name = "Flont Twiright"
title = "False Friend"
size = "10723 KB"
addr = ["https://docs.google.com/uc?export=download&confirm=nNC6&id=0BziXTzOf-9oTQmV5aHhOb0tIeGc"]
genre = "FRENCHCORE"
impr = "31"
total = "271"
median = "9"
avg = "8.74"
regist = "2015/07/03 00:39"
update = "2015/07/27 00:00"

[[entries]]
no = "17"
name = "kyan"
title = "Machinarhythm"
size = "4570 KB"
addr = ["https://dl.dropboxusercontent.com/u/95928342/Machinarhythm_ogg.rar"]
genre = "Tech House"
impr = "15"
total = "61"
median = "4"
avg = "4.06"
regist = "2015/07/03 15:27"
update = "2015/07/26 23:51"

[[entries]]
no = "18"
name = "NONE"
title = "Sogaikan Utopia"
size = "54426 KB"
addr = ["http://1drv.ms/1R9xhpv"]
genre = "Drum&Bass"
impr = "34"
total = "289"
median = "9"
avg = "8.5"
regist = "2015/07/03 20:05"
update = "2015/07/26 23:55"

[[entries]]
no = "19"
name = "Qga"
title = "banquet"
size = "35419 KB"
addr = ["https://www.dropbox.com/s/s9nhrenqsl3t4hg/banquet.zip?dl=0"]
genre = "schranz"
impr = "22"
total = "144"
median = "7"
avg = "6.54"
regist = "2015/07/04 00:24"
update = "2015/07/26 23:54"

[[entries]]
no = "20"
name = "Sho Fish"
title = "Cut The Fiber"
size = "14404 KB"
addr = ["http://www.mediafire.com/download/9aeugj1zg81iu32/Sho_Fish_-_Cut_The_Fiber-ogg.zip"]
genre = "Tribecore"
impr = "32"
total = "240"
median = "8"
avg = "7.5"
regist = "2015/07/04 11:49"
update = "2015/07/27 02:11"

[[entries]]
no = "21"
name = "q/stol"
title = "Skeptical"
size = "25838 KB"
addr = ["https://www.dropbox.com/s/0qmat4lyykrhmuq/Skeptical_ogg.zip?dl=1"]
genre = "Trap"
impr = "28"
total = "219"
median = "8"
avg = "7.82"
regist = "2015/07/04 13:52"
update = "2015/07/26 23:57"

[[entries]]
no = "22"
name = "竜。 feat.さとうささら lyrics.まさゆき"
title = "キャラメルポップ"
size = "71400 KB"
addr = [
    "wav 58.3MB",
    "https://goo.gl/8AQSvK",
    "ogg 13.1MB",
    "https://goo.gl/gzMLCJ",
]
genre = "Sweet Euro Beat"
impr = "24"
total = "170"
median = "7"
avg = "7.08"
regist = "2015/07/04 14:36"
update = "2015/07/27 23:28"

[[entries]]
no = "23"
name = "TiS feat.紅梔子"
title = "Starry Fate"
size = "49894 KB"
addr = ["http://cineraria-studio.com/?page_id=53"]
genre = "EUROBEAT"
impr = "45"
total = "425"
median = "10"
avg = "9.44"
regist = "2015/07/04 18:11"
update = "2015/11/04 14:05"

[[entries]]
no = "24"
name = "Bit Upper"
title = "tenisu"
size = "3890 KB"
addr = [
    "http://uprdeco.littlestar.jp/tenisu_ogg.rar",
    "-------------------",
    "追加差分",
    "http://uprdeco.littlestar.jp/tenisu_sabun.rar",
    "（NORMAL・ANOTHER差分）",
    "http://uprdeco.littlestar.jp/tenisu_ogg_sabuninclude.rar",
    "（NORMAL・ANOTHER差分含みアーカイブ）",
]
genre = "HARD RAVE"
impr = "21"
total = "150"
median = "8"
avg = "7.14"
regist = "2015/07/04 18:51"
update = "2015/07/26 23:58"

[[entries]]
no = "25"
name = "Ym1024 feat. lamie*"
title = "sweet pop"
size = "6048 KB"
addr = ["http://yellowmapleleaf.com/bms/ym45_sweet_ogg.rar"]
genre = "J-Happy Pop Core"
impr = "39"
total = "325"
median = "9"
avg = "8.33"
regist = "2015/07/04 22:44"
update = "2015/07/26 23:59"

[[entries]]
no = "26"
name = "ぜらにも"
title = "wakewalk"
size = "5442 KB"
addr = ["https://www.dropbox.com/s/391562ebh2i9umy/%21nongenre_wakewalk.lzh?dl=1"]
genre = "Liquid Funk"
impr = "21"
total = "145"
median = "7"
avg = "6.9"
regist = "2015/07/04 23:23"
update = "2015/07/26 23:57"

[[entries]]
no = "27"
name = "コーヒー"
title = "Dusk"
size = "34831 KB"
addr = ["https://dl.dropboxusercontent.com/s/om3zyg90wea02a2/dusk_dist.zip?dl=1"]
genre = "DRUM & BASS"
impr = "22"
total = "144"
median = "7"
avg = "6.54"
regist = "2015/07/05 02:13"
update = "2015/07/28 00:40"

[[entries]]
no = "28"
name = "Sora Akegami"
title = "Humexam"
size = "11054 KB"
addr = [
    "http://1drv.ms/1JKGHDN",
    "(onedrive)",
]
genre = "Drumstep"
impr = "19"
total = "132"
median = "7"
avg = "6.94"
regist = "2015/07/05 13:26"
update = "2015/07/26 23:59"

[[entries]]
no = "29"
name = "suna"
title = "Cheesy Mouse"
size = "8355 KB"
addr = ["https://mega.nz/#F!IP4iTAyI!jkwvNbkccH-EUATbGI4SWg"]
genre = "CLICK HOUSE"
impr = "28"
total = "217"
median = "8"
avg = "7.75"
regist = "2015/07/05 17:50"
update = "2018/05/03 00:09"

[[entries]]
no = "30"
name = "gmtn."
title = "LL3C"
size = "48131 KB"
addr = ["http://gmtn.sub.jp/_carage_LL3C_ogg.zip"]
genre = "TRANCE"
impr = "25"
total = "192"
median = "8"
avg = "7.68"
regist = "2015/07/05 21:46"
update = "2015/07/26 23:56"

[[entries]]
no = "31"
name = "Lime"
title = "Gleam of Aigis"
size = "42000 KB"
addr = [
    "ogg:",
    "http://www.land3939.info/lime_gleam_of_aigis_ogg.zip",
    "(追加譜面同梱済)",
    "(wav版は少々お待ちください)",
    "追加譜面:",
    "http://www.land3939.info/lime_gleam_of_aigis_app.zip",
    "(07/07 7:00以前にダウンロードされた方のみ、こちらのファイルを落として頂いてBMSフォルダに入れて頂ければ嬉しいです。)",
]
genre = "Hardcore"
impr = "30"
total = "258"
median = "9"
avg = "8.6"
regist = "2015/07/05 22:11"
update = "2015/07/26 23:56"

[[entries]]
no = "32"
name = "dj koishi"
title = "yph sonic!"
size = "2977 KB"
addr = ["https://www.dropbox.com/s/dunxkdcl1954ouk/yph%20sonic%21.zip?dl=0"]
genre = "Rotterdam"
impr = "22"
total = "109"
median = "5.5"
avg = "4.95"
regist = "2015/07/05 22:50"
update = "2015/07/26 23:58"

[[entries]]
no = "33"
name = "SM-NX"
title = "good bye my origin"
size = "783 KB"
addr = ["https://dl.dropboxusercontent.com/s/vabkxayx2wsrn4x/sm-nx_good_bye_my_origin.zip"]
genre = "-"
impr = "14"
total = "63"
median = "4.5"
avg = "4.5"
regist = "2015/07/05 22:59"
update = "2015/07/27 02:25"

[[entries]]
no = "34"
name = "Yosk!"
title = "Hot Jupiter"
size = "21154 KB"
addr = ["https://drive.google.com/open?id=0B7qCw4hNijr4My1qbzkwdFZFMVE"]
genre = "MORNING"
impr = "22"
total = "173"
median = "8"
avg = "7.86"
regist = "2015/07/05 23:50"
update = "2018/02/14 04:14"

[[entries]]
no = "35"
name = "dosugoge"
title = "Rewind -out of my monitor-"
size = "90360 KB"
addr = [
    "HQwav版：",
    "https://www.dropbox.com/s/1flimt2ljxrjl34/%5Bdosugoge%5Drewind_HQwav.zip?dl=0",
    "（パッケージ版との変更点：一部ノイズ削除、テキスト上書）",
    "LQwav版：",
    "https://www.dropbox.com/s/c2ka4dpp946vzsn/%5Bdosugoge%5Drewind_LQwav.zip?dl=0",
]
genre = "Unexpected"
impr = "29"
total = "208"
median = "7"
avg = "7.17"
regist = "2015/07/05 23:51"
update = "2015/08/26 01:20"

[[entries]]
no = "36"
name = "wosderge"
title = "Dear, my canvas."
size = "1945 KB"
addr = ["http://nullpoarchives.orz.hm/uploader2/upload_dat/FILE641.zip"]
genre = "TRANCE"
impr = "29"
total = "146"
median = "5"
avg = "5.03"
regist = "2015/07/05 23:53"
update = "2015/07/26 23:59"

[[entries]]
no = "37"
name = "wosderge remixed by LU"
title = "HASCORALGUN(remix)"
size = "28491 KB"
addr = ["http://gensoukyousoukyoku.nekokan.dyndns.info/8-wosderge_remixed_by_LU-HASCORALGUN.rar"]
genre = "HARD DNB MIX"
impr = "35"
total = "274"
median = "8"
avg = "7.82"
regist = "2015/07/05 23:55"
update = "2015/07/26 23:52"

[[entries]]
no = "38"
name = "die_oggend_son"
title = "CAUTION;"
size = "6051 KB"
addr = ["http://dl.dropboxusercontent.com/s/2i4488cem3lp2vt/cautionbms.rar?dl=0"]
genre = "DRUM'N'BASS"
impr = "21"
total = "112"
median = "6"
avg = "5.33"
regist = "2015/07/05 23:58"
update = "2015/07/27 18:40"
