[[entries]]
no = "1"
name = "UPnknown Artist"
title = "BOFOON0人"
size = "9900 KB"
addr = ["https://dl.dropboxusercontent.com/s/o7gplzy0buiiq7r/youtuber_foon.rar?dl=0"]
genre = "-"
impr = "17"
total = "16"
median = "0"
avg = "0.94"
regist = "2015/11/13 16:51"
update = "2015/11/29 23:28"

[[entries]]
no = "2"
name = "DJ Body_Kracker a.k.a B_K"
title = "よく使ってない身体部位で何でもしてみた"
size = "235 KB"
addr = ["https://www.dropbox.com/s/d6b825tzfsr353r/_body_to_music.zip?dl=1"]
genre = "Hi-Tech Body Style PERCUSSIVE"
impr = "16"
total = "16"
median = "1"
avg = "1"
regist = "2015/11/13 19:04"
update = "2015/11/30 19:06"

[[entries]]
no = "3"
name = "1000."
title = "四重ノーツ"
size = "50 KB"
addr = ["http://docs.google.com/uc?id=0B_ACOCjd9IgBZ3BkRFU0dWVLazg"]
genre = "kick"
impr = "19"
total = "17"
median = "1"
avg = "0.89"
regist = "2015/11/13 19:28"
update = "2015/11/30 23:32"

[[entries]]
no = "4"
name = "o(Yu^-^ta)o feat. 石油王 vs 愚民"
title = "Arabian 石油王 Night"
size = "6052 KB"
addr = ["https://www.dropbox.com/s/wit740ehdmlkarp/yuta_arabian.zip?dl=1"]
genre = "BOFU打ち上げ焼肉のノリ"
impr = "17"
total = "13"
median = "0"
avg = "0.76"
regist = "2015/11/13 21:37"
update = "2015/11/29 23:58"

[[entries]]
no = "5"
name = "DJ wsbmr"
title = "Cer"
size = "10 KB"
addr = [
    "http://drive.google.com/file/d/0B67PlzDLaernYTZPUV8tWGhhbVU/view",
    "ＩＩＤＸ風差分((o(*ﾟ▽ﾟ*)o))",
    "https://drive.google.com/file/d/0B67PlzDLaernTHlySFU0eFVCdlk/view",
]
genre = "Tek"
impr = "15"
total = "7"
median = "0"
avg = "0.46"
regist = "2015/11/13 22:21"
update = "2015/11/29 22:53"

[[entries]]
no = "6"
name = "NA7"
title = "DTMのイラストの男の子が打ちこんでいる曲（NA7 Remix）"
size = "16296 KB"
addr = ["https://drive.google.com/open?id=0B0cIMin-PyHXNHJodEdUdGZ6RkU"]
genre = "IRASUTOYA"
impr = "16"
total = "15"
median = "0"
avg = "0.93"
regist = "2015/11/13 22:36"
update = "2015/11/30 16:43"

[[entries]]
no = "7"
name = "車掌"
title = "人 身 事 故 で 停 止 －転 生 編－"
size = "1150 KB"
addr = ["http://www1.axfc.net/u/3566315"]
genre = "線路は続くよどこまでも"
impr = "17"
total = "17"
median = "0"
avg = "1"
regist = "2015/11/13 23:59"
update = "2015/11/29 21:49"

[[entries]]
no = "8"
name = "ああああ"
title = "おちんぽビーム"
size = "2540 KB"
addr = ["https://drive.google.com/file/d/0B8GwtzMj7C4gdzFIVFQzMTkyakk/view"]
genre = "ネオアームストロングサイクロンジェットアームストロング砲"
impr = "32"
total = "31"
median = "0"
avg = "0.96"
regist = "2015/11/14 00:40"
update = "2015/11/29 23:54"

[[entries]]
no = "9"
name = "litmus*"
title = "TEST YOUR LUCK (slot machine)"
size = "14465 KB"
addr = [
    "https://drive.google.com/file/d/0B0a6-fXyD9ZEajlTMG4wTjItb0U/view?usp=sharing",
    "(2015-11-17 Final BGM Updated)",
    "https://drive.google.com/file/d/0B0a6-fXyD9ZEZzNEZVdyYmdSM2s/view?usp=sharing",
    "(append pack)",
]
genre = "Casino"
impr = "17"
total = "17"
avg = "1"
regist = "2015/11/14 04:38"
update = "2015/11/29 23:34"

[[entries]]
no = "10"
name = "マードック博士"
title = "曲自体うろ覚えだし音感ないけど思い出しながらポップンツインビーのボス戦(ぶっとびたい方野郎どもに捧ぐ)～クリア時に流れるのをコピアレをする"
size = "1794 KB"
addr = ["https://dl.dropboxusercontent.com/s/kb3l40ztlq67xgf/popntwinurooboe.zip"]
genre = "うろ覚えコピアレ"
impr = "16"
total = "16"
median = "1"
avg = "1"
regist = "2015/11/14 18:40"
update = "2015/11/29 23:35"

[[entries]]
no = "11"
name = "普乳派"
title = "おっぱい"
size = "869 KB"
addr = ["https://dl.dropboxusercontent.com/u/91177583/BMS/oppai.zip"]
genre = "おっぱい"
impr = "17"
total = "17"
median = "0"
avg = "1"
regist = "2015/11/14 23:29"
update = "2015/11/29 21:38"

[[entries]]
no = "12"
name = "杭君 BGA：出前"
title = "杭チャレンジ"
size = "2459 KB"
addr = ["https://www.dropbox.com/s/94bszs48vjgr7n4/kusokui.rar?dl=0"]
genre = "クソゲー"
impr = "16"
total = "14"
median = "0"
avg = "0.87"
regist = "2015/11/15 00:13"
update = "2015/11/29 23:38"

[[entries]]
no = "13"
name = "アクジ feat.ニフラムできえそうなやつ"
title = "Breaking Wind"
size = "2222 KB"
addr = ["https://dl.dropboxusercontent.com/u/272956039/Breaking%20Wind.zip"]
genre = "GABBAGABBA"
impr = "14"
total = "14"
median = "0"
avg = "1"
regist = "2015/11/15 00:58"
update = "2015/11/29 23:54"

[[entries]]
no = "14"
name = "/L○o○〆＜BOFU2015よ！！！！俺はここでさらばだ！！！！"
title = "L○o○〆＜BOFU2015よ！！！！俺はここでさらばだ！！！！"
size = "5700 KB"
addr = ["L○o○〆＜BOFU2015よ！！！！俺はここでさらばだ！！！！"]
genre = "L○o○〆＜BOFU2015よ！！！！俺はここでさらばだ！！！！"
impr = "19"
total = "19"
median = "1"
avg = "1"
regist = "2015/11/15 18:55"
update = "2016/03/29 19:02"

[[entries]]
no = "15"
name = "風上ユウオン"
title = "忙しい人のためのエクストリームひつじダッシュ"
size = "25172 KB"
addr = ["https://www.dropbox.com/s/uadbiicpb1u6ahv/%5B%E9%A2%A8%E4%B8%8A%E3%83%A6%E3%82%A6%E3%82%AA%E3%83%B3%5D%E5%BF%99%E3%81%97%E3%81%84%E4%BA%BA%E3%81%AE%E3%81%9F%E3%82%81%E3%81%AE%E3%82%A8%E3%82%AF%E3%82%B9%E3%83%88%E3%83%AA%E3%83%BC%E3%83%A0%E3%81%B2%E3%81%A4%E3%81%98%E3%83%80%E3%83%83%E3%82%B7%E3%83%A5.zip?dl=1"]
genre = "わくわくあにまるろっく"
impr = "14"
total = "7"
median = "0"
avg = "0.5"
regist = "2015/11/15 19:18"
update = "2015/11/29 23:41"

[[entries]]
no = "16"
name = "饅頭"
title = "踏み台昇降"
size = "52800 KB"
addr = ["https://dl.dropboxusercontent.com/u/106790826/%E8%B8%8F%E3%81%BF%E5%8F%B0%E6%98%87%E9%99%8D.rar"]
genre = "フュージョン"
impr = "16"
total = "9"
median = "0"
avg = "0.56"
regist = "2015/11/15 21:36"
update = "2015/11/29 23:01"

[[entries]]
no = "17"
name = "M-kani vs. CirCy"
title = "某appに文字をなぞりリズム隊を乗せてFLで再構成した曲"
size = "678 KB"
addr = ["http://www.dropbox.com/s/bcsbnpcdpp7mq5k/name.zip?dl=1"]
genre = "techno"
impr = "14"
total = "5"
median = "0"
avg = "0.35"
regist = "2015/11/15 22:13"
update = "2015/12/04 01:40"

[[entries]]
no = "18"
name = "おやじギャグマン"
title = "おやじギャグ"
size = "300 KB"
addr = ["https://www.dropbox.com/s/tu3238p3p9dfgf3/%E3%81%8A%E3%82%84%E3%81%98%E3%82%AE%E3%83%A3%E3%82%B0.zip?dl=0"]
genre = "おやじ"
impr = "15"
total = "14"
median = "0"
avg = "0.93"
regist = "2015/11/15 22:30"
update = "2015/11/29 23:25"

[[entries]]
no = "19"
name = "dosugoge"
title = "ヘンなテレビ？"
size = "14510 KB"
addr = ["https://dl.dropboxusercontent.com/s/4dmw7q2rzje5wvc/%5Bdosugoge%5Dhen_na_TV_ogg.zip?dl=0"]
genre = "脳内リレー"
impr = "20"
total = "20"
median = "1"
avg = "1"
regist = "2015/11/15 23:13"
update = "2015/12/05 20:43"

[[entries]]
no = "20"
name = "山形ガンギマリ花"
title = "ちくわパフェ"
size = "1100 KB"
addr = ["https://www.dropbox.com/s/ty5m0xh3igmppr6/chikuwa.zip?dl=1"]
genre = "ちくわパフェ"
impr = "22"
total = "21"
median = "0"
avg = "0.95"
regist = "2015/11/15 23:14"
update = "2015/11/29 23:57"

[[entries]]
no = "21"
name = "ホーネット"
title = "どらむんGUN"
size = "1230 KB"
addr = ["http://fa18af.sakura.ne.jp/bmsfa18/gun_foon2015.zip"]
genre = "GUN SOUND"
impr = "18"
total = "14"
median = "1"
avg = "0.77"
regist = "2015/11/15 23:25"
update = "2015/11/29 23:25"

[[entries]]
no = "22"
name = "sound piercer"
title = "おみくじ"
size = "45194 KB"
addr = ["https://www.dropbox.com/s/0tc7u8re9g78m69/__sp_omikuji__beta.zip?dl=1"]
genre = "Sofa $2015 -> $1"
impr = "22"
total = "22"
median = "1"
avg = "1"
regist = "2015/11/15 23:47"
update = "2015/11/29 23:48"

[[entries]]
no = "23"
name = "店主 vs 客"
title = "ラーメン二郎 BMS店"
size = "591 KB"
addr = ["https://www.dropbox.com/s/fnr6b76r5y49vsi/jirou.zip?dl=0"]
genre = "-"
impr = "25"
total = "25"
median = "1"
avg = "1"
regist = "2015/11/15 23:53"
update = "2016/03/14 03:02"

[[entries]]
no = "24"
name = "Takeshita"
title = "(^^) (Takeshita Remix)"
size = "962 KB"
addr = ["https://goo.gl/851QGw"]
genre = "Breakcore / Fooncore"
impr = "19"
total = "19"
median = "1"
avg = "1"
regist = "2015/11/15 23:55"
update = "2017/03/08 00:44"

[[entries]]
no = "25"
name = "bm_asahi"
title = "FL Studioを開いて最初にやること"
size = "9 KB"
addr = ["http://bm-asahi.com/FLStudio_saisho.rar"]
genre = "FL is GOD"
impr = "17"
total = "16"
median = "0"
avg = "0.94"
regist = "2015/11/15 23:57"
update = "2015/11/29 23:55"

[[entries]]
no = "26"
name = "NECOX"
title = "ネオ・テンション"
size = "859 KB"
addr = ["https://dl.dropboxusercontent.com/u/48382591/%E5%B1%B1%E7%94%B0%E5%8B%9D%E5%B7%B1.zip"]
genre = "テンション"
impr = "14"
total = "14"
median = "0"
avg = "1"
regist = "2015/11/15 23:58"
update = "2015/11/29 22:59"

[[entries]]
no = "27"
name = "アニマル山田"
title = "ＨＡＰＰＹ ＦＯＯＮ ＫＯＲＥ"
size = "6922 KB"
addr = ["http://www1.axfc.net/u/3567532"]
genre = "Happy Hardocore"
impr = "16"
total = "7"
median = "0"
avg = "0.43"
regist = "2015/11/15 23:58"
update = "2015/11/29 23:57"

[[entries]]
no = "28"
name = "変態糞DJ"
title = "やったぜ。"
size = "26600 KB"
addr = ["http://www1.axfc.net/u/3567537"]
genre = "変態"
impr = "16"
total = "12"
median = "0"
avg = "0.75"
regist = "2015/11/15 23:58"
update = "2015/11/29 23:19"

[[entries]]
no = "29"
name = "あがーやれ"
title = "あがーやれ"
size = "0 KB"
addr = ["-----"]
genre = "あがーやれ"
impr = "22"
total = "8"
median = "0"
avg = "0.36"
regist = "2015/11/15 23:58"
update = "2018/05/02 21:22"
