[[entries]]
no = "1"
name = "p_d"
team = "ポポ子"
title = "きわどい瞬間"
size = "432 KB"
addr = ["http://www.pixiv.net/member_illust.php?mode=medium&illust_id=54772564"]
genre = "On The Bed"
impr = "9"
total = "66"
median = "7"
avg = "7.33"
regist = "2016/01/18 00:10"
update = "2016/02/07 23:26"

[[entries]]
no = "2"
name = "Sakamiya feat.mirina"
team = "勇希-YUKI-"
title = "RiZE UP FUTURE"
size = "4270 KB"
addr = ["https://www.dropbox.com/s/kwvvs95jptlwsgb/RiZE_UP_FUTURE_sakamiya_ogg.zip?dl=0"]
genre = "Digital-J-EURO"
impr = "15"
total = "125"
median = "9"
avg = "8.33"
regist = "2016/01/20 06:32"
update = "2017/10/27 00:33"

[[entries]]
no = "3"
name = "Sakamiya feat.mirina"
team = "ライラ(Lyra)"
title = "Airetsiw"
size = "3620 KB"
addr = ["https://www.dropbox.com/s/z3uz4x3ifeusamr/Airetsiw_sakmiya_ogg.zip?dl=0"]
genre = "Digital-J-Pop"
impr = "14"
total = "118"
median = "9"
avg = "8.42"
regist = "2016/01/21 22:33"
update = "2017/10/27 00:33"

[[entries]]
no = "4"
name = "九条カノン"
team = "SkyGazer"
title = "かなたす～"
size = "91 KB"
addr = ["http://www.pixiv.net/member_illust.php?mode=medium&illust_id=54863483"]
genre = "Fanart"
impr = "9"
total = "65"
median = "7"
avg = "7.22"
regist = "2016/01/23 19:50"
update = "2016/02/07 23:06"

[[entries]]
no = "5"
name = "振人"
team = "ポポ子"
title = "kickin' runner"
size = "248 KB"
addr = ["http://www.pixiv.net/member_illust.php?mode=medium&illust_id=54963574"]
genre = "Spring Core"
impr = "7"
total = "61"
median = "8"
avg = "8.71"
regist = "2016/01/29 09:12"
update = "2016/02/07 23:30"

[[entries]]
no = "6"
name = "涼風クハレ"
team = "ポポ子"
title = "くりあぶるーすかい"
size = "3820 KB"
addr = ["http://www.pixiv.net/member_illust.php?mode=medium&illust_id=54967332"]
genre = "Blue Sky"
impr = "6"
total = "52"
median = "9"
avg = "8.66"
regist = "2016/01/29 17:30"
update = "2016/02/08 02:54"

[[entries]]
no = "7"
name = "じゃっこ"
team = "がめ子"
title = "Gamegame"
size = "3500 KB"
addr = ["http://www.pixiv.net/member_illust.php?mode=medium&illust_id=55004022"]
genre = "がめ子"
impr = "13"
total = "122"
median = "10"
avg = "9.38"
regist = "2016/01/31 12:42"
update = "2016/02/07 23:06"

[[entries]]
no = "8"
name = "asahi33"
team = "あさひねこ"
title = "clear color"
size = "3354 KB"
addr = ["http://bm-asahi.com/bms/clearcolor.rar"]
genre = "progressive house"
impr = "9"
total = "72"
median = "8"
avg = "8"
regist = "2016/01/31 18:31"
update = "2016/02/08 01:33"

[[entries]]
no = "9"
name = "ごんぎつね"
team = "琉寺(るてら)"
title = "楓葉狼藉"
size = "66704 KB"
addr = ["https://www.dropbox.com/s/fjnbpiw25ec6fgx/huyourouzeki.zip?dl=1"]
genre = "J-デジロック"
impr = "9"
total = "67"
median = "8"
avg = "7.44"
regist = "2016/01/31 23:53"
update = "2016/02/07 23:07"
