[[entries]]
no = "1"
name = "S.S.D. Arranged by Y.W"
title = "トレジャーフェスティバル!!!"
size = "26459 KB"
addr = ["http://www.yw-works.com/data/bm/treasure_festival_ogg.zip"]
genre = "HAPPY ☆ JIG"
impr = "16"
total = "59"
median = "0"
avg = "3.68"
regist = "2016/02/27 00:06"
update = "2016/03/29 17:49"

[[entries]]
no = "2"
name = "37.gate"
title = "じてんしゃ(SPEEDER MIX)"
size = "4050 KB"
addr = ["https://www.dropbox.com/s/vx93zxsqvjd602d/jotensya.zip?dl=1"]
genre = "PKM-SPEED"
impr = "6"
total = "12"
median = "0"
avg = "2"
regist = "2016/02/27 00:08"
update = "2016/03/29 17:44"

[[entries]]
no = "3"
name = "9-zen"
title = "ふしぎなおくりもの"
size = "6023 KB"
addr = ["https://drive.google.com/uc?export=download&id=1mQwwHb8Gv6mzXszCQkS7a9Wc9Zed8JKh"]
genre = "Everyone Happy! Wi-Fi Connection"
impr = "9"
total = "31"
median = "2"
avg = "3.44"
regist = "2016/02/27 00:56"
update = "2022/05/27 10:33"

[[entries]]
no = "4"
name = "Arranged by Y.W"
title = "GOOD BYE AND NEW COMER!!"
size = "10042 KB"
addr = ["http://www.yw-works.com/data/bm/gs_3839_ogg.zip"]
genre = "HAPPY SYMPHONY"
impr = "9"
total = "32"
median = "0"
avg = "3.55"
regist = "2016/02/27 01:07"
update = "2016/03/29 23:03"

[[entries]]
no = "5"
name = "ニンフィアかわいい！"
title = "たまごろーど！"
size = "9080 KB"
addr = ["https://www.dropbox.com/s/j3q3uyfl6qcf26m/%5Bsak%5D%E3%81%9F%E3%81%BE%E3%81%94%E3%82%8D%E3%83%BC%E3%81%A9%EF%BC%81.zip?dl=1"]
genre = "SWEET SCAMPER!"
impr = "11"
total = "40"
median = "3"
avg = "3.63"
regist = "2016/02/27 07:34"
update = "2019/01/14 22:08"

[[entries]]
no = "6"
name = "岩石丸"
title = "ポケモンカードGB クラブマスター戦(がんせきおとしデッキmix)"
size = "10965 KB"
addr = ["https://www.dropbox.com/s/9gwks4cnsww78t4/Pokemon%20CG%20GB%20vs%20Club%20Master%28Stone%20Club%20Mix%29.zip?dl=1"]
genre = "TCG JUMP STYLE"
impr = "7"
total = "16"
median = "0"
avg = "2.28"
regist = "2016/02/28 02:30"
update = "2016/03/30 00:00"

[[entries]]
no = "7"
name = "RYO-K"
title = "あの紫の華はあなたを忘れない"
size = "7189 KB"
addr = ["https://www.dropbox.com/s/dtfdw3hsj4v26lg/%E3%80%90RYO-K%E3%80%91%E3%81%82%E3%81%AE%E7%B4%AB%E3%81%AE%E8%8F%AF%E3%81%AF%E3%81%82%E3%81%AA%E3%81%9F%E3%82%92%E5%BF%98%E3%82%8C%E3%81%AA%E3%81%84.zip?dl=1"]
genre = "Halfstep Drum&Bass"
impr = "13"
total = "38"
median = "0"
avg = "2.92"
regist = "2016/03/03 01:09"
update = "2016/03/29 22:51"

[[entries]]
no = "8"
name = "MA$AKI"
title = "ポケモンピンボール 青台ゲットモード"
size = "35724 KB"
addr = ["https://www.dropbox.com/s/rg7e56ubru2yq0h/getmode_ao.zip?dl=1"]
genre = "GAME MUSIC"
impr = "9"
total = "22"
median = "0"
avg = "2.44"
regist = "2016/03/03 19:59"
update = "2016/03/29 17:57"

[[entries]]
no = "9"
name = "ぶいぜるらばー2016号"
title = "ミシロタウン（6-8chip mix）"
size = "5440 KB"
addr = ["https://www.dropbox.com/s/bmj0r9iio477jyj/bui_mishiro_ogg.rar?dl=1"]
genre = "chip waltz"
impr = "6"
total = "14"
median = "0"
avg = "2.33"
regist = "2016/03/05 21:00"
update = "2016/03/29 17:58"

[[entries]]
no = "10"
name = "asahi33"
title = "A.U.M."
size = "2424 KB"
addr = ["http://bm-asahi.com/bms/a_u_m_.rar"]
genre = "Japanese Techno"
impr = "7"
total = "18"
median = "2"
avg = "2.57"
regist = "2016/03/05 23:57"
update = "2016/06/21 20:30"

[[entries]]
no = "11"
name = "DashRaver feat. RainbowColors"
title = "Taken The First Step"
size = "57250 KB"
addr = [
    "https://www.dropbox.com/s/w8r4naibq0wtu4f/dr_ttfs_ogg.zip?dl=1",
    "【修正差分】 2016/3/6 20:30以前に落とした方向け",
    "https://www.dropbox.com/s/3kihleuzdghuk1k/dr_ttfs_fix_20160307.zip?dl=1",
]
genre = "HappyCore"
impr = "13"
total = "48"
median = "0"
avg = "3.69"
regist = "2016/03/06 22:25"
update = "2016/03/29 22:58"

[[entries]]
no = "12"
name = "MSMcorp."
title = "カラクリ屋敷(インドネシア地方版)"
size = "20545 KB"
addr = ["https://www.dropbox.com/s/3lb1rttivmdwrvq/%E3%82%AB%E3%83%A9%E3%82%AF%E3%83%AA%E5%B1%8B%E6%95%B7%28%E3%82%A4%E3%83%B3%E3%83%89%E3%83%8D%E3%82%B7%E3%82%A2%E5%9C%B0%E6%96%B9%E7%89%88%29.zip?dl=1"]
genre = "FUNKOT"
impr = "7"
total = "20"
median = "0"
avg = "2.85"
regist = "2016/03/07 06:16"
update = "2016/03/29 17:50"

[[entries]]
no = "13"
name = "sak respect for Arata Iiyoshi"
title = "Reason of being"
size = "41000 KB"
addr = ["https://www.dropbox.com/s/0ih3qmxfv7ctcre/%5Bsak%5DReason_of_being.zip?dl=1"]
genre = "Finale"
impr = "18"
total = "66"
median = "3"
avg = "3.66"
regist = "2016/03/10 21:44"
update = "2019/01/14 22:00"

[[entries]]
no = "14"
name = "gransear"
title = "古代の風に沈む城"
size = "8710 KB"
addr = ["http://gransear.noor.jp/hscolors/bpms/gransear_ancientcastle_ogg.zip"]
genre = "WORLD/BREAKBEATS"
impr = "8"
total = "23"
median = "2"
avg = "2.87"
regist = "2016/03/13 06:39"
update = "2016/03/30 02:10"

[[entries]]
no = "15"
name = "たそがれブラザーズバンド"
title = "ビレッジブリッジフェスティバル2016"
size = "15820 KB"
addr = [
    "http://www1.axfc.net/u/3638017.zip",
    "http://www1.axfc.net/u/3640850.zip",
    "（譜面追加,ogg版）",
]
genre = "CARNIVAL"
impr = "7"
total = "19"
median = "2"
avg = "2.71"
regist = "2016/03/20 23:50"
update = "2016/03/29 23:01"

[[entries]]
no = "16"
name = "dosugoge"
title = "帰ろう -ポケットモンスターRSEエンディング- / -殿堂入りしてからがスタートだ！MIX-"
size = "17750 KB"
addr = ["https://www.dropbox.com/s/zfkbt3w2zqrc2e6/kaerou__pokemon_RS_ed.zip?dl=1"]
genre = "Ending / Opening"
impr = "6"
total = "15"
median = "1.5"
avg = "2.5"
regist = "2016/03/20 23:58"
update = "2016/10/16 15:06"
