[[entries]]
no = "1"
name = "Trinity"
title = "Hopeful Sky"
size = "16100 KB"
addr = ["https://www.dropbox.com/s/l3f0x03sifqxxp8/%5BTrinity%5Dhopeful%20sky.zip?dl=0"]
genre = "TRANCE"
impr = "59"
total = "202"
median = "3"
avg = "3.42"
regist = "2016/06/01 00:05"
update = "2016/06/27 11:16"

[[entries]]
no = "2"
name = "けふぃー"
title = "albagioso vergine"
size = "11020 KB"
addr = ["https://www.dropbox.com/s/9pvo5z6mr9kxnld/albagioso%20vergine.rar?dl=0"]
genre = "GOTHIC HARD INSTRUMENTAL"
impr = "92"
total = "398"
median = "4"
avg = "4.32"
regist = "2016/06/01 00:05"
update = "2016/06/30 22:50"

[[entries]]
no = "3"
name = "白"
title = "ウチナルココロ"
size = "28828 KB"
addr = ["https://drive.google.com/file/d/0ByJKPc7HPAAlSHhyejl1RURoTW8/view?usp=sharing"]
genre = "Electronica"
impr = "56"
total = "199"
median = "4"
avg = "3.55"
regist = "2016/06/01 00:14"
update = "2016/06/26 23:48"

[[entries]]
no = "4"
name = "yuki."
title = "Catalyst"
size = "31000 KB"
addr = ["https://www.dropbox.com/s/2h8f8cajoy9sbsu/%5Byuki.%5DCatalyst.zip?dl=0"]
genre = "J-CORE"
impr = "93"
total = "438"
median = "5"
avg = "4.7"
regist = "2016/06/01 00:16"
update = "2016/06/26 23:58"

[[entries]]
no = "5"
name = "早明浦キュウゾウ"
title = "THIS TIME; LAST TIME"
size = "25712 KB"
addr = [
    "BMSファイル",
    "https://www.dropbox.com/s/65rylfcv3igyvw2/%5BKyuzo_Sameura%5DTHIS_TIME_LAST_TIME.zip?dl=0",
    "追加譜面のみ",
    "https://www.dropbox.com/s/sgs3k5dv1oqdsw7/%28append%29%5BKyuzo_Sameura%5DTHIS_TIME_LAST_TIME.zip?dl=0",
]
genre = "2 step"
impr = "98"
total = "454"
median = "5"
avg = "4.63"
regist = "2016/06/01 00:33"
update = "2016/07/09 17:38"

[[entries]]
no = "6"
name = "Zoety"
title = "Orange sunlight"
size = "48563 KB"
addr = ["https://www.dropbox.com/s/we9g6mf40gf4jsf/%5BZoety%5DOrange_sunlight.rar?dl=0"]
genre = "UK Hardcore"
impr = "55"
total = "210"
median = "4"
avg = "3.81"
regist = "2016/06/01 00:36"
update = "2016/06/26 23:56"

[[entries]]
no = "7"
name = "KIRI"
title = "Fresh Splash!!"
size = "8847 KB"
addr = [
    "https://www.dropbox.com/s/rdgseqfxi5y3aj6/Fresh%20Splash%21%21%20-KIRI%28BGI%E6%9C%89%E3%82%8A%29.zip?dl=0",
    "(BGI有り)",
]
genre = "HAPPY HARDCORE"
impr = "55"
total = "181"
median = "3"
avg = "3.29"
regist = "2016/06/01 00:39"
update = "2016/06/26 23:49"

[[entries]]
no = "8"
name = "sugipamo"
title = "Bit"
size = "39979 KB"
addr = ["http://drive.google.com/open?id=0BypmxEVuaYoOdG5QV05fX0VsWWc"]
genre = "DUBSTEP"
impr = "53"
total = "168"
median = "3"
avg = "3.16"
regist = "2016/06/01 00:41"
update = "2016/06/26 23:49"

[[entries]]
no = "9"
name = "blslick"
title = "Blink Of Star"
size = "39700 KB"
addr = ["https://www.dropbox.com/s/nkt3cowhim6r6vh/Blink%20Of%20Star.zip?dl=1"]
genre = "UK HARDCORE"
impr = "56"
total = "205"
median = "4"
avg = "3.66"
regist = "2016/06/01 00:49"
update = "2016/06/26 23:49"

[[entries]]
no = "10"
name = "tokiwa"
title = "Grief_N_Delight"
size = "11059 KB"
addr = [
    "https://www.dropbox.com/s/zgylhbw44gc7can/Grief_and_delight.zip?dl=0",
    "SPH修正差分:",
    "https://www.dropbox.com/s/ihmnocui3rioajm/Grief_N_Delight_SPH.bms?dl=0",
]
genre = "UK HARDCORE"
impr = "60"
total = "266"
median = "5"
avg = "4.43"
regist = "2016/06/01 01:00"
update = "2016/06/26 23:49"

[[entries]]
no = "11"
name = "moniq"
title = "Starlight Spiral"
size = "27269 KB"
addr = ["https://www.dropbox.com/s/ga3ldwttquph6ne/Starlight_Spiral.zip?dl=0"]
genre = "HAPPYHARDCORE"
impr = "55"
total = "211"
median = "4"
avg = "3.83"
regist = "2016/06/01 02:08"
update = "2016/06/26 23:53"

[[entries]]
no = "12"
name = "suki"
title = "テーマソング"
size = "56300 KB"
addr = ["https://www.dropbox.com/s/kdgju61bnbuk3vw/%E3%83%86%E3%83%BC%E3%83%9E%E3%82%BD%E3%83%B3%E3%82%B0_suki.zip?dl=0"]
genre = "Folk-Pop/Toytronica"
impr = "74"
total = "328"
median = "5"
avg = "4.43"
regist = "2016/06/01 06:08"
update = "2016/06/26 23:57"

[[entries]]
no = "13"
name = "KiSHi"
title = "Ansakas"
size = "29692 KB"
addr = ["http://www1.axfc.net/u/3674462"]
genre = "P†ano"
impr = "54"
total = "176"
median = "3"
avg = "3.25"
regist = "2016/06/01 22:29"
update = "2016/06/26 23:50"

[[entries]]
no = "14"
name = "REVLIS"
title = "Argentum"
size = "24880 KB"
addr = ["https://www.dropbox.com/s/iitxyf9kaxz1r4z/argentum.rar?dl=0"]
genre = "TRANCE"
impr = "49"
total = "126"
median = "3"
avg = "2.57"
regist = "2016/06/02 00:41"
update = "2016/06/27 02:34"

[[entries]]
no = "15"
name = "MALVA"
title = "Achillea"
size = "73200 KB"
addr = ["https://drive.google.com/open?id=1xOr-n3pRjog3Dsv7bCEYzUSwkFHlhvBH"]
genre = "SCHLACHT"
impr = "61"
total = "215"
median = "4"
avg = "3.52"
regist = "2016/06/02 17:50"
update = "2017/11/26 21:30"

[[entries]]
no = "16"
name = "9A"
title = "be at sea"
size = "31461 KB"
addr = ["http://stairway.sakura.ne.jp/be_at_sea_ogg.zip"]
genre = "digital music"
impr = "62"
total = "249"
median = "4"
avg = "4.01"
regist = "2016/06/02 23:54"
update = "2016/06/26 23:55"

[[entries]]
no = "17"
name = "mryat"
title = "Sound Battle!!"
size = "32315 KB"
addr = ["https://drive.google.com/open?id=0B2WmVBIhE1OrUnFhWUk0ekt0a2c"]
genre = "ELECTRO"
impr = "58"
total = "232"
median = "4"
avg = "4"
regist = "2016/06/03 00:25"
update = "2016/06/26 23:56"

[[entries]]
no = "18"
name = "TamaDo"
title = "Blank of History"
size = "79300 KB"
addr = ["https://www.dropbox.com/s/iwfnbg26b1f05w4/BlankofHistory.zip?dl=0"]
genre = "melodic d'n'b"
impr = "53"
total = "198"
median = "4"
avg = "3.73"
regist = "2016/06/03 00:37"
update = "2016/06/26 23:59"

[[entries]]
no = "19"
name = "XxdbxX"
title = "hypno-thermia"
size = "30388 KB"
addr = ["https://drive.google.com/open?id=0B93xE1j0qvlvVHR0TDRZSjBieU0"]
genre = "liquid funk"
impr = "47"
total = "156"
median = "3"
avg = "3.31"
regist = "2016/06/03 15:34"
update = "2016/06/26 23:51"

[[entries]]
no = "20"
name = "cookie+"
title = "tripping falling"
size = "35942 KB"
addr = [
    "本体",
    "https://www.dropbox.com/s/x8jle7m2hsi8vns/%5Bcookie%2B%5Dtripping_falling.zip?dl=0",
    "2016/6/4 am3:00以前にダウンロードした方へ。譜面の修正がありました。申し訳ございません。",
    "修正差分",
    "https://www.dropbox.com/s/byseocf06v11t38/%5Bcookie%2B%5D%E5%B7%AE%E5%88%86%E8%AD%9C%E9%9D%A2%28trippingfalling%29.zip?dl=0",
]
genre = "HAPPY HARDCORE"
impr = "49"
total = "170"
median = "3"
avg = "3.46"
regist = "2016/06/03 20:18"
update = "2016/06/26 23:51"

[[entries]]
no = "21"
name = "the 1000th summer"
title = "BlackLily"
size = "42615 KB"
addr = ["https://www.dropbox.com/s/fqa9lzzqvlk8swj/blacklily.zip?dl=0"]
genre = "Curse Chant"
impr = "58"
total = "232"
median = "4"
avg = "4"
regist = "2016/06/03 22:40"
update = "2016/06/27 23:02"

[[entries]]
no = "22"
name = "alt"
title = "Plunge into cloud"
size = "33000 KB"
addr = ["https://www.dropbox.com/s/cln0bj11rcmxq1p/Plunge%20into%20cloud.zip?dl=0"]
genre = "electro trance"
impr = "50"
total = "146"
median = "3"
avg = "2.92"
regist = "2016/06/03 23:19"
update = "2016/06/27 11:17"

[[entries]]
no = "23"
name = "シア(CV:mia)×レイナ(CV:mirina) / Music:Sakamiya"
title = "Lyzoande for sacrifice"
size = "33800 KB"
addr = ["https://www.dropbox.com/s/lrgzhab0d5kcvzh/Lyzoande_for_sacrifice_Sakamiya_HQogg.zip?dl=1"]
genre = "Phonicgain"
impr = "95"
total = "426"
median = "5"
avg = "4.48"
regist = "2016/06/04 15:04"
update = "2017/10/27 00:37"

[[entries]]
no = "24"
name = "いわし"
title = "彼方へ"
size = "21100 KB"
addr = ["https://drive.google.com/file/d/0B8hxAD0L6Y3nM0hXM3J4S3BzRUk/view?usp=sharing"]
genre = "BATTLE"
impr = "47"
total = "153"
median = "3"
avg = "3.25"
regist = "2016/06/04 17:09"
update = "2016/06/26 23:52"

[[entries]]
no = "25"
name = "9640"
title = "AnGeLoS"
size = "9200 KB"
addr = [
    "https://www.dropbox.com/s/asiw6fsg3a4l6xq/9640_AnGeLoS.zip?dl=1",
    "(ogg本体)",
    "https://www.dropbox.com/s/j6q5dkppbm5x4uc/AnGeLoS_SP_HYPER_re.zip?dl=1",
    "(SP_HYPER修正版)",
]
genre = "TRANCE"
impr = "53"
total = "151"
median = "3"
avg = "2.84"
regist = "2016/06/04 18:45"
update = "2016/06/27 00:18"

[[entries]]
no = "26"
name = "Hydria"
title = "Underground Euphoria"
size = "47000 KB"
addr = ["https://www.dropbox.com/s/7v6iazi8uj5241j/undergroundeuphoria.zip?dl=0"]
genre = "Hardtek"
impr = "54"
total = "202"
median = "4"
avg = "3.74"
regist = "2016/06/04 20:20"
update = "2016/06/26 23:58"

[[entries]]
no = "27"
name = "BBBox"
title = "LLSC"
size = "39629 KB"
addr = ["https://www.dropbox.com/s/t40mfk6vd5841zk/BBBox%20-%20LLSC.zip?dl=0"]
genre = "Hard Minimal"
impr = "57"
total = "232"
median = "4"
avg = "4.07"
regist = "2016/06/04 22:51"
update = "2016/06/27 00:41"

[[entries]]
no = "28"
name = "SuraN"
title = "VoLueTRiC"
size = "37709 KB"
addr = ["https://drive.google.com/folderview?id=0B7IjgnopIYhXMjBsU3BPZmVfdDg&usp=sharing"]
genre = "Trancecore"
impr = "49"
total = "175"
median = "4"
avg = "3.57"
regist = "2016/06/04 22:59"
update = "2016/06/26 23:53"

[[entries]]
no = "29"
name = "新人"
title = "Fallen"
size = "57229 KB"
addr = ["https://drive.google.com/file/d/0B6UORKrI6KIuUXpPQ2xCYlZqLVE/view"]
genre = "DnB"
impr = "48"
total = "159"
median = "3"
avg = "3.31"
regist = "2016/06/04 23:42"
update = "2016/06/27 22:34"

[[entries]]
no = "30"
name = "Alf zero"
title = "Fallen Angel"
size = "13951 KB"
addr = ["https://drive.google.com/file/d/0B2FYk0gprrHManZyOF9BSnNIYmM/"]
genre = "Artcore"
impr = "52"
total = "197"
median = "4"
avg = "3.78"
regist = "2016/06/05 00:58"
update = "2016/06/26 23:59"

[[entries]]
no = "31"
name = "Knowka"
title = "Divers Preparedness"
size = "51358 KB"
addr = ["https://drive.google.com/file/d/0B1vYLbTEo4uMQmNwLXBxdFcwa2s/view?usp=sharing"]
genre = "Hard Techno"
impr = "57"
total = "236"
median = "4"
avg = "4.14"
regist = "2016/06/05 01:57"
update = "2016/06/26 23:54"

[[entries]]
no = "32"
name = "しなちくシステム"
title = "Swallow"
size = "45238 KB"
addr = [
    "プレイ用BMS(通常はコチラ):",
    "https://dl.dropboxusercontent.com/s/rrpzj0fadoy1lkw/Swallow.zip",
    "差分譜面制作用BMS:",
    "https://www.dropbox.com/s/y1vi1r23abz05ka/Swallow-All%20notes.zip?dl=1",
]
genre = "Symphonic Electro"
impr = "86"
total = "393"
median = "5"
avg = "4.56"
regist = "2016/06/05 02:17"
update = "2016/06/26 23:57"

[[entries]]
no = "33"
name = "Niskdai"
title = "PATIENTLY"
size = "9258 KB"
addr = ["https://www.dropbox.com/s/r9zy75ypwevocaf/patiently_ogg.zip?dl=1"]
genre = "HARDCORE"
impr = "47"
total = "128"
median = "3"
avg = "2.72"
regist = "2016/06/05 15:21"
update = "2016/06/28 23:55"

[[entries]]
no = "34"
name = "LIU-RALD"
title = "TRUE SIGNAL"
size = "51038 KB"
addr = ["https://drive.google.com/file/d/0B1AnbpQSVz_GQ1JyeHRMcU5CZ1E/view?usp=sharing"]
genre = "HAPPY HARD CORE"
impr = "45"
total = "106"
median = "2"
avg = "2.35"
regist = "2016/06/05 15:21"
update = "2016/06/26 23:59"

[[entries]]
no = "35"
name = "0samil0"
title = "Your mind... (Hypnosis)"
size = "12618 KB"
addr = ["http://www.dropbox.com/s/likoprs82ph2k5b/01%20Your%20mind.zip?dl=1"]
genre = "Future House"
impr = "54"
total = "208"
median = "4"
avg = "3.85"
regist = "2016/06/05 16:24"
update = "2016/06/29 00:18"

[[entries]]
no = "36"
name = "k0PP3P4n"
title = "Alice in the cyberland"
size = "19670 KB"
addr = ["https://www.dropbox.com/s/gfpa7uiheodlzgd/%5B%E7%84%A1%E5%90%8D%E6%88%A613%5DAlice%20in%20the%20cyberland.zip?dl=0"]
genre = "Complextro"
impr = "63"
total = "243"
median = "4"
avg = "3.85"
regist = "2016/06/05 17:11"
update = "2016/06/26 23:55"

[[entries]]
no = "37"
name = "常川浩平"
title = "Three to the Power"
size = "12154 KB"
addr = ["https://dl.dropboxusercontent.com/u/85685659/bms/BOFU2016%E3%82%B9%E3%83%AA%E3%83%BC%E3%83%88%E3%82%A5%E3%82%B6%E3%83%91%E3%83%AF%E3%83%BC/Three%20to%20the%20Power.rar"]
genre = "ProgressiveRock"
impr = "56"
total = "166"
median = "3"
avg = "2.96"
regist = "2016/06/05 18:13"
update = "2016/06/27 03:35"

[[entries]]
no = "38"
name = "どぅるん"
title = "Nextage"
size = "10616 KB"
addr = ["https://dl.dropboxusercontent.com/u/154776615/BMS/%5BDurun%5DNextage.zip"]
genre = "UK Hardcore"
impr = "57"
total = "236"
median = "4"
avg = "4.14"
regist = "2016/06/05 18:35"
update = "2016/06/26 23:55"

[[entries]]
no = "39"
name = "KITUNE"
title = "Crow Mage"
size = "8250 KB"
addr = ["https://www.dropbox.com/s/rqaojdntrc0766h/Crow%20Mage.zip?dl=1"]
genre = "WITCH FUNK"
impr = "47"
total = "163"
median = "3"
avg = "3.46"
regist = "2016/06/05 18:53"
update = "2016/07/20 13:09"

[[entries]]
no = "40"
name = "Chronus"
title = "Gating Leaper"
size = "21100 KB"
addr = ["https://www.dropbox.com/s/lq3oaj2c95sj8ce/Gating_Leaper.bms.zip?dl=0"]
genre = "Electro Rock"
impr = "65"
total = "265"
median = "4"
avg = "4.07"
regist = "2016/06/05 19:00"
update = "2016/06/28 00:58"

[[entries]]
no = "41"
name = "HyuN"
title = "FINAL ATTACK -BMS Edit- (BGAは後で公開します)"
size = "25016 KB"
addr = ["https://drive.google.com/file/d/0BxdWLxHTZvueNGR4aGhXWGpacmM/view?usp=sharing"]
genre = "HARD ROCK"
impr = "50"
total = "171"
median = "3"
avg = "3.42"
regist = "2016/06/05 19:44"
update = "2016/06/26 23:56"

[[entries]]
no = "42"
name = "いぬすけ"
title = "Arise My Pet"
size = "27200 KB"
addr = ["https://www.dropbox.com/s/y4p9f12uv661bvy/%5B%E3%81%84%E3%81%AC%E3%81%99%E3%81%91%5DArise%20My%20Pet%20%28bga%E8%BF%BD%E5%8A%A0%E7%89%88%29.zip?dl=0"]
genre = "Hardstyle"
impr = "56"
total = "170"
median = "3"
avg = "3.03"
regist = "2016/06/05 21:24"
update = "2016/06/27 00:24"

[[entries]]
no = "43"
name = "noal"
title = "Demagogie"
size = "5810 KB"
addr = ["http://www1.axfc.net/u/3675483"]
genre = "HARDTECHNO"
impr = "65"
total = "304"
median = "5"
avg = "4.67"
regist = "2016/06/05 21:46"
update = "2016/06/26 23:56"

[[entries]]
no = "44"
name = "hinoken"
title = "Sleepless E'utopia"
size = "46700 KB"
addr = ["https://www.dropbox.com/s/z4kw7qfm8oxiqsd/Sleepless%20E%27utopia.zip?dl=0"]
genre = "UK Hardcore"
impr = "64"
total = "215"
avg = "3.35"
regist = "2016/06/05 23:07"
update = "2016/06/27 00:13"

[[entries]]
no = "45"
name = "しとえふ"
title = "ArchAngle"
size = "46102 KB"
addr = ["https://www.dropbox.com/s/i6nppdudwrn5vb0/ArchAngle.rar?dl=0"]
genre = "UK_HARDCORE"
impr = "77"
total = "339"
median = "4"
avg = "4.4"
regist = "2016/06/05 23:18"
update = "2016/06/26 23:57"

[[entries]]
no = "46"
name = "sigross"
title = "especially happie!!!!!"
size = "27340 KB"
addr = ["https://www.dropbox.com/s/l3rf42ty1ghkmdu/%5Bsigross%5Despecially%20happie%21%21%21%21%21.zip?dl=0"]
genre = "HIGHSPEED HAPPYHARDCORE"
impr = "57"
total = "233"
median = "4"
avg = "4.08"
regist = "2016/06/05 23:34"
update = "2016/06/26 23:58"

[[entries]]
no = "47"
name = "Breaker vs. Ra-ili"
title = "エピネフリン"
size = "59823 KB"
addr = [
    "Full pakage:",
    "https://www.dropbox.com/s/xfs85fyn7m59tqi/%5BBreaker_Ra-ili%5D_Epinephrine_ogg_20160626.zip?dl=0",
    "BGA only:",
    "https://www.dropbox.com/s/yz8x1wstc097y8r/_movie.mpg?dl=0",
]
genre = "Dub Core"
impr = "62"
total = "254"
median = "4"
avg = "4.09"
regist = "2016/06/05 23:52"
update = "2016/06/26 23:57"

[[entries]]
no = "48"
name = "Meisolate"
title = "Afterwhile"
size = "38725 KB"
addr = ["http://www.mediafire.com/download/4wqa0odwa1u5do1/Afterwhile_bms_ogg.zip"]
genre = "PROGRESSIVE HOUSE"
impr = "87"
total = "410"
median = "5"
avg = "4.71"
regist = "2016/06/05 23:53"
update = "2016/06/26 23:57"

[[entries]]
no = "49"
name = "かたぎり"
title = "The Feast"
size = "2912 KB"
addr = ["https://www.dropbox.com/s/actilaspumnfp10/thefeast.zip?dl=1"]
genre = "FESTUM"
impr = "53"
total = "208"
median = "4"
avg = "3.92"
regist = "2016/06/05 23:56"
update = "2016/06/27 02:15"

[[entries]]
no = "50"
name = "punchhh"
title = "HIGHER"
size = "20699 KB"
addr = [
    "https://www.dropbox.com/s/dfcs2lin1vg2dvh/poprock_ogg___.zip?dl=0",
    "(A譜面同梱)",
    "https://www.dropbox.com/s/1d8eotpz5a4c4mt/_higher_a.zip?dl=0",
    "(A譜面のみ)",
]
genre = "Pop Rock"
impr = "51"
total = "197"
median = "4"
avg = "3.86"
regist = "2016/06/05 23:57"
update = "2016/06/26 23:57"

[[entries]]
no = "51"
name = "青い厚揚げ"
title = "Light-Blue"
size = "3840 KB"
addr = [
    "https://www.dropbox.com/s/l4xgc8hl18166ok/Light-Blue.zip",
    "（上のzipに既に追加差分は入っています、下記ＵＲＬは追加差分のみ）",
    "https://www.dropbox.com/s/hpwtdjljso7iu1w/Light-Blue%20sporty.bms",
]
genre = "easy pop"
impr = "59"
total = "221"
median = "4"
avg = "3.74"
regist = "2016/06/05 23:58"
update = "2016/06/27 00:32"

[[entries]]
no = "52"
name = "PAMCYL"
title = "℃M"
size = "14000 KB"
addr = [
    "↓譜面追加ver",
    "http://www1.axfc.net/u/3676903",
    "6月7日以前にDLしてくれた方もしくはパッケージでDLしてくれた方は下の追加譜面差分を追加していただけると幸いです。※Normal譜面修正済みです（6/8 23:30up)",
    "http://www1.axfc.net/u/3676905",
]
genre = "罵られstyle"
impr = "47"
total = "121"
median = "3"
avg = "2.57"
regist = "2016/06/05 23:59"
update = "2016/06/26 23:58"
