[[entries]]
no = "1"
name = "Kevin & William"
title = "Soda Pop Party"
size = "44682 KB"
addr = [
    "*** CAUTION: WAV VERSION IS OVER 100 MB !! ***",
    "(ogg)",
    "https://dl.dropboxusercontent.com/s/lir6bt25lqzrync/soda_pop_party_ogg.zip",
    "(wav)",
    "https://dl.dropboxusercontent.com/s/27y7a01xryc4ey3/soda_pop_party_wav.zip",
]
genre = "SUMMER TUNES"
impr = "29"
total = "76"
median = "3"
avg = "2.62"
regist = "2016/07/02 00:02"
update = "2016/07/18 00:34"

[[entries]]
no = "2"
name = "月風"
title = "きっと☆Happiness"
size = "17620 KB"
addr = ["https://www.dropbox.com/s/g1c717y7ypet7ui/kittohappy_tsukikaze_ogg.rar?dl=1"]
genre = "HYPER POP"
impr = "23"
total = "55"
median = "2"
avg = "2.39"
regist = "2016/07/02 00:08"
update = "2016/07/23 01:31"

[[entries]]
no = "3"
name = "psi"
title = "EVERLASTING HAPPiNESS↑"
size = "8500 KB"
addr = ["https://www.dropbox.com/s/azi2rk2hb5tvmwa/%5Bpsi%20as%20sak%5DEVERLASTING%20HAPPiNESS.zip?dl=1"]
genre = "HAPPY HARDCORE"
impr = "30"
total = "75"
median = "3"
avg = "2.5"
regist = "2016/07/02 00:10"
update = "2019/01/14 21:44"

[[entries]]
no = "4"
name = "落龍"
title = "幸降開花"
size = "6140 KB"
addr = ["http://www1.axfc.net/u/3686033"]
genre = "ASIAN HIGH-SPEED"
impr = "25"
total = "53"
median = "2"
avg = "2.12"
regist = "2016/07/02 00:13"
update = "2016/07/18 02:16"

[[entries]]
no = "5"
name = "卯月"
title = "Blooming Jump!"
size = "16400 KB"
addr = ["https://www.dropbox.com/s/bpjbefd62bcor6e/%5Buzuki%5Dblooming_jump_ogg.zip?dl=1"]
genre = "はっぴーうーちゃんコア"
impr = "29"
total = "84"
median = "3"
avg = "2.89"
regist = "2016/07/02 00:17"
update = "2016/08/24 23:28"

[[entries]]
no = "6"
name = "uni"
title = "テトラエトセトラ"
size = "11900 KB"
addr = ["http://www1.axfc.net/u/3686041//"]
genre = "Indie Toy Pop"
impr = "25"
total = "66"
median = "3"
avg = "2.64"
regist = "2016/07/02 00:17"
update = "2016/07/18 10:23"

[[entries]]
no = "7"
name = "水兵"
title = "LIEBE"
size = "24800 KB"
addr = [
    "https://www.dropbox.com/s/fb0l7zw7kdo5c48/Suihei_LIEBE.zip?dl=1",
    "(ogg本体)",
]
genre = "CHARM TRANCE"
impr = "25"
total = "46"
median = "2"
avg = "1.84"
regist = "2016/07/02 00:21"
update = "2016/07/18 01:31"

[[entries]]
no = "8"
name = "汚滝健太郎"
title = "静城の月"
size = "21000 KB"
addr = ["https://www.dropbox.com/s/vwz5g8ha5l5qp7n/otaki_.zip?dl=1"]
genre = "騒音"
impr = "24"
total = "40"
median = "1"
avg = "1.66"
regist = "2016/07/02 01:56"
update = "2019/03/12 23:30"

[[entries]]
no = "9"
name = "Samarium"
title = "Give me Coconut!"
size = "18900 KB"
addr = ["http://www1.axfc.net/u/3686180.rar//"]
genre = "HANDZ UP"
impr = "26"
total = "58"
median = "2"
avg = "2.23"
regist = "2016/07/02 08:33"
update = "2016/07/18 11:57"

[[entries]]
no = "10"
name = "Vanilla Flavor"
title = "Citrus Sunset"
size = "38173 KB"
addr = [
    "(7/3 15:03修正)",
    "https://www.dropbox.com/s/2rp1javpxosugvi/VF_citrus_ogg_ver2.zip?dl=1",
    "(修正BGAのみ・そのまま上書きしてください)",
    "https://www.dropbox.com/s/aulhnpxxir0q5i5/Citrus%20Sunset_640_640_1.mpg?dl=1",
]
genre = "kawaiicore"
impr = "27"
total = "77"
median = "3"
avg = "2.85"
regist = "2016/07/02 09:22"
update = "2016/07/18 19:01"

[[entries]]
no = "11"
name = "Specter L"
title = "ハッピーだあああぁああぁあぁあああ！！！！！"
size = "31600 KB"
addr = ["http://goo.gl/6Siwyk"]
genre = "USUAL TECHNO"
impr = "33"
total = "88"
median = "3"
avg = "2.66"
regist = "2016/07/02 10:34"
update = "2016/07/17 23:44"

[[entries]]
no = "12"
name = "cookie+(CAPSLUCK)"
title = "ELECTRIC HIGHWAY"
size = "41300 KB"
addr = ["http://www1.axfc.net/u/3686222"]
genre = "HAPPY HARDCORE"
impr = "25"
total = "54"
median = "2"
avg = "2.16"
regist = "2016/07/02 11:22"
update = "2016/07/18 21:55"

[[entries]]
no = "13"
name = "cohou"
title = "Myriad Of The Stars"
size = "13500 KB"
addr = ["https://dl.dropboxusercontent.com/s/gdfpytgw9fqpv8s/Myriad_Of_The_Stars.zip"]
genre = "UK HARDCORE"
impr = "24"
total = "58"
median = "2"
avg = "2.41"
regist = "2016/07/02 16:32"
update = "2016/07/17 23:46"

[[entries]]
no = "14"
name = "Kitty"
title = "ネコにまつわるエトセトラ"
size = "17200 KB"
addr = ["http://www1.axfc.net/uploader/so/3686336"]
genre = "Lesson"
impr = "29"
total = "82"
median = "3"
avg = "2.82"
regist = "2016/07/02 18:01"
update = "2016/07/18 01:02"

[[entries]]
no = "15"
name = "ニーナ&アリーナ"
title = "幸せのダンプカー(HANDZ UP MIX)"
size = "4670 KB"
addr = ["http://www1.axfc.net/u/3686359.rar"]
genre = "HAPPY HANDZ UP"
impr = "24"
total = "54"
median = "2"
avg = "2.25"
regist = "2016/07/02 19:10"
update = "2016/07/18 00:17"

[[entries]]
no = "16"
name = "Shinobu Omiya"
title = "Alice"
size = "17852 KB"
addr = ["http://www.mediafire.com/download/rb889a3g4amzpml/%5BShino%5DAlice_ogg.zip"]
genre = "UK Hardcore"
impr = "26"
total = "62"
median = "2"
avg = "2.38"
regist = "2016/07/02 22:18"
update = "2016/07/20 04:55"

[[entries]]
no = "17"
name = "SHUGOH"
title = "ACTIVE DXYO-N"
size = "892 KB"
addr = ["http://www1.axfc.net/u/3686510.rar"]
genre = "HAPPY"
impr = "23"
total = "46"
median = "2"
avg = "2"
regist = "2016/07/02 23:30"
update = "2016/07/18 07:57"

[[entries]]
no = "18"
name = "galaxie"
title = "R:especial"
size = "28016 KB"
addr = ["https://www.dropbox.com/s/2tc4j04pl8e8n9c/Re_special.rar?dl=1"]
genre = "HAPPY HARDCORE"
impr = "22"
total = "41"
median = "2"
avg = "1.86"
regist = "2016/07/03 03:49"
update = "2016/07/18 03:08"

[[entries]]
no = "19"
name = "Magic@l Festiv@l"
title = "Encore!!"
size = "34000 KB"
addr = ["https://drive.google.com/file/d/0B9nyyjZJFpKhY3BvSVRhRHZQR1U/view?usp=sharing"]
genre = "HAPPY"
impr = "24"
total = "65"
median = "3"
avg = "2.7"
regist = "2016/07/03 03:50"
update = "2016/07/18 02:14"

[[entries]]
no = "20"
name = "flicknote"
title = "OVER-WHELMING JOY"
size = "10158 KB"
addr = ["https://dl.dropboxusercontent.com/u/25097375/BMS/2016/over-whelming_joy.zip"]
genre = "SPEED CARNIVAL"
impr = "0"
total = "0"
median = "3"
avg = "2.58"
regist = "2016/07/03 05:09"
update = "2016/07/19 19:47"

[[entries]]
no = "21"
name = "Scootaloo"
title = "Winter Wrap Up (HAPPY REMIX)"
size = "15971 KB"
addr = ["https://www.dropbox.com/s/efjv1w4k033p9kl/winter_wrap_up_remix_ogg.zip?dl=1"]
genre = "HAPPY HARDCORE"
impr = "22"
total = "45"
median = "2"
avg = "2.04"
regist = "2016/07/03 08:03"
update = "2016/07/17 23:58"

[[entries]]
no = "22"
name = "卵黄＋かぼちゃ"
title = "Pumpkin Pudding Punching"
size = "41107 KB"
addr = ["https://www.dropbox.com/s/1u5kxyotv9slv92/%5Begg%20yolk%2Bpumpkin%2Bmilk%5DPPP.zip?dl=1"]
genre = "Sweet Cooking Tune"
impr = "23"
total = "62"
median = "3"
avg = "2.69"
regist = "2016/07/03 09:41"
update = "2016/07/18 02:40"

[[entries]]
no = "23"
name = "夏"
title = "like a dandelion (Cheerful Summer Mix)"
size = "11582 KB"
addr = ["https://dl.dropboxusercontent.com/u/50992731/BMS%20Original/ladsummer_ogg.zip"]
genre = "Summertime Trance"
impr = "27"
total = "66"
median = "2"
avg = "2.44"
regist = "2016/07/03 10:22"
update = "2016/07/18 02:11"

[[entries]]
no = "24"
name = "Vegetarian Pomeranian"
title = "Happy Escalation↑↑"
size = "18109 KB"
addr = ["http://www1.axfc.net/u/3686854.zip"]
genre = "Happy Hardcore"
impr = "26"
total = "64"
median = "2"
avg = "2.46"
regist = "2016/07/03 18:10"
update = "2016/07/17 23:49"

[[entries]]
no = "25"
name = "るり"
title = "Pompadour"
size = "8890 KB"
addr = ["https://www.dropbox.com/s/plownsh82kkyvag/Pompadour.zip?dl=1"]
genre = "swing waltz"
impr = "28"
total = "78"
median = "3"
avg = "2.78"
regist = "2016/07/03 22:00"
update = "2016/07/18 08:45"

[[entries]]
no = "26"
name = "CyanAura"
title = "Breaking Breeze"
size = "42815 KB"
addr = ["https://dl.dropbox.com/s/r3ka8y3267dy7ub/CyanAura_Breaking_Breeze.zip"]
genre = "Hands Up"
impr = "25"
total = "59"
median = "2"
avg = "2.36"
regist = "2016/07/03 22:05"
update = "2016/07/17 23:50"

[[entries]]
no = "27"
name = "Hyperstyle"
title = "Rising into the Starlight(Hyperstyle Edition)"
size = "7830 KB"
addr = ["https://www.dropbox.com/s/cv3peypqa1p4ia8/%5BHyperstyle%5D-Rising_into_the_Starlight.zip?dl=1"]
genre = "Nightcore"
impr = "20"
total = "41"
median = "2"
avg = "2.05"
regist = "2016/07/03 22:30"
update = "2016/07/17 23:54"

[[entries]]
no = "28"
name = "Citronellal*"
title = "Summer Sour Splash!!"
size = "10200 KB"
addr = ["https://www.dropbox.com/s/u2lmnxva01z10ny/Summer%20Sour%20Splash%21%21.rar?dl=1"]
genre = "HAPPY HARDCORE"
impr = "23"
total = "63"
median = "3"
avg = "2.73"
regist = "2016/07/03 22:38"
update = "2016/07/19 00:52"

[[entries]]
no = "29"
name = "DJ HoppingRabbit"
title = "Jumping Leaping!"
size = "69700 KB"
addr = [
    "https://www.dropbox.com/s/iul9ktn9g0189f0/%E3%80%90BMS%E3%80%91Jumping%20Leaping%21%28ogg%29.zip?dl=1",
    "(ogg版) (推奨)",
    "https://www.dropbox.com/s/2cweqq7r2t4u0ym/%E3%80%90BMS%E3%80%91Jumping%20Leaping%21%28wav%29.zip?dl=1",
    "(wav版)",
    "________________________________________________________________________________________________________",
    "修正BGA:",
    "https://www.dropbox.com/s/l5r4ldmb846y81e/JumpingLeaping%21.mpg?dl=1",
]
genre = "Happy Pop Jumping"
impr = "33"
total = "99"
median = "3"
avg = "3"
regist = "2016/07/03 23:06"
update = "2016/07/17 23:50"

[[entries]]
no = "30"
name = "HSZ放送協会"
title = "できるかな？-HSZ教育ビデオシリーズ-"
size = "808 KB"
addr = ["https://www.dropbox.com/s/c6609m9qxkbdf8r/%E3%83%AA%E3%83%88%E3%83%9F%E3%83%83%E3%82%AF.zip?dl=0"]
genre = "リトミック"
impr = "22"
total = "30"
median = "1"
avg = "1.36"
regist = "2016/07/03 23:12"
update = "2016/07/17 23:59"

[[entries]]
no = "31"
name = "るいまる"
title = "僕らの希望は大空を渡る"
size = "4600 KB"
addr = ["https://www.dropbox.com/s/fmuljn6bq8u96yo/%E5%83%95%E3%82%89%E3%81%AE%E5%B8%8C%E6%9C%9B%E3%81%AF%E5%A4%A7%E7%A9%BA%E3%82%92%E6%B8%A1%E3%82%8B_ogg.zip?dl=1"]
genre = "Chip Speed Pop"
impr = "25"
total = "64"
median = "3"
avg = "2.56"
regist = "2016/07/03 23:20"
update = "2016/07/17 23:57"

[[entries]]
no = "32"
name = "zako"
title = "3hours"
size = "7843 KB"
addr = ["http://www1.axfc.net/u/3687043.zip"]
genre = "Happy"
impr = "19"
total = "24"
median = "1"
avg = "1.26"
regist = "2016/07/03 23:32"
update = "2016/07/17 23:54"

[[entries]]
no = "33"
name = "ena"
title = "Summer Days"
size = "10737 KB"
addr = ["http://starkey.ivory.ne.jp/archives/summer_days.zip"]
genre = "TRANCE"
impr = "22"
total = "63"
median = "3"
avg = "2.86"
regist = "2016/07/03 23:37"
update = "2016/07/17 23:58"

[[entries]]
no = "34"
name = "桜ぷろじぇくと！feat.春名しおん"
title = "Tell my LUV"
size = "46000 KB"
addr = ["https://www.dropbox.com/s/uvquks8jaunmh5v/Tell%20my%20LUV.zip?dl=0"]
genre = "J-Happy Hardcore"
impr = "27"
total = "71"
median = "3"
avg = "2.62"
regist = "2016/07/03 23:41"
update = "2016/07/18 00:01"

[[entries]]
no = "35"
name = "36"
title = "Ramune"
size = "26000 KB"
addr = ["http://www1.axfc.net/u/3687047"]
genre = "Future Tech Electro"
impr = "21"
total = "55"
median = "3"
avg = "2.61"
regist = "2016/07/03 23:44"
update = "2016/07/17 23:56"

[[entries]]
no = "36"
name = "相 琴葉"
title = "トンガ・トング・トンゴ"
size = "39600 KB"
addr = [
    "https://www.dropbox.com/s/uisaoih6lovf5c2/%5Bai-kotoba%5Dtonga_tong_tongo.zip?dl=1",
    "(パッケージ版のBGAは無音化が行われていないので、更新推奨です。)",
]
genre = "HAPPY"
impr = "22"
total = "50"
median = "2"
avg = "2.27"
regist = "2016/07/03 23:58"
update = "2016/10/16 16:24"

[[entries]]
no = "37"
name = "Name Old Monger"
title = "スリースターズ"
size = "5297 KB"
addr = [
    "http://www.dropbox.com/s/opawiupkq6sfoao/threestars_BH.zip?dl=0",
    "(20160704修正後)",
    "http://www1.axfc.net/u/3687062",
    "(修正前)",
]
genre = "Triplet Hardcore"
impr = "20"
total = "37"
median = "2"
avg = "1.85"
regist = "2016/07/03 23:58"
update = "2017/02/25 23:51"

[[entries]]
no = "38"
name = "blackcat"
title = "happy pop"
size = "4431 KB"
addr = ["https://www.dropbox.com/s/e9xoja9yi6v4kum/happy_pop.rar?dl=0"]
genre = "relax"
impr = "20"
total = "43"
median = "2"
avg = "2.15"
regist = "2016/07/03 23:59"
update = "2016/07/19 05:55"

[[entries]]
no = "39"
name = "カーリー"
title = "Early Curly Middy Day"
size = "12000 KB"
addr = ["http://www1.axfc.net/u/3687079.zip"]
genre = "PoPs"
impr = "0"
total = "0"
median = "2"
avg = "2"
regist = "2016/07/04 00:16"
update = "2016/07/17 23:58"
