[[entries]]
no = "1"
name = "cuba→kataG"
title = "dub ambivalence"
size = "3432 KB"
addr = [
    "http://niigata.cool.ne.jp/kmbms/bms/cuba%20",
    "[ambient]%20dub%20a.rar",
]
genre = "ambient"
impr = "29"
total = "66"
avg = "2.27"
update = "2004/02/23 00:34"

[[entries]]
no = "2"
name = "color→SE-JI"
title = "lost memory"
size = "3434 KB"
addr = ["http://www.geocities.jp/color_event/event.html"]
genre = "spanish hardcore"
impr = "26"
total = "15"
avg = "0.57"
update = "2004/02/23 15:10"

[[entries]]
no = "3"
name = "Mixo-lydian (ミクソリディアン)"
title = "Tragic:Desert"
size = "4516 KB"
addr = ["http://www7.tok2.com/home/add6/index.html"]
genre = "Argentina Fusion"
impr = "38"
total = "100"
avg = "2.63"
update = "2004/02/20 13:36"

[[entries]]
no = "4"
name = "Respecter→Gun-SEKI"
title = "後ろ姿"
size = "8679 KB"
addr = ["http://page.freett.com/respecter/"]
genre = "love groove"
impr = "38"
total = "84"
avg = "2.21"
update = "2004/02/23 00:08"

[[entries]]
no = "5"
name = "SHaKe → TiY"
title = "Chocolate"
size = "6079 KB"
addr = ["http://unibeat.s53.xrea.com/"]
genre = "happy hardcore"
impr = "23"
total = "34"
avg = "1.47"
update = "2004/02/23 01:03"

[[entries]]
no = "6"
name = "tikyu-jin -＞ borze"
title = "about:blank"
size = "1679 KB"
addr = ["http://sound.jp/pj_dnuos/"]
genre = "HIPHOP"
impr = "30"
total = "67"
avg = "2.23"
update = "2004/02/23 02:38"

[[entries]]
no = "7"
name = "mixx → nu"
title = "DRUNKARD"
size = "2118 KB"
addr = ["http://www.geocities.jp/mixx999jp/index.htm"]
genre = "TECHNO"
impr = "15"
total = "26"
avg = "1.73"
update = "2004/02/24 01:17"

[[entries]]
no = "8"
name = "ぬぺらんかー → NKJG"
title = "resq"
size = "550 KB"
addr = ["http://www.h3.dion.ne.jp/~ish0/nlk_resq.rar"]
genre = "minimal"
impr = "22"
total = "45"
avg = "2.04"
update = "2004/02/23 00:06"

[[entries]]
no = "9"
name = "white chocolate max → ねこみみ魔法使い"
title = "★LittlE HearTs★"
size = "3060 KB"
addr = ["http://sound.jp/white_c_m/"]
genre = "HappY PoPcorN"
impr = "51"
total = "122"
avg = "2.39"
update = "2004/02/23 01:33"

[[entries]]
no = "10"
name = "-404 → KeeL"
title = "堕獄"
size = "7032 KB"
addr = ["http://www.geocities.jp/christianized_luna/dagoku.zip"]
genre = "-"
impr = "24"
total = "38"
avg = "1.58"
update = "2004/02/23 01:20"

[[entries]]
no = "11"
name = "eight-piece → TiY"
title = "OuterDrive [Radio Edit]"
size = "4168 KB"
addr = ["http://www2.aqweb.net/c-curve/"]
genre = "Trance"
impr = "19"
total = "23"
avg = "1.21"
update = "2004/02/23 00:59"

[[entries]]
no = "12"
name = "mc.low → Yuji.M"
title = "Lost Angel"
size = "3769 KB"
addr = ["http://www.ismusic.ne.jp/siromaru/lost_angel.zip"]
genre = "dream trance"
impr = "22"
total = "56"
avg = "2.54"
update = "2004/02/23 23:25"

[[entries]]
no = "13"
name = "Acid Tomb → OPENSPACE"
title = "absolute partition"
size = "3589 KB"
addr = ["http://www.music.ne.jp/~ma-ro/At99.zip"]
genre = "Techno"
impr = "31"
total = "85"
avg = "2.74"
update = "2004/02/25 00:12"
