[[entries]]
no = "1"
name = "Aiel underground"
team = "rkgk taste music"
title = "seoul EVOLVED ver. B"
size = "0 KB"
addr = ["https://youtu.be/UqP2N7gl5YA"]
genre = "EVOLVED"
impr = "3"
total = "2750"
median = "900"
avg = "916.66"
regist = "2016/09/16 00:25"
update = "2016/09/30 02:34"

[[entries]]
no = "2"
name = "Sakamiya feat.北宮"
team = "Eternal resonance"
title = "tear regn"
size = "13700 KB"
addr = ["https://www.dropbox.com/s/kwpl59hohi8xwxg/tearregn_sakamiya_HQogg.zip?dl=1"]
genre = "90's J-Pop"
impr = "9"
total = "7650"
median = "910"
avg = "850"
regist = "2016/09/16 03:32"
update = "2017/10/27 00:40"

[[entries]]
no = "3"
name = "SUPER COLLAB BROS"
team = "Super Collab Bros"
title = '"Pierce" : Official Trailer'
size = "0 KB"
addr = [
    "https://www.youtube.com/watch?v=FKmtKswajwM",
    "comming soon",
]
genre = "Trailer"
impr = "0"
total = "0"
median = "0"
avg = "0"
regist = "2016/09/16 17:02"
update = "2016/09/16 17:07"

[[entries]]
no = "4"
name = "SUPER COLLAB BROS"
team = "Super Collab Bros"
title = '"Invade" : Official Trailer'
size = "0 KB"
addr = [
    "https://www.youtube.com/watch?v=G5BDwN0k2cg",
    "He is comming soon...",
]
genre = "Trailer"
impr = "0"
total = "0"
median = "0"
avg = "0"
regist = "2016/09/16 19:34"
update = "2016/09/16 19:34"

[[entries]]
no = "5"
name = "フリーダムキッズメンバー"
team = "ブリブリブリリ"
title = "ウンコ台風(typhoon)"
size = "114514 KB"
addr = ["https://soundcloud.com/buriburiburiri/unko-typhoon"]
genre = "Schranz"
impr = "0"
total = "0"
median = "0"
avg = "0"
regist = "2016/09/17 20:42"
update = "2016/09/17 20:45"

[[entries]]
no = "6"
name = "AMAZING CRAFT"
team = "AMAZING!!"
title = "BOFU2016前夜 -Amazing Prologue-"
size = "15711 KB"
addr = ["https://www.dropbox.com/s/juxwpy7vsvwt8qm/amazing_prologue.RAR?dl=1"]
genre = "prologue"
impr = "4"
total = "3530"
median = "890"
avg = "882.5"
regist = "2016/09/19 06:33"
update = "2016/11/01 19:38"

[[entries]]
no = "7"
name = "Hyun&Ritoru"
team = "Xenopus"
title = "Fly Again"
size = "1 KB"
addr = ["https://soundcloud.com/hyun_stuidio/bofu2016-hyun-ritoru-fly-again"]
genre = "HAPPY HARDCORE"
impr = "0"
total = "0"
median = "0"
avg = "0"
regist = "2016/09/20 00:33"
update = "2016/09/20 08:28"

[[entries]]
no = "8"
name = "LAZ Shin"
team = "Team EXiT"
title = "Chaos Squad"
size = "1 KB"
addr = ["https://soundcloud.com/shin-laz/bofu2016-chaos-squad"]
genre = "DUBCORE"
impr = "4"
total = "3707"
median = "965"
avg = "926.75"
regist = "2016/09/20 01:34"
update = "2016/09/28 09:15"

[[entries]]
no = "9"
name = "Artmospia"
team = "Team EXiT"
title = "White Film"
size = "1 KB"
addr = ["https://soundcloud.com/artmospia/bofu2016-artmospia-white-film"]
genre = "Progressive House"
impr = "0"
total = "0"
median = "0"
avg = "0"
regist = "2016/09/20 08:26"
update = "2016/09/20 08:26"

[[entries]]
no = "10"
name = "tkqn14 feat. POKU"
team = "Team EXiT"
title = "EXiT 2 SKY"
size = "1 KB"
addr = ["https://soundcloud.com/tkqn14-official/bofu2016-exit2sky"]
genre = "HAPPY HARDCORE"
impr = "1"
total = "775"
median = "775"
avg = "775"
regist = "2016/09/20 08:33"
update = "2016/09/22 01:48"

[[entries]]
no = "11"
name = "KRUX"
team = "InnoXent"
title = "Illusion of Inflict"
size = "1 KB"
addr = ["https://soundcloud.com/hyun_stuidio/bofu2016-krux-illusion-of"]
genre = "Drum'N Bass"
impr = "2"
total = "1700"
median = "850"
avg = "850"
regist = "2016/09/20 08:42"
update = "2016/09/26 12:20"

[[entries]]
no = "12"
name = "HyuN"
team = "InnoXent"
title = "Infinity Heaven"
size = "1 KB"
addr = ["https://soundcloud.com/hyun_stuidio/bofu2016-infinity-heaven-free-download"]
genre = "Inifnity Fantasy"
impr = "0"
total = "0"
median = "0"
avg = "0"
regist = "2016/09/20 16:24"
update = "2016/09/20 16:24"

[[entries]]
no = "13"
name = "Hyunesis&REnewer"
team = "InnoXent"
title = "Fade Away -2016 Edit-"
size = "1 KB"
addr = ["https://soundcloud.com/hyun_stuidio/bofu2016-hyunesis-renewer-fade"]
genre = "BLUE HARDCORE"
impr = "2"
total = "1825"
median = "912.5"
avg = "912.5"
regist = "2016/09/20 16:32"
update = "2016/09/22 01:50"

[[entries]]
no = "14"
name = "tkqn14"
team = "InnoXent"
title = "#FFFFFF"
size = "1 KB"
addr = ["https://soundcloud.com/tkqn14-official/bofu2016-ffffff"]
genre = "HARD TRANCE"
impr = "0"
total = "0"
median = "0"
avg = "0"
regist = "2016/09/20 16:32"
update = "2016/09/20 16:36"

[[entries]]
no = "15"
name = "LOVE LAIKA"
team = "CINDERELLA PROJECT"
title = "Venera"
size = "0 KB"
addr = ["https://www.youtube.com/watch?v=jjoxJCxU9EQ"]
genre = "Liquid Funk"
impr = "0"
total = "0"
median = "0"
avg = "0"
regist = "2016/09/21 00:55"
update = "2016/09/21 00:55"

[[entries]]
no = "16"
name = "new generations"
team = "CINDERELLA PROJECT"
title = "Song for You!"
size = "0 KB"
addr = ["https://www.youtube.com/watch?v=aRRdVonR-RQ"]
genre = "Idol Pop"
impr = "0"
total = "0"
median = "0"
avg = "0"
regist = "2016/09/21 00:55"
update = "2016/09/21 00:55"

[[entries]]
no = "17"
name = "Rosenburg Engel"
team = "CINDERELLA PROJECT"
title = "闇ノ華ト光ヲ導ク者ノ平行世界"
size = "0 KB"
addr = ["https://www.youtube.com/watch?v=4Y7KvjytfAc"]
genre = "Cappriccio"
impr = "0"
total = "0"
median = "0"
avg = "0"
regist = "2016/09/21 00:55"
update = "2016/09/21 00:55"

[[entries]]
no = "18"
name = "CANDY ISLAND"
team = "CINDERELLA PROJECT"
title = "あめ×2思い"
size = "0 KB"
addr = ["https://www.youtube.com/watch?v=nUdy_zK_yi0"]
genre = "Electro Pop"
impr = "0"
total = "0"
median = "0"
avg = "0"
regist = "2016/09/21 00:56"
update = "2016/09/21 00:56"

[[entries]]
no = "19"
name = "凸レーション"
team = "CINDERELLA PROJECT"
title = "DELIGHTFUL☆DREAM"
size = "0 KB"
addr = ["https://www.youtube.com/watch?v=0aibAcsR-1w"]
genre = "HAPPY"
impr = "0"
total = "0"
median = "0"
avg = "0"
regist = "2016/09/21 00:56"
update = "2016/09/21 00:56"

[[entries]]
no = "20"
name = "*（Asterisk）"
team = "CINDERELLA PROJECT"
title = "Lonely Cat"
size = "0 KB"
addr = ["https://www.youtube.com/watch?v=eeXEbcQUg_Y"]
genre = "House"
impr = "0"
total = "0"
median = "0"
avg = "0"
regist = "2016/09/21 00:56"
update = "2017/10/15 13:57"

[[entries]]
no = "21"
name = "おみー"
team = "チーム提督業"
title = "水無月 ～Glory Moon"
size = "14300 KB"
addr = ["https://www.dropbox.com/s/r8uyaf0f39csi3m/%5Bomi%5Dglory_moon_ogg.zip?dl=1"]
genre = "June Trance"
impr = "4"
total = "3130"
median = "830"
avg = "782.5"
regist = "2016/09/22 19:53"
update = "2016/09/30 22:53"

[[entries]]
no = "22"
name = "nemumi"
team = "nemumi"
title = "test"
size = "0 KB"
addr = []
genre = "test"
impr = "0"
total = "0"
median = "0"
avg = "0"
regist = "2016/09/23 02:32"
update = "2016/09/23 11:16"

[[entries]]
no = "27"
name = "HyuN & Ritoru"
team = "Xenopus"
title = "Fly Again"
size = "206848 KB"
addr = ["https://drive.google.com/file/d/0BxdWLxHTZvueREprdXZYM0N0Q3c/view"]
genre = "HAPPY HARDCORE"
impr = "1"
total = "900"
median = "900"
avg = "900"
regist = "2016/09/24 14:20"
update = "2016/09/27 21:05"

[[entries]]
no = "28"
name = "Tec:Naga"
team = "カオスな曲を作る人がチームを作ろうと思ったらいろんな人が集まってきてカオスなチームになってしまった件について。"
title = "Hello!!!(予告)"
size = "0 KB"
addr = ["http://"]
genre = "Chaos core"
impr = "0"
total = "0"
median = "0"
avg = "0"
regist = "2016/09/24 14:54"
update = "2016/09/24 21:26"

[[entries]]
no = "29"
name = "Artmospia"
team = "Team EXiT"
title = "White Film"
size = "64000 KB"
addr = ["https://soundcloud.com/artmospia/bofu2016-artmospia-white-film"]
genre = "PROGRESSIVE HOUSE"
impr = "0"
total = "0"
median = "0"
avg = "0"
regist = "2016/09/24 19:54"
update = "2016/09/24 20:05"

[[entries]]
no = "30"
name = "KarK"
team = "カオスな曲を作る人がチームを作ろうと思ったらいろんな人が集まってきてカオスなチームになってしまった件について。"
title = "lumiere"
size = "0 KB"
addr = ["http://"]
genre = "Drumstep"
impr = "1"
total = "950"
median = "950"
avg = "950"
regist = "2016/09/26 16:45"
update = "2016/09/28 17:24"

[[entries]]
no = "31"
name = "flicknote"
team = "TEAM-BMSON"
title = "#15secsongchallenge"
size = "5900 KB"
addr = ["https://bemuse.ninja/?server=https://be-music.spacet.me/test/"]
genre = "15sec"
impr = "0"
total = "0"
median = "0"
avg = "0"
regist = "2016/09/29 01:25"
update = "2016/09/29 01:28"

[[entries]]
no = "32"
name = "lee ium"
team = "NAME"
title = "Rise"
size = "20700 KB"
addr = ["https://drive.google.com/file/d/0B62YjCNNSMlyc2hIczRtTGtUU1U/view?usp=sharing"]
genre = "trancecore"
impr = "0"
total = "0"
median = "0"
avg = "0"
regist = "2016/10/02 00:03"
update = "2016/10/02 00:03"

[[entries]]
no = "34"
name = "h0pe"
team = "DREAMING"
title = "OCEAN"
size = "11673 KB"
addr = ["https://www.dropbox.com/s/f05axt6sdmp74wq/%5Bh0pe%5DOCEAN.zip?dl=1"]
genre = "TECHNO"
impr = "0"
total = "0"
median = "0"
avg = "0"
regist = "2016/10/02 12:20"
update = "2016/10/02 12:20"

[[entries]]
no = "35"
name = "Muu"
team = 'TEAM "HYPER" ELEPRO'
title = "The Ki9"
size = "117000 KB"
addr = ["https://www.dropbox.com/s/3esawn1wxkrm609/The_Ki9.zip?dl=1"]
genre = "高速核"
impr = "0"
total = "0"
median = "0"
avg = "0"
regist = "2016/10/02 20:36"
update = "2016/10/02 20:36"

[[entries]]
no = "36"
name = "Muu"
team = 'TEAM "HYPER" ELEPRO'
title = "The_Ki9"
size = "17000 KB"
addr = ["https://www.dropbox.com/s/3esawn1wxkrm609/The_Ki9.zip?dl=1"]
genre = "高速核"
impr = "0"
total = "0"
median = "0"
avg = "0"
regist = "2016/10/02 22:36"
update = "2016/10/02 22:36"

[[entries]]
no = "37"
name = "flicknote"
team = "TEAM-BMSON"
title = "RECURSIVE DESCENT"
size = "4950 KB"
addr = ["https://dl.dropboxusercontent.com/u/25097375/BMS/2016/recursivedescent.zip"]
genre = "TRANCE"
impr = "0"
total = "0"
median = "0"
avg = "0"
regist = "2016/10/02 23:36"
update = "2016/10/02 23:42"
