[[entries]]
no = "1"
name = "有賀 澪"
title = "Defeat awaken battle ship"
size = "35135 KB"
addr = ["https://www.dropbox.com/s/s1i959igi9m5xu6/%5B%E6%9C%89%E8%B3%80%E6%BE%AA%5DDefeatawakenbattleship.zip?dl=1"]
genre = "SYMPHONIC SCHRANZ"
impr = "29"
total = "105"
median = "3"
avg = "3.62"
regist = "2017/02/18 00:01"
update = "2017/10/27 00:50"

[[entries]]
no = "2"
name = "夢遊病"
title = "Tripping In the Dream"
size = "2160 KB"
addr = ["https://www.axfc.net/u/3777079"]
genre = "( ~ω~)ｽﾔｧ…"
impr = "23"
total = "40"
median = "2"
avg = "1.73"
regist = "2017/02/18 00:02"
update = "2017/03/13 23:59"

[[entries]]
no = "3"
name = "結月ゆかり and アトラnティス"
title = "転生ディザイア"
size = "22702 KB"
addr = ["https://www.dropbox.com/s/2uvbqqa8xqp4cow/Desire_ogg.rar?dl=1"]
genre = "ANIME POP"
impr = "28"
total = "101"
median = "4"
avg = "3.6"
regist = "2017/02/18 00:07"
update = "2017/03/15 19:19"

[[entries]]
no = "4"
name = "music:kingfisher/movie:tatazu"
title = "MeZaMe"
size = "12000 KB"
addr = ["http://fast-uploader.com/file/7042902699327/"]
genre = "Tribal Electro"
impr = "28"
total = "128"
median = "5"
avg = "4.57"
regist = "2017/02/18 01:04"
update = "2017/03/14 12:54"

[[entries]]
no = "5"
name = "犬塚モリタカ"
title = "Lone Belief"
size = "33725 KB"
addr = ["https://mega.nz/#F!IP4iTAyI!jkwvNbkccH-EUATbGI4SWg"]
genre = "Liquid Drum'n'core"
impr = "25"
total = "74"
median = "3"
avg = "2.96"
regist = "2017/02/18 01:06"
update = "2018/05/03 00:14"

[[entries]]
no = "6"
name = "futonbound"
title = "Sugary Drive"
size = "10700 KB"
addr = ["https://drive.google.com/open?id=0ByuhzURFLmsTdW5wNU90N2Ytb00"]
genre = "HAPPY HARDCORE"
impr = "27"
total = "89"
median = "3"
avg = "3.29"
regist = "2017/02/18 03:18"
update = "2017/03/14 01:52"

[[entries]]
no = "7"
name = "小坂みゆ (music. NAIKI)"
title = "CAN☆D☆POP"
size = "28222 KB"
addr = ["http://llllllllllll.sakura.ne.jp/djtakuan/b_BMS/candpop.zip"]
genre = "J-HAPPY HARDCORE"
impr = "29"
total = "112"
median = "4"
avg = "3.86"
regist = "2017/02/18 14:56"
update = "2017/03/14 00:33"

[[entries]]
no = "8"
name = "Big Wolf"
title = "Re:ConstRuct"
size = "30700 KB"
addr = ["http://fast-uploader.com/file/7042963423447/"]
genre = "ArtCore"
impr = "27"
total = "93"
median = "4"
avg = "3.44"
regist = "2017/02/18 18:08"
update = "2017/03/13 23:58"

[[entries]]
no = "9"
name = "琴瀬悠"
title = "Holy Lightbringer"
size = "14600 KB"
addr = [
    "http://fast-uploader.com/file/7042978351126/",
    "※BMS本体(BGI非同梱)",
    "http://fast-uploader.com/file/7044379444327/",
    "※追加BGI,readme.txt(BMS本体のものに上書きして下さい)",
    "2019.03.31 リンク切れのため再UPしました",
    "https://www.dropbox.com/s/dy6souqmfu3ghyd/%5B%E7%90%B4%E7%80%AC%E6%82%A0%5Dholylightbringer_ogg_190331.zip?dl=1",
    "※追加BGI適用済み完成版のデータになります",
]
genre = "ANI POP"
impr = "33"
total = "151"
median = "5"
avg = "4.57"
regist = "2017/02/18 22:05"
update = "2019/03/31 14:00"

[[entries]]
no = "10"
name = "parasitic S+f feat.ラテ"
title = "Crossing Hearts"
size = "36000 KB"
addr = ["https://www.dropbox.com/s/79dc8azoab7wofp/crossing_hearts_ogg.zip?dl=1"]
genre = "Digital-J-Pop"
impr = "30"
total = "121"
median = "4"
avg = "4.03"
regist = "2017/02/18 23:43"
update = "2017/03/14 01:50"

[[entries]]
no = "11"
name = "Sheryl"
title = "Shelah"
size = "18000 KB"
addr = ["https://www.axfc.net/u/3777462"]
genre = "HARDSTYLE"
impr = "28"
total = "98"
median = "3"
avg = "3.5"
regist = "2017/02/19 00:01"
update = "2017/03/14 00:13"

[[entries]]
no = "12"
name = "D632"
title = "wHO nEEDS mUSIC"
size = "7000 KB"
addr = ["http://fast-uploader.com/file/7042999972218"]
genre = "DIGITAL HARDCORE"
impr = "25"
total = "41"
median = "1"
avg = "1.64"
regist = "2017/02/19 04:05"
update = "2017/03/14 01:38"

[[entries]]
no = "13"
name = "XE7"
title = "ΛVEИiR"
size = "63000 KB"
addr = ["https://www.dropbox.com/s/zhjc9zbi2haln4v/%5BXE7%5DAVENIR.zip?dl=0"]
genre = "Progressive House"
impr = "29"
total = "130"
median = "5"
avg = "4.48"
regist = "2017/02/19 14:29"
update = "2017/03/14 22:23"

[[entries]]
no = "14"
name = "JP-8 Eater"
title = "THE SERVANT OF EVIL"
size = "66503 KB"
addr = ["https://www.dropbox.com/s/hfw7g4qslxplcwe/THE%20SERVANT%20OF%20EVIL.zip?dl=1"]
genre = "Trance"
impr = "25"
total = "102"
median = "4"
avg = "4.08"
regist = "2017/02/19 14:39"
update = "2017/03/13 23:58"

[[entries]]
no = "15"
name = "haikawa hldgs"
title = "kamal daura"
size = "8846 KB"
addr = [
    "http://fast-uploader.com/file/7043064392180/",
    "http://www.mediafire.com/file/shwrl8ehcb0brrr/haikawa_kamardaura.zip",
]
genre = "Indian Ragga Jungle"
impr = "24"
total = "97"
median = "4"
avg = "4.04"
regist = "2017/02/19 15:17"
update = "2017/03/13 23:58"

[[entries]]
no = "16"
name = "sahuagin(bg:yabuhebi)"
title = "我ガ求ムハ気高キ蛇ノ刃"
size = "30712 KB"
addr = ["http://fast-uploader.com/file/7043040107379/"]
genre = "ORIENTAL ART"
impr = "24"
total = "84"
median = "4"
avg = "3.5"
regist = "2017/02/19 15:43"
update = "2017/03/14 07:51"

[[entries]]
no = "17"
name = "Acet."
title = "Strange Fire"
size = "1273 KB"
addr = [
    "http://www.axfc.net/u/3777823?key=WPIV",
    "BGA有り（13,983 kB）",
    "https://drive.google.com/file/d/1PGy79GWpFuE1kDEuKDlbV_0DeiUyGvv4/view?usp=sharing",
    "BGA有りWAV版（18,231 kB）",
    "https://drive.google.com/file/d/1F9BIR7xZVdVv27cX6-I3Zwmud9Fm6WMD/view?usp=sharing",
]
genre = "Drum'n'Bass"
impr = "20"
total = "55"
median = "3"
avg = "2.75"
regist = "2017/02/19 20:33"
update = "2017/11/11 14:32"

[[entries]]
no = "18"
name = "QM"
title = "Nokin Classics"
size = "5500 KB"
addr = ["https://www.axfc.net/u/3777866"]
genre = "Hardstyle"
impr = "26"
total = "95"
median = "4"
avg = "3.65"
regist = "2017/02/19 21:25"
update = "2017/03/13 23:58"

[[entries]]
no = "19"
name = "Kanon"
title = "Fortuna"
size = "20000 KB"
addr = ["https://www.dropbox.com/s/9chu8mf0vtrwfvd/%5BKanon%5DFortuna_ogg.zip?dl=1"]
genre = "WITCHES PRAY"
impr = "24"
total = "90"
median = "4"
avg = "3.75"
regist = "2017/02/19 21:41"
update = "2017/05/09 00:08"

[[entries]]
no = "20"
name = "Akashina"
title = "Bit Charger"
size = "6887 KB"
addr = ["http://nobjective.com/akashina_bit.zip"]
genre = "Full On"
impr = "23"
total = "80"
median = "3"
avg = "3.47"
regist = "2017/02/19 23:01"
update = "2017/03/13 23:57"

[[entries]]
no = "21"
name = "Mystic"
title = "White Corvus"
size = "11549 KB"
addr = ["https://drive.google.com/open?id=0B7qCw4hNijr4emJFRkdhSXFUZkE"]
genre = "CHIP TUNE"
impr = "21"
total = "89"
median = "4"
avg = "4.23"
regist = "2017/02/19 23:04"
update = "2018/02/14 04:48"

[[entries]]
no = "22"
name = "Multipleton / BGA: Trompeuse"
title = "F4C4D3"
size = "66314 KB"
addr = ["https://www.dropbox.com/s/aeclmhlkjfxil19/%5BMultipleton%5DF4C4D3.rar?dl=1"]
genre = "UK HARDCORE"
impr = "31"
total = "138"
median = "5"
avg = "4.45"
regist = "2017/02/19 23:27"
update = "2017/03/13 23:58"

[[entries]]
no = "23"
name = "The Predatiger"
title = "Mankind Hunting Games"
size = "15524 KB"
addr = ["http://www.mediafire.com/file/qz6pkqa9tqwzqyi/mankind_hunting_game.zip"]
genre = "DARK SYNTHWAVE /  AMBIENT"
impr = "21"
total = "55"
median = "2"
avg = "2.61"
regist = "2017/02/19 23:29"
update = "2017/03/14 03:47"

[[entries]]
no = "24"
name = "IZ Nit Feat. CH Wit"
title = "John and Robert again lied"
size = "12748 KB"
addr = ["https://www.axfc.net/u/3778003"]
genre = "UK GARAGE"
impr = "24"
total = "107"
median = "4.5"
avg = "4.45"
regist = "2017/02/19 23:47"
update = "2017/03/13 23:59"

[[entries]]
no = "25"
name = "namaboko"
title = "tashinami"
size = "6991 KB"
addr = ["https://srv09.bitsend.jp/download/4a82055e4c6f613390b770f3f44deacf.html"]
genre = "Scam/Lolicore"
impr = "20"
total = "68"
median = "3"
avg = "3.4"
regist = "2017/02/19 23:50"
update = "2017/03/13 23:59"

[[entries]]
no = "26"
name = "正体不明"
title = "行方不明"
size = "9300 KB"
addr = ["https://www.axfc.net/u/3778175"]
genre = "意味不明"
impr = "18"
total = "50"
median = "3"
avg = "2.77"
regist = "2017/02/19 23:51"
update = "2017/03/13 23:59"

[[entries]]
no = "27"
name = "Erika Itsumi"
title = "Phalaenopsis (radio edit)"
size = "20000 KB"
addr = [
    "OGG版 本体:",
    "https://drive.google.com/open?id=0B49UbytSjfMBdEpybWhSelZ4RGs",
    "Another Hyper差分  ：",
    "https://drive.google.com/open?id=0B49UbytSjfMBd3BTOURVY2g0bkE",
]
genre = "Progressive Trance"
impr = "21"
total = "69"
median = "3"
avg = "3.28"
regist = "2017/02/19 23:55"
update = "2017/03/13 23:59"

[[entries]]
no = "28"
name = "LIEFROG"
title = "恋愛と贅沢と資本主義"
size = "20000 KB"
addr = [
    "http://fast-uploader.com/file/7043856946250/",
    "(☆6,☆9,☆11)",
    "---------------------",
    "http://fast-uploader.com/file/7043071843814/",
    "(☆9のみ）",
    "http://fast-uploader.com/file/7043856794060/",
    "(☆6,☆11追加譜面のみ)",
]
genre = "GOTHIC INSTRUMENTAL"
impr = "21"
total = "84"
median = "4"
avg = "4"
regist = "2017/02/19 23:58"
update = "2017/03/14 01:48"

[[entries]]
no = "29"
name = "Da's mach System"
title = "ME AND BΦΦΦYS"
size = "68500 KB"
addr = ["https://www.axfc.net/u/3778020"]
genre = "Future Bass"
impr = "20"
total = "66"
median = "3"
avg = "3.3"
regist = "2017/02/19 23:59"
update = "2017/03/14 03:27"

[[entries]]
no = "30"
name = "Pink Elephant"
title = "PASSED OUT"
size = "53146 KB"
addr = ["http://www.axfc.net/u/3777917.zip"]
genre = "Electro House / Bass House"
impr = "23"
total = "86"
median = "4"
avg = "3.73"
regist = "2017/02/19 23:59"
update = "2017/03/14 03:28"
