[[entries]]
no = "1"
name = "Sakamiya feat.黄身"
title = "Knock my heart -Sakamiya RMX-"
size = "16619 KB"
addr = ["https://www.dropbox.com/s/sf2q9kwh0xzkdgd/KnockmyheartRMX_sakamiya_HQogg.zip?dl=1"]
genre = "Digital-J-Trance"
impr = "21"
total = "74"
median = "0"
avg = "3.52"
regist = "2017/04/28 00:01"
update = "2017/10/27 00:50"

[[entries]]
no = "2"
name = "変異竜。"
title = "DECISIVE (Sky Dragon Remix)"
size = "33882 KB"
addr = [
    "ogg 33882kb",
    "https://goo.gl/aqEUyc",
    "wav 125549kb",
    "https://goo.gl/HGvN6o",
]
genre = "GAME MUSIC/ART CORE"
impr = "18"
total = "51"
median = "1"
avg = "2.83"
regist = "2017/04/28 00:04"
update = "2017/06/05 22:27"

[[entries]]
no = "3"
name = "DEMK feat.猫村いろは"
title = "やさしい両手"
size = "11295 KB"
addr = ["http://demk.net/yasasiiryoute.rar"]
genre = "GAMESONG COVER"
impr = "22"
total = "76"
median = "0"
avg = "3.45"
regist = "2017/04/28 00:23"
update = "2017/05/28 23:58"

[[entries]]
no = "4"
name = "Ogu"
title = "星の入り江"
size = "85864 KB"
addr = ["http://ogut.sakura.ne.jp/temp/BMS_hosinoirie.ZIP"]
genre = "ambient"
impr = "20"
total = "58"
median = "1"
avg = "2.9"
regist = "2017/04/28 00:23"
update = "2017/05/29 01:28"

[[entries]]
no = "5"
name = "MIDI：た人 / BMS：9-zen"
title = "呑んべぇのレムリア"
size = "20635 KB"
addr = ["https://drive.google.com/uc?export=download&id=1kbOAh5SqHkGHZAEBZ_BhFjciSdWRuwID"]
genre = "黄昏酒場"
impr = "20"
total = "45"
median = "2"
avg = "2.25"
regist = "2017/04/28 00:24"
update = "2022/05/27 10:29"

[[entries]]
no = "6"
name = "Chlorargyrite"
title = "Liberate from Nebula"
size = "30895 KB"
addr = ["https://www.dropbox.com/s/c9nw9ptpfejixrx/%5BChlorargyrite%5D%20Liberate%20from%20Nebula.zip?dl=1"]
genre = "SYMPHONIC ROCK"
impr = "19"
total = "46"
median = "2"
avg = "2.42"
regist = "2017/04/28 01:08"
update = "2017/06/01 16:10"

[[entries]]
no = "7"
name = "HoQ-10"
title = "Hateno House"
size = "9935 KB"
addr = ["https://www.dropbox.com/s/91vduj164vinmga/HoQ-10%20-%20Hateno%20House.zip?dl=0"]
genre = "House"
impr = "16"
total = "45"
median = "0"
avg = "2.81"
regist = "2017/04/28 11:27"
update = "2017/05/28 23:41"

[[entries]]
no = "8"
name = "アドヴェリタス"
title = "KiZuNa"
size = "13586 KB"
addr = ["https://www.dropbox.com/s/52wi0w3y9i9hxqk/suzaku3bms.rar?dl=0"]
genre = "Hardcore"
impr = "15"
total = "35"
median = "0"
avg = "2.33"
regist = "2017/04/28 20:01"
update = "2017/05/28 22:27"

[[entries]]
no = "9"
name = "DJ TAKUAN"
title = "天外魔境ZEROの大ボス戦のBGMをサイケっぽくアレンジしたやつ(Original Mix)"
size = "12100 KB"
addr = ["http://llllllllllll.sakura.ne.jp/djtakuan/b_BMS/tengai.zip"]
genre = "DARK PSYCHEDELIC TRANCE"
impr = "19"
total = "61"
median = "0.5"
avg = "3.21"
regist = "2017/04/29 00:30"
update = "2017/05/28 22:27"

[[entries]]
no = "10"
name = "t-soach"
title = "ライバルとあそぼう"
size = "11214 KB"
addr = ["https://www.dropbox.com/s/zerr3poeymlm3gb/puyo_rival%5Bogg%5D.zip?dl=1"]
genre = "GAME MUSIC"
impr = "18"
total = "61"
median = "0"
avg = "3.38"
regist = "2017/04/29 01:24"
update = "2017/05/28 22:27"

[[entries]]
no = "11"
name = "さんまのこぼね"
title = "午後の勇者"
size = "28315 KB"
addr = ["https://www.dropbox.com/s/6k1qzbvd40bhw0n/%E5%8D%88%E5%BE%8C%E3%81%AE%E5%8B%87%E8%80%85.zip?dl=0"]
genre = "chillout"
impr = "17"
total = "47"
median = "0"
avg = "2.76"
regist = "2017/04/30 00:45"
update = "2017/05/28 22:27"

[[entries]]
no = "12"
name = "落雁"
title = "終わる世界にお別れを"
size = "2680 KB"
addr = ["http://fantasicnotes.net/bms/LUCK24_GC.zip"]
genre = "最強ガーディアン・クルス"
impr = "16"
total = "31"
median = "0"
avg = "1.93"
regist = "2017/04/30 16:51"
update = "2017/05/28 22:27"

[[entries]]
no = "13"
name = "○△□"
title = "RPGツクール2 BGM7"
size = "6700 KB"
addr = ["http://toriaezu-hp.sakura.ne.jp/event_bms.html"]
genre = "GAME MUSIC"
impr = "22"
total = "73"
median = "0"
avg = "3.31"
regist = "2017/04/30 18:57"
update = "2017/05/30 00:17"

[[entries]]
no = "14"
name = "ライプリヒ製薬 (ABOxxx)"
title = "Karma - Tief Blau 2017 Null -"
size = "7500 KB"
addr = ["https://www.dropbox.com/s/5ba72ojvh0h467v/aaa_ever17_karma_tief_blau_2017_null.zip?dl=0"]
genre = "Ambient"
impr = "19"
total = "52"
median = "1"
avg = "2.73"
regist = "2017/05/01 00:00"
update = "2017/05/29 01:13"

[[entries]]
no = "15"
name = "ビンビンラディン"
title = "Come To Me -BINBIN REMIX-"
size = "23413 KB"
addr = ["https://www.axfc.net/u/3801521/binbin"]
genre = "Dance"
impr = "22"
total = "68"
median = "1"
avg = "3.09"
regist = "2017/05/01 00:40"
update = "2018/03/26 10:17"

[[entries]]
no = "16"
name = "WesS_Gik372"
title = "カードロボトル"
size = "8916 KB"
addr = [
    "wav  8916KB",
    "https://www.dropbox.com/s/w19kqokcy0q6dxy/Gik01_cardrobottle_wav.zip?dl=0",
    "ogg  2488KB",
    "https://www.dropbox.com/s/f10z5uua79zx385/Gik01_cardrobottle_ogg.zip?dl=0",
]
genre = "GAME MUSIC / Chiptune"
impr = "18"
total = "54"
median = "0"
avg = "3"
regist = "2017/05/02 23:40"
update = "2017/05/29 00:27"

[[entries]]
no = "17"
name = "Ogu"
title = "MODEL KJ2"
size = "90714 KB"
addr = ["http://ogut.sakura.ne.jp/temp/BMS_MODELKJ2.ZIP"]
genre = "Heavy Metal"
impr = "21"
total = "69"
median = "1"
avg = "3.28"
regist = "2017/05/03 01:44"
update = "2017/05/29 01:26"

[[entries]]
no = "18"
name = "loz"
title = "Loony Princess"
size = "82219 KB"
addr = ["https://www.axfc.net/u/3802347"]
genre = "HARD ELECTROPOP"
impr = "17"
total = "45"
median = "0"
avg = "2.64"
regist = "2017/05/03 09:39"
update = "2017/05/28 22:41"

[[entries]]
no = "19"
name = "idzuchi takl"
title = "遠征～当てもない一人旅"
size = "15645 KB"
addr = ["http://www.dropbox.com/s/ytow02dtbxgy077/Ensei_HItoritabi_idzc_VGBMS.zip?dl=1"]
genre = "FUSION"
impr = "21"
total = "70"
median = "0"
avg = "3.33"
regist = "2017/05/03 18:35"
update = "2017/05/28 22:28"

[[entries]]
no = "20"
name = "Ju_E"
title = "Even If You Leave Me"
size = "13190 KB"
addr = [
    "https://drive.google.com/open?id=0Bxz8QkAsI7tFVXY2R0tjZjNaeXc",
    "(WAV, 114MB)",
    "https://drive.google.com/open?id=0Bxz8QkAsI7tFLXhlMXNoN0FCbzA",
    "(OGG, 12.8MB)",
]
genre = "Pokémon Mystery Dungeon"
impr = "15"
total = "29"
median = "0"
avg = "1.93"
regist = "2017/05/03 23:34"
update = "2017/05/28 22:28"

[[entries]]
no = "21"
name = "alt"
title = "まくらもとのStarbow"
size = "3700 KB"
addr = ["https://www.dropbox.com/s/32xohvwegqoqa5y/Starbow.zip?dl=0"]
genre = "Game music / Drum & Bass"
impr = "17"
total = "42"
median = "0"
avg = "2.47"
regist = "2017/05/04 14:12"
update = "2017/05/29 14:34"

[[entries]]
no = "22"
name = "Nakaith"
title = "Alphys(Nakaith Remix)"
size = "25527 KB"
addr = ["https://mega.nz/#F!IP4iTAyI!jkwvNbkccH-EUATbGI4SWg"]
genre = "Future Footwork"
impr = "16"
total = "48"
median = "1"
avg = "3"
regist = "2017/05/06 01:22"
update = "2018/05/03 00:15"

[[entries]]
no = "23"
name = "9-zen"
title = "Top Gear GO-GO-GO!"
size = "20412 KB"
addr = ["https://drive.google.com/uc?export=download&id=16A8ZGeZWeg3bLFh6Sf_0GF3qioORHHW3"]
genre = "スクリューブレイカー 轟振どりるれろ"
impr = "19"
total = "60"
median = "1"
avg = "3.15"
regist = "2017/05/06 10:42"
update = "2022/05/27 10:26"

[[entries]]
no = "24"
name = "kitUNE"
title = "SUBMARiNE Pt.33"
size = "14196 KB"
addr = ["https://www.dropbox.com/s/zo4rh6odx2luci1/SUBMARiNE%20Pt.33.zip?dl=1"]
genre = "Super Bombeat Style"
impr = "17"
total = "41"
median = "0"
avg = "2.41"
regist = "2017/05/06 12:24"
update = "2017/05/28 22:29"

[[entries]]
no = "25"
name = "れおん"
title = "★☆はるかぜオールスター☆★"
size = "78967 KB"
addr = [
    "https://drive.google.com/file/d/0B4RKpMA1a_r8Z1gtYVZ5cWFZMlk/view?usp=sharing",
    "（WAV版：78967KB）",
    "https://drive.google.com/file/d/0B4RKpMA1a_r8VGEtS25xS3JNd0E/view?usp=sharing",
    "（OGG版：17054KB）",
]
genre = "Memorial Medley"
impr = "30"
total = "112"
median = "0"
avg = "3.73"
regist = "2017/05/07 00:30"
update = "2017/05/30 09:03"

[[entries]]
no = "26"
name = "MA$AKI"
title = "Wrapped in Black -Ravers Super Rush mix-"
size = "2562 KB"
addr = ["https://www.dropbox.com/s/uc5fcb64rjtco6v/Wrapp.rar?dl=0"]
genre = "RAVERS TECHNO SPEED"
impr = "15"
total = "40"
median = "0"
avg = "2.66"
regist = "2017/05/07 03:23"
update = "2017/05/28 22:29"

[[entries]]
no = "27"
name = "KITUNE"
title = "Supporting Me(pressure Mix) -BMS Edit-"
size = "14464 KB"
addr = ["https://www.dropbox.com/s/krr9b4u1y3uvc3x/Supporting%20Me%28pressure%20Mix%29%20-BMS%20Edit-.zip?dl=1"]
genre = "BIG BEAT"
impr = "14"
total = "37"
median = "0"
avg = "2.64"
regist = "2017/05/07 14:33"
update = "2017/05/28 22:29"

[[entries]]
no = "28"
name = "exclusion"
title = "Endless Way"
size = "9858 KB"
addr = [
    "https://www.dropbox.com/s/937a4hvcgxghd4v/endless_way_ogg.zip?dl=0",
    "(ミラー)",
    "https://drive.google.com/open?id=0B2H4n5O4rM2Kd2RnQ1hqRWp6N1U",
]
genre = "GAME MUSIC"
impr = "19"
total = "59"
median = "0"
avg = "3.1"
regist = "2017/05/07 16:00"
update = "2017/05/28 22:29"

[[entries]]
no = "29"
name = "アレンジ:momo★yama"
title = "Spectronizer-舞踏戦隊のうた- (momo★yama J-EUROBEAT REMIX)"
size = "43881 KB"
addr = ["https://www.dropbox.com/s/lxj7hjze9ecp4vo/momoyama_Spectronizer.rar?dl=0"]
genre = "CD屋によくある「特撮ユーロビートミックス」ってオムニバスCDに入ってそうな奴"
impr = "21"
total = "67"
median = "0"
avg = "3.19"
regist = "2017/05/07 17:34"
update = "2017/05/28 23:17"

[[entries]]
no = "30"
name = "Vulpes"
title = "Dance Through the Danger [proto-inst mix ver.]"
size = "12128 KB"
addr = ["https://www.dropbox.com/s/05j66oj1q2rykd3/Dance%20Through%20the%20Danger%20%5Bproto-inst%20mix%20ver.%5D.zip?dl=1"]
genre = "BELLY DANCE SPEED"
impr = "17"
total = "44"
median = "0"
avg = "2.58"
regist = "2017/05/07 19:21"
update = "2017/05/28 22:29"

[[entries]]
no = "31"
name = "CirCy"
title = "HYDLIDE Field (CC mix)"
size = "1543 KB"
addr = [
    "http://drive.google.com/file/d/0B7rN2JU3m0plaHFiUjAyb3NhMG8/view?usp=sharing",
    "WAV版（7,064 kB）",
    "http://drive.google.com/file/d/0B7rN2JU3m0plcVdhQVlZSUVBQzg/view?usp=sharing",
]
genre = "garage mix / game music"
impr = "17"
total = "40"
median = "0"
avg = "2.35"
regist = "2017/05/07 21:09"
update = "2017/05/28 23:42"

[[entries]]
no = "32"
name = "RYO-K a.k.a Kanikama"
title = "Super Sonic Racing(Full-throttle MIX)"
size = "18613 KB"
addr = ["https://www.dropbox.com/s/v63w3fparppnmg9/%5BRYO-K%5DSuperSonicRacing%28Full-throttle%20MIX%29.zip?dl=1"]
genre = "Speedy Dance Pop"
impr = "17"
total = "53"
median = "0"
avg = "3.11"
regist = "2017/05/07 21:41"
update = "2017/05/28 22:29"

[[entries]]
no = "33"
name = "きぬきみ"
title = "クレイジーシティを散歩して"
size = "16789 KB"
addr = ["https://www.dropbox.com/s/naywdqj3hggoj8k/crazycity.zip?dl=1"]
genre = "Motown Beats /Funk Shuffle"
impr = "19"
total = "61"
median = "0"
avg = "3.21"
regist = "2017/05/07 21:48"
update = "2017/05/28 22:30"

[[entries]]
no = "34"
name = "izeiru"
title = "ザ グレイトバトルV ステージ1"
size = "7887 KB"
addr = ["https://www.dropbox.com/s/6epcvxk48y4cm4x/izeiru_great_battleV_ogg.zip?dl=0"]
genre = "GameMusic"
impr = "14"
total = "31"
median = "0"
avg = "2.21"
regist = "2017/05/07 23:05"
update = "2017/06/06 22:01"

[[entries]]
no = "35"
name = "TamaDo"
title = "Ishtar -TDRMX-"
size = "39229 KB"
addr = ["http://drive.google.com/open?id=0B3C7qRU5MILfbkY0N2FEMzdYZWs"]
genre = "Pop"
impr = "18"
total = "63"
median = "1"
avg = "3.5"
regist = "2017/05/07 23:20"
update = "2017/05/28 23:40"

[[entries]]
no = "36"
name = "SOMON"
title = "シャイニングスコーピオン ～季節大会～"
size = "4300 KB"
addr = ["https://www.dropbox.com/s/v7q140mi5gtymkq/SOMON_shining_scorpion.zip?dl=0"]
genre = "GAME MUSIC"
impr = "16"
total = "37"
median = "2"
avg = "2.31"
regist = "2017/05/07 23:24"
update = "2020/04/29 23:15"

[[entries]]
no = "37"
name = "ANKAKE"
title = "Space Zone Stage.2"
size = "1041 KB"
addr = ["http://kobako-lab.main.jp/BMS/ankake_space_zone_stage2.rar"]
genre = "GAME MUSIC"
impr = "18"
total = "48"
median = "0"
avg = "2.66"
regist = "2017/05/07 23:24"
update = "2017/05/28 22:48"

[[entries]]
no = "38"
name = "Qga"
title = "Sea coral"
size = "9545 KB"
addr = ["https://www.dropbox.com/s/mu3fvj2mo932ch4/Sea%20coral.zip?dl=1"]
genre = "Drum'n'Bass"
impr = "16"
total = "47"
median = "0"
avg = "2.93"
regist = "2017/05/07 23:31"
update = "2017/05/28 22:30"

[[entries]]
no = "39"
name = "SM-NX"
title = "FF4 Main Theme （SM-NX D&B Arrange）"
size = "13000 KB"
addr = ["http://www.dropbox.com/s/3pu7a0pvctqzfox/sm-nx_FF4main.zip?dl=1"]
genre = "Drum ＆ Bass"
impr = "15"
total = "33"
median = "0"
avg = "2.2"
regist = "2017/05/07 23:36"
update = "2017/05/28 22:30"

[[entries]]
no = "40"
name = "SM-NX"
title = "ぷよ通魔導の塔終盤（SM-NX MAIN Mix）"
size = "20000 KB"
addr = ["http://www.dropbox.com/s/kanwtowwrrjn4n9/sm-nx_puyo2main.zip?dl=1"]
genre = "MAINSTREAM HARDCORE/Hard Style"
impr = "14"
total = "32"
median = "0"
avg = "2.28"
regist = "2017/05/07 23:40"
update = "2017/05/28 22:31"

[[entries]]
no = "41"
name = "SM-NX"
title = "遠き普遍の過程（intelligence）"
size = "90000 KB"
addr = ["http://www.dropbox.com/s/i2wt47omn2y4l8g/sm-nx_huheninte.zip?dl=1"]
genre = "abstract/industrial"
impr = "14"
total = "21"
median = "0"
avg = "1.5"
regist = "2017/05/07 23:44"
update = "2017/05/28 22:31"

[[entries]]
no = "42"
name = "Ogu"
title = "My pace!!"
size = "99805 KB"
addr = ["http://ogut.sakura.ne.jp/temp/BMS_Mypace.ZIP"]
genre = "Rock"
impr = "14"
total = "38"
median = "1"
avg = "2.71"
regist = "2017/05/07 23:45"
update = "2017/05/29 01:29"

[[entries]]
no = "43"
name = "きるは"
title = "夜の向日葵小屋"
size = "11600 KB"
addr = ["https://dl.dropboxusercontent.com/s/h6wskxpcdxsgwnn/%E5%A4%9C%E3%81%AE%E5%90%91%E6%97%A5%E8%91%B5%E5%B0%8F%E5%B1%8B.zip"]
genre = "ハウス"
impr = "20"
total = "69"
median = "0"
avg = "3.45"
regist = "2017/05/07 23:57"
update = "2017/05/28 23:57"

[[entries]]
no = "44"
name = "マインクラフト博士"
title = "MINECRAFT∵ADVENTURE∴MEDLEY =C-H-I-L-L-M-I-X="
size = "77974 KB"
addr = [
    "https://www.dropbox.com/s/3tn2xmqw55lsuq2/MINECRAFT_CHILLMIX.zip?dl=1",
    "2017/5/21/8:55以前にDLされた方でPMS及びDPが欲しい方へ↓",
    "2017/5/21/8:55 이전에 DL된 분에 PMS 및 DP를 원하는 분에게↓",
    "PMS↓",
    "https://www.dropbox.com/s/iru72oqntixdkd7/MINECRAFT_CHILLMIX_PMS.zip?dl=1",
    "DP↓",
    "https://www.dropbox.com/s/abicggdvibtn34u/MINECRAFT_CHILLMIX_DP.zip?dl=1",
]
genre = "LET'S PLAY MINECRAFT!!"
impr = "24"
total = "89"
median = "0"
avg = "3.7"
regist = "2017/05/07 23:59"
update = "2017/05/28 23:48"

[[entries]]
no = "45"
name = "温泉の力"
title = "MELTY BLOOD"
size = "46000 KB"
addr = ["https://www.dropbox.com/s/mkx2qu4omu0k1et/MELTYBLOOD.zip?dl=0"]
genre = "GAME OP"
impr = "19"
total = "41"
median = "0"
avg = "2.15"
regist = "2017/05/08 00:04"
update = "2017/05/28 22:31"
