[[entries]]
no = "1"
name = "おみー Remixed by REVLIS"
title = "雪月風花 ～ Crescent Moon -BMS Edit-"
size = "96519 KB"
addr = ["https://drive.google.com/open?id=0B9bZ63dms-RtQkp3d2xtVXBuSjA"]
genre = "ARTCORE"
impr = "16"
total = "91"
median = "6"
avg = "5.68"
regist = "2017/05/13 00:02"
update = "2017/06/04 18:08"

[[entries]]
no = "2"
name = "Se-U-Ra"
title = "竜蝕のサクリファクト -storia of Arq-"
size = "64011 KB"
addr = ["https://www.axfc.net/u/3805313/arq"]
genre = "ART CORE"
impr = "21"
total = "184"
median = "9"
avg = "8.76"
regist = "2017/05/13 00:09"
update = "2017/06/04 23:10"

[[entries]]
no = "3"
name = "NA7"
title = "Euryale"
size = "7323 KB"
addr = ["https://drive.google.com/open?id=0B0cIMin-PyHXT0U2eVpST1ZENWc"]
genre = "Artcore"
impr = "18"
total = "127"
median = "7"
avg = "7.05"
regist = "2017/05/13 00:10"
update = "2017/06/04 23:00"

[[entries]]
no = "4"
name = "69 de 74"
title = "確固たる意志"
size = "50931 KB"
addr = ["https://dl.dropboxusercontent.com/s/jel9o7zvlnjgfb9/%5B69%20de%2074%5D%E7%A2%BA%E5%9B%BA%E3%81%9F%E3%82%8B%E6%84%8F%E5%BF%97_ogg.zip?dl=1"]
genre = "Drum'n'Bass"
impr = "24"
total = "219"
median = "9"
avg = "9.12"
regist = "2017/05/13 00:14"
update = "2019/07/17 15:50"

[[entries]]
no = "5"
name = "Centain"
title = "Night road"
size = "8363 KB"
addr = ["http://docs.google.com/uc?id=0B_ACOCjd9IgBNHFzLW9NM3lqUEk"]
genre = "Drum'n'bass"
impr = "20"
total = "155"
median = "8"
avg = "7.75"
regist = "2017/05/13 00:29"
update = "2017/06/04 23:37"

[[entries]]
no = "6"
name = "Juggernaut."
title = "LucifeR"
size = "35194 KB"
addr = ["https://www.dropbox.com/s/c1pwr5p24rdfq9a/%5BJuggernaut.%5D%20LucifeR.zip?dl=0"]
genre = "drum'n'bass"
impr = "18"
total = "135"
median = "8"
avg = "7.5"
regist = "2017/05/13 02:10"
update = "2017/06/04 23:33"

[[entries]]
no = "7"
name = "BJ.chika"
title = "Mysteries of the Earth"
size = "40715 KB"
addr = ["https://www.dropbox.com/s/1tzeviqa43wybpp/%5BBJ.chika%5DMysteries%20of%20the%20Earth.zip?dl=1"]
genre = "Liquid Funk"
impr = "18"
total = "119"
median = "7"
avg = "6.61"
regist = "2017/05/13 20:35"
update = "2017/06/04 23:02"

[[entries]]
no = "8"
name = "Lino Flint"
title = "From Scratch"
size = "28748 KB"
addr = ["https://www.dropbox.com/s/jtovduv5kwjjf3p/From_Scratch-Lino_Flint.zip?dl=1"]
genre = "Drum'n bass"
impr = "23"
total = "214"
median = "10"
avg = "9.3"
regist = "2017/05/13 21:30"
update = "2017/06/05 19:59"

[[entries]]
no = "9"
name = "Superbia"
title = "Entschadigung"
size = "20455 KB"
addr = ["https://www.dropbox.com/s/343o6hg8xxv5k2g/Entschadigung_Superbia.zip?dl=1"]
genre = "SACRED DnB"
impr = "20"
total = "157"
median = "8"
avg = "7.85"
regist = "2017/05/14 08:33"
update = "2017/10/27 00:52"

[[entries]]
no = "10"
name = "Nakaith"
title = "FOLLY BRAINz"
size = "14905 KB"
addr = ["https://mega.nz/#F!IP4iTAyI!jkwvNbkccH-EUATbGI4SWg"]
genre = "Drum'n'Bass"
impr = "24"
total = "203"
median = "8.5"
avg = "8.45"
regist = "2017/05/14 09:31"
update = "2018/05/03 00:15"

[[entries]]
no = "11"
name = "scamp"
title = "LU the LU"
size = "12900 KB"
addr = ["https://www.dropbox.com/s/e7ybuxq7b7pi10s/LU%20the%20LU.rar?dl=0"]
genre = "DnB"
impr = "19"
total = "113"
median = "6"
avg = "5.94"
regist = "2017/05/14 13:23"
update = "2017/06/04 23:28"

[[entries]]
no = "12"
name = "早明浦キュウゾウ"
title = "frozen over"
size = "43000 KB"
addr = ["https://drive.google.com/open?id=0B54vB6C2PQGuODlXckdJT2xwQlk"]
genre = "liquid funk"
impr = "27"
total = "260"
median = "10"
avg = "9.62"
regist = "2017/05/14 19:07"
update = "2017/06/04 23:41"

[[entries]]
no = "13"
name = "白"
title = "That's"
size = "63323 KB"
addr = [
    "BGA同梱",
    "https://drive.google.com/file/d/0ByJKPc7HPAAlbV9VV1FjaENQdms/view?usp=sharing",
    "BGA追加差分(5/19 16:00以前にDLされた方向け)",
    "https://drive.google.com/file/d/0ByJKPc7HPAAlV2VXT0FtMEYzRlE/view?usp=sharing",
]
genre = "Break beats"
impr = "22"
total = "174"
median = "8"
avg = "7.9"
regist = "2017/05/14 20:16"
update = "2017/06/04 23:13"

[[entries]]
no = "14"
name = "KIDS 2 GO HAND"
title = "Breaking the ヨッツ"
size = "9743 KB"
addr = ["https://drive.google.com/file/d/0B2TD5ZL2Mw-AQ1dRWllQcDBHZlk"]
genre = "NEUROSTEP"
impr = "19"
total = "142"
median = "8"
avg = "7.47"
regist = "2017/05/14 20:56"
update = "2017/06/05 00:33"

[[entries]]
no = "15"
name = "Felisica"
title = "Ayakashi"
size = "19170 KB"
addr = [
    "http://fuki1755.starfree.jp/bms/Ayakashi_ogg.zip",
    "(通常はこちらをどうぞ)",
    "------------------------------------------------------------------------------------",
    "旧仮BGA版",
    "http://fuki1755.starfree.jp/bms/Ayakashi_ogg_tempbga.zip",
]
genre = "Microfunk"
impr = "27"
total = "247"
median = "9"
avg = "9.14"
regist = "2017/05/14 20:57"
update = "2020/02/13 16:55"

[[entries]]
no = "16"
name = "kanoryo"
title = "幽冥クライシス"
size = "25600 KB"
addr = ["https://www.dropbox.com/s/ik55pfkj7nk3utw/%5Bkanoryo%5Dyuumei_crisis%EF%BC%BFogg.zip?dl=1"]
genre = "Gothic Crossbreed"
impr = "26"
total = "217"
median = "8.5"
avg = "8.34"
regist = "2017/05/14 21:05"
update = "2017/06/04 23:19"

[[entries]]
no = "17"
name = "TQ"
title = "Astrglare"
size = "60390 KB"
addr = ["https://www.dropbox.com/s/0fkcth7fgi73113/Astrglare_D2.zip?dl=0"]
genre = "Artcore"
impr = "18"
total = "133"
median = "7"
avg = "7.38"
regist = "2017/05/14 22:00"
update = "2017/06/04 23:49"

[[entries]]
no = "18"
name = "kohaxy"
title = "-Null-Devorted"
size = "54000 KB"
addr = ["https://www.dropbox.com/s/uku9qc9fipwfvyq/-Null-Devorted.zip?dl=0"]
genre = "NeuroFunk"
impr = "21"
total = "173"
median = "8"
avg = "8.23"
regist = "2017/05/14 23:16"
update = "2017/06/04 23:47"

[[entries]]
no = "19"
name = "Re:rive"
title = "D&G&B&P"
size = "90030 KB"
addr = ["https://www.dropbox.com/s/dx3yxkhmpoog17k/dagabap.zip?dl=0"]
genre = "Drum'n crash bass"
impr = "18"
total = "115"
median = "6.5"
avg = "6.38"
regist = "2017/05/14 23:34"
update = "2017/06/04 18:25"

[[entries]]
no = "20"
name = "Night Ruler"
title = "TAXUS"
size = "7214 KB"
addr = [
    "http://www.dropbox.com/s/7syxtpoh3dgiavg/TAXUS_idzc_DNBmsFes.zip?dl=1",
    "（17/05/16 00:27 差分適用済み）",
    "http://www.dropbox.com/s/f9hni5p9jyq7cxt/TAXUS_sabun.zip?dl=1",
    "（追加差分）",
]
genre = "ALTERNATIVE DRUM'N'BASS"
impr = "22"
total = "189"
median = "8.5"
avg = "8.59"
regist = "2017/05/14 23:52"
update = "2017/06/04 23:41"

[[entries]]
no = "21"
name = "KIRI"
title = "sparkling wind"
size = "2800 KB"
addr = ["https://www.dropbox.com/s/szu5c6vwm9jl7s4/sparkling%20wind-KIRI-%20another%2CBGI%E8%BF%BD%E5%8A%A0%E7%89%88.zip?dl=1"]
genre = "Drum'n'bass"
impr = "19"
total = "127"
median = "7"
avg = "6.68"
regist = "2017/05/14 23:54"
update = "2017/06/04 23:31"

[[entries]]
no = "22"
name = "Naukorin"
title = "Widespread Belief"
size = "19547 KB"
addr = [
    "https://drive.google.com/open?id=0ByQrLptYUjKXQldRaV8zQ3NuckU",
    "(最終版)",
    "https://drive.google.com/open?id=0ByQrLptYUjKXUzhLT1JTSnB1T1E",
    "(追加差分 - 05/16 Update)",
]
genre = "Drum ('n') Bass"
impr = "0"
total = "0"
median = "3"
avg = "3"
regist = "2017/05/14 23:59"
update = "2017/05/29 01:43"

[[entries]]
no = "23"
name = "LU"
title = "waterfossil(original:undertale waterfall)"
size = "37644 KB"
addr = ["http://gensoukyousoukyoku.nekokan.dyndns.info/7-LU-waterfossil.rar"]
genre = "SKULLSTEP"
impr = "22"
total = "201"
median = "9"
avg = "9.13"
regist = "2017/05/15 00:01"
update = "2017/06/04 23:39"
