[[entries]]
no = "1"
name = "keroco"
title = "LINE RACE"
size = "6124 KB"
addr = ["https://drive.google.com/uc?id=16YAKUlPL7LZ_R9KimdG7GytlbpObUKYZ"]
genre = "NullpoMino"
impr = "11"
total = "55000"
median = "0"
avg = "5000"
regist = "2017/12/24 00:28"
update = "2023/02/27 15:43"

[[entries]]
no = "2"
name = "Google翻訳先生"
title = "えいごのおべんきょう"
size = "11000 KB"
addr = [
    "(本体)",
    "https://www.dropbox.com/s/lsja24w9ozljgj4/Eigo.zip?dl=1",
    "(追加ばらし差分)",
    "https://www.dropbox.com/s/oombnpq7s9gjyfb/Eigo_add%20pack.zip?dl=1",
]
genre = "TOEIC"
impr = "9"
total = "45000"
median = "0"
avg = "5000"
regist = "2017/12/25 00:11"
update = "2018/01/22 12:11"

[[entries]]
no = "3"
name = "M-kani"
title = "ニュース"
size = "8909 KB"
addr = ["http://drive.google.com/file/d/1tOAZhqvvGdyaGuUYkg-B5UmcGX6pF0AS/view?usp=sharing"]
genre = "BMSA"
impr = "6"
total = "30000"
median = "0"
avg = "5000"
regist = "2017/12/31 08:36"
update = "2018/01/14 23:19"

[[entries]]
no = "4"
name = "かまたり"
title = "【地雷飲料】最強候補？カレーラムネを飲んでみた！"
size = "89518 KB"
addr = ["http://scytheleg.sakura.ne.jp/tempyou/bms/bms/tansan.rar"]
genre = "YouTubms"
impr = "9"
total = "45000"
median = "0"
avg = "5000"
regist = "2018/01/04 17:57"
update = "2018/01/14 23:42"

[[entries]]
no = "5"
name = "AI_rip"
title = "ふぁっきゅー"
size = "16000 KB"
addr = ["https://drive.google.com/file/d/1d9BtXKCRDOVJ067B_bc3fQj0LQOEYMHa/view?usp=drivesdk"]
genre = "ふぁふぁふぁふぁっく..."
impr = "4"
total = "20000"
median = "0"
avg = "5000"
regist = "2018/01/06 20:51"
update = "2018/07/09 22:54"

[[entries]]
no = "6"
name = "M,Gumi."
title = "ラストセンチュリーメランコリック-hyper trance m,gumix-の最後らへん。"
size = "100000 KB"
addr = ["https://drive.google.com/file/d/1rc_N2jFw1XXUGkIutCranRm_MslZMiM2/view?usp=drivesdk"]
genre = "Future trance"
impr = "1"
total = "5000"
median = "0"
avg = "5000"
regist = "2018/01/06 21:04"
update = "2018/08/11 19:42"

[[entries]]
no = "7"
name = "NASA島隆太"
title = "脳を鍛える大人のBMSトレーニング"
size = "18800 KB"
addr = ["https://www.dropbox.com/s/h62kloypj6q92ut/noutore.zip?dl=1"]
genre = "Brain Training for MATH"
impr = "11"
total = "55000"
median = "0"
avg = "5000"
regist = "2018/01/08 02:49"
update = "2018/01/15 00:16"

[[entries]]
no = "8"
name = "YAN*TS"
title = "おめーの席ねぇから！"
size = "482 KB"
addr = ["https://www.dropbox.com/s/u648b7gb19hf6ia/seki.zip?dl=1"]
genre = "BMショートアニメ(LIFE)"
impr = "5"
total = "25000"
median = "0"
avg = "5000"
regist = "2018/01/08 14:06"
update = "2018/01/14 23:24"
