[[entries]]
no = "1"
name = "------"
title = "Sympathy (Radio Edit)"
size = "99962 KB"
addr = ["https://mega.nz/#F!IP4iTAyI!jkwvNbkccH-EUATbGI4SWg"]
genre = "Uplifting trance"
impr = "18"
total = "56"
median = "3"
avg = "3.11"
regist = "2018/04/01 00:01"
update = "2018/06/03 13:13"

[[entries]]
no = "2"
name = "------"
title = "Celestial Axes"
size = "51379 KB"
addr = ["https://drive.google.com/uc?authuser=0&id=1_oUm9X1RfK3_BLDr6gQYYtAIomMhFhCn&export=download"]
genre = "GrimReaper"
impr = "26"
total = "118"
median = "5"
avg = "4.53"
regist = "2018/04/01 00:01"
update = "2018/05/07 05:32"

[[entries]]
no = "3"
name = "------"
title = "Majestic"
size = "2637 KB"
addr = ["https://www.dropbox.com/s/l6uiexjy5u7snpa/Majestic.rar?dl=0"]
genre = "GoaTrance"
impr = "0"
total = "0"
median = "2"
avg = "2.57"
regist = "2018/04/01 00:04"
update = "2018/05/06 21:03"

[[entries]]
no = "4"
name = "------"
title = "Free your Mind"
size = "11021 KB"
addr = ["https://www.dropbox.com/s/py8a2kh18884xif/free_your_mind_ogg.rar?dl=1"]
genre = "Epic"
impr = "20"
total = "82"
median = "4"
avg = "4.1"
regist = "2018/04/01 00:04"
update = "2018/05/07 14:07"

[[entries]]
no = "5"
name = "------"
title = "DIMENSION DIVER"
size = "35000 KB"
addr = ["http://fast-uploader.com/file/7081000570873/"]
genre = "Electro Trance"
impr = "19"
total = "83"
median = "4"
avg = "4.36"
regist = "2018/04/01 00:07"
update = "2018/05/06 23:19"

[[entries]]
no = "6"
name = "------"
title = "mist"
size = "59996 KB"
addr = [
    "https://www.dropbox.com/s/4l3l9om2s1f17z5/_mi.zip?dl=1",
    "譜面作成用BMSファイル入り(wav版, NHA譜面は変わってないです)",
    "https://www.dropbox.com/s/muikahicvz22py7/%5BFlatnique%5Dmist.zip?dl=1",
]
genre = "Techno / Fear (_)"
impr = "18"
total = "57"
median = "3"
avg = "3.16"
regist = "2018/04/01 00:08"
update = "2018/05/07 13:59"

[[entries]]
no = "7"
name = "------"
title = "coming & going"
size = "50641 KB"
addr = ["https://drive.google.com/open?id=1AVa-INfy6VxVjIXtw3Ae3vg80OBDCYrq"]
genre = "HARD DANCE"
impr = "17"
total = "73"
median = "4"
avg = "4.29"
regist = "2018/04/01 00:30"
update = "2020/04/04 11:47"

[[entries]]
no = "8"
name = "------"
title = "Back world"
size = "50000 KB"
addr = [
    "ogg版",
    "https://www.axfc.net/u/3899950",
    "wav版",
    "https://www.axfc.net/u/3899947",
    "4.2 Another譜面追加",
    "https://www.axfc.net/u/3900256",
    "pass",
    "bm2nd",
]
genre = "Hard GABBA"
impr = "13"
total = "25"
median = "2"
avg = "1.92"
regist = "2018/04/01 00:41"
update = "2018/10/13 00:43"

[[entries]]
no = "9"
name = "------"
title = "Cosmic in the Mist"
size = "23778 KB"
addr = [
    "https://www.dropbox.com/s/thc8yrwzqylquw5/cosmic",
    "(ogg).zip?dl=1",
]
genre = "JAZZ FUNK"
impr = "19"
total = "84"
median = "5"
avg = "4.42"
regist = "2018/04/01 01:29"
update = "2018/05/13 14:48"

[[entries]]
no = "10"
name = "------"
title = "Yup"
size = "8993 KB"
addr = ["http://www.mediafire.com/file/1ea7s7o18v2pqov/Yup_bms.zip"]
genre = "UPBEAT"
impr = "16"
total = "66"
median = "4"
avg = "4.12"
regist = "2018/04/01 07:19"
update = "2018/05/06 23:54"

[[entries]]
no = "11"
name = "------"
title = "in a well"
size = "279 KB"
addr = ["https://www.axfc.net/u/3900010.rar"]
genre = "DRUM SAMPLES"
impr = "11"
total = "20"
median = "2"
avg = "1.81"
regist = "2018/04/01 09:02"
update = "2018/05/07 00:42"

[[entries]]
no = "12"
name = "------"
title = "Brand New Party"
size = "4000 KB"
addr = ["https://drive.google.com/open?id=1lHSg5OVJEG8qd1OP5nSA8R5XYrKEDvIB"]
genre = "Hard Swing"
impr = "14"
total = "60"
median = "4.5"
avg = "4.28"
regist = "2018/04/01 15:51"
update = "2018/05/06 22:24"

[[entries]]
no = "13"
name = "------"
title = "lost reality"
size = "36807 KB"
addr = ["https://www.dropbox.com/s/ujrm79uqpzy4mjh/lost%20reality.zip?dl=0"]
genre = "HARDCORE"
impr = "16"
total = "74"
median = "5"
avg = "4.62"
regist = "2018/04/01 18:07"
update = "2018/05/06 23:18"

[[entries]]
no = "14"
name = "------"
title = "月の下で / 結月ゆかり"
size = "9153 KB"
addr = ["https://goo.gl/cf4e2W"]
genre = "演歌"
impr = "11"
total = "38"
median = "4"
avg = "3.45"
regist = "2018/04/02 00:08"
update = "2018/05/07 14:08"

[[entries]]
no = "15"
name = "------"
title = "Unlock"
size = "65726 KB"
addr = ["https://www.dropbox.com/s/qkuev2mgxjgspsd/unlock.zip?dl=1"]
genre = "Toybox"
impr = "26"
total = "124"
median = "5"
avg = "4.76"
regist = "2018/04/02 00:32"
update = "2018/05/07 00:07"

[[entries]]
no = "16"
name = "------"
title = "shutterstock"
size = "44000 KB"
addr = ["https://www.dropbox.com/s/39xw2j1k6we5q5k/shutterstock-ogg.zip?dl=0"]
genre = "TRANCE"
impr = "12"
total = "26"
median = "2"
avg = "2.16"
regist = "2018/04/02 01:44"
update = "2018/05/07 10:33"

[[entries]]
no = "17"
name = "------"
title = "Merry Third of October, Mr.糞譜面DERAYMASTER"
size = "19967 KB"
addr = ["https://mega.nz/#!a4RzHKRQ!JxXQ7tvXDNAjf__E6p4Rh6Nm3TKtJZuesukucY-6eW8"]
genre = "CATACLASM"
impr = "11"
total = "34"
median = "3"
avg = "3.09"
regist = "2018/04/02 01:49"
update = "2018/05/06 22:51"

[[entries]]
no = "18"
name = "------"
title = "Just look at my eyes (bms edit)"
size = "19000 KB"
addr = ["https://drive.google.com/open?id=1T_Y5F3-QNnLeLzqVlNFrK5yBJaIoyx72"]
genre = "TV Drama Pop"
impr = "13"
total = "51"
median = "4"
avg = "3.92"
regist = "2018/04/02 02:27"
update = "2018/05/07 00:10"

[[entries]]
no = "19"
name = "------"
title = "LOSHAXI"
size = "28957 KB"
addr = ["https://www.axfc.net/u/3900270/7OSHAXI"]
genre = "性欲望的無調音楽"
impr = "22"
total = "104"
median = "5"
avg = "4.72"
regist = "2018/04/02 05:09"
update = "2018/05/09 00:33"

[[entries]]
no = "20"
name = "------"
title = "Uncle"
size = "1310 KB"
addr = ["https://drive.google.com/file/d/1s8QGu1iRuTFtWEjbVI9yy54-svvSgo4R/view?usp=sharing"]
genre = "Piano"
impr = "13"
total = "22"
median = "2"
avg = "1.69"
regist = "2018/04/02 05:50"
update = "2018/05/22 03:32"

[[entries]]
no = "21"
name = "------"
title = "Valkyrie Revolutia"
size = "20068 KB"
addr = ["https://www.dropbox.com/s/089dnr0szei2z7d/ValkyrieRevolutia_sakamiya.zip?dl=1"]
genre = "Holy knight core"
impr = "17"
total = "67"
median = "4"
avg = "3.94"
regist = "2018/04/02 22:56"
update = "2018/05/07 00:01"

[[entries]]
no = "22"
name = "------"
title = "Meteor Shower"
size = "100000 KB"
addr = ["https://www.axfc.net/u/3900575"]
genre = "TRANCE"
impr = "13"
total = "26"
median = "2"
avg = "2"
regist = "2018/04/03 15:48"
update = "2018/05/20 13:58"

[[entries]]
no = "23"
name = "------"
title = "AЯEИA"
size = "2276 KB"
addr = ["http://fuki1755.starfree.jp/bms/ARENA.zip"]
genre = "DIGITAL HARDCORE"
impr = "12"
total = "47"
median = "4"
avg = "3.91"
regist = "2018/04/04 18:28"
update = "2020/02/13 16:51"

[[entries]]
no = "24"
name = "------"
title = "After Planet feat.桃音モモ"
size = "89554 KB"
addr = ["https://dl.dropboxusercontent.com/s/b0bfnrmlhyg1fh5/aftp.zip"]
genre = "UTAUPOP"
impr = "13"
total = "45"
median = "4"
avg = "3.46"
regist = "2018/04/04 19:18"
update = "2018/05/06 23:22"

[[entries]]
no = "25"
name = "------"
title = "Tendaness Air feat.IA"
size = "14723 KB"
addr = ["公開終了"]
genre = "Angelic Trance"
impr = "12"
total = "47"
median = "4"
avg = "3.91"
regist = "2018/04/05 09:19"
update = "2018/05/16 01:01"

[[entries]]
no = "26"
name = "------"
title = "Dinosaur Step"
size = "28779 KB"
addr = ["https://www.dropbox.com/s/akoy99f6vq531cm/Dinosaur%20Step.zip?dl=1"]
genre = "Industrial Techno"
impr = "11"
total = "34"
median = "3"
avg = "3.09"
regist = "2018/04/06 16:08"
update = "2018/05/06 23:36"

[[entries]]
no = "27"
name = "------"
title = "You are a super DJ"
size = "64500 KB"
addr = ["https://www.axfc.net/u/3903136"]
genre = "------"
impr = "14"
total = "46"
median = "3.5"
avg = "3.28"
regist = "2018/04/07 14:57"
update = "2018/05/06 23:52"

[[entries]]
no = "28"
name = "------"
title = "Crystalized"
size = "2800 KB"
addr = ["https://drive.google.com/uc?id=1kf4dEq8iLE8IPR6EMqA4cm0qKmCfnQ1A"]
genre = "TRANCE"
impr = "14"
total = "49"
median = "3.5"
avg = "3.5"
regist = "2018/04/07 20:44"
update = "2018/05/06 23:46"

[[entries]]
no = "29"
name = "------"
title = "Clouds above the sunset, and a gentle summer breeze."
size = "48600 KB"
addr = ["https://drive.google.com/uc?id=14yaHM-U2Km5BUY_WSsSjrSNCbWSjdb9h&export=download"]
genre = "Liquid Artbreaks"
impr = "13"
total = "56"
median = "4"
avg = "4.3"
regist = "2018/04/07 23:49"
update = "2018/05/07 06:10"

[[entries]]
no = "30"
name = "------"
title = "惨禍"
size = "5300 KB"
addr = ["https://www.dropbox.com/s/id5re0n7jj9jloo/sanka_ogg.zip?dl=1"]
genre = "Crossbreed/Breakcore"
impr = "11"
total = "44"
median = "4"
avg = "4"
regist = "2018/04/08 01:26"
update = "2018/05/06 23:23"

[[entries]]
no = "31"
name = "------"
title = "Ibuki"
size = "15619 KB"
addr = ["https://www.dropbox.com/s/mc41i6hs8calq4c/%5BOriental%20Neuro%5D%20Ibuki.zip?dl=1"]
genre = "Oriental Neuro"
impr = "13"
total = "52"
median = "4"
avg = "4"
regist = "2018/04/08 15:36"
update = "2018/05/06 23:40"

[[entries]]
no = "32"
name = "------"
title = "BEAT MASTER SLAYER"
size = "9333 KB"
addr = ["https://www.dropbox.com/s/nbe5x8s5xg0ck1z/BEAT%20MASTER%20SLAYER_ogg.zip?dl=1"]
genre = "BUCHIAGE MAX SPEEDCORE"
impr = "15"
total = "68"
median = "5"
avg = "4.53"
regist = "2018/04/08 15:50"
update = "2018/05/07 02:11"

[[entries]]
no = "33"
name = "------"
title = "Galvanizer"
size = "5929 KB"
addr = [
    "https://www.dropbox.com/s/5b5zpeq8gcxpzzv/Galvanizer.zip?dl=1",
    "Another譜面のみ:",
    "https://www.dropbox.com/s/9zfe1jizhcefta6/_Galvanizer_Another.bme?dl=1",
]
genre = "Tech electro"
impr = "13"
total = "56"
median = "4"
avg = "4.3"
regist = "2018/04/08 22:07"
update = "2018/05/07 01:50"

[[entries]]
no = "34"
name = "------"
title = "Bicorn"
size = "17600 KB"
addr = ["https://www.dropbox.com/s/9hwtojdp1hfkqsp/%5B------%5DBicorn.rar?dl=1"]
genre = "Soundtrack"
impr = "13"
total = "50"
median = "4"
avg = "3.84"
regist = "2018/04/08 22:16"
update = "2018/05/06 21:31"

[[entries]]
no = "35"
name = "------"
title = "StnaparusA"
size = "4600 KB"
addr = ["http://fast-uploader.com/file/7078748837843/"]
genre = "Speedcore"
impr = "8"
total = "22"
median = "3"
avg = "2.75"
regist = "2018/04/08 22:22"
update = "2018/05/06 22:07"

[[entries]]
no = "36"
name = "------"
title = "R613"
size = "36700 KB"
addr = [
    "wav版",
    "https://www.axfc.net/u/3901904",
    "ーーーーーーーーーーーーーーーーーーーーーーーーーーー",
    "ogg版",
    "https://www.axfc.net/u/3901903",
]
genre = "RAVE"
impr = "12"
total = "35"
median = "3"
avg = "2.91"
regist = "2018/04/08 22:26"
update = "2018/05/24 15:56"

[[entries]]
no = "37"
name = "------"
title = "アイ・ライク・バンカー"
size = "9554 KB"
addr = ["https://www.axfc.net/u/3901910.zip"]
genre = "GOLF / ELECTRO SWING"
impr = "20"
total = "92"
median = "5"
avg = "4.6"
regist = "2018/04/08 22:41"
update = "2018/05/06 23:58"

[[entries]]
no = "38"
name = "------"
title = "神仙・竜巻返し ～ Black Whirlwind"
size = "25000 KB"
addr = ["https://www.dropbox.com/s/hvwxxavbxyng1xe/Black_Whirlwind_ogg.zip?dl=1"]
genre = "Calm Logic Trance"
impr = "18"
total = "84"
median = "5"
avg = "4.66"
regist = "2018/04/08 23:40"
update = "2018/05/07 00:58"

[[entries]]
no = "39"
name = "------"
title = "trompe-l'oeil"
size = "500000 KB"
addr = ["https://www.axfc.net/u/3901952"]
genre = "IDB"
impr = "8"
total = "16"
median = "2"
avg = "2"
regist = "2018/04/08 23:59"
update = "2018/05/06 22:27"
