[[entries]]
no = "1"
name = "えふ"
title = "Congratulations!"
size = "3982 KB"
addr = [
    "http://www.ismusic.ne.jp/fms/Congratulations_MQ.rar",
    "http://www.ismusic.ne.jp/fms/Congratulations_MQ.zip",
]
genre = "HAPPY HARDCORE"
impr = "46"
total = "157"
avg = "3.41"
regist = "2004/04/10 00:05"
update = "2004/04/25 23:12"

[[entries]]
no = "2"
name = "シロマル"
title = "Dim Dawn"
size = "4000 KB"
addr = ["http://www.ismusic.ne.jp/siromaru/si_dim.rar"]
genre = "Drum'n Bass"
impr = "38"
total = "123"
avg = "3.23"
regist = "2004/04/10 00:07"
update = "2004/04/25 23:13"

[[entries]]
no = "3"
name = "BACO"
title = "Golden Ray"
size = "7985 KB"
addr = ["http://f37.aaacafe.ne.jp/~boxism/over_3mb/golden_ray/golden_ray.htm"]
genre = "Drum'n bass"
impr = "27"
total = "98"
avg = "3.62"
regist = "2004/04/10 00:08"
update = "2004/04/25 23:22"

[[entries]]
no = "4"
name = "Deeper Darkness Dragon"
title = "6-Z-6"
size = "264 KB"
addr = ["http://www.geocities.jp/deeperdarknessdragon/"]
genre = "TECHNO"
impr = "24"
total = "48"
avg = "2"
regist = "2004/04/10 00:17"
update = "2004/04/26 00:06"

[[entries]]
no = "5"
name = "RELISH with Mana"
title = "stray star"
size = "6411 KB"
addr = [
    "【ノーマル版(6.25M)】",
    "http://relish.main.jp/bms/stray_star.zip",
    "【ハイクオリティ版(31.0M)】",
    "http://relish.main.jp/bms/stray_star_HQ.zip",
]
genre = "swing jazz"
impr = "68"
total = "280"
avg = "4.11"
regist = "2004/04/10 00:21"
update = "2004/04/25 23:31"

[[entries]]
no = "6"
name = "McQueen"
title = "the falcon"
size = "3990 KB"
addr = ["http://www.interq.or.jp/saturn/psypha/bigkatsu/falcon.rar"]
genre = "epic trance"
impr = "33"
total = "94"
avg = "2.84"
regist = "2004/04/10 00:46"
update = "2004/04/26 01:11"

[[entries]]
no = "7"
name = "t-plain"
title = "Leaves Fall..."
size = "3209 KB"
addr = ["http://sound.jp/ptf/bms/DL.html"]
genre = "instrumental"
impr = "24"
total = "70"
avg = "2.91"
regist = "2004/04/10 01:11"
update = "2004/04/25 23:14"

[[entries]]
no = "8"
name = "PE"
title = "Pebashiri World"
size = "3060 KB"
addr = ["http://www.geocities.co.jp/Playtown/9992/pebashiri.zip"]
genre = "Gabber"
impr = "37"
total = "139"
avg = "3.75"
regist = "2004/04/10 01:13"
update = "2004/04/25 23:49"

[[entries]]
no = "9"
name = "BANGLAR"
title = "Pollen"
size = "1946 KB"
addr = [
    "BMS",
    "http://www.ismusic.ne.jp/banglar/banglar_pollen.zip",
    "BGA(6751 KB)",
    "http://www.ismusic.ne.jp/synk/pollen_bga.zip",
]
genre = "techno"
impr = "38"
total = "167"
avg = "4.39"
regist = "2004/04/10 01:34"
update = "2004/04/25 23:15"

[[entries]]
no = "10"
name = "GEMA"
title = "Beautification"
size = "2200 KB"
addr = [
    "http://uziel.hp.infoseek.co.jp/music/beautification.lzh",
    "(2.7M)",
    "http://uziel.hp.infoseek.co.jp/music/beautification.rar",
    "(2.2M)",
]
genre = "Goa Trance"
impr = "26"
total = "80"
avg = "3.07"
regist = "2004/04/10 02:12"
update = "2004/04/25 23:15"

[[entries]]
no = "11"
name = "ねこみりん"
title = "Wind Chaser -cold sorrow style-"
size = "7430 KB"
addr = [
    "HomePage [",
    "http://www3.to/nemu/",
    "]",
    "(Top Page→BMS・MP3→｢Wind Chaser -cold sorrow style-｣)",
]
genre = "Trance (instrumental)"
impr = "23"
total = "73"
avg = "3.17"
regist = "2004/04/10 03:36"
update = "2004/04/28 03:30"

[[entries]]
no = "12"
name = "こんすとらくたぁ～"
title = "world 4 U and こんすとらくたぁ～"
size = "8730 KB"
addr = ["http://constructor.hp.infoseek.co.jp/frame.html"]
genre = "happyhardcore"
impr = "31"
total = "100"
avg = "3.22"
regist = "2004/04/10 04:13"
update = "2004/04/25 23:16"

[[entries]]
no = "13"
name = "Project Trance Header.（Ta2 feat.Koji M）"
title = "November☆Moon -Techno party mix-"
size = "6116 KB"
addr = ["http://www11.plala.or.jp/ta2_1103/BMS/bms-01_NovemberMoon.html"]
genre = "TECHNO PARTY"
impr = "34"
total = "93"
avg = "2.73"
regist = "2004/04/10 04:17"
update = "2004/04/26 06:42"

[[entries]]
no = "14"
name = "ポポス"
title = "lounge memory"
size = "3628 KB"
addr = ["http://popos.web-zz.com/lounge_memory.zip"]
genre = "house"
impr = "25"
total = "78"
avg = "3.12"
regist = "2004/04/10 06:12"
update = "2004/04/25 23:17"

[[entries]]
no = "15"
name = "djTAK"
title = "Force of A Shade"
size = "5859 KB"
addr = ["http://djtak.hp.infoseek.co.jp/spring_phase/force_of_a_shade.shtml"]
genre = "Trance"
impr = "22"
total = "68"
avg = "3.09"
regist = "2004/04/10 10:37"
update = "2004/04/25 23:26"

[[entries]]
no = "16"
name = "HIBITO"
title = "Quick Fixation"
size = "646 KB"
addr = ["http://lilac.hokkai.net/~hibito/bms/quick_fixation.zip"]
genre = "SPEED TECHNO"
impr = "25"
total = "62"
avg = "2.48"
regist = "2004/04/10 13:01"
update = "2004/04/25 23:59"

[[entries]]
no = "17"
name = "glustar"
title = "Cafe Claris"
size = "941 KB"
addr = ["http://ractina.hp.infoseek.co.jp/bmscc.htm"]
genre = "Bossanova"
impr = "25"
total = "81"
avg = "3.24"
regist = "2004/04/10 15:14"
update = "2004/04/26 00:14"

[[entries]]
no = "18"
name = "Elun"
title = "Last Graduation"
size = "2748 KB"
addr = ["http://kikirpg.s31.xrea.com/lasgra.zip"]
genre = "BALLADE POP"
impr = "19"
total = "51"
avg = "2.68"
regist = "2004/04/10 16:42"
update = "2004/04/25 23:18"

[[entries]]
no = "19"
name = "20 cigarettes (a-k-a Yuji.M)"
title = "DummyJack"
size = "432 KB"
addr = [
    "http://trsh.cside.ne.jp/data/bms/20dj.rar",
    "(RAR3.10 / 432KB)",
    "http://trsh.cside.ne.jp/data/bms/20dj.zip",
    "(ZIP / 544KB)",
]
genre = "drum'n bass"
impr = "34"
total = "148"
avg = "4.35"
regist = "2004/04/10 17:22"
update = "2004/04/25 23:18"

[[entries]]
no = "20"
name = "Qantas(Q9Q9)"
title = "The mad geezers dancing on floor"
size = "1368 KB"
addr = [
    "http://www.ismusic.ne.jp/qantas/files/qqqq_themad.zip",
    "HQ版：",
    "http://www.ismusic.ne.jp/qantas/files/qqqq_themad_hq.zip",
]
genre = "hard dance"
impr = "24"
total = "76"
avg = "3.16"
regist = "2004/04/10 17:55"
update = "2004/04/25 23:26"

[[entries]]
no = "21"
name = "ridis"
title = "end of white season"
size = "2731 KB"
addr = [
    "http://nothing.sh/~liz/ridis/eows.rar",
    "（2731KB）",
    "http://nothing.sh/~liz/ridis/eows.lzh",
    "（4189KB）",
    "http://nothing.sh/~liz/ridis/eows_hq.rar",
    "（HQ版/17988KB）",
]
genre = "instrumental"
impr = "39"
total = "145"
avg = "3.71"
regist = "2004/04/10 18:14"
update = "2004/04/25 23:19"

[[entries]]
no = "22"
name = "Syatten"
title = "beyond the limit"
size = "6132 KB"
addr = ["http://www.ismusic.ne.jp/s-curve/sp.html"]
genre = "Trance"
impr = "75"
total = "326"
avg = "4.34"
regist = "2004/04/10 18:20"
update = "2004/04/25 23:34"

[[entries]]
no = "23"
name = "未来"
title = "Turnin' Point"
size = "4904 KB"
addr = ["http://www11.plala.or.jp/rf_mirai/bms/m12_turning_point.zip"]
genre = "J-Rock -bm edit-"
impr = "37"
total = "125"
avg = "3.37"
regist = "2004/04/10 19:04"
update = "2004/07/16 14:46"

[[entries]]
no = "24"
name = "spinai"
title = "Fortune Message"
size = "5970 KB"
addr = ["http://nupinupi.hp.infoseek.co.jp/bms/"]
genre = "House Pop"
impr = "31"
total = "133"
avg = "4.29"
regist = "2004/04/10 19:29"
update = "2004/04/25 23:19"

[[entries]]
no = "25"
name = "vol"
title = "Memory of Green zone:two"
size = "3785 KB"
addr = ["http://www.ismusic.ne.jp/vol/spdl.html"]
genre = "drum'n bass"
impr = "22"
total = "47"
avg = "2.13"
regist = "2004/04/10 20:38"
update = "2004/04/25 23:28"

[[entries]]
no = "26"
name = "RYU!"
title = "Matari wave"
size = "1720 KB"
addr = ["http://nanmin.s4.xrea.com/matari_bms.zip"]
genre = "Break beats"
impr = "31"
total = "130"
avg = "4.19"
regist = "2004/04/10 20:51"
update = "2004/04/25 23:40"

[[entries]]
no = "27"
name = "naotyu-"
title = "#74"
size = "9265 KB"
addr = ["http://www.naotyu-studio7.com/music/index.html"]
genre = "2step"
impr = "46"
total = "180"
avg = "3.91"
regist = "2004/04/10 20:58"
update = "2004/05/29 12:55"

[[entries]]
no = "28"
name = "Yas-Ji"
title = "PROTMIND"
size = "16200 KB"
addr = ["http://www.eonet.ne.jp/~yas-ji/protmind.zip"]
genre = "Romantic Beat"
impr = "45"
total = "215"
avg = "4.77"
regist = "2004/04/10 21:20"
update = "2004/04/25 23:20"

[[entries]]
no = "29"
name = "micron"
title = "carnage"
size = "1616 KB"
addr = ["http://www.ismusic.ne.jp/micron/carnage.zip"]
genre = "hard minimal"
impr = "39"
total = "171"
avg = "4.38"
regist = "2004/04/10 22:00"
update = "2004/04/25 23:21"

[[entries]]
no = "30"
name = "Scarlet Eyes"
title = "snowman"
size = "996 KB"
addr = ["http://industrial-garage.hp.infoseek.co.jp/bm/snowman.zip"]
genre = "NEWSTYLE GABBER"
impr = "26"
total = "85"
avg = "3.26"
regist = "2004/04/10 22:11"
update = "2004/04/25 23:21"

[[entries]]
no = "31"
name = "DreamDay"
title = "First day of spring"
size = "5680 KB"
addr = ["http://yhm.s57.xrea.com/Fdos.zip"]
genre = "Guitar pop"
impr = "18"
total = "22"
avg = "1.22"
regist = "2004/04/11 11:07"
update = "2004/04/25 23:21"

[[entries]]
no = "32"
name = "wata"
title = "White Spring"
size = "3445 KB"
addr = [
    "http://wataq.hp.infoseek.co.jp/whitespring.rar",
    "(3445kb)",
    "http://wataq.hp.infoseek.co.jp/whitespring_z.zip",
    "(6854kb)",
    "-HQ版-",
    "http://wataq.hp.infoseek.co.jp/whitespring_HQ.rar",
    "(16840kb)",
]
genre = "Ambience Inst"
impr = "46"
total = "195"
avg = "4.23"
regist = "2004/04/11 12:59"
update = "2004/04/26 23:31"

[[entries]]
no = "33"
name = "彷徨旅人"
title = "夕暮れと波と潮騒"
size = "1119 KB"
addr = ["http://www1.kcn.ne.jp/~solomon/contents/music/wv_yugure_bms.zip"]
genre = "Nature"
impr = "34"
total = "136"
avg = "4"
regist = "2004/04/11 14:56"
update = "2004/04/26 00:33"

[[entries]]
no = "34"
name = "Est"
title = "Kirsche"
size = "5364 KB"
addr = [
    "http://stwww.ec.kagawa-u.ac.jp/~s01e078/bms/kirsche.zip",
    "(通常版,5364KB)",
    "http://stwww.ec.kagawa-u.ac.jp/~s01e078/bms/kirsche_hq.zip",
    "(HQ版,20448KB)",
]
genre = "TRANCE"
impr = "23"
total = "81"
avg = "3.52"
regist = "2004/04/11 16:03"
update = "2004/04/26 00:36"

[[entries]]
no = "35"
name = "ring"
title = "concentration"
size = "4600 KB"
addr = [
    "http://www.ismusic.ne.jp/_ref/concentration.zip",
    "http://www.ismusic.ne.jp/_ref/concentration.rar",
    "http://www.ismusic.ne.jp/_ref/sp.htm",
]
genre = "trance techno"
impr = "27"
total = "85"
avg = "3.14"
regist = "2004/04/11 17:04"
update = "2004/04/25 23:22"

[[entries]]
no = "36"
name = "Y.W"
title = "Dreamers startline"
size = "7508 KB"
addr = ["http://www.pmeyw.com/m/spring_phase.htm"]
genre = "Happy hardcore"
impr = "43"
total = "161"
avg = "3.74"
regist = "2004/04/11 17:25"
update = "2004/04/26 00:05"

[[entries]]
no = "37"
name = "djHIRO"
title = "The soft world"
size = "1150 KB"
addr = ["http://popup12.tok2.com/home2/conpiro/the_soft_world.htm"]
genre = "EPIC TRANCE"
impr = "25"
total = "67"
avg = "2.68"
regist = "2004/04/11 18:18"
update = "2004/04/26 00:44"

[[entries]]
no = "38"
name = "にゃーん"
title = "13th floweret"
size = "10000 KB"
addr = [
    "ＤＬ用Page→",
    "http://www13.plala.or.jp/nya_n/",
    "ＨＱ10M→",
    "http://www13.plala.or.jp/nya_n/floweretHQ.rar",
    "ＬＱ1M→",
    "http://www13.plala.or.jp/nya_n/floweretLQ.rar",
    "ＨＱ(zip)14M→",
    "http://www13.plala.or.jp/nya_n/floweretHQ.zip",
]
genre = "trance"
impr = "23"
total = "75"
avg = "3.26"
regist = "2004/04/11 18:21"
update = "2004/04/25 23:23"

[[entries]]
no = "39"
name = "葵井巫女子"
title = "Forgotten Primavera"
size = "3900 KB"
addr = [
    "http://page.freett.com/mikoko/down.htm",
    "rar-3900KB zip-6000KB HQ-19MB",
]
genre = "ethnic"
impr = "27"
total = "84"
avg = "3.11"
regist = "2004/04/11 18:25"
update = "2004/04/25 23:23"

[[entries]]
no = "40"
name = "tarolabo"
title = "Irregular"
size = "13632 KB"
addr = [
    "http://page.freett.com/tarolabo/irr_HQ.zip",
    "ハイクオリティ 13632KB",
    "http://page.freett.com/tarolabo/irr_LQ.zip",
    "ロークオリティ 7072KB",
    "http://page.freett.com/tarolabo/irr_SLQ.zip",
    "Ｓロークオリティ 2448KB",
    "http://page.freett.com/tarolabo/irr_omk.zip",
    "オマケ 16KB",
]
genre = "Heavy teckno"
impr = "19"
total = "37"
avg = "1.94"
regist = "2004/04/11 20:46"
update = "2004/04/25 23:23"

[[entries]]
no = "41"
name = "LUV2"
title = "CORONA -BM Edition-"
size = "3671 KB"
addr = ["http://ctbr.jp/content/sound/bms/sp.html"]
genre = "TRANCE & CYBER TRANCE"
impr = "23"
total = "74"
avg = "3.21"
regist = "2004/04/11 21:48"
update = "2004/04/25 23:24"

[[entries]]
no = "42"
name = "Zechariah"
title = "錆びついた懐中時計"
size = "13578 KB"
addr = ["----"]
genre = "remembrance"
impr = "37"
total = "159"
avg = "4.29"
regist = "2004/04/11 22:38"
update = "2004/04/26 00:46"

[[entries]]
no = "43"
name = "EarBreaker"
title = "Hit Back"
size = "11922 KB"
addr = ["http://www.ismusic.ne.jp/eb/music/eb_hit_back.zip"]
genre = "RAVE"
impr = "39"
total = "143"
avg = "3.66"
regist = "2004/04/11 22:55"
update = "2004/04/25 23:25"

[[entries]]
no = "44"
name = "Opt"
title = "Rapid Stream"
size = "736 KB"
addr = ["http://www.ismusic.ne.jp/alabaster/event/event.html"]
genre = "TRANCE CORE"
impr = "20"
total = "42"
avg = "2.1"
regist = "2004/04/11 23:09"
update = "2004/04/27 13:09"

[[entries]]
no = "45"
name = "SOLVALOU"
title = "ゼビウス好き2 ～バキュラ256～"
size = "57 KB"
addr = ["http://a-p.cside.ne.jp/files/xevious2.rar"]
genre = "breakbeats"
impr = "26"
total = "98"
avg = "3.76"
regist = "2004/04/12 00:01"
update = "2004/04/25 23:25"

[[entries]]
no = "46"
name = "nu"
title = "High"
size = "4540 KB"
addr = ["http://www.geocities.co.jp/MusicStar-Bass/6766/high.html"]
genre = "Acid House"
impr = "27"
total = "107"
avg = "3.96"
regist = "2004/04/12 00:08"
update = "2004/04/25 23:51"

[[entries]]
no = "47"
name = "IRAG"
title = "colour"
size = "8811 KB"
addr = ["http://hoyo0108.hp.infoseek.co.jp/dl.htm"]
genre = "Instrumental"
impr = "22"
total = "88"
avg = "4"
regist = "2004/04/12 00:30"
update = "2004/04/26 00:16"

[[entries]]
no = "48"
name = "Project Trance Header.（Seithi Yumeno）"
title = "ぽっぷる！"
size = "2866 KB"
addr = ["http://www11.plala.or.jp/ta2_1103/BMS/bms-02_poppuru.html"]
genre = "HAPPY HARDCORE"
impr = "34"
total = "108"
avg = "3.17"
regist = "2004/04/12 00:57"
update = "2004/04/26 07:02"

[[entries]]
no = "49"
name = "kataG"
title = "700000000 Reflections(bazooka mix)"
size = "6370 KB"
addr = ["http://niigata.cool.ne.jp/kmbms/700000000rmxLQ.zip"]
genre = "GABBA"
impr = "42"
total = "188"
avg = "4.47"
regist = "2004/04/12 01:36"
update = "2004/07/18 10:32"

[[entries]]
no = "50"
name = "LV.4"
title = "Solanoiro"
size = "9130 KB"
addr = ["http://www30.tok2.com/home/lv4/solanoiro.zip"]
genre = "Celtrance"
impr = "26"
total = "86"
avg = "3.3"
regist = "2004/04/12 03:32"
update = "2004/04/25 23:39"

[[entries]]
no = "51"
name = "鷹龍"
title = "panic"
size = "1900 KB"
addr = ["http://www.ismusic.ne.jp/ryuryu/rrkt/panic_bms_.zip"]
genre = "pop"
impr = "16"
total = "42"
avg = "2.62"
regist = "2004/04/12 04:46"
update = "2004/04/25 23:27"

[[entries]]
no = "52"
name = "tpa:pbr"
title = "Tran-C Heaven!"
size = "3800 KB"
addr = ["http://sound.jp/tpapbr/tranC_heaven.html"]
genre = "Happy Gabba"
impr = "25"
total = "91"
avg = "3.64"
regist = "2004/04/12 12:49"
update = "2004/04/26 00:24"

[[entries]]
no = "53"
name = "ねこみみ魔法使い"
title = "あの頃のように -white snow street-"
size = "2441 KB"
addr = ["http://nekomimi.name/"]
genre = "house"
impr = "37"
total = "154"
avg = "4.16"
regist = "2004/04/12 16:59"
update = "2005/01/14 19:12"

[[entries]]
no = "54"
name = "ねこみみ魔法使い"
title = "going on -spring wind-"
size = "6152 KB"
addr = ["http://nekomimi.name/"]
genre = "high jazzy pop"
impr = "66"
total = "256"
avg = "3.87"
regist = "2004/04/12 16:59"
update = "2005/01/14 19:13"

[[entries]]
no = "55"
name = "#ねここ14歳"
title = "☆ さくらなみきのかぜ ☆"
size = "8115 KB"
addr = [
    "http://www.bmsjournal.net/yamajet/nekoko14.rar",
    "http://www.yamajet.com/nekokoherher/nekoko14.zip",
]
genre = "kirby pop"
impr = "71"
total = "320"
avg = "4.5"
regist = "2004/04/12 16:59"
update = "2004/04/25 23:59"

[[entries]]
no = "56"
name = "djHIRO"
title = "Яⅱ"
size = "1010 KB"
addr = ["http://popup12.tok2.com/home2/conpiro/r2_rmx.htm"]
genre = "TECHNO"
impr = "20"
total = "43"
avg = "2.15"
regist = "2004/04/12 17:15"
update = "2004/04/26 00:45"

[[entries]]
no = "57"
name = "Bit Upper"
title = "Sakura Electro"
size = "2863 KB"
addr = ["http://amonkido.at.infoseek.co.jp/smowphase.htm"]
genre = "ELECTRO"
impr = "21"
total = "72"
avg = "3.42"
regist = "2004/04/12 19:50"
update = "2004/04/25 23:28"

[[entries]]
no = "58"
name = "A.I.TOYS"
title = "カゼトウタウヒト"
size = "3696 KB"
addr = ["http://www.globetown.net/~a_i_toys/bms/kaze.html"]
genre = "JP-SPIRITUAL CORE"
impr = "25"
total = "73"
avg = "2.92"
regist = "2004/04/12 21:55"
update = "2004/06/03 23:24"

[[entries]]
no = "59"
name = "TakaYu"
title = "Happiness Blue"
size = "9000 KB"
addr = ["http://page.freett.com/sound_on_sound/ivent.html"]
genre = "Trance Core"
impr = "19"
total = "38"
avg = "2"
regist = "2004/04/12 23:40"
update = "2004/04/25 23:40"

[[entries]]
no = "60"
name = "猫の人"
title = "Pocket"
size = "2913 KB"
addr = ["http://page.freett.com/nekonohito/pocket.htm"]
genre = "HAPPY HARDCORE"
impr = "20"
total = "58"
avg = "2.9"
regist = "2004/04/12 23:46"
update = "2004/04/26 09:22"

[[entries]]
no = "61"
name = "Liveric"
title = "Future×Future"
size = "1620 KB"
addr = [
    "http://popup12.tok2.com/home2/conpiro/f_f_LQ.lzh",
    "(1.62MB)",
    "http://popup12.tok2.com/home2/conpiro/f_f_HQ.lzh",
    "(5.85MB)",
]
genre = "NU-NRG"
impr = "19"
total = "44"
avg = "2.31"
regist = "2004/04/12 23:47"
update = "2004/04/26 00:18"

[[entries]]
no = "62"
name = "Chikuwa"
title = ".dot-exprience"
size = "10000 KB"
addr = [
    "http://chikuwa3.hp.infoseek.co.jp/chik_dot_exp.rar",
    "http://chikuwa3.hp.infoseek.co.jp/chik_dot_exp_bga.rar",
]
genre = "electronica"
impr = "25"
total = "101"
avg = "4.04"
regist = "2004/04/12 23:53"
update = "2004/04/25 23:34"

[[entries]]
no = "63"
name = "Caspi Cruz"
title = "サクラ スケアクロウ"
size = "6353 KB"
addr = [
    "http://babu.com/~cruz/bms/scare.html",
    "（zip LQ版 6.3MB）",
    "（zip HQ版 31.0MB）",
    "（rar HQ版 22.1MB）",
]
genre = "J-POP"
impr = "33"
total = "129"
avg = "3.9"
regist = "2004/04/12 23:59"
update = "2004/05/26 18:41"

[[entries]]
no = "64"
name = "maxXx65535"
title = "Cynthia"
size = "7301 KB"
addr = [
    "http://www.ismusic.ne.jp/maxxx65535/65535_cynthia.zip",
    "(↑通常はこちらをダウンロードしてください。)",
    "http://www.ismusic.ne.jp/maxxx65535/65535_cynthia_vorbis.zip",
    "(↑DDRが正式にOgg Vorbis対応しましたので試験的に配布してみます。)",
]
genre = "Artcore"
impr = "43"
total = "165"
avg = "3.83"
regist = "2004/04/13 01:19"
update = "2004/04/25 23:26"
