[[entries]]
no = "1"
name = "fk"
team = "CONTEMPORARY"
title = "tit"
size = "1 KB"
addr = ["http://fuki1755.starfree.jp/bms/tit.cab"]
genre = "OLDSKOOL 470BYTES"
impr = "4"
total = "37"
median = "9.5"
avg = "9.25"
regist = "2018/09/20 09:11"
update = "2021/04/20 22:58"

[[entries]]
no = "2"
name = "KidZ G"
team = "CONTEMPORARY"
title = "Afro meets Fidget Pt.2"
size = "14327 KB"
addr = ["https://drive.google.com/file/d/1sjeUthcrQQpnIZtDZoTGM9ChkZyz-zZQ"]
genre = "FUTURE FIDGET"
impr = "3"
total = "24"
median = "8"
avg = "8"
regist = "2018/09/26 20:37"
update = "2019/03/31 23:16"

[[entries]]
no = "3"
name = "scamp"
team = "CONTEMPORARY"
title = "ODYSSEY"
size = "1000 KB"
addr = ["https://www.dropbox.com/s/uciyedtgbmtmptd/ODYSSEY.rar?dl=0"]
genre = "fanfare"
impr = "2"
total = "13"
median = "6.5"
avg = "6.5"
regist = "2018/10/02 07:15"
update = "2019/03/31 23:19"

[[entries]]
no = "4"
name = "Lollipop"
team = "CONTEMPORARY"
title = "Minuet for Harpsichord and Oboe"
size = "13896 KB"
addr = [
    "https://drive.google.com/file/d/1btL-pSyIPZ0PQiqMOttjLXXrXv1Tz_I3/view?usp=sharing",
    "(.ogg/.png, 7K and 5K, for modern BMS player)",
    "https://drive.google.com/file/d/1eXWex3ML5mGUdQrKfcRwPKZbmo9U73dp/view?usp=sharing",
    "(.wav/.bmp, 5K only, for BM98)",
]
genre = "OLDSKOOL BAROQUE"
impr = "4"
total = "35"
median = "9"
avg = "8.75"
regist = "2018/10/20 08:43"
update = "2019/03/31 23:30"

[[entries]]
no = "5"
name = "太郎"
team = "CONTEMPORARY"
title = "とっとこハム"
size = "23561 KB"
addr = ["https://1drv.ms/u/s!AgqfFd7wACD2g4443lAjKgS8XB9kzA"]
genre = "ANIME SONG"
impr = "13"
total = "94"
median = "8"
avg = "7.23"
regist = "2018/10/20 10:53"
update = "2019/03/31 02:12"

[[entries]]
no = "6"
name = "YAN*TS Remix by Mister.Himi"
team = "CONTEMPORARY"
title = "Estrella†Catedral -Revolutionary.Himix-"
size = "4993 KB"
addr = ["http://nekokan.dyndns.info/~anonymous/n/o/i/z/estrella_catedral_remix.rar"]
genre = "[CONTEMPORARY] Gothic Baroque"
impr = "3"
total = "24"
median = "8"
avg = "8"
regist = "2018/10/20 19:35"
update = "2019/03/31 23:25"

[[entries]]
no = "7"
name = "Nakaiankow"
team = "CONTEMPORARY"
title = "The Legend (Nakaiankow Remix)"
size = "38667 KB"
addr = ["https://drive.google.com/open?id=1wE-fgYvtRxZmI5XEcXKHMKgkDt4rBNqW"]
genre = "Hardstyle"
impr = "4"
total = "37"
median = "9"
avg = "9.25"
regist = "2018/11/04 23:14"
update = "2019/03/31 23:35"

[[entries]]
no = "8"
name = "don't worry"
team = "CONTEMPORARY"
title = "遅刻"
size = "8440 KB"
addr = ["https://www.dropbox.com/s/gmxdtpgscg09627/chikoku.zip?dl=1"]
genre = "2018年G2Rの旅"
impr = "3"
total = "25"
median = "8"
avg = "8.33"
regist = "2018/11/05 00:05"
update = "2019/03/31 23:38"

[[entries]]
no = "9"
name = "scytheleg"
team = "CONTEMPORARY"
title = "Battlekeys Megamix '18 (FR Mix)"
size = "35394 KB"
addr = ["http://scytheleg.sakura.ne.jp/tempyou/bms/bms/megamix2.rar"]
genre = "Thanks for many oldskool BMS all rights Karate"
impr = "5"
total = "49"
median = "10"
avg = "9.8"
regist = "2018/12/02 01:35"
update = "2018/12/26 11:59"

[[entries]]
no = "10"
name = "DJ 惣"
team = "CONTEMPORARY"
title = "KUSOSUMASU2018"
size = "2995 KB"
addr = ["https://www.dropbox.com/s/q6at4v4dqd711ht/UNKO.zip?dl=1"]
genre = "OLDSCHOOL X'mas Core"
impr = "5"
total = "23"
median = "5"
avg = "4.6"
regist = "2018/12/25 00:31"
update = "2019/03/31 23:05"
