[[entries]]
no = "1"
name = "uma"
team = "BGAPARTY Unlimited"
title = "Sweet Little Chocolate"
size = "39000 KB"
addr = [
    "本体+BGA差分",
    "https://drive.google.com/open?id=1JU-eu73-qoEydAJSRp4mqPdx5Y5_Bp_B",
    "BGA差分のみ",
    "https://drive.google.com/file/d/152ZcH1HnTQl2RGpYP1MI-7bslFpBGmod",
    "beatoraja用960x720サイズBGA",
    "https://drive.google.com/open?id=1s9mLJ9VB719fAF8ce3G2x5ZNlUq9un63",
]
genre = "Hardcore"
impr = "13"
total = "--"
median = "--"
avg = "--"
regist = "2018/12/23 00:46"
update = "2019/01/14 01:39"

[[entries]]
no = "2"
name = "narve"
team = "BGAPARTY Unlimited"
title = "osmosis"
size = "44088 KB"
addr = [
    "・BMS+BGAセット",
    "https://drive.google.com/open?id=1Jbwb5mLx1u_NlojkfWCc5KmFdgOCRZtd",
    "・beatoraja用差分(640x360・BGAのみ)",
    "https://drive.google.com/open?id=1922pDApAqt2CBp5R1zAnoBPNBKcPbkNQ",
]
genre = "psychedelic trance"
impr = "14"
total = "--"
median = "--"
avg = "--"
regist = "2018/12/24 02:08"
update = "2019/01/17 12:01"

[[entries]]
no = "3"
name = "cybermiso"
team = "BGAPARTY Unlimited"
title = "MUSIC MACHINES SHOWER"
size = "60100 KB"
addr = [
    "本体+BGA差分",
    "https://drive.google.com/open?id=122GBRgv8e5URBj3BjPowIRy3lRNcaZi8",
    "BGA差分ONLY",
    "https://drive.google.com/open?id=1O3caBy5qw5zz3pWgGsWXWdcQR8FjrwI_",
]
genre = "00's ELECTRO POP"
impr = "13"
total = "--"
median = "--"
avg = "--"
regist = "2018/12/27 23:28"
update = "2019/01/13 23:48"

[[entries]]
no = "4"
name = "DJ MTYS"
team = "BGAPARTY Classic"
title = "the magnificent babylon stars (inferno remix)"
size = "3388 KB"
addr = [
    "http://scytheleg.sakura.ne.jp/tempyou/bms/bga/stl_magnifi_bga.rar",
    "(Source BMS)",
    "http://www.yamajet.com/bms/data/yamajet_the_magnificent_babylon_stars_inferno_remix.rar",
]
genre = "BIG BEAT"
impr = "11"
total = "--"
median = "--"
avg = "--"
regist = "2018/12/30 15:18"
update = "2019/01/13 23:51"

[[entries]]
no = "5"
name = "I-kani (itaojirou)"
team = "BGAPARTY Unlimited"
title = "futurescape"
size = "4140 KB"
addr = ["https://drive.google.com/uc?id=1-4P7Yw-1ogN5UGeAnbLm5CRXyb5_GfE3&export=download"]
genre = "Trance"
impr = "10"
total = "--"
median = "--"
avg = "--"
regist = "2018/12/31 17:43"
update = "2019/01/13 23:50"

[[entries]]
no = "6"
name = "haikawa hldgs"
team = "BGAPARTY Classic"
title = "kamal daura"
size = "2102 KB"
addr = [
    "・BGA",
    "https://drive.google.com/open?id=15jCqh0szuokmdgUOpEKeDYE4TZlEN9Y7",
    "・Source BMS",
    "http://manbow.nothing.sh/event/event.cgi?action=More_def&num=15&event=112",
]
genre = "Indian Ragga Jungle"
impr = "12"
total = "--"
median = "--"
avg = "--"
regist = "2019/01/01 00:00"
update = "2019/01/14 00:00"

[[entries]]
no = "7"
name = "almea*"
team = "BGAPARTY Unlimited"
title = "Azurite"
size = "238000 KB"
addr = ["https://www.dropbox.com/s/hm88dilh0xqfvf7/%5Balmea%EF%BC%8A%5D%20Azurite.zip?dl=1"]
genre = "Artcore"
impr = "11"
total = "--"
median = "--"
avg = "--"
regist = "2019/01/03 21:01"
update = "2019/01/13 23:52"

[[entries]]
no = "8"
name = "テヅカ × Qayo"
team = "BGAPARTY Unlimited"
title = "ニニ"
size = "63020 KB"
addr = [
    "BMS＋BGA",
    "https://drive.google.com/open?id=1_NRfzTqluP9Bi26bdgZOxOcqrPsbZXNs",
]
genre = "ORIENTAL CORE"
impr = "9"
total = "--"
median = "--"
avg = "--"
regist = "2019/01/06 15:11"
update = "2019/01/14 00:06"

[[entries]]
no = "9"
name = "牧野"
team = "BGAPARTY Unlimited"
title = "From Megalopolis with Love"
size = "117425 KB"
addr = [
    "[mp4&wmv]",
    "https://drive.google.com/open?id=1k-cStGLTNEWKMKrZ3YEPzZbNHJE8HnJw",
    "[wmvOnly]",
    "https://drive.google.com/open?id=1DZ2L5yZ2LxQiy5kiD3FUpL5ACrUmZWIr",
    "beatorajaなど用に高画質mp4データを同梱しているのが上です。wmvは不要であれば削除してください。",
    "LR2の人は下でいいと思います。",
]
genre = "Synthwave/Future Funk"
impr = "14"
total = "--"
median = "--"
avg = "--"
regist = "2019/01/06 22:51"
update = "2019/01/13 23:57"
