[[entries]]
no = "1"
name = "REVLIS"
title = "Manupulation"
size = "52841 KB"
addr = ["https://drive.google.com/open?id=1tDYuOfWCdN_vVgsW9HgkOrKmC7gtpScV"]
genre = "PSYCHEDELIC TRANCE"
impr = "4"
total = "4"
median = "0"
avg = "1"
regist = "2019/05/09 00:00"
update = "2019/05/27 14:42"

[[entries]]
no = "2"
name = "NASA"
title = "Marineside Cafeteria"
size = "4130 KB"
addr = [
    "(wav 35.03MB)",
    "https://www.dropbox.com/s/nxycd3a6e9refl7/Marineside%20Cafeteria_wav.zip?dl=1",
    "(ogg 4.13MB)",
    "https://www.dropbox.com/s/n9p35qsjqo0qcrc/Marineside%20Cafeteria_ogg.zip?dl=1",
    "(修正差分)",
    "https://www.dropbox.com/s/xsx9zeuyz4bl269/Marineside%20Cafeteria_fix.zip?dl=1",
]
genre = "Piano Shuffle"
impr = "9"
total = "9"
median = "0"
avg = "1"
regist = "2019/05/09 00:01"
update = "2019/05/26 22:11"

[[entries]]
no = "3"
name = "Nakaiankow"
title = """Nalpha (Nakaiankow "I'm still NonAlpha even in 2k19" Remix)"""
size = "21365 KB"
addr = [
    "OGG:",
    "https://drive.google.com/open?id=1pyT83UmJsh3GLDoyzV-XmlTahHG4q8m6",
    "WAV:",
    "https://www.dropbox.com/s/jnao9vyetw78dbz/suna_-_nalpha_nakaiankow_remix_wav.rar?dl=1",
]
genre = "Halfstep Drum'n'bass"
impr = "4"
total = "4"
median = "0"
avg = "1"
regist = "2019/05/09 00:01"
update = "2019/05/25 15:15"

[[entries]]
no = "4"
name = "0310 pres. まゆP"
title = "まゆすき ~Deep Inside~"
size = "11395 KB"
addr = [
    "OGG:",
    "https://drive.google.com/open?id=1vbqKgoTK1xG_BDu9NW_ba6sMoBbYbq5o",
    "WAV:",
    "https://drive.google.com/open?id=1xTKwguOKGQ8OkoUM19YrYYRHP908nW67",
]
genre = "Deeptech House"
impr = "7"
total = "7"
median = "0"
avg = "1"
regist = "2019/05/09 22:14"
update = "2019/05/26 22:00"

[[entries]]
no = "5"
name = "しらいし"
title = "硬核機動-remake"
size = "7000 KB"
addr = ["https://drive.google.com/uc?id=1gS8t4kyzKQqZ2ZQaqnKpyOSBpqjWwpku"]
genre = "Merodius"
impr = "5"
total = "5"
median = "0"
avg = "1"
regist = "2019/05/09 23:51"
update = "2019/05/25 15:31"

[[entries]]
no = "6"
name = "LuL"
title = "Acid Lady (LuL Prog Remix)"
size = "27996 KB"
addr = ["https://www.dropbox.com/s/zi61lwf7c4stm7e/acidrmx.zip?dl=1"]
genre = "ACID / PROG"
impr = "4"
total = "4"
median = "0"
avg = "1"
regist = "2019/05/11 23:02"
update = "2019/05/25 15:35"

[[entries]]
no = "7"
name = "Kanata.S"
title = "After 15 Years"
size = "2995 KB"
addr = ["http://ponytailrecord.com/BMS/after_15_years.zip"]
genre = "WORLD HOUSE"
impr = "5"
total = "5"
median = "0"
avg = "1"
regist = "2019/05/12 18:22"
update = "2019/05/26 18:42"

[[entries]]
no = "8"
name = "Takuya Namba feat. HARD GU.W-C.I"
title = "SYNR (BMS Edit.)"
size = "14148 KB"
addr = ["https://drive.google.com/file/d/1wJJnrCBcK3LBqAysNQ7elA4J8MS7yr76/view?usp=sharing"]
genre = "Abstract Hip-Hop / Autonomic"
impr = "9"
total = "9"
median = "0"
avg = "1"
regist = "2019/05/14 21:02"
update = "2019/05/26 23:57"

[[entries]]
no = "9"
name = "ルゼ"
title = "ZEUS † 666"
size = "46300 KB"
addr = ["http://www.luzeria.net/music/86_zeus666_ogg.zip"]
genre = "PANDORA REVELATION"
impr = "9"
total = "9"
median = "0"
avg = "1"
regist = "2019/05/19 15:15"
update = "2019/05/26 23:02"

[[entries]]
no = "10"
name = "DJ Saw-Low vs nob unfotunated"
title = "GIGAGOONIES Part2"
size = "22564 KB"
addr = ["http://scytheleg.sakura.ne.jp/tempyou/bms/bms/djsl-pmc_gg2.rar"]
genre = "RAVE"
impr = "7"
total = "7"
median = "0"
avg = "1"
regist = "2019/05/19 23:30"
update = "2019/05/26 22:29"

[[entries]]
no = "11"
name = "nekomimi_STRaw"
title = "教会でセーブしたときに流れそうなBeep tune(教会では流れなさそうなMelodic D'n'B Extended Remix)"
size = "35737 KB"
addr = [
    "OGG版:",
    "https://dl.dropboxusercontent.com/s/glm2mdr0hcngag0/Beep_tune_Remix_ogg.zip?dl=0",
    "WAV版:",
    "https://dl.dropboxusercontent.com/s/2lsk15am0vgd3tn/Beep_tune_Remix.zip?dl=0",
]
genre = "Melodic D'N'B"
impr = "8"
total = "8"
median = "0"
avg = "1"
regist = "2019/05/19 23:59"
update = "2019/05/26 18:18"
