[[entries]]
no = "1"
name = "A&T"
title = "CODE:SS2"
size = "2770 KB"
addr = [
    "http://www16.big.or.jp/~shockc/",
    "(BMS)",
    "http://liz.nothing.sh/at/AT_codess2_bga.rar",
    "(BGA)",
]
genre = "Rock"
impr = "13"
total = "13"
avg = "1"
regist = "2004/02/28 00:04"
update = "2004/03/13 23:49"

[[entries]]
no = "2"
name = "RED"
title = "The Beautiful Sunset of That Day(Radio Edit)"
size = "7000 KB"
addr = [
    "http://www.sound.jp/wirel-yourl/",
    "(BMS)",
    "http://red-bga.hp.infoseek.co.jp/red_sunset_bga.zip",
    "(BGA)",
    "http://red-bga.hp.infoseek.co.jp/red_sunset_bga_for_mac.zip",
    "(for MacBeat User)",
]
genre = "Hard Trance"
impr = "14"
total = "14"
avg = "1"
regist = "2004/02/28 00:49"
update = "2004/03/13 23:36"

[[entries]]
no = "3"
name = "冬弥"
title = "worlds"
size = "4320 KB"
addr = [
    "http://www001.upp.so-net.ne.jp/keyc/",
    "(BMS)",
    "http://www.interq.or.jp/red/jinkun/touya_worlds_bga.zip",
    "(BGA)",
]
genre = "drum'n'bass"
impr = "13"
total = "13"
avg = "1"
regist = "2004/02/28 03:40"
update = "2004/03/13 23:53"

[[entries]]
no = "4"
name = "makein"
title = "少女の檻 Last Night, Last Dancing"
size = "3469 KB"
addr = [
    "BMS:",
    "http://homepage3.nifty.com/beatmario/",
    "BGA:",
    "http://makein.hp.infoseek.co.jp/box/makein_ori.lzh",
    "BMSはビートまりお氏のHPのBMSページからお願いします。",
]
genre = "EURO BEAT"
impr = "12"
total = "12"
avg = "1"
regist = "2004/02/28 21:40"
update = "2004/03/13 23:55"

[[entries]]
no = "5"
name = "66"
title = "CANDY☆"
size = "3143 KB"
addr = [
    "http://liz.nothing.sh/bgafinal/songs_candy.html",
    "(ダウンロードページへ飛びます)",
]
genre = "HAPPY HARDCORE"
impr = "25"
total = "25"
avg = "1"
regist = "2004/02/28 23:21"
update = "2004/03/13 23:51"

[[entries]]
no = "6"
name = "642"
title = "FLUTE MAN (remix)"
size = "4000 KB"
addr = [
    "http://yamaguchi.cool.ne.jp/hima642/642_flute_bga_LQ.rar",
    "http://yamaguchi.cool.ne.jp/hima642/642_flute_bga_HQ.rar",
]
genre = "DRUM'N'BASS"
impr = "11"
total = "11"
avg = "1"
regist = "2004/02/29 06:07"
update = "2004/03/13 23:44"

[[entries]]
no = "7"
name = "tes"
title = "feedpoint#02"
size = "2680 KB"
addr = [
    "(BGA)",
    "http://t-e-s.hp.infoseek.co.jp/tes_feedpoint_bga.zip",
    "(BMS)",
    "http://sound.jp/nixx/",
]
genre = "hard techno"
impr = "14"
total = "14"
avg = "1"
regist = "2004/02/29 08:58"
update = "2004/03/13 23:47"

[[entries]]
no = "8"
name = "SYNK"
title = "Power Line"
size = "6170 KB"
addr = [
    "http://www.ismusic.ne.jp/synk/synk_powerline_bga.zip",
    "[BGA]",
    "http://synktank.hp.infoseek.co.jp/synk_powerline_bga.zip",
    "[BGA (Mirror)]",
    "http://www.ismusic.ne.jp/banglar/",
    "[BMS]",
]
genre = "techno"
impr = "10"
total = "10"
avg = "1"
regist = "2004/02/29 13:43"
update = "2004/03/13 23:57"

[[entries]]
no = "9"
name = "AOiRO_Manbow"
title = "GREEN GREENS -tumbling style-"
size = "1407 KB"
addr = [
    "http://www.yamajet.com/",
    "(BMS)",
    "http://manbow.nothing.sh/bgapartyfinal/AM_yamajet_ggs_re_bga.rar",
    "(BGA)",
]
genre = "HAPPY HARDCORE"
impr = "8"
total = "8"
avg = "1"
regist = "2004/03/01 01:15"
update = "2004/03/13 23:43"

[[entries]]
no = "10"
name = "140"
title = "phase IV"
size = "8350 KB"
addr = [
    "http://commonsense.web.infoseek.co.jp/",
    "（BMS）",
    "http://www.h6.dion.ne.jp/~dlt_3bit/140_Phase04BGA.zip",
    "（BGA）",
    "http://www.h6.dion.ne.jp/~dlt_3bit/140_phase04bgaLQ.exe",
    "(LQ版 4820KB)",
]
genre = "d'n'b"
impr = "13"
total = "13"
avg = "1"
regist = "2004/03/01 11:28"
update = "2004/03/13 23:42"

[[entries]]
no = "11"
name = "140"
title = "Flusso bianco della neve"
size = "6760 KB"
addr = [
    "http://www.yamajet.com/",
    "(BMS）",
    "http://www.h6.dion.ne.jp/~dlt_3bit/140_flussoBGA.zip",
    "（bga）",
]
genre = "lounge house"
impr = "12"
total = "12"
avg = "1"
regist = "2004/03/01 11:33"
update = "2004/03/13 23:46"

[[entries]]
no = "12"
name = "66"
title = "+45"
size = "1129 KB"
addr = [
    "http://www.kcnet.ne.jp/~hyuri/f-6th/",
    "(BMS)",
    "http://liz.nothing.sh/bgafinal/66_+45_bga.rar",
    "(BGA)",
]
genre = "noise pop"
impr = "7"
total = "7"
avg = "1"
regist = "2004/03/02 02:19"
update = "2004/03/13 23:57"

[[entries]]
no = "13"
name = "氷魔"
title = "7th"
size = "7420 KB"
addr = [
    "http://absolutebeat.k-free.net/i/",
    "(BMS)",
    "http://www10.ocn.ne.jp/~zeroxeno/7th_bga.GCA",
    "(BGA)",
]
genre = "trance"
impr = "7"
total = "7"
avg = "1"
regist = "2004/03/03 23:14"
update = "2004/03/13 23:57"

[[entries]]
no = "14"
name = "あかくらげ & M.H"
title = "Endless Dream"
size = "5434 KB"
addr = [
    "びーえむえすは「",
    "http://kobe.cool.ne.jp/linker/",
    "」からおとせます。",
    "びーじーえーはしたのあどれすからどれかひとつをだうんろーどしてください。",
    "http://sound.jp/white_c_m/dance_get_you_2004/",
    "(だうんろーどぺーじにとびます)",
    "http://www.geocities.co.jp/Playtown-Bingo/8394/endlessdream_bga.zip",
    "(にじゅうあっしゅくです)",
    "http://a-p.cside.ne.jp/dance_get_you_2004/endlessdream_bga.rar",
    "http://kame_37.at.infoseek.co.jp/endlessdream_bga.rar",
    "http://www.hayasoft.com/nekomimi/dance_get_you_2004/endlessdream_bga.rar",
    "http://image.freespace.jp/twin_tail/2nd/dance_get_you_2004/endlessdream_bga.rar",
]
genre = "HAPPY HARDCORE"
impr = "15"
total = "15"
avg = "1"
regist = "2004/03/04 02:20"
update = "2004/03/13 23:48"

[[entries]]
no = "15"
name = "cyclia"
title = "(^^)"
size = "1753 KB"
addr = [
    "http://www.yamajet.com/",
    "(BMS作者さんのページへ)",
    "http://www.ismusic.ne.jp/naotyu/cyc/cyc-bga_sugoi-FC.zip",
    "(24bit/1753KB)",
]
genre = "foon"
impr = "13"
total = "13"
avg = "1"
regist = "2004/03/06 15:07"
update = "2004/03/22 00:18"

[[entries]]
no = "16"
name = "Lo-KREW (cyclia)"
title = "BLUEWATER"
size = "2411 KB"
addr = [
    "http://www3.to/a_shop/",
    "(BMS)",
    "http://www.ismusic.ne.jp/naotyu/cyc/cyc-bga_bw.zip",
    "(16色/2411KB)",
    "http://www.ismusic.ne.jp/naotyu/cyc/cyc-bga_bw-HQ.zip",
    "(256色/6446KB)",
]
genre = "Art Core"
impr = "9"
total = "9"
avg = "1"
regist = "2004/03/06 15:13"
update = "2004/03/13 10:31"

[[entries]]
no = "17"
name = "cyclia"
title = "Acque Minerali"
size = "5928 KB"
addr = [
    "http://www.ismusic.ne.jp/naotyu/music/12.html",
    "(BMS/BGAダウンロード先)",
]
genre = "Drum'n'Bass"
impr = "8"
total = "8"
avg = "1"
regist = "2004/03/06 15:26"
update = "2004/03/12 15:38"

[[entries]]
no = "18"
name = "G"
title = "on the sequence #3"
size = "4330 KB"
addr = [
    "http://kp213.hp.infoseek.co.jp/bms/list1.html",
    "(BMS)",
    "http://www.13sec.net/ots3/ots.html",
    "(BGA/zip)",
]
genre = "d`n`b"
impr = "14"
total = "14"
avg = "1"
regist = "2004/03/06 23:57"
update = "2004/03/13 23:43"

[[entries]]
no = "19"
name = "ers"
title = "witchcraft"
size = "3100 KB"
addr = [
    "BMS",
    "http://homepage1.nifty.com/paraoka/",
    "BGA",
    "http://www.geocities.co.jp/Playtown-Queen/2149/bga/witch_bga.zip",
]
genre = "bigbeat"
impr = "14"
total = "14"
avg = "1"
regist = "2004/03/07 00:28"
update = "2004/03/28 21:14"
