[[entries]]
no = "1"
name = "w_tre"
title = "Cybenko's Theorem"
size = "17400 KB"
addr = [
    "https://bit.ly/2RAAiUy",
    "(ogg, 17MB)",
    "https://bit.ly/3caoHmQ",
    "(wav, 108MB)",
    "(mirror)",
    "https://drive.google.com/open?id=1yEGRGzY7VsUT6iRNTkdw0BqXgIuwRiMt",
    "(ogg)",
    "https://drive.google.com/open?id=1gJaMQ8d6htbBWvAVyvQ2NjjqLzHb8TL2",
    "(wav)",
    "※ 2020-04-13 08:00 リンクの不具合を修正",
]
genre = "シグモイドデュエット"
impr = "33"
total = "99"
median = "3"
avg = "3"
regist = "2020/04/05 00:01"
update = "2020/06/24 22:29"

[[entries]]
no = "2"
name = "Cyanide beta"
title = "門出の扉、桜ひとひら"
size = "17800 KB"
addr = [
    "(修正適用済本体)",
    "https://www.dropbox.com/s/dced11rqdkthx5u/kadodenotobira_sakurahitohira.zip?dl=1",
    "(おまけ7KEYS)",
    "https://www.dropbox.com/s/dhq7qo3e1s2wvi5/kadodenotobira_sakurahitohira_add.zip?dl=1",
    "(修正差分 04/06 15:39追記)",
    "https://www.dropbox.com/s/egv5nhzffzyduyu/kadodenotobira_sakurahitohira_fix.zip?dl=1",
    "(修正差分2 04/09 20:00追記)",
    "https://www.dropbox.com/s/j4883byy107djq3/kadodenotobira_sakurahitohira_fix2.zip?dl=1",
]
genre = "トラジェクトリー"
impr = "26"
total = "71"
median = "3"
avg = "2.73"
regist = "2020/04/05 00:01"
update = "2020/05/05 02:05"

[[entries]]
no = "3"
name = "Lollipop"
title = "a day in the park"
size = "25908 KB"
addr = ["https://mega.nz/file/XagihQJS#6GWsoKHO9VZ7bs6YejxRxENpVxrQeITgTVkXjkkIBM0"]
genre = "アーバン・ライフスタイル"
impr = "26"
total = "63"
median = "2"
avg = "2.42"
regist = "2020/04/05 04:59"
update = "2020/05/04 00:27"

[[entries]]
no = "4"
name = "戒斗"
title = "彼方紡ぐ伝承の旋律"
size = "28974 KB"
addr = ["https://dl.dropboxusercontent.com/s/a6rf0xclt9zxe7o/tradition_kanata.zip"]
genre = "トラディション"
impr = "25"
total = "59"
median = "2"
avg = "2.36"
regist = "2020/04/05 12:21"
update = "2020/05/04 00:43"

[[entries]]
no = "5"
name = "mots"
title = "The Hillside Terrace - 2020 Spring Edit -"
size = "10064 KB"
addr = ["https://drive.google.com/file/d/1ewGffZP89LyYrXuqEDhr59xBmsM6yoF7/view?usp=sharing"]
genre = "インストラメンタル ポップ"
impr = "24"
total = "49"
median = "2"
avg = "2.04"
regist = "2020/04/05 15:11"
update = "2021/11/02 22:35"

[[entries]]
no = "6"
name = "CYLTIE."
title = "キマグレ☆テキトウ・アンサンブル→コミュニケーション Re:Dive!"
size = "131072 KB"
addr = [
    "https://drive.google.com/open?id=1SqqFcLJKNqtFXDKVgyLklbCMrJs6WMsM",
    "(wav版)",
    "https://drive.google.com/open?id=15miJs9KveJ44nAKZspBUBcT8Gd5L334V",
    "(ogg版)",
    "※2020/4/10 1:50頃までにogg版をDLした方へ",
    "一部音が抜けていた問題の修正ファイル(出てきたファイルを元のフォルダに入れてください)",
    "https://drive.google.com/open?id=155Hod9Rif_MmlF_b0lYKQzXEuEWbEK2n",
    "※差分製作者向け 未配置pmsファイル(C4さんありがとうございます……！)",
    "https://drive.google.com/open?id=1OFjaBVZaMPmCljFbHIFawhcSExySGY3I",
]
genre = "スピードポップコア"
impr = "28"
total = "83"
median = "3"
avg = "2.96"
regist = "2020/04/05 21:53"
update = "2020/05/04 00:14"

[[entries]]
no = "7"
name = "MITCH DOWNVELL"
title = "FIELDER '87"
size = "13339 KB"
addr = ["https://mega.nz/file/X8sjTQRB#VAqqjqqGjxnffM-1xwpcyO6ZFkq0OdBdFWrh0N53u0k"]
genre = "クリック・スウィング"
impr = "26"
total = "66"
median = "3"
avg = "2.53"
regist = "2020/04/07 15:23"
update = "2020/05/04 00:39"

[[entries]]
no = "8"
name = "ず"
title = "あらぞめ"
size = "8530 KB"
addr = ["https://anonymous.nekokan.dyndns.info/data/zu/Arazome_zu.zip"]
genre = "お花見ポップ"
impr = "24"
total = "55"
median = "2"
avg = "2.29"
regist = "2020/04/09 05:38"
update = "2020/05/04 10:17"

[[entries]]
no = "9"
name = "しらいし"
title = "Square Song"
size = "2400 KB"
addr = ["https://drive.google.com/uc?id=1wdK-uIzcbRwMgNFxAw1qt1VoBgAOgJEO"]
genre = "ELECTROPOP"
impr = "25"
total = "46"
median = "2"
avg = "1.84"
regist = "2020/04/09 17:04"
update = "2020/05/04 10:26"

[[entries]]
no = "10"
name = "Nakaiankow"
title = "The Tiger Eyes"
size = "31372 KB"
addr = [
    "ogg/png:",
    "https://drive.google.com/open?id=1VDSTgTgZ4xSRba2IkHI1tk-uqomGB2JK",
]
genre = "ハイブリッドエレクトロニック"
impr = "28"
total = "79"
median = "3"
avg = "2.82"
regist = "2020/04/10 12:11"
update = "2020/05/04 10:30"

[[entries]]
no = "11"
name = "Alexandre de la Fontaine"
title = "Le jeu des neuf boutons"
size = "9534 KB"
addr = ["https://mega.nz/file/nfo1XbhZ#cNLR82pqrMaZY__fPSy1sce9xHG7QJQJIATMHz4ZsfY"]
genre = "バゲット"
impr = "25"
total = "69"
median = "3"
avg = "2.76"
regist = "2020/04/10 13:54"
update = "2020/05/04 00:36"

[[entries]]
no = "12"
name = "池田哲次"
title = "Nowin"
size = "6103 KB"
addr = ["https://drive.google.com/open?id=1DPk6r3Iu9EfOLl1V7LdF-p1EyL1LSawO"]
genre = "シンスワン"
impr = "23"
total = "49"
median = "2"
avg = "2.13"
regist = "2020/04/10 22:33"
update = "2020/05/04 10:23"

[[entries]]
no = "13"
name = "ume"
title = "#E198B4"
size = "34000 KB"
addr = ["https://drive.google.com/open?id=1HO3xPgGEnYMCZoQO8kXwbwbHeAjsjmXQ"]
genre = "ディパーチャー"
impr = "26"
total = "72"
median = "3"
avg = "2.76"
regist = "2020/04/10 23:23"
update = "2020/05/04 10:33"

[[entries]]
no = "14"
name = "daisan"
title = "for teenines"
size = "11519 KB"
addr = ["http://clockxellox.sakura.ne.jp/BMS/daisan_for_teenines.zip"]
genre = "トリオスウィング"
impr = "26"
total = "70"
median = "3"
avg = "2.69"
regist = "2020/04/11 07:57"
update = "2020/05/04 10:20"

[[entries]]
no = "15"
name = "dwarf"
title = "A seashell utopia"
size = "32581 KB"
addr = ["https://drive.google.com/open?id=1E9xuZ-3MYDZ23afaViwU2ZljhgHhQJfQ"]
genre = "アクアティック・ゲーマーズ・ウェーブ"
impr = "27"
total = "80"
median = "3"
avg = "2.96"
regist = "2020/04/11 16:00"
update = "2020/05/04 00:15"

[[entries]]
no = "16"
name = "zatsuzatsu"
title = "青天"
size = "31000 KB"
addr = ["https://www.dropbox.com/s/vt5i618t3qwj6pa/ox_seiten.zip?dl=1"]
genre = "ポップステップ2"
impr = "27"
total = "77"
median = "3"
avg = "2.85"
regist = "2020/04/11 17:25"
update = "2020/05/04 00:55"

[[entries]]
no = "17"
name = "Deadline Hater"
title = "Tự sát"
size = "61277 KB"
addr = [
    "https://1drv.ms/u/s!AodogG7jJNekbz5KczdTpcYt45o?e=7hac6y",
    "(PMS archive - 1 chart (Normal 13) - 61,277 KB)",
    "https://1drv.ms/u/s!AodogG7jJNekcOwzJd452jG1syE?e=PX2mc8",
    "(BMS archive - 1 chart (SP Normal 4) - 61,277 KB)",
]
genre = "F"
impr = "24"
total = "36"
median = "1"
avg = "1.5"
regist = "2020/04/12 00:10"
update = "2020/05/04 11:02"

[[entries]]
no = "18"
name = "0310"
title = '"hello, there"'
size = "11650 KB"
addr = [
    "OGG (recommended):",
    "https://drive.google.com/open?id=1jVSlxWz5e7YrcRZURiScvKUz1zrkQ3zR",
    "WAV:",
    "https://drive.google.com/open?id=1dSNaZVka4ULuPbhwczYYL0ZjVB-14A4n",
]
genre = "むゆう"
impr = "26"
total = "71"
median = "3"
avg = "2.73"
regist = "2020/04/12 04:13"
update = "2020/05/04 00:48"

[[entries]]
no = "19"
name = "agu"
title = "Ratman's Terrarium Medley"
size = "5031 KB"
addr = ["https://drive.google.com/file/d/1niEixMGZiP_LFQHhjIJj6-B8VxyY2MHq/view?usp=sharing"]
genre = "Fantasy"
impr = "23"
total = "45"
median = "2"
avg = "1.95"
regist = "2020/04/12 12:21"
update = "2020/05/04 00:34"

[[entries]]
no = "20"
name = "ねぎとまと"
title = "AngelPainter"
size = "14135 KB"
addr = ["https://drive.google.com/uc?id=17HUVTSbYu3-UtCFCHh4kBhnnnURi-M6v"]
genre = "ふわふわポップ"
impr = "28"
total = "75"
median = "3"
avg = "2.67"
regist = "2020/04/12 17:46"
update = "2020/05/04 10:14"

[[entries]]
no = "21"
name = "草壁美鈴"
title = "Eagle Tears... (Off Vocal)"
size = "14000 KB"
addr = ["http://yaritaihoudie.free.fr/bms/boxofsins/eagle_tears.rar"]
genre = "アニメタル"
impr = "25"
total = "49"
median = "2"
avg = "1.96"
regist = "2020/04/12 20:25"
update = "2023/05/26 11:51"

[[entries]]
no = "22"
name = "nekomimi_STRaw & C4"
title = "Fall Mirage ((Fall))"
size = "18678 KB"
addr = ["https://drive.google.com/uc?id=1WAI8OKO7ba7muI2TOoF0io6ibywWACCT"]
genre = "テクノ"
impr = "27"
total = "71"
median = "3"
avg = "2.62"
regist = "2020/04/12 21:43"
update = "2020/05/04 00:32"

[[entries]]
no = "23"
name = "nonomori feat. Noir"
title = "蘭"
size = "36100 KB"
addr = ["https://www.dropbox.com/s/o80in7klnml2eeg/%5Bnonomori%5Dran.zip?dl=1"]
genre = "アニメロック"
impr = "30"
total = "89"
median = "3"
avg = "2.96"
regist = "2020/04/12 22:17"
update = "2020/05/04 00:42"

[[entries]]
no = "24"
name = "KA-KU"
title = "マジカル♡ミラクル☆ヒロイズム"
size = "39000 KB"
addr = ["https://www.dropbox.com/s/29k3oo1e3lz4lsn/heroism.zip?dl=1"]
genre = "A-マジカルヒーローポップ"
impr = "26"
total = "60"
median = "2"
avg = "2.3"
regist = "2020/04/12 22:22"
update = "2020/05/04 00:21"

[[entries]]
no = "25"
name = "くるやのぶ"
title = "GraviSkull"
size = "6502 KB"
addr = ["https://www.dropbox.com/s/dwf4lba8rin51oz/Graviskull%5BHARDDANCE%20meets%20GABBA%5D.zip?dl=1"]
genre = "ハードダンスミーツガバ"
impr = "23"
total = "51"
median = "2"
avg = "2.21"
regist = "2020/04/12 22:39"
update = "2020/05/04 00:30"

[[entries]]
no = "26"
name = "Nego_tiator"
title = "Praesidium tridacnae"
size = "62118 KB"
addr = [
    "[本体]",
    "https://drive.google.com/file/d/1sl0GKhH3ebM5kSukpsSIvkB0Ne9Z_oUx/view?usp=sharing",
    "[修正Hyper・追加EX]",
    "https://drive.google.com/file/d/1wpnBrFuQzfJGtfZGCDNcawWnfadqQN4x/view?usp=sharing",
    "[HQ BGA]",
    "https://drive.google.com/file/d/1juy3JX2FPhGF585iRr6_7dGZoH5HX8pj/view?usp=sharing",
]
genre = "グレイス"
impr = "31"
total = "89"
median = "3"
avg = "2.87"
regist = "2020/04/12 23:29"
update = "2020/05/04 00:10"

[[entries]]
no = "27"
name = "KA-KU"
title = "My Best Friend"
size = "39000 KB"
addr = ["https://www.dropbox.com/s/nj5thrf0xa1jyno/MBF.zip?dl=1"]
genre = "フラワーゲイザー"
impr = "24"
total = "56"
median = "2"
avg = "2.33"
regist = "2020/04/12 23:44"
update = "2020/05/07 01:26"

[[entries]]
no = "28"
name = "Hyparpax"
title = "RAVE NIGHTINGALE"
size = "68985 KB"
addr = [
    "https://drive.google.com/open?id=1DAP4IRSIxeH9b-T6bPwY7CumpiV3ZCjK",
    "Hyper / EX:",
    "https://drive.google.com/open?id=1aQAmT_mX_1hCLvWnrFRPZefBAYhQFw3V",
]
genre = "ハード・レーブ・ユーフォリア"
impr = "26"
total = "76"
median = "3"
avg = "2.92"
regist = "2020/04/12 23:54"
update = "2020/05/04 00:25"
