[[entries]]
no = "1"
name = "Nakaiankow"
title = "#3000"
size = "1474 KB"
addr = [
    "MQ:",
    "https://drive.google.com/file/d/1OuzZUlHYoojOFVwYXACZ_o30LOLvxHMl/view?usp=sharing",
]
genre = "Dubstep"
impr = "30"
total = "228"
median = "8"
avg = "7.6"
regist = "2021/05/08 12:38"
update = "2021/06/14 23:51"

[[entries]]
no = "2"
name = "Nelf"
title = "Execution"
size = "1029 KB"
addr = [
    "DL(1029KB)",
    "https://www.dropbox.com/s/vgrl0thp0g0e210/Execution_nelf.zip?dl=1",
    "DL:HQver.(3744KB)",
    "https://www.dropbox.com/s/tvp1kkj1ve0llos/Execution_Nelf_HQ.zip?dl=1",
]
genre = "Acid"
impr = "31"
total = "271"
median = "9"
avg = "8.74"
regist = "2021/05/08 12:41"
update = "2021/06/15 00:00"

[[entries]]
no = "3"
name = "scamp"
title = "MEDUSA"
size = "1330 KB"
addr = ["https://dl.dropboxusercontent.com/s/lsc25rbx8sue5yo/%5Bscamp%5D%20MEDUSA.7z?dl=0"]
genre = "none"
impr = "20"
total = "106"
median = "5.5"
avg = "5.3"
regist = "2021/05/08 12:53"
update = "2021/06/14 23:50"

[[entries]]
no = "4"
name = "scamp"
title = "Rabbit Love it"
size = "1363 KB"
addr = ["https://dl.dropboxusercontent.com/s/emod83ljpf3frtv/%5Bscamp%5D%20Rabbit%20Love%20it.7z?dl=0"]
genre = "cheaptune"
impr = "25"
total = "131"
median = "6"
avg = "5.24"
regist = "2021/05/08 13:05"
update = "2021/06/14 23:49"

[[entries]]
no = "5"
name = "scamp"
title = "カムコウラ覚醒"
size = "1397 KB"
addr = ["https://dropboxusercontent.com/s/sr9cfz7163psd9k/%E3%82%AB%E3%83%A0%E3%82%B3%E3%82%A6%E3%83%A9%E8%A6%9A%E9%86%92%20%E6%B8%9B%E9%87%8F%E7%89%88.7z?dl=0"]
genre = "亀仙流武術"
impr = "22"
total = "131"
median = "6"
avg = "5.95"
regist = "2021/05/08 13:16"
update = "2021/06/14 23:49"

[[entries]]
no = "6"
name = "6CHA9N"
title = "チャネル"
size = "1032 KB"
addr = ["https://drive.google.com/uc?export=download&id=1gQ6r_3G7ddcI6cyOHlogNUxrK2TC090l"]
genre = "Electronica"
impr = "29"
total = "232"
median = "8"
avg = "8"
regist = "2021/05/08 13:58"
update = "2021/06/14 23:49"

[[entries]]
no = "7"
name = "Lollipop"
title = "ye olde marine snow"
size = "1213 KB"
addr = ["https://mega.nz/file/KGhEmCDb#p0OswQh2KhsZE_FW5DV3Jzs5eblqcktVPf-JIjW1cb4"]
genre = "Medieval"
impr = "27"
total = "204"
median = "7"
avg = "7.55"
regist = "2021/05/08 14:46"
update = "2021/06/14 23:48"

[[entries]]
no = "8"
name = "空読無 白眼"
title = "Biotope"
size = "489 KB"
addr = [
    "http://9domu46i.com/BMS/DOM30_Biotope.7z",
    "https://drive.google.com/file/d/1uZeHvVK2CCAL893q9ESLskvBbz95BkA-/view?usp=sharing",
    "(ミラー)",
]
genre = "_"
impr = "31"
total = "265"
median = "9"
avg = "8.54"
regist = "2021/05/08 14:59"
update = "2021/06/14 23:48"

[[entries]]
no = "9"
name = "Block"
title = "Subdivision recollection"
size = "53 KB"
addr = ["https://drive.google.com/file/d/1wkvrSXNtgOOBFCqAQZLBRoxdTDsO6FtR/view?usp=sharing"]
genre = "Techno"
impr = "29"
total = "180"
median = "6"
avg = "6.2"
regist = "2021/05/08 15:09"
update = "2021/06/14 23:50"

[[entries]]
no = "10"
name = "縺九℃繧ｦ縺輔ぐ"
title = "縺薙ｏ繧後ち縺帙°繧､"
size = "788 KB"
addr = ["https://anonymous.nekokan.dyndns.info/data/__.7z"]
genre = "_"
impr = "28"
total = "241"
median = "9"
avg = "8.6"
regist = "2021/05/08 16:27"
update = "2021/06/14 23:47"

[[entries]]
no = "11"
name = "しらいし"
title = "ディメンジャー"
size = "1440 KB"
addr = ["https://drive.google.com/uc?id=1m2xDFQCcQkGViK2hoVCv489pSISPSfCz"]
genre = "FantasyMonster"
impr = "28"
total = "215"
median = "8"
avg = "7.67"
regist = "2021/05/08 23:55"
update = "2021/06/14 23:04"

[[entries]]
no = "12"
name = "DJ AE"
title = "First Time"
size = "1399 KB"
addr = ["https://www.dropbox.com/s/sevv5lvgazg32no/first_time.zip?dl=0"]
genre = "Rave"
impr = "31"
total = "270"
median = "9"
avg = "8.7"
regist = "2021/05/09 23:57"
update = "2021/06/20 19:47"

[[entries]]
no = "13"
name = "Ym1024"
title = "urara"
size = "42 KB"
addr = ["http://yellowmapleleaf.com/bms/ym60_urara_wav-lq.7z"]
genre = "Chip Shuffle Pop'n"
impr = "31"
total = "272"
median = "9"
avg = "8.77"
regist = "2021/05/10 22:01"
update = "2021/06/14 22:45"

[[entries]]
no = "14"
name = "И"
title = "Chugga Chugga Cha-ching"
size = "1404 KB"
addr = [
    "https://darksabun.github.io/songs/imuh3_Chugga_Chugga_Cha-ching.zip",
    "2021/05/14 23:53 (GMT+9) PMS Updated.",
    "追加差分(PMS)：",
    "https://darksabun.github.io/songs/imuh3_Chugga_Chugga_Cha-ching_tuika.zip",
]
genre = "OpenTTD"
impr = "21"
total = "96"
median = "4"
avg = "4.57"
regist = "2021/05/13 03:05"
update = "2021/06/23 19:17"

[[entries]]
no = "15"
name = "MITCH DOWNVELL"
title = "visceral"
size = "1264 KB"
addr = ["https://drive.google.com/file/d/1shdsYKhaSLKq7AsKR9BumEOxAYT4TaKr/view?usp=sharing"]
genre = "TECHNO BASS"
impr = "27"
total = "228"
median = "9"
avg = "8.44"
regist = "2021/05/14 17:49"
update = "2021/06/14 22:51"

[[entries]]
no = "16"
name = "REJUVENATION DAY"
title = "羊"
size = "1417 KB"
addr = ["http://yaritaihoudie.free.fr/bms/boxofsins/rwd.7z"]
genre = "󠀡"
impr = "27"
total = "235"
median = "9"
avg = "8.7"
regist = "2021/05/14 23:37"
update = "2023/05/26 11:58"

[[entries]]
no = "17"
name = "t-soach"
title = "slatewood"
size = "336 KB"
addr = [
    "https://www.dropbox.com/s/b0nfu2wfw8n53ea/slatewood%5Bogg%5D.7z?dl=1",
    "(LQ)",
]
genre = "house"
impr = "30"
total = "257"
median = "9"
avg = "8.56"
regist = "2021/05/15 16:37"
update = "2021/06/14 22:52"

[[entries]]
no = "18"
name = "isocosa"
title = "CYLENE STAR -STAGE 1: ZERO CITY-"
size = "905 KB"
addr = ["https://drive.google.com/file/d/1ahWuv4w032gnqYbm9jNHD7y8zzzg9Ofu/view?usp=sharing"]
genre = "FM VGM"
impr = "28"
total = "233"
median = "8.5"
avg = "8.32"
regist = "2021/05/15 21:53"
update = "2021/06/14 23:50"

[[entries]]
no = "19"
name = "lucy lake"
title = "rectangle girl"
size = "326 KB"
addr = ["https://drive.google.com/file/d/1ahzx4Z6MQnr5uk3xMOCiR-d3PfdYwmWM/view"]
genre = "shapes"
impr = "27"
total = "203"
median = "8"
avg = "7.51"
regist = "2021/05/15 22:09"
update = "2021/06/14 23:54"

[[entries]]
no = "20"
name = "Ogu"
title = "SKY JUNGLE"
size = "1443 KB"
addr = ["http://ogut.sakura.ne.jp/temp/BMS_SKY_JUNGLE.7z"]
genre = "drum'n bass"
impr = "29"
total = "226"
median = "8"
avg = "7.79"
regist = "2021/05/16 01:22"
update = "2021/06/14 22:57"

[[entries]]
no = "21"
name = "CirCy"
title = "The post (schranz remix)"
size = "491 KB"
addr = [
    "https://drive.google.com/uc?id=1-YvoF3r8nFj8xUXW4gtMOleIKk99nDaS&export=download",
    "追加差分（24 kB）",
    "https://drive.google.com/uc?id=1WtMnk9r5CduTvydxetejbduywoiqcog-&export=download",
]
genre = "schranz"
impr = "29"
total = "211"
median = "7"
avg = "7.27"
regist = "2021/05/17 00:06"
update = "2021/06/14 22:40"

[[entries]]
no = "22"
name = "The Rhythm Development and Study"
title = "The Polyrhythm Test"
size = "172 KB"
addr = ["https://mega.nz/file/3ToUSY6Z#urYObHWXSoGhsmvP6NRrHcx7RLLCmkU8KXC8C44-WdI"]
genre = "Assessment"
impr = "22"
total = "113"
median = "5"
avg = "5.13"
regist = "2021/05/17 03:56"
update = "2021/06/15 06:02"

[[entries]]
no = "23"
name = "syuuroku"
title = "NORMAL"
size = "762 KB"
addr = ["https://www.dropbox.com/s/u1pp2596nsvdcmn/%5Bsyuuroku%5DNORMAL_ogg.zip?dl=1"]
genre = "TECHNO"
impr = "28"
total = "204"
median = "7.5"
avg = "7.28"
regist = "2021/05/17 07:48"
update = "2021/06/14 23:56"

[[entries]]
no = "24"
name = "ANKAKE"
title = "Busyness Theater"
size = "397 KB"
addr = ["http://kobako-lab.main.jp/BMS/ankake_busyness_theater_ogg.rar"]
genre = "TECHNO"
impr = "30"
total = "251"
median = "8"
avg = "8.36"
regist = "2021/05/17 11:47"
update = "2021/06/14 23:38"

[[entries]]
no = "25"
name = "ALTA"
title = "Sparsity/// / /  /  /   /"
size = "456 KB"
addr = ["https://drive.google.com/uc?export=download&id=1RckIXhr63O-3pwlX9C49SnFw_J0H9JLG"]
genre = "ArtCore"
impr = "28"
total = "237"
median = "8.5"
avg = "8.46"
regist = "2021/05/17 11:54"
update = "2021/06/14 23:52"

[[entries]]
no = "26"
name = "Nakaiankow"
title = "502 Bad Gateway"
size = "545 KB"
addr = ["https://drive.google.com/file/d/1ihqQiXsC0DqB1sMEuJ_m5STZ26uM_vH2/view?usp=sharing"]
genre = "UK Garage"
impr = "23"
total = "161"
median = "7"
avg = "7"
regist = "2021/05/17 11:59"
update = "2021/06/14 22:13"
