[[entries]]
no = "1"
name = "agu"
title = "MASTERS OF MISCHIEF"
size = "1212 KB"
addr = ["https://mega.nz/file/LngwBBiT#b32Yqgd97ZrYabxgv-4PtCuHWKDcwJvgPvv13MskuHI"]
genre = "MISCHIEF FUNK"
impr = "9"
total = "31200"
median = "3800"
avg = "3466.66"
regist = "2021/07/05 18:07"
update = "2021/08/22 17:58"

[[entries]]
no = "2"
name = "ArkaanDM"
title = "Closer"
size = "40865 KB"
addr = ["http://www.dropbox.com/s/haazu8u6ezxyktg/adm_closer.rar?dl=0"]
genre = "CATCHY TECHNO"
impr = "8"
total = "26500"
median = "3000"
avg = "3312.5"
regist = "2021/07/05 19:49"
update = "2021/08/22 18:06"

[[entries]]
no = "3"
name = "nothing (that) created me"
title = "S. Machine Y2"
size = "4008 KB"
addr = ["https://drive.google.com/file/d/1M1Vs_haaIX-9Vrf4sdb25541UuVQXsuO/view?usp=sharing"]
genre = "Out of Tune"
impr = "6"
total = "11250"
median = "475"
avg = "1875"
regist = "2021/07/05 21:08"
update = "2021/08/22 18:11"

[[entries]]
no = "4"
name = "Lollipop"
title = "Praetorium"
size = "39715 KB"
addr = ["https://mega.nz/file/TTAR2YZQ#VWmgyvzXo0fpVak0rCyQ0NIqL66AafBeUz3F3U23Clk"]
genre = "Ensemble"
impr = "8"
total = "31400"
median = "4300"
avg = "3925"
regist = "2021/07/10 04:23"
update = "2021/08/22 19:01"

[[entries]]
no = "5"
name = "it was bussin"
title = "to make him moan like that 😩😪"
size = "4889 KB"
addr = ["https://cdn.discordapp.com/attachments/269267264660832257/863527398091915264/bussin.zip"]
genre = "i can tell"
impr = "8"
total = "12802"
median = "600"
avg = "1600.25"
regist = "2021/07/11 06:14"
update = "2021/08/22 19:05"

[[entries]]
no = "6"
name = "lollipop"
title = "a vast field of corn"
size = "64983 KB"
addr = ["https://mega.nz/file/eSpVQALJ#wdc6uk8JRo4eLMI9xlWolxZYqjDqBddomuiRfrEVMFQ"]
genre = "piano"
impr = "11"
total = "45200"
median = "4400"
avg = "4109.09"
regist = "2021/07/11 12:48"
update = "2021/08/22 19:08"

[[entries]]
no = "7"
name = "Gangnam Guy"
title = "The lost chungus"
size = "25000 KB"
addr = ["https://drive.google.com/file/d/10HOF_LY7dMHckSPwd1S4mOoFEDlH4UV_/view?usp=sharing"]
genre = "󠀡"
impr = "9"
total = "14799"
median = "500"
avg = "1644.33"
regist = "2021/07/17 18:28"
update = "2021/08/22 19:11"

[[entries]]
no = "8"
name = "hitsujisquare"
title = "saccharine dropper"
size = "5696 KB"
addr = [
    "https://anonymous.nekokan.dyndns.info/data/beatissimo/saccharine_dropper_v2.zip",
    "(DP☆4,9,11)",
    "https://anonymous.nekokan.dyndns.info/data/beatissimo/saccharine_dropper_add.zip",
    "(additional chart(DP HYPER ☆9), modified readme text)",
]
genre = "DRUM'N BASS"
impr = "11"
total = "46999"
median = "4500"
avg = "4272.63"
regist = "2021/07/18 01:39"
update = "2021/08/22 21:46"

[[entries]]
no = "9"
name = "menue"
title = "弥生"
size = "22491 KB"
addr = ["http://scytheleg.sakura.ne.jp/tempyou/bms/bms/men_march.rar"]
genre = "piano solo"
impr = "9"
total = "42099"
median = "4800"
avg = "4677.66"
regist = "2021/07/18 03:55"
update = "2021/08/22 19:52"

[[entries]]
no = "10"
name = "ArkaanDM"
title = "世界"
size = "12805 KB"
addr = ["https://www.dropbox.com/s/jzg6jbwubp58gck/adm_dpsekai.rar?dl=0"]
genre = "WORLD"
impr = "8"
total = "22800"
median = "2650"
avg = "2850"
regist = "2021/07/18 13:11"
update = "2021/08/22 20:04"

[[entries]]
no = "11"
name = "Alex Turell"
title = "beatissimo"
size = "55361 KB"
addr = ["https://drive.google.com/file/d/1tf0ug9t8NVkANSKNsDf-7291Mlpkyfbj/view?usp=sharing"]
genre = "ANTHEM"
impr = "7"
total = "20100"
median = "2300"
avg = "2871.42"
regist = "2021/07/18 22:58"
update = "2021/08/22 20:12"

[[entries]]
no = "12"
name = "0310"
title = "Plastic Garden"
size = "3715 KB"
addr = [
    "OGG:",
    "https://drive.google.com/file/d/1NYVp1byjTL80l1qqKDkaLOVTiPD7h8dh/view?usp=sharing",
    "WAV:",
    "https://drive.google.com/file/d/1PJJZSneYYQiv5iZ-qNZdMraCwgf8QKqB/view?usp=sharing",
]
genre = "Abstract"
impr = "11"
total = "47498"
median = "4400"
avg = "4318"
regist = "2021/07/19 00:32"
update = "2021/08/21 23:37"

[[entries]]
no = "13"
name = "Thiago de la Fontaine"
title = "watermelon did NOT give me a title"
size = "9000 KB"
addr = ["https://ufile.io/powymnpc"]
genre = "easy jazz"
impr = "10"
total = "44587"
median = "4550"
avg = "4458.7"
regist = "2021/07/19 08:25"
update = "2021/08/22 20:37"

[[entries]]
no = "14"
name = "Nakaiankow"
title = "Linghun Inferno"
size = "10557 KB"
addr = ["https://drive.google.com/file/d/1XClyGJkf7mpr15IETSupwN_73BxgdLwc/view?usp=sharing"]
genre = "Soundtrack"
impr = "8"
total = "33250"
median = "4300"
avg = "4156.25"
regist = "2021/07/19 20:14"
update = "2021/08/22 21:07"

[[entries]]
no = "15"
name = "Hyparpax"
title = "Nu Flame"
size = "54954 KB"
addr = [
    "https://drive.google.com/file/d/1l1wvoQzXXQPoGgrHOHYvs6QYKsJs0451/view?usp=sharing",
    "https://drive.google.com/file/d/125_ASUTiI7cOXjt3xDvBOxkhbIhk_19V/view?usp=sharing",
    "BGA Only",
]
genre = "HYBRID GQOM"
impr = "10"
total = "45800"
median = "4750"
avg = "4580"
regist = "2021/07/19 20:45"
update = "2021/10/24 14:45"
