[[entries]]
no = "1"
name = "cyclia"
title = "Cynthia"
size = "3114 KB"
addr = [
    "http://www99.s27.xrea.com/",
    "(BMS 作者様のページへ)",
    "http://www.geocities.jp/retrofuture_ag/cyc-cynthia_bga.zip",
    "(BGA)",
    "※BGAをダウンロードする際はIrvineなどのダウンロード支援ツールをご使用になるか、右クリックで「対象をファイルに保存」をしてください。",
]
genre = "Artcore"
impr = "7"
total = "7"
avg = "1"
regist = "2004/06/19 00:16"
update = "2004/06/30 01:31"

[[entries]]
no = "2"
name = "zit"
title = "Solanoiro"
size = "6370 KB"
addr = [
    "http://www30.tok2.com/home/lv4",
    "（作者様のサイト）",
    "http://digizliar.nobody.jp/zit_solabga.zip",
    "(BGA)",
    "右クリック保存でお願いします、もしくはＤＬ支援ソフトを。",
]
genre = "Celtrance"
impr = "7"
total = "7"
avg = "1"
regist = "2004/06/19 22:12"
update = "2004/06/30 01:16"
