[[entries]]
no = "1"
name = "Tiv"
title = "DOMPATCH BREAKING"
size = "158964 KB"
addr = ["https://drive.google.com/file/d/1smoLYuU10sk6HYv5zqxZFXWgYDT9Lpjb/view?usp=drive_link"]
genre = "GABBA"
impr = "41"
total = "34"
median = "0"
avg = "0.82"
regist = "2025/06/06 00:01"
update = "2025/06/23 23:10"

[[entries]]
no = "2"
name = "Roise feat.梵そよぎ"
title = "Ice Doll"
size = "120792 KB"
addr = ["https://drive.google.com/file/d/1wliNj7RWdpDmLq9K8NnYAV3khIh1mz21/view?usp=drive_link"]
genre = "frozen my heart"
impr = "38"
total = "33"
median = "0"
avg = "0.86"
regist = "2025/06/06 00:05"
update = "2025/06/23 22:47"

[[entries]]
no = "3"
name = "MiKaDo"
title = "東奔西走★龍虎娘"
size = "109000 KB"
addr = ["https://drive.google.com/file/d/1nYSONUZmstmhLXWlss-Hs5Kpv7QvBYuZ/view?usp=sharing"]
genre = "Orientalcore"
impr = "41"
total = "36"
median = "0"
avg = "0.87"
regist = "2025/06/06 00:20"
update = "2025/06/23 23:15"

[[entries]]
no = "4"
name = "160-320"
title = "Phreatic explosion"
size = "32000 KB"
addr = ["https://drive.google.com/file/d/1oriPp3wou9TysBXeKKi45OUzw2UvDNnZ/view?usp=drive_link"]
genre = "BLAZE CORE"
impr = "0"
total = "0"
median = "0"
avg = "0.3"
regist = "2025/06/06 01:11"
update = "2025/06/23 22:54"

[[entries]]
no = "5"
name = "Echa"
title = "Total Obliterator"
size = "3000 KB"
addr = ["https://drive.google.com/file/d/1eiAW-eZNt0Eojo1jisiH3yI00h5S2lgu/view?usp=sharing"]
genre = "+KICK-ONLY+"
impr = "38"
total = "2"
median = "0"
avg = "0.05"
regist = "2025/06/06 01:12"
update = "2025/06/23 23:18"

[[entries]]
no = "6"
name = "Nakaiankow"
title = "Edible Ethane Eagle Eligible Elastic Euphoria"
size = "55104 KB"
addr = ["https://drive.google.com/file/d/1UJymZxaeVu4AjiftIM-jgtGlZi5PV0dI/view?usp=sharing"]
genre = "Nu Fusion"
impr = "40"
total = "20"
median = "0"
avg = "0.5"
regist = "2025/06/06 02:32"
update = "2025/06/23 23:21"

[[entries]]
no = "7"
name = "DJ Eye"
title = "KOUGAI"
size = "4619 KB"
addr = ["https://9domu46i.com/BMS/DOM45_KOUGAI.zip"]
genre = "SINGELI"
impr = "44"
total = "40"
median = "0"
avg = "0.9"
regist = "2025/06/06 23:18"
update = "2025/06/23 23:25"

[[entries]]
no = "8"
name = "otenami"
title = "CAN MAKE?"
size = "17000 KB"
addr = ["https://drive.google.com/file/d/1AdFaILDUWp9LADJDjffD-5T6weS3798x/view?usp=sharing"]
genre = "speed core"
impr = "0"
total = "0"
median = "0"
avg = "0.14"
regist = "2025/06/06 23:22"
update = "2025/06/23 23:03"

[[entries]]
no = "9"
name = "CYLTIE."
title = "オーバーサンプリング・ネクストゲーマーズ！"
size = "74854 KB"
addr = [
    "https://drive.google.com/file/d/1N0wkLR0ltsznogL1bbTqeEHEoYt_870X/view?usp=sharing",
    "(WAV)",
    "https://drive.google.com/file/d/1MVAW0ceOlsDN00uBtpQA-38oWR6KQwBq/view?usp=sharing",
    "(OGG)",
]
genre = "スピードポップコア"
impr = "41"
total = "38"
median = "0"
avg = "0.92"
regist = "2025/06/07 06:06"
update = "2025/06/23 23:58"

[[entries]]
no = "10"
name = "OfficialAz3"
title = "No Concision, Full Deception"
size = "48961 KB"
addr = [
    "GDrive (main):",
    "https://drive.google.com/file/d/1B2piPKkeNJw9oHN2f9YEOqk-On8uikeo/view?usp=sharing",
    "mega.nz (Backup):",
    "https://mega.nz/file/dgxQHL7L#cYd2mP9HMfeBbX-DGhM8t5V8IZrnea_smah81M1FNOI",
    "HQ mp4 (16:9) BGA: Coming Soon(er)",
]
genre = "Flavorcore (Full Flavor Mashcore)"
impr = "37"
total = "18"
median = "0"
avg = "0.48"
regist = "2025/06/07 08:14"
update = "2025/06/23 23:50"

[[entries]]
no = "11"
name = "LSC"
title = "파라다이스 디버"
size = "58400 KB"
addr = ["https://drive.google.com/file/d/1JwavyVRYW56DxSeMitb0CNqKMq3LZh6t/view?usp=sharing"]
genre = "하이스피드 브레이크비트 하드코어"
impr = "35"
total = "8"
median = "0"
avg = "0.22"
regist = "2025/06/07 18:26"
update = "2025/06/23 23:53"

[[entries]]
no = "12"
name = "Constellation"
title = "Cortex Overdrive"
size = "72000 KB"
addr = [
    "Main:",
    "https://www.dropbox.com/scl/fi/33xv8cbyhrtwsk8017kpm/maxbeat_re-cortex_overdrive.zip?rlkey=uygf4mn5481qi9y7q0p7zxgq2&st=66r74s5v&dl=0",
    "Append:",
    "(not yet, or soon)",
]
genre = "Cyberspeed"
impr = "34"
total = "4"
median = "0"
avg = "0.11"
regist = "2025/06/07 18:50"
update = "2025/06/23 23:54"

[[entries]]
no = "13"
name = "[SIGNALER] vs. Catonieca"
title = "n u l l s t a r _"
size = "8000 KB"
addr = ["https://drive.google.com/file/d/1aomjFKqLsVkGtDqYkfiwj6YoJXBxnOJN/view?usp=sharing"]
genre = "HYPERTONE"
impr = "37"
total = "2"
median = "0"
avg = "0.05"
regist = "2025/06/08 08:29"
update = "2025/06/23 23:45"

[[entries]]
no = "14"
name = "ブレイクビーツの重要性を知らない傲慢勇者VS今まで良いように扱われていたブレイクビーツ"
title = "ブレイクビーツ！ 貴様は高速音ゲー曲には不要だ！ 俺達の曲から出ていきな！"
size = "37554 KB"
addr = ["https://drive.google.com/file/d/1P177M5b2TelU7FEgHWf_ObRV7kfUx7ZZ/view?usp=sharing"]
genre = "追放されしブレイクビーツの英雄譚～ブレイクビーツは高速音ゲー曲に不要だと追放されましたが、他の曲でたくさん使われ大活躍(以下略)"
impr = "40"
total = "39"
median = "1"
avg = "0.97"
regist = "2025/06/08 17:39"
update = "2025/06/24 00:05"

[[entries]]
no = "15"
name = "L216"
title = "Against All Prejudices"
size = "5153 KB"
addr = [
    "https://drive.google.com/file/d/1NnVIed2WH0omDdwiJ5E9ZVnnEWzUU-NU/view?usp=sharing",
    "https://1drv.ms/u/c/a4d724e36e806887/EYqidEjRcZVEs-kRJCF5iD8BOYS9-VkXCU5JtlH5LAfz8Q?e=kgpdDD",
]
genre = "I think it's Rock"
impr = "34"
total = "8"
median = "0"
avg = "0.23"
regist = "2025/06/08 18:42"
update = "2025/06/23 23:25"

[[entries]]
no = "16"
name = "BASSKNIVES"
title = "CODENAME_666"
size = "37034 KB"
addr = ["https://drive.google.com/file/d/1dxmuttu8-SUsyfKrJfnjnA9NEqpSYFde/view?usp=sharing"]
genre = "SPEEDCORE"
impr = "38"
total = "24"
median = "0"
avg = "0.63"
regist = "2025/06/08 20:40"
update = "2025/06/23 23:37"

[[entries]]
no = "17"
name = "スーパー(21)(21)ハンターズ"
title = "Hiding Tears in the Sun"
size = "29024 KB"
addr = [
    "https://www.dropbox.com/scl/fi/af462i7xo93f0brl8srg3/MAXBEAT_RE_VOLVED-Hiding-Tears-in-the-Sun.zip?rlkey=ezx1w5cctraou4w4emzkgmf0p&dl=1",
    "↓ LR2でなんかスネアの音がならねぇぞって人はこれに差し替えるとうまくいくかもしれない（フォルダに投げて上書きしよう）",
    "https://www.dropbox.com/scl/fi/8k00ff9snq73iysgvhyzo/b_HC_Snare-1_v100l8o5c.ogg?rlkey=vsnnv1t0quzfcr6f1wezyut48&dl=1",
]
genre = "JAYCORE / HYPERFLIP"
impr = "36"
total = "34"
median = "1"
avg = "0.94"
regist = "2025/06/09 01:36"
update = "2025/06/25 08:26"

[[entries]]
no = "18"
name = "Remixed by uet"
title = "ひぐらしのなく頃に(speedcore bootleg)"
size = "26833 KB"
addr = ["https://beatmaniauet.sakura.ne.jp/BMS/higurashiboot_ogg.zip"]
genre = "Speedcore"
impr = "40"
total = "34"
median = "0"
avg = "0.85"
regist = "2025/06/09 13:26"
update = "2025/06/23 23:30"

[[entries]]
no = "19"
name = "#71 Nissan Skyline GT-R V-Spec II (2002)"
title = "771"
size = "845 KB"
addr = ["https://www.mediafire.com/file/cpjdxd69qyxd8ca/771-R34-2002.zip/file"]
genre = "Sampling Horizon 5"
impr = "35"
total = "3"
median = "0"
avg = "0.08"
regist = "2025/06/09 13:57"
update = "2025/06/25 11:36"

[[entries]]
no = "20"
name = "池田哲次 feat.初音ミク"
title = "流星エンドゲイズ"
size = "38404 KB"
addr = [
    "https://drive.google.com/file/d/12Om532RgD3p4NIwgOJBm9GMtR12Qyqsc/view?usp=sharing",
    "(wav)",
    "https://drive.google.com/file/d/1-Gu47QWmhe61nr8TqMtPFOMoW6PHJ0F0/view?usp=sharing",
    "(ogg)",
    "https://drive.google.com/file/d/1UpkVeNRB-uk_DPkKqvfsOLkVFivkfjcu/view?usp=sharing",
    "(fix)",
]
genre = "10’s VOCALOID"
impr = "37"
total = "14"
median = "1"
avg = "0.37"
regist = "2025/06/09 14:30"
update = "2025/06/23 23:43"

[[entries]]
no = "21"
name = "鴉二 from 減縮研究所"
title = "Bloodhuman"
size = "21263 KB"
addr = ["https://anonymous.nekokan.dyndns.info/data/kaji_bloodhuman.zip"]
genre = "Breakcore / Splittercore"
impr = "38"
total = "23"
median = "0"
avg = "0.6"
regist = "2025/06/09 19:21"
update = "2025/06/23 23:32"

[[entries]]
no = "22"
name = "・・"
title = "続きを読む"
size = "27184 KB"
addr = ["https://drive.google.com/file/d/12hpggiZUxEgSEFEMoS51fMfnAjBCI__1/view?usp=sharing"]
genre = "_"
impr = "38"
total = "14"
median = "0"
avg = "0.36"
regist = "2025/06/09 21:05"
update = "2025/07/08 02:30"

[[entries]]
no = "23"
name = "sd5y"
title = "What's Limit?? Pt.3 ～限界の果てにあるもの～"
size = "24228 KB"
addr = ["https://www.dropbox.com/scl/fi/cgjjlif02o3w9qhn7pc50/Whats_Limit_pt3-ogg.rar?rlkey=pmjxv0pri1wnezfm1hshq1sr5&st=mrzuy8pq&dl=1"]
genre = "SPEEDCORE"
impr = "41"
total = "27"
median = "1"
avg = "0.65"
regist = "2025/06/09 23:28"
update = "2025/06/25 10:37"

[[entries]]
no = "24"
name = "かたぎり"
title = "CAT ROTATION"
size = "44825 KB"
addr = ["https://drive.google.com/file/d/1b3RK2cUCrY2DZ7N_qUCS8y7jE_CBfR77/view?usp=sharing"]
genre = "BREAKCORE"
impr = "49"
total = "48"
median = "1"
avg = "0.97"
regist = "2025/06/09 23:38"
update = "2025/06/23 23:27"

[[entries]]
no = "25"
name = "DJ Saw-Low"
title = "tsuMo (8000All)"
size = "242635 KB"
addr = ["https://scytheleg.sakura.ne.jp/tempyou/bms/bms/djsl_tsumo.rar"]
genre = "IPPATSU HARDCORE"
impr = "36"
total = "34"
median = "1"
avg = "0.94"
regist = "2025/06/09 23:50"
update = "2025/06/23 23:59"

[[entries]]
no = "26"
name = "Emulation System aborted in DYSTOPIA (a.k.a. 4G)"
title = "Rumble Dance"
size = "12558 KB"
addr = ["https://kids-philosophy.candypop.jp/archives/rumbledance.rar"]
genre = "ELECTRO SHAABI / SPED UP"
impr = "38"
total = "34"
median = "1"
avg = "0.89"
regist = "2025/06/09 23:53"
update = "2025/08/01 19:55"

[[entries]]
no = "27"
name = "LU vs. ARMYTOM"
title = "Luxembourg Zwee"
size = "378823 KB"
addr = [
    "・WAV版+MP4",
    "https://drive.google.com/file/d/152i-TxmYzGYpPzNGzkvSi0g7Z-6tgnwa/view?usp=drive_link",
    "ミラー:",
    "https://drive.google.com/file/d/1QLTEXHkorQTLOWtiH_BXC3MJ-X3WxALB/view?usp=sharing",
    "(※ミラー一つ削除しました)",
    "・OGG版",
    "準備中",
]
genre = "NIGHTFUNK"
impr = "38"
total = "19"
median = "1"
avg = "0.5"
regist = "2025/06/09 23:57"
update = "2025/06/23 23:38"

[[entries]]
no = "28"
name = "福建高速音楽研究学会（猫龍+DJ NORMAL1ZER+DJ Momo）"
title = "CUNNY TRIO"
size = "255255 KB"
addr = [
    "wav版：",
    "https://drive.google.com/file/d/15LgOx09bAg2DKPPXJrYBmFPKctWoHFny/view?usp=drive_link",
    "https://1drv.ms/u/c/5b74e59b25964053/EcSrQzBLFnVNgB3gpolYQ0QBLBx53IMBobicQZEpiPg2Zw?e=bd4FFD",
    "ogg版：",
    "https://drive.google.com/file/d/1i487huFKeiCd9nVGYexLTffrovONc7dZ/view?usp=drive_link",
    "https://1drv.ms/u/c/5b74e59b25964053/EfO6KpsRnPhAgeb5KynJcyYBWkWlVbhaf2wY5fRWMjxS3g?e=vILeL5",
]
genre = "KAWAii 0xFF MIXTURE"
impr = "40"
total = "36"
median = "1"
avg = "0.9"
regist = "2025/06/09 23:57"
update = "2025/06/23 23:58"
