[[entries]]
no = "1"
name = "2004/05/02"
title = "Quay"
size = "4795 KB"
addr = [
    "http://www.ismusic.ne.jp/ruz/",
    "file:///D:/nothing.sh/dee_news/2weekir/11_2WR_n5.zip",
]
genre = "Phase:11 1P5key激(Cruel限定)"
impr = "0"
total = "0"
avg = "0"
regist = "2004/06/06 22:50"
update = "2004/06/06 22:50"

[[entries]]
no = "2"
name = "2004/05/09"
title = "from Session Stream 2"
size = "0 KB"
addr = [
    "[コースリスト]",
    "http://nothing.sh/~manbow/dee_news/2weekir/course.html#011",
    "[ランキング]",
    "http://bms.nothing.sh/bmsid?action=getcourseranking&courseid=EE995498-00DD5908",
]
genre = "Phase:12 1P7keyLNCOURSE"
impr = "0"
total = "0"
avg = "0"
regist = "2004/06/06 23:03"
update = "2004/06/06 23:03"

[[entries]]
no = "3"
name = "2004/05/09"
title = "EX+Rebirth"
size = "0 KB"
addr = [
    "[コースリスト]",
    "http://nothing.sh/~manbow/dee_news/2weekir/course.html#011",
    "[ランキング]",
]
genre = "Phase:12 1P7keyLNCOURSE"
impr = "0"
total = "0"
avg = "0"
regist = "2004/06/06 23:13"
update = "2004/06/06 23:13"

[[entries]]
no = "4"
name = "2004/06/06"
title = "Spring Phase"
size = "0 KB"
addr = [
    "[コースリスト]",
    "http://nothing.sh/~manbow/dee_news/2weekir/course.html#012",
    "[ランキング]",
    "http://bms.nothing.sh/bmsid?action=getcourseranking&courseid=6CEA0064-63B738E4",
]
genre = "Phase:13 7KeyCOURSE"
impr = "0"
total = "0"
avg = "0"
regist = "2004/06/07 00:39"
update = "2004/06/28 00:49"

[[entries]]
no = "5"
name = "2004/06/06"
title = "☆ さくらなみきのかぜ ☆"
size = "8115 KB"
addr = [
    "[ダウンロード先]",
    "http://ww2.ctt.ne.jp/~nekomimi/",
    "[2WR用譜面]",
    "http://nothing.sh/~manbow/dee_news/2weekir/13_2WR_nekoko14_9key.zip",
    "[ランキング]",
    "http://bms.nothing.sh/bmsid?action=getbmsranking&bmsid=208807",
    "(NORMAL)",
    "http://bms.nothing.sh/bmsid?action=getbmsranking&bmsid=206779",
    "(HYPER)",
]
genre = "Phase:13 9Key"
impr = "0"
total = "0"
avg = "0"
regist = "2004/06/07 01:21"
update = "2004/06/28 00:44"

[[entries]]
no = "6"
name = "2004/06/28"
title = "FEVER [(((^ ^))) mix]"
size = "610 KB"
addr = [
    "[ダウンロード先]",
    "http://www.ismusic.ne.jp/ruz/",
    "[差分譜面]",
    "http://nothing.sh/~manbow/dee_news/2weekir/14_2WR_fever.zip",
    "(5key・7key同封)",
    "[ランキング]",
    "http://bms.nothing.sh/bmsid?action=getbmsranking&bmsid=214413",
    "(5key)",
    "http://bms.nothing.sh/bmsid?action=getbmsranking&bmsid=214414",
    "(7key)",
]
genre = "Phase:14 5key・7key"
impr = "0"
total = "0"
avg = "0"
regist = "2004/06/28 01:09"
update = "2004/06/28 01:09"

[[entries]]
no = "7"
name = "2004/06/28"
title = "Aurora Fleedom"
size = "5720 KB"
addr = [
    "[ダウンロード先]",
    "http://www16.big.or.jp/~shockc/",
    "[差分譜面]",
    "http://nothing.sh/~manbow/dee_news/2weekir/14_2WR_aurora.zip",
    "[ランキング]",
    "http://bms.nothing.sh/bmsid?action=getbmsranking&bmsid=214415",
    "(7keyNORMAL)",
    "http://bms.nothing.sh/bmsid?action=getbmsranking&bmsid=214416",
    "(7keyAnother)",
]
genre = "Phase:14 7key"
impr = "0"
total = "0"
avg = "0"
regist = "2004/06/28 01:22"
update = "2004/06/28 01:22"
