[[entries]]
no = "1"
name = "メンマ"
title = "メンマ"
size = "4882 KB"
addr = ["https://drive.google.com/file/d/1LyVR5oFk9pwp7mP_6zrX40JPitOU4-cf/view?usp=sharing"]
genre = "メンマ"
impr = "19"
total = "10"
median = "0"
avg = "0.52"
regist = "2026/02/01 00:02"
update = "2026/02/22 22:10"

[[entries]]
no = "2"
name = "ダン☆ダン☆ダン☆シャーン♪"
title = "あ！スーモ！"
size = "378 KB"
addr = ["https://drive.google.com/file/d/1WHLIRXsaVHWdn7Hr_IAuW3y4pBDRvxJh/view?usp=sharing"]
genre = "家探し"
impr = "17"
total = "5"
median = "0"
avg = "0.29"
regist = "2026/02/01 00:03"
update = "2026/02/22 12:20"

[[entries]]
no = "3"
name = "UOL Sound Team"
title = "ドッグラン"
size = "38293 KB"
addr = ["https://drive.google.com/file/d/16JcEbdh6UQQqK5Exu_QWfHnpQTWeka03/view?usp=drive_link"]
genre = "INU"
impr = "19"
total = "14"
median = "0"
avg = "0.73"
regist = "2026/02/01 00:06"
update = "2026/02/22 22:11"

[[entries]]
no = "4"
name = "Y〇shi"
title = "Y〇shi"
size = "240 KB"
addr = ["https://anonymous.nekokan.dyndns.info/data/_Y%E3%80%87shi.zip"]
genre = "Y〇shi"
impr = "19"
total = "9"
median = "0"
avg = "0.47"
regist = "2026/02/01 00:16"
update = "2026/02/22 22:12"

[[entries]]
no = "5"
name = "なんなのあんこう"
title = "宵から明け迄 (FOON Edit)"
size = "4000000 KB"
addr = ["https://drive.google.com/file/d/10beOy_F4vEvP0wAa1mTj8kuNqnn_5rgK/view?usp=sharing"]
genre = "acoustic"
impr = "18"
total = "7"
median = "0"
avg = "0.38"
regist = "2026/02/01 05:25"
update = "2026/02/22 22:13"

[[entries]]
no = "6"
name = "なかむらけんた"
title = "乙女の祈り"
size = "18400 KB"
addr = ["https://drive.google.com/file/d/1TWLTPnbOfPkpd-_NpfdtdkUJ5Qtbvnai/view?usp=sharing"]
genre = "○○が好きすぎる小学生"
impr = "17"
total = "12"
median = "0"
avg = "0.7"
regist = "2026/02/01 06:43"
update = "2026/02/22 12:27"

[[entries]]
no = "7"
name = "MUR"
title = "野獣先輩の金玉消失"
size = "24200 KB"
addr = ["https://drive.google.com/file/d/1BNniJPotv1Worwk4m5HeLpItTGg6fk-U/view?usp=sharing"]
genre = "BB先輩劇場"
impr = "19"
total = "12"
median = "0"
avg = "0.63"
regist = "2026/02/01 15:13"
update = "2026/02/22 23:42"

[[entries]]
no = "8"
name = "またしてもギャグセンスのない人"
title = "FOONのネタが思いつかないよ～・続"
size = "5973 KB"
addr = ["https://drive.google.com/file/d/1BOVsFU4xTeWQ604re-13oP28n9593dye/view?usp=drive_link"]
genre = "黒歴史は繰り返す"
impr = "18"
total = "13"
median = "0"
avg = "0.72"
regist = "2026/02/02 18:50"
update = "2026/02/22 22:13"

[[entries]]
no = "9"
name = "にょろも"
title = "1月30日の金価格暴落に巻きこまれました"
size = "4900 KB"
addr = ["https://drive.google.com/file/d/1WQSGABKjk-OWuQATvFFo_Y3yB2w6hEgG/view"]
genre = "個人的なご報告です"
impr = "18"
total = "12"
median = "0"
avg = "0.66"
regist = "2026/02/03 02:00"
update = "2026/02/22 12:34"

[[entries]]
no = "10"
name = "Composer: 不詳 ; Vocal: 黄 仲王行"
title = "第三套 全国中学生広播体操 放飛理想"
size = "85504 KB"
addr = ["https://wwbfy.lanzn.com/inDbm3hnjo1i"]
genre = "setting-up exercise soundtrack"
impr = "20"
total = "14"
median = "1"
avg = "0.7"
regist = "2026/02/03 14:23"
update = "2026/02/22 23:44"

[[entries]]
no = "11"
name = "bruh"
title = "wow the cat is very cute"
size = "2244 KB"
addr = ["https://drive.google.com/file/d/1ADJQC0AW51_E6oUhPv0zoKEvu0qnA71W/view"]
genre = "awww"
impr = "19"
total = "17"
median = "1"
avg = "0.89"
regist = "2026/02/03 18:20"
update = "2026/02/23 00:04"

[[entries]]
no = "12"
name = "LiJian Lin"
title = "Mirita"
size = "9590 KB"
addr = ["https://drive.google.com/file/d/1DUFvtw5fmwsoZ9AjaKsM-2SJBet5eFpO/view?usp=sharing"]
genre = "Traditional psy Rock"
impr = "17"
total = "12"
median = "0"
avg = "0.7"
regist = "2026/02/03 19:16"
update = "2026/02/22 12:42"

[[entries]]
no = "13"
name = "狂人C vs. 狂人C with 狂人C/ Lyric: 狂人C/ BMS: 狂人C respect for 狂人C"
title = "アーマンレコーディッドヒズボイスアズザーサーンプル。ジスイズウォットハペンドターヒズワーク (feat. 狂人C)"
size = "22900 KB"
addr = [
    "オージージー バージョン(22900kb):",
    "https://www.dropbox.com/scl/fi/vetc3whp0mktkmikl5y4q/bofoon21-a_man_who_recorded_his_voice.zip?rlkey=imtx5zrummg45mnj98mg8kx7j&st=q1n5u42h&dl=0",
]
genre = "ニューロファートブレイクコア"
impr = "20"
total = "12"
median = "0"
avg = "0.6"
regist = "2026/02/04 01:56"
update = "2026/02/22 23:45"

[[entries]]
no = "14"
name = "れおん"
title = "ワープスター（SDX）"
size = "1333 KB"
addr = ["https://86iro716.pupu.jp/bms/warpstar_sdx.zip"]
genre = "SOUND EFFECT"
impr = "18"
total = "9"
median = "0"
avg = "0.5"
regist = "2026/02/04 18:47"
update = "2026/02/22 22:15"

[[entries]]
no = "15"
name = "Disaster of Piano"
title = "Piano?"
size = "359 KB"
addr = ["https://anonymous.nekokan.dyndns.info/data/Piano_fixed.rar"]
genre = "Noise"
impr = "15"
total = "5"
median = "0"
avg = "0.33"
regist = "2026/02/04 22:33"
update = "2026/02/23 01:12"

[[entries]]
no = "16"
name = "Chickuya (VeryDrunkAndNoSleep)"
title = "Be ChickenOnTheTree Source"
size = "75000 KB"
addr = ["https://drive.google.com/file/d/1zp7kcqC0s3Zu3GJU_DOEnWiFZGjW_CzL/view?usp=sharing"]
genre = "CHICKEN"
impr = "16"
total = "15"
median = "1"
avg = "0.93"
regist = "2026/02/05 04:26"
update = "2026/02/22 12:49"

[[entries]]
no = "17"
name = "GbbG制作委員会"
title = "GarbagebakinG 2023 - BOFOON:NT COMPILATION ALBUM - 全曲視聴"
size = "12237 KB"
addr = [
    "2026.2.6 BGの誤字を修正する",
    "https://www.mediafire.com/file/7lg0ikhxp4z5whh/gbbg2023%255Bogg%255D.zip/file",
]
genre = "save the time"
impr = "17"
total = "16"
median = "1"
avg = "0.94"
regist = "2026/02/06 01:16"
update = "2026/02/22 22:16"

[[entries]]
no = "18"
name = "関2爺"
title = "The Song of G2YE"
size = "14016 KB"
addr = ["https://drive.google.com/file/d/1DOjRpomyafqVX5oNjB5aZVek_cKs6a04/view?usp=sharing"]
genre = "G2YE - GO 2 YOUR EVOLUTION -"
impr = "14"
total = "8"
median = "0"
avg = "0.57"
regist = "2026/02/06 03:43"
update = "2026/02/22 12:53"

[[entries]]
no = "19"
name = "ティム・フォリン"
title = "ファミコンの階段"
size = "1270 KB"
addr = ["https://97.gigafile.nu/0308-cbe23dcb56e443198cb3a9de5e574024b"]
genre = "「ファミコン最高峰のBGM」とかで検索すると大概出てくる曲"
impr = "14"
total = "9"
median = "0"
avg = "0.64"
regist = "2026/02/06 21:43"
update = "2026/02/22 12:55"

[[entries]]
no = "20"
name = "SpadeK"
title = "アメちゃんなぶら急上昇ぅ！"
size = "25300 KB"
addr = ["https://drive.google.com/file/d/1mach-Ei7Y6RaX-gKAEWlEnc021_cTNBM/view?usp=sharing"]
genre = "Lo-Fi + Artcore"
impr = "15"
total = "6"
median = "0"
avg = "0.4"
regist = "2026/02/06 22:05"
update = "2026/02/22 22:20"

[[entries]]
no = "21"
name = "DIRECTED BY 狂人C"
title = "幻想郷茶番！幻想郷全体に春を告げようとしたリリーホワイト"
size = "32800 KB"
addr = ["https://www.dropbox.com/scl/fi/ona0n7iu9cvoprq7ukzcn/bofoon21-spring_is_coming.zip?rlkey=vev56bzlypopym8op1joj9w65&st=2kxtlb05&dl=0"]
genre = "異変"
impr = "14"
total = "6"
median = "0"
avg = "0.42"
regist = "2026/02/06 22:31"
update = "2026/02/22 12:57"

[[entries]]
no = "22"
name = "大市唱(赵磊)"
title = "男の娘の腰振り練習"
size = "1630 KB"
addr = ["https://www.mediafire.com/file/v35v9puv8d03lsx/%25E7%2594%25B7%25E3%2581%25AE%25E5%25A8%2598%25E3%2581%25AE%25E8%2585%25B0%25E6%258C%25AF%25E3%2582%258A%25E7%25B7%25B4%25E7%25BF%2592.rar/file"]
genre = "音楽がとても素晴らしい！！"
impr = "16"
total = "2"
median = "0"
avg = "0.12"
regist = "2026/02/06 22:38"
update = "2026/02/22 12:58"

[[entries]]
no = "23"
name = "."
title = "選曲BGMを一時停止します"
size = "70 KB"
addr = ["https://www.mediafire.com/file/5p9hxzerq1wy5kd/StopTheSelectBGM_BMS_ogg.zip/file"]
genre = "AFKしたいけど音量調整するのが面倒な場合"
impr = "15"
total = "6"
median = "0"
avg = "0.4"
regist = "2026/02/06 23:56"
update = "2026/02/22 22:21"

[[entries]]
no = "24"
name = "DJ 天子帝王"
title = "心の壁 (天子帝王 Remix)"
size = "52605 KB"
addr = ["https://drive.google.com/file/d/1Eyt_UE96HH61KTqHOtG2PzmF7yA_Jsvf/view?usp=drive_link"]
genre = "Too High DJ"
impr = "15"
total = "9"
median = "0"
avg = "0.6"
regist = "2026/02/07 04:16"
update = "2026/02/22 13:00"

[[entries]]
no = "25"
name = "FOONKIN"
title = "【新人Youtuber】激辛焼きそば食べてみた【初投稿８本目】"
size = "78263 KB"
addr = ["https://drive.google.com/file/d/1r5TeOkuwXEZ8MmejF2bYmmrfKim5nF4a/view"]
genre = "高評価チャンネル登録"
impr = "16"
total = "8"
median = "0"
avg = "0.5"
regist = "2026/02/07 18:00"
update = "2026/02/22 22:23"

[[entries]]
no = "26"
name = "BMS: ."
title = "bababooey"
size = "3379 KB"
addr = ["https://www.mediafire.com/file/qdvaz5gqnjzvexn/bababooeyMS_ogg.zip/file"]
genre = "meme"
impr = "15"
total = "13"
median = "0"
avg = "0.86"
regist = "2026/02/07 22:29"
update = "2026/02/22 22:26"

[[entries]]
no = "27"
name = "アンドロイ・メカコスキー feat.重音テト"
title = "ボーイッシュ幼馴染は純愛であれ高校"
size = "9885 KB"
addr = ["https://drive.google.com/file/d/1xlFQuHY6JSYOkKqgdpKnYJJmXz_Utw5a/view"]
genre = "校歌"
impr = "15"
total = "7"
median = "0"
avg = "0.46"
regist = "2026/02/08 12:41"
update = "2026/02/22 13:05"

[[entries]]
no = "28"
name = "凄い椅子"
title = "ゴイゴ椅子"
size = "23300 KB"
addr = ["https://drive.google.com/file/d/1s3Dcyqlybndbm1P9jv0nu_Tsgxk9hVLD/view?usp=sharing"]
genre = "chair凄い"
impr = "16"
total = "11"
median = "0"
avg = "0.68"
regist = "2026/02/08 15:59"
update = "2026/02/22 22:26"

[[entries]]
no = "29"
name = "最強feat.SAIKYOUwith最強交通"
title = "最強の歌"
size = "13600 KB"
addr = ["https://drive.google.com/file/d/1xERuv2MJXssRil2koHIxXu-n2iON0THV/view?usp=sharing"]
genre = "最強"
impr = "15"
total = "7"
median = "0"
avg = "0.46"
regist = "2026/02/08 17:51"
update = "2026/02/22 13:07"

[[entries]]
no = "30"
name = "M-kani"
title = "mk extra6 (強化版)"
size = "531 KB"
addr = ["https://drive.google.com/uc?id=1ZJ8xO3k9w7YRiMg4AqfC8JAsqatnvAo-&export=download"]
genre = "techno"
impr = "14"
total = "2"
median = "0"
avg = "0.14"
regist = "2026/02/08 20:28"
update = "2026/02/22 13:08"

[[entries]]
no = "31"
name = "HeartF"
title = "【BOF22】魚の口"
size = "73092 KB"
addr = [
    "wav+mp4:",
    "https://drive.google.com/file/d/1qRlXt5sKrx7oUh2aj5CsN1CKjrzEysFf/view?usp=sharing",
    "ogg+wmv:",
    "https://drive.google.com/file/d/1PPjWtfTUANcAeuNIhC6HVcnbOjaBdRl3/view?usp=sharing",
]
genre = "Huture Buns"
impr = "15"
total = "15"
median = "0"
avg = "1"
regist = "2026/02/08 20:46"
update = "2026/02/22 22:30"

[[entries]]
no = "32"
name = "2019.12.21"
title = "少し調子の悪いWiiを起動する"
size = "337 KB"
addr = ["https://drive.google.com/uc?export=download&id=1z6kxYnAUxDgiL4nFiPHUWPe6-PGar8Fb"]
genre = "_"
impr = "16"
total = "5"
median = "0"
avg = "0.31"
regist = "2026/02/08 21:44"
update = "2026/02/22 22:32"

[[entries]]
no = "33"
name = "kdcysth"
title = "2025musicsharing1"
size = "4940 KB"
addr = ["https://drive.google.com/file/d/1ABUP5zPULE4JrIS5_eYwSZ-QXOm3Zlcv/view?usp=sharing"]
genre = "wochuizhiwadebushen"
impr = "14"
total = "1"
median = "0"
avg = "0.07"
regist = "2026/02/08 22:46"
update = "2026/02/22 13:11"

[[entries]]
no = "34"
name = "xeninsecttcesninex"
title = "You were reborn, on the night before the deadline for submitting entries to the G2R21 competition."
size = "1945 KB"
addr = ["https://wwapn.lanzoul.com/iZfgS3i36b2j"]
genre = "zheshishazi"
impr = "10"
total = "2"
median = "0"
avg = "0.2"
regist = "2026/02/08 22:49"
update = "2026/02/22 13:12"

[[entries]]
no = "35"
name = "Composer: 不詳 (cover: DJ合浦仔阿恭/mov: 合浦微視)"
title = "捏二捏三賣捏鵝"
size = "54900 KB"
addr = ["https://drive.google.com/file/d/1H9W8lZD-n17JEY-Vmybnc_J8dyzuKDEc/view?usp=sharing"]
genre = "民謡"
impr = "15"
total = "12"
median = "1"
avg = "0.8"
regist = "2026/02/08 23:13"
update = "2026/02/22 13:13"

[[entries]]
no = "36"
name = "NASA"
title = "近所のビルのドア"
size = "92800 KB"
addr = ["https://anonymous.nekokan.dyndns.info/data/door.zip"]
genre = "調子がやや悪い"
impr = "18"
total = "15"
median = "0"
avg = "0.83"
regist = "2026/02/08 23:22"
update = "2026/02/22 23:18"

[[entries]]
no = "37"
name = "二游吃"
title = "424242424242424242424242"
size = "115343 KB"
addr = ["https://wwapn.lanzoul.com/is8w83i3a17i"]
genre = "118"
impr = "17"
total = "1"
median = "0"
avg = "0.05"
regist = "2026/02/08 23:25"
update = "2026/02/22 13:17"

[[entries]]
no = "38"
name = "nekomimi_STRaw  / BGA: LLRK"
title = "なさなさ★デストロイヤーメイド"
size = "70500 KB"
addr = [
    "Ogg版：",
    "https://nekomimi-straw.com/BMS/",
    "[nekomimi_STRaw]7373_destroyer_maid_ogg.zip",
    "Wav版：",
    "https://nekomimi-straw.com/BMS/",
    "[nekomimi_STRaw]7373_destroyer_maid_wav.zip",
]
genre = "HYPER NASA SONG"
impr = "15"
total = "13"
median = "0"
avg = "0.86"
regist = "2026/02/08 23:48"
update = "2026/02/22 22:33"

[[entries]]
no = "39"
name = "Phleguratone"
title = "100%DENIM-pattern!!"
size = "4300 KB"
addr = [
    "Wav→",
    "https://drive.google.com/file/d/1TpYkSVLFPI9HeKgy5aURGk90MP2W6J0k/view?usp=sharing",
    "Ogg→",
    "https://drive.google.com/file/d/1yYQbMO_umByPks4-ByAWF-nN_o8S8PqW/view?usp=sharing",
    "（26/2/9 1:50修正）Ogg版のみファイル名の定義ミスで「syd_hat.ogg」が鳴らない不具合がありました。左記の日付以前でDLされた方は再DLしていただくか、「syd hat.ogg」を「syd_hat.ogg」にリネームをお願いします。",
]
genre = "semi-Chance Operation"
impr = "15"
total = "14"
median = "1"
avg = "0.93"
regist = "2026/02/08 23:53"
update = "2026/03/23 20:57"

[[entries]]
no = "40"
name = "Kurast703 remixed by Kurast7〇3"
title = "Sorry_ (But it is a More Realistic Remix)"
size = "24064 KB"
addr = ["https://www.mediafire.com/file/2a6isvw4cba2h2v/Sorry_ButItIsAMoreRealisticRemix_BMS_ogg.zip/file"]
genre = "黒歴史techstyle"
impr = "15"
total = "10"
median = "1"
avg = "0.66"
regist = "2026/02/08 23:57"
update = "2026/02/22 22:48"
