[[entries]]
no = "1"
name = "zit"
title = "Dear sexxx DanCer"
size = "4700 KB"
addr = [
    "http://www.geocities.jp/zit_srts/",
    "(BGA)",
    "BMS&原作BGA",
    "http://www2u.biglobe.ne.jp/~cranky/index.htm",
    "(cranky氏HP 5keyよりDLをお願いします)",
]
genre = "NEWYORK"
impr = "16"
total = "16"
avg = "1"
regist = "2004/08/15 04:39"
update = "2004/08/31 21:06"

[[entries]]
no = "2"
name = "cyclia"
title = "P8107 -further insanity-"
size = "12489 KB"
addr = [
    "http://www.ismusic.ne.jp/naotyu/data/cyc-bga_p8107HQ.zip",
    "(BGA)",
    "http://www107.sakura.ne.jp/~onoken/",
    "(原作BMS BGA)",
]
genre = "drum'n core"
impr = "18"
total = "18"
avg = "1"
regist = "2004/08/16 21:53"
update = "2004/08/31 21:19"

[[entries]]
no = "3"
name = "makein/cranky"
title = 'For Your Love "overdub mix"'
size = "1610 KB"
addr = [
    "BGA",
    "http://makein.hp.infoseek.co.jp/box/mkin_fyl.lzh",
    "BMS&原作BGA",
    "http://www2u.biglobe.ne.jp/~cranky/index.htm",
    "(cranky氏HP 5keyよりDLをお願いします)",
]
genre = "TECHNO HOUSE"
impr = "11"
total = "11"
avg = "1"
regist = "2004/08/19 10:45"
update = "2004/08/31 21:29"

[[entries]]
no = "4"
name = "retu"
title = "on the sequence #3"
size = "5210 KB"
addr = ["http://www.pixellife.x0.to/bms/retu-ots3bga.zip"]
genre = "d'n'b"
impr = "13"
total = "13"
avg = "1"
regist = "2004/08/22 22:56"
update = "2006/04/13 13:38"

[[entries]]
no = "5"
name = "逆凪"
title = "FELYS"
size = "5000 KB"
addr = [
    "http://namebf.s60.xrea.com/skng_felys.zip",
    "ONOKENさん",
    "http://www107.sakura.ne.jp/~onoken/",
]
genre = "drum'n bass"
impr = "9"
total = "9"
avg = "1"
regist = "2004/08/22 23:35"
update = "2004/08/31 22:30"
