[[entries]]
no = "1"
name = "268 (pms268sugarplum)"
title = "Is your life happy?"
size = "14 KB"
addr = [
    "http://www.geocities.co.jp/Playtown/9637/pms268happyeuro.zip",
    "http://bin.dot908.net/9b/",
    "(キューキービーツ会場)",
]
genre = "ウラ・ユーロビート"
impr = "1"
total = "1"
avg = "1"
regist = "2004/09/13 00:12"
update = "2004/09/26 21:43"

[[entries]]
no = "2"
name = "268 (pms268sugarplum)"
title = "EVERGREEN"
size = "540 KB"
addr = [
    "http://www.geocities.co.jp/Playtown/9637/pms268evergreen.zip",
    "http://www2u.biglobe.ne.jp/~cranky/",
    "(元BMS配布先)",
]
genre = "トランス"
impr = "1"
total = "1"
avg = "1"
regist = "2004/09/13 23:59"
update = "2004/09/27 00:08"

[[entries]]
no = "3"
name = "268 (pms268sugarplum)"
title = "POST"
size = "24 KB"
addr = [
    "http://www.geocities.co.jp/Playtown/9637/pms268post.zip",
    "http://www30.cds.ne.jp/~slk_ymd/",
    "(元BMS配布先)",
]
genre = "エレクトロポップ?"
impr = "1"
total = "1"
avg = "1"
regist = "2004/09/15 00:00"
update = "2004/09/28 20:28"

[[entries]]
no = "4"
name = "bs1"
title = "lastdance"
size = "9 KB"
addr = ["http://niigata.cool.ne.jp/bs1sabun/lastdance-pms.zip"]
genre = "フュージョン"
impr = "1"
total = "1"
avg = "1"
regist = "2004/09/16 00:14"
update = "2004/09/28 22:27"

[[entries]]
no = "5"
name = "D11(激辛党)"
title = "ヤマジェット☆コースターガール"
size = "14 KB"
addr = ["http://onohoke.hp.infoseek.co.jp/ura9k.html"]
genre = "サイバーロック☆"
impr = "1"
total = "1"
avg = "1"
regist = "2004/09/21 22:31"
update = "2004/09/26 15:26"

[[entries]]
no = "6"
name = "珊瑚"
title = "in the starlight"
size = "24 KB"
addr = [
    "http://www.geocities.jp/p_vizya_q/starlight_9.lzh",
    "http://www.ucatv.ne.jp/~ookami/kemoryu.htm",
    "(元bms配布元)",
]
genre = "ハイパーユーロビート"
impr = "1"
total = "1"
avg = "1"
regist = "2004/09/25 01:30"
update = "2004/09/28 23:33"

[[entries]]
no = "7"
name = "268 (pms268sugarplum)"
title = "恋のしょほうせん(医療ミstyle)"
size = "24 KB"
addr = [
    "http://www.geocities.co.jp/Playtown/9637/pms268oisyasan.zip",
    "http://www30.cds.ne.jp/~slk_ymd/",
    "(原作bms配布元)",
]
genre = "アキバポップ"
impr = "1"
total = "1"
avg = "1"
regist = "2004/09/25 23:22"
update = "2004/10/01 00:38"

[[entries]]
no = "8"
name = "珊瑚"
title = "on the sequence #3"
size = "18 KB"
addr = [
    "http://www.geocities.jp/p_vizya_q/onthesequence3_9.lzh",
    "http://commonsense.web.infoseek.co.jp/",
    "(元bms配布元)",
]
genre = "ドラムンベース"
impr = "1"
total = "1"
avg = "1"
regist = "2004/09/26 23:36"
update = "2004/10/01 23:02"

[[entries]]
no = "9"
name = "bs1"
title = "猿が猿と暮らす猿の村"
size = "12 KB"
addr = ["http://niigata.cool.ne.jp/bs1sabun/eleape-pms.zip"]
genre = "トライバルテクノ"
impr = "1"
total = "1"
avg = "1"
regist = "2004/09/27 21:22"
update = "2004/10/02 20:35"

[[entries]]
no = "10"
name = "Spelunker"
title = "シェルターキッズ"
size = "28 KB"
addr = ["http://www30.cds.ne.jp/~slk_ymd/muzik/shelter9.rar"]
genre = "デジ寓話"
impr = "1"
total = "1"
avg = "1"
regist = "2004/10/01 20:19"
update = "2004/10/02 22:40"

[[entries]]
no = "11"
name = "TML"
title = "ラベンダーの咲く庭～DIGITAL FLOWER JUNGLE～"
size = "8 KB"
addr = [
    "http://bms.s26.xrea.com/sarashi/img/1792.zip",
    "http://hw001.gate01.com/loki/",
    "(原曲)",
]
genre = "ジャングル"
impr = "2"
total = "2"
avg = "1"
regist = "2004/10/01 22:54"
update = "2004/10/03 18:45"

[[entries]]
no = "12"
name = "TML"
title = "GRADIUSIC PARTY -SS2 Special-(PMSedition)"
size = "42 KB"
addr = [
    "http://bms.s26.xrea.com/sarashi/img/1793.zip",
    "http://manbow.org/",
    "(BMS版)",
]
genre = "グラディウスメドレー"
impr = "1"
total = "1"
avg = "1"
regist = "2004/10/01 23:32"
update = "2004/10/03 18:54"

[[entries]]
no = "13"
name = "268 (pms268sugarplum)"
title = "strawberry music"
size = "20 KB"
addr = [
    "http://www.geocities.co.jp/Playtown/9637/pms268strawberry.zip",
    "http://www.yamajet.com/",
    "(原作配布元)",
]
genre = "ボッサGO GO"
impr = "1"
total = "1"
avg = "1"
regist = "2004/10/01 23:44"
update = "2004/10/03 19:15"
