[[entries]]
no = "1"
name = "赤蓮舞踊師嵐堂(RANDO:)"
title = "人間の盾"
size = "1108 KB"
addr = ["http://isweb39.infoseek.co.jp/art/rnderv/rnd_hs.zip"]
genre = "-----"
impr = "18"
total = "14"
avg = "0.77"
regist = "20020427"
update = "20020511"

[[entries]]
no = "2"
name = "コウ"
title = "outboard"
size = "770 KB"
addr = ["http://www.geocities.co.jp/MusicStar-Bass/1570/outboard.lzh"]
genre = "-----"
impr = "13"
total = "11"
avg = "0.84"
regist = "20020427"
update = "20020511"

[[entries]]
no = "3"
name = "zinya"
title = "contingency"
size = "563 KB"
addr = ["http://isweb3.infoseek.co.jp/play/zinya/event/noise/"]
genre = "-----"
impr = "6"
total = "6"
avg = "1"
regist = "20020428"
update = "20020508"

[[entries]]
no = "4"
name = "K3(s.s.)"
title = "blaze ocean"
size = "1147 KB"
addr = ["http://www2.ttcn.ne.jp/~y-o/bms.htm"]
genre = "-----"
impr = "2"
total = "0"
avg = "0"
regist = "20020428"
update = "20020508"

[[entries]]
no = "5"
name = "LUNE"
title = "壊れちゃうよぉ・・・"
size = "1187 KB"
addr = ["http://rs.myvnc.com/~lune/date/koware.rar"]
genre = "-----"
impr = "5"
total = "3"
avg = "0.6"
regist = "20020428"
update = "20020508"

[[entries]]
no = "6"
name = "shala"
title = "nwfz"
size = "900 KB"
addr = ["http://homepage.mac.com/iz_us/nwfz.lzh"]
genre = "-----"
impr = "3"
total = "2"
avg = "0.66"
regist = "20020428"
update = "20020508"
