[[entries]]
no = "1"
name = "AOiRO_Manbow"
title = "Shock Waltz"
size = "30722 KB"
addr = ["http://manbow.nothing.sh/bms/%5bem31%5dshock_w.zip"]
genre = "HARD CORE"
impr = "13"
total = "10"
avg = "0.76"
regist = "2004/12/31 07:38"
update = "2005/01/08 22:32"

[[entries]]
no = "2"
name = "zit"
title = "AcidAce-Alliance"
size = "7291 KB"
addr = ["http://www7a.biglobe.ne.jp/~PixelLife/event/a3-bga-zit.zip"]
genre = "speedfunk"
impr = "16"
total = "6"
avg = "0.37"
regist = "2004/12/31 23:57"
update = "2005/01/08 22:34"

[[entries]]
no = "3"
name = "cyclia"
title = "kioku"
size = "1099 KB"
addr = ["http://www.geocities.jp/retrofuture_ag/cyc-kioku.zip"]
genre = "Experimental"
impr = "16"
total = "10"
avg = "0.62"
regist = "2004/12/31 08:25"
update = "2005/01/08 22:35"

[[entries]]
no = "4"
name = "Nori"
title = "gleamy ignorance"
size = "8460 KB"
addr = [
    "http://www.ismusic.ne.jp/s-curve/as/",
    "http://ama-oto.org/bga/gi-bga-hq.zip",
    "http://ama-oto.org/bga/gi-bga-lq.zip",
]
genre = "d'm'b"
impr = "17"
total = "9"
avg = "0.52"
regist = "2004/12/31 08:26"
update = "2005/01/08 22:46"

[[entries]]
no = "5"
name = "tes"
title = "CY BER  S ECT I ON"
size = "2000 KB"
addr = ["http://t-e-s.hp.infoseek.co.jp/works/tes_cs_bga.zip"]
genre = "TECHNICAL BASS"
impr = "15"
total = "10"
avg = "0.66"
regist = "2004/12/31 08:27"
update = "2005/01/08 22:59"

[[entries]]
no = "6"
name = "ers"
title = "JULIA"
size = "0 KB"
addr = ["http://www.rave-slave.com/up/julia.zip"]
genre = "RAVE"
impr = "13"
total = "6"
avg = "0.46"
regist = "2004/12/31 08:27"
update = "2005/01/08 23:15"

[[entries]]
no = "7"
name = "retu"
title = "like a dandelion"
size = "4172 KB"
addr = ["http://www.pixellife.x0.to/bms/retu-lad-bga.zip"]
genre = "house"
impr = "13"
total = "12"
avg = "0.92"
regist = "2004/12/31 08:28"
update = "2006/04/17 15:34"

[[entries]]
no = "8"
name = "140"
title = "all day"
size = "3920 KB"
addr = ["http://big.freett.com/140_threebit/140_alldayBGA.zip"]
genre = "trance"
impr = "14"
total = "4"
avg = "0.28"
regist = "2004/12/31 08:29"
update = "2005/01/08 23:34"

[[entries]]
no = "9"
name = "zit"
title = "AcidAce-Alliance"
size = "7000 KB"
addr = ["http://digizliar.hp.infoseek.co.jp/a3bga.zip"]
genre = "speedfunk"
impr = "0"
total = "0"
avg = "0"
regist = "2004/12/31 23:57"
update = "2004/12/31 23:57"
