[[entries]]
no = "1"
name = "Elyts"
title = "For Fun"
size = "1740 KB"
addr = ["http://d3mix.x0.com/mystyle/bms/for_fun.zip"]
genre = "HAPPY"
impr = "5"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 00:01"
update = "2005/08/04 12:59"

[[entries]]
no = "2"
name = "tarolabo"
title = "CapeBall"
size = "1326 KB"
addr = ["http://hi-ho.mine.nu/tarolabo/CapeBall.zip"]
genre = "Techno"
impr = "23"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 00:04"
update = "2005/08/06 23:52"

[[entries]]
no = "3"
name = "源屋"
title = "Heaven's Logic"
size = "12412 KB"
addr = ["http://minamotoya2960.hp.infoseek.co.jp/files/HLQ.rar"]
genre = "Trance"
impr = "4"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 00:04"
update = "2005/08/04 21:36"

[[entries]]
no = "4"
name = "部長"
title = "ハリボテ音楽隊"
size = "931 KB"
addr = ["http://sapporo.cool.ne.jp/butyau/haribote.zip"]
genre = "Collage"
impr = "7"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 00:04"
update = "2005/08/04 01:33"

[[entries]]
no = "5"
name = "morigasigeru"
title = "FTW-893"
size = "5317 KB"
addr = ["http://sound.jp/takelove/ftw.html"]
genre = "HIP HOP"
impr = "15"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 00:07"
update = "2005/08/04 18:18"

[[entries]]
no = "6"
name = "PASS"
title = "cobalt blue"
size = "2700 KB"
addr = ["http://hc5.seikyou.ne.jp/home/ore303miss-ile/DLpage02.htm"]
genre = "House"
impr = "8"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 00:10"
update = "2005/08/04 13:37"

[[entries]]
no = "7"
name = "AKIRA YAMAOKA"
title = "350bpm"
size = "1543 KB"
addr = ["http://miku22.hp.infoseek.co.jp/350bpm.zip"]
genre = "HYPER TECNO"
impr = "5"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 00:15"
update = "2005/08/07 00:00"

[[entries]]
no = "8"
name = "NECOX -33.90%"
title = "This is ﾋﾟﾓ song."
size = "723 KB"
addr = [
    "(ほんけ)",
    "http://www37.tok2.com/home2/nekomimi/bms/necox_bof2005before.zip",
    "(みらー)",
    "http://nekomimi.bms.ms/bms/necox_bof2005before.zip",
]
genre = "J-ﾃﾗﾔﾙｾﾅｽｗｗｗｗｗｗｗｗｗ"
impr = "7"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 00:27"
update = "2005/08/03 14:24"

[[entries]]
no = "9"
name = "#268"
title = "船着場"
size = "8323 KB"
addr = ["http://www.geocities.jp/pms268/bms/268_04_fune_mq.zip"]
genre = "Acoustic"
impr = "3"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 00:54"
update = "2005/08/04 13:09"

[[entries]]
no = "10"
name = "#268"
title = "呪い"
size = "9 KB"
addr = ["http://www.geocities.jp/pms268/bms/268_05_noroi_lq.zip"]
genre = "Curse"
impr = "4"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 00:56"
update = "2005/08/03 14:13"

[[entries]]
no = "11"
name = "assoa"
title = "ばーすとのう はやい"
size = "112 KB"
addr = ["http://homepage3.nifty.com/freeze_soa_31/temp/asdfsoa.rar"]
genre = "PROGRESSIVE ASDF"
impr = "8"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 01:03"
update = "2005/08/05 16:18"

[[entries]]
no = "12"
name = "feat.丸山"
title = "コロ助2006 -Romantic extra-"
size = "365 KB"
addr = ["http://homepage3.nifty.com/freeze_soa_31/temp/korosukesoa.rar"]
genre = "HAPPY KUSOGE- CORE"
impr = "8"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 02:08"
update = "2005/08/05 19:10"

[[entries]]
no = "13"
name = "908 / supbaby / Yamajet"
title = "drivin'FTR"
size = "6420 KB"
addr = ["http://yamajet.bms.ms/bms/data/yamajet_drivin_ftr.rar"]
genre = "TECHNO"
impr = "7"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 02:38"
update = "2005/08/06 23:59"

[[entries]]
no = "14"
name = "RUZEEA"
title = "鉄の花"
size = "2093 KB"
addr = ["http://www.ismusic.ne.jp/ruz/bms/ruz_tetu-hana.rar"]
genre = "Techno"
impr = "4"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 02:52"
update = "2005/08/06 23:57"

[[entries]]
no = "15"
name = "roop"
title = "Beat out Floor"
size = "7500 KB"
addr = ["http://www5f.biglobe.ne.jp/~roop/data/bof.rar"]
genre = "BREAKBEAT"
impr = "9"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 03:30"
update = "2005/08/06 23:52"

[[entries]]
no = "16"
name = "Yamajet"
title = "super long discouragement"
size = "14858 KB"
addr = ["http://yamajet.bms.ms/bms/data/yamajet_super_long_discouragement.rar"]
genre = "ACID JAZZ"
impr = "9"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 03:36"
update = "2005/08/06 23:52"

[[entries]]
no = "17"
name = "ratsulg"
title = "Afternoon Cafe"
size = "13800 KB"
addr = ["http://www.geocities.jp/seven_colors_pallet/af.htm"]
genre = "Bossanova"
impr = "5"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 03:49"
update = "2005/08/06 23:48"

[[entries]]
no = "18"
name = "Yamajet"
title = "2038"
size = "10606 KB"
addr = ["http://yamajet.bms.ms/bms/data/yamajet_2038.rar"]
genre = "MONDO"
impr = "7"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 04:21"
update = "2005/08/06 23:43"

[[entries]]
no = "19"
name = "λ口"
title = "お叱りのメール"
size = "640 KB"
addr = ["http://hitujimura.hp.infoseek.co.jp/bms.html"]
genre = "エレクトロ"
impr = "4"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 06:31"
update = "2005/08/04 21:42"

[[entries]]
no = "20"
name = "源屋"
title = "MTC001"
size = "7384 KB"
addr = ["http://minamotoya2960.hp.infoseek.co.jp/files/MTC001.rar"]
genre = "Trancecore"
impr = "3"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 13:40"
update = "2005/08/05 03:59"

[[entries]]
no = "21"
name = "void"
title = "movement"
size = "2577 KB"
addr = ["http://void-z.hp.infoseek.co.jp/void_movement.zip"]
genre = "Epic House"
impr = "2"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 14:07"
update = "2005/08/05 04:15"

[[entries]]
no = "22"
name = "Patena"
title = "泡沫"
size = "9586 KB"
addr = [
    "http://www.ismusic.ne.jp/lemd/mp/utakata-hq-.rar",
    "（HQ版7Mくらい）",
    "http://www.ismusic.ne.jp/lemd/mp/utakata-mq-.rar",
    "（MQ版1,4Mくらい）",
    "http://www.ismusic.ne.jp/lemd/mp/utakata-lq-.rar",
    "（LQ版1Mくらい）",
]
genre = "Drum'n Dirge"
impr = "2"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 14:27"
update = "2005/08/06 09:32"

[[entries]]
no = "23"
name = "Rats"
title = "walk around there"
size = "4062 KB"
addr = [
    "http://kazu3.com/silverstar/music/rt03_walk-around-there.zip",
    "http://www.geocities.jp/rs_sign_2nd/bms.html",
    "（ミラー）",
]
genre = "light pop"
impr = "1"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 16:01"
update = "2005/08/02 23:34"

[[entries]]
no = "24"
name = "TAK"
title = "Thunder V <777-Style>"
size = "1748 KB"
addr = ["http://www.ismusic.ne.jp/djtak/bms/thunder_lq.rar"]
genre = "Epic Trance"
impr = "2"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 16:14"
update = "2005/08/06 23:46"

[[entries]]
no = "25"
name = "Est"
title = "カゼノサカナノウタ"
size = "3633 KB"
addr = ["http://estish.hp.infoseek.co.jp/bms/kaze.zip"]
genre = "TRANCE"
impr = "7"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 16:47"
update = "2005/08/06 23:58"

[[entries]]
no = "26"
name = "Yuzo Masuko"
title = "Unknown Rhythm"
size = "1240 KB"
addr = ["http://"]
genre = "Techno"
impr = "1"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 17:41"
update = "2005/08/06 11:43"

[[entries]]
no = "27"
name = "Glome (maxXx65535)"
title = "Eclipse (Luna)"
size = "6049 KB"
addr = [
    "http://65535.bms.ms/files/glome_eclipse_luna.rar",
    "(WAVE版)",
    "http://65535.bms.ms/files/glome_eclipse_luna_vorbis.rar",
    "(Vorbis版)",
]
genre = "Drum'n'Bass"
impr = "4"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 19:12"
update = "2005/08/06 23:54"

[[entries]]
no = "28"
name = "plastic"
title = "しぐ☆しぐ"
size = "1599 KB"
addr = [
    "http://www.closeplace.com/bms/sigsig.rar",
    "http://www.closeplace.com/bms/sigsig_hq.rar",
    "（高音質版）",
]
genre = "HAPPY HARDCORE"
impr = "4"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 20:43"
update = "2005/08/06 23:58"

[[entries]]
no = "29"
name = "scytheleg"
title = "sky with you"
size = "2300 KB"
addr = ["http://www4.pf-x.net/~scytheleg/tempyou/music/bms/swy/event.html"]
genre = "speed pop"
impr = "1"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 22:25"
update = "2005/08/03 10:47"

[[entries]]
no = "30"
name = "14歳"
title = "wondergirl★fangirl"
size = "5796 KB"
addr = ["http://age14.s152.xrea.com/wsf.zip"]
genre = "love song"
impr = "3"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 22:40"
update = "2005/08/04 22:43"

[[entries]]
no = "31"
name = "naotyu-"
title = "Good Bye W.McL..."
size = "7072 KB"
addr = ["http://www.naotyu-studio7.com/music/data/mcl.zip"]
genre = "Latin House"
impr = "5"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 23:03"
update = "2005/08/06 23:49"

[[entries]]
no = "32"
name = "rhythm crax"
title = "festival"
size = "2030 KB"
addr = ["http://mnmr.dw.land.to/dlbms/rc_festival.zip"]
genre = "tribal"
impr = "2"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 23:20"
update = "2005/08/03 02:16"

[[entries]]
no = "33"
name = "(*´ω｀)っ[ルゼ]"
title = "bit cross"
size = "100 KB"
addr = ["http://www.bisuke.biz/~mikodjhiro/music/21_bit_cross_lq.rar"]
genre = "CLICK HOUSE"
impr = "3"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 23:23"
update = "2005/08/01 12:13"

[[entries]]
no = "34"
name = "knot"
title = "instant jungle"
size = "2703 KB"
addr = ["http://knot2565.hp.infoseek.co.jp/knot_bms.html"]
genre = "HARD TECHNO"
impr = "4"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 23:42"
update = "2005/08/04 22:33"

[[entries]]
no = "35"
name = "Tassam"
title = "Autism"
size = "3280 KB"
addr = ["http://kokuryu.s49.xrea.com/tassam/autism.rar"]
genre = "Hardstyle"
impr = "6"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 23:47"
update = "2005/08/06 23:55"

[[entries]]
no = "36"
name = "Octa the B.G."
title = "ブレイクビーツ"
size = "1796 KB"
addr = ["http://www.geocities.jp/octa124/breakbeats.zip"]
genre = "ブレイクビーツ"
impr = "6"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 23:47"
update = "2005/08/06 23:50"

[[entries]]
no = "37"
name = "SUKE"
title = "ANTI"
size = "7133 KB"
addr = ["http://biznot.biz/ANTI.zip"]
genre = "MINIMAL"
impr = "8"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 23:48"
update = "2005/08/07 03:23"

[[entries]]
no = "38"
name = "t+pazolite"
title = "Pubescent*Heart*Starship*Remix"
size = "5794 KB"
addr = ["http://www.bisuke.biz/~chs/works/pubescent_heart_starship_remix.rar"]
genre = "Happy Synth Pop"
impr = "2"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 23:50"
update = "2005/08/03 03:52"

[[entries]]
no = "39"
name = "ルナマりア"
title = "有限と微小のパン"
size = "12000 KB"
addr = ["http://big.freett.com/mikoko/pan.rar"]
genre = "Dark s.d'n.q.b"
impr = "4"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 23:53"
update = "2005/08/06 23:45"

[[entries]]
no = "40"
name = "DOT96"
title = "GAMBLE"
size = "9 KB"
addr = ["http://cng.s54.xrea.com/bms/gamble.cab"]
genre = "DRUM'N'BASS"
impr = "8"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 23:56"
update = "2005/08/06 23:45"

[[entries]]
no = "41"
name = "one"
title = "one"
size = "6 KB"
addr = ["http://sameness.s56.xrea.com/file/one.zip"]
genre = "techno"
impr = "1"
total = "--"
median = "--"
avg = "--"
regist = "2005/07/30 23:57"
update = "2005/08/02 13:53"
