[[entries]]
no = "1"
name = "よるなぎ＋鍋＋餅"
title = "激☆空間プロポーズ"
size = "15048 KB"
addr = [
    "http://park8.wakwak.com/~nagi/_ynm_gpa.rar",
    "http://nightcalm.net/_ynm_gpa.rar",
    "（ミラー）",
]
genre = "be gone"
impr = "8"
total = "8"
avg = "1"
regist = "2005/09/04 00:02"
update = "2005/09/19 21:51"

[[entries]]
no = "2"
name = "鈴木あも"
title = "The Old Man and Deep Blue Ocean"
size = "17017 KB"
addr = [
    "HQ版(16M)",
    "http://simesaba.sakura.ne.jp/camu/bga/tom_dbo/tom_dbo_bga_HQ.lzh",
]
genre = "lounge"
impr = "7"
total = "7"
avg = "1"
regist = "2005/09/04 00:25"
update = "2006/01/06 12:28"

[[entries]]
no = "3"
name = "fity"
title = "貴方の居る場所"
size = "4501 KB"
addr = ["http://www.h4.dion.ne.jp/~fity/anatano_STD_bga.rar"]
genre = "BALLAD"
impr = "8"
total = "8"
avg = "1"
regist = "2005/09/06 22:54"
update = "2005/09/18 22:26"

[[entries]]
no = "4"
name = "タリキホンガンジ"
title = "another one"
size = "3930 KB"
addr = ["http://bisuke.biz/~digizliar/zit_bof_bga.rar"]
genre = "trance"
impr = "5"
total = "5"
avg = "1"
regist = "2005/09/09 23:59"
update = "2005/09/18 22:27"

[[entries]]
no = "5"
name = "mxk"
title = "成敗！ -Boost Remix-"
size = "11500 KB"
addr = ["http://zephlabel.com/bof2005a/mxk_obelisk_seibai.zip"]
genre = "Makina/Trance Core"
impr = "7"
total = "7"
avg = "1"
regist = "2005/09/10 01:43"
update = "2005/09/18 22:27"

[[entries]]
no = "6"
name = "KAKU"
title = "有限と微小のパン"
size = "4140 KB"
addr = ["削除済"]
genre = "Dark s.d'n.q.b"
impr = "3"
total = "3"
avg = "1"
regist = "2005/09/11 00:09"
update = "2005/09/22 21:39"

[[entries]]
no = "7"
name = "タリキホンガンジ"
title = "Clione -cyber mix-"
size = "4800 KB"
addr = ["http://bisuke.biz/~digizliar/zit_clione_bga.zip"]
genre = "TRANCE"
impr = "5"
total = "5"
avg = "1"
regist = "2005/09/11 00:11"
update = "2005/09/18 22:28"

[[entries]]
no = "8"
name = "wandering light a.k.a. syatten"
title = "Love Module"
size = "11357 KB"
addr = [
    "http://www.ismusic.ne.jp/s-curve/bms/wl_love_module_bgaLQ.rar",
    "(11.0M)",
    "http://www.ismusic.ne.jp/s-curve/bms/wl_love_module_bgaHQ.rar",
    "(24.8M)",
]
genre = "J-TRANCE"
impr = "8"
total = "8"
avg = "1"
regist = "2005/09/11 21:44"
update = "2005/09/18 23:14"

[[entries]]
no = "9"
name = "Symmetric face"
title = "drop (dive to noise)"
size = "3440 KB"
addr = ["http://kokuryu.s49.xrea.com/tassam/sf_ddtn_bga.rar"]
genre = "industrial"
impr = "7"
total = "7"
avg = "1"
regist = "2005/09/11 22:30"
update = "2005/09/18 22:45"

[[entries]]
no = "10"
name = "eff_01x with 思春期さん"
title = "another one"
size = "15000 KB"
addr = ["http://www.bisuke.biz/~ke/imgside/mov/bga/ews_bga_a1.zip"]
genre = "trance"
impr = "6"
total = "6"
avg = "1"
regist = "2005/09/11 23:04"
update = "2005/09/22 21:40"

[[entries]]
no = "11"
name = "cyclia"
title = "drivin'FTR"
size = "2138 KB"
addr = [
    "http://manbow.nothing.sh/event/event.cgi?action=More_def&num=13&event=23",
    "(BMS file)",
    "http://www.geocities.jp/retrofuture_ag/cyc-ftr-lq.zip",
    "http://www.geocities.jp/retrofuture_ag/cyc-ftr-hq.zip",
    "(13666KB)",
]
genre = "TECHNO"
impr = "6"
total = "6"
avg = "1"
regist = "2005/09/11 23:37"
update = "2005/09/18 23:20"

[[entries]]
no = "12"
name = "ケモノ☆ラバーズ"
title = "道しるべ"
size = "9250 KB"
addr = ["コメント欄参照"]
genre = "starry pop"
impr = "9"
total = "9"
avg = "1"
regist = "2005/09/11 23:58"
update = "2005/09/18 23:42"
