[[entries]]
no = "1"
name = "sun3+Mik"
title = "うどんげ"
size = "18000 KB"
addr = ["http://www.geocities.jp/sun3_bms/junk.html"]
genre = "invisible core"
impr = "17"
total = "41"
avg = "2.41"
regist = "2005/09/12 00:01"
update = "2005/09/21 22:57"

[[entries]]
no = "2"
name = "田村くん"
title = "は じ め て"
size = "441 KB"
addr = ["http://sound.jp/takesama/tyou.html"]
genre = "HIP HOP"
impr = "11"
total = "35"
avg = "3.18"
regist = "2005/09/12 00:01"
update = "2005/09/19 23:47"

[[entries]]
no = "3"
name = "Dark_seeD"
title = "刹那の見斬り"
size = "398 KB"
addr = ["http://hi-ho.mine.nu/tarolabo/setsuna.zip"]
genre = "[ ]"
impr = "20"
total = "66"
avg = "3.3"
regist = "2005/09/12 00:03"
update = "2005/09/20 22:55"

[[entries]]
no = "4"
name = "朝日大学付属高校カバディー部キャプテン"
title = "俺はビートマニア！お前はカバディーマニア!!"
size = "2304 KB"
addr = ["http://2.csx.jp/users/boxism-8500/junk/kabadhi-2.zip"]
genre = "カバデー"
impr = "11"
total = "34"
avg = "3.09"
regist = "2005/09/12 00:18"
update = "2005/09/19 17:10"

[[entries]]
no = "5"
name = "sept"
title = "starsplay"
size = "2200 KB"
addr = ["http://stnspr.hp.infoseek.co.jp/eve.html"]
genre = "chaoscore"
impr = "10"
total = "15"
avg = "1.5"
regist = "2005/09/12 00:18"
update = "2005/09/19 23:55"

[[entries]]
no = "6"
name = "NECOX -33.90%＋D-723＋NM昆布員＋BMS関係者数名"
title = 'ピアノ協奏曲第-1番 "蠍ヴィ"'
size = "2820 KB"
addr = [
    "http://nekomimi.bms.ms/bms/necox_sasori.rar",
    "(2820KB)",
    "http://nekomimi.bms.ms/bms/necox_sasori.zip",
    "(3430KB)",
    "※今回の登録作3作品全て(No.06・08・09)をまとめたアーカイブは以下です。",
    "http://nekomimi.bms.ms/bms/bofoon2005_allbms.rar",
    "(3150KB)",
    "http://www37.tok2.com/home2/nekomimi/bms/bofoon2005_allbms.zip",
    "(4020KB)",
]
genre = "いろんな意味でDIRGE"
impr = "32"
total = "123"
avg = "3.84"
regist = "2005/09/12 00:36"
update = "2005/09/20 06:36"

[[entries]]
no = "7"
name = "モルさん"
title = "minimamusisutemu"
size = "6000 KB"
addr = ["http://plaza.rakuten.co.jp/mol300/"]
genre = "tekuno"
impr = "11"
total = "32"
avg = "2.9"
regist = "2005/09/12 00:41"
update = "2005/09/20 00:12"

[[entries]]
no = "8"
name = "Digitalize-723"
title = "X300"
size = "352 KB"
addr = [
    "http://nekomimi.bms.ms/bms/d723_x300.rar",
    "(352KB)",
    "http://nekomimi.bms.ms/bms/d723_x300.zip",
    "(599KB)",
    "※今回の登録作3作品全て(No.06・08・09)をまとめたアーカイブは以下です。",
    "http://nekomimi.bms.ms/bms/bofoon2005_allbms.rar",
    "(3150KB)",
    "http://www37.tok2.com/home2/nekomimi/bms/bofoon2005_allbms.zip",
    "(4020KB)",
]
genre = "Break Core"
impr = "12"
total = "28"
avg = "2.33"
regist = "2005/09/12 00:41"
update = "2005/09/20 00:15"

[[entries]]
no = "9"
name = "NECOX -33.90%"
title = "なんかGameOverっぽい"
size = "10 KB"
addr = [
    "http://nekomimi.bms.ms/bms/necox_gameover.zip",
    "(10KB)",
    "※今回の登録作3作品全て(No.06・08・09)をまとめたアーカイブは以下です。",
    "http://nekomimi.bms.ms/bms/bofoon2005_allbms.rar",
    "(3150KB)",
    "http://www37.tok2.com/home2/nekomimi/bms/bofoon2005_allbms.zip",
    "(4020KB)",
]
genre = "J-8bit"
impr = "13"
total = "38"
avg = "2.92"
regist = "2005/09/12 00:52"
update = "2005/09/20 00:19"

[[entries]]
no = "10"
name = "ｐぁｓちｃの中の人"
title = "お花畑と妖精とダルシム"
size = "7066 KB"
addr = [
    "http://www.closeplace.com/cat/",
    "からダウンロードお願いします。",
    "女の子がBMSで男の子がMP3です。",
]
genre = "象さんは好きです。でも娘の方がもっと好きです。"
impr = "13"
total = "42"
avg = "3.23"
regist = "2005/09/12 01:49"
update = "2005/09/20 22:46"

[[entries]]
no = "11"
name = "匿名リサーチ350X"
title = "ANCHI"
size = "1430 KB"
addr = ["http://www.bisuke.biz/~mikodjhiro/temp/anchi.rar"]
genre = "TECHNO"
impr = "6"
total = "11"
avg = "1.83"
regist = "2005/09/12 03:24"
update = "2005/09/20 04:02"

[[entries]]
no = "12"
name = "穴楽"
title = "ぼうけんははじまらない"
size = "39 KB"
addr = ["http://kure-na.hp.infoseek.co.jp/dqn.html"]
genre = "どらくえ"
impr = "10"
total = "38"
avg = "3.8"
regist = "2005/09/12 09:38"
update = "2005/09/20 16:47"

[[entries]]
no = "13"
name = "Nick"
title = "かえるのうた"
size = "379 KB"
addr = ["http://nick.shrine-maiden.org/kaeru.lzh"]
genre = "民謡"
impr = "8"
total = "23"
avg = "2.87"
regist = "2005/09/12 09:57"
update = "2005/09/20 20:16"

[[entries]]
no = "14"
name = "HaLとririとにゃんこ"
title = "私のにゃんこちゃん"
size = "16012 KB"
addr = ["http://www.remarkablesense.org/~hal/waveceptor/bof2005/watanya.zip"]
genre = "ひっぷほっぷ☆"
impr = "15"
total = "38"
avg = "2.53"
regist = "2005/09/12 14:43"
update = "2005/09/20 22:50"

[[entries]]
no = "15"
name = "BnMC"
title = "1 -one-"
size = "1037 KB"
addr = ["http://www.realintegrity.net/~misobon3/bms/one.htm"]
genre = "dream and memory"
impr = "6"
total = "20"
avg = "3.33"
regist = "2005/09/12 16:08"
update = "2005/09/20 20:35"

[[entries]]
no = "16"
name = "(´дゝ｀)"
title = "('A｀)"
size = "99999 KB"
addr = ["http://wakimata0rz.hp.infoseek.co.jp/BMS/bms.html"]
genre = "へびーへたれしゃうと"
impr = "10"
total = "33"
avg = "3.3"
regist = "2005/09/12 16:12"
update = "2005/09/25 16:52"

[[entries]]
no = "17"
name = "XeX"
title = "THE へたれ"
size = "614 KB"
addr = ["http://www.geocities.jp/gradius_573/dairi/the_hetare.zip"]
genre = "MINIMA TECHNO"
impr = "7"
total = "18"
avg = "2.57"
regist = "2005/09/12 16:53"
update = "2005/09/20 20:50"

[[entries]]
no = "18"
name = "('дゝ｀)"
title = "いうえお"
size = "12345 KB"
addr = ["http://wakimata0rz.hp.infoseek.co.jp/BMS/bms.html"]
genre = "あ"
impr = "8"
total = "28"
avg = "3.5"
regist = "2005/09/12 17:23"
update = "2005/09/25 16:53"

[[entries]]
no = "19"
name = "M2"
title = "Take It Yabu"
size = "84 KB"
addr = [
    "http://members.at.infoseek.co.jp/maru_hensin/top.htm",
    "ここの上からどうぞ",
]
genre = "竹薮と私"
impr = "6"
total = "21"
avg = "3.5"
regist = "2005/09/12 18:16"
update = "2005/09/20 21:03"

[[entries]]
no = "20"
name = "ぴあののおに"
title = "じしんさく"
size = "2550 KB"
addr = ["http://www.bisuke.biz/~mikodjhiro/temp/abcdefg.zip"]
genre = "ぴあのあんびえんと"
impr = "9"
total = "31"
avg = "3.44"
regist = "2005/09/12 19:40"
update = "2005/09/20 21:09"

[[entries]]
no = "21"
name = "#268"
title = "おおぞらをとびたい…(T△T)"
size = "7790 KB"
addr = ["http://www.geocities.jp/pms268/bms/268_06_fits_lq.zip"]
genre = "交響曲第268番(うそ)"
impr = "10"
total = "28"
avg = "2.8"
regist = "2005/09/12 19:54"
update = "2005/09/20 21:17"

[[entries]]
no = "22"
name = "IkAGURA"
title = "In The Dark (for BOFooN)"
size = "94499 KB"
addr = ["http://ikaruga.bms.ms/data/itd.zip"]
genre = "Hard Minimal"
impr = "7"
total = "19"
avg = "2.71"
regist = "2005/09/12 21:28"
update = "2005/09/20 21:34"

[[entries]]
no = "23"
name = "skmz vs ピーナッツ吉森"
title = "萌"
size = "1695 KB"
addr = ["http://www.realintegrity.net/~misobon3/bms/moe.htm"]
genre = "HUMAN SWIMMER"
impr = "6"
total = "13"
avg = "2.16"
regist = "2005/09/12 22:03"
update = "2005/09/18 12:31"

[[entries]]
no = "24"
name = "RevenG"
title = "900bpm"
size = "334 KB"
addr = ["http://style.x0.com/900bpm.zip"]
genre = "TRUE GABBA"
impr = "8"
total = "22"
avg = "2.75"
regist = "2005/09/12 22:32"
update = "2005/09/21 07:11"

[[entries]]
no = "25"
name = "Needle Valley(Amano Jack)"
title = "曲。"
size = "1787 KB"
addr = ["http://www.geocities.jp/needle_valleys/bofoon2005.html"]
genre = "わかりません。"
impr = "6"
total = "19"
avg = "3.16"
regist = "2005/09/13 01:05"
update = "2005/09/21 00:29"

[[entries]]
no = "26"
name = "Clair"
title = "冬の灯火"
size = "1030 KB"
addr = ["http://hi-ho.mine.nu/krafight/temp/clair_tomosibi.rar"]
genre = "Kanonちっく"
impr = "10"
total = "37"
avg = "3.7"
regist = "2005/09/13 02:23"
update = "2005/09/21 17:33"

[[entries]]
no = "27"
name = "ギャオソ"
title = "音痴な信号 その2"
size = "198 KB"
addr = ["http://gyaon.web.infoseek.co.jp/bmbm_Oth_.html"]
genre = "AHO MUSIC"
impr = "16"
total = "67"
avg = "4.18"
regist = "2005/09/13 13:09"
update = "2005/09/20 22:56"

[[entries]]
no = "28"
name = "IkAGURA"
title = "Amen Broken!!!"
size = "460 KB"
addr = ["http://ikaruga.bms.ms/data/amen.zip"]
genre = "BreakCore"
impr = "10"
total = "40"
avg = "4"
regist = "2005/09/13 14:45"
update = "2005/09/19 06:06"

[[entries]]
no = "29"
name = "Remixed by U2(DJ.Angel+Mr.Z)"
title = "沢木椿-Electroshock Remix-"
size = "2668 KB"
addr = [
    "URL(DL)",
    "http://www.geocities.jp/revivalitive/BMS/tsubaki_ele.zip",
    "HQ(上書き版)",
    "http://www.geocities.jp/revivalitive/BMS/tsubaki_elehq.zip",
]
genre = "ELECTROSHOCK"
impr = "8"
total = "19"
avg = "2.37"
regist = "2005/09/13 17:22"
update = "2005/09/18 15:34"

[[entries]]
no = "30"
name = "dustcloth"
title = "one day of gabbar"
size = "777 KB"
addr = ["http://dustcloth.info/bms/Ikemen_hardcore_2.zip"]
genre = "Noise'n'bass"
impr = "10"
total = "29"
avg = "2.9"
regist = "2005/09/13 19:42"
update = "2005/09/20 21:46"

[[entries]]
no = "31"
name = "けぺろぴょｆ"
title = "○んこ"
size = "616 KB"
addr = ["http://asdf.bms.ms/junk/bms/keperopyof_sahfufsdjifhjfssdfdf.zip"]
genre = "MEDIEVAL CHOIR"
impr = "8"
total = "22"
avg = "2.75"
regist = "2005/09/14 02:14"
update = "2005/09/19 06:04"

[[entries]]
no = "32"
name = "λ口"
title = "††† 罪 †††"
size = "2850 KB"
addr = ["http://hitujimura.hp.infoseek.co.jp/bms.html"]
genre = "Guilty Break"
impr = "9"
total = "30"
avg = "3.33"
regist = "2005/09/14 08:15"
update = "2005/09/20 21:59"

[[entries]]
no = "33"
name = "ギャオソ"
title = "鳥"
size = "578 KB"
addr = ["http://gyaon.web.infoseek.co.jp/bms/g_tori.lzh"]
genre = "将来の夢"
impr = "15"
total = "59"
avg = "3.93"
regist = "2005/09/14 09:51"
update = "2005/09/19 23:17"

[[entries]]
no = "34"
name = "CM"
title = "W.H.U"
size = "263 KB"
addr = [
    "こちらに移しました",
    "http://d.hatena.ne.jp/cm_comac/",
]
genre = "PIANO PUNK／やりすぎです"
impr = "7"
total = "25"
avg = "3.57"
regist = "2005/09/14 19:11"
update = "2005/09/21 06:52"

[[entries]]
no = "35"
name = "DJDJ-KAI"
title = "THE SAFARI -PIPIPI MIX-"
size = "100 KB"
addr = ["http://www9.plala.or.jp/ffsaga-kai/safari.lzh"]
genre = "ぴぴっぴ"
impr = "5"
total = "17"
avg = "3.4"
regist = "2005/09/14 23:25"
update = "2005/09/19 05:58"

[[entries]]
no = "36"
name = "対象年齢12-33"
title = "び～とまによん"
size = "122 KB"
addr = ["http://www.geocities.jp/challenger_challe/bms/challenger_beat.zip"]
genre = "percussion"
impr = "6"
total = "15"
avg = "2.5"
regist = "2005/09/15 09:24"
update = "2005/09/26 13:35"

[[entries]]
no = "37"
name = "未来"
title = "Endless end"
size = "319 KB"
addr = ["http://www.geocities.jp/rf_mirai/bms/kuso4.zip"]
genre = "Trance"
impr = "8"
total = "28"
avg = "3.5"
regist = "2005/09/15 17:37"
update = "2005/09/19 06:00"

[[entries]]
no = "38"
name = "Nick"
title = "うんこちんちん"
size = "00000000000000000000000000000 KB"
addr = ["http://nick.shrine-maiden.org/unkotintin.lzh"]
genre = "下ネタ"
impr = "5"
total = "14"
avg = "2.8"
regist = "2005/09/15 22:26"
update = "2005/09/19 01:39"

[[entries]]
no = "39"
name = "闇を撒くもの"
title = "ぼこすか戦争"
size = "94 KB"
addr = ["http://www5a.biglobe.ne.jp/~yami/bms/bokosuka.lzh"]
genre = "ねばーえんでぃんぐすとーりー"
impr = "14"
total = "46"
avg = "3.28"
regist = "2005/09/16 06:09"
update = "2005/09/20 00:23"

[[entries]]
no = "40"
name = "AKY"
title = "米"
size = "608 KB"
addr = ["http://minamotoya2960.hp.infoseek.co.jp/files/foon_g.rar"]
genre = "人間演奏"
impr = "5"
total = "12"
avg = "2.4"
regist = "2005/09/16 22:36"
update = "2005/09/20 21:07"

[[entries]]
no = "41"
name = "ショタロウくん11歳"
title = "The Emperor's New Clothes"
size = "9 KB"
addr = ["http://mikihara.hp.infoseek.co.jp/BMS/keyboard.bms"]
genre = "KEYBOARD MUSIC"
impr = "5"
total = "9"
avg = "1.8"
regist = "2005/09/17 01:47"
update = "2005/09/20 21:55"

[[entries]]
no = "42"
name = "コマ＋CM"
title = "来週？"
size = "1311 KB"
addr = [
    "こちらに移しました",
    "http://d.hatena.ne.jp/cm_comac/",
]
genre = "謎です"
impr = "4"
total = "4"
avg = "1"
regist = "2005/09/17 09:43"
update = "2005/09/21 06:51"

[[entries]]
no = "43"
name = "Elyts"
title = "ハッピー・はっぴー・レインボー"
size = "3476 KB"
addr = ["http://d3mix.x0.com/mystyle/bms/happy_happy_rainbow.zip"]
genre = "HAPPY"
impr = "4"
total = "9"
avg = "2.25"
regist = "2005/09/17 11:25"
update = "2005/09/21 07:14"

[[entries]]
no = "44"
name = "#268"
title = "トイレ"
size = "1318 KB"
addr = ["http://www.geocities.jp/pms268/bms/268_07_toire_hq.zip"]
genre = "日常"
impr = "3"
total = "10"
avg = "3.33"
regist = "2005/09/17 16:44"
update = "2005/09/20 22:51"

[[entries]]
no = "45"
name = "dustcloth"
title = "うろ覚えコピーbms"
size = "1997 KB"
addr = ["http://dustcloth.info/bms/saikotech.zip"]
genre = "Happysynthhardcore"
impr = "2"
total = "8"
avg = "4"
regist = "2005/09/17 21:04"
update = "2005/09/20 22:12"

[[entries]]
no = "46"
name = "KOH"
title = "夏か・・・げ？"
size = "256 KB"
addr = ["http://www.geocities.jp/kou_bm98/k_natsukage.zip"]
genre = "どろり濃厚"
impr = "2"
total = "7"
avg = "3.5"
regist = "2005/09/18 01:39"
update = "2005/09/20 21:46"

[[entries]]
no = "47"
name = "かあかあ"
title = "ニャーです。。。よろしく！"
size = "1330 KB"
addr = ["http://www.geocities.jp/root_boko/bms/bms.html"]
genre = "otonomori techno"
impr = "3"
total = "11"
avg = "3.66"
regist = "2005/09/18 02:59"
update = "2005/09/27 15:07"

[[entries]]
no = "48"
name = "BMS created by Ta2 / BGA・LAYER れいちぇる"
title = "BRAMBLES - from SUPER DONKEY KONG 2-"
size = "20215 KB"
addr = ["http://purotora.com/BMS/bms-08_BRAMBLES.html"]
genre = "GAME MUSIC"
impr = "3"
total = "5"
avg = "1.66"
regist = "2005/09/18 07:46"
update = "2005/09/20 20:48"

[[entries]]
no = "49"
name = "dj p_server(猫っていいよねぇfoon styleとか名乗るヴぁか)"
title = "特に何も考えず適当に音を配置して(略しました)"
size = "1724 KB"
addr = ["http://foonfoonfoon.uh-oh.jp/asdfsugi.zip"]
genre = "もうなんだかなんだろうかクリア不能"
impr = "4"
total = "17"
avg = "4.25"
regist = "2005/09/18 08:46"
update = "2009/11/10 15:13"

[[entries]]
no = "50"
name = "だるしむ"
title = "つんでれつんでれつんでれつんでれつんでれ"
size = "3960 KB"
addr = [
    "http://www.closeplace.com/cat/",
    "http://www.closeplace.com/cat/my_mother.rar",
]
genre = "ひゅーまん いんてれ・・すちん・・ぐ？"
impr = "3"
total = "14"
avg = "4.66"
regist = "2005/09/18 10:28"
update = "2005/09/20 22:43"

[[entries]]
no = "51"
name = "dj p_server(練習したかった輩)"
title = "あの曲の１フレーズ"
size = "54 KB"
addr = ["http://foonfoonfoon.uh-oh.jp/respectmei.zip"]
genre = "STAIR"
impr = "5"
total = "19"
avg = "3.8"
regist = "2005/09/18 18:31"
update = "2009/11/10 15:15"

[[entries]]
no = "52"
name = "未来"
title = "(^-^)/~~~"
size = "496 KB"
addr = ["http://www.geocities.jp/rf_mirai/bms/kuso5.zip"]
genre = "(^-^)/~~~"
impr = "4"
total = "12"
avg = "3"
regist = "2005/09/18 19:28"
update = "2005/09/20 21:03"

[[entries]]
no = "53"
name = "あっぱー"
title = "もちつけ俺とかいう曲らしい"
size = "4 KB"
addr = ["http://amonkido.at.infoseek.co.jp/densyamix.zip"]
genre = "copy"
impr = "2"
total = "7"
avg = "3.5"
regist = "2005/09/18 23:57"
update = "2005/09/20 22:53"

[[entries]]
no = "54"
name = "いぬみれい"
title = "きょうも頑張れ！いぬこたん☆夕日に向かってふわふわふ～"
size = "14868 KB"
addr = ["http://page.freett.com/inumimi/index.htm"]
genre = "電波ソング"
impr = "6"
total = "25"
avg = "4.16"
regist = "2005/09/19 01:13"
update = "2005/09/21 00:15"

[[entries]]
no = "55"
name = "2003年の人"
title = "obsmune"
size = "161 KB"
addr = ["http://www.ismusic.ne.jp/lemd/foon/prm_lq.rar"]
genre = "記憶にございません"
impr = "2"
total = "3"
avg = "1.5"
regist = "2005/09/19 21:18"
update = "2005/09/20 21:23"

[[entries]]
no = "56"
name = "未来"
title = "インプレ期間を1日延長します"
size = "2005 KB"
addr = ["http://asdf.com"]
genre = "お知らせ"
impr = "15"
total = "60"
avg = "4"
regist = "2005/09/19 21:52"
update = "2005/09/20 22:46"
