[[entries]]
no = "1"
name = "D.N.A.MOL3"
title = "％２５"
size = "17700 KB"
addr = ["http://plaza.rakuten.co.jp/mol300/2001"]
genre = "techno"
impr = "12"
total = "8"
avg = "0.66"
regist = "2005/10/08 00:02"
update = "2005/10/16 14:05"

[[entries]]
no = "2"
name = "sun3"
title = "子午線の祀り Nu-style GABBA mix"
size = "5678 KB"
addr = ["http://succinicacid.hp.infoseek.co.jp/BMS33.html"]
genre = "Nu-style GABBA"
impr = "22"
total = "25"
avg = "1.13"
regist = "2005/10/08 00:03"
update = "2005/10/18 22:55"

[[entries]]
no = "3"
name = "腋亦"
title = "BLACK METAL SOUND"
size = "4967 KB"
addr = ["http://wakimata0rz.hp.infoseek.co.jp/BMS/down.html"]
genre = "HEAVY METAL"
impr = "21"
total = "18"
avg = "0.85"
regist = "2005/10/08 00:03"
update = "2005/10/17 08:25"

[[entries]]
no = "4"
name = "キャプテン・ホーク"
title = "呼び醒まされた記憶"
size = "7735 KB"
addr = [
    "http://www99.jp.land.to/",
    "http://www99.jp.land.to/yobisamasaretakioku_lq.rar",
]
genre = "Heavy Metal"
impr = "12"
total = "8"
avg = "0.66"
regist = "2005/10/08 00:05"
update = "2005/10/16 14:51"

[[entries]]
no = "5"
name = "sept-em"
title = "Cruciform Gate"
size = "6938 KB"
addr = ["http://stnspr.hp.infoseek.co.jp/eve2005.html"]
genre = "goa trance"
impr = "15"
total = "17"
avg = "1.13"
regist = "2005/10/08 01:03"
update = "2005/10/17 00:10"

[[entries]]
no = "6"
name = "DJ ボクッ娘"
title = "ボクはスクラッチ名人"
size = "7794 KB"
addr = ["http://morigasigeeru.hp.infoseek.co.jp/boku.html"]
genre = "自慢"
impr = "29"
total = "51"
avg = "1.75"
regist = "2005/10/08 01:14"
update = "2005/10/16 23:08"

[[entries]]
no = "7"
name = "Patena"
title = "Countrydrug"
size = "5832 KB"
addr = [
    "http://www.ismusic.ne.jp/lemd/mp/cd.rar",
    "（8,800KB）",
    "http://www.ismusic.ne.jp/lemd/mp/cd_lq.rar",
    "（5,832KB）",
]
genre = "Psycho"
impr = "14"
total = "11"
avg = "0.78"
regist = "2005/10/08 07:48"
update = "2005/12/16 19:07"

[[entries]]
no = "8"
name = "jippe"
title = "core diver"
size = "11500 KB"
addr = ["http://www.geocities.jp/jippejp/core_diver.zip"]
genre = "？？？"
impr = "16"
total = "8"
avg = "0.5"
regist = "2005/10/08 15:25"
update = "2005/10/16 15:30"

[[entries]]
no = "9"
name = "Renaissance B.C.@yusuke takeuchi"
title = "oblivion"
size = "7074 KB"
addr = [
    "http://www.commonsense.nu/songs/oblivion.rar",
    "http://www.commonsense.nu/songs/oblivion_hq.rar",
]
genre = "d'n'b/progressive"
impr = "18"
total = "26"
avg = "1.44"
regist = "2005/10/08 23:42"
update = "2005/10/16 15:45"

[[entries]]
no = "10"
name = "TAK"
title = "Silent Moon"
size = "17089 KB"
addr = [
    "http://www.ismusic.ne.jp/djtak/bms/silent_moon.zip",
    "http://www.ismusic.ne.jp/djtak/bms/silent_moon.rar",
]
genre = "Art Core"
impr = "24"
total = "37"
avg = "1.54"
regist = "2005/10/10 14:12"
update = "2005/10/16 23:16"

[[entries]]
no = "11"
name = "KO-KO"
title = "trans gate"
size = "9680 KB"
addr = [
    "http://www.ismusic.ne.jp/KO-KO/data/KO-KO_trans_gate_MQ.rar",
    "（RAR2.90圧縮 9680KB)",
    "http://www.ismusic.ne.jp/KO-KO/data/KO-KO_trans_gate_MQ.zip",
    "（zip圧縮 15150KB)",
]
genre = "trance"
impr = "15"
total = "5"
avg = "0.33"
regist = "2005/10/10 21:18"
update = "2005/10/16 23:17"

[[entries]]
no = "12"
name = "dustcloth"
title = "My psychedelic week"
size = "1022 KB"
addr = ["http://dustcloth.info/bms/d-mpw.zip"]
genre = "drum'n'bass"
impr = "17"
total = "6"
avg = "0.35"
regist = "2005/10/10 22:32"
update = "2005/10/16 23:18"

[[entries]]
no = "13"
name = "HaL"
title = "Arcadia"
size = "28528 KB"
addr = [
    "http://www.remarkablesense.org/~hal//waveceptor/bms/bms_arcadia.rar",
    "(28,528KB)",
    "http://www.remarkablesense.org/~hal//waveceptor/bms/bms_arcadia.zip",
    "(37,324KB)",
    "http://www.remarkablesense.org/~hal//waveceptor/bms/bms_arcadia_LQ.rar",
    "(6,724KB)",
    "http://www.remarkablesense.org/~hal//waveceptor/bms/bms_arcadia_LQ.zip",
    "(8,697KB)",
    "※rarファイルのほうは解凍にWinRARのバージョン3.00以上が必要になります。",
]
genre = "tribal pop"
impr = "28"
total = "52"
avg = "1.85"
regist = "2005/10/10 23:53"
update = "2005/10/16 23:18"

[[entries]]
no = "14"
name = "Shiga Niigata elektricity"
title = "Phunky habitude"
size = "8170 KB"
addr = [
    "http://kaibutuk.hp.infoseek.co.jp/sne001.zip",
    "(zip圧縮:8170KB)",
    "http://niigata.cool.ne.jp/kmbms/sne001.rar",
    "(rar圧縮:6120KB)",
]
genre = "liquid funk"
impr = "25"
total = "46"
avg = "1.84"
regist = "2005/10/10 23:56"
update = "2005/10/16 23:19"

[[entries]]
no = "15"
name = "Amatias"
title = "マタタビズム"
size = "4670 KB"
addr = ["http://ueno.cool.ne.jp/nattoumaki/matatabi.rar"]
genre = "Minimal"
impr = "16"
total = "6"
avg = "0.37"
regist = "2005/10/10 23:59"
update = "2005/10/16 23:19"
