[[entries]]
no = "1"
name = "morigasigeru"
title = "girl"
size = "23900 KB"
addr = ["http://he2ho2.s7.xrea.com/mori/"]
genre = "ABSTRACT HIPHOP"
impr = "7"
total = "5"
avg = "0.71"
regist = "2005/12/27 00:40"
update = "2006/01/18 02:54"

[[entries]]
no = "2"
name = "B地区"
title = "passion"
size = "4510 KB"
addr = [
    "http://www9.ocn.ne.jp/~fms/",
    "(BMS)",
    "http://www.bisuke.biz/~mikodjhiro/b_tick/",
    "(BGA)",
]
genre = "Techno"
impr = "7"
total = "2"
avg = "0.28"
regist = "2005/12/27 00:48"
update = "2006/01/18 02:59"

[[entries]]
no = "3"
name = "iimode-do"
title = "L99"
size = "11987 KB"
addr = [
    "http://iimode-do.jp/obj/l99_bga_iimo.zip",
    "(↑BGA)",
    "http://www.naotyu-studio7.com/music/data/l99.rar",
    "http://www.naotyu-studio7.com/music/data/l99.zip",
    "(↑BMS：15.3MB or 23.7MB)",
]
genre = "Progressive Fusion"
impr = "9"
total = "9"
avg = "1"
regist = "2005/12/27 00:52"
update = "2006/05/14 23:40"

[[entries]]
no = "4"
name = "JiNG*da*LaW"
title = "Eida,change of clothes"
size = "150 KB"
addr = ["http://nekomimi.ws/~iemitsu/ecoc.rar"]
genre = "RAVE"
impr = "9"
total = "0"
avg = "0"
regist = "2005/12/27 00:53"
update = "2006/01/17 04:45"

[[entries]]
no = "5"
name = "fity"
title = "Arcadia"
size = "10050 KB"
addr = ["http://www.h4.dion.ne.jp/~fity/bga_HQ_arcadia.rar"]
genre = "tribal pop"
impr = "11"
total = "4"
avg = "0.36"
regist = "2005/12/27 00:53"
update = "2006/01/17 04:59"

[[entries]]
no = "6"
name = "ALPHARD(murasin)"
title = "SAKURA"
size = "14000 KB"
addr = [
    "http://titans-server.ddo.jp/titansweb/mura/sakura_bga.zip",
    "（bgaのみ)",
    "http://titans-server.ddo.jp/titansweb/mura/sakura.zip",
    "（bms代理アップ）",
]
genre = "TRANCE"
impr = "8"
total = "6"
avg = "0.75"
regist = "2005/12/27 00:53"
update = "2006/01/17 04:50"

[[entries]]
no = "7"
name = "ers"
title = "Dancer"
size = "10626 KB"
addr = [
    "http://www.geocities.jp/ers3104/bga/gfb05-6_tones-dancer.zip",
    "（右クリック保存）",
    "http://ers3104.hp.infoseek.co.jp/bga/gfb05-6_tones-dancer.zip",
    "（ミラー）",
]
genre = "LIQUID FUNK"
impr = "12"
total = "12"
avg = "1"
regist = "2005/12/27 00:54"
update = "2006/01/18 01:22"

[[entries]]
no = "8"
name = "zit"
title = "Emerald Green"
size = "2700 KB"
addr = [
    "http://www.geocities.jp/rf_mirai/",
    "(BMS)",
    "http://bisuke.biz/~digizliar/zit_eg_bga.zip",
    "(BGA)",
]
genre = "Instrumental"
impr = "11"
total = "0"
avg = "0"
regist = "2005/12/27 00:55"
update = "2006/01/18 01:21"

[[entries]]
no = "9"
name = "cyclia"
title = "kioku [unconnected]"
size = "4794 KB"
addr = [
    "http://atmbzk.s56.xrea.com/",
    "(BMS本体はATMBZK氏のサイトから)",
    "http://big.freett.com/vtr901/cy-kuc-hq.rar",
    "(高画質版 32M)",
    "http://big.freett.com/vtr901/cy-kuc-lq.rar",
    "(低画質版 4M)",
]
genre = "Experimental (remixed)"
impr = "9"
total = "6"
avg = "0.66"
regist = "2005/12/27 00:55"
update = "2006/01/17 05:02"

[[entries]]
no = "10"
name = "mxk"
title = "Arcadia"
size = "33772 KB"
addr = ["http://www.sequensizer.org/bga/mira_arcadia.zip"]
genre = "tribal pop"
impr = "8"
total = "2"
avg = "0.25"
regist = "2005/12/27 00:56"
update = "2008/09/12 13:19"

[[entries]]
no = "11"
name = "140"
title = "Liberte -SuperSaw Epic mix-"
size = "12516 KB"
addr = [
    "http://minamotrance.com/",
    "(BMS)",
    "http://big.freett.com/140_threebit/140Liberte_bga.rar",
    "(BGA 12.1MB)",
]
genre = "Trance"
impr = "9"
total = "7"
avg = "0.77"
regist = "2005/12/27 00:56"
update = "2006/01/18 01:24"

[[entries]]
no = "12"
name = "retu+Orda"
title = "神居古潭"
size = "40657 KB"
addr = [
    "http://www.naotyu-studio7.com/music/data/kamui_kotan.zip",
    "(40M)",
]
genre = "ユーカラ"
impr = "9"
total = "2"
avg = "0.22"
regist = "2005/12/27 00:56"
update = "2006/01/18 01:31"

[[entries]]
no = "13"
name = "sta"
title = "55"
size = "11675 KB"
addr = [
    "http://bit192.s18.xrea.com/55.zip",
    "http://bit192.s18.xrea.com/55bga.zip",
]
genre = "-"
impr = "10"
total = "4"
avg = "0.4"
regist = "2005/12/27 00:57"
update = "2006/01/17 05:07"

[[entries]]
no = "14"
name = "kazuhiro.haniuda"
title = "slope"
size = "17700 KB"
addr = [
    "http://www7a.biglobe.ne.jp/~PixelLife/bms/retu-slope-bga.zip",
    "(17M)",
]
genre = "techno"
impr = "12"
total = "8"
avg = "0.66"
regist = "2005/12/27 00:57"
update = "2006/01/17 05:10"
