[[entries]]
no = "1"
name = "あにまるいあー"
title = "でじたるわんこ"
size = "3051 KB"
addr = ["http://www.geocities.co.jp/Bookend-Christie/5687/"]
genre = "すぴーでぃー はっぴー"
impr = "14"
total = "13"
avg = "0.92"
update = "2002/09/08 11:44"

[[entries]]
no = "2"
name = "PEASE MAN"
title = "my happy overheat！"
size = "3650 KB"
addr = ["http://www.geocities.co.jp/Playtown-Queen/1094/my_happy_overheat.zip"]
genre = "Happy hardcore"
impr = "13"
total = "20"
avg = "1.53"
update = "2002/09/09 15:59"

[[entries]]
no = "3"
name = "sept-em"
title = "Dream Travel"
size = "2182 KB"
addr = ["http://isweb39.infoseek.co.jp/diary/k_chitos/drtr.rar"]
genre = "Happy Dream Core"
impr = "14"
total = "15"
avg = "1.07"
update = "2002/09/09 02:33"

[[entries]]
no = "4"
name = "765→Playerβ"
title = "HAPPY MAPPY"
size = "1347 KB"
addr = ["http://sound.jp/ptf/mapicore.rar"]
genre = "MAPPY HARDCORE"
impr = "15"
total = "22"
avg = "1.46"
update = "2002/09/09 12:12"

[[entries]]
no = "5"
name = "ciel-son-terre"
title = "consider nothing (C4-CST MIX)"
size = "395 KB"
addr = ["http://manbow.nothing.sh/behappy_bms/cnc4.zip"]
genre = "TECHNYO POP"
impr = "17"
total = "22"
avg = "1.29"
update = "2002/09/09 01:39"

[[entries]]
no = "6"
name = "シロマル"
title = "White Expression"
size = "1700 KB"
addr = ["http://manbow.nothing.sh/behappy_bms/white_expression.rar"]
genre = "happy hardcore"
impr = "14"
total = "19"
avg = "1.35"
update = "2002/09/09 01:40"

[[entries]]
no = "7"
name = "sept-em"
title = "rainbow world"
size = "2759 KB"
addr = ["http://"]
genre = "HAPPY"
impr = "11"
total = "9"
avg = "0.81"
update = "2002/09/11 22:38"

[[entries]]
no = "8"
name = "N255（fether）"
title = "HappyCoreChocobo"
size = "732 KB"
addr = ["http://www.kcnet.ne.jp/~hyuri/f-6th/"]
genre = "Happy Pop Core"
impr = "19"
total = "37"
avg = "1.94"
update = "2003/08/01 14:30"

[[entries]]
no = "9"
name = "ひさんなつじ → Yamajet"
title = "Before the dawn"
size = "3433 KB"
addr = ["http://manbow.nothing.sh/behappy_bms/dawn.rar"]
genre = "HAPPY HARDCORE"
impr = "22"
total = "34"
avg = "1.54"
update = "2002/09/09 08:02"

[[entries]]
no = "10"
name = "feather→-45/裏吉川"
title = "コンバットピクミン"
size = "1358 KB"
addr = ["http://www.manbow.nothing.sh/behappy_bms/combat_picmin.rar"]
genre = "Happy"
impr = "17"
total = "25"
avg = "1.47"
update = "2002/09/09 10:14"

[[entries]]
no = "11"
name = "テクノイZ→srack"
title = "Long time randing"
size = "4720 KB"
addr = ["http://members6.tsukaeru.net/siru/ltr.zip"]
genre = "HAPPY HARD CORE"
impr = "31"
total = "46"
avg = "1.48"
update = "2002/09/09 01:25"

[[entries]]
no = "12"
name = "ぱにっくあたっく"
title = "幸せ家族"
size = "2340 KB"
addr = ["http://"]
genre = "HAPPY HARDCORE"
impr = "15"
total = "18"
avg = "1.2"
update = "2002/09/09 00:28"

[[entries]]
no = "13"
name = "nez=snow drop"
title = "That's the style!!"
size = "3450 KB"
addr = ["http://isweb45.infoseek.co.jp/art/eden_soa/tts.rar"]
genre = "Happy HardCore"
impr = "25"
total = "45"
avg = "1.8"
update = "2002/09/09 02:14"

[[entries]]
no = "14"
name = "えるのべ→ＳＨＩＫＩでした。"
title = "Promise of the ”19”"
size = "3969 KB"
addr = ["http://www.aa.alpha-net.ne.jp/linker/bms.htm"]
genre = "CANDY POP CORE"
impr = "26"
total = "45"
avg = "1.73"
update = "2002/09/09 02:21"

[[entries]]
no = "15"
name = "831 → RUZEEA"
title = "831_P929"
size = "4044 KB"
addr = ["http://sound.jp/831"]
genre = "rapid pop"
impr = "14"
total = "23"
avg = "1.64"
update = "2002/09/09 02:11"

[[entries]]
no = "16"
name = "Y.Z.R."
title = "Unknown quantity"
size = "3260 KB"
addr = ["http://isweb42.infoseek.co.jp/art/yuzuru03/main/BMS/Unknown_Y.rar"]
genre = "HAPPY LOUNGE"
impr = "12"
total = "12"
avg = "1"
update = "2002/09/08 21:09"

[[entries]]
no = "17"
name = "AAA→Playerβ"
title = "Snowmouse Race"
size = "1470 KB"
addr = ["http://manbow.nothing.sh/behappy_bms/snowmouse.rar"]
genre = "HAPPY HARDCORE"
impr = "9"
total = "6"
avg = "0.66"
update = "2002/09/09 12:15"

[[entries]]
no = "18"
name = "AOJiRU_Manbow (narve)"
title = "seaside party"
size = "6895 KB"
addr = ["http://members.tripod.co.jp/dt6359/"]
genre = "happy hardcore"
impr = "19"
total = "32"
avg = "1.68"
update = "2002/09/09 02:26"

[[entries]]
no = "19"
name = "(dsk)war-taro→sanan"
title = "”oh，vaca”ｔｉｏｎ"
size = "1034 KB"
addr = ["http://osaka.cool.ne.jp/xspace/"]
genre = "happy hardcore"
impr = "8"
total = "6"
avg = "0.75"
update = "2002/09/09 22:58"

[[entries]]
no = "20"
name = "㌔㍉"
title = "脳内フォーマット"
size = "2500 KB"
addr = ["http://sun.freehost.ne.jp/~shun/date/bms/dairi/format.html"]
genre = "HAPPY CORE"
impr = "15"
total = "10"
avg = "0.66"
update = "2002/09/09 00:08"

[[entries]]
no = "21"
name = "シャン・ツン"
title = "FRIENDSHIP"
size = "2644 KB"
addr = ["http://www.interq.or.jp/green/mokiti/onngaku/friendship.rar"]
genre = "HAPPY HARDKORE"
impr = "11"
total = "11"
avg = "1"
update = "2002/09/08 21:51"

[[entries]]
no = "22"
name = "tapoo→ojo"
title = "flower garden"
size = "6620 KB"
addr = ["http://w2222.nsk.ne.jp/~yoyoyo/flower_garden.lzh"]
genre = "happy"
impr = "11"
total = "11"
avg = "1"
update = "2002/09/09 21:57"

[[entries]]
no = "23"
name = "Sam-Rai→Coco"
title = "sea paradise"
size = "1660 KB"
addr = ["http://isweb43.infoseek.co.jp/computer/yryouta/seahappy.zip"]
genre = "HAPPY HARDCORE"
impr = "10"
total = "8"
avg = "0.8"
update = "2002/09/09 22:17"

[[entries]]
no = "24"
name = "chocolate max【ささくれ夕雁(*^3^)ﾉ☆】"
title = "★SweeT DiscoverY★"
size = "3207 KB"
addr = ["http://sound.jp/50288/sweetdiscovery.zip"]
genre = "HappY PoPcorN"
impr = "35"
total = "68"
avg = "1.94"
update = "2002/09/09 01:19"

[[entries]]
no = "25"
name = "PSYPHA"
title = "mushroom temptation"
size = "4834 KB"
addr = ["http://www.aya.or.jp/~naga/mushroomTemptation.zip"]
genre = "HappyHardGoa"
impr = "10"
total = "17"
avg = "1.7"
update = "2002/09/11 10:52"

[[entries]]
no = "26"
name = "AOiRO_Manbow feat. NO/CHS"
title = "magicalian(仮称)"
size = "2270 KB"
addr = ["http://manbow.nothing.sh/behappy_bms/magicalian.rar"]
genre = "ﾆｾHAPPY HARDCORE"
impr = "11"
total = "10"
avg = "0.9"
update = "2002/09/09 02:15"

[[entries]]
no = "27"
name = "14 feat. 379&4L → MASAKI feat. 4○&ciel-son-terre"
title = "Ｂ・Ｌ・Ｍ"
size = "2429 KB"
addr = ["http://isweb40.infoseek.co.jp/art/ratsyrt/blm.lzh"]
genre = "happy hard pop"
impr = "16"
total = "19"
avg = "1.18"
update = "2002/09/09 12:39"

[[entries]]
no = "28"
name = "sampling masters ㍉ → URL参照"
title = "Pre-Have"
size = "3000 KB"
addr = ["http://isweb45.infoseek.co.jp/art/eden_soa/prehav1.rar"]
genre = "HappyHardCore"
impr = "8"
total = "2"
avg = "0.25"
update = "2002/09/10 16:14"

[[entries]]
no = "29"
name = "´ー｀)ﾉ"
title = "8bit island"
size = "2639 KB"
addr = ["http://isweb39.infoseek.co.jp/art/msz_gao/8i.zip"]
genre = "Speed Pop"
impr = "9"
total = "10"
avg = "1.11"
update = "2002/09/12 02:26"
