[[entries]]
no = "1"
name = "ねこみりん"
title = "Shanghai, 33rd teahouse"
size = "1080 KB"
addr = [
    "MQ(rar)",
    "http://freett.com/nekomimimaid/bms/nekomirin_shanghai.rar",
    "(1080KB)",
    "MQ(zip)",
    "http://www.geocities.jp/nekomimimaid_ryo/bms/nekomirin_shanghai.zip",
    "(1380KB)",
    "※全て右クリックからDLをお願いします。",
]
genre = "Click House"
impr = "21"
total = "29"
avg = "1.38"
regist = "2006/03/25 00:02"
update = "2006/04/05 00:50"

[[entries]]
no = "2"
name = "sun3"
title = "Ancient Memory"
size = "14000 KB"
addr = ["http://succinicacid.hp.infoseek.co.jp/BMS36.html"]
genre = "Ancient beats"
impr = "20"
total = "46"
avg = "2.3"
regist = "2006/03/25 00:03"
update = "2006/04/05 21:18"

[[entries]]
no = "3"
name = "N-island-K"
title = "夢-見"
size = "10000 KB"
addr = ["http://www.geocities.jp/nkk_o_saka1329/yume-mi.zip"]
genre = "Dream Ambient"
impr = "17"
total = "41"
avg = "2.41"
regist = "2006/03/25 00:31"
update = "2006/04/02 23:54"

[[entries]]
no = "4"
name = "天音"
title = "Beyond The Alice"
size = "5000 KB"
addr = ["http://youzyo.net/bms/ama02_17alice.zip"]
genre = "WORLD / ELECTRONICA"
impr = "19"
total = "39"
avg = "2.05"
regist = "2006/03/25 00:57"
update = "2006/04/02 23:45"

[[entries]]
no = "5"
name = "ONI-GUNSOU"
title = "Power Judgment"
size = "33000 KB"
addr = ["http://www.mistbell.com//private/PJ.zip"]
genre = "Hard Core"
impr = "18"
total = "33"
avg = "1.83"
regist = "2006/03/26 04:56"
update = "2006/04/02 23:47"

[[entries]]
no = "6"
name = "izna"
title = "恋色☆ユーロスパーク"
size = "13250 KB"
addr = [
    "http://izmizm.sakura.ne.jp/bms/ms.rar",
    "(rar版 13250KB)",
    "http://izmizm.sakura.ne.jp/bms/ms.zip",
    "(zip版 15740KB)",
]
genre = "EURO BEAT"
impr = "17"
total = "30"
avg = "1.76"
regist = "2006/03/26 09:09"
update = "2006/04/09 02:13"

[[entries]]
no = "7"
name = "tkz-"
title = "裁判沙汰"
size = "6846 KB"
addr = ["あんまり消されるような物長々と置いとくのも何なんで公開停止します。"]
genre = "さもしいテクノ"
impr = "12"
total = "9"
avg = "0.75"
regist = "2006/03/26 15:26"
update = "2006/04/03 18:00"

[[entries]]
no = "8"
name = "OS"
title = "上海紅茶館 - time of dusk -"
size = "6537 KB"
addr = ["http://try-up.hp.infoseek.co.jp/BMS/O_TouhouBMS.rar"]
genre = "Game Music"
impr = "22"
total = "52"
avg = "2.36"
regist = "2006/03/26 20:12"
update = "2006/04/02 23:54"

[[entries]]
no = "9"
name = "ルゼ"
title = "gray flower"
size = "2670 KB"
addr = [
    "[RAR形式]",
    "http://www.bisuke.biz/~mikodjhiro/music/28_grayflower_lq.rar",
    "http://www.bisuke.biz/~mikodjhiro/music/28_grayflower_ogg.rar",
    "[ZIP形式]",
    "http://www.bisuke.biz/~mikodjhiro/music/28_grayflower_lq.zip",
    "http://www.bisuke.biz/~mikodjhiro/music/28_grayflower_ogg.zip",
]
genre = "TECHNO"
impr = "18"
total = "32"
avg = "1.77"
regist = "2006/03/26 23:07"
update = "2006/04/02 23:46"

[[entries]]
no = "10"
name = "Spelunker"
title = "リグル・モーニング(774 EDIT)"
size = "14886 KB"
addr = ["http://www.slk-9888.com/slk_wm.zip"]
genre = "TECHNO POP"
impr = "13"
total = "22"
avg = "1.69"
regist = "2006/03/26 23:20"
update = "2006/04/04 06:22"

[[entries]]
no = "11"
name = "plastic"
title = "うどんげぇじ"
size = "5079 KB"
addr = [
    "http://placase.bms.ms/data/bms/pla_udon.rar",
    "http://placase.bms.ms/data/bms/pla_udon_hq.rar",
    "ミラー",
    "http://close-place.hp.infoseek.co.jp/pla_udon.zip",
    "http://close-place.hp.infoseek.co.jp/pla_udon_hq.rar",
    "追加譜面（難しいor簡単すぎな方はどうぞ）",
    "http://close-place.hp.infoseek.co.jp/pla_udon_s.zip",
    "＾３＾",
    "http://close-place.sakura.ne.jp/udon.jpg",
]
genre = "ORIENT NU-STYLE GABBER"
impr = "23"
total = "47"
avg = "2.04"
regist = "2006/03/26 23:21"
update = "2006/04/17 06:15"

[[entries]]
no = "12"
name = "D_es"
title = "Eastern Night(extract)"
size = "7640 KB"
addr = ["http://deviceone.hp.infoseek.co.jp/EN_ex.zip"]
genre = "TRANCE"
impr = "12"
total = "13"
avg = "1.08"
regist = "2006/03/26 23:24"
update = "2006/04/02 23:52"

[[entries]]
no = "13"
name = "七草多粥"
title = "サウザンテイルズ"
size = "27000 KB"
addr = ["http://page.freett.com/madblast/"]
genre = "Nostalcore"
impr = "18"
total = "35"
avg = "1.94"
regist = "2006/03/26 23:40"
update = "2006/04/02 23:53"

[[entries]]
no = "14"
name = "LUNE"
title = "御伽の国の萃香様"
size = "7207 KB"
addr = ["http://rin.s101.xrea.com/suica.zip"]
genre = "-"
impr = "15"
total = "32"
avg = "2.13"
regist = "2006/03/26 23:53"
update = "2006/04/03 18:46"

[[entries]]
no = "15"
name = "MKT"
title = "Synthsized full moon"
size = "16876 KB"
addr = [
    "(MQ:5656kb)",
    "http://prsq.hp.infoseek.co.jp/data/fullmoon_bms.rar",
    "(HQ:13195kb)",
    "http://prsq.hp.infoseek.co.jp/data/fullmoon_hq.rar",
    "(イベント時にDLした人用の差分）",
    "http://prsq.hp.infoseek.co.jp/data/fullmoon_sabun.zip",
]
genre = "Synthsized Techno"
impr = "14"
total = "29"
avg = "2.07"
regist = "2006/03/26 23:54"
update = "2006/04/08 05:42"

[[entries]]
no = "16"
name = "Needle Valley"
title = "U.N.O. (Hip-Hop Mix)"
size = "5600 KB"
addr = ["http://www.geocities.jp/needle_valleys/toho.html"]
genre = "HIP HOP REMIX"
impr = "21"
total = "53"
avg = "2.52"
regist = "2006/03/26 23:55"
update = "2006/04/02 23:55"

[[entries]]
no = "17"
name = "hishin"
title = "プラスチックマインド-育つノイズ-"
size = "5137 KB"
addr = ["http://freett.com/hishin300/"]
genre = "ILLBIENT"
impr = "19"
total = "55"
avg = "2.89"
regist = "2006/03/26 23:57"
update = "2006/04/03 00:07"

[[entries]]
no = "18"
name = "Octa the B.G."
title = "o2is"
size = "5148 KB"
addr = ["http://www3.pf-x.net/~boxism-8500/bms/o2is/o2is.htm"]
genre = "techno"
impr = "13"
total = "35"
avg = "2.69"
regist = "2006/03/26 23:59"
update = "2006/04/10 03:47"

[[entries]]
no = "19"
name = "otokaz"
title = "月と時計の使者 まじかる☆さくや"
size = "8303 KB"
addr = [
    "http://www.pleades.com/~oto/data/oto09_sakuya_mq.zip",
    "(MQ版:8.3MB)",
    "http://www.pleades.com/~oto/data/oto09_sakuya_hq.zip",
    "(HQ版:35.0MB)",
    "http://www.ismusic.ne.jp/kagetora/mirror/oto09_sakuya_mq.rar",
    "(ミラーMQrar版:5.4MB)",
    "http://www.ismusic.ne.jp/kagetora/mirror/oto09_sakuya_hq.rar",
    "(ミラーHQrar版:25.3MB)",
]
genre = "Magical Pop"
impr = "19"
total = "38"
avg = "2"
regist = "2006/03/26 23:59"
update = "2006/04/02 23:56"

[[entries]]
no = "20"
name = "Ｆ／Ａ１８"
title = "シンデレラケージ ～ Kagome-Kagome ～"
size = "9100 KB"
addr = ["http://www3.ocn.ne.jp/~fa18/"]
genre = "Game Music"
impr = "10"
total = "13"
avg = "1.3"
regist = "2006/03/30 03:55"
update = "2006/04/02 23:57"
