[[entries]]
no = "1"
name = "L-more"
title = "abaddon"
size = "1900 KB"
addr = ["http://sound.jp/poxymize/oden/"]
genre = "Hard Breaks"
impr = "6"
total = "6"
avg = "1"
regist = "2006/05/30 00:03"
update = "2006/06/09 22:51"

[[entries]]
no = "2"
name = "guna"
title = "Lamellibrachia"
size = "4889 KB"
addr = ["http://nothing.sh/%7eliz/ridis/lamellibrachia.rar"]
genre = "instrumental"
impr = "8"
total = "8"
avg = "1"
regist = "2006/05/30 00:20"
update = "2006/06/10 23:59"

[[entries]]
no = "3"
name = "ねこみりん"
title = "Sadistic energy"
size = "3307 KB"
addr = [
    "http://nekomimi.bms.ms/mp3/sadistic_energy.mp3",
    "※MP3ファイルですので保存は「右クリック⇒対象をファイルに保存」からどうぞ。",
]
genre = "Psychedelic Techno"
impr = "3"
total = "3"
avg = "1"
regist = "2006/05/30 01:25"
update = "2006/06/04 11:56"

[[entries]]
no = "4"
name = "tetu"
title = "Qliece"
size = "5124 KB"
addr = [
    "http://magamiyuuya.hp.infoseek.co.jp/Qliece.mp3",
    "BMSではないのでDLは「右クリック→対象をファイルに保存」でお願いします。",
]
genre = "Old Sound Trance"
impr = "4"
total = "4"
avg = "1"
regist = "2006/05/30 07:08"
update = "2006/06/10 23:57"

[[entries]]
no = "5"
name = "Toti"
title = "浴室の壁に貼り付いた無数のトビウオ"
size = "11222 KB"
addr = ["http://8.pro.tok2.com/~toti/mp3/Cypselurus.rar"]
genre = "EXPERIMENTAL"
impr = "12"
total = "12"
avg = "1"
regist = "2006/05/30 21:40"
update = "2006/06/09 23:22"

[[entries]]
no = "6"
name = "kurenaissance"
title = "JECT"
size = "2295 KB"
addr = ["http://kure-na.hp.infoseek.co.jp/"]
genre = "Techno"
impr = "3"
total = "3"
avg = "1"
regist = "2006/05/31 02:06"
update = "2006/06/06 19:03"

[[entries]]
no = "7"
name = "サルダイン"
title = "Boost and Leave -short version-"
size = "1617 KB"
addr = ["http://kabyi-ie.hp.infoseek.co.jp/music/b_and_l.zip"]
genre = "Drum'n Bass"
impr = "3"
total = "3"
avg = "1"
regist = "2006/05/31 02:09"
update = "2006/06/15 20:26"

[[entries]]
no = "8"
name = "えふ"
title = "触手のモリ"
size = "2716 KB"
addr = ["http://www.ismusic.ne.jp/fms/tentax.htm"]
genre = "Techno"
impr = "5"
total = "5"
avg = "1"
regist = "2006/05/31 18:13"
update = "2006/06/10 00:06"

[[entries]]
no = "9"
name = "Cres"
title = "brutal stalker"
size = "4287 KB"
addr = ["http://crescent.nm.land.to/data/brutal_stalker.mp3"]
genre = "Hard House"
impr = "4"
total = "4"
avg = "1"
regist = "2006/05/31 19:32"
update = "2006/06/10 11:43"

[[entries]]
no = "10"
name = "cacono"
title = "Octribe"
size = "3328 KB"
addr = ["http://colorsign.hp.infoseek.co.jp/octribe-originalmix3.mp3"]
genre = "Techno"
impr = "4"
total = "4"
avg = "1"
regist = "2006/05/31 22:23"
update = "2006/06/10 00:40"

[[entries]]
no = "11"
name = "にゃーん（えちぃ）"
title = "a tentacle"
size = "2848 KB"
addr = [
    "■下の注意をよく読んで、同意できる方はどうぞ■",
    "http://www13.plala.or.jp/nya_n/nyan10tax.mp3",
]
genre = "Ambient"
impr = "14"
total = "14"
avg = "1"
regist = "2006/05/31 23:59"
update = "2006/06/10 23:09"

[[entries]]
no = "12"
name = "壱原侑子"
title = "檻"
size = "949 KB"
addr = ["http://tokyo.cool.ne.jp/rysu78/ori.zip"]
genre = "Avan"
impr = "6"
total = "6"
avg = "1"
regist = "2006/06/01 15:03"
update = "2006/06/10 00:14"

[[entries]]
no = "13"
name = "keyc"
title = "New Creatures"
size = "1875 KB"
addr = ["http://www001.upp.so-net.ne.jp/keyc/files/c40-NC.mp3"]
genre = "ELECTRONICA"
impr = "4"
total = "4"
avg = "1"
regist = "2006/06/01 23:19"
update = "2006/06/10 23:44"

[[entries]]
no = "14"
name = "Cybernetic Fantasy"
title = "Danced brain"
size = "4390 KB"
addr = ["http://www.geocities.jp/forcesounds/d_brain.mp3"]
genre = "Hard Trance"
impr = "3"
total = "3"
avg = "1"
regist = "2006/06/02 02:21"
update = "2006/06/05 23:34"

[[entries]]
no = "15"
name = "FMN"
title = "Coral Forest"
size = "3150 KB"
addr = ["http://fmn.kuronowish.com/coral_forest.htm"]
genre = "Techno pop?"
impr = "4"
total = "4"
avg = "1"
regist = "2006/06/02 03:36"
update = "2006/06/10 11:38"

[[entries]]
no = "16"
name = "-45"
title = "XXX multiply"
size = "7324 KB"
addr = [
    "http://malie2.hp.infoseek.co.jp/XXX_multiply.mp3",
    "http://www5.pf-x.net/~malie/archive/XXX_multiply.mp3",
]
genre = "goa"
impr = "11"
total = "11"
avg = "1"
regist = "2006/06/02 20:04"
update = "2006/06/10 23:53"

[[entries]]
no = "17"
name = "hyla a.k.a. xarva"
title = "nitestalker"
size = "8888 KB"
addr = ["http://phantomscape.in/event/10tax/nitestalker.html"]
genre = "-"
impr = "11"
total = "11"
avg = "1"
regist = "2006/06/02 22:32"
update = "2006/06/10 23:42"

[[entries]]
no = "18"
name = "D_es"
title = "wire loop"
size = "3297 KB"
addr = ["http://deviceone.hp.infoseek.co.jp/wire_loop.mp3"]
genre = "break beats"
impr = "7"
total = "7"
avg = "1"
regist = "2006/06/02 23:27"
update = "2006/06/10 23:39"

[[entries]]
no = "19"
name = "ルゼ"
title = "紫陽花の忘れ物"
size = "1785 KB"
addr = [
    "＜ogg版 2.82MB＞",
    "http://www.bisuke.biz/~mikodjhiro/music/29_tentax_ogg.rar",
    "＜lq版 1.79MB＞",
    "http://www.bisuke.biz/~mikodjhiro/music/29_tentax_lq.rar",
]
genre = "PSYCHEDELIC"
impr = "4"
total = "4"
avg = "1"
regist = "2006/06/02 23:52"
update = "2006/06/09 22:12"

[[entries]]
no = "20"
name = "Needle Valley"
title = "The close room"
size = "5000 KB"
addr = ["http://www.geocities.jp/needle_valleys/close.mp3"]
genre = "break beats"
impr = "5"
total = "5"
avg = "1"
regist = "2006/06/02 23:58"
update = "2006/06/16 01:20"
