[[entries]]
no = "1"
name = "noritama"
title = "Check it out"
size = "825 KB"
addr = ["http://www.geocities.jp/djsyouta/noritama.zip"]
genre = "college techno"
impr = "7"
total = "17"
avg = "2.42"
regist = "2006/06/17 00:02"
update = "2006/06/24 08:52"

[[entries]]
no = "2"
name = "ドラゴンボール"
title = "ドラゴンボール"
size = "223 KB"
addr = ["http://gyaon.sakura.ne.jp/bms/g_dbdb.rar"]
genre = "ドラゴンボール"
impr = "12"
total = "53"
avg = "4.41"
regist = "2006/06/17 00:05"
update = "2006/06/26 07:22"

[[entries]]
no = "4"
name = "Elyts Assault X"
title = "MAX300 -mechanical mix-"
size = "94 KB"
addr = ["http://d3mix.x0.com/mystyle/bms/max300_reimx.zip"]
genre = "SUPER HARDCORE"
impr = "9"
total = "32"
avg = "3.55"
regist = "2006/06/17 00:12"
update = "2006/06/23 22:23"

[[entries]]
no = "5"
name = "KOH"
title = "Hetarertino in Blue"
size = "784 KB"
addr = ["http://www.geocities.jp/koh_hetarex/k_foon2006.zip"]
genre = "Progressive"
impr = "8"
total = "26"
avg = "3.25"
regist = "2006/06/17 00:13"
update = "2006/06/21 22:11"

[[entries]]
no = "6"
name = "ゆ"
title = "にゅー案セムゴアすぴーどくりっくはうし"
size = "635 KB"
addr = ["http://asdf.bms.ms/junk/bms/asdfasdfsadfasdfghcddf.zip"]
genre = "のびたラーメン諸島"
impr = "6"
total = "16"
avg = "2.66"
regist = "2006/06/17 00:15"
update = "2006/06/20 03:26"

[[entries]]
no = "7"
name = "Mr.M"
title = "DUE YESTERDAY"
size = "271 KB"
addr = ["http://www.geocities.jp/rf_mirai/bms/2006/m0601_due_yesterday.zip"]
genre = "TECHNO"
impr = "5"
total = "15"
avg = "3"
regist = "2006/06/17 00:16"
update = "2006/06/23 21:13"

[[entries]]
no = "8"
name = "DJ Lemon"
title = "Space x-x-x"
size = "221 KB"
addr = ["http://www.ztv.ne.jp/iekmf2ar/868.zip"]
genre = "Space"
impr = "5"
total = "11"
avg = "2.2"
regist = "2006/06/17 00:18"
update = "2006/06/26 00:02"

[[entries]]
no = "9"
name = "Lemo"
title = "level-nine"
size = "495 KB"
addr = ["http://www.ztv.ne.jp/iekmf2ar/asso-.zip"]
genre = "bug area"
impr = "5"
total = "17"
avg = "3.4"
regist = "2006/06/17 00:21"
update = "2006/06/26 00:00"

[[entries]]
no = "10"
name = "Nick"
title = "代々木ゼミナール"
size = "465 KB"
addr = ["http://nick.xxxxxxxx.jp/yozemi.lzh"]
genre = "CM SONG"
impr = "19"
total = "52"
avg = "2.73"
regist = "2006/06/17 00:23"
update = "2006/06/22 01:16"

[[entries]]
no = "11"
name = "真実の愛の探求者ドキンちゃんことでぃあぶろ"
title = "真実の愛の探求者ドキンちゃんことでぃあぶろ"
size = "933 KB"
addr = ["http://www.geocities.jp/nkk_o_saka1329/dia.zip"]
genre = "drum'n bass"
impr = "5"
total = "13"
avg = "2.6"
regist = "2006/06/17 00:41"
update = "2006/06/20 14:19"

[[entries]]
no = "12"
name = "る"
title = "夢精 第二楽章"
size = "1310 KB"
addr = ["http://www.geocities.jp/gensoukyousoukyoku/ichigo.zip"]
genre = "trance"
impr = "13"
total = "49"
avg = "3.76"
regist = "2006/06/17 01:05"
update = "2006/06/23 22:56"

[[entries]]
no = "13"
name = "もるさん"
title = "紅い空 (original mix)"
size = "5410 KB"
addr = ["http://plaza.rakuten.co.jp/mol300/"]
genre = "ARPEGGIO TECHNO"
impr = "7"
total = "17"
avg = "2.42"
regist = "2006/06/17 01:05"
update = "2006/06/27 22:20"

[[entries]]
no = "14"
name = "白紙の巻物"
title = "宇宙の真理について考える曲"
size = "4580 KB"
addr = ["http://www.bisuke.biz/~mikodjhiro/temp/cosmo.rar"]
genre = "じゃず"
impr = "4"
total = "12"
avg = "3"
regist = "2006/06/17 02:45"
update = "2006/06/20 14:23"

[[entries]]
no = "15"
name = "#268"
title = "ZERO-ONE"
size = "445 KB"
addr = ["http://"]
genre = "ELECTROSHOCK"
impr = "17"
total = "55"
avg = "3.23"
regist = "2006/06/17 03:00"
update = "2006/06/26 00:10"

[[entries]]
no = "16"
name = "NECO Assault X"
title = "The ﾀﾞﾝﾃﾞｨｰ of Loudness"
size = "4160 KB"
addr = [
    "http://nekomimi.bms.ms/bms/necox_dandy.zip",
    "(5140KB)",
    "つ期間限定／",
    "http://nekomimi.bms.ms/temp/dandy.txt",
]
genre = "ダンディズムハードこア"
impr = "28"
total = "77"
avg = "2.75"
regist = "2006/06/17 03:27"
update = "2006/07/03 01:56"

[[entries]]
no = "17"
name = "ねこふんじやtt"
title = "ねこふんじやtt"
size = "230 KB"
addr = ["http://www.geocities.co.jp/muku39_ryu/nya-.zip"]
genre = "ねこふんじやtt"
impr = "5"
total = "14"
avg = "2.8"
regist = "2006/06/17 03:53"
update = "2006/06/20 22:13"

[[entries]]
no = "18"
name = "DJ MONMAS"
title = "KONAKiC-2k6ライヴバージョン(Multiple personality unit mix)"
size = "5740 KB"
addr = ["http://hitujimura.hp.infoseek.co.jp/kasou.html"]
genre = "日本盤のみのボーナストラック"
impr = "6"
total = "13"
avg = "2.16"
regist = "2006/06/17 04:02"
update = "2006/06/25 23:13"

[[entries]]
no = "19"
name = "('дゝ｀)"
title = "練習した結果"
size = "5 KB"
addr = ["http://wakimata0rz.hp.infoseek.co.jp/BMS/a.zip"]
genre = "あれから一年"
impr = "10"
total = "39"
avg = "3.9"
regist = "2006/06/17 05:40"
update = "2006/06/22 15:36"

[[entries]]
no = "20"
name = "知らないおじさん"
title = "テーマオブふーん（第一夜）"
size = "550 KB"
addr = ["削除したよ☆"]
genre = "みんなのちから（無断借用）"
impr = "3"
total = "10"
avg = "3.33"
regist = "2006/06/17 05:59"
update = "2006/06/26 00:14"

[[entries]]
no = "21"
name = "(´дゝ｀)"
title = "三作品同梱"
size = "325 KB"
addr = ["http://wakimata0rz.hp.infoseek.co.jp/BMS/b.rar"]
genre = "昔流行った替え歌"
impr = "5"
total = "18"
avg = "3.6"
regist = "2006/06/17 06:48"
update = "2006/06/22 15:33"

[[entries]]
no = "22"
name = "Jack"
title = "ファッキンガムパレス"
size = "625 KB"
addr = ["http://kure-na.hp.infoseek.co.jp/fuck.html"]
genre = "DEATH METAL"
impr = "6"
total = "17"
avg = "2.83"
regist = "2006/06/17 09:00"
update = "2006/06/21 21:38"

[[entries]]
no = "23"
name = "ｷ･･ｱﾄ｢屡･ﾖﾆ･･ﾄﾆﾄ"
title = "あぐらをかく"
size = "163 KB"
addr = ["http://kasamatusan.sakura.ne.jp/cgi-bin2/src/ichi40334.bza"]
genre = "日常"
impr = "5"
total = "15"
avg = "3"
regist = "2006/06/17 11:18"
update = "2006/06/21 21:54"

[[entries]]
no = "24"
name = "にゃんにゃん祭り実行委員会"
title = "にゃんにゃん祭り"
size = "212 KB"
addr = [
    "http://nagoya.cool.ne.jp/hyper880405/nyannyanmatsuri.zip",
    "【穴ザーsabun】",
    "http://nagoya.cool.ne.jp/hyper880405/huziko.zip",
]
genre = "ルール：ひたすらにゃんにゃんする"
impr = "4"
total = "11"
avg = "2.75"
regist = "2006/06/17 12:12"
update = "2006/06/22 19:27"

[[entries]]
no = "25"
name = "Gureito Drummer & Sugoi guitarist"
title = "U3"
size = "1281 KB"
addr = ["http://wonber.hp.infoseek.co.jp/dairi/u3.rar"]
genre = "EXPERIMENTAL ROCK"
impr = "7"
total = "28"
avg = "4"
regist = "2006/06/17 13:37"
update = "2006/06/22 00:00"

[[entries]]
no = "26"
name = "無限"
title = "無限ループってこわくね？"
size = "145 KB"
addr = ["http://akiba.geocities.jp/mugen_kowai/mugen.zip"]
genre = "hiphop"
impr = "5"
total = "11"
avg = "2.2"
regist = "2006/06/17 14:57"
update = "2006/06/23 00:14"

[[entries]]
no = "27"
name = "Titsh"
title = "Genius -I- (なまえをいれてください)"
size = "87 KB"
addr = ["http://asdf.uh-oh.jp/_.zip"]
genre = "CYBER OPUS"
impr = "6"
total = "20"
avg = "3.33"
regist = "2006/06/17 15:32"
update = "2006/06/24 09:08"

[[entries]]
no = "28"
name = "某えるもあ好きの人"
title = "L More Lovely"
size = "2212 KB"
addr = ["http://www9.ocn.ne.jp/~singo-s/Flying_on_IGR.rar"]
genre = "MAKINA"
impr = "4"
total = "10"
avg = "2.5"
regist = "2006/06/17 16:34"
update = "2006/06/25 23:20"

[[entries]]
no = "29"
name = "リポビタンＺ"
title = "NEMUI"
size = "1250 KB"
addr = ["http://erotyabin.gotdns.com/user/erotyabin/cgi/uproda/img/upsf002998.zip"]
genre = "新曲"
impr = "7"
total = "32"
avg = "4.57"
regist = "2006/06/17 17:15"
update = "2006/06/26 18:01"

[[entries]]
no = "30"
name = "Amano Jack"
title = "曲。"
size = "1787 KB"
addr = ["http://www.geocities.jp/needle_valleys/bofoon2006.html"]
genre = "わかりません。"
impr = "4"
total = "12"
avg = "3"
regist = "2006/06/17 18:20"
update = "2006/06/21 23:47"

[[entries]]
no = "31"
name = "NOVA+R"
title = "duihill"
size = "4490 KB"
addr = ["http://rasuku.s116.xrea.com/foon/download.html"]
genre = "trance"
impr = "4"
total = "15"
avg = "3.75"
regist = "2006/06/17 19:36"
update = "2006/06/24 09:02"

[[entries]]
no = "32"
name = "CM"
title = "W.H.U.3"
size = "1091 KB"
addr = ["http://www7a.biglobe.ne.jp/~cm_comac/bms/whu3.zip"]
genre = "使いまわしｗ"
impr = "7"
total = "27"
avg = "3.85"
regist = "2006/06/17 22:04"
update = "2006/06/26 06:51"

[[entries]]
no = "33"
name = "Clay-G.K"
title = ".cHAos"
size = "3841 KB"
addr = ["http://kazjp.hp.infoseek.co.jp/bms/chaos.zip"]
genre = "Depression World"
impr = "3"
total = "9"
avg = "3"
regist = "2006/06/17 22:39"
update = "2006/06/20 22:47"

[[entries]]
no = "34"
name = "SUKE"
title = "RAR"
size = "5667 KB"
addr = ["http://biznot.biz/music/rar.rar"]
genre = "ELECTRONIC"
impr = "5"
total = "8"
avg = "1.6"
regist = "2006/06/17 23:10"
update = "2006/06/22 22:41"

[[entries]]
no = "35"
name = "SUKE"
title = "Nineteen Walls"
size = "4156 KB"
addr = ["http://biznot.biz/music/19walls.zip"]
genre = "TECHNO"
impr = "6"
total = "10"
avg = "1.66"
regist = "2006/06/17 23:24"
update = "2006/06/22 22:43"

[[entries]]
no = "36"
name = "ホーネット"
title = "gunshot"
size = "570 KB"
addr = ["http://www3.ocn.ne.jp/~fa18/gunshot/gunshot.html"]
genre = "射撃日記"
impr = "3"
total = "10"
avg = "3.33"
regist = "2006/06/18 01:14"
update = "2006/06/20 22:43"

[[entries]]
no = "37"
name = "330bpm"
title = "Imperishable Katcho"
size = "1056 KB"
addr = ["http://otiko.s57.xrea.com/19.zip"]
genre = "experiment higeoyaji"
impr = "4"
total = "14"
avg = "3.5"
regist = "2006/06/18 02:20"
update = "2006/06/23 21:27"

[[entries]]
no = "38"
name = "AOiRO_Manbow"
title = "S.Z.E-R"
size = "620 KB"
addr = ["http://manbow.nothing.sh/bms/sze-r.rar"]
genre = "S.Z.E HARDCORE"
impr = "5"
total = "12"
avg = "2.4"
regist = "2006/06/18 02:57"
update = "2006/06/21 14:29"

[[entries]]
no = "39"
name = "知らないおじさん"
title = "テーマオブふーん第二夜ー今日の晩御飯はひっぷほっぷー"
size = "588 KB"
addr = ["削除したよ☆"]
genre = "みんあのちから２"
impr = "3"
total = "8"
avg = "2.66"
regist = "2006/06/18 06:07"
update = "2006/06/26 00:13"

[[entries]]
no = "40"
name = "Borragi vs Preser"
title = "痔"
size = "67 KB"
addr = ["http://www15.ocn.ne.jp/~holyca/di.rar"]
genre = "HUMAN STRRUGLE"
impr = "4"
total = "13"
avg = "3.25"
regist = "2006/06/18 06:22"
update = "2006/06/21 14:25"

[[entries]]
no = "41"
name = "未来"
title = "So Fine!"
size = "93 KB"
addr = ["http://www.geocities.jp/rf_mirai/bms/2006/m0602_so_fine.zip"]
genre = "J-POP"
impr = "10"
total = "29"
avg = "2.9"
regist = "2006/06/18 06:54"
update = "2006/06/22 02:06"

[[entries]]
no = "42"
name = "John Makura Gaeshi"
title = "2006bpm"
size = "560 KB"
addr = ["http://hitujimura.hp.infoseek.co.jp/bj7th.html"]
genre = "DANCE HAYAI"
impr = "6"
total = "11"
avg = "1.83"
regist = "2006/06/18 08:52"
update = "2006/06/24 09:17"

[[entries]]
no = "43"
name = "IkARUGA"
title = "朝青Ryu☆"
size = "534 KB"
addr = ["http://ikaruga.bms.ms/data/seiryu.rar"]
genre = "Techno"
impr = "4"
total = "13"
avg = "3.25"
regist = "2006/06/18 12:06"
update = "2006/06/21 00:15"

[[entries]]
no = "44"
name = "vol_7"
title = "dungeon.1"
size = "833 KB"
addr = ["http://www15.ocn.ne.jp/~holyca/dungeon1.rar"]
genre = "retrospection"
impr = "6"
total = "15"
avg = "2.5"
regist = "2006/06/18 13:27"
update = "2006/06/30 02:36"

[[entries]]
no = "45"
name = "たっくん"
title = "幸せのダンプカー"
size = "7500 KB"
addr = ["ttp://vegetation.o0o0.jp/pochi/src/jyuuyon14614.rar.html"]
genre = "ハッピーあんびえんと☆"
impr = "7"
total = "25"
avg = "3.57"
regist = "2006/06/18 14:22"
update = "2006/06/24 21:09"

[[entries]]
no = "46"
name = "ぷらたん"
title = "ぱんつ"
size = "5000 KB"
addr = ["http://placase.bms.ms/data/bms/pla_hafun.rar"]
genre = "とらんちゅ"
impr = "7"
total = "14"
avg = "2"
regist = "2006/06/18 16:44"
update = "2006/06/22 01:40"

[[entries]]
no = "47"
name = "(´дゝ｀)"
title = "四つ打ち命"
size = "2 KB"
addr = ["http://wakimata0rz.hp.infoseek.co.jp/BMS/4.zip"]
genre = "本家"
impr = "10"
total = "32"
avg = "3.2"
regist = "2006/06/18 19:34"
update = "2006/06/21 07:44"

[[entries]]
no = "48"
name = "BACO feat. いぬみれい"
title = "Unreal BMer"
size = "18418 KB"
addr = ["http://page.freett.com/inumimi/unreal.htm"]
genre = "DANCE SPEED"
impr = "4"
total = "10"
avg = "2.5"
regist = "2006/06/18 21:27"
update = "2006/06/22 01:46"

[[entries]]
no = "49"
name = "DJ Rickey"
title = "八零零（弐零零、四零零）"
size = "312 KB"
addr = ["http://www.geocities.jp/kira24132413/hatizerozero.zip"]
genre = "Hi-Speed"
impr = "6"
total = "19"
avg = "3.16"
regist = "2006/06/18 21:39"
update = "2006/07/29 16:22"

[[entries]]
no = "50"
name = "The Alice Team"
title = "Alice BMS"
size = "6248 KB"
addr = ["http://www.comeup.info/bofoon2006/"]
genre = "Techno"
impr = "7"
total = "21"
avg = "3"
regist = "2006/06/18 21:45"
update = "2006/06/25 23:26"

[[entries]]
no = "51"
name = "CMとソフラン大好きなコマ＋北京原人他"
title = "永遠"
size = "1946 KB"
addr = ["http://www7a.biglobe.ne.jp/~cm_comac/bms/314.zip"]
genre = "元・ラジオ日本的ピアノ協奏曲第3141592番"
impr = "5"
total = "12"
avg = "2.4"
regist = "2006/06/18 21:59"
update = "2006/06/21 23:36"

[[entries]]
no = "52"
name = "LMND"
title = "3 to 300"
size = "15 KB"
addr = ["http://www.ztv.ne.jp/iekmf2ar/3300.zip"]
genre = "Low-Hi-Speed"
impr = "4"
total = "14"
avg = "3.5"
regist = "2006/06/18 22:51"
update = "2006/06/26 00:00"

[[entries]]
no = "53"
name = "小林家"
title = "061808"
size = "316 KB"
addr = [
    "http://www3.pf-x.net/~boxism-8500/text/diary/log/2006jan.htm",
    "の18.Jan内のリンクよりDL",
    "日記はread me代わりに",
]
genre = "家族旅行"
impr = "5"
total = "16"
avg = "3.2"
regist = "2006/06/18 23:15"
update = "2006/06/22 02:10"

[[entries]]
no = "54"
name = "線引ハジメ"
title = "あなたは新しい武器を手に入れました"
size = "292 KB"
addr = ["http://www.geocities.jp/yh_tsukimi999/wehq.zip"]
genre = "100万倍の男3"
impr = "4"
total = "7"
avg = "1.75"
regist = "2006/06/18 23:39"
update = "2006/06/22 01:27"

[[entries]]
no = "55"
name = "tetsuko"
title = "楽曲案 #7"
size = "2453 KB"
addr = ["http://pokoneko.haru.gs/nekoko/bms/music7.zip"]
genre = "POP"
impr = "6"
total = "14"
avg = "2.33"
regist = "2006/06/18 23:45"
update = "2006/06/24 01:18"

[[entries]]
no = "56"
name = "Ryu☆好きな何か"
title = "青龍最高＞ｗ＜ｂ"
size = "2098 KB"
addr = ["http://clair.oh.land.to/aoryu.zip"]
genre = "ダンスすぴーどだっけ？"
impr = "7"
total = "22"
avg = "3.14"
regist = "2006/06/18 23:55"
update = "2006/06/21 14:05"

[[entries]]
no = "57"
name = "Little Pianist"
title = "fortissimo"
size = "1003 KB"
addr = ["http://www15.ocn.ne.jp/~holyca/fortissimo.rar"]
genre = "Burning SHIT"
impr = "3"
total = "9"
avg = "3"
regist = "2006/06/18 23:57"
update = "2006/06/26 00:16"

[[entries]]
no = "58"
name = "酢雀"
title = "酢雀"
size = "47 KB"
addr = ["http://www.bisuke.biz/~mikodjhiro/temp/suzaku.rar"]
genre = "doors"
impr = "4"
total = "14"
avg = "3.5"
regist = "2006/06/18 23:57"
update = "2006/06/21 00:03"

[[entries]]
no = "59"
name = "知らないおじさん"
title = "テーマオブふーん[最終夜]"
size = "860 KB"
addr = ["削除したよ☆"]
genre = "みんなのちから３"
impr = "3"
total = "8"
avg = "2.66"
regist = "2006/06/18 23:59"
update = "2006/06/26 00:13"
