[[entries]]
no = "1"
name = "ドリームグライダー"
title = "ドリームグライダー"
size = "7017 KB"
addr = ["http://prettyhamchan.hp.infoseek.co.jp/uplorder/event/dream_glider.htm"]
genre = "ドリームグライダー"
impr = "23"
total = "52"
avg = "2.26"
regist = "2006/07/01 00:00"
update = "2006/07/17 00:09"

[[entries]]
no = "2"
name = "Absolute Ego Creator"
title = "dont let quiet"
size = "4840 KB"
addr = ["http://sound.jp/aec/dl_dlq.html"]
genre = "upper house / disco techno"
impr = "21"
total = "57"
avg = "2.71"
regist = "2006/07/01 00:03"
update = "2006/07/17 02:09"

[[entries]]
no = "3"
name = "honey princess"
title = "LOVE☆BEAM (orange summer mix)"
size = "6864 KB"
addr = ["http://members3.jcom.home.ne.jp/t.moriya-nari/love_beam_os_mq.rar"]
genre = "H.H.P"
impr = "34"
total = "99"
avg = "2.91"
regist = "2006/07/01 00:04"
update = "2006/07/17 00:42"

[[entries]]
no = "4"
name = "レコレ"
title = "おるめりー らんごーど"
size = "2727 KB"
addr = [
    "[LQ]",
    "http://titans-server.ddo.jp/~murasin/dl/olmry_lq.rar",
    "(2727KB)",
    "[HQ]",
    "http://titans-server.ddo.jp/~murasin/dl/olmry_hq.rar",
    "(15.9MB)",
]
genre = "メモランド"
impr = "16"
total = "28"
avg = "1.75"
regist = "2006/07/01 00:15"
update = "2006/07/17 00:34"

[[entries]]
no = "5"
name = "Personative"
title = "How Magnificent !!"
size = "9411 KB"
addr = [
    "http://music.geocities.jp/werboontz/",
    "お手数ですが一度HTMLファイルに飛んでからあらゆる手段をつくしてDLお願いします。",
    "※ムシャクシャしたときに消す場合があるので、その場合は本サイトまでドウゾ",
    "http://www3.pf-x.net/~void/",
]
genre = "Buchiage Trance"
impr = "23"
total = "56"
avg = "2.43"
regist = "2006/07/01 00:38"
update = "2006/07/17 00:19"

[[entries]]
no = "6"
name = "MRF"
title = "Sexual Appetite"
size = "4845 KB"
addr = ["http://2nd.geocities.jp/mrf_lb/"]
genre = "Hyper Techno"
impr = "12"
total = "22"
avg = "1.83"
regist = "2006/07/01 01:16"
update = "2006/07/18 00:23"

[[entries]]
no = "7"
name = "MRF"
title = "Real Dreamer"
size = "8876 KB"
addr = ["http://2nd.geocities.jp/mrf_lb/"]
genre = "Happy Hardcore"
impr = "13"
total = "24"
avg = "1.84"
regist = "2006/07/01 01:24"
update = "2006/07/18 00:25"

[[entries]]
no = "8"
name = "Hyuji"
title = "New Start"
size = "5417 KB"
addr = ["http://www.pmeyw.com/event/new_start.zip"]
genre = "Happy Hardcore"
impr = "15"
total = "14"
avg = "0.93"
regist = "2006/07/01 01:40"
update = "2006/07/17 01:02"

[[entries]]
no = "9"
name = "Kitty Guy"
title = "Kitten Flyer"
size = "2363 KB"
addr = ["http://kitten-flyer.hp.infoseek.co.jp/kitten-flyer_lq.rar"]
genre = "Happy Hardcore"
impr = "13"
total = "19"
avg = "1.46"
regist = "2006/07/02 01:02"
update = "2006/07/16 22:46"

[[entries]]
no = "10"
name = "COH"
title = "はるかぜ"
size = "14606 KB"
addr = [
    "http://www.geocities.jp/tank_place/harukaze.zip",
    "修正しました↓上書きしてください。",
    "http://www.geocities.jp/tank_place/harukaze_syusei.zip",
]
genre = "happy trance core"
impr = "16"
total = "31"
avg = "1.93"
regist = "2006/07/02 13:49"
update = "2006/07/16 22:48"

[[entries]]
no = "11"
name = "how-mach * charm"
title = "Euphoria"
size = "5043 KB"
addr = ["http://www.comeup.info/euphoria.rar"]
genre = "Happy"
impr = "21"
total = "56"
avg = "2.66"
regist = "2006/07/02 14:19"
update = "2006/07/17 00:47"

[[entries]]
no = "12"
name = "kasuka shiraki"
title = "Sous la lune"
size = "429 KB"
addr = ["http://www.geocities.jp/shirakikasuka/sll.zip"]
genre = "House"
impr = "16"
total = "21"
avg = "1.31"
regist = "2006/07/02 15:56"
update = "2006/07/16 22:50"

[[entries]]
no = "13"
name = "corecubic"
title = "sigsigsig"
size = "4109 KB"
addr = ["http://www.geocities.jp/corecubic/index.html"]
genre = "Trance"
impr = "14"
total = "11"
avg = "0.78"
regist = "2006/07/02 19:37"
update = "2006/07/17 12:49"

[[entries]]
no = "14"
name = "kuzumi"
title = "Alti"
size = "3410 KB"
addr = ["http://www.geocities.jp/tigerkuzumi/sub.htm"]
genre = "HAPPY"
impr = "14"
total = "28"
avg = "2"
regist = "2006/07/02 20:06"
update = "2006/07/17 00:27"

[[entries]]
no = "15"
name = "ウィン"
title = "AtlanCHIs"
size = "3914 KB"
addr = ["http://nekomimi.name/behappy2/win_atlanchis.rar"]
genre = "HAPPY SUNSOFT"
impr = "18"
total = "38"
avg = "2.11"
regist = "2006/07/02 21:25"
update = "2006/07/17 17:26"

[[entries]]
no = "16"
name = "RLF"
title = "Broken Toy-CLOCK"
size = "1410 KB"
addr = ["http://tokyo.cool.ne.jp/rysu78/btc.zip"]
genre = "PSYCHEDELIC"
impr = "12"
total = "19"
avg = "1.58"
regist = "2006/07/02 21:41"
update = "2006/07/16 22:55"

[[entries]]
no = "17"
name = "サセボブラザーズ(兄)"
title = "メダパニダンス"
size = "2540 KB"
addr = ["http://yokoska.s221.xrea.com/yokosuka_medapani.rar"]
genre = "Techno"
impr = "14"
total = "35"
avg = "2.5"
regist = "2006/07/02 22:14"
update = "2006/07/16 22:56"

[[entries]]
no = "18"
name = "グレィラビット"
title = "Ground & Air"
size = "3445 KB"
addr = ["http://www.geocities.jp/djsyouta/stl_gaa.zip"]
genre = "Speed Pop"
impr = "12"
total = "10"
avg = "0.83"
regist = "2006/07/02 22:33"
update = "2006/07/17 16:16"

[[entries]]
no = "19"
name = "Tさん&Yさん"
title = "サラダ"
size = "7428 KB"
addr = ["http://www.geocities.jp/emarginaldest/index.html"]
genre = "POP'n GROOVE"
impr = "22"
total = "60"
avg = "2.72"
regist = "2006/07/02 23:07"
update = "2006/07/17 02:57"

[[entries]]
no = "20"
name = "HEHEHE"
title = "So Fabulous !! (Especially a tension !!!)"
size = "2275 KB"
addr = [
    "http://yamajet1984.net/up/hehehe_feb.zip",
    "http://yamajet1984.net/up/hehehe_feb_hq.zip",
]
genre = "BUCHIAGE HAPPYCORE"
impr = "11"
total = "12"
avg = "1.09"
regist = "2006/07/02 23:10"
update = "2006/07/16 23:00"

[[entries]]
no = "21"
name = "Lul"
title = "なつのえにっき"
size = "5068 KB"
addr = [
    "http://www.shimasan.jp/miyu/~data/enikki.zip",
    "(通常版)",
    "http://www.shimasan.jp/miyu/~data/enikki_hq.zip",
    "(HQ版 35816KB)",
]
genre = "DREAM TECHNO"
impr = "21"
total = "48"
avg = "2.28"
regist = "2006/07/02 23:15"
update = "2006/07/17 00:54"

[[entries]]
no = "22"
name = "サセボブラザーズ(いもうと)"
title = "キタベップ"
size = "4212 KB"
addr = [
    "http://yokoska.s221.xrea.com/yokosuka_imouto.rar",
    "http://yokoska.s221.xrea.com/onychaaan.rar",
    "(修正差分)",
]
genre = "Techno"
impr = "16"
total = "32"
avg = "2"
regist = "2006/07/02 23:30"
update = "2006/07/16 23:03"

[[entries]]
no = "23"
name = "234"
title = "Blue-White Crazybits"
size = "2036 KB"
addr = ["http://yamajet1984.net/up/crazybits.rar"]
genre = "HAPPY HARDCORE"
impr = "14"
total = "17"
avg = "1.21"
regist = "2006/07/02 23:47"
update = "2006/07/16 23:06"

[[entries]]
no = "24"
name = "Absolute Ego Creator"
title = "The Cosmic Wheels"
size = "7310 KB"
addr = ["http://sound.jp/aec/dl_tcw.html"]
genre = "upper house / disco techno"
impr = "14"
total = "35"
avg = "2.5"
regist = "2006/07/02 23:59"
update = "2006/07/17 02:15"

[[entries]]
no = "25"
name = "PROJECT SOM"
title = "Little Light"
size = "9030 KB"
addr = [
    "http://nekomimi.bms.ms/bms/nekomirin_ll.zip",
    "(LQ、約9MB)",
    "※HQ公開終了。サーバ提供していただいたnaotyu-先生、ありがとうございました。",
]
genre = "POP Inst"
impr = "16"
total = "28"
avg = "1.75"
regist = "2006/07/02 23:59"
update = "2006/07/17 02:28"

[[entries]]
no = "26"
name = "ノア"
title = "dreamy traveler"
size = "8572 KB"
addr = [
    "http://www.bisuke.biz/~mikodjhiro/b_hpy/dreamy_traveler.rar",
    "http://www.bisuke.biz/~mikodjhiro/b_hpy/dreamy_traveler_hq.rar",
    "(33378KB)",
    "http://www.bisuke.biz/~mikodjhiro/b_hpy/dreamy_traveler_ogg.rar",
    "(16703KB)",
]
genre = "wahoo pop"
impr = "15"
total = "36"
avg = "2.4"
regist = "2006/07/02 23:59"
update = "2006/07/17 00:58"
