[[entries]]
no = "1"
name = "KO-KO(original:nixx)"
title = "2088(phuture_remixx)"
size = "4315 KB"
addr = ["http://venocity.web.fc2.com/2088.htm"]
genre = "mixture"
impr = "15"
total = "21"
avg = "1.4"
regist = "2006/07/15 00:01"
update = "2006/07/23 22:30"

[[entries]]
no = "2"
name = "HOUJIROU"
title = "心 乱 恐 旋"
size = "5755 KB"
addr = ["http://page.freett.com/takacyan930/sinran_dlpage.html"]
genre = "Classical Hard Techno"
impr = "11"
total = "6"
avg = "0.54"
regist = "2006/07/15 00:10"
update = "2006/07/23 22:33"

[[entries]]
no = "3"
name = "sumomo"
title = "絶望と破壊のソネタ"
size = "1970 KB"
addr = ["http://r866761.hp.infoseek.co.jp/bms/takost_soneta.rar"]
genre = "Horror Instrumental"
impr = "11"
total = "3"
avg = "0.27"
regist = "2006/07/15 00:18"
update = "2006/07/25 14:26"

[[entries]]
no = "4"
name = "HAL*"
title = "EXiST (radio edit)"
size = "9402 KB"
addr = ["http://das-buch.tank.jp/hal-on/EXiST-re-.zip"]
genre = "TRANCE"
impr = "12"
total = "13"
avg = "1.08"
regist = "2006/07/15 00:20"
update = "2006/07/23 22:37"

[[entries]]
no = "5"
name = "N-island-K"
title = "Sie werden Zauberin"
size = "2127 KB"
addr = ["http://www.geocities.jp/nkk_o_saka1329/sie.zip"]
genre = "Schwarzer Ritus"
impr = "13"
total = "15"
avg = "1.15"
regist = "2006/07/15 02:05"
update = "2006/07/23 22:42"

[[entries]]
no = "6"
name = "sept"
title = "Extinction and reproduction#2"
size = "2362 KB"
addr = ["http://stnspr.hp.infoseek.co.jp/eve2006.html"]
genre = "-"
impr = "9"
total = "6"
avg = "0.66"
regist = "2006/07/15 11:14"
update = "2006/07/23 22:43"

[[entries]]
no = "7"
name = "LU"
title = "faucet"
size = "1124 KB"
addr = ["http://www.geocities.jp/gensoukyousoukyoku/faucet.zip"]
genre = "darkstep"
impr = "15"
total = "17"
avg = "1.13"
regist = "2006/07/15 14:40"
update = "2006/07/23 22:46"

[[entries]]
no = "8"
name = "L4M"
title = "TESTAROSSA"
size = "4126 KB"
addr = ["http://as01-iidx.ddo.jp/testarossa.zip"]
genre = "FREEFORM"
impr = "13"
total = "6"
avg = "0.46"
regist = "2006/07/15 14:48"
update = "2006/07/23 23:14"

[[entries]]
no = "9"
name = "void"
title = "Verzweiflung"
size = "5296 KB"
addr = ["http://www3.pf-x.net/~void/verzweiflung.html"]
genre = "Goa Breaks"
impr = "10"
total = "13"
avg = "1.3"
regist = "2006/07/15 18:09"
update = "2006/07/24 00:13"

[[entries]]
no = "10"
name = "wave life"
title = "曇天翔空"
size = "4831 KB"
addr = [
    "http://music.geocities.jp/wave_life_g/donten_high.zip",
    "[33.6MB]",
    "http://music.geocities.jp/wave_life_g/donten_low.zip",
    "[4.8MB]",
]
genre = "minimal / drum'n'bass"
impr = "9"
total = "7"
avg = "0.77"
regist = "2006/07/16 00:09"
update = "2006/07/24 00:05"

[[entries]]
no = "11"
name = "NOVA+R"
title = "iruka"
size = "4120 KB"
addr = ["http://rasuku.s116.xrea.com/bms/nova_iruka.rar"]
genre = "Ambient"
impr = "9"
total = "9"
avg = "1"
regist = "2006/07/16 02:52"
update = "2006/07/23 22:52"

[[entries]]
no = "12"
name = "ominous"
title = "Dutch courage"
size = "3751 KB"
addr = ["http://www.geocities.jp/panda_bms/"]
genre = "newstyle"
impr = "19"
total = "34"
avg = "1.78"
regist = "2006/07/16 06:51"
update = "2006/07/23 22:53"

[[entries]]
no = "13"
name = "Dragovic Boobsski"
title = "ハカイノイデンシ-E.O.T.W.mix-"
size = "603 KB"
addr = ["http://lionel.hp.infoseek.co.jp/event_dl.html"]
genre = "TRANCE"
impr = "11"
total = "4"
avg = "0.36"
regist = "2006/07/16 17:06"
update = "2006/07/23 22:55"

[[entries]]
no = "14"
name = "COH"
title = "North Pole"
size = "7054 KB"
addr = [
    "LQ 版",
    "http://www.geocities.jp/tank_place/north_pole_LQ.zip",
    "MQ 版",
    "http://www.geocities.jp/tank_place/north_pole_MQ.zip",
]
genre = "Trance"
impr = "8"
total = "6"
avg = "0.75"
regist = "2006/07/16 18:42"
update = "2006/07/23 22:56"

[[entries]]
no = "15"
name = "simesaba"
title = "ニガサナイ"
size = "3624 KB"
addr = ["http://home.v08.itscom.net/yanagi/bms/saba_panic.rar"]
genre = "Panic House"
impr = "13"
total = "0"
avg = "0"
regist = "2006/07/16 23:57"
update = "2006/07/23 22:58"

[[entries]]
no = "16"
name = "-"
title = "輪切りのLolita"
size = "5865 KB"
addr = ["http://o-n-na-no-ko.hp.infoseek.co.jp/lolita.zip"]
genre = "-"
impr = "17"
total = "29"
avg = "1.7"
regist = "2006/07/16 23:58"
update = "2006/07/23 22:59"

[[entries]]
no = "17"
name = "Needle Valley"
title = "Grudge ～怨塊～"
size = "4110 KB"
addr = ["http://www.geocities.jp/needle_valleys/dark.html"]
genre = "TERROR CORE"
impr = "17"
total = "20"
avg = "1.17"
regist = "2006/07/16 23:58"
update = "2006/07/23 23:01"

[[entries]]
no = "18"
name = "morigasigeru with atomic sphere"
title = "ロボット"
size = "27758 KB"
addr = ["http://sound.jp/takelove/robot.html"]
genre = "EXPERIMENTAL"
impr = "18"
total = "29"
avg = "1.61"
regist = "2006/07/16 23:59"
update = "2006/07/23 23:05"
