[[entries]]
no = "1"
name = "カレーの幼女様(10辛)"
title = "ふわふわだよ？"
size = "14480 KB"
addr = [
    "http://asdf.bms.ms/bof/curryyojo_fuwafuwa.rar",
    "(BMS/wav/LQ/rar) (14480KB)",
    "http://asdf.bms.ms/bof/curryyojo_fuwafuwa.zip",
    "(BMS/wav/LQ/zip) (17780KB)",
    "http://asdf.bms.ms/bof/curryyojo_fuwafuwa_ogg.rar",
    "(BMS/ogg/HQ/rar) (9205KB)",
    "http://asdf.bms.ms/bof/curryyojo_fuwafuwa_mv.rar",
    "(MOVIE/mpg/rar) (14537KB)",
]
genre = "プレリュード"
impr = "4"
total = "--"
median = "--"
avg = "--"
regist = "2006/07/16 03:06"
update = "2006/08/04 03:21"

[[entries]]
no = "2"
name = "ケポパジツカタニバ"
title = "おなか"
size = "1360 KB"
addr = ["http://zrk.bms.ms/popos/kepo_onaka.mp3"]
genre = "Electronica"
impr = "1"
total = "--"
median = "--"
avg = "--"
regist = "2006/07/17 14:11"
update = "2006/07/23 02:37"

[[entries]]
no = "3"
name = "けもみみメイドカフェ"
title = "ちーむ・ぷろもーしょん"
size = "20268 KB"
addr = ["http://kemomimimaid.dip.jp/kemomimi_bof.mpg"]
genre = "ぷろもーしょんむーびー"
impr = "0"
total = "--"
median = "--"
avg = "--"
regist = "2006/07/18 04:33"
update = "2006/07/22 18:15"

[[entries]]
no = "4"
name = "廃人工房"
title = "RAISIN' MY DESIRE(short)"
size = "933 KB"
addr = ["ttp://music.geocities.jp/myaku_389/RAISIN_MY_DESIRE_short.mp3"]
genre = "Eurobeat"
impr = "0"
total = "--"
median = "--"
avg = "--"
regist = "2006/07/19 06:50"
update = "2006/07/30 05:18"

[[entries]]
no = "5"
name = "Cut/Work"
title = "ハルノオワリ"
size = "4000 KB"
addr = [
    "http://stage6.divx.com/members/108834/videos/1016210",
    "(Divx Stage6)",
    "http://video.google.com/videoplay?docid=5429129963021481348",
    "(Google Video)",
]
genre = "Movie"
impr = "4"
total = "--"
median = "--"
avg = "--"
regist = "2006/07/20 02:30"
update = "2006/10/01 03:52"

[[entries]]
no = "6"
name = "残念だよ。"
title = "T & D"
size = "1405 KB"
addr = ["http://g-g-station.web.infoseek.co.jp/music/mp3/Team_Zannenndayo_T&D.mp3"]
genre = "ART CORE / SYMPHONIC HARD TECHNO"
impr = "1"
total = "--"
median = "--"
avg = "--"
regist = "2006/07/20 23:55"
update = "2006/07/26 01:05"

[[entries]]
no = "7"
name = "(大量発生！)チームゴキブリ"
title = "ゴキッティッド"
size = "15612 KB"
addr = [
    "http://www.grooveforest.net/team_gokiburi.zip",
    "ミラー",
    "http://anseie.ath.cx/dexhip/data/team_gokiburi.zip",
]
genre = "HIPHOP"
impr = "5"
total = "--"
median = "--"
avg = "--"
regist = "2006/07/21 00:44"
update = "2006/07/29 17:35"

[[entries]]
no = "8"
name = "らぴすらずりさんとそのお友達"
title = "Memory in childhood"
size = "3654 KB"
addr = ["http://www.rinku.zaq.ne.jp/makky/Memory_in_childhood.mp3"]
genre = "Piano solo"
impr = "1"
total = "--"
median = "--"
avg = "--"
regist = "2006/07/22 01:09"
update = "2006/07/25 19:21"

[[entries]]
no = "9"
name = "NU RICE"
title = "crossfade"
size = "1040 KB"
addr = ["http://calcretes-style.com/crossfade_new_rice.mp3"]
genre = "いろいろ"
impr = "2"
total = "--"
median = "--"
avg = "--"
regist = "2006/07/22 01:58"
update = "2006/08/01 12:25"

[[entries]]
no = "10"
name = "THE THIRD 陳PACT"
title = "the 3rd"
size = "1376 KB"
addr = ["http://3rd.geocities.jp/third_chimpact/"]
genre = "demo"
impr = "2"
total = "--"
median = "--"
avg = "--"
regist = "2006/07/22 04:08"
update = "2006/08/05 02:49"

[[entries]]
no = "11"
name = "三次元"
title = "魘 -Introduction-"
size = "7706 KB"
addr = ["http://yamada300.web.fc2.com/page.htm"]
genre = "Before Battle"
impr = "2"
total = "--"
median = "--"
avg = "--"
regist = "2006/07/22 19:04"
update = "2006/08/02 01:58"

[[entries]]
no = "12"
name = "信号"
title = "想う壺～ジンジャーフロウ～advance blue"
size = "10221 KB"
addr = ["http://singou.s224.xrea.com/_singou.rar"]
genre = "TECHNO"
impr = "4"
total = "--"
median = "--"
avg = "--"
regist = "2006/07/22 21:54"
update = "2006/07/29 17:39"

[[entries]]
no = "13"
name = "Druggy's Acid RacK"
title = "Druggy's Acid RacK BOF 2006 前哨戦"
size = "1174 KB"
addr = ["http://www30.tok2.com/home/lv4/darkbof2006.mp3"]
genre = "Hard core mix"
impr = "2"
total = "--"
median = "--"
avg = "--"
regist = "2006/07/22 22:15"
update = "2006/07/25 02:11"

[[entries]]
no = "14"
name = "hopeless erotic box"
title = "VINYL BLENDER"
size = "9777 KB"
addr = ["http://biznot.biz/works/BOF/index.html"]
genre = "HARD TECHNO MIX"
impr = "8"
total = "--"
median = "--"
avg = "--"
regist = "2006/07/22 23:15"
update = "2006/08/05 23:58"

[[entries]]
no = "15"
name = "ポッポーズ"
title = "POPPO TRACKS"
size = "4598 KB"
addr = ["http://8.pro.tok2.com/~toti/bof2006/poppo_tracks.rar"]
genre = "MIX"
impr = "0"
total = "--"
median = "--"
avg = "--"
regist = "2006/07/22 23:41"
update = "2006/07/23 00:25"

[[entries]]
no = "16"
name = "atomic sphere team"
title = "waterman"
size = "17000 KB"
addr = ["http://anseie.ath.cx/atomicsphere/_bms/atomicsphere_waterman_sp.zip"]
genre = "jazzstep"
impr = "4"
total = "--"
median = "--"
avg = "--"
regist = "2006/07/23 00:04"
update = "2006/07/29 17:44"

[[entries]]
no = "17"
name = "The Kusofumen Tower"
title = "（＾＾）Shooting"
size = "6821 KB"
addr = ["http://wonber.hp.infoseek.co.jp/dairi/shooting.rar"]
genre = "GAME"
impr = "1"
total = "--"
median = "--"
avg = "--"
regist = "2006/07/23 03:38"
update = "2006/07/23 11:11"

[[entries]]
no = "18"
name = "soundDeMP"
title = "Information from soundDeMP"
size = "2840 KB"
addr = [
    "http://nekomimi.bms.ms/bms/Info_from_soundDeMP.zip",
    "(BMS/2840KB)",
    "http://nekomimi.bms.ms/mp3/Info_from_soundDeMP.mp3",
    "(MP3/ 452KB)",
]
genre = "Radiotic Info"
impr = "4"
total = "--"
median = "--"
avg = "--"
regist = "2006/07/23 05:46"
update = "2006/07/29 17:50"

[[entries]]
no = "19"
name = "ラムバム製作プロジェクト（仮）"
title = "アンケートにお答え下さい"
size = "3686 KB"
addr = ["http://hitujimura.hp.infoseek.co.jp/foon.html"]
genre = "SAMPLE2000"
impr = "6"
total = "--"
median = "--"
avg = "--"
regist = "2006/07/23 09:00"
update = "2006/08/06 02:11"

[[entries]]
no = "20"
name = "triospect"
title = "Synthesized Resonance"
size = "9122 KB"
addr = ["http://kure-na.hp.infoseek.co.jp/demo.html"]
genre = "triospect composed"
impr = "1"
total = "--"
median = "--"
avg = "--"
regist = "2006/07/23 18:22"
update = "2006/07/29 17:47"

[[entries]]
no = "21"
name = "psychedelia"
title = "psychedelia.mpg"
size = "27270 KB"
addr = ["http://www.sound.jp/sunset_flower/psychedelia/"]
genre = "PSYCHEDELIC"
impr = "2"
total = "--"
median = "--"
avg = "--"
regist = "2006/07/23 18:48"
update = "2006/08/01 12:40"

[[entries]]
no = "22"
name = "w e i s s - w i e - e i n"
title = "w e i s s - w i e - e i n ( c r o s s f a d e)"
size = "2654 KB"
addr = ["http://void-z.hp.infoseek.co.jp/weiss-wie-ein.mp3"]
genre = "Experimental / Electronica / Progressive"
impr = "0"
total = "--"
median = "--"
avg = "--"
regist = "2006/07/23 19:40"
update = "2006/07/23 19:40"

[[entries]]
no = "23"
name = "bright⇔darkness"
title = "bright⇔darkness"
size = "2325 KB"
addr = ["http://big.freett.com/bright_darkness/b_d.mp3"]
genre = "team introduction"
impr = "0"
total = "--"
median = "--"
avg = "--"
regist = "2006/07/23 19:47"
update = "2006/08/08 21:58"

[[entries]]
no = "24"
name = "いろいろいろいろいろいろいろいろいろ"
title = "aurora town"
size = "3140 KB"
addr = ["http://kaikou.nothing.sh/auroratown.mp3"]
genre = "オーロラウンジ"
impr = "2"
total = "--"
median = "--"
avg = "--"
regist = "2006/07/23 23:53"
update = "2006/07/27 22:58"
