[[entries]]
no = "1"
name = "ke"
title = "feedpoint#03"
size = "3840 KB"
addr = [
    "http://www.geocities.jp/seek_mejp/ke_feedpoint03_bga_lq.zip",
    "http://moonshine.yh.land.to/ke_feedpoint03_bga_lq.zip",
    "どちらのアドレスも同じファイルです",
]
genre = "hard techno"
impr = "7"
total = "7"
avg = "1"
regist = "2006/09/17 00:37"
update = "2006/10/07 23:56"

[[entries]]
no = "2"
name = "fity/spine"
title = "forest"
size = "5720 KB"
addr = ["http://www.h4.dion.ne.jp/~fity/kepo_spine_forest_bga.rar"]
genre = "fractal beats"
impr = "8"
total = "8"
avg = "1"
regist = "2006/09/27 11:12"
update = "2006/10/07 23:39"

[[entries]]
no = "3"
name = "wandering light / spine"
title = "forest"
size = "2136 KB"
addr = [
    "http://www.planetoid.biz/bms/wl_forest_bgalq.rar",
    "(LQ 2136KB)",
    "http://www.planetoid.biz/bms/wl_forest_bgahq.rar",
    "(HQ 5795KB)",
]
genre = "fractal beats"
impr = "6"
total = "6"
avg = "1"
regist = "2006/09/30 00:16"
update = "2006/10/07 23:20"

[[entries]]
no = "5"
name = "iimode-do@X-JAPONICA"
title = "VIP ～飛べない俺はただのｸﾏｰ～"
size = "14052 KB"
addr = [
    "http://iimode-do.jp/obj/iimo_vip_bga.zip",
    "(右クリック→対象をファイルに保存 を推奨)",
    "BGAのみのパッケージです｡BMSは透ける・t・鋼鉄者氏のDLページ",
    "http://page.freett.com/wakimata_sabu/vipbm.html",
    "↑からDLしてください｡",
]
genre = "VISUAL SHOCK"
impr = "6"
total = "6"
avg = "1"
regist = "2006/09/30 23:12"
update = "2006/10/08 00:27"
