[[entries]]
no = "1"
name = "Playerβ"
title = "Activation"
size = "21 KB"
addr = ["http://a-p.cside.ne.jp/files/activation.zip"]
genre = "eurobeat"
impr = "4"
total = "4"
avg = "1"
regist = "2007/01/04 14:05"
update = "2007/01/18 10:34"

[[entries]]
no = "2"
name = "ブチュチュンパ"
title = "teke"
size = "540 KB"
addr = [
    "http://page.freett.com/woody_/teke.zip",
    "右クリックで保存お願いします。",
]
genre = "hard house"
impr = "6"
total = "6"
avg = "1"
regist = "2007/01/06 17:52"
update = "2007/02/18 15:28"

[[entries]]
no = "3"
name = "樟"
title = "Le Fou"
size = "1042 KB"
addr = ["http://www.geocities.jp/shirakikasuka/lefou.zip"]
genre = "Floor"
impr = "4"
total = "4"
avg = "1"
regist = "2007/01/07 18:24"
update = "2007/02/18 15:31"

[[entries]]
no = "4"
name = "通りすがり"
title = "orangegirl sentiment '07"
size = "6 KB"
addr = [
    "http://otoge.is.land.to/sarashi/img/396.zip",
    "(no objet)",
    "http://otoge.is.land.to/sarashi/img/399.zip",
    "(★７)",
]
genre = "pops"
impr = "5"
total = "5"
avg = "1"
regist = "2007/01/14 19:24"
update = "2007/02/18 16:13"

[[entries]]
no = "5"
name = "Needle Valley"
title = "Freeee Dom"
size = "287 KB"
addr = [
    "http://page.freett.com/needle_valley/bms/freedom.rar",
    "※右クリック⇒⇒保存でお願いします。",
]
genre = "HAPPY"
impr = "6"
total = "6"
avg = "1"
regist = "2007/01/16 00:25"
update = "2007/02/18 16:13"

[[entries]]
no = "6"
name = "KIREJI"
title = "SCORN"
size = "5294 KB"
addr = [
    "http://djugg.hp.infoseek.co.jp/scorn.rar",
    "http://djugg.hp.infoseek.co.jp/scornlq.rar",
]
genre = "DANCE"
impr = "2"
total = "2"
avg = "1"
regist = "2007/01/17 16:01"
update = "2007/02/18 16:13"

[[entries]]
no = "7"
name = "ka2o"
title = "Angelic Layer-14KEYS-"
size = "9 KB"
addr = [
    "BMS本体",
    "http://kobe.cool.ne.jp/linker/",
    "BMS差分",
    "http://longleguncle.hp.infoseek.co.jp/angelic14.zip",
]
genre = "trance"
impr = "1"
total = "1"
avg = "1"
regist = "2007/01/29 19:06"
update = "2007/02/18 16:14"

[[entries]]
no = "8"
name = "Obj Tech Lovers"
title = "Obj Tech Lovers"
size = "2765 KB"
addr = ["http://nekokan.dyndns.info/~otlovers/"]
genre = "SITE"
impr = "1"
total = "1"
avg = "1"
regist = "2007/02/12 21:51"
update = "2007/02/18 16:14"
