[[entries]]
no = "1"
name = "KIREJI"
title = "一月一日"
size = "2767 KB"
addr = [
    "http://djugg.hp.infoseek.co.jp/kireji_1_1.zip",
    "http://djugg.hp.infoseek.co.jp/kireji_1_1lq.zip",
]
genre = "2007"
impr = "10"
total = "9"
avg = "0.9"
regist = "2007/01/01 03:42"
update = "2007/02/10 01:47"

[[entries]]
no = "2"
name = "syzfonics"
title = "Digital White"
size = "15336 KB"
addr = ["http://sound.jp/syzf/4th.html"]
genre = "Trance"
impr = "6"
total = "10"
avg = "1.66"
regist = "2007/01/02 00:29"
update = "2007/01/09 00:09"

[[entries]]
no = "3"
name = "4G"
title = "play that game plan"
size = "1622 KB"
addr = ["http://www7a.biglobe.ne.jp/~furiefurie/bms/gameplan.rar"]
genre = "BIG BEAT"
impr = "7"
total = "11"
avg = "1.57"
regist = "2007/01/02 10:32"
update = "2007/01/15 23:24"

[[entries]]
no = "4"
name = "Vospi"
title = "Snow Stream"
size = "15906 KB"
addr = ["http://vospi.bemafia.ru/files/simfiles/iidx/%5BBMS%5D%20Snow%20Stream-LQ.rar"]
genre = "Light Dnb"
impr = "12"
total = "34"
avg = "2.83"
regist = "2007/01/05 10:57"
update = "2007/02/10 02:20"

[[entries]]
no = "5"
name = "s.m.Niko"
title = "TT BEAT IT re.mix"
size = "4718 KB"
addr = ["http://124.34.229.34:81/servlet/M302/bbs/129373/img/0049665319.zip"]
genre = "Trance"
impr = "7"
total = "4"
avg = "0.57"
regist = "2007/01/05 18:40"
update = "2007/01/14 03:50"

[[entries]]
no = "6"
name = "Ｆ／Ａ１８"
title = "Facing to Death -FAITH TOTAL MACHINE-"
size = "6200 KB"
addr = ["http://www3.ocn.ne.jp/~fa18/"]
genre = "Game Music (聖剣伝説３)"
impr = "5"
total = "12"
avg = "2.4"
regist = "2007/01/07 01:59"
update = "2007/01/10 22:02"

[[entries]]
no = "7"
name = "Gatia"
title = "Grand Prairies"
size = "3288 KB"
addr = ["http://kobagame.hp.infoseek.co.jp/bms/prairies.zip"]
genre = "Trance"
impr = "6"
total = "9"
avg = "1.5"
regist = "2007/01/07 13:18"
update = "2007/01/18 22:51"

[[entries]]
no = "8"
name = "ウル"
title = "月まで届け、不死の煙"
size = "3949 KB"
addr = ["http://terminalvelocity.hp.infoseek.co.jp/cgi-bin/dcnt/dcnt.cgi?n=10"]
genre = "Game Music(東方永夜抄)"
impr = "4"
total = "4"
avg = "1"
regist = "2007/01/07 13:24"
update = "2007/01/17 00:34"

[[entries]]
no = "9"
name = "Re:cycle"
title = "Gloomy Needl"
size = "3394 KB"
addr = ["http://www.geocities.jp/akatsuki_520/Glomy_Needl.zip"]
genre = "minimal"
impr = "5"
total = "7"
avg = "1.4"
regist = "2007/01/08 21:30"
update = "2007/02/20 16:30"

[[entries]]
no = "10"
name = "Playerβ"
title = "Techno Objects"
size = "2 KB"
addr = ["http://a-p.cside.ne.jp/files/techno_object.zip"]
genre = "BMS rhythm score"
impr = "9"
total = "7"
avg = "0.77"
regist = "2007/01/09 00:57"
update = "2007/01/18 13:32"

[[entries]]
no = "11"
name = "d__t"
title = "zT-STRaS"
size = "1920 KB"
addr = ["http://nekokan.dyndns.info/~anonymous/2ch/zT.zip"]
genre = "ELECTRONICA"
impr = "10"
total = "23"
avg = "2.3"
regist = "2007/01/10 02:51"
update = "2007/02/17 18:58"

[[entries]]
no = "12"
name = "MIAO"
title = "HARD STYLE"
size = "3572 KB"
addr = ["http://bulub.com/data/hs_lq.zip"]
genre = "drum n bass"
impr = "5"
total = "13"
avg = "2.6"
regist = "2007/01/10 18:56"
update = "2007/02/17 18:59"

[[entries]]
no = "13"
name = "MIAO"
title = "marginary collecting"
size = "2319 KB"
addr = ["http://bulub.com/data/mc_lq.zip"]
genre = "glitched house"
impr = "3"
total = "6"
avg = "2"
regist = "2007/01/11 03:21"
update = "2007/02/17 18:59"

[[entries]]
no = "14"
name = "eir"
title = "eve (solstice mix)"
size = "47244 KB"
addr = [
    "http://sunsetclouds.ddo.jp:/atmosphere/eir_eve_lq.rar",
    "http://sunsetclouds.ddo.jp:/atmosphere/eir_eve_hq.rar",
]
genre = "instrumental"
impr = "8"
total = "23"
avg = "2.87"
regist = "2007/01/11 10:14"
update = "2007/02/17 19:00"

[[entries]]
no = "15"
name = "みちくさ"
title = "魔降臨連鎖概説"
size = "8155 KB"
addr = ["http://bmsup.web.fc2.com/"]
genre = "GAME MUSIC"
impr = "6"
total = "14"
avg = "2.33"
regist = "2007/01/14 23:19"
update = "2007/02/17 19:02"

[[entries]]
no = "16"
name = "Black"
title = "Windows System"
size = "820 KB"
addr = ["http://kobagame.hp.infoseek.co.jp/bms/windows.zip"]
genre = "Techno"
impr = "1"
total = "3"
avg = "3"
regist = "2007/01/25 14:08"
update = "2007/02/17 19:04"

[[entries]]
no = "17"
name = "wata"
title = "Flying with..."
size = "22497 KB"
addr = [
    "http://www.sohmatoa.com/bms/flyhq.zip",
    "(HQ 73MB)",
    "http://www.sohmatoa.com/bms/flymq.zip",
    "(MQ 22MB)",
    "http://www.sohmatoa.com/bms/flywavmq.zip",
    "(MQ BGA無し 15MB)",
    "http://www.sohmatoa.com/bms/flywavlq.zip",
    "(LQ BGA無し 4MB)",
    "http://www.sohmatoa.com/bms/fly_bga_lq.zip",
    "(BGA 6MB)",
]
genre = "Break beats"
impr = "7"
total = "19"
avg = "2.71"
regist = "2007/01/28 16:33"
update = "2007/02/18 15:11"

[[entries]]
no = "18"
name = "Needle Valley"
title = "Flea"
size = "58 KB"
addr = [
    "http://page.freett.com/needle_valley/bms/flea.rar",
    "ZIP版もあります＾＾",
    "http://page.freett.com/needle_valley/bms/flea.zip",
    "(82KB)",
    "※右クリック⇒保存でお願いします！",
]
genre = "HARD STEP"
impr = "5"
total = "12"
avg = "2.4"
regist = "2007/01/30 03:27"
update = "2007/02/18 15:12"

[[entries]]
no = "19"
name = "HAL*"
title = "20,January"
size = "12366 KB"
addr = ["http://www7.tok2.com/home/ionwater/bms/HAL-20January.zip"]
genre = "HOUSE"
impr = "3"
total = "6"
avg = "2"
regist = "2007/02/03 16:20"
update = "2007/02/18 15:14"

[[entries]]
no = "20"
name = "Estfeat.小宮真央"
title = "Relative -アメツチノウタ-"
size = "13324 KB"
addr = [
    "http://estish.hp.infoseek.co.jp/bms/relative.zip",
    "(13M)",
    "http://estish.hp.infoseek.co.jp/bms/relative_ogg.zip",
    "(ogg版 7M)",
]
genre = "TRANCE"
impr = "4"
total = "10"
avg = "2.5"
regist = "2007/02/03 20:36"
update = "2007/02/18 15:14"

[[entries]]
no = "21"
name = "Ym1024"
title = "Light Heart"
size = "5000 KB"
addr = ["http://members.at.infoseek.co.jp/Ym1024/bms/ym05_light.rar"]
genre = "Rock'n Pop"
impr = "2"
total = "5"
avg = "2.5"
regist = "2007/02/08 22:01"
update = "2007/02/18 15:14"

[[entries]]
no = "22"
name = "t-plain"
title = "Sunlight Yard"
size = "1976 KB"
addr = ["http://playerb-web.hp.infoseek.co.jp/files/SunlightYard.rar"]
genre = "speed popcore"
impr = "2"
total = "6"
avg = "3"
regist = "2007/02/09 00:17"
update = "2007/02/16 00:14"

[[entries]]
no = "23"
name = "s.m.Niko"
title = "輪廻"
size = "2560 KB"
addr = ["http://124.38.234.170:81/servlet/M302/bbs/129373/img/0053935576.zip"]
genre = "Techno"
impr = "2"
total = "2"
avg = "1"
regist = "2007/02/10 18:32"
update = "2007/02/18 15:15"
