[[entries]]
no = "1"
name = "9 0 8 / BGA:tutidama"
title = "d r i v i n ' I C"
size = "3860 KB"
addr = ["http://sazanka.sakura.ne.jp/~2tdm/tutidama_drivinIC.rar"]
genre = "t e c h n o"
impr = "5"
total = "5"
avg = "1"
update = "2002/10/26 16:54"

[[entries]]
no = "2"
name = "MILK // BGA:66"
title = "Lost World"
size = "2930 KB"
addr = ["http://www.eonet.ne.jp/~ciel-son-terre/bga/66_lostbga.rar"]
genre = "euro trance"
impr = "5"
total = "5"
avg = "1"
update = "2002/10/23 12:30"

[[entries]]
no = "3"
name = "908/BGA:140"
title = "driven'IC"
size = "3730 KB"
addr = ["http://www.geocities.co.jp/Playtown-Bishop/1864/140_drivnBGA.zip"]
genre = "t e c h n o"
impr = "5"
total = "5"
avg = "1"
update = "2002/10/31 20:58"

[[entries]]
no = "4"
name = "908 + 117@G.S.M"
title = "drivin'IC"
size = "2841 KB"
addr = ["http://www.geocities.co.jp/MusicStar-Percussion/1943/117_drivinIC.lzh"]
genre = "t e c h n o"
impr = "2"
total = "2"
avg = "1"
update = "2002/10/29 23:09"
