[[entries]]
no = "1"
name = "Ym1024"
title = "Fallen Leaves"
size = "17500 KB"
addr = ["http://members.at.infoseek.co.jp/Ym1024/bms/ym04_leaves.rar"]
genre = "Jazz Waltz"
impr = "15"
total = "36"
avg = "2.4"
regist = "2007/01/20 00:01"
update = "2007/02/06 00:59"

[[entries]]
no = "2"
name = "celas"
title = "廃屋の闇"
size = "32413 KB"
addr = [
    "DLページ",
    "http://bm2dx.dip.jp/creation/bms/",
    "通常版(HQ@RAR) 31.6MB",
    "http://bm2dx.dip.jp/creation/bms/darkhouse.rar",
    "通常版(HQ@ZIP) 49.2MB",
    "http://bm2dx.dip.jp/creation/bms/darkhouse.zip",
    "低音質版(MQ@RAR) 16.8MB",
    "http://bm2dx.dip.jp/creation/bms/darkhouse_mq.rar",
    "低音質版(MQ@ZIP) 23.3MB",
    "http://bm2dx.dip.jp/creation/bms/darkhouse_mq.zip",
]
genre = "drum'n bass"
impr = "12"
total = "23"
avg = "1.91"
regist = "2007/01/20 00:02"
update = "2007/02/05 23:36"

[[entries]]
no = "3"
name = "dust.c"
title = "Orange jam reqiem for 2jankies"
size = "4570 KB"
addr = [
    "http://music.geocities.jp/dustccc/orangejam.html",
    "http://dustc.biz/bms/dust-2ch_hq.zip",
    "[HQ 15MBぐらい]",
]
genre = "I think maybe they aren't breakcore"
impr = "27"
total = "57"
avg = "2.11"
regist = "2007/01/20 00:09"
update = "2007/02/06 19:19"

[[entries]]
no = "4"
name = "KOH"
title = "on the cloud"
size = "9247 KB"
addr = ["http://www.geocities.jp/koh_hetarex/k_otc.zip"]
genre = "Trance"
impr = "7"
total = "11"
avg = "1.57"
regist = "2007/01/20 00:14"
update = "2007/02/05 23:39"

[[entries]]
no = "5"
name = "4G"
title = "キオクノハネ"
size = "9111 KB"
addr = [
    "zip形式:8.89MB",
    "http://www7a.biglobe.ne.jp/~furiefurie/mumeibms/hane.zip",
    "rar形式:7.11MB",
    "http://www7a.biglobe.ne.jp/~furiefurie/mumeibms/hane.rar",
]
genre = "CELTIC TECHNO"
impr = "11"
total = "25"
avg = "2.27"
regist = "2007/01/20 00:29"
update = "2007/02/05 23:43"

[[entries]]
no = "6"
name = "MSA2"
title = "After the tragedy"
size = "7472 KB"
addr = [
    "http://page.freett.com/mbemsa2/index.htm",
    "※直リンクは無理な鯖でした＾＾；",
    "サイトのほうから御願いします。お手数おかけして申し訳ございません",
]
genre = "Rotteldam Techno"
impr = "8"
total = "9"
avg = "1.12"
regist = "2007/01/20 01:06"
update = "2007/02/05 23:41"

[[entries]]
no = "7"
name = "SHiNKA"
title = "Trans"
size = "8536 KB"
addr = [
    "http://shinka-cb.sakura.ne.jp/shi_trans.htm",
    "※ダウンロードページに飛びます",
]
genre = "Trance"
impr = "16"
total = "36"
avg = "2.25"
regist = "2007/01/20 01:33"
update = "2007/02/04 21:00"

[[entries]]
no = "8"
name = "S.in"
title = "蟲師"
size = "13782 KB"
addr = [
    "http://splfly.mireene.com/bmsfile/chungsa_lq.zip",
    "http://splfly.mireene.com/bmsfile/chungsa_mq.zip",
    "http://splfly.mireene.com/bmsfile/chungsa_mq.rar",
    "(こちらが圧縮用量が小さいからお勧めします)",
    "http://user.chol.com/~djbd/chungsa_lq.zip",
    "(if traffic over)",
]
genre = "Tribal"
impr = "10"
total = "24"
avg = "2.4"
regist = "2007/01/20 02:03"
update = "2007/02/03 23:24"

[[entries]]
no = "9"
name = "N-island-K"
title = "Fate..."
size = "6679 KB"
addr = [
    "http://big.freett.com/t59g59/N-island-K",
    "[Fate...].rar",
]
genre = "dramatic"
impr = "6"
total = "11"
avg = "1.83"
regist = "2007/01/20 02:07"
update = "2007/02/03 17:36"

[[entries]]
no = "10"
name = "サルダイン"
title = "SKY JUMP!!"
size = "2516 KB"
addr = ["http://kabyi-ie.hp.infoseek.co.jp/music/skyjump.zip"]
genre = "Happy Hardcore"
impr = "10"
total = "8"
avg = "0.8"
regist = "2007/01/20 02:11"
update = "2007/02/08 19:58"

[[entries]]
no = "11"
name = "HOUJIROU"
title = "舞姫 ～buki～"
size = "10444 KB"
addr = ["http://page.freett.com/takacyan930/ev_dlpage.html"]
genre = "JP-S RAVE"
impr = "25"
total = "74"
avg = "2.96"
regist = "2007/01/20 08:43"
update = "2007/02/05 23:11"

[[entries]]
no = "12"
name = "ELE-G"
title = "Vinegar"
size = "4050 KB"
addr = ["no bms"]
genre = "ELECTRONICA"
impr = "11"
total = "22"
avg = "2"
regist = "2007/01/20 12:18"
update = "2007/02/08 07:26"

[[entries]]
no = "13"
name = "sun3"
title = "そらのむこう pop swing mix"
size = "8000 KB"
addr = ["http://succinicacid.hp.infoseek.co.jp/mumei_07.html"]
genre = "SYNTH POP"
impr = "9"
total = "20"
avg = "2.22"
regist = "2007/01/20 12:39"
update = "2007/02/03 01:51"

[[entries]]
no = "14"
name = "DEMK"
title = "Heaven's world"
size = "5103 KB"
addr = ["http://demk.net/Heaven'sworld.zip"]
genre = "TRANCE BEAT"
impr = "11"
total = "21"
avg = "1.9"
regist = "2007/01/20 16:41"
update = "2007/02/05 23:49"

[[entries]]
no = "15"
name = "LU"
title = "bitamin dance"
size = "630 KB"
addr = ["http://nekokan.dyndns.info/~gensoukyousoukyoku/bitamin.rar"]
genre = "drum'n'bass"
impr = "12"
total = "25"
avg = "2.08"
regist = "2007/01/20 19:09"
update = "2007/02/04 21:01"

[[entries]]
no = "16"
name = "#268"
title = "Ruriko REBIRTH"
size = "13731 KB"
addr = ["http://pms268.dw.land.to/bms/268_14_ruriko-rebirth_mq.zip"]
genre = "EURO TRANCE"
impr = "15"
total = "42"
avg = "2.8"
regist = "2007/01/20 21:49"
update = "2007/02/07 22:23"

[[entries]]
no = "17"
name = "ume"
title = "shining"
size = "13000 KB"
addr = ["http://umeboz.hp.infoseek.co.jp/dl.html"]
genre = "happy hardcore"
impr = "15"
total = "39"
avg = "2.6"
regist = "2007/01/21 02:25"
update = "2007/02/07 00:15"

[[entries]]
no = "18"
name = "dj-wooni"
title = "Date of Shooting game 2 ~ Hyper trance remix ~"
size = "45513 KB"
addr = [
    "http://kwhp.dothome.co.kr/data/dos2",
    "(international).zip",
]
genre = "Trance"
impr = "1"
total = "2"
avg = "2"
regist = "2007/01/21 02:36"
update = "2007/01/23 23:28"

[[entries]]
no = "19"
name = "kiku_b"
title = "chart"
size = "44500 KB"
addr = [
    "http://kikub.hp.infoseek.co.jp/dl.html",
    "（通常版・HQ版）",
]
genre = "overture"
impr = "9"
total = "18"
avg = "2"
regist = "2007/01/21 05:14"
update = "2007/02/05 23:10"

[[entries]]
no = "20"
name = "LU"
title = "our heads"
size = "874 KB"
addr = ["http://nekokan.dyndns.info/~gensoukyousoukyoku/ourheads.rar"]
genre = "booty trance"
impr = "16"
total = "36"
avg = "2.25"
regist = "2007/01/21 06:41"
update = "2007/02/05 00:05"

[[entries]]
no = "21"
name = "Hyuji"
title = "Stellar Light"
size = "7516 KB"
addr = [
    "http://eternal21.ddo.jp/~hyuji/stellar_light.zip",
    "http://www.pmeyw.com/event/stellar_light.zip",
]
genre = "Speed Eurobeat"
impr = "12"
total = "14"
avg = "1.16"
regist = "2007/01/21 06:49"
update = "2007/02/07 12:19"

[[entries]]
no = "22"
name = "樟"
title = "奇譚"
size = "596 KB"
addr = ["http://tokyo.cool.ne.jp/rysu78/kitan.zip"]
genre = "Goth"
impr = "19"
total = "44"
avg = "2.31"
regist = "2007/01/21 18:20"
update = "2007/02/05 23:46"

[[entries]]
no = "23"
name = "らいおねる。"
title = "elemental.nrg"
size = "1345 KB"
addr = ["http://lionel.hp.infoseek.co.jp/event_dl.html"]
genre = "CONTEMPORARY NATION"
impr = "6"
total = "3"
avg = "0.5"
regist = "2007/01/21 18:28"
update = "2007/02/05 23:37"

[[entries]]
no = "24"
name = "七草多粥"
title = "slaughterous RED"
size = "9820 KB"
addr = ["http://soundnsound.parallel.jp/event.html"]
genre = "UnhappinessHardCore"
impr = "7"
total = "14"
avg = "2"
regist = "2007/01/21 21:23"
update = "2007/02/05 01:03"

[[entries]]
no = "25"
name = "Re:cycle"
title = "R3-Re:cycle remix-"
size = "160 KB"
addr = ["http://www.geocities.jp/akatsuki_520/R3-remix-.zip"]
genre = "NOISY RAVE"
impr = "6"
total = "5"
avg = "0.83"
regist = "2007/01/21 22:02"
update = "2007/02/03 14:28"

[[entries]]
no = "26"
name = "valentia"
title = "carry on (beat on remake)"
size = "1950 KB"
addr = ["http://page.freett.com/monosky/"]
genre = "drum'n'bass"
impr = "12"
total = "25"
avg = "2.08"
regist = "2007/01/21 22:04"
update = "2007/07/09 00:49"

[[entries]]
no = "27"
name = "λ口"
title = "MURIUS"
size = "12100 KB"
addr = [
    "http://lambdakani.hp.infoseek.co.jp/",
    "リンク先の下のDLを押してください",
]
genre = "J-PSYCHO:OG3"
impr = "13"
total = "35"
avg = "2.69"
regist = "2007/01/21 22:09"
update = "2007/02/05 23:42"

[[entries]]
no = "28"
name = "GEMA"
title = "Sadness of Heaven"
size = "11840 KB"
addr = ["http://uziel.hp.infoseek.co.jp/music/SoH_bms.zip"]
genre = "Trance'n Shock"
impr = "6"
total = "9"
avg = "1.5"
regist = "2007/01/21 22:47"
update = "2007/02/03 14:36"

[[entries]]
no = "29"
name = "Rezanov"
title = "Cassis Orange"
size = "30228 KB"
addr = [
    "http://prime.s56.xrea.com/bms/index.html",
    "HQ版：30.2MB",
    "LQ版：6.7MB",
]
genre = "HOUSE"
impr = "10"
total = "20"
avg = "2"
regist = "2007/01/21 23:55"
update = "2007/02/05 23:10"

[[entries]]
no = "30"
name = "S.E.lain"
title = "existence"
size = "6775 KB"
addr = ["http://sound.jp/morigasigeru/existence.html"]
genre = "--"
impr = "15"
total = "36"
avg = "2.4"
regist = "2007/01/21 23:59"
update = "2007/02/04 19:25"

[[entries]]
no = "31"
name = "EXCALIpUR"
title = "MIGHTY OBSTACLE"
size = "6730 KB"
addr = ["http://excalipur.hp.infoseek.co.jp/bms/excalipur_ys6-mo_refine.zip"]
genre = "SPEED DANCE"
impr = "5"
total = "10"
avg = "2"
regist = "2007/01/21 23:59"
update = "2007/02/10 17:38"
