[[entries]]
no = "1"
name = "KIREJI"
title = "coca core"
size = "3553 KB"
addr = ["http://djugg.hp.infoseek.co.jp/cocacore.zip"]
genre = "GABBA"
impr = "11"
total = "14"
avg = "1.27"
regist = "2007/01/20 00:09"
update = "2007/02/06 21:25"

[[entries]]
no = "2"
name = "takdrive"
title = "minimalize"
size = "9960 KB"
addr = [
    "HQ(Zip版)☆容量は「Size」に記載",
    "http://big.freett.com/mumei_takdrive/hq_mini.zip",
    "HQ（RAR版）☆4202KB",
    "http://big.freett.com/mumei_takdrive/hq_mini.rar",
    "MQ（Zip版）☆6490KB",
    "http://big.freett.com/mumei_takdrive/mq_mini.zip",
    "MQ（RAR版）☆2561KB",
    "http://big.freett.com/mumei_takdrive/mq_mini.rar",
    "※DLは右クリックでお願いします※",
    "----------------------------------------------------------",
    "HQ版に、wavファイルで入っていない物が発見されたので、",
    "1/21 14:36以前にDLされた方は、",
    "http://page.freett.com/mumei_takdrive/hq_syuusei.zip",
    "をDL（右クリックでお願いします。）して、中身を入れてください。本当に申し訳ございません。",
    "1/21 14:36以降にDLされる方は、修正済みなので、上記のものをDLする必要はありません。",
]
genre = "minimal"
impr = "14"
total = "21"
avg = "1.5"
regist = "2007/01/20 03:34"
update = "2007/02/04 22:18"

[[entries]]
no = "3"
name = "midori"
title = "Pluto"
size = "18253 KB"
addr = ["http://iidxquasar.hp.infoseek.co.jp/Pluto.zip"]
genre = "Trance"
impr = "17"
total = "40"
avg = "2.35"
regist = "2007/01/20 07:39"
update = "2007/12/17 01:43"

[[entries]]
no = "4"
name = "卯月由羽"
title = "lunatic 3rd"
size = "9181 KB"
addr = ["http://park.geocities.jp/y0uy0u2003/mumei.htm"]
genre = "lunatic sonata"
impr = "13"
total = "11"
avg = "0.84"
regist = "2007/01/20 10:01"
update = "2007/02/04 15:21"

[[entries]]
no = "5"
name = "RearDawn"
title = "backpacker"
size = "3346 KB"
addr = ["http://fdist.ps.land.to/bms/backpacker.lzh"]
genre = "tribe minimal"
impr = "22"
total = "52"
avg = "2.36"
regist = "2007/01/20 12:00"
update = "2010/01/24 04:00"

[[entries]]
no = "6"
name = "M-Ky"
title = "Aquarism"
size = "4771 KB"
addr = ["http://music.geocities.jp/music_cre8ive/bms/mumei.htm"]
genre = "drum'n'bass"
impr = "16"
total = "36"
avg = "2.25"
regist = "2007/01/20 12:31"
update = "2007/02/05 21:57"

[[entries]]
no = "7"
name = "桐生カノ"
title = "Bloody Mary -Act.2-"
size = "4996 KB"
addr = ["http://usamimi.info/~tetra/mumei6.html"]
genre = "Gothic"
impr = "17"
total = "38"
avg = "2.23"
regist = "2007/01/20 14:53"
update = "2007/02/05 23:09"

[[entries]]
no = "8"
name = "ima"
title = "寂れた樹海"
size = "10400 KB"
addr = ["http://hpcgi2.nifty.com/oisinbo/dcnt/dcnt.cgi?n=11"]
genre = "bgm"
impr = "14"
total = "31"
avg = "2.21"
regist = "2007/01/20 20:42"
update = "2007/02/04 23:19"

[[entries]]
no = "9"
name = "syzfonics"
title = "az me"
size = "26699 KB"
addr = [
    "http://page.freett.com/syzfonics/index.htm",
    "HQ(rar) MQ(rar) MQ(zip)",
    "File Sizeに記載している容量はMQ(zip)です",
]
genre = "Happy"
impr = "13"
total = "30"
avg = "2.3"
regist = "2007/01/20 22:52"
update = "2007/02/04 15:16"

[[entries]]
no = "10"
name = "えむ"
title = "Z"
size = "1984 KB"
addr = ["http://m-bbm.hp.infoseek.co.jp/"]
genre = "Happy Hardcore"
impr = "12"
total = "14"
avg = "1.16"
regist = "2007/01/20 23:13"
update = "2007/02/05 22:06"

[[entries]]
no = "11"
name = "K-ky"
title = "黎明、森羅脈動"
size = "24181 KB"
addr = [
    "（LQ版 zip形式）",
    "http://yorozuya.ddo.jp/~keikai_sannri/music/reimei_LQ.zip",
    "（24MB）",
    "（LQ版 rar形式）",
    "http://yorozuya.ddo.jp/~keikai_sannri/music/reimei_LQ.rar",
    "（15MB）",
    "（HQ版 zip形式）",
    "http://yorozuya.ddo.jp/~keikai_sannri/music/reimei_HQ.zip",
    "（45MB）",
    "（HQ版 rar形式）",
    "http://yorozuya.ddo.jp/~keikai_sannri/music/reimei_HQ.rar",
    "（29MB）",
    "（ogg版 rar形式）",
    "http://yorozuya.ddo.jp/~keikai_sannri/music/reimei_ogg.rar",
    "（9MB）",
]
genre = "Nature"
impr = "23"
total = "63"
avg = "2.73"
regist = "2007/01/21 05:24"
update = "2007/02/05 22:37"

[[entries]]
no = "12"
name = "樋奈月みつ"
title = "コスモス"
size = "8266 KB"
addr = ["http://www.geocities.jp/rhyth_hinatsuki/index.htm"]
genre = "MYSTIC POP"
impr = "12"
total = "33"
avg = "2.75"
regist = "2007/01/21 09:50"
update = "2007/02/04 15:20"

[[entries]]
no = "13"
name = "mitchel"
title = "Apricot"
size = "13500 KB"
addr = [
    "http://dragoon.adsv.jp/bms/apricot_lq.zip",
    "http://dragoon.adsv.jp/bms/apricot_hq.zip",
]
genre = "Synthesized DnB"
impr = "19"
total = "40"
avg = "2.1"
regist = "2007/01/21 15:24"
update = "2007/02/05 20:14"

[[entries]]
no = "14"
name = "XRIS"
title = "GLOW-PLANET"
size = "13561 KB"
addr = [
    "HQ RAR 13M",
    "http://www5.pf-x.net/~xris/bms/XR_Glow_planet_HQ.rar",
    "HQ ZIP 16M",
    "http://www5.pf-x.net/~xris/bms/XR_Glow_planet_HQ.zip",
    "MQ RAR 8M",
    "http://www5.pf-x.net/~xris/bms/XR_Glow_Planet_MQ.rar",
    "MQ ZIP 10M",
    "http://www5.pf-x.net/~xris/bms/XR_Glow_Planet_MQ.zip",
]
genre = "DUTCH TRANCE"
impr = "14"
total = "33"
avg = "2.35"
regist = "2007/01/21 16:09"
update = "2007/02/04 22:00"

[[entries]]
no = "15"
name = "ASH."
title = "Clear WEEKDAY"
size = "8342 KB"
addr = [
    "(zip版)",
    "http://ash-rainbow.hp.infoseek.co.jp/BMS/Clear_WEEKDAY.zip",
    "(rar版)",
    "http://ash-rainbow.hp.infoseek.co.jp/BMS/Clear_WEEKDAY.rar",
]
genre = "TRANCE"
impr = "10"
total = "16"
avg = "1.6"
regist = "2007/01/21 18:00"
update = "2007/02/04 22:27"

[[entries]]
no = "16"
name = "d__t"
title = "Loops"
size = "3250 KB"
addr = ["http://nekokan.dyndns.info/~anonymous/mumei6th/loops.zip"]
genre = "PROGRESSIVE"
impr = "14"
total = "39"
avg = "2.78"
regist = "2007/01/21 21:49"
update = "2007/02/05 22:09"

[[entries]]
no = "17"
name = "Giude"
title = "confront fortress (Hybrid Rock style)"
size = "23439 KB"
addr = [
    "http://g-ambient.com/bms/fortress_hq.zip",
    "(HQ 23.4MB)",
    "http://g-ambient.com/bms/fortress_mq.zip",
    "(MQ 18.3MB)",
    "http://g-ambient.com/bms/fortress_bgalesshq.zip",
    "(BGAなしHQ 15.5MB)",
]
genre = "DRUM'N'DIGI-ROCK"
impr = "8"
total = "14"
avg = "1.75"
regist = "2007/01/21 23:26"
update = "2007/02/04 22:42"

[[entries]]
no = "18"
name = "MrBPM"
title = "True No Revenger"
size = "2740 KB"
addr = ["http://yorusann.hp.infoseek.co.jp/bms1.html"]
genre = "Noise"
impr = "12"
total = "30"
avg = "2.5"
regist = "2007/01/21 23:26"
update = "2007/02/10 02:27"

[[entries]]
no = "19"
name = "天音"
title = "その斯くも美しき紅に"
size = "19070 KB"
addr = [
    "http://youzyo.net/bms/ama03_kakumo.zip",
    "（zip圧縮MQ：19070KB）",
    "http://youzyo.net/bms/ama03_kakumo.rar",
    "（rar圧縮MQ：14688KB）",
]
genre = "Drum'n'Ambient"
impr = "25"
total = "65"
avg = "2.6"
regist = "2007/01/21 23:35"
update = "2007/02/05 22:54"

[[entries]]
no = "20"
name = "Josette"
title = "colors of little"
size = "27000 KB"
addr = [
    "http://kokuryu.s49.xrea.com/music/colors_of_little.rar",
    "(HQ)",
    "http://kokuryu.s49.xrea.com/music/colors_of_little.zip",
]
genre = "dreamworks"
impr = "19"
total = "51"
avg = "2.68"
regist = "2007/01/21 23:42"
update = "2007/02/05 22:54"

[[entries]]
no = "21"
name = "SWEEZ & Meine Meinung"
title = "COLORFUL"
size = "43926 KB"
addr = [
    "■DLページ",
    "http://sweez.net/item.html",
    "■高音質版 (zip/43.9MB)",
    "http://sweez.net/cgi-bin/dcnt/dcnt.cgi?n=1",
    "■中音質版 (zip/23.5MB)",
    "http://sweez.net/cgi-bin/dcnt/dcnt.cgi?n=2",
]
genre = "R&B"
impr = "43"
total = "124"
avg = "2.88"
regist = "2007/01/21 23:55"
update = "2007/04/08 13:45"

[[entries]]
no = "22"
name = "JiNG*da*LaW"
title = "Tokyo Fantasmix"
size = "10470 KB"
addr = [
    "http://nekomimi.ws/~iemitsu/up/TF-BMS-HQ.rar",
    "http://nekomimi.ws/~iemitsu/up/TF-BMS-HQ.zip",
    "http://nekomimi.ws/~iemitsu/up/TF-BMS-MQ.rar",
    "http://nekomimi.ws/~iemitsu/up/TF-BMS-MQ.zip",
]
genre = "The Beast Trance"
impr = "15"
total = "37"
avg = "2.46"
regist = "2007/01/22 03:50"
update = "2007/02/04 23:24"

[[entries]]
no = "23"
name = "鳩"
title = "SuPeRHeRo"
size = "44100 KB"
addr = [
    "http://hatmusics.com/sphr.rar",
    "http://hatmusics.com/sphr.zip",
]
genre = "ClassicTechno"
impr = "12"
total = "27"
avg = "2.25"
regist = "2007/01/23 02:52"
update = "2007/02/05 14:12"

[[entries]]
no = "24"
name = "m"
title = "ice floe"
size = "3298 KB"
addr = [
    "http://page.freett.com/smbms/index.htm",
    "(bmsとmp3がダウンロード可能です)",
]
genre = "-"
impr = "9"
total = "24"
avg = "2.66"
regist = "2007/01/24 00:19"
update = "2007/02/05 22:34"
