[[entries]]
no = "1"
name = "takdrive feat MC taqro."
title = "Legend of the D.M."
size = "3849 KB"
addr = [
    "http://big.freett.com/mumei_takdrive/lodm.rar",
    "http://big.freett.com/mumei_takdrive/lodm.zip",
    "(5852KB)",
    "※DLは右クリックでお願いします。",
]
genre = "NUSTYLE GABBA"
impr = "12"
total = "2399999978"
avg = "199999998.16"
regist = "2007/03/17 01:54"
update = "2007/04/01 23:38"

[[entries]]
no = "2"
name = "@.fizz"
title = "Sprun"
size = "7808 KB"
addr = [
    "http://www6.tok2.com/home/kill0625/sprun.zip",
    "(ogg版-推奨-)",
    "http://fizzlime.sakura.ne.jp/Sprun-wav.rar",
    "(wav版)",
]
genre = "Hi - pop"
impr = "8"
total = "1599999984"
avg = "199999998"
regist = "2007/03/17 02:07"
update = "2007/04/01 23:39"

[[entries]]
no = "3"
name = "Bit Upper"
title = "promoted action"
size = "351 KB"
addr = ["http://amonkido.at.infoseek.co.jp/chaos_field.htm"]
genre = "CORE"
impr = "9"
total = "1799999987"
avg = "199999998.55"
regist = "2007/03/17 02:45"
update = "2007/04/05 03:20"

[[entries]]
no = "4"
name = "emu"
title = "Lost Aster Promise"
size = "18900 KB"
addr = ["http://page.freett.com/loli_emu_studio2/bms.htm"]
genre = "NOT TRANCE"
impr = "10"
total = "1999999983"
avg = "199999998.3"
regist = "2007/03/17 10:46"
update = "2007/04/01 23:40"

[[entries]]
no = "5"
name = "4G"
title = "hexadecimal mixing"
size = "1457 KB"
addr = ["http://www7a.biglobe.ne.jp/~furiefurie/bms/hexadecimal.rar"]
genre = "SCHRANZ"
impr = "6"
total = "1199999984"
avg = "199999997.33"
regist = "2007/03/17 11:06"
update = "2007/04/01 23:41"

[[entries]]
no = "6"
name = "Soblian"
title = "Ground Breakers"
size = "18534 KB"
addr = ["公開終了"]
genre = "Hard Techno"
impr = "7"
total = "1399999985"
median = "1"
avg = "199999997.85"
regist = "2007/03/17 13:13"
update = "2019/08/10 00:30"

[[entries]]
no = "7"
name = "czardas"
title = "post mortal momentum"
size = "32458 KB"
addr = ["http://apple-jc.com/~giudecca/momentum.rar"]
genre = "post rock"
impr = "16"
total = "3199999992"
avg = "199999999.5"
regist = "2007/03/17 21:43"
update = "2007/04/01 23:43"

[[entries]]
no = "8"
name = "穴楽"
title = "Redestruct"
size = "20260 KB"
addr = ["http://kure-na.hp.infoseek.co.jp"]
genre = "electro shock"
impr = "12"
total = "2399999990"
avg = "199999999.16"
regist = "2007/03/18 01:02"
update = "2007/04/01 23:43"

[[entries]]
no = "9"
name = "ねこみりん"
title = "include minimalization"
size = "792 KB"
addr = [
    "http://nekomimi.bms.ms/bms/nekomirin_im.zip",
    "(MQ:792KB)",
    "http://nekomimi.bms.ms/bms/nekomirin_im_HQ.rar",
    "(HQ:3800KB)",
]
genre = "TECHNO"
impr = "7"
total = "1399999985"
avg = "199999997.85"
regist = "2007/03/18 06:00"
update = "2007/04/01 23:44"

[[entries]]
no = "10"
name = "jet:tones (Yamajet vs 6 tones)"
title = "Romancecar (Kukan Junkyu Edit)"
size = "11408 KB"
addr = [
    "http://yamajet.bms.ms/bms/data/jettones_romancecar.zip",
    "http://yamajet.bms.ms/bms/data/jettones_romancecar_HQogg.zip",
    "(11,145KB)",
    "BMP 高画質＋ogg 高音質版です。",
]
genre = "Liquid Funk"
impr = "20"
total = "3999999994"
avg = "199999999.7"
regist = "2007/03/18 11:20"
update = "2007/04/01 23:44"

[[entries]]
no = "11"
name = "samplingergirl"
title = "re:"
size = "1488 KB"
addr = ["http://sound.jp/samplingergirl/"]
genre = "-"
impr = "10"
total = "1999999989"
avg = "199999998.9"
regist = "2007/03/18 13:00"
update = "2007/04/01 23:45"

[[entries]]
no = "12"
name = "MNMr"
title = "Raspberry Queen"
size = "7290 KB"
addr = [
    "http://mnmr.dw.land.to/bms.html",
    "(上記URLの一番上のDOWNLOADをクリック)",
]
genre = "happy hardcore"
impr = "9"
total = "1799999984"
avg = "199999998.22"
regist = "2007/03/18 18:37"
update = "2007/04/01 23:45"

[[entries]]
no = "13"
name = "XRIS"
title = "ChaotiCavE"
size = "11742 KB"
addr = [
    "http://eternal-walkure.hp.infoseek.co.jp/XR_Chaoticave.rar",
    "HQ版 11.4MB",
]
genre = "SUBLIME TECHNO"
impr = "8"
total = "1599999988"
avg = "199999998.5"
regist = "2007/03/18 20:38"
update = "2007/04/01 23:46"

[[entries]]
no = "14"
name = "λ口-G"
title = "ALL.NUDE"
size = "9660 KB"
addr = [
    "http://lambdakani.hp.infoseek.co.jp/",
    "ｂｍｓコーナーの真ん中です。",
]
genre = "ＮＡＮＤＡ－ＣＯＲＥ"
impr = "17"
total = "3399999993"
avg = "199999999.58"
regist = "2007/03/18 21:04"
update = "2007/04/01 23:47"

[[entries]]
no = "15"
name = "SOLVALOU"
title = "ゼビウス軟着陸"
size = "22 KB"
addr = ["http://a-p.cside.ne.jp/files/softlandingxevious.rar"]
genre = "softlanding"
impr = "6"
total = "1199999988"
avg = "199999998"
regist = "2007/03/18 23:38"
update = "2007/04/01 23:21"

[[entries]]
no = "16"
name = "d__t"
title = "CLASS"
size = "3530 KB"
addr = ["http://nekokan.dyndns.info/~anonymous/2ch/CLASS.zip"]
genre = "AMBIENT"
impr = "8"
total = "1599999985"
avg = "199999998.12"
regist = "2007/03/18 23:47"
update = "2007/04/01 23:48"

[[entries]]
no = "17"
name = "tarolabo"
title = "パネルでポン/フレアのテーマ"
size = "3368 KB"
addr = ["http://hi-ho.mine.nu/tarolabo/paneponFlare.rar"]
genre = "riphop"
impr = "9"
total = "1799999995"
avg = "199999999.44"
regist = "2007/03/18 23:51"
update = "2007/04/01 23:50"

[[entries]]
no = "18"
name = "山田と見せかけて…"
title = "アルパカ66"
size = "11400 KB"
addr = ["http://kaibutuk.hp.infoseek.co.jp/alpaca66.zip"]
genre = "distortion disco"
impr = "10"
total = "1999999993"
avg = "199999999.3"
regist = "2007/03/19 00:39"
update = "2007/04/01 23:51"
