[[entries]]
no = "1"
name = "エレラビッツ"
title = "TAKE ME TO THE MOON"
size = "4209 KB"
addr = ["http://space.geocities.jp/ele_rabbits/"]
genre = "COSMIC POP"
impr = "22"
total = "60"
avg = "2.72"
regist = "2007/06/30 00:08"
update = "2007/07/17 00:18"

[[entries]]
no = "2"
name = "YKai"
title = "LASER CRUSTER [はぴコア MIX]"
size = "2361 KB"
addr = ["https://drive.google.com/open?id=0B7qCw4hNijr4alVZdU1raTVBaHc"]
genre = "HAPPY HARDCORE"
impr = "16"
total = "20"
median = "2"
avg = "1.25"
regist = "2007/06/30 00:15"
update = "2018/02/13 16:20"

[[entries]]
no = "3"
name = "MIKE"
title = "SUNDAY"
size = "2474 KB"
addr = [
    "http://www7.uploader.jp/dl/mike_5656/mike_5656_uljp00001.rar.html",
    "(rar版 2474KB)",
    "http://www7.uploader.jp/dl/mike_5656/mike_5656_uljp00002.zip.html",
    "(zip版 3535KB)",
    "--------------------------------------------",
    "DLにパスワードをかけてありますので",
    "「happybms」と入力するとDLできます！",
    "お手数かけますが宜しくお願いします。",
]
genre = "FUNK POP"
impr = "24"
total = "59"
avg = "2.45"
regist = "2007/06/30 00:59"
update = "2007/07/16 23:53"

[[entries]]
no = "4"
name = "DJ TYM"
title = "SMALL WAVES REMIX"
size = "2410 KB"
addr = ["http://www.qumarich.net/bms/swr.zip"]
genre = "RAVE"
impr = "18"
total = "38"
avg = "2.11"
regist = "2007/06/30 02:26"
update = "2007/07/20 14:18"

[[entries]]
no = "5"
name = "Marines"
title = "マリンパラダイス"
size = "4270 KB"
addr = ["http://image4.bannch.com:83/bs/M302/bbs/199701/img/0068635863.rar"]
genre = "POP FUSION"
impr = "11"
total = "19"
avg = "1.72"
regist = "2007/06/30 15:21"
update = "2007/07/17 02:46"

[[entries]]
no = "6"
name = "masopp"
title = "happy puppy"
size = "80 KB"
addr = ["http://amiad.hp.infoseek.co.jp/"]
genre = "chipskit"
impr = "21"
total = "52"
avg = "2.47"
regist = "2007/06/30 23:55"
update = "2007/07/17 00:29"

[[entries]]
no = "7"
name = "Soda"
title = "Lucky Star"
size = "5500 KB"
addr = ["http://members.at.infoseek.co.jp/Ym1024/bms/ym06_lucky.rar"]
genre = "Happy Hardcore"
impr = "14"
total = "31"
avg = "2.21"
regist = "2007/07/01 02:06"
update = "2007/07/17 02:12"

[[entries]]
no = "8"
name = "東京アリス幻樂団"
title = "稲田姫様ご乱心"
size = "27579 KB"
addr = [
    "http://bm2dx.dip.jp/creation/bms/inada.rar",
    "修正差分[2,783KB]",
    "http://bm2dx.dip.jp/creation/bms/inada_sabun.rar",
]
genre = "happy hardcore"
impr = "19"
total = "33"
avg = "1.73"
regist = "2007/07/01 16:20"
update = "2007/07/17 11:34"

[[entries]]
no = "9"
name = "ですばすば"
title = "ずっと俺のターンテーブル"
size = "355 KB"
addr = ["http://"]
genre = "DJバトル"
impr = "3"
total = "3"
avg = "1"
regist = "2007/07/01 18:45"
update = "2007/07/16 22:30"

[[entries]]
no = "10"
name = "018"
title = "YellowRunning"
size = "5194 KB"
addr = ["http://music.geocities.jp/happyhappy018/yellowrunning.zip"]
genre = "SYNTHPOP"
impr = "22"
total = "59"
avg = "2.68"
regist = "2007/07/01 21:30"
update = "2007/07/16 23:54"

[[entries]]
no = "11"
name = "AM 8:08"
title = "Holiday Morning"
size = "1125 KB"
addr = ["http://nekokan.dyndns.info/~anonymous/behappy3rd/HolidayMorning.rar"]
genre = "kirby pop"
impr = "13"
total = "22"
avg = "1.69"
regist = "2007/07/01 22:14"
update = "2007/07/16 23:25"

[[entries]]
no = "12"
name = "隔離された子供達"
title = "僕たちは、憧れた、空、"
size = "7061 KB"
addr = [
    "http://nekokan.dyndns.info/~anonymous/behappy3rd/akogare.zip",
    "http://nekokan.dyndns.info/~anonymous/behappy3rd/akogare_hq.zip",
    "（推奨）",
]
genre = "TRANCE"
impr = "14"
total = "17"
avg = "1.21"
regist = "2007/07/01 23:31"
update = "2007/07/17 00:58"

[[entries]]
no = "13"
name = "TOMA"
title = "funny crasher"
size = "7193 KB"
addr = ["http://estish.hp.infoseek.co.jp/bms/fc.zip"]
genre = "HAPPY GABBA"
impr = "20"
total = "54"
avg = "2.7"
regist = "2007/07/01 23:32"
update = "2007/07/17 21:49"

[[entries]]
no = "14"
name = "ピヨスケ"
title = "P-ChicK-ParK(・◇・)"
size = "32000 KB"
addr = [
    "http://sasakure.bms.ms/bms/pchickparkMQ.rar",
    "(正式公開版 中音質 35MB)",
    "http://sasakure.bms.ms/bms/pchickparkLQ.rar",
    "(正式公開版 低音質 11MB)",
]
genre = "PoPStepS"
impr = "29"
total = "77"
avg = "2.65"
regist = "2007/07/01 23:50"
update = "2007/08/04 01:46"

[[entries]]
no = "15"
name = "ele switch"
title = "Sunny Side Girls"
size = "15390 KB"
addr = ["http://nekokan.dyndns.info/~anonymous/behappy3rd/ssg_lq.rar"]
genre = "High Speed Synth Pop"
impr = "14"
total = "30"
avg = "2.14"
regist = "2007/07/01 23:56"
update = "2007/07/17 23:18"

[[entries]]
no = "16"
name = "晴明"
title = "happy life"
size = "3750 KB"
addr = ["http://rasuku.s116.xrea.com/bms/seiman_happy_life.rar"]
genre = "Techno"
impr = "16"
total = "31"
avg = "1.93"
regist = "2007/07/01 23:57"
update = "2007/07/17 20:28"

[[entries]]
no = "17"
name = "道満"
title = "9 persent resort"
size = "9719 KB"
addr = [
    "http://nekokan.dyndns.info/~anonymous/behappy3rd/9pr.rar",
    "http://nekokan.dyndns.info/~ngk/bms/9pr.rar",
    "(NOVA+R作成差分つき)",
]
genre = "_"
impr = "19"
total = "54"
avg = "2.84"
regist = "2007/07/01 23:58"
update = "2007/07/17 20:30"

[[entries]]
no = "18"
name = "Seasoning"
title = "Soy sauce"
size = "1500 KB"
addr = ["削除済み"]
genre = "HAPPY"
impr = "10"
total = "20"
avg = "2"
regist = "2007/07/09 00:15"
update = "2007/07/17 04:05"

[[entries]]
no = "19"
name = "東京モルール"
title = "blue bird"
size = "964 KB"
addr = [
    "http://www.geocities.jp/imitation612/bluebirdHQ.zip",
    "(HQ版:5310KB)",
    "http://www.geocities.jp/imitation612/bluebirdLQ.zip",
    "(LQ版:964KB)",
    "(rar→zipの二重圧縮になっております）",
]
genre = "DRUM'N'BASS"
impr = "13"
total = "31"
avg = "2.38"
regist = "2007/07/09 00:17"
update = "2007/07/17 01:25"
