[[entries]]
no = "1"
name = "エージェント foon"
title = "ロビーの大乱射"
size = "613 KB"
addr = ["http://www3.ocn.ne.jp/~fa18/matrix_foon.zip"]
genre = "マトリックス"
impr = "3"
total = "11"
avg = "3.66"
regist = "2007/08/24 00:10"
update = "2007/09/09 18:16"

[[entries]]
no = "2"
name = "未来"
title = "夏の終わりに"
size = "156 KB"
addr = [
    "http://www.geocities.jp/rf_mirai/bms/index.html",
    "http://www.geocities.jp/rf_mirai/bms/2007/m0701_natsuno-owarini.zip",
    "[156KB] ※右クリック保存",
]
genre = "J-POP"
impr = "2"
total = "8"
avg = "4"
regist = "2007/08/24 00:21"
update = "2007/09/01 18:50"

[[entries]]
no = "3"
name = "もわわわ言ってる人"
title = "もわわわわわわわわわ"
size = "104 KB"
addr = ["http://briefcase.yahoo.co.jp/sinsanngoku"]
genre = "破壊音声"
impr = "4"
total = "15"
avg = "3.75"
regist = "2007/08/24 02:18"
update = "2008/02/24 22:32"

[[entries]]
no = "4"
name = "らむだし"
title = "俺の落書き帳"
size = "2499 KB"
addr = ["http://lambdakani.hp.infoseek.co.jp/foon2007.html"]
genre = "PROGRESSIVE"
impr = "2"
total = "7"
avg = "3.5"
regist = "2007/08/24 04:20"
update = "2007/09/13 16:02"

[[entries]]
no = "5"
name = "kazu."
title = "ずっと5.1.1.のターン"
size = "530 KB"
addr = ["http://kazjp.hp.infoseek.co.jp/untitled.html"]
genre = "PIANO AMBIENT"
impr = "5"
total = "20"
avg = "4"
regist = "2007/08/24 15:08"
update = "2007/09/15 02:47"

[[entries]]
no = "6"
name = "ないつ"
title = "( ´Д`)"
size = "138 KB"
addr = ["http://www.eonet.ne.jp/~act-style/bms/foon.zip"]
genre = "ケツぷり"
impr = "2"
total = "3"
avg = "1.5"
regist = "2007/08/24 19:06"
update = "2007/08/29 03:52"

[[entries]]
no = "7"
name = "Nick"
title = "やりたい放題"
size = "1910 KB"
addr = [
    "http://nick.xxxxxxxx.jp/yaranaika.lzh",
    "（右クリック保存）",
]
genre = "無料"
impr = "2"
total = "8"
avg = "4"
regist = "2007/08/24 20:16"
update = "2007/09/07 22:52"

[[entries]]
no = "8"
name = "PnRk"
title = "速けりゃ良いってもんじゃない"
size = "3769 KB"
addr = ["http://briefcase.yahoo.co.jp/bc/kira2413kira2413/"]
genre = "F-S-S"
impr = "1"
total = "4"
avg = "4"
regist = "2007/08/24 23:42"
update = "2007/09/09 16:37"

[[entries]]
no = "9"
name = "桜居 ft. Steve.A.B.(E.)"
title = "HIMEM.SYS"
size = "319 KB"
addr = ["http://skriblmr.if.land.to/"]
genre = "国民機"
impr = "3"
total = "10"
avg = "3.33"
regist = "2007/08/25 01:29"
update = "2007/09/10 01:28"

[[entries]]
no = "10"
name = "KO-KO"
title = "七時です"
size = "14 KB"
addr = ["http://nekokan.dyndns.info/~anonymous/bms/p_eyes/7.rar"]
genre = "clock"
impr = "3"
total = "10"
avg = "3.33"
regist = "2007/08/25 02:33"
update = "2007/09/01 07:08"

[[entries]]
no = "11"
name = "偽みすたーてぃー"
title = "ﾃﾞｭｰﾂﾓﾛｰ (人生ｵﾜﾀmix)"
size = "923 KB"
addr = ["http://briefcase.yahoo.co.jp/bc/mei_414m/lst?.dir=/a09e&.order=&.view=l&.src=bc&.done=http%3a//briefcase.yahoo.co.jp/"]
genre = "H(et)AR(e)DCORE TECHNO"
impr = "1"
total = "3"
avg = "3"
regist = "2007/08/25 04:05"
update = "2007/09/09 16:32"

[[entries]]
no = "12"
name = "ももやま"
title = "なんと曲が10曲も入ってる(ｒｙ"
size = "6120 KB"
addr = [
    "http://www.geocities.jp/pink_no_cool/BMS/otoku.zip",
    "※右クリック保存でダウンロードできます。",
]
genre = "はっぴーだんすゆーろとぷろぐれとくらしかるとこんてんぽらりーとせんたいひーろー"
impr = "2"
total = "8"
avg = "4"
regist = "2007/08/25 11:58"
update = "2007/08/27 05:59"

[[entries]]
no = "13"
name = "織田信短"
title = "⑨"
size = "350 KB"
addr = ["http://up.pandoravote.net/link.php?id=01747"]
genre = "⑨"
impr = "5"
total = "18"
avg = "3.6"
regist = "2007/08/25 14:18"
update = "2007/09/16 23:48"

[[entries]]
no = "14"
name = "カス"
title = "へぇ～"
size = "000 KB"
addr = ["http://briefcase.yahoo.co.jp/bc/asdfghjk329329/lst?&.dir=/ce20&.src=bc&.view=l"]
genre = "へぇ～"
impr = "0"
total = "0"
avg = "4.66"
regist = "2007/08/25 17:55"
update = "2007/09/18 05:22"

[[entries]]
no = "15"
name = "ゴミ"
title = "もう音階とか無視"
size = "000000000 KB"
addr = ["http://briefcase.yahoo.co.jp/bc/asdfghjk329329/lst?&.dir=/ce20&.src=bc&.view=l"]
genre = "qwertyui"
impr = "0"
total = "0"
avg = "4.5"
regist = "2007/08/25 17:57"
update = "2007/09/18 05:22"

[[entries]]
no = "16"
name = "guri & gura"
title = "健康戦隊のエンディングテーマ"
size = "1788 KB"
addr = ["http://asdf.bms.ms/junk/bms/d11_rakisurume.zip"]
genre = "らき☆するめ"
impr = "1"
total = "4"
avg = "4"
regist = "2007/08/26 00:23"
update = "2007/09/09 16:24"

[[entries]]
no = "17"
name = "志村健一"
title = "ドリフの大爆笑"
size = "103 KB"
addr = ["http://www.csync.net/service/file/view.cgi?id=1188723392"]
genre = "ザ･ドリフターズ（流れてたので再うｐ 9/2）"
impr = "2"
total = "7"
avg = "3.5"
regist = "2007/08/26 02:43"
update = "2007/09/09 19:10"

[[entries]]
no = "18"
name = "NECOXさん"
title = "キンちゃん RUSH"
size = "6550 KB"
addr = ["http://nekomimi.bms.ms/bms/necox_kinchan.zip"]
genre = "金閣寺れいぶ"
impr = "11"
total = "48"
avg = "4.36"
regist = "2007/08/26 04:20"
update = "2007/09/18 05:21"

[[entries]]
no = "20"
name = "THE ERRORS"
title = "Error #1 (BUCHI MIX)"
size = "653 KB"
addr = [
    "http://freett.com/mixmax412/music/error01.html",
    "MIX-MAX氏のホームページにアップロードさせて頂きました。",
]
genre = "NON MUSIC"
impr = "2"
total = "7"
avg = "3.5"
regist = "2007/08/26 08:27"
update = "2007/09/30 16:40"

[[entries]]
no = "21"
name = "DJ.Deplorer"
title = ".59 -heavens SC remix-"
size = "20000 KB"
addr = ["http://music.geocities.jp/erasure_deplorer/bof2007.html"]
genre = "TECHNO"
impr = "3"
total = "8"
avg = "2.66"
regist = "2007/08/26 08:56"
update = "2007/09/09 15:52"

[[entries]]
no = "22"
name = "知らないおじさん"
title = "知らないおじさんは他人の音を盗んでいきました"
size = "480 KB"
addr = ["http://nullpo.vip2ch.com/dl.php?f=ga9320.zip"]
genre = "ハッピーみんなの力"
impr = "4"
total = "16"
avg = "4"
regist = "2007/08/26 10:13"
update = "2007/09/09 16:25"

[[entries]]
no = "23"
name = "ごめんなさいmon"
title = "池田ンち"
size = "849 KB"
addr = ["http://3rd.geocities.jp/accessflight/ikeda.zip"]
genre = "PERCUSSIVE"
impr = "2"
total = "7"
avg = "3.5"
regist = "2007/08/26 14:26"
update = "2007/09/15 21:52"

[[entries]]
no = "24"
name = "少年BOOM"
title = "Final Sonic -the sonic wave mixxx-"
size = "1032 KB"
addr = [
    "http://uploader.bms.ms/data/sen-goku/",
    "[boy_boom]final_sonic.zip",
]
genre = "cyber voice techno"
impr = "2"
total = "5"
avg = "2.5"
regist = "2007/08/26 17:43"
update = "2007/09/09 16:13"

[[entries]]
no = "25"
name = "霧雨"
title = "Voyage into a cage..."
size = "1629 KB"
addr = ["http://kirisame.oboroduki.com/game/bpms/voyage_into_a_cage.zip"]
genre = "GRAND PIANO"
impr = "2"
total = "8"
avg = "4"
regist = "2007/08/26 19:11"
update = "2007/09/13 22:04"

[[entries]]
no = "28"
name = "Cola"
title = "Go Ahead"
size = "17000 KB"
addr = [
    "http://island.geocities.jp/sodadadadada/goahead_hq.zip",
    "(1164MB)",
    "http://island.geocities.jp/sodadadadada/goahead_tq.zip",
    "(17595MB)",
]
genre = "Rock'n Pop (J-POP)"
impr = "1"
total = "2"
avg = "2"
regist = "2007/08/26 19:41"
update = "2007/08/29 03:59"

[[entries]]
no = "29"
name = "ポテトＬ5"
title = "テラ☆YO☆SH☆IKI☆"
size = "1794 KB"
addr = ["http://iimode-do.jp/obj/wakimata.zip"]
genre = "新規テキスト ドキュメント.bms"
impr = "4"
total = "16"
avg = "4"
regist = "2007/08/26 20:36"
update = "2007/09/16 18:19"

[[entries]]
no = "30"
name = "pianist R"
title = 'ピアノ協奏曲第425番"階段"'
size = "4659 KB"
addr = ["http://briefcase.yahoo.co.jp/bc/pianist_gigadelic/"]
genre = "Lesson"
impr = "4"
total = "16"
avg = "4"
regist = "2007/08/26 21:18"
update = "2007/09/03 01:42"

[[entries]]
no = "33"
name = "ｿﾚﾅﾝﾃ=ｴ=ﾛｹﾞ"
title = "それ、なんてエロゲ？"
size = "4000 KB"
addr = ["http://jkgazou.sakura.ne.jp/roda/src/jkgazo0994.rar"]
genre = "詳細きぼんぬ"
impr = "5"
total = "14"
avg = "2.8"
regist = "2007/08/26 23:30"
update = "2007/09/09 05:25"

[[entries]]
no = "34"
name = "戦國アリス実行委員会"
title = "戦國アリス"
size = "11490 KB"
addr = ["http://www.comeup.info/bofoon2007/"]
genre = "Techno"
impr = "2"
total = "7"
avg = "3.5"
regist = "2007/08/26 23:54"
update = "2007/09/11 22:09"

[[entries]]
no = "35"
name = "い.い.男. -G"
title = "We Need a MASTERpiece"
size = "1092 KB"
addr = ["http://skriblmr.if.land.to/getget.rar"]
genre = "Cymbal"
impr = "3"
total = "11"
avg = "3.66"
regist = "2007/08/26 23:56"
update = "2007/09/09 16:02"

[[entries]]
no = "36"
name = "スクラップ&スクラップ"
title = "世界一位"
size = "1850 KB"
addr = ["http://kasoup.s1.x-beat.com/3/src/kasoup30382.rar"]
genre = "best tune music"
impr = "2"
total = "9"
avg = "4.5"
regist = "2007/08/26 23:59"
update = "2007/09/17 00:03"

[[entries]]
no = "37"
name = "未来"
title = "インプレ期間延長します(～9/16)"
size = "4165 KB"
addr = ["http://www17.plala.or.jp/rf_mirai/m0604_mbmitw.rar"]
genre = "お知らせ"
impr = "0"
total = "0"
avg = "5"
regist = "2007/09/01 05:30"
update = "2007/09/18 05:23"
