[[entries]]
no = "1"
name = "zannen vs contron"
title = "OMEGA IX"
size = "9500 KB"
addr = ["http://www2.atpages.jp/zannen/2007/index.htm"]
genre = "NEURO FUNK"
impr = "7"
total = "7"
avg = "1"
regist = "2007/09/01 00:19"
update = "2007/09/30 19:14"

[[entries]]
no = "2"
name = "雛鍔 葵 / yassu"
title = "Typica"
size = "2700 KB"
addr = ["http://klokken.fem.jp/yassu_ori10_typica_aketa.zip"]
genre = "JAZZ SESSION"
impr = "5"
total = "5"
avg = "1"
regist = "2007/09/01 23:51"
update = "2007/09/30 23:34"

[[entries]]
no = "3"
name = "壱air@Visualizer"
title = "Jade Star"
size = "39300 KB"
addr = ["http://www.visualizer.jp/ichi-air/js_vis.zip"]
genre = "Trance"
impr = "10"
total = "10"
avg = "1"
regist = "2007/09/02 04:18"
update = "2007/09/30 19:40"

[[entries]]
no = "4"
name = "fity / SHIKI"
title = "Jade Star"
size = "10000 KB"
addr = ["http://www.h4.dion.ne.jp/~fity/fityJSbga.rar"]
genre = "Trance"
impr = "3"
total = "3"
avg = "1"
regist = "2007/09/06 23:22"
update = "2007/09/29 23:07"

[[entries]]
no = "5"
name = "iimode-do / Rezanov"
title = "Little Night"
size = "10157 KB"
addr = [
    "http://iimode-do.jp/obj/littlenight_bga_iimo.rar",
    "(BGAのみ10157KB)",
    "http://iimode-do.jp/obj/littlenight_HQ.rar",
    "(HQ版BMS同梱56406KB)",
    "http://iimode-do.jp/obj/littlenight_MQ.rar",
    "(MQ版BMS同梱19110KB)",
]
genre = "Waltz"
impr = "5"
total = "5"
avg = "1"
regist = "2007/09/16 11:59"
update = "2007/09/30 20:04"

[[entries]]
no = "6"
name = "fity/Ym1024"
title = "Flowers'"
size = "6260 KB"
addr = ["http://www.h4.dion.ne.jp/~fity/flowbga.rar"]
genre = "Instrumental House"
impr = "6"
total = "6"
avg = "1"
regist = "2007/09/16 20:14"
update = "2007/09/29 23:39"

[[entries]]
no = "7"
name = "kody/kozato"
title = "四十五年ノ雪桜"
size = "29450 KB"
addr = [
    "[LQ版]",
    "http://uploader.bms.ms/data/sen-goku/%5Bkozato_kody%5D45th_SCB_LQ.zip",
    "[HQ/ogg版]",
    "http://uploader.bms.ms/data/sen-goku/%5Bkozato_kody%5D45th_SCB_ogg.zip",
]
genre = "Dramatical"
impr = "2"
total = "2"
avg = "1"
regist = "2007/09/16 23:55"
update = "2007/09/30 20:45"

[[entries]]
no = "8"
name = "雛鍔 葵"
title = "Jade Star"
size = "13400 KB"
addr = ["http://klokken.fem.jp/jadestar_XIX.zip"]
genre = "Trance"
impr = "3"
total = "3"
avg = "1"
regist = "2007/09/30 13:29"
update = "2007/09/30 23:46"
