[[entries]]
no = "1"
name = "sun3"
title = "ANGELIC MIRAGE"
size = "9400 KB"
addr = ["http://www14.plala.or.jp/sun3_bms/ANGELIC_MIRAGE.rar"]
genre = "Nu-style Gabba"
impr = "7"
total = "--"
median = "--"
avg = "--"
regist = "2007/09/30 00:02"
update = "2007/10/28 22:28"

[[entries]]
no = "2"
name = "Ｆ／Ａ１８"
title = "稲田姫様に叱られるから"
size = "5410 KB"
addr = ["http://fa18af.sakura.ne.jp/"]
genre = "GAME MUSIC"
impr = "11"
total = "--"
median = "--"
avg = "--"
regist = "2007/09/30 01:58"
update = "2007/10/28 22:52"

[[entries]]
no = "3"
name = "Ritsu"
title = "Nu-Known"
size = "435 KB"
addr = [
    "http://music.geocities.jp/txy5728/index.htm",
    "(MUSICよりDLお願いします)",
]
genre = "Chiptune"
impr = "8"
total = "--"
median = "--"
avg = "--"
regist = "2007/09/30 18:59"
update = "2007/10/28 22:15"

[[entries]]
no = "4"
name = "Nitrix"
title = "Eastern Beats"
size = "2806 KB"
addr = ["http://page.freett.com/nitrix/toho2.html"]
genre = "NU SKOOL BREAKS"
impr = "9"
total = "--"
median = "--"
avg = "--"
regist = "2007/10/01 01:05"
update = "2007/10/31 01:58"

[[entries]]
no = "5"
name = "Soblian"
title = "in the Moonlight"
size = "17817 KB"
addr = ["公開終了"]
genre = "Trance"
impr = "5"
total = "--"
median = "--"
avg = "--"
regist = "2007/10/02 17:12"
update = "2019/08/10 00:31"

[[entries]]
no = "6"
name = "Ｆ／Ａ１８"
title = "クリスタライズシルバー"
size = "9400 KB"
addr = ["http://fa18af.sakura.ne.jp/"]
genre = "GAME MUSIC"
impr = "3"
total = "--"
median = "--"
avg = "--"
regist = "2007/10/10 23:07"
update = "2007/10/28 22:02"

[[entries]]
no = "7"
name = "EXCALIpUR"
title = "LUNASA the Stormcauser"
size = "4890 KB"
addr = [
    "http://excalipur.hp.infoseek.co.jp/thbms2.html",
    "※お手数ですが仮設ページからダウンロードして下さい。",
]
genre = "FREEFORM"
impr = "5"
total = "--"
median = "--"
avg = "--"
regist = "2007/10/11 01:08"
update = "2007/10/28 21:51"

[[entries]]
no = "8"
name = "wara"
title = "fairy on lake"
size = "4460 KB"
addr = ["http://www.geocities.jp/wara511/bms.htm"]
genre = "---"
impr = "4"
total = "--"
median = "--"
avg = "--"
regist = "2007/10/13 19:21"
update = "2007/10/28 21:42"

[[entries]]
no = "9"
name = "Est"
title = "妖々夢 ～ Snow & Snow Crystals"
size = "4523 KB"
addr = ["http://estish.hp.infoseek.co.jp/bms/yym_rmx.zip"]
genre = "-"
impr = "6"
total = "--"
median = "--"
avg = "--"
regist = "2007/10/14 00:11"
update = "2007/11/04 19:25"

[[entries]]
no = "10"
name = "N-island-K"
title = "Eternal Earth"
size = "25601 KB"
addr = [
    "http://big.freett.com/t59g59/Eternal_Earth_HQogg.rar",
    "http://big.freett.com/t59g59/Eternal_Earth_MQ.rar",
    "http://big.freett.com/t59g59/Eternal_Earth_LQ.rar",
]
genre = "ハードノスタルジア"
impr = "8"
total = "--"
median = "--"
avg = "--"
regist = "2007/10/14 02:17"
update = "2007/10/28 21:22"

[[entries]]
no = "11"
name = "glassmoon"
title = "眠ろうファンタジア"
size = "7058 KB"
addr = [
    "http://g-moon-web.hp.infoseek.co.jp/data/nmr_ogg.zip",
    "http://g-moon-web.hp.infoseek.co.jp/data/nmr_wav.zip",
]
genre = "Pops"
impr = "4"
total = "--"
median = "--"
avg = "--"
regist = "2007/10/14 23:09"
update = "2007/10/28 21:05"

[[entries]]
no = "12"
name = "MONO"
title = "Fantasmagoria"
size = "31424 KB"
addr = [
    "http://shirosaki.net/ark/Fanta_BMS+BGA.zip",
    "(BGA同封)",
    "http://shirosaki.net/ark/Fanta_BMS.zip",
    "(BGA無)",
    "http://big.freett.com/oneb/Fanta_-BMS+BGA-.zip",
    "(BGA同封、ミラー)",
    "http://big.freett.com/oneb/Fanta_-BMS-.zip",
    "(BGA無、ミラー)",
    "(ミラーからダウンロードするときは右クリックで保存をお願いします)",
]
genre = "TRANCE"
impr = "10"
total = "--"
median = "--"
avg = "--"
regist = "2007/10/14 23:47"
update = "2007/11/05 00:43"

[[entries]]
no = "13"
name = "穴楽"
title = "T.R.E.～永夜の舞～"
size = "6563 KB"
addr = ["http://kure-na.hp.infoseek.co.jp/"]
genre = "LABYRINTH"
impr = "2"
total = "--"
median = "--"
avg = "--"
regist = "2007/10/22 00:11"
update = "2007/10/28 20:56"
