[[entries]]
no = "1"
name = "-"
title = "camellia"
size = "3670 KB"
addr = ["http://estish.hp.infoseek.co.jp/bms/camellia.zip"]
genre = "Nu-style Gabba"
impr = "12"
total = "19"
avg = "1.58"
regist = "2007/10/12 00:08"
update = "2007/10/22 00:31"

[[entries]]
no = "2"
name = "wire puller"
title = "be at a loss"
size = "1000 KB"
addr = ["http://sound.jp/wire_puller/"]
genre = "wire puller"
impr = "7"
total = "9"
avg = "1.28"
regist = "2007/10/12 00:12"
update = "2007/10/21 23:46"

[[entries]]
no = "3"
name = "RainDrops"
title = "飛翔転生"
size = "9206 KB"
addr = ["http://nekokan.dyndns.info/~anonymous/WirePuller/air-no-used2-rmx.rar"]
genre = "J-EURO TRANCE POP"
impr = "16"
total = "41"
avg = "2.56"
regist = "2007/10/12 00:21"
update = "2007/10/22 00:01"

[[entries]]
no = "4"
name = "The Shrimp"
title = "Sleep,sleep,well"
size = "10808 KB"
addr = ["http://shrimp.if.land.to/"]
genre = "ambient"
impr = "10"
total = "20"
avg = "2"
regist = "2007/10/12 01:22"
update = "2007/10/22 01:26"

[[entries]]
no = "5"
name = "Mutsumi"
title = "Ocean Pacific Peace!!"
size = "2893 KB"
addr = ["http://www.geocities.jp/mutu_bpm623/opp.html"]
genre = "Minimalpop"
impr = "13"
total = "33"
avg = "2.53"
regist = "2007/10/12 03:18"
update = "2007/10/21 23:51"

[[entries]]
no = "6"
name = "Black hood"
title = "fragmentation"
size = "1750 KB"
addr = [
    "LQ…1750KB",
    "http://nekokan.dyndns.info/~anonymous/WirePuller/fragmentation_LQ.rar",
    "HQ…6540KB",
    "http://nekokan.dyndns.info/~anonymous/WirePuller/fragmentation_HQ.rar",
]
genre = "Jarring hard tekuno"
impr = "14"
total = "32"
avg = "2.28"
regist = "2007/10/12 03:31"
update = "2007/10/21 23:52"

[[entries]]
no = "7"
name = "Misao Hiragi"
title = "The ninja"
size = "4574 KB"
addr = [
    "http://www12.axfc.net/uploader/18/so/Ne_2494.rar.html",
    "（wav版32khz）",
    "http://www12.axfc.net/uploader/18/so/Ne_2493.rar.html",
    "（ogg版）",
    "pass:bms",
]
genre = "Techno"
impr = "16"
total = "32"
avg = "2"
regist = "2007/10/12 05:50"
update = "2007/10/31 03:04"

[[entries]]
no = "8"
name = "Dj.Nitro"
title = "Beyond Stream"
size = "4899 KB"
addr = ["http://pds6.egloos.com/pds/200710/13/48/beyondstream.zip"]
genre = "Trance"
impr = "10"
total = "13"
avg = "1.3"
regist = "2007/10/13 02:57"
update = "2007/10/21 23:14"

[[entries]]
no = "9"
name = "myorabassi"
title = "Into cloudy, midnight New York city"
size = "2575 KB"
addr = [
    "http://uploader.bms.ms/data/wirepuller/myorabassi/icmnc_wav.rar",
    "(wavLQ / 2.51MB)",
    "http://uploader.bms.ms/data/wirepuller/myorabassi/icmnc_ogg.rar",
    "(oggHQ / 3.50MB)",
]
genre = "hiphop"
impr = "13"
total = "34"
avg = "2.61"
regist = "2007/10/13 05:27"
update = "2007/10/22 00:37"

[[entries]]
no = "10"
name = "Unknown Artist"
title = "Amanita Muscaria"
size = "8387 KB"
addr = ["http://uploader.bms.ms/data/wirepuller/unknown_artist-amanita_muscaria.zip"]
genre = "----"
impr = "8"
total = "15"
avg = "1.87"
regist = "2007/10/13 12:50"
update = "2007/10/21 23:23"

[[entries]]
no = "11"
name = "鏡の真"
title = "鏡"
size = "22016 KB"
addr = ["公開終了"]
genre = "-"
impr = "8"
total = "13"
median = "1"
avg = "1.62"
regist = "2007/10/13 16:12"
update = "2019/08/10 00:31"

[[entries]]
no = "12"
name = "050 10 39"
title = "マリオネットとパペットマン。"
size = "4750 KB"
addr = [
    "http://uploader.bms.ms/data/wirepuller/0501039/maripape_ogg.rar",
    "(ogg / 4.75MB)",
    "http://uploader.bms.ms/data/wirepuller/0501039/maripape_lq.rar",
    "(wav / 5.96MB)",
]
genre = "trance pop"
impr = "9"
total = "14"
avg = "1.55"
regist = "2007/10/13 21:36"
update = "2007/10/21 23:18"

[[entries]]
no = "13"
name = "SPMG-"
title = "Star Rubbish"
size = "3729 KB"
addr = ["http://s.freepe.com/std.cgi?id=9999998888&pn=01"]
genre = "DREAM TRANCE"
impr = "11"
total = "12"
avg = "1.09"
regist = "2007/10/13 22:40"
update = "2007/10/22 21:29"

[[entries]]
no = "14"
name = "GREEDY GROOVE"
title = "DARKISM"
size = "5694 KB"
addr = ["http://uploader.bms.ms/data/wirepuller/greedy/darkism.rar"]
genre = "Drum'n Bass"
impr = "10"
total = "23"
avg = "2.3"
regist = "2007/10/13 23:49"
update = "2007/10/22 00:59"

[[entries]]
no = "15"
name = "muhn"
title = "untitled"
size = "27600 KB"
addr = ["http://uploader.bms.ms/data/wirepuller/muhn/untitled.rar"]
genre = "jazz"
impr = "15"
total = "39"
avg = "2.6"
regist = "2007/10/13 23:52"
update = "2007/10/21 23:55"

[[entries]]
no = "16"
name = "太田瀬豆"
title = "158201"
size = "26600 KB"
addr = [
    "http://uploader.bms.ms/data/wirepuller/158201/158201H.rar",
    "http://uploader.bms.ms/data/wirepuller/158201/158201H.zip",
    "http://uploader.bms.ms/data/wirepuller/158201/158201L.rar",
    "http://uploader.bms.ms/data/wirepuller/158201/158201L.zip",
]
genre = "Ambient"
impr = "7"
total = "11"
avg = "1.57"
regist = "2007/10/13 23:53"
update = "2007/10/21 23:21"

[[entries]]
no = "17"
name = "NANO"
title = "midget lamp."
size = "6209 KB"
addr = ["http://uploader.bms.ms/data/wirepuller/nano/midget.rar"]
genre = "electro"
impr = "10"
total = "27"
avg = "2.7"
regist = "2007/10/13 23:58"
update = "2007/10/21 23:23"

[[entries]]
no = "18"
name = "dj-B"
title = "MirroR"
size = "4930 KB"
addr = ["http://members.at.infoseek.co.jp/Ym1024/bms/ym09_mirror.rar"]
genre = "Progressive Rock"
impr = "12"
total = "30"
avg = "2.5"
regist = "2007/10/13 23:58"
update = "2007/10/22 01:17"

[[entries]]
no = "19"
name = "Saz"
title = "Act #000000"
size = "15282 KB"
addr = [
    "http://uploader.bms.ms/data/wirepuller/Saz%5EActkuro.rar",
    "ミスが見つかりました。",
    "http://uploader.bms.ms/data/wirepuller/Saz/back.rar",
    "お手数ですが、このファイルを上書きして頂けると助かります。",
    "上書きしないと一部音が本当にえらい事になります。",
    "あと___bmse_temp.bmsも混入されていました。消してください。",
    "色々と滑り込みのぼろが出て悲しいです。",
]
genre = "trance/hardstyle"
impr = "18"
total = "52"
avg = "2.88"
regist = "2007/10/13 23:59"
update = "2007/10/22 00:47"

[[entries]]
no = "20"
name = "cottontails"
title = "be"
size = "16000 KB"
addr = ["http://uploader.bms.ms/data/wirepuller/cottontails-be.rar"]
genre = "."
impr = "16"
total = "45"
avg = "2.81"
regist = "2007/10/13 23:59"
update = "2007/10/22 02:06"

[[entries]]
no = "21"
name = "PDN"
title = "Phantom of spring"
size = "7893 KB"
addr = ["http://uploader.bms.ms/data/wirepuller/pd/phantom_of_spring.rar"]
genre = "techno"
impr = "20"
total = "52"
avg = "2.6"
regist = "2007/10/14 01:19"
update = "2007/10/22 02:40"
