[[entries]]
no = "1"
name = "壱air@Visualizer"
title = "2038"
size = "10450 KB"
addr = [
    "BGA :",
    "http://visualizer.jp/ichi-air/ichiBGA_2038.zip",
    "BMS :",
    "http://www.yamajet.com/music/html/2038.html",
]
genre = "MONDO"
impr = "34"
total = "61"
avg = "1.79"
regist = "2008/02/22 01:45"
update = "2008/03/02 23:31"

[[entries]]
no = "2"
name = "雛鍔 葵"
title = "午後の喫茶"
size = "12119 KB"
addr = [
    "http://klokken.fem.jp/aoi_afternoonBGA.zip",
    "http://www3.to/ractina/",
]
genre = "bossanova"
impr = "32"
total = "60"
avg = "1.87"
regist = "2008/02/22 05:29"
update = "2008/03/02 23:58"

[[entries]]
no = "3"
name = "brinda"
title = "Exception hearts"
size = "13925 KB"
addr = [
    "BGA :",
    "http://www.outfound.info/data/bga/brinda_ex_heart_bga.rar",
    "BMS :",
    "http://atmbzk.s56.xrea.com/",
]
genre = "Multiplex breakbeats"
impr = "24"
total = "35"
avg = "1.45"
regist = "2008/02/22 06:23"
update = "2008/03/02 23:54"

[[entries]]
no = "4"
name = "BIZNOT / dj BEATCONTROLLER"
title = "Nine Spot After Dark"
size = "11000 KB"
addr = ["http://biznot.biz/products/Nine_Spot_After_Dark.zip"]
genre = "ELECTRIC FUNKY HOUSE"
impr = "28"
total = "38"
avg = "1.35"
regist = "2008/02/23 01:36"
update = "2008/03/03 00:14"

[[entries]]
no = "5"
name = "VJ TETS"
title = "The Red Sky"
size = "639 KB"
addr = [
    "BGA :",
    "http://www.outfound.info/data/bga/tets_theredsky_bga.rar",
    "BMS :",
    "http://www.ne.jp/asahi/b/banglar/",
]
genre = "Break Beats"
impr = "19"
total = "22"
avg = "1.15"
regist = "2008/02/23 08:20"
update = "2008/03/02 23:56"

[[entries]]
no = "6"
name = "Toxvid"
title = "Aci - L"
size = "21000 KB"
addr = [
    "BMS",
    "http://www5.pf-x.net/~malie/",
    "BGA HQ (22mb)",
    "http://lepusnette.aquz.biz/bgadata/",
    "(BGA-HQ)Aci-L.rar",
    "BGA MQ (14mb)",
    "http://lepusnette.aquz.biz/bgadata/",
    "(bga-mq)aci-l.rar",
]
genre = "t r a n c e"
impr = "27"
total = "45"
avg = "1.66"
regist = "2008/02/23 10:43"
update = "2009/03/16 08:30"

[[entries]]
no = "7"
name = "wandering light"
title = "RAY"
size = "8448 KB"
addr = [
    "LQ :",
    "http://www.planetoid.biz/bga/wl_ray_bgalq.rar",
    "(8448KB)",
    "HQ :",
    "http://www.planetoid.biz/bga/wl_ray_bgahq.rar",
    "(17620KB)",
    "bms :",
    "http://tobitaro.hp.infoseek.co.jp/",
]
genre = "HARD TRANCE"
impr = "24"
total = "42"
avg = "1.75"
regist = "2008/02/23 17:15"
update = "2011/02/25 17:18"

[[entries]]
no = "8"
name = "Altoona"
title = "IT'S MY PLAY"
size = "332 KB"
addr = [
    "BGA：",
    "http://page.freett.com/altoona/itsmyplay_bga_alt.rar",
    "BMS：",
    "http://manbow.nothing.sh/event/event.cgi?action=More_def&num=117&event=44",
]
genre = "DRUMFUNK"
impr = "28"
total = "52"
avg = "1.85"
regist = "2008/02/24 00:32"
update = "2008/12/17 03:03"

[[entries]]
no = "9"
name = "zit"
title = "ウタカタノ夢"
size = "14330 KB"
addr = ["http://bisuke.biz/~digizliar/utakata.html"]
genre = "nica/pops"
impr = "21"
total = "17"
avg = "0.8"
regist = "2008/02/24 21:29"
update = "2008/03/02 23:58"

[[entries]]
no = "10"
name = "Ghastly Conceit"
title = "Lament of Mechanical Heart"
size = "18057 KB"
addr = [
    "http://nekokan.dyndns.info/~anonymous/bms/g_conceit/gc_lament.rar",
    "(※音源同梱。)",
]
genre = "INDUSTRIAL"
impr = "29"
total = "54"
avg = "1.86"
regist = "2008/02/24 22:12"
update = "2008/03/03 00:28"

[[entries]]
no = "11"
name = "fity"
title = "Xecus"
size = "13600 KB"
addr = ["http://www.h4.dion.ne.jp/~fity/xecus.rar"]
genre = "Trance core"
impr = "22"
total = "36"
avg = "1.63"
regist = "2008/02/24 22:55"
update = "2008/03/02 23:34"

[[entries]]
no = "12"
name = "zero image teritory"
title = "ametsuchi"
size = "8715 KB"
addr = [
    "http://www.qumarich.net/mirror/ametschi_bga.zip",
    "(BGA)",
    "http://bin.dot908.net/?mode=detail&no=0469",
    "(BMS)",
    "http://www.qumarich.net/mirror/ametsuchi_fixed.zip",
    "(修正差分)",
]
genre = "discopunk / shoegazer"
impr = "22"
total = "26"
avg = "1.18"
regist = "2008/02/24 23:09"
update = "2008/03/02 23:57"

[[entries]]
no = "13"
name = "retu"
title = "jigsaw colors"
size = "15800 KB"
addr = [
    "BGA",
    "http://www.pixellife.x0.to/bms/jigsaw_bga_retu.zip",
    "BMS",
    "http://manbow.nothing.sh/event/event.cgi?action=More_def&num=108&event=44",
]
genre = "_"
impr = "35"
total = "68"
avg = "1.94"
regist = "2008/02/24 23:31"
update = "2008/03/02 23:53"

[[entries]]
no = "14"
name = "じぇふ / TAK vs General"
title = "black opal"
size = "21783 KB"
addr = [
    "[OGG]",
    "http://uploader.bms.ms/data/bgabattle/blackopal_ogg.zip",
    "[WAV(MQ)]",
    "http://uploader.bms.ms/data/bgabattle/blackopal_wav_mq.zip",
]
genre = "NRG"
impr = "24"
total = "27"
avg = "1.12"
regist = "2008/02/24 23:35"
update = "2008/03/02 23:41"

[[entries]]
no = "15"
name = "coda"
title = "そして振動する"
size = "4059 KB"
addr = [
    "BGA",
    "http://www.antennapedia.net/up/sindou.rar",
    "BMS",
    "http://www.commonsense.nu/",
]
genre = "minimal"
impr = "31"
total = "53"
avg = "1.7"
regist = "2008/02/24 23:46"
update = "2008/03/03 01:53"

[[entries]]
no = "16"
name = "iimode-do"
title = "L99"
size = "31535 KB"
addr = [
    "http://iimode-do.jp/obj/l99_with_bga_remake.rar",
    "(BMSと同梱)",
    "http://iimode-do.jp/obj/iimo_l99_bga_remake.rar",
    "(BGAのみ約15MB)",
]
genre = "Progressive Fusion"
impr = "38"
total = "68"
avg = "1.78"
regist = "2008/02/24 23:59"
update = "2008/03/03 02:30"

[[entries]]
no = "17"
name = "kody"
title = "Lapislazuli"
size = "20600 KB"
addr = ["http://nekokan.dyndns.info/~anonymous/bms/Lapislazuli/Lapislazuli_MQ.zip"]
genre = "TRANCE"
impr = "23"
total = "26"
avg = "1.13"
regist = "2008/02/25 00:16"
update = "2008/03/03 02:29"
