[[entries]]
no = "1"
name = "sept-em"
title = "零下の雪原"
size = "3291 KB"
addr = ["http://sept-em.hp.infoseek.co.jp/bms/Amb_.rar"]
genre = "Ambient Trance"
impr = "23"
total = "22"
avg = "0.95"
update = "2002/12/16 16:03"

[[entries]]
no = "2"
name = "青砥竜"
title = "Morning dew"
size = "2971 KB"
addr = ["http://www.ismusic.ne.jp/ryuryu/bms/Morning%20dew.zip"]
genre = "piano ambient"
impr = "20"
total = "24"
avg = "1.2"
update = "2002/12/16 16:13"

[[entries]]
no = "3"
name = "ホシカゲビト⇒美月 正"
title = "キセキの火"
size = "4926 KB"
addr = ["http://puyo-tip.hp.infoseek.co.jp/kisekinohi.lzh"]
genre = "instrumental"
impr = "44"
total = "67"
avg = "1.52"
update = "2002/12/17 09:55"

[[entries]]
no = "4"
name = "Renaissance B.C.→6yen"
title = "pneuma"
size = "3576 KB"
addr = ["http://sapporo.cool.ne.jp/renaissancebc/pneuma.zip"]
genre = "atomosphere"
impr = "25"
total = "42"
avg = "1.68"
update = "2002/12/17 12:06"

[[entries]]
no = "5"
name = "TemporaryFiles (Tempest)"
title = "in deep..."
size = "2306 KB"
addr = ["http://page.freett.com/LOGICAL/BMS.html"]
genre = "ambient"
impr = "10"
total = "7"
avg = "0.7"
update = "2002/12/17 22:46"

[[entries]]
no = "6"
name = "ciel-soa-terre → ridis(Rai)"
title = "時計仕掛けの少女"
size = "4595 KB"
addr = ["http://hat774.hp.infoseek.co.jp/tokeiz.zip"]
genre = "774's TRANCE"
impr = "46"
total = "82"
avg = "1.78"
update = "2002/12/17 08:43"

[[entries]]
no = "7"
name = "maDream → narve"
title = "S"
size = "7741 KB"
addr = ["http://manbow.nothing.sh/ambience_bms/s.rar"]
genre = "Ambient"
impr = "25"
total = "39"
avg = "1.56"
update = "2002/12/17 17:32"

[[entries]]
no = "8"
name = "RUZEEA"
title = "Quay"
size = "4799 KB"
addr = ["http://ruz.s12.xrea.com/winter.html"]
genre = "ambient techno"
impr = "23"
total = "37"
avg = "1.6"
update = "2002/12/16 17:34"

[[entries]]
no = "9"
name = "SOA"
title = "Wintry tonight"
size = "1430 KB"
addr = ["http://homepage3.nifty.com/freeze_soa_31/soa_wt.rar"]
genre = "AMBIENT"
impr = "10"
total = "3"
avg = "0.3"
update = "2002/12/16 17:42"

[[entries]]
no = "10"
name = "RYU!"
title = "B un flash back"
size = "3304 KB"
addr = ["http://nanmin.s4.xrea.com/flash.zip"]
genre = "Ambient"
impr = "11"
total = "12"
avg = "1.09"
update = "2002/12/16 17:51"

[[entries]]
no = "11"
name = "Iolite"
title = "Domine"
size = "4317 KB"
addr = ["http://malie.p-visual.com/"]
genre = "-"
impr = "44"
total = "76"
avg = "1.72"
update = "2002/12/18 17:31"

[[entries]]
no = "12"
name = "ポポス"
title = "illusion forest"
size = "4826 KB"
addr = ["http://mp.digitaljunk.net/popos_okiba/i_forest.rar"]
genre = "ambient"
impr = "13"
total = "9"
avg = "0.69"
update = "2002/12/16 18:20"

[[entries]]
no = "13"
name = "端医者(D.B.)→Lavi*"
title = "takibi"
size = "1287 KB"
addr = ["http://sun.freehost.ne.jp/~shun/data/bms/dairi/00002_takibi.html"]
genre = "ambient"
impr = "18"
total = "18"
avg = "1"
update = "2002/12/17 06:26"

[[entries]]
no = "14"
name = "[A10]"
title = "ユキノハナ"
size = "6956 KB"
addr = ["http://symsystem.hp.infoseek.co.jp/html/music/bms/yukinohana.zip"]
genre = "chill piano"
impr = "8"
total = "11"
avg = "1.37"
update = "2002/12/16 18:43"

[[entries]]
no = "15"
name = "w.a.c.[amorphinism]"
title = "粉雪 -silent snow-"
size = "1550 KB"
addr = ["http://isweb45.infoseek.co.jp/art/chikuwa3/wac/"]
genre = "ambient"
impr = "14"
total = "13"
avg = "0.92"
update = "2002/12/17 19:12"

[[entries]]
no = "16"
name = "w.a.c. [Chikuwa]"
title = "Reverberation"
size = "990 KB"
addr = ["http://isweb45.infoseek.co.jp/art/chikuwa3/wac/"]
genre = "Ambient Electronica"
impr = "14"
total = "13"
avg = "0.92"
update = "2002/12/17 23:00"

[[entries]]
no = "17"
name = "w.a.c. [ワラビ]"
title = "a piece of silence"
size = "2500 KB"
addr = ["http://isweb45.infoseek.co.jp/art/chikuwa3/wac/"]
genre = "Ambient"
impr = "13"
total = "12"
avg = "0.92"
update = "2002/12/18 21:30"

[[entries]]
no = "18"
name = "KOX"
title = "Lofty new trunk"
size = "3394 KB"
addr = ["http://ww5.et.tiki.ne.jp/~hiro_jaxs/lz/KXbmLoft.lzh"]
genre = "AMBIENT"
impr = "5"
total = "0"
avg = "0"
update = "2002/12/16 19:17"

[[entries]]
no = "19"
name = "Fine motion→maklow"
title = "霧氷"
size = "1687 KB"
addr = ["http://linker2.hp.infoseek.co.jp/mhy.lzh"]
genre = "ambient"
impr = "9"
total = "11"
avg = "1.22"
update = "2002/12/18 00:49"

[[entries]]
no = "20"
name = "UrbanSoul"
title = "LandScape"
size = "4855 KB"
addr = ["http://www10.plala.or.jp/kad/LandScape.zip"]
genre = "ambient"
impr = "26"
total = "42"
avg = "1.61"
update = "2002/12/17 23:17"

[[entries]]
no = "21"
name = "REO"
title = "Winter (A.M.B)"
size = "2607 KB"
addr = ["http://big.freett.com/NoSmoking/Winter_AMB.exe"]
genre = "AMBIENT"
impr = "6"
total = "2"
avg = "0.33"
update = "2002/12/16 19:39"

[[entries]]
no = "22"
name = "keep another dream"
title = "unrequited love"
size = "4294 KB"
addr = ["http://www10.plala.or.jp/kad/unrequited.zip"]
genre = "piano ambient"
impr = "30"
total = "52"
avg = "1.73"
update = "2002/12/17 10:35"

[[entries]]
no = "23"
name = "sanan"
title = "崩壊後（短）"
size = "694 KB"
addr = ["http://osaka.cool.ne.jp/xspace/houkaigo.zip"]
genre = "ambient"
impr = "7"
total = "7"
avg = "1"
update = "2002/12/17 21:53"

[[entries]]
no = "24"
name = "Coco"
title = "white dwarf"
size = "2370 KB"
addr = ["http://bmmic.hp.infoseek.co.jp/cocowhite.zip"]
genre = "AMBIENT"
impr = "11"
total = "12"
avg = "1.09"
update = "2002/12/16 23:16"

[[entries]]
no = "25"
name = "Ｍａｔ－Ｔ"
title = "U-topian"
size = "4222 KB"
addr = ["http://homepage1.nifty.com/kei_dash/u-topian.lzh"]
genre = "piano ａｍｂｉｅｎｔ"
impr = "14"
total = "22"
avg = "1.57"
update = "2002/12/16 21:14"

[[entries]]
no = "26"
name = "Milky Lolita→Lavi*"
title = "雪 舞"
size = "3267 KB"
addr = ["http://www.geocities.co.jp/MusicStar-Percussion/2930/ambi.html"]
genre = "---"
impr = "21"
total = "31"
avg = "1.47"
update = "2002/12/18 00:27"

[[entries]]
no = "27"
name = "besessen"
title = "少女強姦願望"
size = "609 KB"
addr = ["http://big.freett.com/nattoumaki/goukan.rar"]
genre = "Irrsinn"
impr = "20"
total = "14"
avg = "0.7"
update = "2002/12/17 02:01"

[[entries]]
no = "28"
name = "RAY"
title = "哀の羽音色"
size = "7110 KB"
addr = ["http://ray5121.hp.infoseek.co.jp/WABE.html"]
genre = "piano ambient"
impr = "30"
total = "51"
avg = "1.7"
update = "2002/12/16 21:45"

[[entries]]
no = "29"
name = "Gun-SEKI"
title = "Snowy City"
size = "1864 KB"
addr = ["http://www.aya.or.jp/~naga/snowycity.rar"]
genre = "LOUNGE"
impr = "21"
total = "37"
avg = "1.76"
update = "2002/12/16 21:56"

[[entries]]
no = "30"
name = "Is-m"
title = "silver flower"
size = "4840 KB"
addr = ["http://www1.linkclub.or.jp/~is-m/silver_flower.rar"]
genre = "POPS"
impr = "20"
total = "17"
avg = "0.85"
update = "2002/12/16 23:49"

[[entries]]
no = "31"
name = "Y.Z.R."
title = "26.December"
size = "4220 KB"
addr = ["http://isweb42.infoseek.co.jp/art/yuzuru03/main/BMS/26.December.rar"]
genre = "PIANO AMBIENT"
impr = "17"
total = "26"
avg = "1.52"
update = "2002/12/16 23:11"

[[entries]]
no = "32"
name = "Snow drop"
title = "White warmness"
size = "4986 KB"
addr = ["http://snowdrop-pure.hp.infoseek.co.jp/music/ww.rar"]
genre = "ballad"
impr = "12"
total = "19"
avg = "1.58"
update = "2002/12/16 22:20"

[[entries]]
no = "33"
name = "hakoneko"
title = "temperature"
size = "1282 KB"
addr = ["http://www.ismusic.ne.jp/hakoneko/b/temperature.zip"]
genre = "Experimental"
impr = "16"
total = "20"
avg = "1.25"
update = "2002/12/16 23:05"
