[[entries]]
no = "1"
name = "rich"
title = "LOCK,STOCK AND TWO SMOKING BARRELS"
size = "15350 KB"
addr = ["http://uploader.bms.ms/data/maxbeat/lock.rar"]
genre = "-"
impr = "18"
total = "16"
avg = "0.88"
regist = "2008/03/20 00:01"
update = "2008/04/29 22:28"

[[entries]]
no = "2"
name = "Seren"
title = "uNBRiDLeD"
size = "6679 KB"
addr = ["http://bm2dx.dip.jp/prismatica/yuki/unbridled.zip"]
genre = "SPEEDCORE"
impr = "14"
total = "6"
avg = "0.42"
regist = "2008/03/20 00:04"
update = "2008/03/30 22:20"

[[entries]]
no = "3"
name = "tetu"
title = "Red Scream"
size = "2710 KB"
addr = ["http://magamiyuuya.hp.infoseek.co.jp/RedScreamBMS.lzh"]
genre = "HARDCORE TECHNO"
impr = "11"
total = "2"
avg = "0.18"
regist = "2008/03/20 00:22"
update = "2008/03/30 20:25"

[[entries]]
no = "4"
name = "MIX-MAX"
title = "444"
size = "9130 KB"
addr = ["別の生き物に生まれ変わります"]
genre = "BREAK CORE"
impr = "13"
total = "5"
avg = "0.38"
regist = "2008/03/20 00:23"
update = "2010/02/22 11:18"

[[entries]]
no = "5"
name = "Est"
title = "torte"
size = "11086 KB"
addr = ["http://uploader.bms.ms/data/maxbeat/est_torte.zip"]
genre = "BREAKCORE"
impr = "17"
total = "15"
avg = "0.88"
regist = "2008/03/20 01:24"
update = "2008/04/01 22:32"

[[entries]]
no = "6"
name = "scytheleg"
title = "Singin' to Myself"
size = "19656 KB"
addr = [
    "http://uploader.bms.ms/data/maxbeat/stl_pmc-stm.rar",
    "(無圧縮 19,656KB)",
    "http://www4.pf-x.net/~scytheleg/tempyou/music/pmc/bms/stm/stl_pmc-stmLQ.rar",
    "(LQ版 10,080KB)",
]
genre = "Light Punk"
impr = "18"
total = "9"
avg = "0.5"
regist = "2008/03/20 02:31"
update = "2009/12/02 13:45"

[[entries]]
no = "7"
name = "D-3aid"
title = "Minimam Hades"
size = "0 KB"
addr = [
    "本日を持って削除させていただきます。",
    "もうしわけないです。。。",
]
genre = "NU-STYLE TECHNO"
impr = "13"
total = "3"
avg = "0.23"
regist = "2008/03/20 03:12"
update = "2008/06/07 12:53"

[[entries]]
no = "8"
name = "SKz"
title = "psy:de;lic"
size = "000 KB"
addr = ["させない"]
genre = "psychedelic bass core"
impr = "18"
total = "6"
avg = "0.33"
regist = "2008/03/20 04:48"
update = "2008/06/19 15:45"

[[entries]]
no = "9"
name = "LR44"
title = "魔王"
size = "39420 KB"
addr = ["http://uploader.bms.ms/data/maxbeat/maoh.rar"]
genre = "HARDCORE"
impr = "21"
total = "18"
avg = "0.85"
regist = "2008/03/20 14:19"
update = "2008/03/30 21:35"

[[entries]]
no = "10"
name = "(>o<)ku3"
title = "THE BLACK OCEAN"
size = "1386 KB"
addr = ["http://ku-snow.infoseek.ne.jp/koubm.rar"]
genre = "DRUM`n HARD CORE"
impr = "12"
total = "3"
avg = "0.25"
regist = "2008/03/20 21:11"
update = "2008/03/30 20:51"

[[entries]]
no = "11"
name = "Coco"
title = "ZIGGGY"
size = "4640 KB"
addr = ["http://www.geocities.jp/coco_bms_xxxxxx/zigggy.zip"]
genre = "hardcore breakbeats"
impr = "12"
total = "12"
avg = "1"
regist = "2008/03/20 23:38"
update = "2008/03/30 23:33"

[[entries]]
no = "12"
name = "CRUNCH"
title = "BABEL"
size = "1650 KB"
addr = ["http://3rd.geocities.jp/accessflight/BABEL.zip"]
genre = "BREAK CORE"
impr = "18"
total = "16"
avg = "0.88"
regist = "2008/03/21 01:29"
update = "2008/03/31 17:12"

[[entries]]
no = "13"
name = "czardas"
title = "Mona Lisa overdrive"
size = "12770 KB"
addr = [
    "http://uploader.bms.ms/data/maxbeat/monalisaoverdrive_ogg.rar",
    "http://uploader.bms.ms/data/maxbeat/monalisaoverdrive_wav.rar",
]
genre = "chaotic hardcore"
impr = "37"
total = "31"
avg = "0.83"
regist = "2008/03/21 05:15"
update = "2008/03/30 23:39"

[[entries]]
no = "14"
name = "Maddestrose"
title = "is NOT music"
size = "5532 KB"
addr = ["http://stoicsounds.matrix.jp/isnotmusic.zip"]
genre = "SPEEEETEK"
impr = "28"
total = "11"
avg = "0.39"
regist = "2008/03/21 12:45"
update = "2009/11/10 15:25"

[[entries]]
no = "15"
name = "xi"
title = "FREEDOM DiVE↓"
size = "28141 KB"
addr = [
    "http://uploader.bms.ms/data/maxbeat/xi_freedom_dive.zip",
    "http://uploader.bms.ms/data/maxbeat/xi_HQ_update.zip",
]
genre = "HAPPY HARDCORE"
impr = "25"
total = "23"
avg = "0.92"
regist = "2008/03/21 12:58"
update = "2008/04/01 09:59"

[[entries]]
no = "16"
name = "樟"
title = "Flashback"
size = "1446 KB"
addr = ["http://tokyo.cool.ne.jp/rysu78/flashback.zip"]
genre = "Industrial"
impr = "15"
total = "15"
avg = "1"
regist = "2008/03/21 19:12"
update = "2008/03/30 23:14"

[[entries]]
no = "17"
name = "mommy"
title = "AIRSHAVER"
size = "6900 KB"
addr = ["http://mommy16807.up.seesaa.net/image/airshaver.zip"]
genre = "PROGRESSIVE"
impr = "28"
total = "26"
avg = "0.92"
regist = "2008/03/23 00:24"
update = "2008/04/01 01:26"

[[entries]]
no = "18"
name = "Nitrix"
title = "Reason Breaker"
size = "3832 KB"
addr = ["http://page.freett.com/nitrix/maxbeat.html"]
genre = "SPEED CORE"
impr = "21"
total = "20"
avg = "0.95"
regist = "2008/03/23 01:33"
update = "2008/03/30 23:19"

[[entries]]
no = "19"
name = "_"
title = "atonement you you"
size = "3810 KB"
addr = ["http://uploader.bms.ms/data/maxbeat/02_ayy.rar"]
genre = "_"
impr = "20"
total = "20"
avg = "1"
regist = "2008/03/23 02:06"
update = "2008/03/30 23:51"

[[entries]]
no = "20"
name = "TOMA"
title = "パペットガール"
size = "2637 KB"
addr = ["http://estish.hp.infoseek.co.jp/bms/pg.zip"]
genre = "HARDCORE"
impr = "12"
total = "12"
avg = "1"
regist = "2008/03/23 13:37"
update = "2008/04/01 22:42"

[[entries]]
no = "21"
name = "4G"
title = "Crimson Wind"
size = "12360 KB"
addr = ["http://www7a.biglobe.ne.jp/~furiefurie/bms/crimsonwind.rar"]
genre = "GUITAR WALTZ"
impr = "12"
total = "5"
avg = "0.41"
regist = "2008/03/23 15:52"
update = "2008/03/30 21:38"

[[entries]]
no = "22"
name = "kjhg"
title = "My dream"
size = "4116 KB"
addr = ["http://briefcase.yahoo.co.jp/bc/poispoos/lst?&.dir=/461b&.src=bc&"]
genre = "HAPPY HARD CORE"
impr = "10"
total = "3"
avg = "0.3"
regist = "2008/03/23 17:12"
update = "2008/03/30 22:23"

[[entries]]
no = "23"
name = "daiji+lobsak"
title = "Happy☆mooN"
size = "7060 KB"
addr = ["http://uploader.bms.ms/data/maxbeat/happymoon_s.zip"]
genre = "HHP"
impr = "11"
total = "5"
avg = "0.45"
regist = "2008/03/23 18:47"
update = "2008/03/30 22:24"

[[entries]]
no = "24"
name = "sfjjjjjj"
title = "Op.61 Pf Sonatine 3"
size = "10619 KB"
addr = ["https://drive.google.com/open?id=1qJOwO5R5Z3s1wPdBRSNp_Y8374M8ylhK"]
genre = "MINUETTO"
impr = "13"
total = "7"
median = "0"
avg = "0.53"
regist = "2008/03/24 01:38"
update = "2018/02/13 16:37"

[[entries]]
no = "25"
name = "FT 718"
title = "musicide -BMS Version-"
size = "18652 KB"
addr = [
    "http://uploader.bms.ms/data/maxbeat/musicide%20bms%20lq.zip",
    "改訂版mp3→",
    "http://sound.jp/ft718/ft718music.html",
]
genre = "Terror Core"
impr = "10"
total = "1"
avg = "0.1"
regist = "2008/03/24 16:02"
update = "2011/09/19 03:23"

[[entries]]
no = "26"
name = "ADAM SYSTEM"
title = "YILDRIM"
size = "4530 KB"
addr = ["http://atsp.bms.ms/bms08/9_adamsystem_yildrim-lq.zip"]
genre = "SPEED FUNK"
impr = "19"
total = "14"
avg = "0.73"
regist = "2008/03/24 19:22"
update = "2008/03/30 23:59"

[[entries]]
no = "27"
name = "ELE-G"
title = "Lobotomy"
size = "7800 KB"
addr = ["ヾ(･ω･)ｼ"]
genre = "Drill'n bass"
impr = "24"
total = "24"
avg = "1"
regist = "2008/03/24 22:03"
update = "2008/03/31 00:28"

[[entries]]
no = "28"
name = "ルゼ"
title = "戦歌「オルグラリヤ」"
size = "4530 KB"
addr = ["さよなら"]
genre = "DEATH CORE"
impr = "46"
total = "24"
avg = "0.52"
regist = "2008/03/24 22:53"
update = "2008/03/31 00:13"

[[entries]]
no = "29"
name = "Yamajet"
title = "Overslept"
size = "2046 KB"
addr = [
    "http://yamajet.bms.ms/bms/data/yamajet_overslept.rar",
    "http://yamajet.bms.ms/bms/data/yamajet_overslept_wavlq.rar",
]
genre = "Punk Pop"
impr = "30"
total = "29"
avg = "0.96"
regist = "2008/03/24 23:40"
update = "2012/02/23 21:42"

[[entries]]
no = "30"
name = "9索敵/8"
title = "逃亡"
size = "4263 KB"
addr = [
    "http://uploader.bms.ms/data/maxbeat/sktk-tobo.rar",
    "HQは14067KBです。",
    "http://uploader.bms.ms/data/maxbeat/sk-HQ-tk-tobo.rar",
]
genre = "STE:P"
impr = "22"
total = "22"
avg = "1"
regist = "2008/03/24 23:40"
update = "2008/03/31 18:30"

[[entries]]
no = "31"
name = "Frost_Shrike"
title = "rubbles of memories"
size = "3106 KB"
addr = ["http://www.geocities.jp/shimomozu/FrS06_rubbles_of_memories-ogg.zip"]
genre = "recollection"
impr = "14"
total = "14"
avg = "1"
regist = "2008/03/24 23:52"
update = "2008/03/30 23:56"
