[[entries]]
no = "1"
name = "FALL"
title = "androids dream of humans"
size = "4562 KB"
addr = ["http://page.freett.com/fall_music/androids.html"]
genre = "TECHNO POP"
impr = "8"
total = "22"
avg = "2.75"
regist = "2008/04/12 15:38"
update = "2008/04/27 13:03"

[[entries]]
no = "2"
name = "加賀崎聡"
title = "Fancy Phunky Madness"
size = "8688 KB"
addr = [
    "http://www.qumarich.net/bms/sk_fpm_hq.rar",
    "8688KB",
    "http://www.qumarich.net/bms/sk_fpm_lq.rar",
    "2522KB",
]
genre = "sweet delicious samples"
impr = "9"
total = "20"
avg = "2.22"
regist = "2008/04/13 23:50"
update = "2008/04/28 01:38"

[[entries]]
no = "3"
name = "MIX-MAX"
title = "Little Heaven"
size = "4935 KB"
addr = ["別の生き物に生まれ変わります"]
genre = "DRUM'N'BASS"
impr = "8"
total = "15"
avg = "1.87"
regist = "2008/04/13 23:57"
update = "2010/02/22 11:21"

[[entries]]
no = "4"
name = "glustar"
title = "In the sunrise blue"
size = "41900 KB"
addr = ["http://www.geocities.jp/seven_colors_pallet/itsb.html"]
genre = "-"
impr = "7"
total = "15"
avg = "2.14"
regist = "2008/04/16 01:20"
update = "2011/02/25 19:19"
