[[entries]]
no = "1"
name = "dj Extrose"
title = "KBC Twilight"
size = "28768 KB"
addr = [
    "http://stoicsounds.matrix.jp/kbctwilight.zip",
    "http://stoicsounds.matrix.jp/kbctwilight_lq.zip",
]
genre = "BREAK TECHNO"
impr = "39"
total = "47"
avg = "1.2"
regist = "2008/06/13 00:10"
update = "2010/01/24 07:23"

[[entries]]
no = "2"
name = "4G"
title = "SACA"
size = "16287 KB"
addr = ["http://www7a.biglobe.ne.jp/~furiefurie/bms/4g_saca.rar"]
genre = "HEALING POP"
impr = "34"
total = "56"
avg = "1.64"
regist = "2008/06/13 00:26"
update = "2008/06/30 23:51"

[[entries]]
no = "3"
name = "Sassy"
title = "AQUA"
size = "27502 KB"
addr = ["http://page.freett.com/mbemsa2/aqua.htm"]
genre = "TECHNO"
impr = "34"
total = "30"
avg = "0.88"
regist = "2008/06/13 00:32"
update = "2008/07/03 00:09"

[[entries]]
no = "4"
name = "stereoberry"
title = "遠い星のライカ"
size = "2850 KB"
addr = [
    "http://salad.vivian.jp/music/laika_ogg.rar",
    "(2.85MB)",
    "http://salad.vivian.jp/music/laika.rar",
    "(WAV-HQ 16.1MB)",
    "http://salad.vivian.jp/music/laika_lq.rar",
    "(WAV-LQ 6.6MB)",
]
genre = "alternative"
impr = "52"
total = "142"
avg = "2.73"
regist = "2008/06/13 01:08"
update = "2008/06/30 23:57"

[[entries]]
no = "5"
name = "猫の人"
title = "さささ"
size = "18554 KB"
addr = ["http://page.freett.com/nekonohito/sasasa.htm"]
genre = "ポップ"
impr = "32"
total = "69"
avg = "2.15"
regist = "2008/06/13 01:27"
update = "2008/06/30 23:52"

[[entries]]
no = "6"
name = "みずいろおおかみ"
title = "まっしろケーキの丘"
size = "34828 KB"
addr = [
    "http://kobagame.hp.infoseek.co.jp/bms/whitecake.zip",
    "http://nekokan.dyndns.info/~anonymous/whitecakehq.rar",
]
genre = "Kirby Pop"
impr = "34"
total = "60"
avg = "1.76"
regist = "2008/06/13 01:28"
update = "2009/12/26 12:42"

[[entries]]
no = "7"
name = "DEMK"
title = "Can you help me? [BMS edit]"
size = "15293 KB"
addr = [
    "http://demk.net/can_you_help_me_HQ.rar",
    "http://demk.net/can_you_help_me_LQ.rar",
]
genre = "JAPANESE TRANCE"
impr = "46"
total = "112"
avg = "2.43"
regist = "2008/06/13 03:58"
update = "2008/06/30 23:58"

[[entries]]
no = "8"
name = "nmk"
title = "Awaking Beat"
size = "11638 KB"
addr = [
    "LQ:",
    "http://mio-hosina.tn.st/bms/Awaking%20Beat-LQ.zip",
    "HQ:",
    "http://mio-hosina.tn.st/bms/Awaking%20Beat-HQ.zip",
]
genre = "EUROBEAT"
impr = "23"
total = "26"
avg = "1.13"
regist = "2008/06/13 07:21"
update = "2008/06/30 23:54"

[[entries]]
no = "9"
name = "DJ KU-"
title = "JUMPING USSA!!"
size = "1001 KB"
addr = ["http://ku-snow.hp.infoseek.co.jp/ussa.rar"]
genre = "BUCHIAGE TRANCE"
impr = "36"
total = "54"
avg = "1.5"
regist = "2008/06/13 23:03"
update = "2008/07/03 20:48"

[[entries]]
no = "10"
name = "syzfonics"
title = "BLAST"
size = "6726 KB"
addr = [
    "wav+bmp",
    "http://syzf.108shiki.com/bms/syzf-blast.rar",
    "ogg+png",
    "http://syzf.108shiki.com/bms/syzf-blast-oggpng.rar",
]
genre = "NU STYLE GABBA"
impr = "42"
total = "98"
avg = "2.33"
regist = "2008/06/14 15:59"
update = "2011/02/25 18:50"

[[entries]]
no = "11"
name = "L-more"
title = "Love Entropy"
size = "3190 KB"
addr = [
    "http://lie.or.tp/couloir/bms/love_entropy_wav.rar",
    "http://lie.or.tp/couloir/bms/love_entropy_ogg.rar",
]
genre = "Cornish"
impr = "39"
total = "95"
avg = "2.43"
regist = "2008/06/14 19:13"
update = "2008/06/30 23:57"

[[entries]]
no = "12"
name = "MIX-MAX"
title = "EXPLOSIVE HEAD"
size = "7437 KB"
addr = ["http://freett.com/mixmax412/music/ex_head.html"]
genre = "HARD TECHNO"
impr = "35"
total = "88"
avg = "2.51"
regist = "2008/06/15 16:03"
update = "2008/06/30 23:56"

[[entries]]
no = "13"
name = "CRUNCH"
title = "grief"
size = "3590 KB"
addr = [
    "http://3rd.geocities.jp/accessflight/grief.zip",
    "http://image30.bannch.com/bs/M302/bbs/161129/img/0100072747.rar",
    "http://www.qumarich.net/a-1/upload/grief.rar",
    "http://www.qumarich.net/a-1/upload/grief.zip",
    "念のため主催側でミラーリングさせていただきました。",
]
genre = "ART CORE"
impr = "30"
total = "47"
avg = "1.56"
regist = "2008/06/15 18:44"
update = "2008/07/01 02:04"

[[entries]]
no = "14"
name = "Ym1024"
title = "the True Air"
size = "7159 KB"
addr = [
    "http://page.freett.com/mirrorspace/air.htm",
    "（08/07/01更新）",
]
genre = "Airy Trance"
impr = "42"
total = "87"
avg = "2.07"
regist = "2008/06/15 21:45"
update = "2008/07/01 01:03"

[[entries]]
no = "15"
name = "sfjjjjjj"
title = "Venus(the Bringer of Peace)"
size = "2500 KB"
addr = ["http://music.geocities.jp/froature/info.html"]
genre = "MA-2"
impr = "30"
total = "28"
avg = "0.93"
regist = "2008/06/15 23:34"
update = "2008/06/30 23:57"

[[entries]]
no = "16"
name = "DJ Saw-Low"
title = "Tamano ～粋々～ RAVE"
size = "13289 KB"
addr = ["http://uploader.bms.ms/data/A1/djsl__trave.rar"]
genre = "BON RAVE"
impr = "29"
total = "60"
avg = "2.06"
regist = "2008/06/15 23:50"
update = "2008/12/13 17:28"

[[entries]]
no = "17"
name = "BACO"
title = "Brain Analysis"
size = "23478 KB"
addr = [
    "http://www3.pf-x.net/~boxism-8500/bms.php",
    "(一覧ページの一番上の作品です)",
    "http://www.qumarich.net/a-1/upload/brain_analysis_HQ.rar",
    "(大会期間限定高音質版 53295KB)",
    "以下zip版(大会期間限定)",
    "http://www.qumarich.net/a-1/upload/brain_analysis.zip",
    "(LQ-WAV 25189KB)",
    "http://www.qumarich.net/a-1/upload/brain_analysis_OGG.zip",
    "(HQ-OGG 27970KB)",
    "http://www.qumarich.net/a-1/upload/brain_analysis_HQ.zip",
    "(HQ-WAV 79376KB)",
]
genre = "Psychedelic Trance"
impr = "45"
total = "125"
avg = "2.77"
regist = "2008/06/15 23:57"
update = "2008/07/01 01:38"
