[[entries]]
no = "1"
name = "-"
title = "-"
size = "0 KB"
addr = ["-"]
genre = "-"
impr = "2"
total = "20"
avg = "10"
regist = "2008/09/23 02:54"
update = "2010/08/23 19:27"

[[entries]]
no = "2"
name = "BACO"
title = "Game-8bit-"
size = "42 KB"
addr = [
    "http://www.geocities.jp/octa124/music/game.zip",
    "(右クリック保存)",
]
genre = "8bit"
impr = "3"
total = "30"
avg = "10"
regist = "2008/09/23 03:36"
update = "2008/09/28 23:16"

[[entries]]
no = "3"
name = "ルゼ vs ドヴォルジャーク cf. FinalOffset"
title = "Rave New World - Not Enduras Mix -"
size = "2421 KB"
addr = ["http://www.luzeria.net/music/42_rnw_nem.rar"]
genre = "Press X"
impr = "4"
total = "40"
avg = "10"
regist = "2008/09/23 04:03"
update = "2008/09/28 11:30"

[[entries]]
no = "4"
name = "Xacla"
title = "Sunlight"
size = "7242 KB"
addr = ["http://flrecords.info/files/xacla-sunlight.rar"]
genre = "Euphoric Trance"
impr = "6"
total = "60"
avg = "10"
regist = "2008/09/23 07:15"
update = "2008/09/28 23:17"

[[entries]]
no = "5"
name = "Macadamia Shorthead"
title = "135"
size = "573 KB"
addr = ["http://dustc.biz/bms/mac135.rar"]
genre = "goregrind"
impr = "2"
total = "20"
avg = "10"
regist = "2008/09/23 13:06"
update = "2008/09/29 23:06"

[[entries]]
no = "6"
name = "Ultra Violette"
title = "The 23rd Hour"
size = "8991 KB"
addr = ["http://x-raise.cjb.net/bms_dl/bms_the_23rd_hour.rar"]
genre = "DOWNTEMPO NOISECORE"
impr = "2"
total = "20"
avg = "10"
regist = "2008/09/23 13:17"
update = "2008/09/27 21:18"

[[entries]]
no = "7"
name = "void"
title = "Precipitance"
size = "20506 KB"
addr = ["http://www.mournfinale.com/bof2008/24hour.html"]
genre = "Euphoric Progress"
impr = "5"
total = "50"
avg = "10"
regist = "2008/09/23 13:45"
update = "2008/09/28 23:18"

[[entries]]
no = "8"
name = "秋目漱石"
title = "lkdshrgdfhjozs"
size = "1968 KB"
addr = ["http://rokiss.net/up/src/rokiss0071.zip"]
genre = "techno"
impr = "2"
total = "20"
avg = "10"
regist = "2008/09/23 15:05"
update = "2008/09/27 21:19"

[[entries]]
no = "9"
name = "SKz"
title = "Night city"
size = "18424 KB"
addr = ["http://www7b.biglobe.ne.jp/~ssbossmix/Night_city_LQ.zip"]
genre = "Electro House"
impr = "3"
total = "30"
avg = "10"
regist = "2008/09/23 17:33"
update = "2010/01/08 15:44"

[[entries]]
no = "10"
name = "Sampling Meister KAGA"
title = "YOUNGLIFE"
size = "4390 KB"
addr = ["http://www.qumarich.net/bms/smkaga_younglife_hq.rar"]
genre = "DISTORTION"
impr = "3"
total = "30"
avg = "10"
regist = "2008/09/23 18:12"
update = "2008/09/29 00:42"

[[entries]]
no = "11"
name = "Est"
title = "KIRAMEKI OVERDRIVE"
size = "4077 KB"
addr = [
    "http://nekokan.dyndns.info/%7Eanonymous/24hours/kirameki_rmx.zip",
    "http://nekokan.dyndns.info/%7Eanonymous/24hours/kirameki_rmx_hq.zip",
]
genre = "TRANCE POP"
impr = "3"
total = "30"
avg = "10"
regist = "2008/09/23 19:19"
update = "2009/12/20 13:35"

[[entries]]
no = "12"
name = "yellowberry"
title = "Lack of sleep"
size = "536 KB"
addr = [
    "http://www2.atpages.jp/yellowberry/luck.zip",
    "http://www2.atpages.jp/yellowberry/luck_ogg.zip",
]
genre = "techno"
impr = "7"
total = "70"
avg = "10"
regist = "2008/09/23 19:37"
update = "2008/09/27 21:42"

[[entries]]
no = "13"
name = "D11X"
title = "MonochromeWonderful"
size = "4499 KB"
addr = ["http://asdf.bms.ms/junk/bms/d11_21_monowonderful.zip"]
genre = "strangesteps"
impr = "2"
total = "20"
avg = "10"
regist = "2008/09/23 20:25"
update = "2008/10/26 17:48"

[[entries]]
no = "14"
name = "cinako"
title = "but I fly -discoflyer arrangement-"
size = "4548 KB"
addr = ["http://lie.or.tp/couloir/bms/butiflyarr.rar"]
genre = "Electro"
impr = "6"
total = "60"
avg = "10"
regist = "2008/09/23 21:58"
update = "2012/04/27 19:36"

[[entries]]
no = "15"
name = "daiji+lobsak"
title = "冬色遊興～angelic snow～"
size = "7980 KB"
addr = ["http://uploader.bms.ms/data/bof2008/angelic%20snow_ogg%20.zip"]
genre = "Instrumental"
impr = "4"
total = "40"
avg = "10"
regist = "2008/09/23 22:33"
update = "2008/10/01 23:26"

[[entries]]
no = "16"
name = "scytheleg"
title = "BB Tech"
size = "4608 KB"
addr = ["http://scytheleg.bms.ms/tempyou/music/bms/bbtech/stl_bbtech.rar"]
genre = "Techno Pop"
impr = "6"
total = "60"
avg = "10"
regist = "2008/09/23 23:03"
update = "2008/09/28 23:49"

[[entries]]
no = "17"
name = "東京着いたらまず外回りで2駅ほど"
title = "せせらぎ"
size = "657 KB"
addr = [
    "http://www.geocities.jp/nekomimimaid_ryo/bms/seseragi.zip",
    "（右クリックより保存）",
]
genre = "UNI-PEX"
impr = "3"
total = "30"
avg = "10"
regist = "2008/09/23 23:08"
update = "2008/09/28 23:20"

[[entries]]
no = "18"
name = "イズミケイ"
title = "Fragment blue"
size = "3912 KB"
addr = ["http://prsq.sakura.ne.jp/ismk_bms/fb_ogg.rar"]
genre = "PROGRESSIVE TRANCE"
impr = "7"
total = "70"
avg = "10"
regist = "2008/09/23 23:32"
update = "2008/09/28 23:20"

[[entries]]
no = "19"
name = "みずいろおおかみ"
title = "笛吹きの少年とバイオリン弾きの少女"
size = "3428 KB"
addr = ["http://kobagame.hp.infoseek.co.jp/bms/march.zip"]
genre = "March"
impr = "3"
total = "30"
avg = "10"
regist = "2008/09/23 23:34"
update = "2008/09/28 23:50"

[[entries]]
no = "20"
name = "CRUNCH"
title = "クレパス"
size = "4844 KB"
addr = [
    "http://3rd.geocities.jp/accessflight/kurepasuogg.zip",
    "ogg版 (2099KB)",
    "http://3rd.geocities.jp/accessflight/kurepasuwavlq.zip",
    "wav LQ版 (4844KB)",
]
genre = "NORTHERN TRANCY HOUSE"
impr = "3"
total = "30"
avg = "10"
regist = "2008/09/23 23:34"
update = "2008/09/29 00:56"

[[entries]]
no = "21"
name = "keoui"
title = "B POP MAGIC"
size = "23544 KB"
addr = [
    "http://milky.geocities.jp/keoui98/keoui_bpm135.zip",
    "（wav版 24MB）",
    "http://milky.geocities.jp/keoui98/keoui_bpm135_ogg.zip",
    "（ogg版 4MB）",
]
genre = "BPM135"
impr = "1"
total = "10"
avg = "10"
regist = "2008/09/23 23:51"
update = "2008/09/27 21:22"

[[entries]]
no = "22"
name = "霜鵙"
title = "秋の空き屋敷"
size = "2400 KB"
addr = ["http://dabxrayyellow148.hp.infoseek.co.jp/FrS07_akinoakiyashiki.zip"]
genre = "game"
impr = "1"
total = "10"
avg = "10"
regist = "2008/09/23 23:53"
update = "2008/09/27 21:22"

[[entries]]
no = "23"
name = "moriga"
title = "WAR WAR WAR"
size = "4727 KB"
addr = ["http://uploader.bms.ms/data/bof2008/war.rar"]
genre = "HARD MINIMAL"
impr = "6"
total = "60"
avg = "10"
regist = "2008/09/23 23:55"
update = "2008/09/28 23:20"

[[entries]]
no = "24"
name = "MIX-MAX"
title = "French Fries"
size = "0 KB"
addr = ["パワーアップ中"]
genre = "TECHNO"
impr = "4"
total = "40"
avg = "10"
regist = "2008/09/23 23:56"
update = "2010/02/22 11:28"

[[entries]]
no = "25"
name = "OXYGEN"
title = "TRIP WITH PARTY"
size = "21272 KB"
addr = ["http://zatsuzatsu.sosite.jp/img/bmsfile/twp.zip"]
genre = "WORLD ENSEMBLE"
impr = "5"
total = "50"
avg = "10"
regist = "2008/09/23 23:56"
update = "2008/09/28 06:45"

[[entries]]
no = "26"
name = "バーモントカレー"
title = "love saves bms."
size = "2210 KB"
addr = ["http://big.freett.com/barmontcarry/lsb.rar"]
genre = "house"
impr = "1"
total = "10"
avg = "10"
regist = "2008/09/23 23:59"
update = "2008/09/27 21:23"
