[[entries]]
no = "1"
name = "S.P.S.B."
title = "胎動"
size = "50000 KB"
addr = ["http://uploader.bms.ms/data/bof2008/SPSBtd.zip"]
genre = "EPILOGUE"
impr = "7"
total = "7"
avg = "1"
regist = "2008/10/22 02:32"
update = "2008/11/09 23:59"

[[entries]]
no = "2"
name = "muhi"
title = "おいしいふりかけ"
size = "5980 KB"
addr = ["http://nekokan.dyndns.info/~anonymous/bof2008/muhi/furikake_bga.zip"]
genre = "鮭Break"
impr = "12"
total = "12"
avg = "1"
regist = "2008/10/22 19:49"
update = "2008/11/14 18:49"

[[entries]]
no = "3"
name = "( ﾟдﾟ)P"
title = "S@MBISTER"
size = "5230 KB"
addr = ["http://uploader.bms.ms/data/bof2008/sambista_imas_bmp.zip"]
genre = "HARD DANCE"
impr = "5"
total = "5"
avg = "1"
regist = "2008/10/27 02:58"
update = "2008/11/09 23:58"

[[entries]]
no = "4"
name = "3034"
title = "Fastraffic"
size = "18423 KB"
addr = [
    "DL Site 1 :",
    "http://litania.egloos.com/2428414",
    "DL Site 2 :",
    "http://blog.naver.com/lch0234/40068765558",
]
genre = "techno"
impr = "5"
total = "5"
avg = "1"
regist = "2008/10/29 03:31"
update = "2009/07/05 01:27"

[[entries]]
no = "5"
name = "Mentalstock"
title = "Absurd Gaff"
size = "15100 KB"
addr = ["http://uploader.bms.ms/data/bof2008/siromaru_mentalstock_absurd_gaff.zip"]
genre = "Schranz"
impr = "7"
total = "7"
avg = "1"
regist = "2008/10/29 23:25"
update = "2008/11/09 23:55"

[[entries]]
no = "6"
name = "iimode-do / siromaru"
title = "Absurd Gaff"
size = "16413 KB"
addr = [
    "http://iimode-do.jp/obj/siromaru_absurd_gaff_iimobga.rar",
    "(BGAのみ)",
    "http://manbow.nothing.sh/event/event.cgi?action=More_def&num=11&event=54",
    "(BMS)",
]
genre = "schranz"
impr = "4"
total = "4"
avg = "1"
regist = "2008/11/03 20:56"
update = "2010/01/24 07:07"

[[entries]]
no = "7"
name = "kody/dust.c"
title = "Maria"
size = "55758 KB"
addr = ["http://dustc.biz/bms/maria_ogg.rar"]
genre = "Drum'n'bass"
impr = "3"
total = "3"
avg = "1"
regist = "2008/11/03 23:38"
update = "2008/11/10 01:04"

[[entries]]
no = "8"
name = "vj Eks/siromaru"
title = "Absurd Gaff"
size = "12125 KB"
addr = [
    "http://stoicsounds.ath.cx/evdata/bmsafter/absurdgaff_vjeks_lq.rar",
    "http://stoicsounds.ath.cx/evdata/bmsafter/absurdgaff_vjeks_hq.rar",
]
genre = "schranz"
impr = "3"
total = "3"
avg = "1"
regist = "2008/11/04 00:44"
update = "2012/04/28 09:31"
