[[entries]]
no = "1"
name = "NECOX respect Syatten"
title = "Syatten RESPECT BMS"
size = "8110 KB"
addr = [
    "http://nekomimi.bms.ms/bms/necox_beyo---nd_HQogg.rar",
    "[USB2.0は8.11MB]",
    "http://nekomimi.bms.ms/bms/necox_beyo---nd.rar",
    "[USB1.1は8.13MB]",
]
genre = "Thank You"
impr = "8"
total = "16"
avg = "2"
regist = "2008/11/03 00:06"
update = "2008/11/12 00:36"

[[entries]]
no = "2"
name = "ももやま"
title = "なんと新曲が4曲しか入ってない(ｒｙ"
size = "2217 KB"
addr = ["http://www.geocities.jp/pink_no_cool/BMS/momohimeaisiteru.htm"]
genre = "ぷろぐれっしぶみにまむとふぁんたじーてぃうんてぃうんとふりーむきじゃずと旧曲(お好みでぴんくるーむと類似も追加できます)"
impr = "4"
total = "9"
avg = "2.25"
regist = "2008/11/03 11:06"
update = "2008/11/11 01:17"

[[entries]]
no = "3"
name = "ホーネット スミス"
title = "デザートイーグルは大変な反動を残していきました"
size = "700 KB"
addr = ["http://fa18af.sakura.ne.jp/foon2008/de50.html"]
genre = "GUN SOUND"
impr = "3"
total = "9"
avg = "3"
regist = "2008/11/03 12:55"
update = "2008/11/16 23:42"

[[entries]]
no = "4"
name = "億万"
title = "連打の達人"
size = "34 KB"
addr = ["製造中止"]
genre = "音楽ゲーム"
impr = "4"
total = "9"
avg = "2.25"
regist = "2008/11/03 16:32"
update = "2010/02/22 11:22"

[[entries]]
no = "5"
name = "；"
title = "インテル"
size = "50000 KB"
addr = ["http://uploader.bms.ms/data/ee.zip"]
genre = "CM"
impr = "3"
total = "11"
avg = "3.66"
regist = "2008/11/03 18:05"
update = "2008/11/11 01:32"

[[entries]]
no = "6"
name = "Squid"
title = "foon it!! foon it!!"
size = "804 KB"
addr = ["http://www.geocities.jp/high_gl/bofoon.html"]
genre = "F-BEATS"
impr = "3"
total = "11"
avg = "3.66"
regist = "2008/11/03 18:43"
update = "2008/11/20 16:03"

[[entries]]
no = "7"
name = "bug-light"
title = "busier fighter"
size = "663 KB"
addr = ["http://darkschnider2080.hp.infoseek.co.jp/org/bug-busier_fighter.lzh"]
genre = "FREEFORM"
impr = "3"
total = "13"
avg = "4.33"
regist = "2008/11/03 22:02"
update = "2008/11/16 23:29"

[[entries]]
no = "8"
name = "bug-light"
title = "嘆きの樹 -bug mix-"
size = "26 KB"
addr = ["http://darkschnider2080.hp.infoseek.co.jp/org/bug-nageki.lzh"]
genre = "TRANCE"
impr = "6"
total = "19"
avg = "3.16"
regist = "2008/11/03 22:11"
update = "2008/11/14 21:07"

[[entries]]
no = "9"
name = "さんそ"
title = "YOU-ARE-AN-IDIOT"
size = "2450 KB"
addr = ["http://zatsuzatsu.sosite.jp/img/bmsfile/YAAI.zip"]
genre = "IDIOTRANSE"
impr = "2"
total = "9"
avg = "4.5"
regist = "2008/11/03 23:45"
update = "2008/11/10 22:01"

[[entries]]
no = "10"
name = "びょうき"
title = "ははは"
size = "553 KB"
addr = ["http://briefcase.yahoo.co.jp/kisala_49"]
genre = "あ   はは."
impr = "2"
total = "5"
avg = "2.5"
regist = "2008/11/04 00:33"
update = "2008/11/10 22:05"

[[entries]]
no = "11"
name = "dj Mirai"
title = "Vrtra"
size = "1668 KB"
addr = ["http://www.geocities.jp/rf_mirai/bms/event/04/bofoon2008dl.html"]
genre = "Drum'n Bass"
impr = "2"
total = "6"
avg = "3"
regist = "2008/11/05 10:12"
update = "2008/11/10 22:08"

[[entries]]
no = "12"
name = "RoT"
title = "黒壁ってあってもいいよね"
size = "490 KB"
addr = ["http://briefcase.yahoo.co.jp/bc/shirabaxxx/"]
genre = "TATERENDA"
impr = "2"
total = "6"
avg = "3"
regist = "2008/11/05 21:15"
update = "2008/11/11 01:07"

[[entries]]
no = "13"
name = "えふぇｆっふぇふぇ"
title = "っふぇふぇふぇふぇえ"
size = "1133 KB"
addr = ["http://asdf.bms.ms/box/bofoon2008_moemoepop.zip"]
genre = "ふぇｆっふぇふぇ"
impr = "2"
total = "6"
avg = "3"
regist = "2008/11/05 23:25"
update = "2008/11/10 21:29"

[[entries]]
no = "14"
name = "Nick"
title = "生きたい"
size = "2943 KB"
addr = [
    "http://nick.xxxxxxxx.jp/ikitai.lzh",
    "（右クリック保存）",
]
genre = "RAVE"
impr = "3"
total = "11"
avg = "3.66"
regist = "2008/11/06 15:48"
update = "2008/11/11 19:41"

[[entries]]
no = "15"
name = "-"
title = "-"
size = "0 KB"
addr = ["-"]
genre = "-"
impr = "3"
total = "10"
avg = "3.33"
regist = "2008/11/08 12:28"
update = "2010/08/23 19:25"

[[entries]]
no = "16"
name = "倉賀野嬢を応援するスレ"
title = "レッカー車の肘"
size = "5100 KB"
addr = ["http://briefcase.yahoo.co.jp/bc/kosakkus/lst?&.dir=/9d3d&.src=bc&.view=l"]
genre = "演歌"
impr = "2"
total = "8"
avg = "4"
regist = "2008/11/08 15:17"
update = "2008/11/11 19:43"

[[entries]]
no = "17"
name = "John. KG bmser"
title = "4min 33sec"
size = "759 KB"
addr = ["http://flexus.tistory.com/attachment/49165b5b60fa098.rar"]
genre = "New age"
impr = "2"
total = "4"
avg = "2"
regist = "2008/11/08 20:22"
update = "2008/11/11 21:54"

[[entries]]
no = "18"
name = "KATUSYA (bms:tako)"
title = "七夕"
size = "432 KB"
addr = ["http://r866761.hp.infoseek.co.jp/music/k-tanabata.rar"]
genre = "ROCK/POPS"
impr = "2"
total = "10"
avg = "5"
regist = "2008/11/09 00:04"
update = "2008/11/11 20:31"

[[entries]]
no = "19"
name = "TK◆Vvv2VwVoyW"
title = "Ｖ２（ＴＡＫＡ）/beafmania2DX16より"
size = "2600 KB"
addr = ["http://www1.axfc.net/uploader/He/so/156577"]
genre = "progressive"
impr = "5"
total = "21"
avg = "4.2"
regist = "2008/11/09 05:19"
update = "2008/11/13 22:38"

[[entries]]
no = "20"
name = "bug-light"
title = "ASSAULT MIRAGE"
size = "630 KB"
addr = ["http://darkschnider2080.hp.infoseek.co.jp/org/bug-mirage.lzh"]
genre = "ゆっくりしね！"
impr = "1"
total = "1"
avg = "1"
regist = "2008/11/09 11:52"
update = "2008/11/10 21:38"

[[entries]]
no = "21"
name = "M.A.D & Friends"
title = "英単語レッスン by DJ"
size = "1800 KB"
addr = ["http://3rd.geocities.jp/accessflight/lesson.lzh"]
genre = "LESSON"
impr = "5"
total = "21"
avg = "4.2"
regist = "2008/11/09 22:15"
update = "2008/11/18 00:18"

[[entries]]
no = "22"
name = "POF2008実行委員会"
title = "PITCH OF FIGHTERS 2008"
size = "13622 KB"
addr = [
    "http://uploader.bms.ms/data/pof2008_fullset_fix.zip",
    "http://comeup.info/bofoon2008/pof2008_fullset_fix.zip",
]
genre = "Techno"
impr = "4"
total = "17"
median = "4.5"
avg = "4.25"
regist = "2008/11/09 23:43"
update = "2013/11/01 22:34"

[[entries]]
no = "23"
name = "sd ft. KFL Factory"
title = "Muzik Out Za Groove"
size = "1785 KB"
addr = [
    "http://r866761.hp.infoseek.co.jp/music/mozg_bmsogg.rar",
    "(HQogg 1785KB)",
    "http://r866761.hp.infoseek.co.jp/music/mozg_bms.rar",
    "(LQwav 3378KB)",
    "http://r866761.hp.infoseek.co.jp/music/mozg_dwi.zip",
    "(おまけDWI 2162KB)",
]
genre = "Mixture Techno"
impr = "2"
total = "6"
avg = "3"
regist = "2008/11/09 23:50"
update = "2008/11/11 20:48"

[[entries]]
no = "24"
name = "青酸カリー"
title = "青酸カリー"
size = "872 KB"
addr = ["http://moexx.mad.buttobi.net/uploader/src/ccn_up0313.zip"]
genre = "カレーライス"
impr = "2"
total = "6"
avg = "3"
regist = "2008/11/09 23:57"
update = "2008/11/11 20:40"

[[entries]]
no = "25"
name = "takeda"
title = "えりいぜのために"
size = "12694 KB"
addr = ["http://www.geocities.jp/maxh_takeda/elise.zip"]
genre = "black history"
impr = "3"
total = "9"
avg = "3"
regist = "2008/11/09 23:58"
update = "2008/11/11 20:37"
