[[entries]]
no = "1"
name = "tarolabo"
title = "sista)nightTrans"
size = "16587 KB"
addr = ["http://www.fnbi.jp/tarolabo/trans.rar"]
genre = "morse codokinawa onkaichedelic transpeed corchestranovirby popinsewing"
impr = "18"
total = "26"
avg = "1.44"
regist = "2008/11/07 00:01"
update = "2008/11/21 00:04"

[[entries]]
no = "2"
name = "-"
title = "-"
size = "0 KB"
addr = ["-"]
genre = "-"
impr = "16"
total = "7"
avg = "0.43"
regist = "2008/11/07 08:54"
update = "2009/05/29 12:26"

[[entries]]
no = "3"
name = "SKz"
title = "Death mail Ⅳ"
size = "0000 KB"
addr = ["ー＿－"]
genre = "Neuron reckless driving"
impr = "20"
total = "35"
avg = "1.75"
regist = "2008/11/07 18:43"
update = "2008/11/20 00:03"

[[entries]]
no = "4"
name = "LiTaNia"
title = "Lost Under"
size = "4140 KB"
addr = [
    "http://litania.egloos.com/2151431",
    "http://uploader.bms.ms/data/experimentation/LostUnder_fixed.zip",
    "(Mirror Site)",
]
genre = "Joke Core"
impr = "19"
total = "21"
avg = "1.1"
regist = "2008/11/07 23:13"
update = "2008/11/21 00:15"

[[entries]]
no = "5"
name = "-"
title = "-"
size = "0 KB"
addr = ["-"]
genre = "-"
impr = "16"
total = "13"
avg = "0.81"
regist = "2008/11/08 11:08"
update = "2010/08/23 19:24"

[[entries]]
no = "6"
name = "Macadamia Shorthead"
title = "Sick is thick"
size = "3676 KB"
addr = ["http://dustc.biz/bms/mac_sit.rar"]
genre = "Junglin' Rave"
impr = "16"
total = "17"
avg = "1.06"
regist = "2008/11/08 14:36"
update = "2008/11/20 00:25"

[[entries]]
no = "7"
name = "CRUNCH"
title = "辛＊辛"
size = "3270 KB"
addr = [
    "http://3rd.geocities.jp/accessflight/karakarawavlq.zip",
    "(wav LQ版) 3270KB",
    "http://3rd.geocities.jp/accessflight/karakaraogg.zip",
    "(ogg版) 2110KB",
]
genre = "GARAM'N'MASALA"
impr = "17"
total = "25"
avg = "1.47"
regist = "2008/11/08 16:09"
update = "2008/11/20 01:04"

[[entries]]
no = "8"
name = "DJ RENSA"
title = "Ko Sui Pii"
size = "6477 KB"
addr = ["http://rensa.tistory.com/attachment/4916bb341312bBL.rar"]
genre = "DISTURBANCE"
impr = "15"
total = "4"
avg = "0.26"
regist = "2008/11/08 17:47"
update = "2008/11/22 00:59"

[[entries]]
no = "9"
name = "YATA"
title = "AM2J"
size = "6836 KB"
addr = ["http://www.geocities.jp/toworu38/EXP.html"]
genre = "Office"
impr = "18"
total = "14"
avg = "0.77"
regist = "2008/11/08 21:34"
update = "2008/11/20 23:59"

[[entries]]
no = "10"
name = "Matter8"
title = "盲進の目"
size = "1267 KB"
addr = ["http://cerebralmuddystream.hp.infoseek.co.jp/BMS/eye2.zip"]
genre = "PROG TEK"
impr = "17"
total = "20"
avg = "1.17"
regist = "2008/11/08 23:35"
update = "2008/11/20 00:24"

[[entries]]
no = "11"
name = "-"
title = "-"
size = "23187 KB"
addr = ["-"]
genre = "-"
impr = "0"
total = "0"
avg = "1"
regist = "2008/11/09 03:39"
update = "2008/11/18 00:54"

[[entries]]
no = "12"
name = "clone"
title = "last spirit"
size = "21000 KB"
addr = ["！"]
genre = "GABBIENT"
impr = "17"
total = "26"
avg = "1.52"
regist = "2008/11/09 13:53"
update = "2008/11/20 00:09"

[[entries]]
no = "13"
name = "t-plain"
title = "autumn stage"
size = "16659 KB"
addr = ["http://nekokan.dyndns.info/~anonymous/experimentation/_autumn_stage_HQ_BGA.rar"]
genre = "Piano'n'8bit"
impr = "15"
total = "21"
avg = "1.4"
regist = "2008/11/09 15:03"
update = "2008/11/19 23:52"

[[entries]]
no = "14"
name = "dj Quzu"
title = "Format Xxx Topics"
size = "5510 KB"
addr = ["http://uploader.bms.ms/data/FXP.zip"]
genre = "ROOP FIT"
impr = "17"
total = "16"
avg = "0.94"
regist = "2008/11/09 22:45"
update = "2008/11/19 23:52"

[[entries]]
no = "15"
name = "scytheleg"
title = "Stop and Run Assemble"
size = "5411 KB"
addr = ["http://scytheleg.bms.ms/tempyou/music/pmc/bms/sra/stl_pmc-sra.rar"]
genre = "factory sound"
impr = "15"
total = "24"
avg = "1.6"
regist = "2008/11/09 23:41"
update = "2008/11/20 02:04"

[[entries]]
no = "16"
name = "wosderge"
title = "ExTrAES"
size = "2714 KB"
addr = ["http://cerebralmuddystream.hp.infoseek.co.jp/BMS/ExTrAES.zip"]
genre = "LOCOMOSPHERE"
impr = "21"
total = "19"
avg = "0.9"
regist = "2008/11/09 23:53"
update = "2008/11/20 00:05"

[[entries]]
no = "17"
name = "eicateve"
title = "FLASHBACK"
size = "5079 KB"
addr = [
    "http://www.exout.net/~eicakteve/02.html",
    "(OGGHQ-4.95MB,WAVHQ-16.5MB)",
]
genre = "FLASHBACK"
impr = "23"
total = "40"
avg = "1.73"
regist = "2008/11/09 23:57"
update = "2009/02/13 04:27"

[[entries]]
no = "18"
name = "Kotira Sample"
title = "tuesday"
size = "9787 KB"
addr = [
    "http://sound.jp/morigasigeru/tuesday.html",
    "http://uploader.bms.ms/data/experimentation/tuesday.rar",
]
genre = "60s to electro house"
impr = "25"
total = "42"
avg = "1.68"
regist = "2008/11/09 23:59"
update = "2008/11/19 23:58"
