[[entries]]
no = "1"
name = "Ansie Anterope"
title = "BEER? FOR BATHING!! (Unadorned MIX)"
size = "30 KB"
addr = ["http://www1.axfc.net/uploader/File/so/13792"]
genre = "Ghetto Tech"
impr = "11"
total = "29"
avg = "2.63"
regist = "2008/11/16 01:21"
update = "2008/12/07 22:26"

[[entries]]
no = "2"
name = "音源_dj Extrose/obj_mit"
title = "X -Crossblade-/obj_mit"
size = "20 KB"
addr = ["http://www1.axfc.net/uploader/File/so/14042.zip"]
genre = "SPEEDTEK"
impr = "9"
total = "12"
avg = "1.33"
regist = "2008/11/16 09:04"
update = "2010/05/29 14:30"

[[entries]]
no = "3"
name = "bug-light"
title = "nymphogram(bug mix)"
size = "5 KB"
addr = ["http://darkschnider2080.hp.infoseek.co.jp/sabun_arr/bug-nymphogram-disembowel.lzh"]
genre = "TECHNO"
impr = "10"
total = "17"
avg = "1.7"
regist = "2008/11/18 00:45"
update = "2008/12/08 16:52"

[[entries]]
no = "4"
name = "NO4"
title = "more another-"
size = "95 KB"
addr = ["http://"]
genre = "。"
impr = "0"
total = "0"
avg = "0"
regist = "2008/11/18 05:05"
update = "2012/04/01 17:48"

[[entries]]
no = "5"
name = "momo★yama(桃山)"
title = "～ラピ★ポップ～"
size = "7 KB"
addr = [
    "http://www.geocities.jp/pink_no_cool/BMS/momoyama_rapi.lzh",
    "(右クリックして『対象をファイルに保存』をしてください)",
]
genre = "PSG RAPID POP"
impr = "12"
total = "33"
avg = "2.75"
regist = "2008/11/18 17:51"
update = "2008/12/08 19:34"

[[entries]]
no = "6"
name = "3034"
title = "Together (DANCE MIX)"
size = "15 KB"
addr = ["http://sample3034.tistory.com/attachment/49228abc9c454E8.rar"]
genre = "HARD DANCE"
impr = "8"
total = "17"
avg = "2.12"
regist = "2008/11/18 18:37"
update = "2009/03/31 04:58"

[[entries]]
no = "7"
name = "OXYGEN"
title = "STAR TRACK (NiraicA_nai + OXYGENMix)"
size = "36 KB"
addr = ["http://zatsuzatsu.sosite.jp/img/bmssabun/roop_startrack_kyokuhenkousabun.zip"]
genre = "DISCORE"
impr = "15"
total = "38"
avg = "2.53"
regist = "2008/11/18 23:28"
update = "2008/12/07 22:10"

[[entries]]
no = "8"
name = "hi-low"
title = "SAMBISTA(stomp mix)"
size = "4 KB"
addr = ["http://xxbmsxx.web.fc2.com/sambista_stomp.zip"]
genre = "HARD STYLE"
impr = "12"
total = "24"
avg = "2"
regist = "2008/11/19 05:39"
update = "2008/12/07 23:42"

[[entries]]
no = "9"
name = "kizkiz"
title = "STAR TRACK -the Day of Anthem mix-"
size = "15 KB"
addr = ["http://soundwing.com/bms/roop_startrack_kizkiz.zip"]
genre = "house"
impr = "13"
total = "37"
avg = "2.84"
regist = "2008/11/20 02:28"
update = "2008/12/10 03:17"

[[entries]]
no = "10"
name = "Nitrix"
title = "tokyo underground"
size = "2 KB"
addr = ["http://page.freett.com/nitrix/music_objective.html"]
genre = "HIP HOP"
impr = "10"
total = "21"
avg = "2.1"
regist = "2008/11/21 23:55"
update = "2008/12/07 22:27"

[[entries]]
no = "11"
name = "Nitrix"
title = "pierce the wall!!"
size = "4 KB"
addr = ["http://page.freett.com/nitrix/music_objective.html"]
genre = "ROTTERDAM TECHNO"
impr = "7"
total = "14"
avg = "2"
regist = "2008/11/22 00:01"
update = "2008/12/07 18:13"

[[entries]]
no = "12"
name = "Nitrix"
title = "become a star"
size = "2 KB"
addr = ["http://page.freett.com/nitrix/music_objective.html"]
genre = "Ambient"
impr = "8"
total = "12"
avg = "1.5"
regist = "2008/11/22 00:03"
update = "2008/12/07 18:23"

[[entries]]
no = "13"
name = "DJ Obstetrics"
title = "I MOVE YOU"
size = "6 KB"
addr = ["http://uploader.bms.ms/data/sambista_obstetrics.zip"]
genre = "ROLLING TECHNO"
impr = "9"
total = "23"
avg = "2.55"
regist = "2008/11/24 00:38"
update = "2008/12/07 23:37"

[[entries]]
no = "14"
name = "kizkiz"
title = "Sim's Pabulum Kettle"
size = "3 KB"
addr = ["http://soundwing.com/bms/diskotikor_kizkiz.zip"]
genre = "Bigbeat / Industrial"
impr = "5"
total = "12"
avg = "2.4"
regist = "2008/11/24 01:20"
update = "2008/12/10 03:19"

[[entries]]
no = "15"
name = "living room"
title = "SAM VI STA"
size = "5 KB"
addr = ["http://uploader.bms.ms/data/lr_vista_ex.zip"]
genre = "TECHNO"
impr = "10"
total = "21"
avg = "2.1"
regist = "2008/11/24 01:25"
update = "2008/12/08 00:08"

[[entries]]
no = "16"
name = "Nankumo"
title = "Nymph"
size = "9 KB"
addr = ["http://www.geocities.jp/nankumo_2565/nym.html"]
genre = "TECHNO"
impr = "11"
total = "30"
avg = "2.72"
regist = "2008/11/27 16:01"
update = "2008/12/09 21:11"

[[entries]]
no = "17"
name = "aon"
title = "Grim Monolith"
size = "7 KB"
addr = ["http://artofnotes.hp.infoseek.co.jp/data/grimmonolith_aon.zip"]
genre = "Mana Artifact"
impr = "12"
total = "27"
avg = "2.25"
regist = "2008/11/30 02:07"
update = "2008/12/08 23:20"

[[entries]]
no = "18"
name = "kizkiz"
title = "stream tree"
size = "19 KB"
addr = ["http://soundwing.com/bms/stream_tree_kizkiz.zip"]
genre = "TECHNO"
impr = "9"
total = "24"
avg = "2.66"
regist = "2008/11/30 23:11"
update = "2008/12/10 03:21"

[[entries]]
no = "19"
name = "KOOPA"
title = "World Kecak Circus"
size = "5 KB"
addr = ["http://uploader.bms.ms/data/wkc_koopa.zip"]
genre = "DRUM 'N BASS"
impr = "7"
total = "15"
avg = "2.14"
regist = "2008/11/30 23:24"
update = "2008/12/08 20:27"

[[entries]]
no = "20"
name = "goten"
title = "aballava(?)"
size = "23 KB"
addr = ["http://uploader.bms.ms/data/gotaballava.zip"]
genre = "fgWood"
impr = "14"
total = "41"
avg = "2.92"
regist = "2008/11/30 23:48"
update = "2008/12/11 22:25"
