[[entries]]
no = "1"
name = "トールミツハシ"
title = "Colorful"
size = "18500 KB"
addr = [
    "http://uploader.bms.ms/data/bgabattle2/colorful_TMbga.rar",
    "（ミラー）",
    "http://sweezy.ddo.jp/~sweez/bms/colorful_TMbga.rar",
    "（BMS）",
    "http://sweez.net/home.html",
]
genre = "R&B"
impr = "21"
total = "42"
avg = "2"
regist = "2009/03/06 00:07"
update = "2009/03/23 22:31"

[[entries]]
no = "2"
name = "TOXVID"
title = "Legacy of Hatred"
size = "33000 KB"
addr = [
    "(BMS + BGA)",
    "http://lepusnette.aquz.biz/bgadata/Legacy_of_Hatred_bga_include.rar",
    "http://cid-3d4a5d3f520c193f.skydrive.live.com/self.aspx/.Public/bga/Legacy%7C_of%7C_Hatred%7C_bga%7C_include.rar",
    "///////////////////////////////////////////////",
    "(BGA ONLY)",
    "http://lepusnette.aquz.biz/bgadata/Legacy_of_Hatred_bga_only.rar",
    "http://cid-3d4a5d3f520c193f.skydrive.live.com/self.aspx/.Public/bga/Legacy%7C_of%7C_Hatred%7C_bga%7C_only.rar",
]
genre = "Trance"
impr = "17"
total = "31"
avg = "1.82"
regist = "2009/03/06 13:43"
update = "2009/03/23 22:32"

[[entries]]
no = "3"
name = "kody"
title = "cross the mind"
size = "42038 KB"
addr = ["ftp://nekokan.dyndns.info/bms/crossthemindMPG3/crossthemind_ogg.rar"]
genre = "freeform trancecore"
impr = "15"
total = "9"
avg = "0.6"
regist = "2009/03/08 23:57"
update = "2009/03/23 22:31"

[[entries]]
no = "4"
name = "kawasaki under ground"
title = "nature"
size = "22331 KB"
addr = ["http://vfpq.fau.jp/kawasaki/kawasaki_nature.rar"]
genre = "BREAKBEATS"
impr = "15"
total = "21"
avg = "1.4"
regist = "2009/03/08 23:59"
update = "2009/03/23 22:32"
