[[entries]]
no = "1"
name = "tetsuo / 642"
title = "にんげんていいな"
size = "3200 KB"
addr = ["http://yamaguchi.cool.ne.jp/hima642/event.html"]
genre = "HYPER BRASS"
impr = "2"
total = "2"
avg = "1"
update = "2002/12/19 16:17"

[[entries]]
no = "2"
name = "off-beat / kota"
title = "Trash Vox (5keys)"
size = "3460 KB"
addr = ["http://red_screen.tripod.co.jp/dl/bga_trash.gca"]
genre = "NU-NRG"
impr = "7"
total = "7"
avg = "1"
update = "2002/12/26 03:01"

[[entries]]
no = "3"
name = "asu / AOiRO_Manbow"
title = "sttra lem nattill"
size = "12670 KB"
addr = ["http://www.mnxnet.com/~asuka/sde.rar"]
genre = "Eurotic Pops"
impr = "4"
total = "4"
avg = "1"
update = "2002/12/28 07:18"
