[[entries]]
no = "1"
name = "MADquinesis"
title = "PlaytoDie"
size = "2750 KB"
addr = ["http://uploader.bms.ms/data/playtodie.rar"]
genre = "HARDCORE"
impr = "36"
total = "25"
avg = "0.69"
regist = "2010/02/18 01:02"
update = "2010/03/08 00:34"

[[entries]]
no = "2"
name = "Symphonian"
title = "HELLO MAN"
size = "14745 KB"
addr = ["http://www.symphonian.co.kr/bms.htm"]
genre = "Rotterdam Techno"
impr = "36"
total = "12"
avg = "0.33"
regist = "2010/02/18 01:05"
update = "2010/03/08 01:08"

[[entries]]
no = "3"
name = "koaki"
title = "Final Flight"
size = "3100 KB"
addr = ["http://www.geocities.jp/tigerkuzumi/finalflight.htm"]
genre = "FREEFORM HARDCORE"
impr = "36"
total = "30"
avg = "0.83"
regist = "2010/02/18 01:11"
update = "2010/03/16 13:46"

[[entries]]
no = "4"
name = "Akiho☆Cibir vs Sweets★Factory"
title = "LOVE & SWEETS"
size = "2120 KB"
addr = [
    "http://uploader.bms.ms/data/akiho_SF_Love_and_Sweets.zip",
    "[HQ_OGG]",
    "http://uploader.bms.ms/data/akiho_SF_Love_and_Sweets_LQ.zip",
    "[LQ_WAV]",
]
genre = "HAPPY SPEED CORE"
impr = "38"
total = "17"
avg = "0.44"
regist = "2010/02/18 01:12"
update = "2010/03/07 23:05"

[[entries]]
no = "5"
name = "ZUMMER"
title = "Genesis of Splitter World -工事現場mix-"
size = "46000 KB"
addr = ["http://zummer.sakura.ne.jp/EXTBEAT/"]
genre = "Splittercore"
impr = "41"
total = "15"
avg = "0.36"
regist = "2010/02/18 01:38"
update = "2010/03/08 00:37"

[[entries]]
no = "6"
name = "DJ TAKUAN 及び 西東"
title = "EXTREME☆LOVE"
size = "13500 KB"
addr = ["http://djtakuan.sp.land.to/exbeat.html"]
genre = "J-HAPPY HARDCORE"
impr = "34"
total = "20"
avg = "0.58"
regist = "2010/02/18 03:02"
update = "2010/03/08 00:59"

[[entries]]
no = "7"
name = "-"
title = "-"
size = "0 KB"
addr = ["-"]
genre = "-"
impr = "60"
total = "28"
avg = "0.46"
regist = "2010/02/18 03:59"
update = "2010/08/23 19:21"

[[entries]]
no = "8"
name = "4G"
title = "Deadly Crush"
size = "4360 KB"
addr = ["http://www7a.biglobe.ne.jp/~furiefurie/bms/deadlycrush.rar"]
genre = "HARDCORE"
impr = "31"
total = "10"
avg = "0.32"
regist = "2010/02/18 06:50"
update = "2010/03/07 23:07"

[[entries]]
no = "9"
name = "yoshi"
title = "ALIEN ENCOUNTERS"
size = "3100 KB"
addr = [
    "http://ux.getuploader.com/stagnation/download/25/ALIEN+ENCOUNTERS.rar",
    "http://www1.axfc.net/uploader/He/so/265474.rar",
]
genre = "Hard techno"
impr = "30"
total = "9"
avg = "0.3"
regist = "2010/02/18 11:24"
update = "2010/03/15 19:01"

[[entries]]
no = "10"
name = "xenothium"
title = "Maggots Rain"
size = "10235 KB"
addr = [
    "下記のページよりダウンロードして下さい。",
    "http://sound.jp/roaraddiction/maggotsrain_bms.html",
]
genre = "DIGIROCK CORE"
impr = "41"
total = "33"
avg = "0.8"
regist = "2010/02/18 13:20"
update = "2010/03/08 00:39"

[[entries]]
no = "11"
name = "DAMiEN666(/3)"
title = "PARANOiA(click mix)"
size = "135 KB"
addr = ["http://uploader.bms.ms/data/para_crick.zip"]
genre = "Click Waltz"
impr = "28"
total = "4"
avg = "0.14"
regist = "2010/02/18 18:22"
update = "2010/03/07 23:08"

[[entries]]
no = "12"
name = "xi"
title = ".357 Magnum"
size = "19916 KB"
addr = [
    "http://uploader.bms.ms/data/EXTREMEBEAT/xi_357_Magnum_ogg_LQ.zip",
    "http://uploader.bms.ms/data/EXTREMEBEAT/xi_357_Magnum_wav_HQ.zip",
]
genre = "JAZZ FUSION"
impr = "57"
total = "50"
avg = "0.87"
regist = "2010/02/18 19:20"
update = "2010/03/09 01:13"

[[entries]]
no = "13"
name = "Orange Strophe"
title = "Neps Paradox"
size = "44136 KB"
addr = ["http://neoarre.aquz.biz/xe/bms/5463"]
genre = "Progressive Jazz"
impr = "52"
total = "50"
avg = "0.96"
regist = "2010/02/18 22:47"
update = "2010/03/09 14:25"

[[entries]]
no = "14"
name = "morigasigeru"
title = "Angry Indian"
size = "24360 KB"
addr = ["http://uploader.bms.ms/data/EXTREMEBEAT/moriga/andian.rar"]
genre = "Ethnic/Experimental/Rock"
impr = "41"
total = "34"
avg = "0.82"
regist = "2010/02/18 22:47"
update = "2010/03/07 23:52"

[[entries]]
no = "15"
name = "Y.W"
title = "Pokemon battle imaging - No.3"
size = "8371 KB"
addr = [
    "↓軽量＆推奨。発狂 BMS をプレイされる方もこちら",
    "http://www.yw-works.com/data/bm/org_battle3_hqogg.zip",
    "[HQ OGG]",
    "↓OGG 未対応プレイヤーで遊ぶ場合はこちら",
    "http://www.yw-works.com/data/bm/org_battle3_mqwav.zip",
    "[MQ WAV]",
]
genre = "BATTLE IMAGING"
impr = "39"
total = "37"
avg = "0.94"
regist = "2010/02/18 23:51"
update = "2010/04/05 13:18"

[[entries]]
no = "16"
name = "momo★yama(桃山)"
title = "「崇めよ 魔王竜」"
size = "14114 KB"
addr = ["http://www.geocities.jp/pink_no_cool/BMS/fbs.html"]
genre = "fantasy battle Sequel"
impr = "45"
total = "41"
avg = "0.91"
regist = "2010/02/19 01:48"
update = "2010/03/09 02:46"

[[entries]]
no = "17"
name = "LiTaNia feat. LuSaWorl"
title = "SkyFlow"
size = "8570 KB"
addr = ["http://mahoutsukai.textcube.com/47"]
genre = "Girl's Rock"
impr = "30"
total = "18"
avg = "0.6"
regist = "2010/02/19 21:53"
update = "2010/03/08 11:49"

[[entries]]
no = "18"
name = "dPdk qq"
title = "Luchtvervuiling"
size = "3228 KB"
addr = ["公開終了"]
genre = "Vdekja Industries"
impr = "26"
total = "5"
median = "1"
avg = "0.19"
regist = "2010/02/20 01:59"
update = "2019/08/10 00:29"

[[entries]]
no = "19"
name = "3034"
title = "NS18 (RETIRE)"
size = "8986 KB"
addr = [
    "http://sample3034.tistory.com/attachment/cfile25.uf",
    "@180D9F244B7EE34211AD8D.rar [HQ]",
]
genre = "EXTREME TECHNO"
impr = "35"
total = "33"
avg = "0.94"
regist = "2010/02/20 04:43"
update = "2010/03/14 02:30"

[[entries]]
no = "20"
name = "FALL feat. yufu_sekka"
title = "Still Alive In Love"
size = "21988 KB"
addr = ["http://www.likeside.net/files/bms/stillaliveinlove.zip"]
genre = "SHIBUYA-KEI"
impr = "56"
total = "52"
avg = "0.92"
regist = "2010/02/20 11:33"
update = "2010/03/08 07:14"

[[entries]]
no = "21"
name = "H.U.T GiGAR"
title = "FxxK'EM BRAIN AND INOPERATIVE"
size = "5873 KB"
addr = ["http://loda.jp/dglife/?id=36"]
genre = "FxxKCORE"
impr = "33"
total = "21"
avg = "0.63"
regist = "2010/02/20 19:52"
update = "2010/03/07 23:57"

[[entries]]
no = "22"
name = "310"
title = "Stampede"
size = "3103 KB"
addr = ["http://lobsak.hp.infoseek.co.jp/Stampede.rar"]
genre = "EXTREME METAL"
impr = "31"
total = "18"
avg = "0.58"
regist = "2010/02/21 12:30"
update = "2010/03/13 18:03"

[[entries]]
no = "23"
name = "TOMA"
title = "パペ子・エクストリーム"
size = "2068 KB"
addr = ["http://estish.hp.infoseek.co.jp/bms/est_papekoex.zip"]
genre = "SPEEDCORE"
impr = "49"
total = "39"
avg = "0.79"
regist = "2010/02/22 00:56"
update = "2010/03/08 00:24"

[[entries]]
no = "24"
name = "樟"
title = "Firebrand"
size = "2290 KB"
addr = ["http://tokyo.cool.ne.jp/rysu78/firebrand.zip"]
genre = "Tribal"
impr = "34"
total = "9"
avg = "0.26"
regist = "2010/02/22 14:49"
update = "2010/03/07 23:12"

[[entries]]
no = "25"
name = "FT 718 (sd5y)"
title = "What's Limit??"
size = "4053 KB"
addr = [
    "(WAV, OGG)",
    "http://sound.jp/ft718/ft718music.html",
]
genre = "Speedcore"
impr = "34"
total = "25"
avg = "0.73"
regist = "2010/02/22 16:06"
update = "2010/03/09 22:20"

[[entries]]
no = "26"
name = "Ym1024"
title = "solitude"
size = "6651 KB"
addr = ["http://members.at.infoseek.co.jp/Ym1024/bms/ym24_solit_ogg.rar"]
genre = "Artcore"
impr = "31"
total = "13"
avg = "0.41"
regist = "2010/02/22 16:36"
update = "2010/03/17 08:51"

[[entries]]
no = "27"
name = "jill hi"
title = "Headache"
size = "4006 KB"
addr = ["http://f27.aaa.livedoor.jp/~gypsy/down.html"]
genre = "Drum 'n' Bass"
impr = "40"
total = "38"
avg = "0.95"
regist = "2010/02/22 16:43"
update = "2010/03/08 17:55"

[[entries]]
no = "28"
name = "Damjoy"
title = "The Lady Is A Trump"
size = "34373 KB"
addr = ["http://uploader.bms.ms/data/EXTREMEBEAT/theladyisatrump.rar"]
genre = "Prog Pop"
impr = "40"
total = "34"
avg = "0.85"
regist = "2010/02/22 23:03"
update = "2010/03/08 02:11"

[[entries]]
no = "29"
name = "2TORI"
title = "ゼフィランサス"
size = "16500 KB"
addr = ["http://uploader.bms.ms/data/sen-goku/Zephyranthes.rar"]
genre = "TRANCECORE BREAKS"
impr = "32"
total = "25"
avg = "0.78"
regist = "2010/02/22 23:54"
update = "2010/03/07 23:53"

[[entries]]
no = "30"
name = "Nitrix"
title = "Neck Breaker"
size = "535 KB"
addr = [
    "http://uploader.bms.ms/data/ntr_neck_breaker_ogg.rar",
    "(ogg-535KB)",
    "http://uploader.bms.ms/data/ntr_neck_breaker_wav.rar",
    "(wav-1946KB)",
]
genre = "FRENCH CORE"
impr = "32"
total = "17"
avg = "0.53"
regist = "2010/02/22 23:57"
update = "2010/03/28 00:37"

[[entries]]
no = "31"
name = "DJ Saw-Low"
title = "EXTREMEBEAT"
size = "10442 KB"
addr = ["http://scytheleg.bms.ms/tempyou/music/bms/exb/djsl_exb.rar"]
genre = "SPEED HARDCORE RAVE"
impr = "36"
total = "29"
avg = "0.8"
regist = "2010/02/22 23:58"
update = "2010/03/16 23:02"

[[entries]]
no = "32"
name = "団長"
title = "がんばれ日本"
size = "22900 KB"
addr = ["http://uploader.bms.ms/data/nipon.rar"]
genre = "Electronic"
impr = "34"
total = "29"
avg = "0.85"
regist = "2010/02/22 23:59"
update = "2012/03/11 11:20"
