[[entries]]
no = "1"
name = "Symphonian"
title = "JAM BRAIN"
size = "19082 KB"
addr = ["http://www.symphonian.co.kr/bms.htm"]
genre = "Speedcore"
impr = "26"
total = "5199999974"
avg = "199999999"
regist = "2010/02/20 00:01"
update = "2010/03/11 01:02"

[[entries]]
no = "2"
name = "scytheleg"
title = "Sphagnum squarrosum"
size = "9454 KB"
addr = ["http://scytheleg.bms.ms/tempyou/music/pmc/bms/ss/stl_pmc-ss.rar"]
genre = "---"
impr = "30"
total = "5999999975"
avg = "199999999.16"
regist = "2010/02/20 00:05"
update = "2010/03/08 13:47"

[[entries]]
no = "3"
name = "ニトロサイクロン"
title = "なんじゃ村ほいほ～い"
size = "3430 KB"
addr = ["http://uploader.bms.ms/data/nanjamura.rar"]
genre = "テクノロジー"
impr = "29"
total = "5799999981"
avg = "199999999.34"
regist = "2010/02/20 00:43"
update = "2010/03/08 00:25"

[[entries]]
no = "4"
name = "trapman a.k.a. ルゼ"
title = "minefield surfing"
size = "2280 KB"
addr = ["http://www.luzeria.net/music/48_surfing_ogg.rar"]
genre = "カオスウェーブ"
impr = "32"
total = "6399999980"
avg = "199999999.37"
regist = "2010/02/20 01:48"
update = "2010/03/08 01:22"

[[entries]]
no = "5"
name = "U.P."
title = "technic"
size = "11300 KB"
addr = ["---"]
genre = "ethnic dance"
impr = "29"
total = "5799999968"
avg = "199999998.89"
regist = "2010/02/20 05:50"
update = "2010/03/09 05:43"

[[entries]]
no = "6"
name = "4G"
title = "benitengue"
size = "32041 KB"
addr = ["http://www7a.biglobe.ne.jp/~furiefurie/bms/benitengue.rar"]
genre = "APPLE TECHNO"
impr = "24"
total = "4799999957"
avg = "199999998.2"
regist = "2010/02/20 10:11"
update = "2010/03/07 23:17"

[[entries]]
no = "7"
name = "yujurie"
title = "クロラノ"
size = "35000 KB"
addr = ["http://liz.nothing.sh/yuju/b/gba_rmx.zip"]
genre = "エレクトロニカ"
impr = "28"
total = "5599999985"
avg = "199999999.46"
regist = "2010/02/20 17:56"
update = "2010/03/07 23:56"

[[entries]]
no = "8"
name = "fkRadish"
title = "Time is warping"
size = "481 KB"
addr = ["http://www1.axfc.net/uploader/Sc/so/85090.zip"]
genre = "EXPERIMENTAL BREAKBEATS"
impr = "22"
total = "4399999961"
avg = "199999998.22"
regist = "2010/02/21 11:27"
update = "2010/03/08 15:22"

[[entries]]
no = "9"
name = "YATA"
title = "FJORD"
size = "6853 KB"
addr = ["削除しました"]
genre = "HARDCORE TECHNO"
impr = "23"
total = "4599999966"
avg = "199999998.52"
regist = "2010/02/21 11:36"
update = "2012/08/29 21:44"

[[entries]]
no = "10"
name = "morigasigeru"
title = "Khoomii Dance"
size = "41290 KB"
addr = ["http://uploader.bms.ms/data/khoomii.rar"]
genre = "Experimental/Doom Metal"
impr = "27"
total = "5399999982"
avg = "199999999.33"
regist = "2010/02/21 15:36"
update = "2010/03/07 23:42"

[[entries]]
no = "11"
name = "Tuning View"
title = "重力を消去する人類を舐めた恒星>HOSHi"
size = "17100 KB"
addr = ["http://www1.axfc.net/uploader/N/so/94948.zip"]
genre = "A**L TEMPLE BREAKS"
impr = "27"
total = "5399999991"
avg = "199999999.66"
regist = "2010/02/21 23:52"
update = "2010/03/08 03:36"

[[entries]]
no = "12"
name = "dumboy"
title = "GOD JOB"
size = "435 KB"
addr = [
    "http://uploader.bms.ms/data/dumboy_god_job_ogg.rar",
    "(ogg-435KB)",
    "http://uploader.bms.ms/data/dumboy_god_job_wav.rar",
    "(wav-1506KB)",
]
genre = "FOOLISH TECHNO"
impr = "19"
total = "3799999950"
avg = "199999997.36"
regist = "2010/02/21 23:52"
update = "2010/03/07 23:19"

[[entries]]
no = "13"
name = "sabamiso"
title = "Flashbacked four piece of my foolish preconceptions about India"
size = "10000 KB"
addr = [
    "(たぶんHQ)OGG(推奨)",
    "http://uploader.bms.ms/data/saba/sabamiso%20-%20Flashbacked%20four%20piece%20of%20my%20foolish%20preconceptions%20about%20India%28HQOGG%29.rar",
    "HQWAV(未減質という名の手抜き)",
    "http://uploader.bms.ms/data/saba/sabamiso%20-%20Flashbacked%20four%20piece%20of%20my%20foolish%20preconceptions%20about%20India%28HQWAV%29.rar",
]
genre = "ELECTRO HOUSE"
impr = "31"
total = "6199999981"
avg = "199999999.38"
regist = "2010/02/21 23:57"
update = "2010/03/11 06:47"

[[entries]]
no = "14"
name = "tarolabo"
title = "その動画、boleroかもな。知らないのか？"
size = "23525 KB"
addr = [
    "http://www.fnbi.jp/tarolabo/sonobolero.rar",
    "アクセス出来ない方は",
    "http://page.freett.com/tarolabo/sobolo.html",
    "からどうぞ。",
]
genre = "雅楽"
impr = "34"
total = "6799999992"
avg = "199999999.76"
regist = "2010/02/21 23:58"
update = "2010/03/11 21:01"
