[[entries]]
no = "1"
name = "ETIA."
title = "Takeoff 2 NIKE"
size = "6900 KB"
addr = [
    "ogg形式(6.9MB)",
    "http://uploader.bms.ms/data/takeoff2nike/etia_takeoff2nike_ogg.zip",
    "重いwav形式(20.4MB)",
    "http://uploader.bms.ms/data/takeoff2nike/wav/etia_takeoff2nike_wav.zip",
]
genre = "FREEFORM HARDCORE"
impr = "36"
total = "69"
avg = "1.91"
regist = "2010/05/15 00:03"
update = "2010/05/31 17:14"

[[entries]]
no = "2"
name = "nmk"
title = "Alicia"
size = "42261 KB"
addr = [
    "http://miohosina.moe.hm/bms/Alicia.html",
    "(ミラー)",
    "http://uploader.bms.ms/data/nmk_Alicia_ogg.zip",
]
genre = "VALKYRIE PROFILE II"
impr = "59"
total = "163"
avg = "2.76"
regist = "2010/05/15 00:13"
update = "2011/10/17 09:29"

[[entries]]
no = "3"
name = "bbangsami"
title = "Grow sproutling"
size = "29421 KB"
addr = [
    "http://dl.dropbox.com/u/547749/bbangsami_grow_sp_volumeup.rar",
    "http://bbcworld.zc.bz/bms/bbangsami_grow_sp.html",
    "(mirror)",
]
genre = "Casual fusion"
impr = "40"
total = "83"
avg = "2.07"
regist = "2010/05/15 00:15"
update = "2010/05/30 22:30"

[[entries]]
no = "4"
name = "no name"
title = "そんなものは存在しない"
size = "0 KB"
addr = [
    "http://honsyusaikan.pastorica.net/bms/p_e_deep_blue.zip",
    "(OGG HQ)",
    "http://honsyusaikan.pastorica.net/bms/p_e_deep_blue_LQ.zip",
    "(WAV LQ)",
]
genre = "そんなものは存在しない"
impr = "36"
total = "72"
avg = "2"
regist = "2010/05/15 00:15"
update = "2013/06/11 00:54"

[[entries]]
no = "5"
name = "yellowcat"
title = "神人"
size = "47206 KB"
addr = [
    "http://uploader.bms.ms/data/yellowcat.rar",
    "LISTENING(FOR ANOTHER NOTE) + MORE Patterns",
    "http://uploader.bms.ms/data/MOREPATTERNS.rar",
]
genre = "fusion classic"
impr = "34"
total = "42"
avg = "1.23"
regist = "2010/05/15 00:22"
update = "2010/05/30 23:47"

[[entries]]
no = "6"
name = "Gatia vs みずいろおおかみ"
title = "WW"
size = "1706 KB"
addr = ["http://kobagame.hp.infoseek.co.jp/bms/ww.zip"]
genre = "Happy Popcore"
impr = "33"
total = "63"
avg = "1.9"
regist = "2010/05/15 00:27"
update = "2010/05/30 23:40"

[[entries]]
no = "7"
name = "DJ TAKUAN 及び 佐倉アヤキ"
title = "織姫"
size = "7860 KB"
addr = ["http://djtakuan.sakura.ne.jp/event_mumei.html"]
genre = "TRANCE"
impr = "46"
total = "114"
avg = "2.47"
regist = "2010/05/15 00:33"
update = "2011/05/16 05:46"

[[entries]]
no = "8"
name = "daisan"
title = "Deep Marine"
size = "5820 KB"
addr = [
    "ogg[4.54MB]",
    "http://uploader.bms.ms/data/7thDeep%20Marinemumei/%5B7th%5DDeep%20Marine_ogg%5Bmumei%5D.zip",
    "wav[31.54MB]",
    "http://uploader.bms.ms/data/7thDeep%20Marinemumei/%5B7th%5DDeep%20Marine_wav%5Bmumei%5D.zip",
]
genre = "Trance"
impr = "35"
total = "72"
avg = "2.05"
regist = "2010/05/15 00:48"
update = "2010/05/31 15:22"

[[entries]]
no = "9"
name = "bj.HaLo"
title = "U.N.オーエンは彼女ではないようですね。"
size = "22120 KB"
addr = [
    "wav形式(重いです)",
    "http://uploader.bms.ms/data/unhalo%2B%20wav.zip",
    "ogg形式(驚きの圧縮率)",
    "http://uploader.bms.ms/data/unhalo%2B%20ogg.zip",
]
genre = "FREEFORM HARDCORE"
impr = "27"
total = "37"
avg = "1.37"
regist = "2010/05/15 00:53"
update = "2010/05/30 23:24"

[[entries]]
no = "10"
name = "James McCloud Report translated by Beast Synthesizer"
title = "Out of Dismension"
size = "15100 KB"
addr = ["http://uploader.bms.ms/data/b_s_outofdismension.rar"]
genre = "TECHNO"
impr = "30"
total = "33"
avg = "1.1"
regist = "2010/05/15 01:11"
update = "2010/05/30 21:44"

[[entries]]
no = "11"
name = "49"
title = "repetition"
size = "14567 KB"
addr = ["http://synctoron.sakura.ne.jp/upload/bms/49_repetition.zip"]
genre = "Acoustic DnB"
impr = "31"
total = "57"
avg = "1.83"
regist = "2010/05/15 04:44"
update = "2010/06/11 09:17"

[[entries]]
no = "12"
name = "KHAS"
title = "Lucid Dream"
size = "8510 KB"
addr = ["http://uploader.bms.ms/data/KHAS%20-%20Lucid%20Dream.zip"]
genre = "Trance"
impr = "30"
total = "58"
avg = "1.93"
regist = "2010/05/15 09:19"
update = "2010/05/30 22:55"

[[entries]]
no = "13"
name = "DJ.ZEST"
title = "Crazie"
size = "2800 KB"
addr = [
    "http://cid-48a5474a28eaf5af.skydrive.live.com/self.aspx/.Public/",
    "[DJ.ZEST]%20Crazie_.rar  (HQ wav) Drag and Drop please",
    "http://uploader.bms.ms/data/",
    "[DJ.ZEST]%20Crazie.rar  (Mirror Site)",
]
genre = "Break beat"
impr = "30"
total = "57"
avg = "1.9"
regist = "2010/05/15 09:59"
update = "2010/05/30 21:18"

[[entries]]
no = "14"
name = "Lime"
title = "Shining☆Star(bms edit)"
size = "3944 KB"
addr = [
    "ogg版(3,944KB)  -",
    "http://uploader.bms.ms/data/shining_star_ogg.rar",
    "WAV版(21,617KB) -",
    "http://uploader.bms.ms/data/shining_star_wav.rar",
]
genre = "Happy"
impr = "30"
total = "68"
avg = "2.26"
regist = "2010/05/15 11:28"
update = "2010/11/08 23:18"

[[entries]]
no = "15"
name = "Belle."
title = "final_strike"
size = "33200 KB"
addr = ["http://bbw.sakura.ne.jp/bms/final_strike.rar"]
genre = "Dramatical"
impr = "28"
total = "46"
avg = "1.64"
regist = "2010/05/15 11:38"
update = "2010/05/30 21:19"

[[entries]]
no = "17"
name = "Athame"
title = "-1R"
size = "1559 KB"
addr = [
    "http://www14.atpages.jp/athame/bms/100512_m1r.zip",
    "(直リン禁止なのでコピーしてアドレスバーに直接入力してください)",
    "http://uploader.bms.ms/data/100512_m1r.zip",
    "(ミラー)",
]
genre = "Minimal"
impr = "28"
total = "47"
avg = "1.67"
regist = "2010/05/15 14:07"
update = "2010/05/30 23:39"

[[entries]]
no = "18"
name = "exci"
title = "Afterglow (Radio Edit)"
size = "8503 KB"
addr = [
    "http://exciup.tistory.com/attachment/cfile8.uf",
    "@187D13224BEE6A9A2C4D42.zip (HQ OGG)",
    "http://exciup.tistory.com/attachment/cfile25.uf",
    "@13446C254BEE9F83A168AD.zip (LQ WAV)",
]
genre = "Hard Trance"
impr = "40"
total = "104"
avg = "2.6"
regist = "2010/05/15 18:21"
update = "2010/05/30 23:59"

[[entries]]
no = "19"
name = "dj VAKA"
title = "ﾃ-ﾚｯﾃｰ新宿談"
size = "51220 KB"
addr = ["http://uploader.bms.ms/data/vaka/terette-.zip"]
genre = "NU-FAMIＫOＮ ROMANCING HARDCORE/176/鷲リスペクト"
impr = "31"
total = "9"
avg = "0.29"
regist = "2010/05/15 19:23"
update = "2010/05/30 23:08"

[[entries]]
no = "20"
name = "Kei Iwata"
title = "CODE-E -Everlasting planets-"
size = "7410 KB"
addr = ["http://nekokan.dyndns.info/~anonymous/CODE-E_-Everlasting_planets-.rar"]
genre = "trance"
impr = "28"
total = "41"
avg = "1.46"
regist = "2010/05/15 19:54"
update = "2010/05/31 14:18"

[[entries]]
no = "21"
name = "HoQ-10"
title = "30 thirst"
size = "8861 KB"
addr = ["http://nekokan.dyndns.info/%7Eanonymous/7th_mumei/HoQ-10%20-%2030%20thirst.zip"]
genre = "slowmotion"
impr = "29"
total = "69"
avg = "2.37"
regist = "2010/05/15 23:19"
update = "2010/05/30 23:40"

[[entries]]
no = "22"
name = "ameba"
title = "KEEP OUT"
size = "10340 KB"
addr = ["http://uploader.bms.ms/hc/?download=h.zip"]
genre = "Industrial"
impr = "33"
total = "64"
avg = "1.93"
regist = "2010/05/15 23:33"
update = "2010/05/30 23:59"

[[entries]]
no = "23"
name = "2TORI"
title = "飛燕草"
size = "15500 KB"
addr = ["http://uploader.bms.ms/data/ogg.rar"]
genre = "TRANCE"
impr = "39"
total = "104"
avg = "2.66"
regist = "2010/05/16 02:24"
update = "2010/05/30 23:42"

[[entries]]
no = "24"
name = "アベ"
title = "Alice's Rave Night"
size = "23347 KB"
addr = ["http://uploader.bms.ms/data/Alice%27s%20Rave%20Night.rar"]
genre = "HARDCORE RAVE"
impr = "27"
total = "37"
avg = "1.37"
regist = "2010/05/16 03:25"
update = "2010/05/30 23:42"

[[entries]]
no = "25"
name = "kireji"
title = "新宿二丁目と歌舞伎町"
size = "3492 KB"
addr = ["http://djugg.hp.infoseek.co.jp/kireji_higegirl.zip"]
genre = "HARDCORE"
impr = "38"
total = "86"
avg = "2.26"
regist = "2010/05/16 11:33"
update = "2010/06/14 17:30"

[[entries]]
no = "26"
name = "Z40M"
title = "Deeply Blue (Radio Edit)"
size = "45568 KB"
addr = ["http://uploader.bms.ms/data/Deeply%20Blue%20.zip"]
genre = "Hard Trance"
impr = "30"
total = "51"
avg = "1.7"
regist = "2010/05/16 11:39"
update = "2010/05/30 23:51"

[[entries]]
no = "27"
name = "ぜらにも"
title = "Lotus leaf"
size = "7349 KB"
addr = ["http://uploader.bms.ms/data/Lotus%20Leaf%28ogg%29.zip"]
genre = "ambiguous pop"
impr = "27"
total = "45"
avg = "1.66"
regist = "2010/05/16 17:06"
update = "2010/05/30 23:46"

[[entries]]
no = "28"
name = "U.P."
title = "Turkey"
size = "13600 KB"
addr = ["http://blueswing.is.land.to/bms/"]
genre = "field dance"
impr = "33"
total = "78"
avg = "2.36"
regist = "2010/05/16 18:38"
update = "2010/05/30 23:59"

[[entries]]
no = "29"
name = "8556"
title = "Nullity Code #10"
size = "5445 KB"
addr = ["http://uploader.bms.ms/data/Nullitycode.zip"]
genre = "Rock"
impr = "36"
total = "45"
avg = "1.25"
regist = "2010/05/16 18:40"
update = "2010/05/30 23:47"

[[entries]]
no = "30"
name = "RMHN"
title = "花びら、3032枚目"
size = "19296 KB"
addr = ["http://neoarre.aquz.biz/xe/event_download"]
genre = "ASIAN CORE"
impr = "35"
total = "76"
avg = "2.17"
regist = "2010/05/16 20:41"
update = "2010/05/30 23:58"

[[entries]]
no = "31"
name = "神風"
title = "carry out faith"
size = "70956 KB"
addr = [
    "http://uploader.bms.ms/data/cof.zip",
    "↑本命のミラー",
    "↓貧弱な本鯖",
    "http://whirlwind.boy.jp/bms/cof.rar",
    "http://whirlwind.boy.jp/bms/cof.zip",
]
genre = "90's J-POP"
impr = "34"
total = "73"
avg = "2.14"
regist = "2010/05/16 23:39"
update = "2010/05/31 00:32"

[[entries]]
no = "32"
name = "funnysakura"
title = "Bizarre Subaqueous City"
size = "25396 KB"
addr = ["http://uploader.bms.ms/data/fs_hydro.rar"]
genre = "HYDROHIP"
impr = "24"
total = "17"
avg = "0.7"
regist = "2010/05/17 01:37"
update = "2010/05/30 23:51"

[[entries]]
no = "33"
name = "夢幻 海"
title = "ピアノ狂詩曲第壱番”天嵐戒”"
size = "13430 KB"
addr = ["http://uploader.bms.ms/data/Rhapsodie.rar"]
genre = "Rhapsodie"
impr = "36"
total = "96"
avg = "2.66"
regist = "2010/05/17 02:56"
update = "2010/05/30 23:59"

[[entries]]
no = "36"
name = "Ras"
title = "Everybody enjoy?"
size = "7304 KB"
addr = [
    "ogg形式",
    "http://uploader.bms.ms/data/everybody%20enloy%28ogg%29.zip",
    "wav形式",
    "http://uploader.bms.ms/data/everybody%20enloy%28wav%29.zip",
]
genre = "TECHNO"
impr = "33"
total = "82"
avg = "2.48"
regist = "2010/05/17 03:07"
update = "2010/05/30 23:52"

[[entries]]
no = "37"
name = "JukJul"
title = "CGH Piano etuden Op.22 No.2"
size = "66781 KB"
addr = ["http://uploader.bms.ms/data/Jukjul/Etuden.zip"]
genre = "Piano solo"
impr = "28"
total = "38"
avg = "1.35"
regist = "2010/05/17 03:29"
update = "2010/05/30 23:53"

[[entries]]
no = "38"
name = "さるだいん"
title = "Rhystortion"
size = "1051 KB"
addr = ["http://uploader.bms.ms/data/rhyst.zip"]
genre = "Techno"
impr = "29"
total = "40"
avg = "1.37"
regist = "2010/05/17 11:12"
update = "2010/05/30 23:58"

[[entries]]
no = "39"
name = "くまらー"
title = "rar"
size = "22100 KB"
addr = [
    "無圧縮wav版",
    "http://uploader.bms.ms/data/aaaa/rar.rar",
    "軽量化ogg版",
    "http://uploader.bms.ms/data/aaaa/rarogg.rar",
]
genre = "Minimal"
impr = "33"
total = "69"
avg = "2.09"
regist = "2010/05/17 21:11"
update = "2010/05/30 23:54"

[[entries]]
no = "40"
name = "CRUNCH"
title = "DORAGON TRANS"
size = "3970 KB"
addr = ["http://uploader.bms.ms/data/DORAGONTRANS.zip"]
genre = "TECHNO"
impr = "35"
total = "95"
avg = "2.71"
regist = "2010/05/17 21:53"
update = "2010/05/31 01:18"

[[entries]]
no = "41"
name = "KaeruUdon"
title = "恋をしました"
size = "13209 KB"
addr = ["http://uploader.bms.ms/data/sen-goku/kaeruudon_ko.zip"]
genre = "E.S.E.TECHNO"
impr = "27"
total = "44"
avg = "1.62"
regist = "2010/05/17 22:31"
update = "2010/05/30 23:55"

[[entries]]
no = "42"
name = "Lazy_selfish"
title = "0 DiMENSiOИ"
size = "37078 KB"
addr = ["http://uploader.bms.ms/data/0dimension.zip"]
genre = "HardCoreTechno"
impr = "28"
total = "44"
avg = "1.57"
regist = "2010/05/17 22:37"
update = "2010/05/30 23:56"

[[entries]]
no = "43"
name = "LiTaNia"
title = "blue cheer (spiritual edit)"
size = "10096 KB"
addr = ["http://litania.egloos.com/2930729"]
genre = "Spiritual Rock"
impr = "27"
total = "44"
avg = "1.62"
regist = "2010/05/17 23:25"
update = "2010/06/07 17:02"

[[entries]]
no = "44"
name = "xenothium"
title = "Una rosa azul el estado extatico."
size = "39000 KB"
addr = [
    "http://sound.jp/roaraddiction/uraeee_bms.html",
    "申し訳ありませんが、上記のDLページを経由してください。",
    "面倒だという方は↓",
    "[wav]",
    "http://uploader.bms.ms/data/uraeee.rar",
    "[ogg]",
    "http://uploader.bms.ms/data/uraeee_ogg.rar",
]
genre = "SPANISH CROSSOVER"
impr = "37"
total = "92"
avg = "2.48"
regist = "2010/05/17 23:46"
update = "2010/05/30 23:57"

[[entries]]
no = "45"
name = "haleit"
title = "fire me up"
size = "9000 KB"
addr = ["http://nekokan.dyndns.info/~anonymous/7th_mumei/haleit_firemeup.zip"]
genre = "Techno"
impr = "31"
total = "73"
avg = "2.35"
regist = "2010/05/17 23:52"
update = "2010/06/10 02:53"

[[entries]]
no = "46"
name = "些細"
title = "jumble"
size = "7250 KB"
addr = ["http://members3.jcom.home.ne.jp/mani-_-mani/jmbl.zip"]
genre = "drum'n'bass"
impr = "33"
total = "93"
avg = "2.81"
regist = "2010/05/17 23:54"
update = "2010/05/30 23:57"

[[entries]]
no = "47"
name = "Team ZUMMER feat. unican"
title = "atmosphere"
size = "7860 KB"
addr = [
    "http://team-zummer.info/bms-side/nanashi/unican.html",
    "http://zummer.sakura.ne.jp/nanashi/unican.html",
    "（ミラー鯖）",
]
genre = "noise-tp"
impr = "32"
total = "56"
avg = "1.75"
regist = "2010/05/17 23:57"
update = "2010/05/30 23:58"

[[entries]]
no = "48"
name = "pentate"
title = "P90"
size = "17188 KB"
addr = ["http://uploader.bms.ms/data/p90.rar"]
genre = "ELECTRO"
impr = "25"
total = "30"
avg = "1.2"
regist = "2010/05/17 23:57"
update = "2010/05/30 23:59"

[[entries]]
no = "49"
name = "ZUMMER"
title = "Aumair World -BMS edit-"
size = "50000 KB"
addr = [
    "http://team-zummer.info/bms-side/nanashi/zummer.html",
    "http://zummer.sakura.ne.jp/nanashi/zummer.html",
    "(ミラー鯖)",
]
genre = "J-CORE"
impr = "28"
total = "32"
avg = "1.14"
regist = "2010/05/17 23:58"
update = "2010/05/30 23:59"

[[entries]]
no = "50"
name = "cybermiso(sabamiso)"
title = "eccentric ghost channel as Poltergeist"
size = "10000 KB"
addr = ["http://uploader.bms.ms/data/saba/sabamiso-eccentric_ghost_channel_as%20Poltergeist.rar"]
genre = "ELECTRO/BREAKS/DUB STEP"
impr = "60"
total = "175"
avg = "2.91"
regist = "2010/05/17 23:59"
update = "2010/05/31 04:59"

[[entries]]
no = "51"
name = "Yosk!"
title = "milky round night"
size = "8058 KB"
addr = ["https://drive.google.com/open?id=0B7qCw4hNijr4UkgyS3ZYdjRLNEU"]
genre = "ファンタジーシルバー"
impr = "27"
total = "47"
median = "1"
avg = "1.74"
regist = "2010/05/17 23:59"
update = "2018/02/14 01:08"

[[entries]]
no = "52"
name = "3034"
title = "NS20"
size = "9811 KB"
addr = [
    "http://sample3034.tistory.com/attachment/cfile1.uf",
    "@1155630C4C0BD74E01EB63.rar [BMS - 2010.6.7 updated]",
    "http://sample3034.tistory.com/attachment/cfile10.uf",
    "@12555B0C4C0BD74B01E78A.rar [7鍵14鍵追加譜面]",
]
genre = "ROTTERDAM TECHNO"
impr = "39"
total = "106"
avg = "2.71"
regist = "2010/05/17 23:59"
update = "2010/06/07 02:17"
