[[entries]]
no = "1"
name = "PMPRS"
team = "赤紙"
title = "Army March"
size = "19425 KB"
addr = [
    "http://pmprs.g.ribbon.to/",
    "http://uploader.bms.ms/data/jyogai/pmprs/Army_March.zip",
    "※ミラー",
]
genre = "SPEEDCORE"
impr = "20"
total = "16942"
avg = "847.1"
regist = "2010/11/03 01:08"
update = "2010/11/20 23:58"

[[entries]]
no = "2"
name = "ETIA. vs MM Sequence"
team = "Team Synth1 場外乱闘編"
title = "DISCHARGE RUSH"
size = "17300 KB"
addr = [
    "[ogg](17.3MB)",
    "http://uploader.bms.ms/data/dischargerush/etia_vs_mm_sequence_ogg.zip",
    "[wav](45.0MB)",
    "http://uploader.bms.ms/data/dischargerush/etia_vs_mm_sequence_wav.zip",
]
genre = "ROTTERDAM TECHNO"
impr = "24"
total = "20974"
avg = "873.91"
regist = "2010/11/03 01:10"
update = "2010/11/21 00:13"

[[entries]]
no = "3"
name = "nmk"
team = "Team Synth1 場外乱闘編"
title = "100%Synth1"
size = "3770 KB"
addr = [
    "[ogg](3.7MB)",
    "http://uploader.bms.ms/data/nmksynth1/nmk_100synth1.zip",
]
genre = "Synth1Trance"
impr = "19"
total = "15437"
avg = "812.47"
regist = "2010/11/03 01:10"
update = "2010/11/20 22:44"

[[entries]]
no = "4"
name = "DJ Saw-Low"
team = "KOJIMA CRISIS"
title = "Attack the Supply convoy in the Valley"
size = "56875 KB"
addr = [
    "http://scytheleg.bms.ms/tempyou/music/bms/atciv/djsl_asciv.rar",
    "(フルパッケージ[BGM+BGA]) 56,875kb",
    "http://scytheleg.bms.ms/tempyou/music/bms/atciv/djsl_asciv_bgm.rar",
    "(BGMのみ) 6,576kb",
]
genre = "Speed Symphonic Metal"
impr = "16"
total = "13491"
avg = "843.18"
regist = "2010/11/03 01:10"
update = "2010/11/21 01:33"

[[entries]]
no = "5"
name = "TAKEMITSU GRAY"
team = "チーム他人のふんどし"
title = "eth sword (Sharp & Blunt mixxx)"
size = "9800 KB"
addr = [
    "http://honsyusaikan.pastorica.net/bms/tkmtgray_ethsword.zip",
    "http://honsyusaikan.pastorica.net/bms/tkmtgray_ethsword_LQ.zip",
]
genre = "BOKKENDZ UP"
impr = "19"
total = "15484"
avg = "814.94"
regist = "2010/11/03 01:12"
update = "2010/11/20 23:53"

[[entries]]
no = "6"
name = "ELE-G / PO"
team = "Animation PO"
title = "Tempest (BGA差分)"
size = "409 KB"
addr = ["http://uploader.bms.ms/data/BOF2010Jougairantou/tempest_po.zip"]
genre = "LEFTFIELD"
impr = "11"
total = "7576"
avg = "688.72"
regist = "2010/11/03 01:22"
update = "2010/11/21 00:01"

[[entries]]
no = "7"
name = "Floatage ( Lime )"
team = "Team Synth1 場外乱闘編"
title = "Aquamarine(bms edit)"
size = "7214 KB"
addr = [
    "ogg：",
    "http://uploader.bms.ms/data/floatage_aquamarine.zip",
]
genre = "Cooling Trance"
impr = "21"
total = "18029"
avg = "858.52"
regist = "2010/11/03 06:33"
update = "2010/11/21 05:53"

[[entries]]
no = "8"
name = "dj wiz. VS ファントムP"
team = "break-damn"
title = "シツコイ(bms edit)"
size = "17138 KB"
addr = ["http://fdist.ps.land.to/bms/cckoi_ogg.zip"]
genre = "tek-nerdcore"
impr = "17"
total = "13928"
avg = "819.29"
regist = "2010/11/03 10:31"
update = "2010/12/13 23:34"

[[entries]]
no = "9"
name = "月華狼"
team = "自称無名作家"
title = "insane ruler -cryolite doll-"
size = "11110 KB"
addr = ["http://uploader.bms.ms/data/gekkaroh/insane_ruler-cryolite_doll-1.01.zip"]
genre = "wailing techno"
impr = "15"
total = "11449"
avg = "763.26"
regist = "2010/11/03 10:58"
update = "2010/11/27 08:49"

[[entries]]
no = "10"
name = "Yellowcat"
team = "ANIMAL CREW Part.1"
title = "NARO:2nd Scene"
size = "25502 KB"
addr = [
    "http://cid-a5fc19fed3e64889.office.live.com/self.aspx/BMS/NAROBMS.rar",
    "BOF2010 Animal Crew Album :",
    "http://cid-a5fc19fed3e64889.office.live.com/self.aspx/BMS/Animal%20Crew%20Album.rar",
]
genre = "Space Trance"
impr = "13"
total = "10776"
avg = "828.92"
regist = "2010/11/03 15:48"
update = "2010/11/20 23:48"

[[entries]]
no = "11"
name = "pentate (luke) / PO"
team = "Animation PO"
title = "Honey Brond (BGA差分)"
size = "131 KB"
addr = ["http://uploader.bms.ms/data/BOF2010Jougairantou/HoneyBrond_ogg_po.zip"]
genre = "TECHNO"
impr = "11"
total = "8638"
avg = "785.27"
regist = "2010/11/04 00:05"
update = "2010/11/21 00:02"

[[entries]]
no = "12"
name = "SLT-Machine"
team = "dark music bms team"
title = "deep forest"
size = "4041 KB"
addr = ["http://uploader.bms.ms/data/slt_m_deep_forest_ogg.rar"]
genre = "DARK AMBIENT"
impr = "15"
total = "13458"
avg = "897.2"
regist = "2010/11/04 02:36"
update = "2010/11/20 23:39"

[[entries]]
no = "13"
name = "MuscleMissile"
team = "赤紙"
title = "RUSSIAN NIGHT FEVER"
size = "12000 KB"
addr = ["http://uploader.bms.ms/data/rnf/russian_night_fever.zip"]
genre = "HARD DANCE / TRANCE"
impr = "16"
total = "13153"
avg = "822.06"
regist = "2010/11/04 19:28"
update = "2010/11/21 01:21"

[[entries]]
no = "14"
name = "桜井あさり"
team = "(･x･`)"
title = "44"
size = "39461 KB"
addr = ["http://roaraddiction.mods.jp/bms/x009_44.rar"]
genre = "HARD DANCE"
impr = "19"
total = "17242"
avg = "907.47"
regist = "2010/11/04 22:27"
update = "2010/11/20 23:54"

[[entries]]
no = "15"
name = "Digital_C.F."
team = "Digital Cyber Fragments"
title = "Chandelier Girl"
size = "39542 KB"
addr = ["http://uploader.bms.ms/data/%5BDigital%20Cyber%20Fragments%20-%20Digital_C.F.%5Dchandelier%20girl.rar"]
genre = "TWINKLE HOUSE"
impr = "15"
total = "12646"
avg = "843.06"
regist = "2010/11/05 04:22"
update = "2010/11/20 23:40"

[[entries]]
no = "16"
name = "Relief*"
team = "忘れ去られた傭兵部隊"
title = "unholic"
size = "9391 KB"
addr = ["http://uploader.bms.ms/data/BOF2010Jougairantou/youhei_unholic_ogg.zip"]
genre = "Synth1を応援し隊/Euphoric Trance"
impr = "22"
total = "21049"
avg = "956.77"
regist = "2010/11/05 06:57"
update = "2010/11/20 23:46"

[[entries]]
no = "17"
name = "Irojironiac"
team = "チーム他人のふんどし"
title = "ROAD 2 IKU"
size = "679 KB"
addr = ["http://uploader.bms.ms/data/bof2010sr10xl2g/road2iku.zip"]
genre = "IKUCORE"
impr = "14"
total = "12424"
avg = "887.42"
regist = "2010/11/05 15:59"
update = "2010/11/21 01:53"

[[entries]]
no = "18"
name = "(^心^)Symphoniac(^心^)"
team = "dark music bms team"
title = "(^心^)Beautifulizer(^心^)"
size = "4010 KB"
addr = ["http://www.symphonian.co.kr/bms/Beautifulizer.rar"]
genre = "(^心^)Gabba(^心^)"
impr = "15"
total = "13168"
avg = "877.86"
regist = "2010/11/05 18:30"
update = "2010/11/21 00:35"

[[entries]]
no = "19"
name = "xenothium with 桜井あさり"
team = "(･x･`)"
title = "Greasy Sesame"
size = "18954 KB"
addr = ["http://roaraddiction.mods.jp/bms/x010_gs.rar"]
genre = "HIP MIXTURE"
impr = "20"
total = "18668"
avg = "933.4"
regist = "2010/11/05 19:04"
update = "2010/11/20 23:51"

[[entries]]
no = "20"
name = "KRX remixed by 削除"
team = "チーム他人のふんどし"
title = "- [none] [8 progress remix]"
size = "51000 KB"
addr = [
    "http://mikkiki.6.ql.bz/none.zip",
    "（なんとか置けました）",
]
genre = "Progressive House"
impr = "30"
total = "28452"
avg = "948.4"
regist = "2010/11/05 21:46"
update = "2010/11/27 14:25"

[[entries]]
no = "21"
name = "ルナ・ヴィオーラ(明智小衣)"
team = "G1"
title = "さようなら、いままで魚をありがとう"
size = "16000 KB"
addr = ["http://page.freett.com/mikoko/fish.html"]
genre = "SPACE TRIP(STRIP)"
impr = "18"
total = "16750"
avg = "930.55"
regist = "2010/11/06 08:58"
update = "2010/11/22 18:05"

[[entries]]
no = "22"
name = "kireji"
team = "赤紙"
title = "PARADE"
size = "19684 KB"
addr = ["http://www7a.biglobe.ne.jp/~kireji/mpe/kireji_parade_ogg.zip"]
genre = "HAPPY"
impr = "17"
total = "15050"
avg = "885.29"
regist = "2010/11/06 19:48"
update = "2010/11/21 00:30"

[[entries]]
no = "23"
name = "ルゼ"
team = "【未承諾広告】>>!!!差分募集中!!!<<<【今がチャンス】"
title = "Lang Tone"
size = "2460 KB"
addr = ["http://www.luzeria.net/music/55_langtone_ogg.rar"]
genre = "BUCKLER"
impr = "13"
total = "11915"
avg = "916.53"
regist = "2010/11/07 00:12"
update = "2010/11/21 08:02"

[[entries]]
no = "24"
name = "eqxetvmmfvv"
team = "eqxetvmmfvv"
title = "lchewsPcLLsbnVf"
size = "97 KB"
addr = [
    "6nJy6h",
    "http://zmmulpxbajdg.com/",
    '">zmmulpxbajdg, [url=',
    "http://xxjsksezlmwf.com/",
    "]xxjsksezlmwf[/url], [link=",
    "http://lcevhmkqibms.com/",
    "]lcevhmkqibms[/link],",
    "http://dgqushepmvzg.com/",
]
genre = "http://rklqvlhhdsih.com/"
impr = "30"
total = "3059"
avg = "101.96"
regist = "2010/11/07 10:53"
update = "2010/11/20 22:52"

[[entries]]
no = "25"
name = "xellox"
team = "(･x･`)"
title = "Voltex Highway"
size = "6918 KB"
addr = ["http://uploader.bms.ms/data/daisan/Voltex%20Highway.zip"]
genre = "TRANCE"
impr = "12"
total = "10064"
avg = "838.66"
regist = "2010/11/07 12:04"
update = "2010/11/23 01:16"

[[entries]]
no = "26"
name = "HEXAHEDRA"
team = "Digital Cyber Fragments"
title = "なつまつり"
size = "15683 KB"
addr = ["http://cid-b316e7f5b08d0178.office.live.com/self.aspx/BMS/natsumatsuri.rar"]
genre = "Nipponno natsu"
impr = "14"
total = "11270"
avg = "805"
regist = "2010/11/07 18:03"
update = "2010/11/20 23:52"

[[entries]]
no = "27"
name = "ラスとルーク / scytheleg"
team = "KOJIMA CRISIS"
title = "ASTRO(BGA差分)"
size = "9514 KB"
addr = ["http://scytheleg.bms.ms/tempyou/item/stl_astrobga.rar"]
genre = "SOFT LANDING"
impr = "10"
total = "8038"
avg = "803.8"
regist = "2010/11/07 20:55"
update = "2010/11/20 23:45"

[[entries]]
no = "28"
name = "MascleMissile"
team = "【未承諾広告】>>!!!差分募集中!!!<<<【今がチャンス】"
title = "Lang Tone -MascleMissileMix-"
size = "1000 KB"
addr = ["http://uploader.bms.ms/data/rnf/MastleMissile_langtone_sabun.zip"]
genre = "BUCKLER TRANCE"
impr = "6"
total = "5240"
avg = "873.33"
regist = "2010/11/07 21:28"
update = "2010/11/21 00:09"

[[entries]]
no = "29"
name = "narve remixed by Beast Synthesizer"
team = "自称無名作家"
title = "The Sorrow of The Islands (Lion Heart Records BMS Exclusive Mix)"
size = "17700 KB"
addr = ["http://cid-431ed7a67fde77a6.office.live.com/self.aspx/THE%20BMS/tsoti%5E_LHRemix.rar"]
genre = "TRANCE"
impr = "9"
total = "6567"
avg = "729.66"
regist = "2010/11/07 22:35"
update = "2010/11/21 01:12"

[[entries]]
no = "30"
name = "Shining Pegasus"
team = "11月20日"
title = "エコ"
size = "6483 KB"
addr = ["http://uploader.bms.ms/data/BOF2010Jougairantou/ECO_ogg.zip"]
genre = "TECHNO"
impr = "13"
total = "11064"
avg = "851.07"
regist = "2010/11/07 23:19"
update = "2010/11/20 23:59"

[[entries]]
no = "31"
name = "SmiGoon"
team = "【未承諾広告】>>!!!差分募集中!!!<<<【今がチャンス】"
title = "Lang Tone - sabun -"
size = "25 KB"
addr = ["http://pds20.egloos.com/pds/201011/09/91/55_langtone_ogg_sabunfix.rar"]
genre = "BUCKLER"
impr = "9"
total = "6690"
avg = "743.33"
regist = "2010/11/08 01:48"
update = "2010/11/20 22:54"

[[entries]]
no = "32"
name = "gmtn. remixed by xenothium"
team = "チーム他人のふんどし"
title = "L.S.D.-Hallucination Remix-"
size = "21097 KB"
addr = ["http://roaraddiction.mods.jp/bms/x011_lsdrmx.rar"]
genre = "UNKNOWN ELECTRO HOUSE"
impr = "12"
total = "10951"
avg = "912.58"
regist = "2010/11/08 14:06"
update = "2010/11/20 23:45"

[[entries]]
no = "33"
name = "Symphonian"
team = "【未承諾広告】>>!!!差分募集中!!!<<<【今がチャンス】"
title = "Lang Tone -DP+鬼-"
size = "53 KB"
addr = ["http://www1.axfc.net/uploader/Sc/so/171710"]
genre = "BUCKLER"
impr = "4"
total = "3380"
avg = "845"
regist = "2010/11/09 19:28"
update = "2010/11/20 22:55"

[[entries]]
no = "34"
name = "Sampling Disaster 咲-SAKI- VS Lion Heart-HD"
team = "Digital Cyber Fragments"
title = "Abnormally Great Old-king"
size = "17089 KB"
addr = ["http://uploader.bms.ms/data/%5BDigital%20Cyber%20Fragments%5DAbnormally%20Great%20Old-King.rar"]
genre = "NU HARD-TECH"
impr = "6"
total = "4611"
avg = "768.5"
regist = "2010/11/09 20:55"
update = "2010/11/21 00:00"

[[entries]]
no = "35"
name = "Tima"
team = "11月20日"
title = "Flying with R."
size = "2114 KB"
addr = ["http://tetra.s21.xrea.com/flwtr.html"]
genre = "HOUSE"
impr = "15"
total = "13237"
avg = "882.46"
regist = "2010/11/09 22:17"
update = "2010/11/20 23:57"

[[entries]]
no = "36"
name = "FALL"
team = "チーム他人のふんどし"
title = "Unexpected rain (likeside remix)"
size = "25313 KB"
addr = ["http://www.likeside.net/files/bms/uer_remix.zip"]
genre = "LIQUID FUNK"
impr = "17"
total = "15853"
avg = "932.52"
regist = "2010/11/09 23:17"
update = "2011/02/18 22:31"

[[entries]]
no = "37"
name = "ミディアム"
team = "メロディック"
title = "ガボット"
size = "5458 KB"
addr = ["http://freett.com/slashorblue/bof2010johgai.html"]
genre = "CLASSIC / GAME MUSIC STYLE"
impr = "11"
total = "9465"
avg = "860.45"
regist = "2010/11/10 01:19"
update = "2010/11/21 00:03"

[[entries]]
no = "38"
name = "DnB Hunter"
team = "ANIMAL CREW Part.1"
title = "Escape"
size = "8044 KB"
addr = [
    "http://cid-48a5474a28eaf5af.office.live.com/self.aspx/BMS/",
    "[DnB%20Hunter]%20Escape.rar",
    "(HQ Wav, NO BGA)",
]
genre = "Break Beat"
impr = "9"
total = "7290"
avg = "810"
regist = "2010/11/10 17:36"
update = "2010/11/20 23:48"

[[entries]]
no = "39"
name = "fdsa feat. sarah beara"
team = "赤紙"
title = 'asdfsong ("mix your own sytrus" mix)'
size = "23688 KB"
addr = ["http://uploader.bms.ms/data/asdfremix.rar"]
genre = "Trance"
impr = "11"
total = "9537"
avg = "867"
regist = "2010/11/11 07:07"
update = "2010/11/20 23:58"

[[entries]]
no = "40"
name = "Kei Izumi"
team = "俺のBMSがこんなに〇〇なわけがない"
title = "Erinnerung"
size = "16237 KB"
addr = ["http://prsq.sakura.ne.jp/data/erin_bms.zip"]
genre = "Acc. House"
impr = "13"
total = "11439"
avg = "879.92"
regist = "2010/11/11 22:34"
update = "2010/11/21 21:12"

[[entries]]
no = "41"
name = "LuL"
team = "Team Synth1 場外乱闘編"
title = "deep sea"
size = "6129 KB"
addr = ["http://www9.plala.or.jp/est/bms/est_deepsea.zip"]
genre = "Synth1 PROG"
impr = "12"
total = "10300"
avg = "858.33"
regist = "2010/11/11 23:34"
update = "2010/11/20 23:20"

[[entries]]
no = "42"
name = "DJ TAKUAN 及び 常緒"
team = "KOJIMA CRISIS"
title = "暮夏 ～20,Novem ver.～"
size = "6400 KB"
addr = ["http://djtakuan.sakura.ne.jp/bof_after.html"]
genre = "J-EURO"
impr = "13"
total = "11265"
avg = "866.53"
regist = "2010/11/12 00:47"
update = "2010/11/21 00:53"

[[entries]]
no = "43"
name = "Shinabro"
team = "Red Jewel Witness"
title = "Light Minutes Adventure"
size = "6442 KB"
addr = ["http://uploader.bms.ms/data/RJW/snbr_lma.zip"]
genre = "Plain BGM"
impr = "12"
total = "10315"
avg = "859.58"
regist = "2010/11/14 09:28"
update = "2010/11/20 23:47"

[[entries]]
no = "44"
name = "Ruby.G"
team = "Red Jewel Witness"
title = "Dance with me ~Be Music Mix~"
size = "15728 KB"
addr = ["http://uploader.bms.ms/data/RJW/rg_dwm.zip"]
genre = "Trance Pop"
impr = "11"
total = "9630"
avg = "875.45"
regist = "2010/11/14 09:31"
update = "2010/11/20 23:52"

[[entries]]
no = "45"
name = "Shinabro vs. Ruby.G pay respect to KRX"
team = "Red Jewel Witness"
title = "- [vacuum] ~poMELODYwer Mix~"
size = "8075 KB"
addr = ["http://uploader.bms.ms/data/RJW/none_vr.zip"]
genre = "Brainiac Melody"
impr = "16"
total = "14075"
avg = "879.68"
regist = "2010/11/14 09:36"
update = "2010/11/20 23:00"

[[entries]]
no = "46"
name = "無誠意"
team = "BMS実験"
title = "CUP"
size = "789 KB"
addr = ["http://uploader.bms.ms/data/CUP.zip"]
genre = "ComboUP"
impr = "12"
total = "8590"
avg = "715.83"
regist = "2010/11/15 18:01"
update = "2010/11/20 23:50"

[[entries]]
no = "47"
name = "44teru-k / noname"
team = "【未承諾広告】>>!!!差分募集中!!!<<<【今がチャンス】"
title = "悲伽羅香「水蓮」～花弁～(BGA差分)"
size = "14794 KB"
addr = ["http://yaruki0.sakura.ne.jp/sabun/suiren_BGA.zip"]
genre = "MIXTURE"
impr = "6"
total = "4635"
median = "767.5"
avg = "772.5"
regist = "2010/11/16 00:59"
update = "2016/11/26 01:27"

[[entries]]
no = "50"
name = "ミディアム"
team = "メロディック"
title = "トルコ行進曲"
size = "6395 KB"
addr = ["http://freett.com/slashorblue/bof2010johgai.html"]
genre = "CLASSIC / GAME MUSIC STYLE"
impr = "11"
total = "8764"
avg = "796.72"
regist = "2010/11/17 00:55"
update = "2010/11/21 00:03"

[[entries]]
no = "51"
name = "K137"
team = "Red Jewel Witness"
title = "DG-2 Ultimatum [ 差分 / OST ]"
size = "11 KB"
addr = [
    "http://uploader.bms.ms/data/RJW/04.%20DG-2%20Ultimatum.mp3",
    "[OST]",
    "http://uploader.bms.ms/data/dg2_7_gor.zip",
    "[SABUN]",
]
genre = "Psychedelic Trance / Sabun"
impr = "2"
total = "1400"
avg = "700"
regist = "2010/11/17 12:04"
update = "2010/11/20 23:01"

[[entries]]
no = "52"
name = "gmtn."
team = "(･x･`)"
title = "furioso melodia"
size = "9000 KB"
addr = ["http://gmtn.sub.jp/_carage_furioso_melodia_ogg.zip"]
genre = "GOTHIC HARDCORE"
impr = "11"
total = "10179"
avg = "925.36"
regist = "2010/11/19 00:48"
update = "2010/11/21 00:05"

[[entries]]
no = "53"
name = "DJ pinky"
team = "11月20日"
title = "25,March"
size = "1853 KB"
addr = [
    "http://www.geocities.jp/pink_no_cool/house.zip",
    "(右クリ保存してＮＥ！！)",
]
genre = "house"
impr = "4"
total = "3155"
avg = "788.75"
regist = "2010/11/20 00:00"
update = "2010/11/20 23:25"

[[entries]]
no = "54"
name = "Tribullets Plus"
team = "Tribullets++"
title = "Tribullets PlusMix"
size = "14746 KB"
addr = ["http://tribullets.info/bof2010/bof2010_tribulletsplus_mix.zip"]
genre = "MIX"
impr = "3"
total = "2540"
avg = "846.66"
regist = "2010/11/20 00:18"
update = "2010/11/23 20:08"

[[entries]]
no = "55"
name = "AHA*"
team = "ANIMAL CREW Part.1"
title = "starfall"
size = "15872 KB"
addr = ["http://uploader.bms.ms/data/starfall_ogg.zip"]
genre = "Space DnB"
impr = "4"
total = "3150"
avg = "787.5"
regist = "2010/11/20 23:08"
update = "2010/11/20 23:43"
