[[entries]]
no = "1"
name = "スーパーサイキッカー 藤井 -FUJY-"
title = "ダーク・アヴァターラ・ビーム"
size = "21173 KB"
addr = ["http://uploader.bms.ms/data/_dark_avatara_beam_ogg.zip"]
genre = "DARK FULL ON"
impr = "63"
total = "168"
avg = "2.66"
regist = "2011/02/26 00:01"
update = "2011/03/29 16:40"

[[entries]]
no = "2"
name = "Hidingpast"
title = "非徘徊主義"
size = "25931 KB"
addr = ["http://www5.pf-x.net/~nora2r/hihaikai.html"]
genre = "Rock"
impr = "29"
total = "55"
avg = "1.89"
regist = "2011/02/26 00:02"
update = "2011/03/28 22:36"

[[entries]]
no = "3"
name = "bounge"
title = "Big ben"
size = "14144 KB"
addr = ["http://bounge.sakura.ne.jp/WP2/index.html"]
genre = "Dubstep"
impr = "48"
total = "128"
avg = "2.66"
regist = "2011/02/26 00:02"
update = "2011/03/29 15:13"

[[entries]]
no = "4"
name = "Blegett Countess of Schwarz"
title = "ある雨の貴婦人の戯れ"
size = "9072 KB"
addr = ["http://uploader.bms.ms/data/Tawamure.zip"]
genre = "Deceptive Baroque"
impr = "29"
total = "70"
avg = "2.41"
regist = "2011/02/26 00:08"
update = "2011/03/28 09:01"

[[entries]]
no = "5"
name = "Domino Wagnar"
title = "it-is"
size = "51100 KB"
addr = ["http://dominowagnar.sphere.sc/itis.zip"]
genre = "Dub step"
impr = "36"
total = "76"
avg = "2.11"
regist = "2011/02/26 00:09"
update = "2011/03/27 23:50"

[[entries]]
no = "6"
name = "Gasbombe"
title = "Morgenglut"
size = "12000 KB"
addr = ["http://akiba.geocities.jp/bmsbms35/"]
genre = "Trance"
impr = "32"
total = "78"
avg = "2.43"
regist = "2011/02/26 00:17"
update = "2011/03/28 10:54"

[[entries]]
no = "7"
name = "桐生りおな with 上浦ひかる+4"
title = "eternal Rainbow POETISM"
size = "9883 KB"
addr = ["http://fdist.ps.land.to/bms/eternalRP.zip"]
genre = "J-EURO POP"
impr = "32"
total = "56"
avg = "1.75"
regist = "2011/02/26 00:20"
update = "2011/03/31 12:55"

[[entries]]
no = "8"
name = "Acid Age"
title = "Acid Fetishism"
size = "1489 KB"
addr = ["http://uploader.bms.ms/data/wp2/acid2.zip"]
genre = "Acid House"
impr = "38"
total = "97"
avg = "2.55"
regist = "2011/02/26 00:20"
update = "2011/03/28 22:30"

[[entries]]
no = "9"
name = "acidnyan"
title = "Verzerrung"
size = "5350 KB"
addr = ["http://uploader.bms.ms/data/Verzerrung.zip"]
genre = "hard techno"
impr = "30"
total = "63"
avg = "2.1"
regist = "2011/02/26 00:35"
update = "2011/03/28 17:28"

[[entries]]
no = "10"
name = "Vita"
title = "梅花の候"
size = "21917 KB"
addr = ["http://www1.axfc.net/uploader/Si/so/100474"]
genre = "PIANO INSTRUMENTAL"
impr = "35"
total = "90"
avg = "2.57"
regist = "2011/02/26 00:43"
update = "2011/03/27 23:49"

[[entries]]
no = "11"
name = "（ ＾ω＾）人（＾ω＾ ）"
title = "東北シカゴシティ"
size = "30500 KB"
addr = ["http://uploader.bms.ms/data/th_chicago.zip"]
genre = "HARDCORE"
impr = "32"
total = "54"
avg = "1.68"
regist = "2011/02/26 00:44"
update = "2011/03/27 23:58"

[[entries]]
no = "12"
name = "DJ Dolphin"
title = "Energy Dolphin"
size = "4350 KB"
addr = ["http://uploader.bms.ms/data/Energy_Dolphin.rar"]
genre = "TECH BREAKS"
impr = "27"
total = "65"
avg = "2.4"
regist = "2011/02/26 00:48"
update = "2011/03/27 23:58"

[[entries]]
no = "13"
name = "Nage Tomoe"
title = "スクラップ情熱"
size = "4441 KB"
addr = ["http://uploader.bms.ms/data/wp2/tomoe_scrapjonetsu.rar"]
genre = "TRIBAL HOUSE + TECHNO + BGM"
impr = "26"
total = "51"
avg = "1.96"
regist = "2011/02/26 01:04"
update = "2011/03/28 19:13"

[[entries]]
no = "14"
name = "The Dear Sexys"
title = "Luv 5 Dancer"
size = "28184 KB"
addr = ["http://uploader.bms.ms/data/luv_5_dancer_the_dear_sexys.zip"]
genre = "RAVE"
impr = "48"
total = "140"
avg = "2.91"
regist = "2011/02/26 10:46"
update = "2011/03/28 21:24"

[[entries]]
no = "15"
name = "Slash act"
title = "D.I.F"
size = "7000 KB"
addr = ["http://loda.jp/slashact/?id=1"]
genre = "Hardcore"
impr = "31"
total = "64"
avg = "2.06"
regist = "2011/02/26 12:59"
update = "2011/03/28 00:55"

[[entries]]
no = "16"
name = "DJ Ash Ketchum"
title = "LOSTSILVER"
size = "27844 KB"
addr = ["http://uploader.bms.ms/data/LOSUTOSIRUBA.zip"]
genre = "Grotesque Breaks"
impr = "36"
total = "76"
avg = "2.11"
regist = "2011/02/26 13:42"
update = "2011/03/27 23:58"

[[entries]]
no = "17"
name = "Scarfaith & Graviton"
title = "Twilight"
size = "2437 KB"
addr = ["http://uploader.bms.ms/data/scarfaith_twilight.zip"]
genre = "Drum & Bass"
impr = "39"
total = "112"
avg = "2.87"
regist = "2011/02/26 14:12"
update = "2011/03/28 00:11"

[[entries]]
no = "18"
name = "Erotic server"
title = "Endless drop"
size = "10805 KB"
addr = [
    "http://uploader.bms.ms/data/Ed.rar",
    "http://www.geocities.jp/pink_no_cool/BMS/Edsabun.zip",
    "(おまけ譜面。右クリ保存推奨。)",
]
genre = "dance"
impr = "28"
total = "65"
avg = "2.32"
regist = "2011/02/26 19:20"
update = "2011/04/01 16:31"

[[entries]]
no = "19"
name = "owl-light"
title = "Acid Squall"
size = "24106 KB"
addr = ["http://uploader.bms.ms/data/wirepuller/ol/%5Bowl-light%5Dacid_squall_ogg.zip"]
genre = "DRUM'N'BASS"
impr = "25"
total = "59"
avg = "2.36"
regist = "2011/02/27 00:00"
update = "2011/03/28 00:17"

[[entries]]
no = "20"
name = "OhunAnno"
title = "kamen_no_otoko"
size = "3795 KB"
addr = ["http://nekokan.dyndns.info/~anonymous/WirePuller2/kamen_no_otoko.zip"]
genre = "TECHNO"
impr = "27"
total = "55"
avg = "2.03"
regist = "2011/02/27 00:48"
update = "2011/03/28 00:09"

[[entries]]
no = "21"
name = "暁美ほむら"
title = "焔-HOMURA-"
size = "12939 KB"
addr = ["http://www1.axfc.net/uploader/Li/so/91785.zip"]
genre = "RENAISSANCE"
impr = "39"
total = "90"
avg = "2.3"
regist = "2011/02/27 08:43"
update = "2011/03/28 13:00"

[[entries]]
no = "22"
name = "Turaés"
title = "SEMITHESIZER"
size = "9172 KB"
addr = ["https://drive.google.com/open?id=0B7qCw4hNijr4dFpHSzYxTE5hMEU"]
genre = "FULL LACTOBACILLUS"
impr = "31"
total = "75"
median = "3"
avg = "2.41"
regist = "2011/02/27 14:48"
update = "2018/02/14 01:56"

[[entries]]
no = "23"
name = "Highway Radio"
title = "Incoming"
size = "5680 KB"
addr = ["http://uploader.bms.ms/data/incoming.zip"]
genre = "Bigbeat"
impr = "33"
total = "73"
avg = "2.21"
regist = "2011/02/27 15:38"
update = "2011/03/28 17:44"

[[entries]]
no = "24"
name = "Big Bang Phoenix"
title = "Fly away"
size = "9827 KB"
addr = [
    "http://uploader.bms.ms/data/wp2/wp2_flyaway.rar",
    "(あぷろだをお借りしupし直しました。)",
]
genre = "UK HARDCORE"
impr = "24"
total = "32"
avg = "1.33"
regist = "2011/02/27 17:19"
update = "2011/03/28 01:54"

[[entries]]
no = "25"
name = "Electro Magonotech DJ CHIBA"
title = "E.D.Life"
size = "5396 KB"
addr = ["http://members3.jcom.home.ne.jp/mani-_-mani/emdc_edl.zip"]
genre = "hiphop"
impr = "26"
total = "54"
avg = "2.07"
regist = "2011/02/27 18:22"
update = "2011/03/28 00:00"

[[entries]]
no = "26"
name = "Hydro Surveyor"
title = "The Deeptreader"
size = "9880 KB"
addr = ["http://uploader.bms.ms/data/wp2/Deeptreader.zip"]
genre = "TECHNO"
impr = "30"
total = "76"
avg = "2.53"
regist = "2011/02/27 20:51"
update = "2011/03/28 00:12"

[[entries]]
no = "27"
name = "ISH overdrive"
title = "rise to R"
size = "5345 KB"
addr = ["http://uploader.bms.ms/data/wp2/risetor.zip"]
genre = "SPEED RAVE"
impr = "27"
total = "50"
avg = "1.85"
regist = "2011/02/27 20:58"
update = "2011/03/28 05:29"

[[entries]]
no = "28"
name = "Passionate Explorer"
title = "Aviator"
size = "9530 KB"
addr = [
    "http://uploader.bms.ms/data/wp2/p_e_Aviator.zip",
    "(HQ-OGG)",
]
genre = "ENERGETIC TRANCE"
impr = "26"
total = "43"
avg = "1.65"
regist = "2011/02/27 21:34"
update = "2011/03/28 00:45"

[[entries]]
no = "29"
name = "nob undead"
title = "belong to..."
size = "6377 KB"
addr = [
    "http://cid-5c95bb1adfdcbf88.office.live.com/self.aspx/.Public/",
    "[nob]belong-to.rar",
]
genre = "TECHNIVAL"
impr = "26"
total = "59"
avg = "2.26"
regist = "2011/02/27 22:11"
update = "2011/03/28 00:00"

[[entries]]
no = "30"
name = "USOTA FUMINORI"
title = "Unfictioniam"
size = "8015 KB"
addr = ["http://gmtn.sub.jp/usota_fuminori.zip"]
genre = "SF ELECTRO"
impr = "39"
total = "109"
median = "3"
avg = "2.79"
regist = "2011/02/27 22:47"
update = "2014/05/18 21:06"

[[entries]]
no = "31"
name = "d8d88d888"
title = "Adhesive Vox-Derating"
size = "4976 KB"
addr = ["http://uploader.bms.ms/data/wp2/%5Bd8d88d888%5D_AVD.zip"]
genre = "HARD TECHNO"
impr = "25"
total = "50"
avg = "2"
regist = "2011/02/27 23:11"
update = "2011/03/31 19:58"

[[entries]]
no = "32"
name = "Midori"
title = "Verdigris"
size = "1920 KB"
addr = ["http://uploader.bms.ms/data/verdigris.zip"]
genre = "Ending..."
impr = "24"
total = "37"
avg = "1.54"
regist = "2011/02/27 23:18"
update = "2011/03/27 23:56"

[[entries]]
no = "33"
name = "HeARTy"
title = "Em Angel"
size = "3259 KB"
addr = ["http://www3.pf-x.net/~boxism-8500/bms.php?no=29&status=0"]
genre = "German Trance"
impr = "28"
total = "50"
avg = "1.78"
regist = "2011/02/27 23:31"
update = "2011/08/10 23:17"

[[entries]]
no = "34"
name = "wereeeeeeeeeeeeee!!!!!!"
title = "absolute cheese cheese!!!!!!"
size = "8890 KB"
addr = ["http://uploader.bms.ms/data/absolute_cheese_cheese%21%21%21%21%21%21.rar"]
genre = "GABBER HOUSE"
impr = "29"
total = "59"
avg = "2.03"
regist = "2011/02/27 23:43"
update = "2011/03/28 00:17"

[[entries]]
no = "35"
name = "dj STAR feat. KIMA"
title = "miss you..."
size = "24641 KB"
addr = ["http://uploader.bms.ms/data/sen-goku/wp2miss/miss_ogg.rar"]
genre = "J-TRANCE"
impr = "26"
total = "52"
avg = "2"
regist = "2011/02/27 23:47"
update = "2011/03/28 02:30"

[[entries]]
no = "36"
name = "Aerowings"
title = "The Radiant sky"
size = "5800 KB"
addr = ["http://uploader.bms.ms/data/wp2/aerowings_radiant_ogg_.zip"]
genre = "Happy Hardcore"
impr = "26"
total = "55"
avg = "2.11"
regist = "2011/02/27 23:50"
update = "2011/05/01 02:07"

[[entries]]
no = "37"
name = "electmentaloid"
title = "Gemstone Mine"
size = "19936 KB"
addr = ["http://uploader.bms.ms/data/sen-goku/gemstone_mine.rar"]
genre = "PROGRESSIVE HOUSE"
impr = "46"
total = "132"
avg = "2.86"
regist = "2011/02/27 23:56"
update = "2011/03/29 08:24"

[[entries]]
no = "38"
name = "Dragon Half"
title = "Sakura Avenue"
size = "13011 KB"
addr = ["http://uploader.bms.ms/data/sen-goku/sakura_a_ogg.rar"]
genre = "HAPPY HARDCORE"
impr = "28"
total = "55"
avg = "1.96"
regist = "2011/02/27 23:58"
update = "2011/03/29 07:33"

[[entries]]
no = "39"
name = "Magic Mash Man / New Genuine Magicial Girl"
title = "AXION"
size = "46747 KB"
addr = [
    "http://ms-x.info/magicmashman/",
    "[magicmashman]_axion.zip",
    "http://uploader.bms.ms/data/wp2/%5Bmagicmashman%5D_axion.zip",
]
genre = "Chaos fantasia"
impr = "79"
total = "231"
avg = "2.92"
regist = "2011/02/27 23:59"
update = "2011/03/28 20:29"

[[entries]]
no = "40"
name = "dake jan A.I"
title = "店舗が違う変人店"
size = "6291 KB"
addr = [
    "http://uploader.bms.ms/data/wp2/henjinremix.zip",
    "音が抜ける現象が起きるようですので、",
    "http://uploader.bms.ms/data/wp2/henjinremix_shusei.zip",
    "お手数ですがこちらの差分を当てて下さい。",
]
genre = "hip hop"
impr = "33"
total = "94"
avg = "2.84"
regist = "2011/02/27 23:59"
update = "2011/03/28 01:17"
