[[entries]]
no = "1"
name = "叔父貴"
title = "叔父貴"
size = "5090 KB"
addr = ["http://uploader.bms.ms/data/ojiki_ogg.rar"]
genre = "HEN-TEK"
impr = "38"
total = "142"
avg = "3.73"
regist = "2011/02/26 00:01"
update = "2011/03/27 23:50"

[[entries]]
no = "2"
name = "野々原ふり子 feat. ロイヤル橋本"
title = "ラブラブ79.99%急接近！？ ～となりのカレはノコギリ波☆～"
size = "25243 KB"
addr = [
    "(ogg 24MB)",
    "http://uploader.bms.ms/data/furikononohara/furiko_nonohara_ogg.zip",
]
genre = "TRANCECORE"
impr = "44"
total = "177"
avg = "4.02"
regist = "2011/02/26 00:03"
update = "2011/03/28 22:06"

[[entries]]
no = "3"
name = "daisuke@92"
title = "Suspicion 13reeds Phantoms"
size = "4782 KB"
addr = ["http://fdist.ps.land.to/bms/S13P.zip"]
genre = "jungle"
impr = "35"
total = "128"
avg = "3.65"
regist = "2011/02/26 00:08"
update = "2011/03/28 00:14"

[[entries]]
no = "4"
name = "candy ★ juice"
title = "enjoy walker"
size = "8400 KB"
addr = ["http://nekokan.dyndns.info/~anonymous/test/enjoywalker.zip"]
genre = "TECHNO POP"
impr = "35"
total = "125"
avg = "3.57"
regist = "2011/02/26 00:10"
update = "2011/03/27 23:52"

[[entries]]
no = "5"
name = "PhotonFairy"
title = "kalter himmel"
size = "52083 KB"
addr = [
    "wav版：",
    "http://uploader.bms.ms/data/sen-goku/kalter/kalter_himmel_HQ.rar",
    "ogg版：",
    "http://uploader.bms.ms/data/sen-goku/kalter/kalter_himmel_LQ.rar",
]
genre = "TRANCE"
impr = "33"
total = "133"
avg = "4.03"
regist = "2011/02/26 00:16"
update = "2011/03/28 00:58"

[[entries]]
no = "6"
name = "Learicorn"
title = "IMPERIAL HUSSAR"
size = "7510 KB"
addr = ["http://uploader.bms.ms/data/imperial_h.rar"]
genre = "TRANCE CORE"
impr = "34"
total = "132"
avg = "3.88"
regist = "2011/02/26 00:29"
update = "2011/03/28 01:34"

[[entries]]
no = "7"
name = "KEMICALISS"
title = "QB"
size = "3441 KB"
addr = ["http://uploader.bms.ms/data/nanchattemumei/kemicaliss_qb.zip"]
genre = "MINIMAL TECHNO"
impr = "29"
total = "108"
avg = "3.72"
regist = "2011/02/26 00:52"
update = "2011/03/28 02:05"

[[entries]]
no = "8"
name = "sweet smeller"
title = "サクライロフワリ"
size = "29576 KB"
addr = ["http://uploader.bms.ms/data/sakurairo_ogg.zip"]
genre = "TECHNO POP"
impr = "56"
total = "276"
avg = "4.92"
regist = "2011/02/26 00:54"
update = "2011/03/28 00:15"

[[entries]]
no = "9"
name = "Frontier Lyric"
title = "Arctic Echoes"
size = "7188 KB"
addr = ["http://uploader.bms.ms/data/AE.zip"]
genre = "INSTRUMENTAL"
impr = "32"
total = "131"
avg = "4.09"
regist = "2011/02/26 00:58"
update = "2011/03/28 00:20"

[[entries]]
no = "10"
name = "Arkham Miskatonic"
title = "Shining Trapezohedron"
size = "52073 KB"
addr = ["http://uploader.bms.ms/data/nanchattemumei/Shining_Trapezohedron.zip"]
genre = "TRANCE CORE"
impr = "29"
total = "78"
avg = "2.68"
regist = "2011/02/26 01:35"
update = "2011/03/28 04:24"

[[entries]]
no = "11"
name = "Vanitas"
title = "Sector Zero"
size = "10585 KB"
addr = ["http://uploader.bms.ms/data/nanchattemumei/sector_zero.zip"]
genre = "Trance"
impr = "29"
total = "44"
avg = "1.51"
regist = "2011/02/26 08:58"
update = "2011/03/28 09:26"

[[entries]]
no = "12"
name = "XEOEXE"
title = "The Gorilla"
size = "8289 KB"
addr = [
    "http://uploader.bms.ms/?download=Gorilla.zip",
    "◆ 曲変更差分（難易度やんわり版） ◆",
    "http://uploader.bms.ms/?download=otegaru_gorilla_pack.zip",
]
genre = "Techno"
impr = "35"
total = "122"
avg = "3.48"
regist = "2011/02/26 20:55"
update = "2012/03/08 17:43"

[[entries]]
no = "13"
name = "Plane"
title = "planetary ring"
size = "4420 KB"
addr = ["http://uploader.bms.ms/data/Plane/planetary_ring_ogg.rar"]
genre = "astronomy"
impr = "29"
total = "95"
avg = "3.27"
regist = "2011/02/26 22:35"
update = "2011/03/28 20:24"

[[entries]]
no = "14"
name = "Airlia"
title = "Sylphy"
size = "7934 KB"
addr = ["http://nekokan.dyndns.info/~anonymous/sylphy.zip"]
genre = "TRANCE"
impr = "38"
total = "177"
avg = "4.65"
regist = "2011/02/27 01:05"
update = "2011/03/28 22:26"

[[entries]]
no = "15"
name = "hachikuro"
title = "CONGA BOOB"
size = "10386 KB"
addr = ["削除しました"]
genre = "Half Step"
impr = "29"
total = "89"
avg = "3.06"
regist = "2011/02/27 16:04"
update = "2012/08/29 21:44"

[[entries]]
no = "16"
name = "姫沙羅"
title = "Sileighty"
size = "39313 KB"
addr = ["http://uploader.bms.ms/data/sileighty.rar"]
genre = "TECHNO TRANCE NRG RAVE"
impr = "33"
total = "150"
avg = "4.54"
regist = "2011/02/28 15:54"
update = "2011/03/28 16:07"

[[entries]]
no = "17"
name = "流菜"
title = "LimeGame"
size = "20206 KB"
addr = ["http://uploader.bms.ms/data/LimeGame_ogg.zip"]
genre = "FreeStyle"
impr = "26"
total = "61"
avg = "2.34"
regist = "2011/02/28 16:45"
update = "2011/03/28 17:37"

[[entries]]
no = "18"
name = "Jump"
title = "Step"
size = "12200 KB"
addr = ["http://uploader.bms.ms/data/hsj.zip"]
genre = "Hop"
impr = "28"
total = "94"
avg = "3.35"
regist = "2011/02/28 19:31"
update = "2011/03/27 23:10"

[[entries]]
no = "19"
name = "tekmin"
title = "gamansinight"
size = "5200 KB"
addr = ["http://uploader.bms.ms/data/gamansinight.zip"]
genre = "techno"
impr = "30"
total = "104"
avg = "3.46"
regist = "2011/02/28 23:36"
update = "2011/03/28 17:30"

[[entries]]
no = "20"
name = "I'm your excrement"
title = "DRUM'N'BASSFXXKERZ"
size = "8260 KB"
addr = ["http://uploader.bms.ms/data/4-I%27m_your_excrement-DRUM%27N%27BASSFXXKERZ.rar"]
genre = "JUMP UP"
impr = "39"
total = "158"
avg = "4.05"
regist = "2011/02/28 23:43"
update = "2011/03/28 00:41"

[[entries]]
no = "21"
name = "星霜ステラ"
title = "凍て空の結晶"
size = "6290 KB"
addr = ["http://uploader.bms.ms/data/nanchattemumei/stella_itezora.zip"]
genre = "Lonely"
impr = "32"
total = "120"
avg = "3.75"
regist = "2011/02/28 23:47"
update = "2011/05/01 03:01"
