[[entries]]
no = "1"
name = "CRUNCH (mov:artslight)"
title = "ホログラムガール"
size = "23000 KB"
addr = ["http://uploader.bms.ms/?download=hologram_girl.rar"]
genre = "ホログラムバレットビート"
impr = "30"
total = "74"
avg = "2.46"
regist = "2011/04/16 00:00"
update = "2011/05/15 22:56"

[[entries]]
no = "2"
name = "primrose"
title = "Birdies' Perch ～小鳥たちのとまり木～"
size = "9760 KB"
addr = [
    "http://uploader.bms.ms/data/SPRING%209KEYS%20ROAD%202011/birdiesperchS9Roads.zip",
    "(音量調整版)",
]
genre = "スプリングヴェール"
impr = "29"
total = "59"
avg = "2.03"
regist = "2011/04/16 00:00"
update = "2011/05/15 00:02"

[[entries]]
no = "3"
name = "U.P."
title = "Little Little Jodel"
size = "10000 KB"
addr = [
    "http://uploader.bms.ms/data/artslight/LittleLittleJodel.zip",
    "http://ux.getuploader.com/bms_up/download/15/LittleLittleJodel.zip",
]
genre = "ディジタルヨーデル"
impr = "30"
total = "67"
avg = "2.23"
regist = "2011/04/16 00:03"
update = "2011/05/15 02:03"

[[entries]]
no = "4"
name = "xi"
title = "Beatrice"
size = "14771 KB"
addr = ["http://music-side.com/pms/xi_beatrice_ogg.zip"]
genre = "マジックジャズ"
impr = "32"
total = "87"
avg = "2.71"
regist = "2011/04/16 00:05"
update = "2011/05/16 21:18"

[[entries]]
no = "5"
name = "DJ TAKUAN 及び 白羽美依"
title = "HAPPY☆LUCKY☆BABY"
size = "23500 KB"
addr = ["http://djtakuan.sakura.ne.jp/event_pms.html"]
genre = "Jハッピコ！"
impr = "37"
total = "106"
avg = "2.86"
regist = "2011/04/16 00:07"
update = "2011/05/14 23:55"

[[entries]]
no = "6"
name = "bj.HaLo"
title = "Lineus longissimus"
size = "7640 KB"
addr = ["http://uploader.bms.ms/data/ll.zip"]
genre = "ブトロックゴア"
impr = "26"
total = "54"
avg = "2.07"
regist = "2011/04/16 00:12"
update = "2011/05/14 23:55"

[[entries]]
no = "7"
name = "Holidra.K"
title = "Grass-land Song"
size = "4200 KB"
addr = [
    "http://ux.getuploader.com/fors9r/download/1/Grass-land_Song%5BforS9L%5D.zip",
    "http://uploader.bms.ms/data/Grass-land_Song%5BforS9R%5D.zip",
    "（ミラー）",
]
genre = "ポップス"
impr = "27"
total = "59"
avg = "2.18"
regist = "2011/04/16 00:21"
update = "2011/05/15 00:13"

[[entries]]
no = "8"
name = "ねこみりん"
title = "THE ROYAL"
size = "2310 KB"
addr = [
    "http://www.nekomirin.com/bms/nekomirin_the_royal_HQogg.zip",
    "【HQ(ogg)：2.31MB】",
    "http://www.nekomirin.com/bms/nekomirin_the_royal.zip",
    "【MQ(wave)：2.69MB】",
    "※404などDLができない場合は下記URLからミラー先をご利用くださいませ。",
]
genre = "ロイヤルテクノ"
impr = "32"
total = "82"
avg = "2.56"
regist = "2011/04/16 00:27"
update = "2012/10/03 01:43"

[[entries]]
no = "9"
name = "SUMMERSUNSET"
title = "LATTICE"
size = "1969 KB"
addr = [
    "http://r9arrowhead.zouri.jp/lattice.zip",
    "http://uploader.bms.ms/?download=lattice.zip",
]
genre = "チップチューン"
impr = "23"
total = "46"
avg = "2"
regist = "2011/04/16 00:43"
update = "2011/05/14 19:38"

[[entries]]
no = "10"
name = "daisan"
title = "La nuit de la poupe'e"
size = "11157 KB"
addr = ["http://uploader.bms.ms/data/daisan/La%20nuit%20de%20la%20poupe%27e.zip"]
genre = "スウィングナイトジャズ"
impr = "30"
total = "81"
avg = "2.7"
regist = "2011/04/16 00:48"
update = "2011/05/15 01:50"

[[entries]]
no = "11"
name = "Holidra.K"
title = "DeepBlue"
size = "4432 KB"
addr = [
    "http://ux.getuploader.com/fors9r/download/3/DeepBlue%5BforS9R%5D.zip",
    "http://uploader.bms.ms/data/DeepBlue%5BforS9R%5D.zip",
    "（ミラー）",
]
genre = "深海シンスロック"
impr = "26"
total = "59"
avg = "2.26"
regist = "2011/04/16 01:14"
update = "2011/05/15 00:14"

[[entries]]
no = "12"
name = "Epiden-drum"
title = "YelLow sun"
size = "15500 KB"
addr = ["http://uploader.bms.ms/data/SPRING%209KEYS%20ROAD%202011/YLs.zip"]
genre = "ヒーリング"
impr = "24"
total = "46"
avg = "1.91"
regist = "2011/04/16 01:37"
update = "2011/05/16 21:36"

[[entries]]
no = "13"
name = "RearDawn"
title = "エゴクラッシュ"
size = "7329 KB"
addr = ["http://fdist.ps.land.to/bms/egocrash.zip"]
genre = "ブロークンハートコア"
impr = "22"
total = "44"
avg = "2"
regist = "2011/04/16 06:32"
update = "2011/05/14 23:31"

[[entries]]
no = "14"
name = "めｎち"
title = "Haunted◆Halloween"
size = "19600 KB"
addr = [
    "http://www1.axfc.net/uploader/N/so/125047",
    "http://menchi.cocona.jp/hauntedhalloween.zip",
    "(ミラー)",
]
genre = "ハロウィン"
impr = "28"
total = "71"
avg = "2.53"
regist = "2011/04/16 10:23"
update = "2011/05/15 11:11"

[[entries]]
no = "15"
name = "DeathisM(CP.ARCHE's Another mind)"
title = "L.i.N.e"
size = "8550 KB"
addr = [
    "http://cid-1d617b05411dafa3.office.live.com/self.aspx/BMS/LiNe%5E_DeathisM.zip",
    "http://www.mediafire.com/?l4k104jriz127k2",
    "http://uploader.bms.ms/data/LiNe_DeathisM.zip",
]
genre = "Drum'n Bass"
impr = "26"
total = "34"
avg = "1.3"
regist = "2011/04/16 16:31"
update = "2011/05/14 23:08"

[[entries]]
no = "16"
name = "髭姫"
title = "Snow Days"
size = "10676 KB"
addr = ["http://higehime.main.jp/bms/higehime_snowdays.zip"]
genre = "テクノポップ"
impr = "22"
total = "42"
avg = "1.9"
regist = "2011/04/17 01:03"
update = "2011/05/14 23:09"

[[entries]]
no = "17"
name = "covered by dawn-system"
title = "季節外れの赤とんぼ (2011 spring cover)"
size = "6568 KB"
addr = [
    "http://fdist.ps.land.to/bms/akatombo2011.zip",
    "http://fdist.ps.land.to/bms/akatombo_syuusei.zip",
    "（修正譜面差分のみ）",
]
genre = "スプリングＪ‐ロック"
impr = "21"
total = "44"
avg = "2.09"
regist = "2011/04/17 01:13"
update = "2011/05/15 00:12"

[[entries]]
no = "18"
name = "神風"
title = "誰が為の戦い"
size = "28371 KB"
addr = ["http://whirlwind.boy.jp/bms/kamikaze_tagatame_ogg.lzh"]
genre = "チープトイポップ⇒反逆デジロック"
impr = "30"
total = "77"
avg = "2.56"
regist = "2011/04/17 03:11"
update = "2011/05/14 23:59"

[[entries]]
no = "19"
name = "ippi@"
title = "Tiny First"
size = "4600 KB"
addr = [
    "http://uploader.bms.ms/data/SPRING%209KEYS%20ROAD%202011/TinyFirst_ogg.rar",
    "[ogg:4.6MB]",
    "http://uploader.bms.ms/data/SPRING%209KEYS%20ROAD%202011/Tiny%20First_wav.rar",
    "[wav:29.2MB]",
]
genre = "エレクトリックステップ"
impr = "24"
total = "47"
avg = "1.95"
regist = "2011/04/17 13:36"
update = "2011/05/14 23:17"

[[entries]]
no = "20"
name = "nmk"
title = "Abuse"
size = "11652 KB"
addr = ["http://www1.axfc.net/uploader/Li/so/95915.zip"]
genre = "フリコロック"
impr = "24"
total = "60"
avg = "2.5"
regist = "2011/04/17 17:32"
update = "2011/05/14 23:18"

[[entries]]
no = "21"
name = "kei_iwata"
title = "CODE-S -Symphonic system-"
size = "5030 KB"
addr = ["http://kei.raindrop.jp/bms/code-s.zip"]
genre = "サイケデリックトランス"
impr = "27"
total = "53"
avg = "1.96"
regist = "2011/04/17 19:41"
update = "2011/05/14 23:19"

[[entries]]
no = "22"
name = "###作曲者は昇天しました。###"
title = "HEAVEN'S CALL(呼ばれました)"
size = "21900 KB"
addr = [
    "###このURLは告死されました。###",
    "###このURLは告死されました。###",
    "http://endymium.net/bms/slpls_heavenscall_7keys.zip",
]
genre = "###このジャンルは告死されました。###"
impr = "25"
total = "51"
avg = "2.04"
regist = "2011/04/18 01:20"
update = "2011/05/15 01:01"

[[entries]]
no = "23"
name = "Shinabro"
title = "darksome"
size = "29677 KB"
addr = ["http://uploader.bms.ms/data/snbr_ds.zip"]
genre = "ダーク・インストゥルメンタル・アンビエント"
impr = "29"
total = "79"
avg = "2.72"
regist = "2011/04/18 02:01"
update = "2011/05/14 23:59"

[[entries]]
no = "24"
name = "wigen_"
title = "Loli Plaza"
size = "14757 KB"
addr = ["http://neoarre.aquz.biz/xe/event_download"]
genre = "ハウスポップ"
impr = "40"
total = "120"
avg = "3"
regist = "2011/04/18 03:11"
update = "2011/05/14 23:59"

[[entries]]
no = "25"
name = "tarolabo/石王マサト/ルゼ"
title = "sterminio"
size = "25119 KB"
addr = [
    "http://page.freett.com/tarolabo/sterminio.html",
    "http://www.fnbi.jp/tarolabo/sterminio.zip",
]
genre = "フトゥリズモ"
impr = "39"
total = "116"
avg = "2.97"
regist = "2011/04/19 19:38"
update = "2011/05/15 00:58"

[[entries]]
no = "26"
name = "TOMA"
title = "Electric Girl"
size = "4627 KB"
addr = ["http://www9.plala.or.jp/est/bms/est_eg.zip"]
genre = "ハッピーガバ"
impr = "27"
total = "70"
avg = "2.59"
regist = "2011/04/19 22:54"
update = "2011/05/14 23:24"

[[entries]]
no = "27"
name = "かゆき"
title = "いつか見た虹の先へ"
size = "5700 KB"
addr = ["http://www1.axfc.net/uploader/Ne/so/106819"]
genre = "POPS"
impr = "22"
total = "51"
avg = "2.31"
regist = "2011/04/20 15:50"
update = "2011/05/14 23:25"

[[entries]]
no = "28"
name = "DETROITMELTDOWN (RMHN/KRX)"
title = "SUGAR RUSH"
size = "20056 KB"
addr = [
    "http://www.mediafire.com/?0v6d95rz5qsz3kf",
    "http://uploader.bms.ms/data/SPRING%209KEYS%20ROAD%202011/DM_SUGARRUSH.rar",
]
genre = "電子音楽"
impr = "29"
total = "59"
avg = "2.03"
regist = "2011/04/21 04:23"
update = "2011/05/14 23:45"

[[entries]]
no = "29"
name = "eio"
title = "sky landscape"
size = "54008 KB"
addr = ["---"]
genre = "リトルヘブンリィ"
impr = "22"
total = "48"
avg = "2.18"
regist = "2011/04/21 17:54"
update = "2012/04/22 18:07"

[[entries]]
no = "30"
name = "Yukiji Houjo / hi-low / mitumeusagi"
title = "World ZERO(Yukiji Pieced Edit)"
size = "26900 KB"
addr = ["http://dl.dropbox.com/u/16367925/worldzero.rar"]
genre = "ワールドゼロ"
impr = "25"
total = "60"
avg = "2.4"
regist = "2011/04/22 05:56"
update = "2011/05/14 23:51"

[[entries]]
no = "31"
name = "市川"
title = "Sunshine Hiker"
size = "13500 KB"
addr = ["http://www1.axfc.net/uploader/Li/so/96298"]
genre = "ハネポップ"
impr = "21"
total = "28"
avg = "1.33"
regist = "2011/04/22 20:30"
update = "2011/05/14 23:40"

[[entries]]
no = "32"
name = "Symphonian"
title = "EXODUS"
size = "28758 KB"
addr = ["http://www.symphonian.co.kr/bms/EXODUS.rar"]
genre = "インダストリアルロック"
impr = "28"
total = "73"
avg = "2.6"
regist = "2011/04/23 00:44"
update = "2011/05/15 01:42"

[[entries]]
no = "33"
name = "Y.W"
title = "はるいろ こみち"
size = "13701 KB"
addr = ["http://www.yw-works.com/data/bm/haruiro_komichi_ogg.zip"]
genre = "ポップリスニング"
impr = "28"
total = "84"
avg = "3"
regist = "2011/04/23 11:16"
update = "2011/05/14 23:46"

[[entries]]
no = "34"
name = "Frost_Shrike"
title = "melange of memories"
size = "3300 KB"
addr = [
    "http://www.geocities.jp/shimomozu/bms/FrS12_mom-ogg.zip",
    "＊右クリック保存でお願いします",
]
genre = "リコレクション2"
impr = "25"
total = "63"
avg = "2.52"
regist = "2011/04/23 20:47"
update = "2011/05/23 00:23"

[[entries]]
no = "35"
name = "xenothium"
title = "Violet Perfume"
size = "55525 KB"
addr = [
    "[wav版]",
    "http://roaraddiction.mods.jp/bms/x015_vp_wav.rar",
    "[ogg版]",
    "http://roaraddiction.mods.jp/bms/x015_vp_ogg.rar",
]
genre = "ナイトハイウェイハウス"
impr = "26"
total = "67"
avg = "2.57"
regist = "2011/04/24 01:37"
update = "2011/05/14 23:48"

[[entries]]
no = "36"
name = "ルゼ"
title = "GRANDMASTER : IMPOSSIBLE"
size = "5870 KB"
addr = ["http://www.luzeria.net/music/59_grandmasterSPEED.rar"]
genre = "グランドマスタースピード"
impr = "26"
total = "69"
avg = "2.65"
regist = "2011/04/24 16:43"
update = "2011/05/15 02:03"

[[entries]]
no = "37"
name = "rhomb"
title = "Triunph !i"
size = "23868 KB"
addr = ["http://www1.axfc.net/uploader/Si/so/105554"]
genre = "Confluence"
impr = "26"
total = "32"
avg = "1.23"
regist = "2011/04/24 20:17"
update = "2011/05/14 23:49"

[[entries]]
no = "38"
name = "TRANCE WARRIORS"
title = "OPTICA(MEGA-BATTLE MIX)"
size = "32800 KB"
addr = ["公開終了"]
genre = "バトルトランス"
impr = "25"
total = "64"
median = "0"
avg = "2.56"
regist = "2011/04/24 20:18"
update = "2019/08/10 01:05"

[[entries]]
no = "39"
name = "fkRadish"
title = "Frost"
size = "9345 KB"
addr = ["http://uploader.bms.ms/data/frost_ogg.zip"]
genre = "アンビエントビーツ"
impr = "20"
total = "44"
avg = "2.2"
regist = "2011/04/24 20:34"
update = "2011/05/15 19:36"

[[entries]]
no = "40"
name = "taqumi"
title = "sonic boom boost"
size = "15800 KB"
addr = ["http://music-side.com/pms/sonic_boom_boost.zip"]
genre = "R2ドラムンベース"
impr = "23"
total = "58"
avg = "2.52"
regist = "2011/04/24 22:35"
update = "2011/05/14 23:51"

[[entries]]
no = "41"
name = "Kei Izumi"
title = "恋情Tuesday"
size = "9183 KB"
addr = ["http://prsq.sakura.ne.jp/data/syouwaroid_bms_ogg.zip"]
genre = "ショウワロイド"
impr = "22"
total = "55"
avg = "2.5"
regist = "2011/04/24 22:40"
update = "2011/05/15 11:48"

[[entries]]
no = "42"
name = "kei_iwata"
title = "虹のシンフォニー"
size = "13000 KB"
addr = [
    "http://kei.raindrop.jp/bms/symphonyofrainbow.zip",
    "(4/24/23:14分以前にDLされた方は最DLお願いします！IRに登録できるようにしました！)",
]
genre = "オーバーザレインボー"
impr = "25"
total = "60"
avg = "2.4"
regist = "2011/04/24 22:51"
update = "2011/05/14 23:51"

[[entries]]
no = "43"
name = "momo★yama"
title = "Fight in the field ～草原の孤狼～"
size = "12007 KB"
addr = ["http://dl.dropbox.com/u/59483835/battlefield.zip"]
genre = "バトルフィールド"
impr = "22"
total = "58"
avg = "2.63"
regist = "2011/04/24 23:28"
update = "2012/06/08 00:28"

[[entries]]
no = "44"
name = "pastel white"
title = "旅しらべ"
size = "21392 KB"
addr = [
    "http://kbwnk.net/data/pw_ts_hqogg.rar",
    "http://kbw.skr.jp/data/pw_ts_hqogg.rar",
    "（ミラー）",
]
genre = "トワイライト ポップ"
impr = "26"
total = "77"
avg = "2.96"
regist = "2011/04/24 23:52"
update = "2011/05/15 02:19"

[[entries]]
no = "45"
name = "Yosk!"
title = "TRUTH↓"
size = "1644 KB"
addr = ["https://drive.google.com/open?id=0B7qCw4hNijr4dk5UWFJBYk40enM"]
genre = "プロムナード"
impr = "26"
total = "54"
median = "1"
avg = "2.07"
regist = "2011/04/24 23:56"
update = "2018/02/14 02:01"

[[entries]]
no = "46"
name = "Speed Magician"
title = "Thirty Minutes Magic"
size = "9817 KB"
addr = ["http://uploader.bms.ms/data/sm_ttmm.zip"]
genre = "サンジュップンクラブハウス"
impr = "25"
total = "40"
avg = "1.6"
regist = "2011/04/24 23:57"
update = "2011/05/14 23:52"

[[entries]]
no = "47"
name = "洞爺湖スウィマーズ"
title = "ツーリング☆UFO ★Universal.Fu-gashi.Ondo★彡"
size = "4721 KB"
addr = [
    "ogg版",
    "http://uploader.bms.ms/data/SPRING%209KEYS%20ROAD%202011/UFO_ogg.zip",
    "wav版",
    "http://uploader.bms.ms/data/SPRING%209KEYS%20ROAD%202011/UFO.zip",
]
genre = "パッショネイトテクノアタック"
impr = "24"
total = "63"
avg = "2.62"
regist = "2011/04/24 23:59"
update = "2011/05/16 01:18"
