[[entries]]
no = "1"
name = "雪"
title = "feign"
size = "5 KB"
addr = ["http://snowdrop-pure.hp.infoseek.co.jp/music/feign.rar"]
genre = "minimal"
impr = "3"
total = "3"
avg = "1"
update = "2002/12/27 20:01"

[[entries]]
no = "2"
name = "竹"
title = "Granule"
size = "4 KB"
addr = ["http://isweb45.infoseek.co.jp/art/chikuwa3/arc-box/granule.rar"]
genre = "minimal"
impr = "3"
total = "3"
avg = "1"
update = "2002/12/24 23:15"

[[entries]]
no = "3"
name = "死"
title = "∫"
size = "5 KB"
addr = ["http://www16.big.or.jp/~shockc/bms/c_5kb.cab"]
genre = "minimal"
impr = "2"
total = "2"
avg = "1"
update = "2002/12/24 18:42"

[[entries]]
no = "4"
name = "葱&柳"
title = "TETRINET"
size = "5 KB"
addr = ["http://tokonats.cside5.com/shammy/bm/te.cab"]
genre = "TETRINET(Game)"
impr = "13"
total = "13"
avg = "1"
update = "2002/12/24 23:35"

[[entries]]
no = "5"
name = "あも"
title = "xi -gokebi mix-"
size = "5 KB"
addr = ["http://homepage3.nifty.com/amo_terra/5kmix.rar"]
genre = "techno"
impr = "3"
total = "3"
avg = "1"
update = "2002/12/28 21:12"

[[entries]]
no = "6"
name = "匠"
title = "ヽ（*^・▽ゝ・^*）y-~~"
size = "3 KB"
addr = ["http://ruz.s12.xrea.com/f3.cab"]
genre = "-"
impr = "2"
total = "2"
avg = "1"
update = "2002/12/24 19:11"

[[entries]]
no = "7"
name = "1 5 m i n i t u e"
title = "0 0 1"
size = "5 KB"
addr = ["http://warabeat.hp.infoseek.co.jp/001.rar"]
genre = "hardcore breakbeats"
impr = "3"
total = "3"
avg = "1"
update = "2002/12/24 22:50"

[[entries]]
no = "8"
name = "銀"
title = "Reptile"
size = "4 KB"
addr = ["http://www2.ocn.ne.jp/~nidoran/ag.cab"]
genre = "Digi Rock"
impr = "5"
total = "5"
avg = "1"
update = "2002/12/27 23:51"

[[entries]]
no = "9"
name = "s"
title = "G"
size = "5 KB"
addr = ["http://www5.ocn.ne.jp/~yutans/g.rar"]
genre = "TECHNO"
impr = "2"
total = "2"
avg = "1"
update = "2002/12/24 23:02"

[[entries]]
no = "10"
name = "肉酢"
title = "sgnl"
size = "5 KB"
addr = ["http://www.geocities.co.jp/MusicStar-Drum/9465/sgnl.cab"]
genre = "techno"
impr = "1"
total = "1"
avg = "1"
update = "2002/12/24 20:30"

[[entries]]
no = "11"
name = "-"
title = "beat on"
size = "5 KB"
addr = ["-"]
genre = "drumfunk"
impr = "1"
total = "1"
avg = "1"
update = "2002/12/30 15:37"

[[entries]]
no = "12"
name = "葱"
title = "ダンジョンBGM.1"
size = "4 KB"
addr = ["http://tokonats.cside5.com/shammy/bm/atlnzd1.cab"]
genre = "アトランチスの謎"
impr = "1"
total = "1"
avg = "1"
update = "2002/12/24 20:44"

[[entries]]
no = "13"
name = "arktbnk"
title = "sis.m"
size = "5 KB"
addr = ["-"]
genre = "trance"
impr = "2"
total = "2"
avg = "1"
update = "2002/12/29 18:51"

[[entries]]
no = "14"
name = "俊"
title = "雑音"
size = "5 KB"
addr = ["http://www9.ocn.ne.jp/~we-love/zatsuon.cab"]
genre = "imitation noise"
impr = "2"
total = "2"
avg = "1"
update = "2002/12/26 14:12"

[[entries]]
no = "15"
name = "star's player → fether"
title = "honey cookie"
size = "5 KB"
addr = ["http://www.kcnet.ne.jp/~hyuri/f-6th/bms_index.html"]
genre = "pop"
impr = "4"
total = "4"
avg = "1"
update = "2002/12/29 16:54"

[[entries]]
no = "16"
name = "低容量職人"
title = "Byte668"
size = "1 KB"
addr = ["http://sound.jp/ptf/b668.rar"]
genre = "minimal"
impr = "3"
total = "3"
avg = "1"
update = "2002/12/25 18:44"

[[entries]]
no = "17"
name = "rio"
title = "P5"
size = "4 KB"
addr = ["http://www.pureweb.jp/~fruit/p5.rar"]
genre = "techno"
impr = "2"
total = "2"
avg = "1"
update = "2002/12/24 23:20"

[[entries]]
no = "18"
name = "肉じゃが"
title = "G"
size = "4 KB"
addr = ["http://www.h5.dion.ne.jp/~nikujaga/G.cab"]
genre = "minimal"
impr = "2"
total = "2"
avg = "1"
update = "2002/12/24 23:09"
