[[entries]]
no = "1"
name = "CRUNCH"
title = "TRILL"
size = "31 KB"
addr = ["http://uploader.bms.ms/data/minikebi/trill.rar"]
genre = "TRIBAL"
impr = "21"
total = "21"
avg = "1"
regist = "2011/05/21 00:00"
update = "2011/06/06 00:54"

[[entries]]
no = "2"
name = "momoyama"
title = "Late bat!"
size = "31 KB"
addr = ["http://www.geocities.jp/pink_no_cool/BMS/lb.html"]
genre = "happy"
impr = "19"
total = "19"
avg = "1"
regist = "2011/05/21 00:01"
update = "2011/06/11 19:56"

[[entries]]
no = "3"
name = "scytheleg"
title = "HITS"
size = "31 KB"
addr = ["http://scytheleg.bms.ms/tempyou/music/bms/hits/stl_hits.rar"]
genre = "CORE"
impr = "19"
total = "19"
avg = "1"
regist = "2011/05/21 00:01"
update = "2011/06/06 00:10"

[[entries]]
no = "5"
name = "loca"
title = "Fire Gay"
size = "32 KB"
addr = [
    "http://page.freett.com/locabms/loca_MinimaL.rar",
    "(右クリック⇒対象をファイルに保存でお願いします。)",
]
genre = "(M)inimaL"
impr = "20"
total = "20"
avg = "1"
regist = "2011/05/21 00:01"
update = "2011/06/07 18:05"

[[entries]]
no = "6"
name = "kireji"
title = "Dobbel kaffe"
size = "32 KB"
addr = ["http://bounge.sakura.ne.jp/32kb/kireji_dk.cab"]
genre = "UK HARDCORE"
impr = "22"
total = "22"
avg = "1"
regist = "2011/05/21 00:01"
update = "2011/06/06 00:24"

[[entries]]
no = "7"
name = "FALL"
title = "QNPM"
size = "32 KB"
addr = ["http://www.likeside.net/files/bms/qnpm.zip"]
genre = "TECHNO POP"
impr = "23"
total = "23"
avg = "1"
regist = "2011/05/21 00:02"
update = "2011/06/05 23:59"

[[entries]]
no = "8"
name = "bbangsami"
title = "Mystical Dejavu - 32kb edition -"
size = "31 KB"
addr = [
    "http://dl.dropbox.com/u/26382926/bbangsami_mystical_dejavu_32kb.rar",
    "http://bbcworld.zc.bz/bsi_bms/dl_mirror.htm",
]
genre = "Ambient"
impr = "20"
total = "20"
avg = "1"
regist = "2011/05/21 00:10"
update = "2011/06/05 23:58"

[[entries]]
no = "9"
name = "bug-light"
title = "bigbug"
size = "28 KB"
addr = ["http://www.geocities.jp/buganderror/event/minikb.html"]
genre = "TECHNO"
impr = "14"
total = "14"
avg = "1"
regist = "2011/05/21 00:13"
update = "2011/06/06 00:35"

[[entries]]
no = "10"
name = "M-kani"
title = "mk32"
size = "30 KB"
addr = ["http://uploader.bms.ms/data/mkani/mk32.zip"]
genre = "techno"
impr = "14"
total = "14"
avg = "1"
regist = "2011/05/21 00:14"
update = "2011/06/06 21:32"

[[entries]]
no = "11"
name = "dj Extrose"
title = "なぜ32KBdownしたﾎﾜｱｱｲ？！"
size = "29 KB"
addr = ["http://stoicsounds.matrix.jp/x.zip"]
genre = "Techno"
impr = "14"
total = "14"
avg = "1"
regist = "2011/05/21 00:51"
update = "2011/06/05 23:52"

[[entries]]
no = "12"
name = "ABE32kb"
title = "Dreaming Android"
size = "32 KB"
addr = ["http://abeyuta.ikaduchi.com/"]
genre = "LO-FI TECH."
impr = "20"
total = "20"
avg = "1"
regist = "2011/05/21 01:34"
update = "2011/06/17 09:54"

[[entries]]
no = "13"
name = "dj Extrose"
title = "ジャンルに誤字は無かった、あったのは32KB is my うぃふぇ"
size = "22 KB"
addr = ["http://stoicsounds.matrix.jp/z.zip"]
genre = "Tencho"
impr = "14"
total = "14"
avg = "1"
regist = "2011/05/21 01:41"
update = "2011/06/05 23:54"

[[entries]]
no = "14"
name = "SAUSU"
title = "フリーダムすぎる↑DiVE↓"
size = "31 KB"
addr = ["http://ux.getuploader.com/sausu/download/4/freedomsugidive.zip"]
genre = "はぴこあ？"
impr = "18"
total = "18"
avg = "1"
regist = "2011/05/21 02:12"
update = "2011/06/06 15:20"

[[entries]]
no = "15"
name = "Extroove"
title = "6000000000000"
size = "20 KB"
addr = ["http://stoicsounds.matrix.jp/n.zip"]
genre = "8bit"
impr = "18"
total = "18"
avg = "1"
regist = "2011/05/21 02:48"
update = "2011/06/05 23:30"

[[entries]]
no = "16"
name = "T.Minico"
title = "ネグリジェンス・オブ・ヴェンジェンス"
size = "29 KB"
addr = [
    "[ogg低音質]",
    "http://3t1a.web.fc2.com/negligence_of_vengeance_ogg.cab",
    "圧縮形式cabを使用しています。対応する解凍ソフトをご使用ください。",
    "イベント終了後に高音質版を公開予定です。",
]
genre = "TECHNO"
impr = "16"
total = "16"
avg = "1"
regist = "2011/05/21 02:59"
update = "2011/06/06 00:05"

[[entries]]
no = "17"
name = "mommy"
title = "Poisonous Peach"
size = "31 KB"
addr = ["http://mommy16807.up.seesaa.net/image/pp.cab"]
genre = "ピポピポJAZZ"
impr = "28"
total = "28"
avg = "1"
regist = "2011/05/21 09:17"
update = "2011/06/06 02:36"

[[entries]]
no = "18"
name = "Lasque"
title = "32maL"
size = "32 KB"
addr = [
    "http://www1.axfc.net/uploader/Sc/so/236176",
    "http://uploader.bms.ms/data/32maL.zip",
]
genre = "MINIMAL"
impr = "19"
total = "19"
avg = "1"
regist = "2011/05/21 11:47"
update = "2011/06/06 00:45"

[[entries]]
no = "19"
name = "fmrl"
title = "crate"
size = "26 KB"
addr = ["http://uploader.bms.ms/data/minikebi/fmcr.rar"]
genre = "house"
impr = "19"
total = "19"
avg = "1"
regist = "2011/05/21 14:45"
update = "2011/06/10 22:24"

[[entries]]
no = "20"
name = "wav系男子 star ＾o＾┓)┫┛┳┏┣(┏ -DYOOON-"
title = "音質には奥手だがその分容量を節約してしまう「あぇお？」系男子-TW"
size = "29 KB"
addr = ["http://stoicsounds.matrix.jp/c.zip"]
genre = "(・x・`)tek"
impr = "16"
total = "16"
avg = "1"
regist = "2011/05/21 16:31"
update = "2011/06/05 23:54"

[[entries]]
no = "21"
name = "くっちー"
title = "U.N.オーエンは彼女なのか？(8bit mix)"
size = "20 KB"
addr = ["http://page.freett.com/ykyk00/"]
genre = "CHIPTUNE"
impr = "20"
total = "20"
avg = "1"
regist = "2011/05/21 17:38"
update = "2011/06/05 23:56"

[[entries]]
no = "22"
name = "FIFTY STAR ※-KOME-"
title = "You'll say!"
size = "31 KB"
addr = ["http://nekokan.dyndns.info/~anonymous/Youll_say.cab"]
genre = "ONLY ONE PEACE"
impr = "15"
total = "15"
avg = "1"
regist = "2011/05/21 17:39"
update = "2011/06/05 23:51"

[[entries]]
no = "23"
name = "Nitrix"
title = "WOW!"
size = "32 KB"
addr = [
    "http://big.freett.com/nitrix/ntr_wow.cab",
    "(32265byte)",
    "(右クリック⇒対象をファイルに保存でお願いします。)",
]
genre = "BOOTY HOUSE"
impr = "20"
total = "20"
avg = "1"
regist = "2011/05/21 17:59"
update = "2011/06/05 23:56"

[[entries]]
no = "24"
name = "Saldy"
title = "k"
size = "11 KB"
addr = [
    "http://uploader.bms.ms/data/minikebi/Saldy_i.zip",
    "(臨時)",
    "http://saldy.client.jp/saldy_i.html",
]
genre = "techno"
impr = "14"
total = "14"
avg = "1"
regist = "2011/05/21 18:21"
update = "2011/06/05 23:46"

[[entries]]
no = "25"
name = "K2Drum Set"
title = "Drum Simulator 3"
size = "32 KB"
addr = [
    "http://tmalrns2721.tistory.com/attachment/cfile4.uf",
    "@124FA7504DD7805F0FB098.rar",
]
genre = "simulated"
impr = "18"
total = "18"
avg = "1"
regist = "2011/05/21 18:23"
update = "2011/06/06 00:16"

[[entries]]
no = "26"
name = "Bit Upper"
title = "MiniTech!"
size = "32 KB"
addr = ["http://uprdeco.littlestar.jp/minitech_spogg.cab"]
genre = "HARDSTYLE"
impr = "17"
total = "17"
avg = "1"
regist = "2011/05/21 22:34"
update = "2011/06/06 00:11"

[[entries]]
no = "27"
name = "w_tre"
title = "Chillfoon"
size = "32 KB"
addr = ["http://cfile217.uf.daum.net/attach/166C744E4DEA08B60250F4"]
genre = "MINI MIDI"
impr = "16"
total = "16"
avg = "1"
regist = "2011/05/21 22:49"
update = "2011/06/05 23:39"

[[entries]]
no = "28"
name = "The Bottom"
title = "Animals-Animals"
size = "30 KB"
addr = ["http://dl.dropbox.com/u/29933226/Animals.cab"]
genre = "Animals noise"
impr = "17"
total = "17"
avg = "1"
regist = "2011/05/21 22:56"
update = "2012/09/24 00:37"

[[entries]]
no = "29"
name = "Gothlia"
title = "Dot Doll"
size = "30 KB"
addr = ["http://www.geocities.jp/gothlia/ddlq2.zip"]
genre = "Noise"
impr = "15"
total = "15"
avg = "1"
regist = "2011/05/21 23:02"
update = "2011/06/05 23:38"

[[entries]]
no = "30"
name = "omusubi"
title = "orz"
size = "32 KB"
addr = ["http://uploader.bms.ms/data/minikebi/omu_orz.zip"]
genre = "trance"
impr = "16"
total = "16"
avg = "1"
regist = "2011/05/21 23:25"
update = "2011/06/05 23:56"

[[entries]]
no = "31"
name = "Ym32"
title = "Minimalized Material"
size = "32 KB"
addr = ["http://yellowmapleleaf.com/bms/ym30_minim_32kb.rar"]
genre = "Click House"
impr = "21"
total = "21"
avg = "1"
regist = "2011/05/22 03:09"
update = "2011/06/06 19:44"

[[entries]]
no = "32"
name = "xarva"
title = "MT"
size = "32 KB"
addr = ["http://phantomscape.in/music/bms/MT_lq.cab"]
genre = "-"
impr = "20"
total = "20"
avg = "1"
regist = "2011/05/22 07:49"
update = "2011/06/05 23:54"

[[entries]]
no = "33"
name = "130"
title = "sketch"
size = "31 KB"
addr = ["http://uploader.bms.ms/data/130/130bms_no30.zip"]
genre = "JUMPSTYLE"
impr = "17"
total = "17"
avg = "1"
regist = "2011/05/22 09:35"
update = "2011/06/05 23:55"

[[entries]]
no = "34"
name = "ねこみみ魔法使い"
title = "彼女の言い分 -ﾋﾟｺﾋﾟｺedit-"
size = "25 KB"
addr = ["http://nekomimi.name/"]
genre = "chiptune"
impr = "24"
total = "24"
avg = "1"
regist = "2011/05/22 21:29"
update = "2011/06/06 07:27"

[[entries]]
no = "35"
name = "omusubi"
title = "カスガ"
size = "32 KB"
addr = ["http://www.megaupload.com/?d=IW3NCFOV"]
genre = "dance"
impr = "16"
total = "16"
avg = "1"
regist = "2011/05/22 22:20"
update = "2011/06/05 23:59"

[[entries]]
no = "36"
name = "dj Extrose from dj p_server"
title = "drummagic Quickable B"
size = "21 KB"
addr = ["http://stoicsounds.matrix.jp/drummagicquickableb.zip"]
genre = "Percassive Respect"
impr = "15"
total = "15"
avg = "1"
regist = "2011/05/22 23:01"
update = "2011/06/05 23:49"

[[entries]]
no = "37"
name = "サクッと香ばしいココアビスケット"
title = "サイカのﾊﾞｶﾔﾛｳ"
size = "28 KB"
addr = ["http://www1.axfc.net/uploader/Sc/so/236829"]
genre = "SAIKA"
impr = "18"
total = "18"
avg = "1"
regist = "2011/05/22 23:34"
update = "2011/06/05 23:53"

[[entries]]
no = "38"
name = "桜井あさり"
title = "METRO BOY"
size = "25 KB"
addr = ["http://roaraddiction.mods.jp/bms/x102_mb.rar"]
genre = "FIDGET HOUSE"
impr = "17"
total = "17"
avg = "1"
regist = "2011/05/22 23:56"
update = "2011/06/05 23:46"
