[[entries]]
no = "1"
name = "Arranged by Y.W"
team = "2011ばん どうろ"
title = "My favorite shoes"
size = "6532 KB"
addr = [
    "http://www.yw-works.com/data/bm/shoes_ogg.zip",
    "(HQ OGG)",
]
genre = "HAPPY SYMPHONY"
impr = "9"
total = "9"
avg = "1"
regist = "2011/07/30 00:02"
update = "2011/08/31 13:18"

[[entries]]
no = "2"
name = "BMP"
team = "Be-Music Phase"
title = "Be-Music Primary"
size = "58894 KB"
addr = [
    "http://199.91.152.149/p9tm1g97syog/48b6zsy6m01c64q/eFeL+-+Be-Music+Primary.zip",
    "http://minus.com/lKk6rhqq3NHiM",
    "[Mirror]",
]
genre = "House"
impr = "12"
total = "12"
avg = "1"
regist = "2011/07/30 00:04"
update = "2011/10/02 23:03"

[[entries]]
no = "3"
name = "TiS vs azu"
team = "SHOOT IN GROOVE"
title = "G vs D"
size = "4790 KB"
addr = ["http://pf-records.appspot.com/music/SIG_MED.mp3"]
genre = "STG MEDLAY"
impr = "5"
total = "5"
avg = "1"
regist = "2011/07/30 00:04"
update = "2011/08/31 13:19"

[[entries]]
no = "4"
name = "痛男次郎"
team = "木工野郎Iチーム"
title = "eternal force blizzard"
size = "2350 KB"
addr = ["http://uploader.bms.ms/data/bof2011pr/eternal%20force%20blizzard.mp3"]
genre = "hardcore"
impr = "1"
total = "1"
avg = "1"
regist = "2011/07/30 20:55"
update = "2011/08/31 13:19"

[[entries]]
no = "5"
name = "daiki"
team = "TEAM HARDCORE (仮)"
title = "L'AUTOMNE"
size = "16179 KB"
addr = ["http://uploader.bms.ms/data/bof2011pr/l%27automne_ogg.zip"]
genre = "HAPPY HARDCORE"
impr = "3"
total = "3"
avg = "1"
regist = "2011/07/30 23:33"
update = "2011/08/31 13:19"

[[entries]]
no = "6"
name = "LeaF"
team = "自由落下症候群"
title = "Sunny Side Up"
size = "39262 KB"
addr = ["http://uploader.bms.ms/data/bof2011pr/Sunny%20Side%20Up.zip"]
genre = "Happy Contemporary"
impr = "4"
total = "4"
avg = "1"
regist = "2011/07/31 00:32"
update = "2011/08/31 13:21"

[[entries]]
no = "7"
name = "TRANCE TANCE from OMR"
team = "Only My Revolution 2011"
title = "GO REWRITE"
size = "16196 KB"
addr = ["http://nekokan.dyndns.info/~anonymous/bof2011/omr/go_rewrite_step.zip"]
genre = "Stepmania"
impr = "2"
total = "2"
avg = "1"
regist = "2011/07/31 01:13"
update = "2011/08/31 13:21"

[[entries]]
no = "8"
name = "Iridium. Vanessa"
team = "illusion beat"
title = "Rapidity (Radio Edit)"
size = "10892 KB"
addr = ["http://uploader.bms.ms/data/bof2011pr/Rapidity%20%28Radio%20Edit%29.rar"]
genre = "Psychedellic Trance"
impr = "6"
total = "6"
avg = "1"
regist = "2011/08/02 00:15"
update = "2011/08/31 19:53"

[[entries]]
no = "9"
name = "bbangsami"
team = "Music Bakery"
title = "Black Flag"
size = "44960 KB"
addr = ["http://dl.dropbox.com/u/34178538/bbangsami_smin_cinic_Black_flag.rar"]
genre = "Detroit Techno"
impr = "4"
total = "4"
avg = "1"
regist = "2011/08/02 19:00"
update = "2011/08/31 13:22"

[[entries]]
no = "10"
name = "w_tre / Mer"
team = "TMG Association"
title = "The Lamia 170"
size = "35802 KB"
addr = ["http://uploader.bms.ms/data/bof2011pr/lamia170.zip"]
genre = "Piano Progressive Metal"
impr = "6"
total = "6"
avg = "1"
regist = "2011/08/03 18:49"
update = "2011/09/01 12:44"

[[entries]]
no = "11"
name = "dj VAKA"
team = "東方スカイタートル試作β・出張版"
title = "Cherrypetal in her mind"
size = "1 KB"
addr = ["http://tmbox.net/pl/4474"]
genre = "thin style"
impr = "2"
total = "2"
avg = "1"
regist = "2011/08/08 14:46"
update = "2011/08/31 13:23"

[[entries]]
no = "12"
name = "ω"
team = "DWMω"
title = "Lasting Dream"
size = "50794 KB"
addr = ["http://uploader.bms.ms/data/bof2011pr/%5BDWMomega%5Dlastingdream.rar"]
genre = "PRELUDE"
impr = "5"
total = "5"
avg = "1"
regist = "2011/08/09 18:09"
update = "2011/09/03 06:37"

[[entries]]
no = "13"
name = "t-soach"
team = "Qpic Sound Complex side R"
title = "sprinkling"
size = "575 KB"
addr = ["http://uploader.bms.ms/data/bof2011pr/sprinkling.zip"]
genre = "MINIMALlike"
impr = "3"
total = "3"
avg = "1"
regist = "2011/08/10 12:30"
update = "2011/08/31 13:24"

[[entries]]
no = "14"
name = "SHANG0"
team = "カオスオレンジ"
title = "Surging Citrus"
size = "10127 KB"
addr = ["http://uploader.bms.ms/data/bof2011pr/Surging%20Citrus%28%E4%BF%AE%E6%AD%A3%29.rar"]
genre = "HAPPY HARDCORE"
impr = "6"
total = "6"
avg = "1"
regist = "2011/08/12 20:15"
update = "2011/08/31 13:25"

[[entries]]
no = "15"
name = "cromo"
team = "Qpic Sound Complex Side-L"
title = "kururi,hirari"
size = "12800 KB"
addr = ["http://dl.dropbox.com/u/30230629/kururi%2Chirari%28fixed%29%5Bogg%5D.zip"]
genre = "りとるすてっぷ"
impr = "3"
total = "3"
avg = "1"
regist = "2011/08/18 12:10"
update = "2011/08/31 19:44"

[[entries]]
no = "16"
name = "Red Savarin"
team = "TEAM SLTRB"
title = "Vol de la nuit"
size = "16700 KB"
addr = ["http://dl.dropbox.com/u/16367925/Vol%20de%20la%20nuit.rar"]
genre = "Nu Disco"
impr = "3"
total = "3"
avg = "1"
regist = "2011/08/20 00:17"
update = "2011/09/20 22:16"

[[entries]]
no = "17"
name = "ueo"
team = "全部長い"
title = "Rebirth Castle"
size = "49200 KB"
addr = [
    "http://www.youtube.com/watch?v=0UGrvuuKy38&hd=1",
    "(HD画質)",
]
genre = "Nu Castle"
impr = "2"
total = "2"
avg = "1"
regist = "2011/08/20 12:32"
update = "2011/08/31 13:25"

[[entries]]
no = "18"
name = "DJ Saw-Low"
team = "大都会岡山連邦 -岡山side-"
title = "完全燃焼ボッケエガス(EURO MIX)"
size = "5223 KB"
addr = [
    "http://scytheleg.bms.ms/tempyou/music/bms/bokkeegas/bokkeegas_ogg.rar",
    "(ogg音声/5,223KB)",
    "http://scytheleg.bms.ms/tempyou/music/bms/bokkeegas/bokkeegas_png.rar",
    "(BGA/11,256KB)←動画投稿などに使用しないで下さい",
]
genre = "J-EUROBEAT"
impr = "4"
total = "4"
avg = "1"
regist = "2011/08/21 00:49"
update = "2011/08/31 23:59"

[[entries]]
no = "19"
name = "デスティニーサーモン"
team = "デスティニーサーモン"
title = "デスティニーサーモン"
size = "15400 KB"
addr = [
    "http://klamnop.info/destiny/Game_DestinySalmon.zip",
    "(ゲーム)",
    "http://klamnop.info/destiny/",
    "(公式サイト)",
]
genre = "シューティングゲーム"
impr = "11"
total = "11"
avg = "1"
regist = "2011/08/21 21:43"
update = "2011/08/31 21:07"

[[entries]]
no = "20"
name = "DG-PとH.U.T GiGARとtaqumi"
team = "RichRacer"
title = "Rotterdam RacerとPARTY SEX CRAZY NIGHT"
size = "7010 KB"
addr = ["http://dg-life.net/iroiro/richracer.mp3"]
genre = "Drive Music"
impr = "1"
total = "1"
avg = "1"
regist = "2011/08/24 19:25"
update = "2011/08/31 13:34"

[[entries]]
no = "21"
name = "Ruby.G / remixed by subomi"
team = "Psychic urchins Lab"
title = "Practice Series (subomi remix)"
size = "9051 KB"
addr = ["http://uploader.bms.ms/data/PW/subomi_prrm.zip"]
genre = "Chip / Electro"
impr = "3"
total = "3"
avg = "1"
regist = "2011/08/26 03:03"
update = "2011/08/31 19:27"

[[entries]]
no = "22"
name = "川島みなみ"
team = "もし高校野球の女子マネージャーがBOFに出たら"
title = "Dusk"
size = "2280 KB"
addr = ["http://72mo471.web.fc2.com/dusk.rar"]
genre = "AMBIENT"
impr = "3"
total = "3"
avg = "1"
regist = "2011/08/27 21:45"
update = "2011/08/31 19:38"

[[entries]]
no = "23"
name = "DTM経験とか関係なしにBMS作成するチーム(BMS,SP譜面:Telno&fkRadish BGA:(i) a.k.a HaL DP譜面:dist)"
team = "DTM経験とか関係なしにBMS作成するチーム"
title = "Temptation"
size = "14506 KB"
addr = [
    "http://uploader.bms.ms/data/bof2011pr/temp_ogg.zip",
    "http://nekokan.dyndns.info/~anonymous/bms/fuki1755/temp_ogg.zip",
    "↑ミラー兼りどみ同梱版(今更…)",
]
genre = "Drum'n'Bass"
impr = "2"
total = "2"
avg = "1"
regist = "2011/08/29 02:57"
update = "2011/10/19 19:00"

[[entries]]
no = "24"
name = "妖精大合奏"
team = "妖精大合奏"
title = "FREEZING MY HEART"
size = "11220 KB"
addr = ["http://cineraria-studio.com/bms/freezingmyheart.zip"]
genre = "EURO BEAT"
impr = "4"
total = "4"
median = "0"
avg = "1"
regist = "2011/08/30 22:23"
update = "2015/02/21 23:51"

[[entries]]
no = "25"
name = "MoonHare"
team = "Moon Culture"
title = "Moon Strength"
size = "0 KB"
addr = ["http://www.youtube.com/watch?v=HBEfx6smrAM"]
genre = "PR"
impr = "2"
total = "2"
avg = "1"
regist = "2011/08/31 00:50"
update = "2011/08/31 19:28"

[[entries]]
no = "26"
name = "SANY-ON"
team = "The Orient ~ リベンジ (仮)"
title = "HARDCORE MOKOTAN (bms edit)"
size = "66867 KB"
addr = [
    "https://www.dropbox.com/s/rxzo8lfvfiksp65/sany_on_hardcore_mokotan.zip",
    "[dropbox]",
    "http://www1.axfc.net/uploader/so/2898679.zip",
    "[axfc]",
]
genre = "HARDCORE"
impr = "2"
total = "2"
avg = "1"
regist = "2011/08/31 05:45"
update = "2013/05/11 16:10"

[[entries]]
no = "27"
name = "パンダ４２号、１８号、７７号"
team = "NORMAL PANDARS"
title = "Pandars crossfade demo"
size = "8250 KB"
addr = ["http://soundcloud.com/normal-pandars/pandars-crossfade"]
genre = "TECHNO"
impr = "1"
total = "1"
avg = "1"
regist = "2011/08/31 18:48"
update = "2011/09/03 06:18"
