[[entries]]
no = "1"
name = "ETIA."
title = "HARDCORE MACHINEGUN"
size = "30000 KB"
addr = [
    "ogg",
    "http://uploader.bms.ms/data/hardcoremachinegun/etia_hardcore_machinegun_ogg.zip",
    "ミラー",
    "http://www1.axfc.net/uploader/C/so/154772&key=ultraextremefever",
]
genre = "SPEEDCORE"
impr = "37"
total = "30"
avg = "0.81"
regist = "2011/12/01 00:01"
update = "2011/12/17 23:29"

[[entries]]
no = "2"
name = "Krystal (taqumi)"
title = "CRYSTAL DICE"
size = "0 KB"
addr = ["http://music-side.com/bms/CrystalDice.zip"]
genre = "CRYSTAL FUSION"
impr = "28"
total = "12"
avg = "0.42"
regist = "2011/12/01 00:02"
update = "2011/12/17 23:30"

[[entries]]
no = "3"
name = "bug-lice"
title = "CIERAHMMY"
size = "454 KB"
addr = ["http://www.geocities.jp/buganderror/event/uxt.html"]
genre = "Anoplura"
impr = "29"
total = "15"
avg = "0.51"
regist = "2011/12/01 00:02"
update = "2011/12/18 00:52"

[[entries]]
no = "4"
name = "MathFabric"
title = "No Tears"
size = "11399 KB"
addr = ["http://www1.axfc.net/uploader/Li/so/115466.zip&key=mf4"]
genre = "SADNESS SPEEDCORE"
impr = "27"
total = "16"
avg = "0.59"
regist = "2011/12/01 23:28"
update = "2012/01/15 19:37"

[[entries]]
no = "5"
name = "LeaF"
title = "Eternal Liberty"
size = "19806 KB"
addr = ["http://www1.axfc.net/uploader/N/so/141826"]
genre = "Progressive"
impr = "25"
total = "12"
avg = "0.48"
regist = "2011/12/02 21:16"
update = "2011/12/17 23:42"

[[entries]]
no = "6"
name = "scytheleg"
title = "Largest Mighty Power"
size = "16574 KB"
addr = [
    "http://dl.dropbox.com/u/35847410/stl_lmp.rar",
    "http://dl.dropbox.com/u/35847410/stl_lmp_fix.rar",
    "(譜面修正版 12/11 14:07以前にダウンロードした方は上書きして下さい)",
]
genre = "Ska Core"
impr = "27"
total = "25"
avg = "0.92"
regist = "2011/12/03 04:32"
update = "2011/12/18 01:18"

[[entries]]
no = "7"
name = "bread buyer a.k.a bbangsami"
title = "White Flag"
size = "27977 KB"
addr = ["http://dl.dropbox.com/u/23821865/breadbuyer_aka_bbangsami_white_flag.rar"]
genre = "Speed Kore"
impr = "27"
total = "17"
avg = "0.62"
regist = "2011/12/03 20:27"
update = "2011/12/17 23:58"

[[entries]]
no = "8"
name = "takdrive"
title = "デジョン"
size = "26030 KB"
addr = [
    "(とりあえずbms.ms鯖繋がらないので↓に上げておきます。)",
    "[ミラー用]",
    "http://www1.axfc.net/uploader/Si/so/126772&key=ultraextreambeat",
]
genre = "Power Electronics"
impr = "30"
total = "25"
avg = "0.83"
regist = "2011/12/04 18:54"
update = "2011/12/17 23:58"

[[entries]]
no = "9"
name = "-"
title = "-"
size = "0 KB"
addr = ["-"]
genre = "-"
impr = "29"
total = "12"
avg = "0.41"
regist = "2011/12/04 19:17"
update = "2012/01/31 03:27"

[[entries]]
no = "10"
name = "GeneralC. VAK"
title = "Skies of Frustration"
size = "18000 KB"
addr = ["http://t.co/HxCPDmsI"]
genre = "ROCK"
impr = "25"
total = "6"
avg = "0.24"
regist = "2011/12/04 19:45"
update = "2011/12/17 23:46"

[[entries]]
no = "11"
name = "H.U.T SpERM"
title = "悶絶！急ハンドル射精ラッシュ！！"
size = "8569 KB"
addr = ["http://dg-life.net/bms/monzetsu_kyuuhundlesyaseirush_ogg.rar"]
genre = "EJACULATIONCORE"
impr = "29"
total = "26"
avg = "0.89"
regist = "2011/12/04 20:45"
update = "2011/12/17 23:59"

[[entries]]
no = "12"
name = "Kei Izumi(yellow program)"
title = "Run,Curry,Run"
size = "17586 KB"
addr = ["http://prsq.sakura.ne.jp/data/ethnicspeed_bms.zip"]
genre = "ETHNIC SPEED"
impr = "27"
total = "26"
avg = "0.96"
regist = "2011/12/04 21:11"
update = "2012/02/25 02:05"

[[entries]]
no = "13"
name = "Yohoi Sou"
title = "Bar-Master's Everyday"
size = "7102 KB"
addr = ["http://nekokan.dyndns.info/~anonymous/bms/Yohoi_Sou/barmaster_ogg.zip"]
genre = "Jazz Waltz"
impr = "24"
total = "11"
avg = "0.45"
regist = "2011/12/04 21:32"
update = "2011/12/17 23:52"

[[entries]]
no = "14"
name = "sd5y"
title = "What's Limit?? Pt.2"
size = "16001 KB"
addr = [
    "http://sound.jp/ft718/ft718music.html",
    "（サーバーの規約でファイル直リンクが出来ませんので、誠に恐れ入りますが、リンク先からDLして下さい）",
    "予備：",
    "http://www.mediafire.com/?0dhdz2z7yn8e7ld",
]
genre = "Speedcore"
impr = "38"
total = "36"
avg = "0.94"
regist = "2011/12/04 23:08"
update = "2011/12/18 03:24"

[[entries]]
no = "15"
name = "スプリ"
title = "dimension mops"
size = "341 KB"
addr = ["http://uprdeco.littlestar.jp/dm-mops_ogg.rar"]
genre = "ENGINE STALL CORE"
impr = "28"
total = "9"
avg = "0.32"
regist = "2011/12/04 23:42"
update = "2011/12/18 00:57"

[[entries]]
no = "16"
name = "TiS underground"
title = "XROSS DIMENSION"
size = "18432 KB"
addr = [
    "ogg版：",
    "http://uploader.bms.ms/data/tis_xross_dimension.zip",
    "miller：",
    "http://www1.axfc.net/uploader/N/so/141998",
]
genre = "GENESIC HARDCORE"
impr = "33"
total = "14"
avg = "0.42"
regist = "2011/12/04 23:43"
update = "2011/12/17 23:58"

[[entries]]
no = "17"
name = "ARMAGEDDON SOUND SQUAD"
title = "FIGHT TO NIGHT"
size = "25028 KB"
addr = [
    "[Original]",
    "http://www1.axfc.net/uploader/Si/so/126815",
    "[bug差分]",
    "http://www.geocities.jp/buganderror/appevent/uxb_ez/bug-fighttonight-ass.zip",
]
genre = "NINTENDOCORE OVERTURE"
impr = "24"
total = "8"
avg = "0.33"
regist = "2011/12/04 23:57"
update = "2011/12/18 14:38"

[[entries]]
no = "18"
name = "403 ERROR ( xi vs ZUMMER )"
title = "FORBIDDEN"
size = "38000 KB"
addr = ["http://tinyurl.com/7yr9hjw"]
genre = "ANTHEM SPEEDCORE"
impr = "40"
total = "29"
avg = "0.72"
regist = "2011/12/04 23:58"
update = "2011/12/18 23:07"

[[entries]]
no = "19"
name = "Blue-J (mov:jueL)"
title = "Out of Recess"
size = "17500 KB"
addr = ["http://dl.dropbox.com/u/51977836/out_of_recess.rar"]
genre = "Hardcore Fusion"
impr = "27"
total = "4"
avg = "0.14"
regist = "2011/12/04 23:59"
update = "2011/12/17 23:58"
