[[entries]]
no = "1"
name = "落雁"
title = "upas as uske"
size = "3246 KB"
addr = ["http://dl.dropbox.com/u/52909188/LUCK7_usu.zip"]
genre = "imaginary world"
impr = "29"
total = "6"
avg = "0.2"
regist = "2012/01/27 00:01"
update = "2012/02/19 23:57"

[[entries]]
no = "2"
name = "taqumi"
title = "Calling"
size = "0 KB"
addr = ["http://music-side.com/bms/calling.zip"]
genre = "HOUSE"
impr = "38"
total = "33"
avg = "0.86"
regist = "2012/01/27 00:03"
update = "2012/02/19 23:56"

[[entries]]
no = "3"
name = "Kanata.S"
title = "終わらない物語とコープスドール"
size = "5000 KB"
addr = ["http://www.mediafire.com/download.php?y9ho87s9vus3b9y"]
genre = "DUB AMBIENT"
impr = "29"
total = "22"
avg = "0.75"
regist = "2012/01/27 00:04"
update = "2012/02/19 23:56"

[[entries]]
no = "4"
name = "kinohito"
title = "YUGAMINAI LOVE"
size = "22847 KB"
addr = [
    "http://dl.dropbox.com/u/45247999/ygmny.zip",
    "7KEY MEDIUM,5KEY LIGHT差分作りました！",
    "2/5以前にＤＬした方はこちらから落としてください。→",
    "http://dl.dropbox.com/u/45247999/ygmny_sabun.zip",
]
genre = "HONKAKUTEKI HIP HOP"
impr = "50"
total = "48"
avg = "0.96"
regist = "2012/01/27 00:06"
update = "2012/02/20 00:13"

[[entries]]
no = "5"
name = "Nine tales (fkRadish)"
title = "repeated lie"
size = "20024 KB"
addr = [
    "http://uploader.bms.ms/data/Ninetales_rl.zip",
    "http://www1.axfc.net/uploader/N/so/145923.zip",
]
genre = "Human habit"
impr = "26"
total = "16"
avg = "0.61"
regist = "2012/01/27 00:09"
update = "2012/02/20 00:03"

[[entries]]
no = "6"
name = "LuL (Est)"
title = "wintry wind"
size = "13914 KB"
addr = ["https://dl.dropbox.com/u/38773828/bms/est104_wintry_wind.zip"]
genre = "CHILL OUT / PROG"
impr = "38"
total = "34"
avg = "0.89"
regist = "2012/01/27 00:18"
update = "2012/06/23 22:22"

[[entries]]
no = "7"
name = "sugisaki"
title = "Secret Rule"
size = "20125 KB"
addr = ["http://nekokan.dyndns.info/~anonymous/bms/2_secret_rule.zip"]
genre = "HOUSE"
impr = "27"
total = "9"
avg = "0.33"
regist = "2012/01/27 01:09"
update = "2012/02/19 23:19"

[[entries]]
no = "8"
name = "okota"
title = "ナメクジ"
size = "11500 KB"
addr = [
    "http://uploader.bms.ms/data/emotion/okota_namekuji.zip",
    "(ミラー)",
    "http://dl.dropbox.com/u/59461144/bms/okota_namekuji.zip",
]
genre = "SLAG FUNK"
impr = "39"
total = "34"
avg = "0.87"
regist = "2012/01/27 01:14"
update = "2012/02/20 00:31"

[[entries]]
no = "9"
name = "Eidolon Squad"
title = "Snow Dirge"
size = "21688 KB"
addr = ["http://dl.dropbox.com/u/59079113/Snow_Dirge_ogg.zip"]
genre = "Ambient"
impr = "25"
total = "1"
avg = "0.04"
regist = "2012/01/27 01:28"
update = "2012/02/20 00:33"

[[entries]]
no = "10"
name = "Richard Roe"
title = "Actinoide"
size = "30072 KB"
addr = ["http://sites.google.com/site/richardroebms/actinoide"]
genre = "ABSTRACT AMBIENTECHOUSE"
impr = "40"
total = "39"
avg = "0.97"
regist = "2012/01/27 03:50"
update = "2012/02/21 18:22"

[[entries]]
no = "11"
name = "-"
title = "-"
size = "0 KB"
addr = ["http://endymium.net/bms/slpls__eclipse.zip"]
genre = "-"
impr = "6"
total = "1"
avg = "0.16"
regist = "2012/01/27 09:38"
update = "2012/02/20 00:09"

[[entries]]
no = "12"
name = "exclusion"
title = "一杯の牛丼"
size = "14568 KB"
addr = ["http://dl.dropbox.com/u/54555387/bms/lazy_beats.zip"]
genre = "lazy beats"
impr = "30"
total = "28"
avg = "0.93"
regist = "2012/01/27 10:16"
update = "2012/02/21 18:48"

[[entries]]
no = "13"
name = "空見沢佳奈"
title = "ノワール"
size = "28935 KB"
addr = [
    "http://www.mediafire.com/download.php?145wf68l5j26d2s",
    "上が重い人用",
    "http://www1.axfc.net/uploader/Si/so/131048",
]
genre = "Ballad"
impr = "26"
total = "17"
avg = "0.65"
regist = "2012/01/27 19:09"
update = "2012/02/19 23:55"

[[entries]]
no = "14"
name = "rasc"
title = "Just Say You're Not Into It"
size = "8688 KB"
addr = [
    "http://uploader.bms.ms/data/arjnr.rar",
    "http://www1.axfc.net/uploader/H/so/151695.rar",
]
genre = "Alternative Rock"
impr = "30"
total = "26"
avg = "0.86"
regist = "2012/01/27 19:47"
update = "2012/02/19 23:49"

[[entries]]
no = "15"
name = "D-suke vs Mana"
title = "Night View -snow angel-"
size = "86888 KB"
addr = ["http://oblivion.dip.jp/creation/bms/_night_view_sa.rar"]
genre = "Nocturne"
impr = "35"
total = "34"
avg = "0.97"
regist = "2012/01/27 22:09"
update = "2012/02/19 23:45"

[[entries]]
no = "16"
name = "碧"
title = "lest"
size = "45543 KB"
addr = ["http://www.mediafire.com/?1t73qfh8foba4fu"]
genre = "TENTATIVE"
impr = "31"
total = "21"
avg = "0.67"
regist = "2012/01/27 22:11"
update = "2012/02/20 01:29"

[[entries]]
no = "17"
name = "TiS"
title = "Starry Cadence"
size = "65900 KB"
addr = [
    "ogg版：",
    "http://uploader.bms.ms/data/tis_starry_cadence.zip",
    "ミラー:",
    "http://www1.axfc.net/uploader/H/so/151708.zip",
]
genre = "HIPHOP"
impr = "32"
total = "29"
avg = "0.9"
regist = "2012/01/28 01:13"
update = "2012/02/20 01:24"

[[entries]]
no = "18"
name = "Alicia*"
title = "Twilight"
size = "36000 KB"
addr = [
    "http://uploader.bms.ms/data/Alicia/Twilight_ogg.zip",
    "ミラー",
    "http://higehime.main.jp/8284/Twilight_ogg.zip",
]
genre = "AMBIENT"
impr = "44"
total = "37"
avg = "0.84"
regist = "2012/01/28 02:15"
update = "2012/02/19 23:58"

[[entries]]
no = "19"
name = "q/stol"
title = "月下時計工場跡地で貴方を待つ"
size = "12254 KB"
addr = [
    "http://uploader.bms.ms/data/qstolmonomosu/gekka_ogg_bmp.zip",
    "↑一枚絵版です。",
    "http://uploader.bms.ms/data/qstolmonomosu/gekka_movie_sabun.zip",
    "↑ムービー差分です。",
]
genre = "Schmaltz"
impr = "27"
total = "18"
avg = "0.66"
regist = "2012/01/28 02:37"
update = "2012/02/23 20:32"

[[entries]]
no = "20"
name = "Gun-SEKI"
title = "光の環"
size = "71145 KB"
addr = [
    "http://www.linnocence.net/bms/hikari_no_wa",
    "[gunseki].rar",
    "http://www.linnocence.net/bms/hikari_no_wa_h7.bme",
    "(↑2/3のAM2:20以前にDLされた方はお手数ですがこちらをDLして上書きしてください)",
]
genre = "love groove"
impr = "31"
total = "25"
avg = "0.8"
regist = "2012/01/28 06:22"
update = "2012/02/20 13:55"

[[entries]]
no = "21"
name = "SAUSU"
title = "Chronus"
size = "6250 KB"
addr = ["http://www1.axfc.net/uploader/H/so/151681"]
genre = "Chaos"
impr = "24"
total = "4"
avg = "0.16"
regist = "2012/01/28 12:30"
update = "2012/02/20 00:07"

[[entries]]
no = "22"
name = "-"
title = "-"
size = "0 KB"
addr = ["-"]
genre = "-"
impr = "28"
total = "14"
avg = "0.5"
regist = "2012/01/28 18:08"
update = "2012/02/20 22:32"

[[entries]]
no = "23"
name = "Saldy"
title = "Citron"
size = "1667 KB"
addr = ["http://nekokan.dyndns.info/~anonymous/Saldy_Citron_em.zip"]
genre = "Minimal step"
impr = "40"
total = "39"
avg = "0.97"
regist = "2012/01/28 19:28"
update = "2012/02/20 00:05"

[[entries]]
no = "24"
name = "ルゼ"
title = "tower"
size = "11700 KB"
addr = ["http://www.luzeria.net/music/63_tower_ogg.rar"]
genre = "GO UP"
impr = "35"
total = "30"
avg = "0.85"
regist = "2012/01/28 21:40"
update = "2012/02/20 01:25"

[[entries]]
no = "25"
name = "盟絵と詩乃"
title = "眼鏡の騎士と人魚姫"
size = "24361 KB"
addr = [
    "BGA同梱版",
    "http://www1.axfc.net/uploader/O/so/195522.zip",
    "BGA追加差分",
    "http://www1.axfc.net/uploader/Si/so/131154.zip",
    "BGA無し",
    "http://www1.axfc.net/uploader/Si/so/131031.zip",
]
genre = "少女セクト"
impr = "29"
total = "20"
avg = "0.68"
regist = "2012/01/28 23:54"
update = "2012/02/19 23:55"

[[entries]]
no = "26"
name = "Bit Upper"
title = "ST-MOTION"
size = "3930 KB"
addr = ["http://uprdeco.littlestar.jp/st-motion_ogg.rar"]
genre = "BIG BEAT"
impr = "25"
total = "14"
avg = "0.56"
regist = "2012/01/29 01:54"
update = "2012/02/20 00:13"

[[entries]]
no = "27"
name = "ume"
title = "I arrived"
size = "26000 KB"
addr = ["http://www42.tok2.com/home/umeboz/iarrived.zip"]
genre = "ballad"
impr = "29"
total = "25"
avg = "0.86"
regist = "2012/01/29 02:59"
update = "2012/02/20 00:15"

[[entries]]
no = "28"
name = "Richard Roe"
title = "Nargile"
size = "28335 KB"
addr = ["http://sites.google.com/site/richardroebms/nargile"]
genre = "RNB ELECTRO"
impr = "27"
total = "24"
avg = "0.88"
regist = "2012/01/29 03:46"
update = "2012/02/20 00:54"

[[entries]]
no = "29"
name = "ueotan"
title = "Lastscape"
size = "15000 KB"
addr = ["http://www1.axfc.net/uploader/N/so/145947.zip"]
genre = "ぴあのあんびえんと"
impr = "34"
total = "28"
avg = "0.82"
regist = "2012/01/29 06:08"
update = "2012/02/20 00:21"

[[entries]]
no = "30"
name = "no.5"
title = "sleeping"
size = "40200 KB"
addr = [
    "http://dl.dropbox.com/u/31391977/no5_sleeping.zip",
    "※1月30日 17:05更新",
    "http://dl.dropbox.com/u/31391977/sleepingfix.zip",
    "※5keys譜面修正+7keys譜面差分",
    "1月30日 17:05以前にダウンロードした方は、中身を上書きしていただけますと幸いです。",
]
genre = "Techno pop"
impr = "32"
total = "29"
avg = "0.9"
regist = "2012/01/29 10:07"
update = "2012/02/20 00:26"

[[entries]]
no = "31"
name = "KRi:neu"
title = "Ruined Castle"
size = "38800 KB"
addr = ["http://www1.axfc.net/uploader/Al/so/82097.zip"]
genre = "ORIENTAL AMBIENT"
impr = "24"
total = "5"
avg = "0.2"
regist = "2012/01/29 13:47"
update = "2012/02/20 00:27"

[[entries]]
no = "32"
name = "Gothlia"
title = "Groove Gravy Joint"
size = "21300 KB"
addr = ["http://dotdollgothlia.web.fc2.com/groove_gravy_joint.zip"]
genre = "Trip Hop"
impr = "25"
total = "19"
avg = "0.76"
regist = "2012/01/29 13:59"
update = "2012/02/20 00:31"

[[entries]]
no = "33"
name = "RearDawn"
title = "Feel Mixture"
size = "27329 KB"
addr = ["http://fdist.ps.land.to/bms/feelmixture.zip"]
genre = "PROGRESSIVE MIXTURE"
impr = "34"
total = "32"
avg = "0.94"
regist = "2012/01/29 15:39"
update = "2012/02/20 09:08"

[[entries]]
no = "34"
name = "NaiveDog"
title = "Act Beloved(NaiveDog Remix)"
size = "23000 KB"
addr = ["http://dl.dropbox.com/u/16367925/BMS/actbeloved_naivedog_remix.rar"]
genre = "Dubstep"
impr = "30"
total = "11"
avg = "0.36"
regist = "2012/01/29 19:13"
update = "2012/02/20 00:36"

[[entries]]
no = "35"
name = "J2"
title = "False promises"
size = "12400 KB"
addr = ["http://www1.axfc.net/uploader/Li/so/120332"]
genre = "Ambient"
impr = "23"
total = "4"
avg = "0.17"
regist = "2012/01/29 19:56"
update = "2012/02/20 16:25"

[[entries]]
no = "36"
name = "カラフル・サウンズ・ポート"
title = "Steel River"
size = "21990 KB"
addr = ["http://www1.axfc.net/uploader/Si/so/131099"]
genre = "POST ROCK"
impr = "42"
total = "41"
avg = "0.97"
regist = "2012/01/29 20:14"
update = "2012/02/20 00:42"

[[entries]]
no = "37"
name = "Ym1024 feat. lamie*"
title = "starless"
size = "11427 KB"
addr = ["http://yellowmapleleaf.com/bms/ym33_starls_ogg.rar"]
genre = "J-Pop Ballad"
impr = "47"
total = "45"
avg = "0.95"
regist = "2012/01/29 20:36"
update = "2012/02/20 01:21"

[[entries]]
no = "38"
name = "rilym"
title = "紫苑"
size = "14000 KB"
addr = ["http://fakechordunion.com/bms/sion.zip"]
genre = "J-POP/ELECTRONICA"
impr = "37"
total = "36"
avg = "0.97"
regist = "2012/01/29 21:04"
update = "2012/02/21 02:22"

[[entries]]
no = "39"
name = "Yosk!"
title = "Netzwerkgenen"
size = "10686 KB"
addr = [
    "ogg :",
    "https://drive.google.com/open?id=0B7qCw4hNijr4UjZQR0RtYm00VDg",
    "wavHQ :",
    "http://dl.dropbox.com/u/40341869/bms/Netz_HQ.zip",
]
genre = "BLAMBIENT"
impr = "24"
total = "22"
median = "1"
avg = "0.91"
regist = "2012/01/29 21:45"
update = "2018/02/14 02:35"

[[entries]]
no = "40"
name = "Tima"
title = "After 5:00a.m."
size = "7274 KB"
addr = ["http://sound.jp/tima/taf5am.html"]
genre = "ACID JAZZ"
impr = "34"
total = "29"
avg = "0.85"
regist = "2012/01/29 21:48"
update = "2012/02/20 01:49"

[[entries]]
no = "41"
name = "mommy"
title = "Derringer"
size = "17960 KB"
addr = ["http://mommy16807.up.seesaa.net/image/Derringer.rar"]
genre = "FUSION"
impr = "44"
total = "44"
avg = "1"
regist = "2012/01/29 22:18"
update = "2012/02/19 23:57"

[[entries]]
no = "42"
name = "JUMPERS"
title = "跳ばせて。"
size = "9967 KB"
addr = [
    "http://dl.dropbox.com/u/59483835/jumpers.rar",
    "http://www1.axfc.net/uploader/Li/so/120355.rar",
]
genre = "KANASIMI"
impr = "28"
total = "25"
avg = "0.89"
regist = "2012/01/29 22:24"
update = "2012/02/21 23:43"

[[entries]]
no = "43"
name = "Ark-Z"
title = "病的な私"
size = "51197 KB"
addr = [
    "http://sparrows-nest.net/~mmaki/sick2.zip",
    "（個人サーバーなもので諸事情により時々ダウンロード出来ない状態が御座います）",
    "(1/29 23:58追記)恒例の如く音量が小さかったようなので、この時間より先にダウンロードされた方は",
    "下記からoggファイルを上書きするようお願いします。お手数お掛け致します",
    "http://sparrows-nest.net/~mmaki/sick2_oggfile.zip",
]
genre = "FAILURES LOW CORE"
impr = "29"
total = "21"
avg = "0.72"
regist = "2012/01/29 22:29"
update = "2012/02/19 23:56"

[[entries]]
no = "44"
name = "Arch"
title = "Labyrinth"
size = "6286 KB"
addr = ["http://dl.dropbox.com/u/59482273/arch_laby.zip"]
genre = "TECHNO POP"
impr = "30"
total = "12"
avg = "0.4"
regist = "2012/01/29 22:49"
update = "2012/02/19 23:45"

[[entries]]
no = "45"
name = "Ritsu"
title = "StarRing"
size = "11000 KB"
addr = ["http://music.geocities.jp/txy5728/hbdepo/ritsu12_star_ogg.zip"]
genre = "shoegazer"
impr = "26"
total = "15"
avg = "0.57"
regist = "2012/01/29 23:02"
update = "2012/02/19 23:52"

[[entries]]
no = "46"
name = "James Peticidor"
title = "Endless Memory"
size = "240000 KB"
addr = [
    "Full pack Ogg",
    "http://www1.axfc.net/uploader/Si/so/131212",
    "※1/31 5:30 以前にDLされたかたは以下上書きでよろしくお願いします。",
    "http://www1.axfc.net/uploader/H/so/151841",
]
genre = "Fake Dream"
impr = "24"
total = "2"
avg = "0.08"
regist = "2012/01/29 23:08"
update = "2012/02/19 23:43"

[[entries]]
no = "47"
name = "130"
title = "arenicolousTuna"
size = "4352 KB"
addr = ["http://dl.dropbox.com/u/59462259/130bms_no47.zip"]
genre = "SKWONK"
impr = "41"
total = "32"
avg = "0.78"
regist = "2012/01/29 23:16"
update = "2012/02/19 23:47"

[[entries]]
no = "48"
name = "Nitrix"
title = "Head Banging Zombie"
size = "3994 KB"
addr = ["http://page.freett.com/nitrix/easymotion.html"]
genre = "INDUSTRIAL / TERROR CORE"
impr = "36"
total = "36"
avg = "1"
regist = "2012/01/29 23:17"
update = "2012/04/01 17:48"

[[entries]]
no = "49"
name = "Humdrumbass"
title = "Mutatie"
size = "14044 KB"
addr = ["http://dl.dropbox.com/u/20077825/BMS/humdrumbass_mutatie.rar"]
genre = "IDM"
impr = "19"
total = "7"
avg = "0.36"
regist = "2012/01/29 23:18"
update = "2012/02/19 23:59"

[[entries]]
no = "50"
name = "xarva"
title = "easymotion"
size = "7476 KB"
addr = ["http://liz.nothing.sh/xrv/easymotion.zip"]
genre = "-"
impr = "66"
total = "66"
avg = "1"
regist = "2012/01/29 23:51"
update = "2012/02/19 23:59"

[[entries]]
no = "51"
name = "Ziken Akahane"
title = "high-school girl(we loved) (Remix)"
size = "6339 KB"
addr = [
    "http://dl.dropbox.com/u/36133429/7-high_school_girl_remix-ziken_akahene.rar",
    "(7鍵同梱)",
    "http://dl.dropbox.com/u/36133429/8-high_school_girl_remix-ziken_akahene-7.rar",
    "(7鍵差分)",
]
genre = "TRIP HOP"
impr = "25"
total = "16"
avg = "0.64"
regist = "2012/01/29 23:54"
update = "2012/08/26 00:38"

[[entries]]
no = "52"
name = "Ωμεγα"
title = "gracial rain"
size = "24400 KB"
addr = ["http://0meganet2.xxxxxxxx.jp/bms.html"]
genre = "POST BALLAD"
impr = "26"
total = "10"
avg = "0.38"
regist = "2012/01/29 23:55"
update = "2013/02/23 03:43"

[[entries]]
no = "53"
name = "Mer"
title = "Longfellow"
size = "61390 KB"
addr = [
    "http://www.mediafire.com/?ewrm53hhqp6tlny",
    "(WAV)",
    "http://www.mediafire.com/?oxz36tk6zz4va27",
    "(LQ, ogg 7020KB)",
]
genre = "post-rock"
impr = "24"
total = "10"
avg = "0.41"
regist = "2012/01/29 23:55"
update = "2012/02/19 23:44"

[[entries]]
no = "54"
name = "haleit"
title = "無限遠点"
size = "5200 KB"
addr = [
    "http://nekokan.dyndns.info/~anonymous/easymotion/haleit_point_at_infinity.zip",
    "Lv8譜面差分（パッケージからor2/1以前にDLされた方向け）",
    "http://nekokan.dyndns.info/~anonymous/easymotion/point_02.zip",
]
genre = "Downtempo"
impr = "26"
total = "19"
avg = "0.73"
regist = "2012/01/29 23:55"
update = "2012/02/19 23:57"

[[entries]]
no = "55"
name = "0kash"
title = "breen vind"
size = "8300 KB"
addr = ["http://firestorage.jp/download/017db5190fbd1037fb896931ef5c930443481512"]
genre = "ambient step"
impr = "29"
total = "21"
avg = "0.72"
regist = "2012/01/29 23:56"
update = "2012/02/20 21:35"

[[entries]]
no = "56"
name = "SABREMISSILE"
title = "悲しみの残りカス"
size = "35717 KB"
addr = [
    "http://dl.dropbox.com/u/45360077/sabremissile-kanasiminonokorikasu.rar",
    "BGA付き本体です。",
    "http://dl.dropbox.com/u/45360077/sabremissile-kanasiminonokorikasu%28BGAappend%29.rar",
    "BGAとreadmeです。1/29 04:00以前にダウンロードされた方はこちらのBGA差分を当てて下さい。",
]
genre = "IDM / DUBSTEP"
impr = "45"
total = "45"
avg = "1"
regist = "2012/01/29 23:57"
update = "2012/02/19 23:58"

[[entries]]
no = "57"
name = "glustar"
title = "lifescape"
size = "78000 KB"
addr = [
    "http://glustar.sub.jp/bms/lifescape.zip",
    "(Wav)",
    "http://glustar.sub.jp/bms/lifescape_ogg.zip",
    "(Ogg) ※推奨",
]
genre = "nostalgia"
impr = "30"
total = "26"
avg = "0.86"
regist = "2012/01/29 23:58"
update = "2012/02/19 23:37"

[[entries]]
no = "58"
name = "kei_iwata"
title = "grow sunset"
size = "34242 KB"
addr = ["http://kei.raindrop.jp/bms/growsunset.zip"]
genre = "House"
impr = "38"
total = "31"
avg = "0.81"
regist = "2012/01/29 23:58"
update = "2012/02/19 23:28"

[[entries]]
no = "59"
name = "ETIA. feat.Jenga / jubeated"
title = "Love Blood"
size = "21600 KB"
addr = [
    "ogg:",
    "http://3t1a.net/bms/Love_Blood_ogg.zip",
    "ミラー:",
    "http://www1.axfc.net/uploader/Si/so/131138&key=lovebloodbms",
]
genre = "J-FUTURE TECHNOPOP"
impr = "47"
total = "43"
avg = "0.91"
regist = "2012/01/29 23:59"
update = "2012/02/20 02:13"

[[entries]]
no = "60"
name = "Lime"
title = "Stargazer"
size = "58000 KB"
addr = [
    "ogg:",
    "http://bmsabun.sitemix.jp/bms/original/lime_stargazerogg.zip",
    "とても重いwav:",
    "http://dl.dropbox.com/u/59509271/lime_stargazerwav.zip",
    "7key HARD差分:",
    "http://bmsabun.sitemix.jp/bms/original/stargazer_hard.zip",
    "( 1/30 2:40以前にダウンロードした方向けです。上の2つには同梱されています。)",
]
genre = "Scene"
impr = "46"
total = "46"
avg = "1"
regist = "2012/01/29 23:59"
update = "2012/02/19 23:59"

[[entries]]
no = "61"
name = "jill hi"
title = "Ocelot"
size = "44331 KB"
addr = ["http://www1.axfc.net/uploader/O/so/195506.zip"]
genre = "jazz house"
impr = "33"
total = "31"
avg = "0.93"
regist = "2012/01/29 23:59"
update = "2012/02/19 23:46"
