[[entries]]
no = "1"
name = "HARASSMENT"
title = "3⇔5"
size = "3 KB"
addr = ["http://ux.getuploader.com/uploderbms/download/12/35loop.zip"]
genre = "ONLYONE SOUND EXTENDED TRILL"
impr = "14"
total = "13"
avg = "0.92"
regist = "2012/04/29 00:02"
update = "2012/05/19 01:22"

[[entries]]
no = "2"
name = "空見沢佳奈 feat. ngstaq"
title = "Block me ngstaq!!!"
size = "3000 KB"
addr = ["http://www.mediafire.com/?a5waxo46h4v26l5"]
genre = "ごめんなさい"
impr = "23"
total = "23"
avg = "1"
regist = "2012/04/29 00:05"
update = "2012/05/19 01:23"

[[entries]]
no = "3"
name = "MI-OH?"
title = "Calling Madness"
size = "3570 KB"
addr = ["http://dl.dropbox.com/u/67107567/q_CallingMadness_ogg.zip"]
genre = "発狂BMS"
impr = "12"
total = "9"
avg = "0.75"
regist = "2012/04/29 00:06"
update = "2012/05/19 23:52"

[[entries]]
no = "4"
name = "かいだんくん"
title = "階段位検定 三級"
size = "1300 KB"
addr = ["http://www1.axfc.net/uploader/Sc/so/341200.rar"]
genre = "KAIDAN"
impr = "13"
total = "12"
avg = "0.92"
regist = "2012/04/29 00:42"
update = "2012/05/19 22:17"

[[entries]]
no = "5"
name = "Lasque"
title = "LioS"
size = "10 KB"
addr = ["http://fuki1755.starfree.jp/bms/lios.rar"]
genre = "BIG BEAT"
impr = "10"
total = "1"
median = "1"
avg = "0.1"
regist = "2012/04/29 01:10"
update = "2020/02/13 19:12"

[[entries]]
no = "6"
name = "DJ.rumba"
title = "La Roomba"
size = "3290 KB"
addr = ["http://www1.axfc.net/uploader/C/so/165266.zip"]
genre = "テックルンバ"
impr = "17"
total = "15"
avg = "0.88"
regist = "2012/04/29 04:06"
update = "2012/05/19 23:23"

[[entries]]
no = "7"
name = "たっかー"
title = "ｶﾁｬｶﾁｬｶﾁｬ……ｯﾀｰﾝ!!"
size = "631 KB"
addr = ["https://www.sugarsync.com/pf/D6795777_7114785_172567"]
genre = "typing"
impr = "11"
total = "11"
avg = "1"
regist = "2012/04/29 14:31"
update = "2012/05/19 23:30"

[[entries]]
no = "8"
name = "ｄＪ ｐＯｗｅＲ"
title = "闇"
size = "9 KB"
addr = ["http://www1.axfc.net/uploader/Li/so/127446.lzh"]
genre = "ＨＵＭＡＮ ＳＥＱＥＮＣＥＲ"
impr = "17"
total = "7"
avg = "0.41"
regist = "2012/04/30 20:58"
update = "2012/05/19 23:53"

[[entries]]
no = "9"
name = "昭和区かまぼこ工場コールセンター"
title = "700nmくらい"
size = "320 KB"
addr = ["==="]
genre = "REDBEAM"
impr = "13"
total = "10"
avg = "0.76"
regist = "2012/04/30 21:10"
update = "2012/05/20 16:05"

[[entries]]
no = "10"
name = "vznevb"
title = "#TITLE"
size = "1400 KB"
addr = ["http://www1.axfc.net/uploader/Sc/so/342146.zip&key=bmsbms"]
genre = "PLOGLESSIBE"
impr = "18"
total = "17"
avg = "0.94"
regist = "2012/05/02 05:29"
update = "2012/05/19 23:17"

[[entries]]
no = "12"
name = "音楽放棄者 (Thefur Celtridorn)"
title = "I GIVE UP"
size = "7650 KB"
addr = ["http://www.mediafire.com/?sfuqz3jcw5ta4z4"]
genre = "無理"
impr = "12"
total = "11"
avg = "0.91"
regist = "2012/05/02 11:49"
update = "2012/05/19 23:34"

[[entries]]
no = "13"
name = "daikon"
title = "Speedy RED"
size = "706 KB"
addr = ["＊いしのなかにいる＊"]
genre = "Liqiud Unk"
impr = "9"
total = "2"
avg = "0.22"
regist = "2012/05/03 02:24"
update = "2012/05/20 23:15"

[[entries]]
no = "14"
name = "(作者は逮捕されました) feat.woslicerII"
title = "爆発2012"
size = "2836 KB"
addr = ["---"]
genre = "無許可"
impr = "11"
total = "5"
avg = "0.45"
regist = "2012/05/03 16:57"
update = "2012/05/20 14:30"

[[entries]]
no = "15"
name = "|･ω･)ﾉ-----------------------@"
title = "おんかい！"
size = "3500 KB"
addr = ["http://dl.dropbox.com/u/77510419/onkaidotcom.zip"]
genre = "これを人は事故という"
impr = "9"
total = "8"
avg = "0.88"
regist = "2012/05/05 01:19"
update = "2012/05/19 23:44"

[[entries]]
no = "16"
name = "体操のお兄さん"
title = "THE・縦連打"
size = "520 KB"
addr = ["http://dl.dropbox.com/u/77530343/taisou.zip"]
genre = "準備体操"
impr = "12"
total = "6"
avg = "0.5"
regist = "2012/05/05 03:12"
update = "2012/05/20 09:55"

[[entries]]
no = "17"
name = "DJ Autos vs. MC Road"
title = "Stuck in the World"
size = "1061 KB"
addr = [
    "http://dl.dropbox.com/s/o5y4ix300ofo37q/stuck.rar?dl=1",
    "http://dl.dropbox.com/s/4orafnkrvfabsme/stuck_ruvit.rar?dl=1",
    "[For ruv-it]",
]
genre = "situation"
impr = "12"
total = "11"
avg = "0.91"
regist = "2012/05/05 14:13"
update = "2012/05/20 00:21"

[[entries]]
no = "18"
name = "Dr.130"
title = "Y/N(130remix)"
size = "5673 KB"
addr = ["http://dl.dropbox.com/u/59462259/130bms_ex4.zip"]
genre = "VARIOUS"
impr = "11"
total = "8"
avg = "0.72"
regist = "2012/05/05 20:26"
update = "2012/05/19 23:06"

[[entries]]
no = "19"
name = "ezo"
title = "ﾊｹﾞﾑｼ"
size = "1360 KB"
addr = ["http://www1.axfc.net/uploader/Sc/so/343193"]
genre = "蝦夷"
impr = "14"
total = "11"
avg = "0.78"
regist = "2012/05/05 20:47"
update = "2012/05/19 23:59"

[[entries]]
no = "20"
name = "Telno & Tingu"
title = "或る鳥の生態"
size = "4511 KB"
addr = ["http://yaruki0.sakura.ne.jp/bms/T_T.zip"]
genre = "漫才"
impr = "12"
total = "11"
median = "0"
avg = "0.91"
regist = "2012/05/05 22:15"
update = "2017/03/12 16:39"

[[entries]]
no = "21"
name = "生録君"
title = "rec soul"
size = "27329 KB"
addr = ["http://www1.axfc.net/uploader/He/so/361840"]
genre = "harmony"
impr = "9"
total = "6"
avg = "0.66"
regist = "2012/05/05 22:35"
update = "2012/05/19 23:57"

[[entries]]
no = "22"
name = "いるか"
title = "謝"
size = "12345 KB"
addr = ["http://dl.dropbox.com/u/68979347/fdscaa.zip"]
genre = "NU STYLE APOLOGY"
impr = "11"
total = "3"
avg = "0.27"
regist = "2012/05/05 23:15"
update = "2012/05/19 23:58"

[[entries]]
no = "23"
name = "新生NECOX銀行"
title = "メガネ壊した謝罪会見"
size = "4600 KB"
addr = ["http://www.nekomirin.com/bms/necox_sorry.zip"]
genre = "HIGE SORRY"
impr = "11"
total = "11"
avg = "1"
regist = "2012/05/05 23:54"
update = "2012/05/19 23:58"
