[[entries]]
no = "1"
name = "taqumi"
title = "BaSSiTaLiaN"
size = "0 KB"
addr = ["http://music-side.com/bms/BaSSiTaLiaN.zip"]
genre = "GABBA"
impr = "60"
total = "504"
avg = "8.4"
regist = "2012/05/18 00:00"
update = "2012/06/10 23:28"

[[entries]]
no = "2"
name = "ueotan"
title = "夢幻城デクシア"
size = "28600 KB"
addr = ["http://dl.dropbox.com/u/13536802/MugenjoDexia.zip"]
genre = "Phantom Castle"
impr = "67"
total = "585"
avg = "8.73"
regist = "2012/05/18 00:01"
update = "2012/06/10 23:57"

[[entries]]
no = "3"
name = "LeaF"
title = "Don't Think, Feel."
size = "12800 KB"
addr = ["http://nekokan.dyndns.info/~anonymous/bms/leaf/dontthinkfeel/DontthinkFeel.zip"]
genre = "MELODIC TECHNO"
impr = "48"
total = "313"
avg = "6.52"
regist = "2012/05/18 00:02"
update = "2012/06/10 23:34"

[[entries]]
no = "4"
name = "5*LEAF(この世全ての悪)"
title = "MAX30000"
size = "2716 KB"
addr = [
    "http://www1.axfc.net/uploader/He/so/362991",
    "##########################################",
    "http://www1.axfc.net/uploader/He/so/364879",
    "##########################################",
    "過去差分全てに新差分を加えたMAX30000全部入りをアップロードしました。よしなに。",
]
genre = "ノンジャンル"
impr = "53"
total = "262"
avg = "4.94"
regist = "2012/05/18 00:03"
update = "2012/07/16 22:18"

[[entries]]
no = "5"
name = "めｎち"
title = "眠レル森ノ毒林檎"
size = "15000 KB"
addr = ["http://menchi.cocona.jp/dokuringobms.zip"]
genre = "グリム童話"
impr = "65"
total = "571"
avg = "8.78"
regist = "2012/05/18 00:04"
update = "2012/06/16 18:33"

[[entries]]
no = "6"
name = "竜。"
title = "Wind Step"
size = "105000 KB"
addr = ["http://www1.axfc.net/uploader/Li/so/128747"]
genre = "TRANCE"
impr = "38"
total = "207"
avg = "5.44"
regist = "2012/05/18 00:25"
update = "2012/06/11 18:54"

[[entries]]
no = "7"
name = "Lasque (fkRadish)"
title = "0=(+-<=>-+)=0 / creeping"
size = "1419 KB"
addr = [
    "http://big.freett.com/fuki1755/0=",
    "(_-_=_-_)=0.rar",
    "http://page.freett.com/fuki1755/nongenre_dl.html",
    "(落とせない方はこちらからどうぞ)",
]
genre = "TECHNO / DRUM'N'BASS"
impr = "53"
total = "426"
avg = "8.03"
regist = "2012/05/18 00:26"
update = "2012/06/11 01:13"

[[entries]]
no = "8"
name = "DG-P"
title = "Drizzling Rain"
size = "17087 KB"
addr = [
    "http://dg-life.net/bms/drizzling_rain_ogg.rar",
    "http://www1.axfc.net/uploader/N/so/153395",
]
genre = "Piano Solo"
impr = "48"
total = "407"
avg = "8.47"
regist = "2012/05/18 00:37"
update = "2012/06/10 23:53"

[[entries]]
no = "9"
name = "夜桜 鍵"
title = "Push one's way"
size = "67000 KB"
addr = ["http://dl.dropbox.com/u/77067884/Push%20%5B%E5%A4%9C%E6%A1%9C%20%E9%8D%B5%5D.zip"]
genre = "Progressive Rock"
impr = "38"
total = "226"
avg = "5.94"
regist = "2012/05/18 00:52"
update = "2012/06/10 23:55"

[[entries]]
no = "10"
name = "okari (mov:kkkfff2)"
title = "ShinyHeart"
size = "25244 KB"
addr = ["http://dl.dropbox.com/u/53491846/%5Bokari%5D%20-%20shinyheart.rar"]
genre = "ProgressiveHouse"
impr = "51"
total = "435"
avg = "8.52"
regist = "2012/05/18 01:02"
update = "2012/06/12 00:54"

[[entries]]
no = "11"
name = "かゆき"
title = "流音の朱音"
size = "5100 KB"
addr = ["http://www1.axfc.net/uploader/Ne/so/132908"]
genre = "RIVER"
impr = "53"
total = "458"
avg = "8.64"
regist = "2012/05/18 01:20"
update = "2012/06/10 23:59"

[[entries]]
no = "12"
name = "うまるつふり"
title = "雪花"
size = "92900 KB"
addr = ["http://www1.axfc.net/uploader/O/so/206468"]
genre = "白透"
impr = "45"
total = "329"
avg = "7.31"
regist = "2012/05/18 02:42"
update = "2012/06/10 22:58"

[[entries]]
no = "13"
name = "EXAM.S"
title = "Capture!"
size = "5500 KB"
addr = [
    "http://www1.axfc.net/uploader/Ne/so/132937.zip",
    "http://dg-life.net/bms/Capture!.zip",
]
genre = "Trance Pop"
impr = "47"
total = "350"
avg = "7.44"
regist = "2012/05/18 21:11"
update = "2012/06/10 23:31"

[[entries]]
no = "14"
name = "H.U.T GiGAR"
title = "SHOTGUN ANTHEM"
size = "25600 KB"
addr = [
    "http://dg-life.net/bms/SHOTGUN_ANTHEM.rar",
    "http://dl.dropbox.com/u/52131493/SHOTGUN_ANTHEM.rar",
]
genre = "GABBER"
impr = "52"
total = "456"
avg = "8.76"
regist = "2012/05/18 23:43"
update = "2012/06/10 23:58"

[[entries]]
no = "15"
name = "KIRA"
title = "Sky World"
size = "32780 KB"
addr = [
    "wav版",
    "http://www1.axfc.net/uploader/Si/so/140377",
    "ogg版",
    "http://www1.axfc.net/uploader/H/so/159004",
]
genre = "shuffle pop"
impr = "34"
total = "230"
avg = "6.76"
regist = "2012/05/19 00:25"
update = "2012/06/10 23:58"

[[entries]]
no = "16"
name = "KIRA"
title = "Sky High"
size = "23510 KB"
addr = [
    "ogg版",
    "http://www1.axfc.net/uploader/Ne/so/133053",
    "wav版",
    "http://www1.axfc.net/uploader/N/so/153558",
]
genre = "TRANCE CORE"
impr = "35"
total = "198"
avg = "5.65"
regist = "2012/05/19 01:48"
update = "2012/06/10 23:57"

[[entries]]
no = "17"
name = "exclusion"
title = "innocent forest"
size = "45029 KB"
addr = ["http://dl.dropbox.com/u/54555387/bms/innocent_forest.zip"]
genre = "DRUM'N'BASS"
impr = "54"
total = "455"
avg = "8.42"
regist = "2012/05/19 03:01"
update = "2012/06/10 23:59"

[[entries]]
no = "18"
name = "rmx by bbangsami"
title = "Snow Flower (icicle fairy remix)"
size = "79259 KB"
addr = [
    "http://bemuri.com/eventpage/nongenre_sf.htm",
    "http://dl.dropbox.com/u/50235824/iv_vs_pn_rmx_bbangsami_Personality_snowflower_icicle_fiary_mix.rar",
    "(mirror)",
]
genre = "Happy Hardcore (J-Core style)"
impr = "55"
total = "482"
avg = "8.76"
regist = "2012/05/19 08:33"
update = "2012/06/11 08:56"

[[entries]]
no = "19"
name = "P.E.overground"
title = "YOKOHAMA DEADSPACE"
size = "6469 KB"
addr = ["http://endymium.net/bms/pe_yokohama.zip"]
genre = "PSYBORG ROCK"
impr = "40"
total = "315"
avg = "7.87"
regist = "2012/05/19 10:07"
update = "2012/06/10 23:59"

[[entries]]
no = "20"
name = "anubasu-anubasu"
title = "The Island of Albatross"
size = "33268 KB"
addr = ["http://dl.dropbox.com/u/45247999/TIOA_anu.zip"]
genre = "ENERGETIC TRANCE"
impr = "82"
total = "778"
avg = "9.48"
regist = "2012/05/19 13:37"
update = "2012/06/13 18:55"

[[entries]]
no = "21"
name = "Johnny"
title = "BLUELIGHT WINGS -BMS Style-"
size = "29000 KB"
addr = ["http://yukisite.com/johnny/others/butu/blw_bms.zip"]
genre = "Humanoid Pop"
impr = "39"
total = "275"
avg = "7.05"
regist = "2012/05/19 17:12"
update = "2012/06/13 04:36"

[[entries]]
no = "22"
name = "130"
title = "hav PUT A SUAVENESS,or CHANGE ME"
size = "7844 KB"
addr = ["http://dl.dropbox.com/u/59462259/130bms_no50.zip"]
genre = "WONKY/SYMPHONIC"
impr = "42"
total = "325"
avg = "7.73"
regist = "2012/05/19 17:35"
update = "2012/06/10 23:59"

[[entries]]
no = "23"
name = "Delight Gear Project"
title = "ORANGE STREAM (Delight Gear mix)"
size = "7987 KB"
addr = [
    "http://dl.dropbox.com/u/9753511/orangestream.rar",
    "http://www1.axfc.net/uploader/H/so/159041",
]
genre = "J-CORE"
impr = "38"
total = "292"
avg = "7.68"
regist = "2012/05/19 18:17"
update = "2012/06/10 23:56"

[[entries]]
no = "24"
name = "Richard Roe"
title = "SCRAPER"
size = "29389 KB"
addr = ["http://sites.google.com/site/richardroebms/scraper"]
genre = "HIP HOP"
impr = "47"
total = "431"
avg = "9.17"
regist = "2012/05/19 20:19"
update = "2012/06/20 13:29"

[[entries]]
no = "25"
name = "ETIA. feat.みちる / 篠乃ちよ"
title = "Believe in Myself"
size = "40000 KB"
addr = [
    "ogg 38.1MB",
    "http://3t1a.net/bms/believe_in_my_self_ogg.zip",
]
genre = "J-FUTURE D'N'B"
impr = "65"
total = "583"
avg = "8.96"
regist = "2012/05/19 22:43"
update = "2012/06/10 23:31"

[[entries]]
no = "26"
name = "ume"
title = "Astronaut's Rockshow"
size = "29000 KB"
addr = ["http://www42.tok2.com/home/umeboz/arbms.zip"]
genre = "Future Rock"
impr = "51"
total = "448"
avg = "8.78"
regist = "2012/05/20 00:11"
update = "2012/06/11 00:04"

[[entries]]
no = "27"
name = "nob ununderstood"
title = "plastic drum machine"
size = "10166 KB"
addr = [
    "https://skydrive.live.com/embedicon.aspx/.Public/",
    "[nob]plasticdrummachine.rar?cid=5c95bb1adfdcbf88&sc=documents",
    "ミラー：",
    "http://scytheleg.bms.ms/tempyou/music/bms/nob/plasticdrummachine/",
    "[nob]plasticdrummachine.rar",
]
genre = "Multiplex Breakbeats"
impr = "33"
total = "268"
avg = "8.12"
regist = "2012/05/20 00:43"
update = "2012/06/10 23:45"

[[entries]]
no = "28"
name = "q/stol"
title = "Nerdish Nerd"
size = "18839 KB"
addr = ["http://dl.dropbox.com/u/60669795/Nerdish_Nerd_ogg.zip"]
genre = "Dance"
impr = "45"
total = "403"
avg = "8.95"
regist = "2012/05/20 00:45"
update = "2012/06/10 23:57"

[[entries]]
no = "29"
name = "q/stol"
title = "Overwhelming Oppression"
size = "15912 KB"
addr = ["http://dl.dropbox.com/u/60669795/Overwhelming_Oppression_ogg.zip"]
genre = "Drum'n'Bass"
impr = "41"
total = "349"
avg = "8.51"
regist = "2012/05/20 00:47"
update = "2012/06/13 09:20"

[[entries]]
no = "30"
name = "竜。"
title = "洞窟の光"
size = "52100 KB"
addr = ["http://www1.axfc.net/uploader/Ne/so/133021"]
genre = "GAME MUSIC"
impr = "31"
total = "167"
avg = "5.38"
regist = "2012/05/20 02:04"
update = "2012/06/11 18:54"

[[entries]]
no = "31"
name = "mommy"
title = "Flavor"
size = "19509 KB"
addr = ["http://mommy16807.up.seesaa.net/image/Flavor.rar"]
genre = "HOUSE"
impr = "47"
total = "426"
avg = "9.06"
regist = "2012/05/20 02:44"
update = "2012/06/11 00:03"

[[entries]]
no = "32"
name = "C17ru5"
title = "Remaining Snow"
size = "8800 KB"
addr = [
    "http://www1.axfc.net/uploader/H/so/159102.zip",
    "http://dl.dropbox.com/u/58944021/remaining_snow_ogg.zip",
]
genre = "Electro House"
impr = "35"
total = "265"
avg = "7.57"
regist = "2012/05/20 11:06"
update = "2012/06/10 23:56"

[[entries]]
no = "33"
name = "4G"
title = "propaganda by D.V.SPELLFORCE"
size = "4164 KB"
addr = ["http://www7a.biglobe.ne.jp/~furiefurie/u/propaganda.rar"]
genre = "EXPERIMENTAL HOUSE"
impr = "32"
total = "230"
avg = "7.18"
regist = "2012/05/20 11:37"
update = "2012/06/10 23:58"

[[entries]]
no = "34"
name = "Hope"
title = "絶対的共依存 -Codependence-"
size = "7500 KB"
addr = ["http://dl.dropbox.com/u/60741100/hope_codependence.zip"]
genre = "HARD TECH"
impr = "39"
total = "324"
avg = "8.3"
regist = "2012/05/20 14:13"
update = "2012/06/10 23:58"

[[entries]]
no = "35"
name = "cnriorc"
title = "JUMPING ENTRY"
size = "18145 KB"
addr = ["http://dl.dropbox.com/u/59462259/130bms_no43.rar"]
genre = "HARDSTYLE"
impr = "37"
total = "250"
avg = "6.75"
regist = "2012/05/20 15:22"
update = "2012/06/10 23:59"

[[entries]]
no = "36"
name = "MathFabric"
title = "Hateness"
size = "5504 KB"
addr = ["http://dl.dropbox.com/u/55776853/mf8_hateness_ogg.zip"]
genre = "GABBA"
impr = "44"
total = "359"
avg = "8.15"
regist = "2012/05/20 15:58"
update = "2012/06/10 23:47"

[[entries]]
no = "37"
name = "X-23"
title = "Leap Frog"
size = "9744 KB"
addr = ["http://www.mediafire.com/?arzgt497t77a8mf"]
genre = "Dubstep"
impr = "38"
total = "302"
avg = "7.94"
regist = "2012/05/20 18:22"
update = "2012/06/12 19:49"

[[entries]]
no = "38"
name = "MI-OH"
title = "FIVE RAYS"
size = "14200 KB"
addr = ["http://dl.dropbox.com/u/67107567/300_five_rays_ogg.zip"]
genre = "Formula Inst."
impr = "38"
total = "285"
avg = "7.5"
regist = "2012/05/20 20:50"
update = "2012/06/26 02:57"

[[entries]]
no = "39"
name = "xenothium"
title = "Ladies and Gentlemen!"
size = "44588 KB"
addr = [
    "[wav版]",
    "http://roaraddiction.mods.jp/bms/x019_lag_wav.rar",
    "[ogg版]",
    "http://roaraddiction.mods.jp/bms/x019_lag_ogg.rar",
]
genre = "DANCEHALL EURO DUBSTEP HARDTRANCE"
impr = "91"
total = "892"
avg = "9.8"
regist = "2012/05/20 20:52"
update = "2012/08/05 22:58"

[[entries]]
no = "40"
name = "佐々木英"
title = "Wonderful Dancing"
size = "11300 KB"
addr = ["http://nekokan.dyndns.info/~anonymous/bms/sa_wd/sa_wd2.zip"]
genre = "Dream Trance"
impr = "41"
total = "332"
avg = "8.09"
regist = "2012/05/20 20:55"
update = "2012/06/11 00:28"

[[entries]]
no = "41"
name = "Conx@0tu"
title = "Lolita℃"
size = "1436 KB"
addr = ["http://minus.com/mbcVfGwIzW"]
genre = "noise"
impr = "33"
total = "235"
avg = "7.12"
regist = "2012/05/20 21:04"
update = "2012/06/10 23:57"

[[entries]]
no = "42"
name = "Junk"
title = "Goodbye My Life"
size = "6564 KB"
addr = ["http://www.junkchannel.net/bms/junk_goodbye.rar"]
genre = "will"
impr = "53"
total = "489"
avg = "9.22"
regist = "2012/05/20 21:14"
update = "2012/06/10 23:50"

[[entries]]
no = "43"
name = "LuLuL"
title = "Detroit"
size = "15148 KB"
addr = ["http://dl.dropbox.com/u/38773828/bms/est106_lulul_detroit.zip"]
genre = "BREAKS"
impr = "53"
total = "492"
avg = "9.28"
regist = "2012/05/20 22:14"
update = "2012/06/23 22:24"

[[entries]]
no = "44"
name = "8284"
title = "Orbital Period"
size = "63000 KB"
addr = [
    "http://higehime.main.jp/8284/OrbitalPeriod_ogg.zip",
    "（修正差分）",
    "http://higehime.main.jp/8284/OrbitalPeriod_syusei.zip",
]
genre = "Acoustic Breaks"
impr = "62"
total = "575"
avg = "9.27"
regist = "2012/05/20 22:30"
update = "2012/06/10 23:58"

[[entries]]
no = "45"
name = "落雁"
title = "Calm Garden"
size = "3601 KB"
addr = [
    "http://dl.dropbox.com/u/52909188/LUCK10_cg.zip",
    "(2012/6/11 0:03差分同梱)",
]
genre = "Healing Harp"
impr = "34"
total = "207"
avg = "6.08"
regist = "2012/05/20 22:40"
update = "2012/06/11 00:07"

[[entries]]
no = "46"
name = "P.E. remixed by gmtn."
title = "Endymion (gmtn. remix)"
size = "13882 KB"
addr = ["http://gmtn.sub.jp/Endymion_gmtn_remix.zip"]
genre = "ENERGETIC TRANCE"
impr = "57"
total = "500"
avg = "8.77"
regist = "2012/05/20 22:59"
update = "2012/06/11 00:04"

[[entries]]
no = "47"
name = "celas respect for W.A.Mozart"
title = "トルコ行進曲 (Hd-NRG mix)"
size = "33300 KB"
addr = [
    "http://oblivion.dip.jp/creation/bms/turkeymarch_r.rar",
    "[通常版33.3MB]",
    "http://oblivion.dip.jp/creation/bms/turkeymarch_r-hqbga.rar",
    "[HQBGA版78.6MB]",
    "http://oblivion.dip.jp/creation/bms/turkeymarch_r/_bga.mpg",
    "[HQBGA単品71.5MB]",
]
genre = "hard nrg"
impr = "53"
total = "431"
avg = "8.13"
regist = "2012/05/20 23:06"
update = "2012/06/10 23:46"

[[entries]]
no = "48"
name = "流菜"
title = "Corona"
size = "8784 KB"
addr = ["http://yaruki0.sakura.ne.jp/bms/Corona_ogg.zip"]
genre = "Trancecore"
impr = "34"
total = "244"
avg = "7.17"
regist = "2012/05/20 23:23"
update = "2012/06/11 00:14"

[[entries]]
no = "49"
name = "KBT / 140"
title = "Lingsphere"
size = "45000 KB"
addr = ["http://www1.axfc.net/uploader/O/so/206773.rar&key=lingsphere"]
genre = "TRANCE"
impr = "47"
total = "413"
avg = "8.78"
regist = "2012/05/20 23:29"
update = "2012/06/10 23:58"

[[entries]]
no = "50"
name = "TiS feat.きゃと"
title = "RiZE UP"
size = "16500 KB"
addr = ["http://cineraria-studio.com/?page_id=53"]
genre = "J-EURO"
impr = "70"
total = "617"
median = "9"
avg = "8.81"
regist = "2012/05/20 23:35"
update = "2014/10/17 18:39"

[[entries]]
no = "51"
name = "薔薇奇耶麻百合華"
title = "恍惚百合女史麻薬的愛液飲料症"
size = "10582 KB"
addr = ["http://dl.dropbox.com/u/80488858/baraki_koukotsu.zip"]
genre = "PSY MINIMAL"
impr = "38"
total = "269"
avg = "7.07"
regist = "2012/05/20 23:37"
update = "2012/06/11 00:01"

[[entries]]
no = "52"
name = "Bit Upper"
title = "ゆるいっと"
size = "2000 KB"
addr = ["http://uprdeco.littlestar.jp/yu_ru_it_ogg.rar"]
genre = "HAPPY"
impr = "26"
total = "192"
avg = "7.38"
regist = "2012/05/20 23:43"
update = "2012/06/10 23:51"

[[entries]]
no = "53"
name = "Ym1024 feat. ひなたゆかり"
title = "ハルシネーション"
size = "6402 KB"
addr = ["http://yellowmapleleaf.com/bms/ym36_hallu_ogg.rar"]
genre = "Shuffle Pop"
impr = "66"
total = "629"
avg = "9.53"
regist = "2012/05/20 23:43"
update = "2012/06/10 23:58"

[[entries]]
no = "54"
name = "KAMO"
title = "breath"
size = "7542 KB"
addr = ["http://dl.dropbox.com/u/10808857/KAMO_breath_ogg.zip"]
genre = "SUNRISE"
impr = "41"
total = "333"
avg = "8.12"
regist = "2012/05/20 23:50"
update = "2012/06/10 23:58"

[[entries]]
no = "55"
name = "glustar"
title = "lotte"
size = "14000 KB"
addr = ["http://glustar.sub.jp/bms/lotte_ogg.zip"]
genre = "bossanova"
impr = "33"
total = "246"
avg = "7.45"
regist = "2012/05/20 23:56"
update = "2012/06/10 23:57"

[[entries]]
no = "56"
name = "Remixed by BACO feat. えみゅう (Original : xi)"
title = "Halcyon -MY INTERPRETATION-"
size = "14191 KB"
addr = ["http://www3.pf-x.net/~boxism-8500/bms.php?no=32&status=0"]
genre = "R&B"
impr = "57"
total = "472"
avg = "8.28"
regist = "2012/05/20 23:56"
update = "2013/09/29 13:42"

[[entries]]
no = "57"
name = "The Frail"
title = "GET OFF!!! LADY????"
size = "9050 KB"
addr = [
    "http://t.co/Rs4FHXk",
    "(OGG)",
    "http://t.co/keYeNjT",
    "(WAV)",
    "http://dl.dropbox.com/u/59489192/bga.mpg",
    "(BGA)",
]
genre = "Math Rock"
impr = "30"
total = "176"
avg = "5.86"
regist = "2012/05/20 23:57"
update = "2012/06/10 23:58"

[[entries]]
no = "58"
name = "CRUNCH"
title = "Golden Ring"
size = "5500 KB"
addr = [
    "http://www1.axfc.net/uploader/Ne/so/133059.rar",
    "http://dl.dropbox.com/u/80495475/Golden_Ring.rar",
]
genre = "PLANET WAVES"
impr = "41"
total = "329"
avg = "8.02"
regist = "2012/05/20 23:58"
update = "2012/07/22 22:58"

[[entries]]
no = "59"
name = "LU"
title = "euphoria/melancholia"
size = "8355 KB"
addr = ["http://gensoukyousoukyoku.nekokan.dyndns.info/6-LU-euphoria_melancholia.rar"]
genre = "TECHSTEP/HALFSTEP"
impr = "57"
total = "506"
avg = "8.87"
regist = "2012/05/20 23:59"
update = "2012/06/10 23:58"

[[entries]]
no = "60"
name = "cybermiso"
title = "ZOOQUU"
size = "11323 KB"
addr = [
    "http://dl.dropbox.com/u/45360077/cybermiso-zooquu%28with_illust%29.rar",
    "↑最新版です。一枚絵同梱版です。",
    "http://dl.dropbox.com/u/45360077/cybermiso-zooquu%28illust_sabun%29.rar",
    "↑一枚絵のみ差分です。",
    "--------------------------------------------------------------------",
    "ttp://dl.dropbox.com/u/45360077/cybermiso-zooquu.rar",
    "ttp://dl.dropbox.com/u/45360077/cybermiso-zooquu%28n%E8%AD%9C%E9%9D%A2%E4%BF%AE%E6%AD%A3%E5%90%8C%E6%A2%B1%E7%89%88%29.rar",
    "↑☆6譜面の名義を間違えていたものを修正した版です。",
    "ttp://dl.dropbox.com/u/45360077/_0_n_sp.bme",
    "↑☆6譜面の修正版単品です。",
    "-------------------------------------------------------------------",
]
genre = "MOOMBAHCORE"
impr = "65"
total = "593"
avg = "9.12"
regist = "2012/05/20 23:59"
update = "2012/06/10 23:59"

[[entries]]
no = "61"
name = "激渋紳士"
title = "激†渋†空†間"
size = "8000 KB"
addr = ["http://0meganet2.xxxxxxxx.jp/bms.html"]
genre = "GEKISHIBU DRUM'N'BASS"
impr = "30"
total = "194"
avg = "6.46"
regist = "2012/05/20 23:59"
update = "2013/02/23 03:41"
