[[entries]]
no = "1"
name = "hammer/BGA makein"
title = "SYNC in AXL"
size = "4427 KB"
addr = ["http://www4.ocn.ne.jp/~makein/etc/makein_sync.lzh"]
genre = "rock (ska)"
impr = "7"
total = "7"
avg = "1"
update = "2003/04/13 10:27"

[[entries]]
no = "2"
name = "hammer / A&T"
title = "SYNC in AXL"
size = "2810 KB"
addr = ["http://liz.nothing.sh/at/AT_sync2.rar"]
genre = "rock(ska)"
impr = "5"
total = "5"
avg = "1"
update = "2003/04/07 20:35"
