[[entries]]
no = "1"
name = "kagerow"
title = "Wonder World!"
size = "19437 KB"
addr = ["http://kagerow.net/s9f/wonder.zip"]
genre = "ドリーミーポップコア"
impr = "21"
total = "60"
avg = "2.85"
regist = "2012/07/14 00:00"
update = "2012/08/10 13:29"

[[entries]]
no = "2"
name = "DJ_VIXEM"
title = "TRUE BLUE"
size = "471 KB"
addr = [
    "https://docs.google.com/open?id=0BzzhFyQH4AgoLUFPcEk4TlQ4akE",
    "http://www1.axfc.net/uploader/File/so/81396.zip",
]
genre = "ミッドナイト"
impr = "19"
total = "45"
avg = "2.36"
regist = "2012/07/14 00:02"
update = "2012/08/08 23:53"

[[entries]]
no = "3"
name = "有栖川 悠"
title = "Dumbass"
size = "4714 KB"
addr = ["http://www1.axfc.net/uploader/Ne/so/136064.zip"]
genre = "ロッテルガバ"
impr = "19"
total = "52"
avg = "2.73"
regist = "2012/07/14 00:23"
update = "2012/08/08 23:49"

[[entries]]
no = "4"
name = "daisan"
title = "奏龍ピアソラ"
size = "24608 KB"
addr = [
    "http://clockxellox.sakura.ne.jp/BMS/Piasolla.zip",
    "(↑本体(7鍵差分同梱済み),↓7鍵差分)",
    "http://clockxellox.sakura.ne.jp/BMS/Sabun/Piasolla_Sabun.zip",
]
genre = "エレメンタルフュージョン"
impr = "25"
total = "73"
avg = "2.92"
regist = "2012/07/14 00:26"
update = "2012/08/11 08:55"

[[entries]]
no = "5"
name = "Holidra.K"
title = "Holy Sun 2012"
size = "11981 KB"
addr = ["http://www1.axfc.net/uploader/Li/so/132496.zip"]
genre = "ラブ＆ピースREMIX"
impr = "15"
total = "35"
avg = "2.33"
regist = "2012/07/14 11:03"
update = "2012/08/08 22:42"

[[entries]]
no = "6"
name = "ルゼ"
title = "clutch"
size = "4440 KB"
addr = ["http://www.luzeria.net/music/65_clutch_ogg.rar"]
genre = "ギアブレイクス"
impr = "19"
total = "50"
avg = "2.63"
regist = "2012/07/14 13:22"
update = "2012/08/09 00:18"

[[entries]]
no = "7"
name = "wigen_ (feat.kana)"
title = "ドキドキ☆夏休み直前スペシャル"
size = "34176 KB"
addr = ["http://neoarre.aquz.biz/xe/event_download"]
genre = "ナツミホップ"
impr = "21"
total = "62"
avg = "2.95"
regist = "2012/07/14 14:13"
update = "2012/08/08 23:50"

[[entries]]
no = "8"
name = "w_tre respect for AT&HU"
title = "Schur's Theorem"
size = "11800 KB"
addr = ["http://db.tt/u7xpfmn5"]
genre = "PIANO ALGEBRA"
impr = "19"
total = "51"
avg = "2.68"
regist = "2012/07/14 19:08"
update = "2012/08/08 23:52"

[[entries]]
no = "9"
name = "q/stol"
title = "星空スクリーン"
size = "13530 KB"
addr = ["http://dl.dropbox.com/u/60669795/starlit_sky_screen_ogg.zip"]
genre = "ティアフルポップ"
impr = "16"
total = "37"
avg = "2.31"
regist = "2012/07/14 23:52"
update = "2012/08/28 23:25"

[[entries]]
no = "10"
name = "oxygen"
title = "Rainy Day, Every Day."
size = "10240 KB"
addr = ["http://dl.dropbox.com/u/49925194/bms/ox_rain.zip"]
genre = "モダン・ストリート"
impr = "18"
total = "50"
avg = "2.77"
regist = "2012/07/15 12:21"
update = "2012/08/10 15:57"

[[entries]]
no = "11"
name = "kei_iwata"
title = "Special Summer Festival !!!"
size = "77500 KB"
addr = ["http://kei.raindrop.jp/bms/specialsummerfestival.zip"]
genre = "ハッピーサマーダンスポップ"
impr = "23"
total = "69"
avg = "3"
regist = "2012/07/16 03:42"
update = "2012/08/08 23:51"

[[entries]]
no = "12"
name = "nmk/エレーナ(犬飼あお)"
title = "I miss you"
size = "17204 KB"
addr = [
    "http://docs.google.com/uc?id=0B97xj9Ow1Tu8S0FxakVKc2VWbzg&export=download",
    "[7key差分]",
    "http://miohosina.moe.hm/bms/dl/i_miss_you_7key.zip",
]
genre = "アイドルステージ"
impr = "17"
total = "48"
avg = "2.82"
regist = "2012/07/16 04:50"
update = "2012/08/08 22:44"

[[entries]]
no = "13"
name = "abysalla"
title = "isolato"
size = "22477 KB"
addr = [
    "http://www.symphonian.co.kr/bms/isolato.rar",
    "(OGG)",
    "http://www.symphonian.co.kr/bms/isolato",
    "(WAV).rar (WAV)",
]
genre = "ウィッチハウス"
impr = "17"
total = "45"
avg = "2.64"
regist = "2012/07/16 04:53"
update = "2012/08/09 19:29"

[[entries]]
no = "14"
name = "P.E.overground"
title = "SABER(short mix)"
size = "11337 KB"
addr = ["http://endymium.net/bms/pe_saber.zip"]
genre = "ボーダーブレイク"
impr = "17"
total = "40"
avg = "2.35"
regist = "2012/07/16 09:14"
update = "2012/08/08 23:48"

[[entries]]
no = "15"
name = "Holidra.K"
title = "飛び立て、大空へ。"
size = "24005 KB"
addr = ["http://www1.axfc.net/uploader/Si/so/144639.zip"]
genre = "ツクールンベース"
impr = "18"
total = "42"
avg = "2.33"
regist = "2012/07/16 19:56"
update = "2012/08/08 23:48"

[[entries]]
no = "16"
name = "mugcups"
title = "涼風の汐"
size = "4300 KB"
addr = ["http://www1.axfc.net/uploader/He/so/368330"]
genre = "Rock"
impr = "19"
total = "39"
avg = "2.05"
regist = "2012/07/17 21:23"
update = "2012/08/08 23:35"

[[entries]]
no = "17"
name = "dawn-system"
title = "ソノママ"
size = "9468 KB"
addr = ["http://fdist.ps.land.to/bms/sonomama_ogg.zip"]
genre = "トゥルーエンシー"
impr = "20"
total = "56"
avg = "2.8"
regist = "2012/07/18 19:58"
update = "2012/08/09 00:18"

[[entries]]
no = "18"
name = "taqumi"
title = "DARK KNIGHT"
size = "1 KB"
addr = ["http://music-side.com/bms/DARK_KNIGHT.zip"]
genre = "ダークロック"
impr = "21"
total = "57"
avg = "2.71"
regist = "2012/07/18 23:37"
update = "2012/08/08 23:53"

[[entries]]
no = "19"
name = "めｎち"
title = "ランダ様に奉げる踊り子の舞"
size = "8700 KB"
addr = ["http://menchi.cocona.jp/baron_dance.zip"]
genre = "バロンダンス"
impr = "23"
total = "64"
avg = "2.78"
regist = "2012/07/19 09:19"
update = "2012/08/09 08:53"

[[entries]]
no = "20"
name = "戒斗"
title = "Tezcatl"
size = "15197 KB"
addr = ["http://www1.axfc.net/uploader/N/so/156788"]
genre = "ピアノプログレッシブ"
impr = "14"
total = "25"
avg = "1.78"
regist = "2012/07/19 17:38"
update = "2012/08/08 23:56"

[[entries]]
no = "21"
name = "KA-KU"
title = "戦姫 -Senki-"
size = "9370 KB"
addr = ["http://dl.dropbox.com/u/87297315/%5BKA-KU%5Dsenki.zip"]
genre = "オリエンタルファンタジー"
impr = "19"
total = "43"
avg = "2.26"
regist = "2012/07/20 22:52"
update = "2012/08/08 23:55"

[[entries]]
no = "22"
name = "Y.W"
title = "なついろ アーチ"
size = "11361 KB"
addr = ["http://www.yw-works.com/data/bm/natsuiro_arch_ogg.zip"]
genre = "ポップリスニング2"
impr = "19"
total = "54"
avg = "2.84"
regist = "2012/07/21 15:23"
update = "2012/08/08 23:59"

[[entries]]
no = "23"
name = "ミルフィーネ"
title = "Witch on The Cake"
size = "6727 KB"
addr = ["http://www1.axfc.net/uploader/H/so/162705.zip"]
genre = "ハッピーブレイクコア"
impr = "17"
total = "40"
avg = "2.35"
regist = "2012/07/21 23:40"
update = "2012/08/08 23:51"

[[entries]]
no = "24"
name = "seizan"
title = "WATER REFLECT"
size = "9779 KB"
addr = [
    "http://dl.dropbox.com/u/87173069/WATER%20REFLECT.zip",
    "http://ux.getuploader.com/seizan_BMS/",
    "(ミラー)",
]
genre = "ハウス"
impr = "15"
total = "29"
avg = "1.93"
regist = "2012/07/22 05:05"
update = "2012/08/08 23:45"

[[entries]]
no = "25"
name = "東風屋 梓"
title = "Σ＜∽ﾟ大フ"
size = "1362 KB"
addr = ["http://ux.getuploader.com/otofu_original/download/2/%E3%82%BF%E3%82%A4%E3%83%88%E3%83%AB%E9%AD%9A%E3%81%A3%E3%81%BD%E3%81%84%E3%82%88%E3%81%AD.zip"]
genre = "チップンコア"
impr = "15"
total = "38"
avg = "2.53"
regist = "2012/07/22 06:20"
update = "2012/08/08 23:42"

[[entries]]
no = "26"
name = "ナナク"
title = "キミとの境界線"
size = "36557 KB"
addr = [
    "http://bit.ly/MPPhzq",
    "http://bit.ly/N5CjO5",
    "↑差分用の追加ファイルをけろりんさんが用意してくださいました。",
    "１分以上のファイルをスライスした物が入っていますので、",
    "差分制作をされる方でIR登録できるようにしたい方はお使い下さい。",
]
genre = "ラブ＆ロール・エフェクター"
impr = "16"
total = "41"
avg = "2.56"
regist = "2012/07/22 15:53"
update = "2012/08/27 10:33"

[[entries]]
no = "27"
name = "Dragoner (fkRadish)"
title = "Letzte kampf"
size = "6221 KB"
addr = ["http://www1.axfc.net/uploader/H/so/162672"]
genre = "パトスコア"
impr = "13"
total = "32"
avg = "2.46"
regist = "2012/07/22 19:11"
update = "2012/08/09 01:23"

[[entries]]
no = "28"
name = "Dryad"
title = "grass-green holiday"
size = "29720 KB"
addr = ["http://db.tt/aVSA540X"]
genre = "フォレストルメンタル"
impr = "16"
total = "43"
avg = "2.68"
regist = "2012/07/22 19:13"
update = "2012/08/08 23:39"

[[entries]]
no = "29"
name = "シガタケ Remixed by MajesticPeriod"
title = "DevilBlade-DeadEnd-"
size = "12300 KB"
addr = ["http://www1.axfc.net/uploader/Li/so/133070"]
genre = "ズィバノーツ"
impr = "13"
total = "25"
avg = "1.92"
regist = "2012/07/22 19:58"
update = "2012/08/08 23:36"

[[entries]]
no = "30"
name = "謎の音楽アーティスト≪ミラクル★J≫"
title = "JUMPERやらせろ"
size = "16530 KB"
addr = ["http://dl.dropbox.com/u/59483835/jumperyarasero.rar"]
genre = "跳躍競技J   -ロック"
impr = "20"
total = "52"
avg = "2.6"
regist = "2012/07/22 22:10"
update = "2012/08/08 23:48"

[[entries]]
no = "31"
name = "kbwnk max"
title = "★So SweeT LittlE HearT★"
size = "8356 KB"
addr = [
    "http://kbwnk.net/data/sslh_ogg_mq.rar",
    "(8.3MB)",
    "http://kbwnk.net/data/sslh_ogg_hq.rar",
    "(14.0MB)",
]
genre = "ハッピーポップコーン"
impr = "19"
total = "54"
avg = "2.84"
regist = "2012/07/22 23:03"
update = "2012/08/09 00:09"

[[entries]]
no = "32"
name = "Telno"
title = "もう帰ろう"
size = "8590 KB"
addr = ["http://yaruki0.sakura.ne.jp/bms/home_ogg.zip"]
genre = "ユウヤケポップ"
impr = "19"
total = "54"
avg = "2.84"
regist = "2012/07/22 23:48"
update = "2012/08/08 23:58"

[[entries]]
no = "33"
name = "tekmin"
title = "Old Fashioned Donuts"
size = "8000 KB"
addr = ["http://artslight.lolipop.jp/bms/Old_Fashioned_Donuts.zip"]
genre = "テクノ80's"
impr = "16"
total = "38"
avg = "2.37"
regist = "2012/07/22 23:48"
update = "2012/08/08 23:33"

[[entries]]
no = "34"
name = "Ωμεγα"
title = "Dusk:of*GaDeN*in:Dawn"
size = "24000 KB"
addr = ["http://0meganet2.xxxxxxxx.jp/bms.html"]
genre = "ライトレス"
impr = "15"
total = "33"
avg = "2.2"
regist = "2012/07/22 23:52"
update = "2013/02/23 03:39"

[[entries]]
no = "35"
name = "tarolabo/riutaso/【躾】ますたー"
title = "天国か地獄"
size = "5337 KB"
addr = ["http://www.fnbi.jp/tarolabo/hiphop9.zip"]
genre = "ヒップホップ９"
impr = "19"
total = "54"
avg = "2.84"
regist = "2012/07/22 23:56"
update = "2012/08/08 23:59"

[[entries]]
no = "36"
name = "DeathParrow"
title = "Schneesturm"
size = "99999 KB"
addr = [
    "http://www.mediafire.com/?1867tcw6waiux8l",
    "http://www1.axfc.net/uploader/P/so/111850",
]
genre = "Electrovalse"
impr = "18"
total = "44"
avg = "2.44"
regist = "2012/07/22 23:56"
update = "2012/08/08 23:45"

[[entries]]
no = "37"
name = "Yosk!"
title = "monde des songe(Remix)"
size = "2400 KB"
addr = [
    "http://dl.dropbox.com/u/40341869/bms/monde.zip",
    "http://dl.dropbox.com/u/40341869/bms/monde_ogg.zip",
    "http://www1.axfc.net/uploader/Si/so/145116",
]
genre = "ファンタジーREMIX"
impr = "15"
total = "22"
avg = "1.46"
regist = "2012/07/22 23:59"
update = "2012/08/08 22:29"

[[entries]]
no = "38"
name = "CRUNCH"
title = "crypto"
size = "5515 KB"
addr = ["http://dl.dropbox.com/u/80495475/crypto.rar"]
genre = "クリスプテクノ"
impr = "21"
total = "62"
avg = "2.95"
regist = "2012/07/22 23:59"
update = "2012/08/08 23:51"

[[entries]]
no = "39"
name = "園じぇるず"
title = "Po Po Po-Pi-Po"
size = "8000 KB"
addr = ["http://kei.raindrop.jp/bms/ppppp.zip"]
genre = "エルオリックバブルガムダンス"
impr = "17"
total = "42"
avg = "2.47"
regist = "2012/07/22 23:59"
update = "2012/08/08 23:56"

[[entries]]
no = "40"
name = "Nornir"
title = "Mystery Forest"
size = "14951 KB"
addr = ["http://www1.axfc.net/uploader/N/so/156954.rar"]
genre = "エスニックウィンド"
impr = "16"
total = "44"
avg = "2.75"
regist = "2012/07/23 00:35"
update = "2013/05/15 01:28"
