[[entries]]
no = "1"
name = "dawn-system obj:落雁"
title = "ソノママ"
size = "17 KB"
addr = ["https://dl.dropbox.com/u/52909188/sonomama-LNluck.zip"]
genre = "7key LNOverjoy"
impr = "1"
total = "1"
avg = "1"
regist = "2012/08/11 00:01"
update = "2012/08/12 13:06"

[[entries]]
no = "2"
name = "(v.a.) obj:lichtr / obj:second"
title = "(14鍵差分 6曲26枚)"
size = "95807 KB"
addr = ["http://objlr.kirara.st/objlr_s9f2012.zip"]
genre = "(various) (14keys)"
impr = "1"
total = "1"
avg = "1"
regist = "2012/08/11 00:02"
update = "2012/08/29 22:55"

[[entries]]
no = "3"
name = "otokaz"
title = "ランダ様に奉げる踊り子の舞"
size = "4 KB"
addr = ["https://dl.dropbox.com/u/92297622/data/otokaz_baron_Plus-p.zip"]
genre = "バロンダンス(9key plus)"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/11 00:08"
update = "2012/08/11 00:08"

[[entries]]
no = "4"
name = "uet / otokaz (kbwnk max) (movie : Moo(鮭))"
title = "★So SweeT LittlE HearT★"
size = "1341 KB"
addr = ["http://db.tt/3viPgDMF"]
genre = "ハッピーポップコーン"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/11 00:10"
update = "2012/08/11 00:58"

[[entries]]
no = "5"
name = "tekmin obj by anubasu-anubasu"
title = "Old Fashioned Donuts 7key差分"
size = "24 KB"
addr = ["https://dl.dropbox.com/u/45247999/old_anu_sabun.zip"]
genre = "テクノ80's(の差分)"
impr = "2"
total = "2"
avg = "1"
regist = "2012/08/11 00:14"
update = "2012/08/26 03:36"

[[entries]]
no = "6"
name = "Various Artist (obj:V-E)"
title = "I miss you ほか(4曲分)"
size = "130 KB"
addr = ["http://www1.axfc.net/uploader/Sc/so/369260&key=DP"]
genre = "14keys"
impr = "1"
total = "1"
avg = "1"
regist = "2012/08/11 00:16"
update = "2012/08/14 22:02"

[[entries]]
no = "7"
name = "P.E.overground / hi-low"
title = "SABER (discus mix)"
size = "189 KB"
addr = [
    "http://www.geocities.jp/flow_flight_fantasy/pe_saber_hi_low_sabun.zip",
    "右クリック→対象をファイルに保存でお願いします。",
    "http://www.dropbox.com/s/reryfek38qut4bj/pe_saber_hi_low_sabun.zip",
    "ミラーです。",
]
genre = "エアバースト"
impr = "1"
total = "1"
avg = "1"
regist = "2012/08/11 00:25"
update = "2012/08/27 02:20"

[[entries]]
no = "8"
name = "kei_iwata(mov:capoki) / Symphonian"
title = "Special Summer Festival !!! （7／14key）"
size = "79 KB"
addr = ["http://www1.axfc.net/uploader/Sc/so/367571"]
genre = "ハッピーサマーダンスポップ"
impr = "2"
total = "2"
avg = "1"
regist = "2012/08/11 00:29"
update = "2012/08/14 22:03"

[[entries]]
no = "9"
name = "q/stol / obj:ゆず太"
title = "星空スクリーン"
size = "22 KB"
addr = ["http://drowsy.hannnari.com/starlit.html"]
genre = "ティアフルポップ -7key-"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/11 00:39"
update = "2012/08/12 14:41"

[[entries]]
no = "10"
name = "bug-light"
title = "Witch on The Cake"
size = "55 KB"
addr = [
    "http://www.geocities.jp/buganderror/appevent/2012_1/bug-cake-mille.zip",
    "(DLはURLコピペでお願いします)",
]
genre = "7KEYS"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/11 00:43"
update = "2012/08/11 00:49"

[[entries]]
no = "11"
name = "bug-light"
title = "Σ＜∽ﾟ大フ"
size = "38 KB"
addr = [
    "http://www.geocities.jp/buganderror/appevent/2012_1/bug-rosvw-tofuya.zip",
    "(DLはURLコピペでお願いします)",
]
genre = "7KEYS"
impr = "1"
total = "1"
avg = "1"
regist = "2012/08/11 00:46"
update = "2012/08/20 13:52"

[[entries]]
no = "12"
name = "bug-light"
title = "JUMPERやらせろ"
size = "25 KB"
addr = [
    "http://www.geocities.jp/buganderror/appevent/2012_1/bug-jumper-momoyama.zip",
    "(DLはURLコピペでお願いします)",
]
genre = "7KEYS"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/11 00:48"
update = "2012/08/11 00:48"

[[entries]]
no = "13"
name = "wigen_ (feat.kana) / obj:yoa"
title = "ドキドキ☆夏休み直前スペシャル"
size = "17 KB"
addr = ["http://fdist.ps.land.to/music/dkns_objyoa.zip"]
genre = "ナツミホップ[5BUTTON][STEP]"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/11 01:15"
update = "2012/08/11 01:15"

[[entries]]
no = "14"
name = "mugcups / obj:yoa"
title = "涼風の汐"
size = "16 KB"
addr = ["http://fdist.ps.land.to/music/suzukazenoshio_objyoa.zip"]
genre = "Rock"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/11 01:18"
update = "2012/08/11 01:18"

[[entries]]
no = "15"
name = "daisan / obj : 0samil0"
title = "奏龍ピアソラ"
size = "16 KB"
addr = ["https://www.dropbox.com/s/cch9vx30ea3vful/Piasolla-31.zip"]
genre = "Elemental Fusion"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/11 02:07"
update = "2012/08/11 02:09"

[[entries]]
no = "16"
name = "差分制作 赤い人"
title = "★So SweeT LittlE HearT★"
size = "189 KB"
addr = [
    "http://akred.web.fc2.com/bmsfile/sslh-AK-HARD.bms",
    "http://akred.web.fc2.com/bmsfile/sslh-AK-HARDEST.bms",
]
genre = "ハッピーポップコーン"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/11 02:11"
update = "2012/08/11 02:14"

[[entries]]
no = "17"
name = "kei_iwata / obj : 0samil0"
title = "Special Summer Festival !!!"
size = "25 KB"
addr = ["https://www.dropbox.com/s/499s42s3vo0zsi5/specialsummerfestival_31.zip"]
genre = "Happy Summer Dance Pop"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/11 02:25"
update = "2012/08/18 17:35"

[[entries]]
no = "18"
name = "KA-KU / obj.ctc"
title = "戦姫 -Senki- (7H/7EX)"
size = "16 KB"
addr = ["http://www1.axfc.net/uploader/Sc/so/369334&key=ctc"]
genre = "オリエンタルファンタジー"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/11 03:00"
update = "2012/08/12 03:36"

[[entries]]
no = "19"
name = "oxygen / つきやま"
title = "Rainy Day, Every Day."
size = "6 KB"
addr = ["http://stellawingroad.web.fc2.com/sabun/kari.html"]
genre = "モダン・ストリート"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/11 07:08"
update = "2012/08/11 07:39"

[[entries]]
no = "20"
name = "daisan (movie : 技師2) / つきやま"
title = "奏龍ピアソラ"
size = "8 KB"
addr = ["http://stellawingroad.web.fc2.com/sabun/kari.html"]
genre = "エレメンタルフュージョン"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/11 07:48"
update = "2012/08/11 07:48"

[[entries]]
no = "21"
name = "ミルフィーネ / つきやま"
title = "Witch on The Cake"
size = "16 KB"
addr = ["http://stellawingroad.web.fc2.com/sabun/kari.html"]
genre = "ハッピーブレイクコア"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/11 08:49"
update = "2012/08/11 08:49"

[[entries]]
no = "22"
name = "taqumi /obj. o"
title = "DARK KNIGHT [9BUTTON] [7KEY]"
size = "50 KB"
addr = ["http://zatsuzatsu.blog.shinobi.jp/Entry/45/"]
genre = "ダークロック"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/11 17:27"
update = "2012/08/11 17:33"

[[entries]]
no = "23"
name = "Dryad /obj. oxygen"
title = "grass-green holiday [7KEY] [14KEY]"
size = "50 KB"
addr = ["http://zatsuzatsu.blog.shinobi.jp/Entry/45/"]
genre = "FORESTRUMENTAL"
impr = "1"
total = "1"
avg = "1"
regist = "2012/08/11 17:38"
update = "2012/08/14 22:04"

[[entries]]
no = "24"
name = "oxygen /obj. oxygen"
title = "Rainy Day, Every Day. [7KEY]"
size = "50 KB"
addr = ["http://zatsuzatsu.blog.shinobi.jp/Entry/45/"]
genre = "モダン・ストリート"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/11 17:50"
update = "2012/08/11 17:50"

[[entries]]
no = "25"
name = "seizan / obj:Holidra.K"
title = "WATER REFLECT"
size = "5 KB"
addr = [
    "https://dl.dropbox.com/u/96538116/WATER%20REFLECT.zip",
    "http://www1.axfc.net/uploader/Sc/so/371938.zip",
    "（ミラー）",
    "※上のURLは自動で直リンクされないようなのでURLコピペでお願いします。",
]
genre = "ハウス(9keys EX)"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/11 18:40"
update = "2012/08/21 12:18"

[[entries]]
no = "26"
name = "原曲：KA-KU / Holidra.K(mov:アカツキユウ) Note:OK@GE"
title = "戦姫 -Senki- / Holy Sun 2012"
size = "50 KB"
addr = ["http://firestorage.jp/download/9a81c1b4ded0f31460213abea178e62e29b47fee"]
genre = "7keys Longnote"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/11 18:49"
update = "2012/08/11 18:51"

[[entries]]
no = "27"
name = "ひかげ (Nornir) obj:S.K"
title = "Mystery Forest"
size = "7 KB"
addr = ["http://ux.getuploader.com/bms_sabun_roda/download/19/%E3%82%A8%E3%82%B9%E3%83%8B%E3%83%83%E3%82%AF%E3%82%A6%E3%82%A3%E3%83%B3%E3%83%89.zip"]
genre = "エスニックウィンド"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/11 20:28"
update = "2012/08/13 11:29"

[[entries]]
no = "28"
name = "Y.W"
title = "なついろ アーチ"
size = "81 KB"
addr = ["http://www.yw-works.com/data/bm/natsuiro_arch_bms.zip"]
genre = "7KEYS、14KEYS"
impr = "2"
total = "2"
avg = "1"
regist = "2012/08/11 23:43"
update = "2012/08/14 22:09"

[[entries]]
no = "29"
name = "P.E.overground/obj:5*LEAF"
title = "SABER(short mix)"
size = "194 KB"
addr = ["https://dl.dropbox.com/u/94663500/pe_saber_7keyssabun.rar"]
genre = "BORDER BREAK"
impr = "1"
total = "1"
avg = "1"
regist = "2012/08/12 15:08"
update = "2012/08/21 14:05"

[[entries]]
no = "30"
name = "kei_iwata (園じぇるず) / Notes:RAY"
title = "Po Po Po-Pi-Po [7key N/H/A]"
size = "28 KB"
addr = ["http://www1.axfc.net/uploader/Sc/so/370110&key=ppppp"]
genre = "エルオリックバブルガムダンス"
impr = "1"
total = "1"
avg = "1"
regist = "2012/08/14 10:03"
update = "2012/08/14 13:46"

[[entries]]
no = "31"
name = "kagerow / obj:Holidra.K"
title = "Wonder World!"
size = "20 KB"
addr = [
    "https://dl.dropbox.com/u/96538116/wonder.zip",
    "http://www1.axfc.net/uploader/Sc/so/371939.zip",
    "（ミラー）",
    "※上のURLは直リンクされないようなのでURLコピペでお願いします。",
]
genre = "ドリーミーポップコア(9keys PLUS)"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/14 19:12"
update = "2012/08/21 12:22"

[[entries]]
no = "32"
name = "Telno / obj：JLS"
title = "もう帰ろう"
size = "8 KB"
addr = ["http://www1.axfc.net/uploader/Sc/so/370455"]
genre = "ユウヤケポップ[LN]"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/14 23:54"
update = "2012/08/15 19:18"

[[entries]]
no = "33"
name = "めｎち / Symphonian"
title = "ランダ様に奉げる踊り子の舞"
size = "72 KB"
addr = ["http://clockxellox.sakura.ne.jp/BMS/Sabun/baronsabun.zip"]
genre = "バロンダンス"
impr = "2"
total = "2"
avg = "1"
regist = "2012/08/15 14:22"
update = "2012/08/26 20:56"

[[entries]]
no = "34"
name = "kagerow / obj：JLS"
title = "Wonder World! [7KEYS ANOTHER++]"
size = "16 KB"
addr = ["http://www1.axfc.net/uploader/Sc/so/370487"]
genre = "ドリーミーポップコア"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/15 21:29"
update = "2012/08/15 21:29"

[[entries]]
no = "35"
name = "taqumi Image:DARK†KOIWAI / obj:lichtr"
title = "DARK KNIGHT"
size = "19546 KB"
addr = ["http://objlr.kirara.st/dark_knight_dp.zip"]
genre = "ダークロック (14keys)"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/16 22:47"
update = "2012/08/29 22:54"

[[entries]]
no = "36"
name = "ルゼ / obj:火尭 火田"
title = "clutch [Z.O.T]"
size = "12 KB"
addr = ["http://www1.axfc.net/uploader/Sc/so/371107&key=bms"]
genre = "ギアブレイクス（14keys?）"
impr = "2"
total = "2"
avg = "1"
regist = "2012/08/18 00:35"
update = "2012/08/26 20:58"

[[entries]]
no = "37"
name = "kbwnk max(otokaz) / obj : 0samil0"
title = "★So SweeT LittlE HearT★"
size = "34 KB"
addr = ["https://www.dropbox.com/s/e36msobt5nypm4e/sslh_31.zip"]
genre = "Happy PopCorN"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/18 17:35"
update = "2012/08/18 17:35"

[[entries]]
no = "38"
name = "ナナク obj:けろりん"
title = "キミとの境界線"
size = "22 KB"
addr = ["http://www1.axfc.net/uploader/Sc/so/371459.zip"]
genre = "ラブ＆ロール・エフェクター [14keys]"
impr = "1"
total = "1"
avg = "1"
regist = "2012/08/19 13:15"
update = "2012/08/26 21:01"

[[entries]]
no = "39"
name = "Y.W (movie : kotomi) obj:けろりん"
title = "なついろ アーチ"
size = "11 KB"
addr = ["http://www1.axfc.net/uploader/Sc/so/371461.zip"]
genre = "ポップリスニング2 [14keys]"
impr = "2"
total = "2"
avg = "1"
regist = "2012/08/19 13:25"
update = "2012/08/26 23:47"

[[entries]]
no = "40"
name = "taqumi/obj:epics-"
title = "DARK KNIGHT [14Keys]"
size = "23 KB"
addr = ["http://www1.axfc.net/uploader/Sc/so/371582"]
genre = "ダークロック"
impr = "1"
total = "1"
avg = "1"
regist = "2012/08/20 00:33"
update = "2012/08/26 23:19"

[[entries]]
no = "41"
name = "mugcups/obj:epics-"
title = "涼風の汐 [14Keys]"
size = "13 KB"
addr = ["http://www1.axfc.net/uploader/Sc/so/371579"]
genre = "Rock"
impr = "1"
total = "1"
avg = "1"
regist = "2012/08/20 00:50"
update = "2012/08/26 23:50"

[[entries]]
no = "42"
name = "戒斗 / obj:Monsta"
title = "Tezcatl"
size = "52 KB"
addr = ["http://www1.axfc.net/uploader/Sc/so/371627"]
genre = "ピアノプログレッシブ"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/20 05:43"
update = "2012/08/20 05:48"

[[entries]]
no = "43"
name = "ひかげ(Nornir) / otokaz(kbwnk max)(mov:Moo(鮭)) / daisan(mov:技師2) / object:薄杏"
title = "Mystery Forest 他2曲"
size = "80 KB"
addr = ["http://lalha.web.fc2.com/s9f2012.html"]
genre = "[7KEY/14KEY]"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/20 13:56"
update = "2012/08/21 11:13"

[[entries]]
no = "44"
name = "ルゼ / obj:Holidra.K"
title = "clutch"
size = "10 KB"
addr = ["http://www1.axfc.net/uploader/Sc/so/371962.zip"]
genre = "GEAR BRAKES[7KEYS]"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/21 16:04"
update = "2012/08/21 16:04"

[[entries]]
no = "45"
name = "nmk/エレーナ(犬飼あお)objあきぽん"
title = "I miss you"
size = "8 KB"
addr = ["http://www1.axfc.net/uploader/Sc/so/372165"]
genre = "アイドルステージ"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/22 02:39"
update = "2012/08/22 02:42"

[[entries]]
no = "46"
name = "wigen_ (feat.kana)(mov:石王マサト) / 差分 : 恋乃"
title = "ドキドキ☆夏休み直前スペシャル"
size = "31 KB"
addr = ["http://www1.axfc.net/uploader/Sc/so/372183"]
genre = "[7KEY]"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/22 08:58"
update = "2012/08/22 08:58"

[[entries]]
no = "47"
name = "ミルフィーネ / BANZAI"
title = "Witch on The Cake"
size = "63 KB"
addr = [
    "http://page.freett.com/iidxbanzai/Witch_sabun.rar",
    "http://www.dotup.org/uploda/www.dotup.org3345763.rar",
]
genre = "ハッピーブレイクコア [7keys][14keys]"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/24 09:55"
update = "2012/08/24 10:02"

[[entries]]
no = "48"
name = "ルゼ"
title = "clutch[broodrush]"
size = "7 KB"
addr = ["https://www.dropbox.com/s/9sca17csmnjjrab/clutch.rar"]
genre = "ギアブレイクス"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/24 22:26"
update = "2012/08/24 22:27"

[[entries]]
no = "49"
name = "Various Artist / JUMPER桃山"
title = "[BEGINNER差分5曲]"
size = "27 KB"
addr = ["https://dl.dropbox.com/u/59483835/BMS/S9Fsabun.rar"]
genre = "[9KEY BEGINNER]"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/25 17:43"
update = "2012/08/25 17:44"

[[entries]]
no = "50"
name = "Nornir obj:CR2032"
title = "Mystery Forest [14A-LN]"
size = "7 KB"
addr = ["http://firestorage.jp/download/4e81a61408e6f1ec3e049ae9ad70f2dc199e73d9"]
genre = "エスニックウインド[14keyLN]"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/26 00:26"
update = "2012/08/26 16:05"

[[entries]]
no = "51"
name = "Nornir / obj:Ωμεγα"
title = "Mystery Forest(7KEYS NORMAL/HYPER/ANOTHER)"
size = "100 KB"
addr = ["http://dl.dropbox.com/u/69517401/ethnicwind_7keys.zip"]
genre = "ETHNIC WIND(エスニックウィンド)"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/26 01:38"
update = "2012/08/26 01:38"

[[entries]]
no = "52"
name = "otokaz (kbwnk max) (movie : Moo(鮭)) / obj：JLS"
title = "★So SweeT LittlE HearT★"
size = "16 KB"
addr = ["http://www1.axfc.net/uploader/Sc/so/373347"]
genre = "ハッピーポップコーン（LN MANIAC）"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/26 22:43"
update = "2012/08/26 22:43"

[[entries]]
no = "53"
name = "ひかげ (Nornir) / obj:killer TOMATO"
title = "Mystery Forest"
size = "23 KB"
addr = ["http://www015.upp.so-net.ne.jp/deep_throat/BMS/mystery_forest.zip"]
genre = "エスニックウィンド [14keys]"
impr = "0"
total = "0"
avg = "0"
regist = "2012/08/26 23:58"
update = "2012/08/26 23:58"
