[[entries]]
no = "1"
name = "nob underground"
team = "大都会岡山開墾戦線 -美作駐屯地-"
title = "okayamaEVOLVED"
size = "11827 KB"
addr = ["http://dl.dropbox.com/u/35847410/bms/%5Bnob%5DokayamaEVOLVED.rar"]
genre = "METROPOLITANISM"
impr = "3"
total = "3"
avg = "1"
regist = "2012/09/01 00:09"
update = "2012/09/30 15:21"

[[entries]]
no = "2"
name = "q/stol"
team = "押してダメなら法的措置"
title = "【MUSIC BOX PICK UP】OTHELLO【QSTOL】"
size = "0 KB"
addr = ["動画です。詳細ページからどうぞ。"]
genre = "ROCKIN'ON"
impr = "9"
total = "9"
avg = "1"
regist = "2012/09/01 00:17"
update = "2012/09/29 20:03"

[[entries]]
no = "3"
name = "dge-nesis"
team = "10km先右折"
title = "【曲のみ】to breaking ur rage"
size = "3660 KB"
addr = ["http://"]
genre = "dnb"
impr = "3"
total = "3"
avg = "1"
regist = "2012/09/01 03:56"
update = "2012/09/29 19:59"

[[entries]]
no = "4"
name = "Re-Te"
team = "Team Wahhei"
title = "Team Wahhei"
size = "5800 KB"
addr = ["http://soundcloud.com/re-te-1/bof-team-wahhei"]
genre = "HARDCORE"
impr = "5"
total = "5"
avg = "1"
regist = "2012/09/01 19:11"
update = "2012/09/29 19:12"

[[entries]]
no = "5"
name = "トコハムシスターズ"
team = "トコハムシスターズ"
title = "トコハムシスターズのテーマ"
size = "1070 KB"
addr = ["http://www.mediafire.com/?by2yqi91w8vcoqn"]
genre = "サイケデリック"
impr = "6"
total = "6"
avg = "1"
regist = "2012/09/01 20:59"
update = "2012/09/29 19:09"

[[entries]]
no = "6"
name = "seizan"
team = "EXPERT+"
title = "for me...(Radio Edit)"
size = "71000 KB"
addr = ["http://dl.dropbox.com/u/87173069/for%20me.zip"]
genre = "JUSCO NATION JAZZ HOUSE"
impr = "4"
total = "4"
avg = "1"
regist = "2012/09/02 12:26"
update = "2012/09/29 20:38"

[[entries]]
no = "7"
name = "klavistr/meropo"
team = "チェリーパイエンタテインメント"
title = "ちぇりーぱい☆ふぁんたしー (song only)"
size = "5272 KB"
addr = ["http://soundcloud.com/klavistr/cherrypie-phantasy"]
genre = "Eurobeat"
impr = "5"
total = "5"
avg = "1"
regist = "2012/09/02 16:14"
update = "2012/09/29 19:49"

[[entries]]
no = "8"
name = "痛男次郎"
team = "木工野郎ＩチームＡＡ"
title = "shinning justice"
size = "2620 KB"
addr = ["http://soundcloud.com/itaojirou/shinning-justice-bms-edit"]
genre = "happy hardcore"
impr = "5"
total = "5"
avg = "1"
regist = "2012/09/02 17:33"
update = "2012/09/29 19:21"

[[entries]]
no = "9"
name = "FLちゃん"
team = "Fruity Lovers"
title = "Miracle☆Fruit(BMS edit)"
size = "9999 KB"
addr = [
    "http://www.youtube.com/watch?v=GkHhW9MDP84&hd=1",
    "BGA ONLY",
]
genre = "フルーティ"
impr = "4"
total = "4"
avg = "1"
regist = "2012/09/02 21:31"
update = "2012/09/29 19:04"

[[entries]]
no = "10"
name = "MNMr"
team = "スクラッチはじめました。"
title = "Bonehead's Optimism"
size = "2800 KB"
addr = ["http://mnmr.dw.land.to/bof2012_pre.html"]
genre = "UK hard house"
impr = "3"
total = "3"
avg = "1"
regist = "2012/09/04 02:05"
update = "2012/09/29 21:57"

[[entries]]
no = "11"
name = "氷室さん"
team = "あじさいぞんび"
title = "Ambivalent / Lifework"
size = "3610 KB"
addr = ["http://ajisaizombie.page2.jp/music/ambivalent_lifework.mp3"]
genre = "Hydrangea Healing"
impr = "2"
total = "2"
avg = "1"
regist = "2012/09/04 22:31"
update = "2012/10/07 22:05"

[[entries]]
no = "12"
name = "noctie*"
team = "kurzweil_NL"
title = "Rewinding Sound Wave (Music Only)"
size = "20900 KB"
addr = ["http://soundcloud.com/noctie/rewinding-sound-wave"]
genre = "HAPPY HARDCORE"
impr = "3"
total = "3"
avg = "1"
regist = "2012/09/05 00:48"
update = "2012/09/29 19:00"

[[entries]]
no = "13"
name = "Team SeeUnion"
team = "SeeUnion"
title = "Team SeeUnion Teaser"
size = "0 KB"
addr = ["http://www.nicovideo.jp/watch/sm18808469"]
genre = "VARIOUS"
impr = "3"
total = "3"
avg = "1"
regist = "2012/09/05 23:00"
update = "2012/09/29 18:53"

[[entries]]
no = "14"
name = "ginkiha,wk."
team = "F.O.E."
title = "EOS"
size = "18200 KB"
addr = ["http://nzrg.jp/temp/EOS_master0906.zip"]
genre = "DAYBREAK HARDCORE"
impr = "13"
total = "13"
avg = "1"
regist = "2012/09/06 03:23"
update = "2012/09/29 20:54"

[[entries]]
no = "15"
name = "Ta2'nbeaT"
team = "Ta2'nbeaT style"
title = "Ancient Blaze"
size = "10173 KB"
addr = ["http://www.mediafire.com/download.php?x8j258aafprn4ez"]
genre = "Contemporary"
impr = "2"
total = "2"
avg = "1"
regist = "2012/09/06 22:58"
update = "2012/09/29 20:47"

[[entries]]
no = "16"
name = "Miss"
title = ","
size = "0 KB"
addr = [","]
genre = ","
impr = "0"
total = "0"
avg = "0"
regist = "2012/09/17 17:48"
update = "2012/09/17 17:52"

[[entries]]
no = "17"
name = "cutie de pranz"
title = "Madpakke"
size = "0 KB"
addr = ["動画のみ"]
genre = "Dirty art"
impr = "2"
total = "2"
avg = "1"
regist = "2012/09/23 00:42"
update = "2012/09/29 20:16"

[[entries]]
no = "18"
name = "代打三兄弟＆主役三姉妹"
team = "代打三兄弟＆主役三姉妹"
title = "☆代打＆主役 BOF2012P.S.☆ ～BMSの中身をちょっとだけ味見だよ！スペシャル～"
size = "1515 KB"
addr = ["http://daida.tv/bms/DAIDA_SYUYAKU_GOUDOU_EXTREME_PACKAGE.zip"]
genre = "tasting"
impr = "2"
total = "2"
avg = "1"
regist = "2012/09/26 00:01"
update = "2012/09/29 18:46"

[[entries]]
no = "19"
name = "MathFabric × Saldy × fkRadish"
team = "DTM経験とか関係なしにBOF参加するチーム"
title = "Re:Work"
size = "8546 KB"
addr = ["http://dl.dropbox.com/u/55776853/sure_rmx_ogg.zip"]
genre = "MEDLEY"
impr = "2"
total = "2"
avg = "1"
regist = "2012/09/28 13:56"
update = "2012/09/29 18:35"
