[[entries]]
no = "1"
name = "Laf_R"
title = "Woodland(BMS Edit)"
size = "40600 KB"
addr = ["http://dl.dropbox.com/u/68979347/woodland-Laf_R.zip"]
genre = "Progressive House"
impr = "53"
total = "451"
avg = "8.5"
regist = "2013/05/17 00:00"
update = "2013/06/09 23:36"

[[entries]]
no = "2"
name = "rebellion"
title = "Backside of the world"
size = "6364 KB"
addr = ["https://www.dropbox.com/s/ndrnc46i1fa2tpm/backside_of_the_world.rar"]
genre = "SPEEDCORE"
impr = "36"
total = "284"
avg = "7.88"
regist = "2013/05/17 00:00"
update = "2013/06/09 23:47"

[[entries]]
no = "3"
name = "Alefgard"
title = "★Black Hole★"
size = "84000 KB"
addr = ["https://dl.dropboxusercontent.com/u/94663500/%E2%98%85Black%20Hole%E2%98%85.rar"]
genre = "ノンジャンル"
impr = "25"
total = "138"
avg = "5.52"
regist = "2013/05/17 00:00"
update = "2013/06/09 23:21"

[[entries]]
no = "4"
name = "月華狼"
title = "Fels"
size = "20363 KB"
addr = ["https://dl.dropboxusercontent.com/s/j51fuxfg4kurc8x/Fels_ogg.zip?token_hash=AAEOlep-jhMfhTADRSzRS9Fqv3gTlBky4x4h6NnKuwfpUg&dl=1"]
genre = "Dramatic Trance"
impr = "23"
total = "147"
avg = "6.39"
regist = "2013/05/17 00:01"
update = "2013/06/09 23:11"

[[entries]]
no = "5"
name = "うまるつふり"
title = "焔花"
size = "16792 KB"
addr = ["http://dl.dropboxusercontent.com/u/86897153/homurabana.zip"]
genre = "炎舞"
impr = "31"
total = "215"
avg = "6.93"
regist = "2013/05/17 00:01"
update = "2013/06/09 23:29"

[[entries]]
no = "6"
name = "nmk/1B"
title = "The Elegant Universe"
size = "40674 KB"
addr = [
    "http://miohosina.moe.hm/bms/dl/nmk_Elegant_Universe.zip",
    "(ミラー)",
    "https://docs.google.com/uc?export=download&confirm=no_antivirus&id=0B97xj9Ow1Tu8N1RYQjhYVkZOcGM",
]
genre = "HARD TRANCE"
impr = "52"
total = "488"
avg = "9.38"
regist = "2013/05/17 00:02"
update = "2013/06/09 23:14"

[[entries]]
no = "7"
name = "髭姫"
title = "Ocean Fairy -BMS Edit-"
size = "22114 KB"
addr = ["http://higehime.main.jp/bms/higehime_of.rar"]
genre = "TRANCE"
impr = "27"
total = "201"
avg = "7.44"
regist = "2013/05/17 00:02"
update = "2013/06/09 22:42"

[[entries]]
no = "8"
name = "Perfect Another"
title = "影法師の桜道 -Blooming Road-"
size = "28245 KB"
addr = ["https://dl.dropboxusercontent.com/u/48004314/b4a.zip"]
genre = "Hard Fantasia"
impr = "27"
total = "190"
avg = "7.03"
regist = "2013/05/17 00:03"
update = "2013/06/10 01:40"

[[entries]]
no = "9"
name = "竜。"
title = "Short☆Happy"
size = "6900 KB"
addr = [
    "https://www.dropbox.com/s/inhwz7k2j7hfoku/Ryu0316_SH_ogg.rar",
    "(ogg)",
    "http://www1.axfc.net/uploader/so/2904576?key=ryu",
    "(wav)",
]
genre = "HAPPY TRANCE"
impr = "26"
total = "169"
avg = "6.5"
regist = "2013/05/17 00:04"
update = "2013/06/10 19:44"

[[entries]]
no = "10"
name = "ridanlue"
title = "NSTEPMIXTURE"
size = "5349 KB"
addr = ["http://drc.usamimi.info/bms/NSTEPMIXTURE.zip"]
genre = "break-bts and house megamix"
impr = "24"
total = "144"
avg = "6"
regist = "2013/05/17 00:05"
update = "2013/06/09 22:33"

[[entries]]
no = "11"
name = "Night Ruler"
title = "OBSERVER"
size = "40652 KB"
addr = [
    "(修正済み)",
    "https://dl.dropboxusercontent.com/u/87173069/OBSERVER_SIZN_.zip",
    "(修正差分)",
    "http://dl.dropboxusercontent.com/u/87173069/OBSERVER%E4%BF%AE%E6%AD%A3%E5%B7%AE%E5%88%86.zip",
]
genre = "UK HARDCORE"
impr = "25"
total = "177"
avg = "7.08"
regist = "2013/05/17 00:09"
update = "2013/06/09 22:21"

[[entries]]
no = "12"
name = "アスパラ音楽隊"
title = "DEYANEN"
size = "12782 KB"
addr = ["http://freett.com/woody_/bms.htm"]
genre = "TUKKOMI BEAT"
impr = "45"
total = "407"
avg = "9.04"
regist = "2013/05/17 00:24"
update = "2013/06/09 23:51"

[[entries]]
no = "13"
name = "polysha"
title = "Electric Signal"
size = "9640 KB"
addr = ["http://www.dropbox.com/s/0w9bw3o7xnu89y2/Electric_signal_ogg.zip"]
genre = "ELECTRO HARDTRANCE"
impr = "24"
total = "177"
avg = "7.37"
regist = "2013/05/17 00:42"
update = "2013/06/09 23:55"

[[entries]]
no = "14"
name = "ume"
title = "暗闇ダンサーズ"
size = "33000 KB"
addr = ["http://www42.tok2.com/home/umeboz/kurayamibms.zip"]
genre = "Alternative rock"
impr = "40"
total = "351"
avg = "8.77"
regist = "2013/05/17 01:04"
update = "2013/06/09 23:59"

[[entries]]
no = "15"
name = "Kennifh"
title = "Twilight Happiness"
size = "13406 KB"
addr = [
    "ogg:",
    "https://www.dropbox.com/s/3qtvyy4ylz5gv42/TwHp_ogg.zip",
    "wav:",
    "https://www.dropbox.com/s/wqvoeu89ty6ybiy/TwHp_wav.zip",
]
genre = "Instrumental Pop"
impr = "32"
total = "267"
avg = "8.34"
regist = "2013/05/17 01:16"
update = "2013/06/09 22:52"

[[entries]]
no = "16"
name = "Nitrix"
title = "Candy☆Symdrome"
size = "959 KB"
addr = ["http://page.freett.com/nitrix/non-g.html"]
genre = "JUMP UP"
impr = "30"
total = "214"
avg = "7.13"
regist = "2013/05/17 03:39"
update = "2013/06/09 23:54"

[[entries]]
no = "17"
name = "P4koo"
title = "8th:Planet"
size = "22733 KB"
addr = ["https://skydrive.live.com/#cid=C9FE89A646FB0230&id=C9FE89A646FB0230%21129"]
genre = "Space Techno"
impr = "37"
total = "300"
avg = "8.1"
regist = "2013/05/17 10:44"
update = "2013/06/09 22:59"

[[entries]]
no = "18"
name = "FROSQ"
title = "Analyzing the Prism"
size = "10000 KB"
addr = ["http://"]
genre = "Hard Trance"
impr = "0"
total = "0"
avg = "0"
regist = "2013/05/17 17:48"
update = "2013/06/01 20:46"

[[entries]]
no = "19"
name = "RYO-K"
title = "cloudless sky"
size = "7508 KB"
addr = ["http://www1.axfc.net/uploader/so/2907870.zip"]
genre = "Uplifting Trance"
impr = "21"
total = "128"
avg = "6.09"
regist = "2013/05/17 18:06"
update = "2013/06/09 23:07"

[[entries]]
no = "20"
name = "taqumi"
title = "Knockout combo"
size = "1 KB"
addr = ["http://music-side.com/bms/knockout_combo.zip"]
genre = "DIRTY DUBSTEP"
impr = "29"
total = "256"
avg = "8.82"
regist = "2013/05/17 19:33"
update = "2013/06/09 23:56"

[[entries]]
no = "21"
name = "4G"
title = "murder company"
size = "1175 KB"
addr = ["http://www7a.biglobe.ne.jp/~furiefurie/murdercompany.rar"]
genre = "ROTTEN BASS"
impr = "22"
total = "133"
avg = "6.04"
regist = "2013/05/17 19:44"
update = "2013/06/09 22:27"

[[entries]]
no = "22"
name = "かゆき"
title = "ピクニックガール"
size = "5200 KB"
addr = ["http://www1.axfc.net/uploader/so/2905483"]
genre = "ピクニカルポップス"
impr = "31"
total = "240"
avg = "7.74"
regist = "2013/05/17 22:30"
update = "2013/06/09 23:51"

[[entries]]
no = "23"
name = "風鈴奏"
title = "1024"
size = "7470 KB"
addr = ["http://www1.axfc.net/uploader/so/2906307.rar"]
genre = "PIANO AMBIENT"
impr = "24"
total = "169"
avg = "7.04"
regist = "2013/05/18 16:32"
update = "2013/06/09 23:10"

[[entries]]
no = "24"
name = "OXYGEN"
title = "Cosmos Boy"
size = "21800 KB"
addr = ["http://dl.dropboxusercontent.com/u/49925194/bms/ox_cosmos_boy.zip"]
genre = "POP TRANCE"
impr = "29"
total = "209"
avg = "7.2"
regist = "2013/05/18 16:33"
update = "2013/06/09 23:12"

[[entries]]
no = "25"
name = "polycube"
title = "Door"
size = "40135 KB"
addr = [
    "https://dl.dropboxusercontent.com/u/86971081/bmsfiles/nongenre2/plcb_door_ogg%5Bnongenre2%5D.zip",
    "(OGG版 BGA同梱)",
]
genre = "TERMINUS"
impr = "44"
total = "365"
avg = "8.29"
regist = "2013/05/18 20:14"
update = "2013/06/09 23:49"

[[entries]]
no = "26"
name = "zest:rave"
title = "H.S:Hadron Strike"
size = "66354 KB"
addr = ["https://skydrive.live.com/#cid=7267A98E9D1E6C21&id=7267A98E9D1E6C21%21206"]
genre = "Cyber Core"
impr = "62"
total = "581"
avg = "9.37"
regist = "2013/05/18 23:50"
update = "2013/06/09 23:46"

[[entries]]
no = "27"
name = "Gothlia"
title = "Kitsune"
size = "11500 KB"
addr = ["https://dl.dropboxusercontent.com/u/97469730/kitsune.zip"]
genre = "Dubstep"
impr = "31"
total = "234"
avg = "7.54"
regist = "2013/05/19 00:09"
update = "2013/06/09 23:53"

[[entries]]
no = "28"
name = "Arch"
title = "Evoltex"
size = "48093 KB"
addr = ["https://dl.dropboxusercontent.com/u/59482273/arch_avoltex_ogg.zip"]
genre = "Dramatic Trancecore"
impr = "33"
total = "272"
avg = "8.24"
regist = "2013/05/19 00:11"
update = "2013/06/09 23:45"

[[entries]]
no = "29"
name = "mommy"
title = "rough"
size = "21587 KB"
addr = ["http://mommy16807.up.seesaa.net/image/rough.rar"]
genre = "PIANO SOLO"
impr = "53"
total = "489"
avg = "9.22"
regist = "2013/05/19 01:05"
update = "2013/06/09 23:50"

[[entries]]
no = "30"
name = "D.J.Nero"
title = "S"
size = "44000 KB"
addr = ["http://black-funeral.kill.jp/s.zip"]
genre = "RENAISSANCE"
impr = "36"
total = "302"
avg = "8.38"
regist = "2013/05/19 09:19"
update = "2013/06/09 23:55"

[[entries]]
no = "31"
name = "DG-P"
title = "HARD DANCE"
size = "10142 KB"
addr = ["http://dg-life.net/bms/_bms_dg-p_kanimiso.zip"]
genre = "カニ"
impr = "33"
total = "260"
avg = "7.87"
regist = "2013/05/19 13:37"
update = "2013/06/09 23:36"

[[entries]]
no = "32"
name = "H.U.T GiGAR"
title = "I'M YOUR WORST NIGHTMARE"
size = "24000 KB"
addr = ["http://dg-life.net/bms/IM%20YOUR%20WORST%20NIGHTMARE.zip"]
genre = "ELECTRO HOUSE"
impr = "30"
total = "263"
avg = "8.76"
regist = "2013/05/19 16:16"
update = "2013/06/09 23:48"

[[entries]]
no = "33"
name = "Symphonian"
title = "Green"
size = "65973 KB"
addr = ["http://www.symphonian.co.kr/bms/Green.rar"]
genre = "New Age"
impr = "30"
total = "255"
avg = "8.5"
regist = "2013/05/19 18:29"
update = "2013/06/09 23:41"

[[entries]]
no = "34"
name = "Good Loosers"
title = "タキオン"
size = "9103 KB"
addr = ["https://www.dropbox.com/s/kydrtdc0g9qc1zx/%5BGood_Loosers%5D%E3%82%BF%E3%82%AD%E3%82%AA%E3%83%B3.zip?dl=1"]
genre = "粒子トランス"
impr = "35"
total = "273"
median = "8"
avg = "7.8"
regist = "2013/05/19 19:42"
update = "2017/10/17 20:00"

[[entries]]
no = "35"
name = "C17ru5"
title = "Polarity"
size = "26661 KB"
addr = [
    "http://www1.axfc.net/uploader/so/2907838",
    "https://dl.dropboxusercontent.com/u/58944021/C17ru5%20-%20Polarity.zip",
]
genre = "EDM"
impr = "29"
total = "239"
avg = "8.24"
regist = "2013/05/19 20:29"
update = "2013/06/09 23:54"

[[entries]]
no = "36"
name = "ROKINA"
title = "Invasion Percolation"
size = "24182 KB"
addr = ["http://sdrv.ms/16zuTB0"]
genre = "HARD AMBIENT"
impr = "20"
total = "161"
median = "8"
avg = "8.05"
regist = "2013/05/19 21:23"
update = "2020/06/11 22:31"

[[entries]]
no = "37"
name = "sound piercer / Project MAY"
title = "ある春の日のセレナーデ (feat. Soojae & Yunji)"
size = "50112 KB"
addr = ["http://sdrv.ms/11OCrhY"]
genre = "K-BALLAD POP"
impr = "47"
total = "427"
avg = "9.08"
regist = "2013/05/19 21:39"
update = "2013/06/09 23:42"

[[entries]]
no = "38"
name = "Lolly POP"
title = "ナノハナフィールド"
size = "3970 KB"
addr = ["http://dl.dropboxusercontent.com/u/87297315/nanohana.zip"]
genre = "LATIN TECHNO POP"
impr = "19"
total = "129"
avg = "6.78"
regist = "2013/05/19 21:43"
update = "2013/06/09 23:50"

[[entries]]
no = "39"
name = "KIRA"
title = "Starry Tears"
size = "13700 KB"
addr = ["https://skydrive.live.com/embed?cid=5316927E6470A7F9&resid=5316927E6470A7F9%21112&authkey=AEH1U9ZDFl6Of6Q"]
genre = "Night Trance"
impr = "25"
total = "169"
avg = "6.76"
regist = "2013/05/19 22:45"
update = "2013/06/09 23:47"

[[entries]]
no = "40"
name = "ume"
title = "Eagle"
size = "11000 KB"
addr = ["http://www42.tok2.com/home/umeboz/eaglebms.zip"]
genre = "house"
impr = "24"
total = "200"
avg = "8.33"
regist = "2013/05/19 22:53"
update = "2013/06/09 23:50"

[[entries]]
no = "41"
name = "q/stol"
title = "Decomposition"
size = "35756 KB"
addr = ["https://dl.dropboxusercontent.com/u/60669795/decomposition_ogg.zip"]
genre = "Electro House"
impr = "39"
total = "353"
avg = "9.05"
regist = "2013/05/19 23:06"
update = "2013/06/18 23:42"

[[entries]]
no = "42"
name = "q/stol"
title = "FUXXING YOUR BRAIN"
size = "27102 KB"
addr = ["https://dl.dropboxusercontent.com/u/60669795/fuxxing_your_brain_ogg.zip"]
genre = "BREAKCORE"
impr = "33"
total = "288"
avg = "8.72"
regist = "2013/05/19 23:06"
update = "2013/06/18 23:53"

[[entries]]
no = "43"
name = "FOLiACETATE(LeaF/sak)"
title = "Heterochromia Iridis"
size = "37915 KB"
addr = ["https://dl.dropboxusercontent.com/u/87878874/Heterochromia_Iridis_FOLiACETATE.zip"]
genre = "COALENSCENT BREAKCORE"
impr = "29"
total = "232"
avg = "8"
regist = "2013/05/19 23:14"
update = "2013/06/09 23:52"

[[entries]]
no = "44"
name = "FIERA"
title = "DanCing Time!"
size = "54321 KB"
addr = ["http://sdrv.ms/ZlbNM2"]
genre = "TRANCE"
impr = "20"
total = "125"
median = "7"
avg = "6.25"
regist = "2013/05/19 23:27"
update = "2013/11/13 21:08"

[[entries]]
no = "45"
name = "syzfonics"
title = "Point Graphy"
size = "21844 KB"
addr = [
    "http://syzf.108shiki.com/bms/pg.zip",
    "(wav) 84MB",
    "http://syzf.108shiki.com/bms/pg_ogg.zip",
    "(ogg) 21MB",
    "https://www.dropbox.com/s/sbivrupyxyvohat/pg.zip",
    "(wav) 84MB",
    "https://www.dropbox.com/s/yoa84uoy1xd0nba/pg_ogg.zip",
    "(ogg) 21MB",
]
genre = "Uplifting Trance"
impr = "32"
total = "276"
avg = "8.62"
regist = "2013/05/19 23:32"
update = "2013/06/09 23:59"

[[entries]]
no = "46"
name = "ROKINA"
title = "七つの鍵盤と大きな円盤のための練習曲 第三番 主にニ長調"
size = "17529 KB"
addr = ["http://sdrv.ms/12LZO7j"]
genre = "CONTEMPORARY ETUDE"
impr = "32"
total = "280"
median = "9"
avg = "8.75"
regist = "2013/05/19 23:33"
update = "2020/06/11 22:34"

[[entries]]
no = "47"
name = "Est"
title = "Rabbits"
size = "12393 KB"
addr = ["https://dl.dropboxusercontent.com/u/38773828/bms/est113_rabbits.zip"]
genre = "TRANCE"
impr = "28"
total = "217"
avg = "7.75"
regist = "2013/05/19 23:47"
update = "2013/06/09 23:59"

[[entries]]
no = "48"
name = "ストロー"
title = "Witch's cookie"
size = "6841 KB"
addr = ["https://dl.dropboxusercontent.com/u/41761207/straw_cookie.zip"]
genre = "Happy Breakcore"
impr = "19"
total = "133"
avg = "7"
regist = "2013/05/19 23:56"
update = "2013/06/09 23:17"

[[entries]]
no = "49"
name = "Ym1024"
title = "Double Magic"
size = "3054 KB"
addr = ["http://yellowmapleleaf.com/bms/ym41_wmagic_ogg.rar"]
genre = "EDM"
impr = "26"
total = "218"
avg = "8.38"
regist = "2013/05/19 23:57"
update = "2013/06/09 23:47"

[[entries]]
no = "50"
name = "Mirhi@MilkT"
title = "refrain train"
size = "4700 KB"
addr = ["http://mirhi.sakura.ne.jp/bms/mirhi_sktamp_ogg.zip"]
genre = "easylistening"
impr = "19"
total = "135"
avg = "7.1"
regist = "2013/05/19 23:59"
update = "2013/06/10 01:32"

[[entries]]
no = "51"
name = "ueotan"
title = "THE ONE"
size = "104000 KB"
addr = ["https://dl.dropboxusercontent.com/u/13536802/bms/THE%20ONE.zip"]
genre = "トレンディーハッピーハードコア"
impr = "45"
total = "406"
avg = "9.02"
regist = "2013/05/19 23:59"
update = "2013/06/09 23:52"

[[entries]]
no = "52"
name = "コバルト Remixed by Ωμεγα"
title = "ロマニム(Infinite Wing Remix)"
size = "22000 KB"
addr = ["http://0meganet2.xxxxxxxx.jp/bms.html"]
genre = "CYBER ART"
impr = "25"
total = "182"
avg = "7.28"
regist = "2013/05/19 23:59"
update = "2013/06/27 02:02"

[[entries]]
no = "53"
name = "軍人 + A.T.M. remixed by LU"
title = "THE SEVEN+COLD TRIBE(remix)"
size = "13815 KB"
addr = ["http://gensoukyousoukyoku.nekokan.dyndns.info/6-ATM+gunjin_remixed_by_LU-theseven+coldtribe.rar"]
genre = "TECHNOID MIX"
impr = "30"
total = "231"
avg = "7.7"
regist = "2013/05/20 00:00"
update = "2013/06/09 23:58"
