[[entries]]
no = "1"
name = "ridanlue"
team = "OLD STYLE"
title = "BOF2013 ending"
size = "5496 KB"
addr = ["http://drc.usamimi.info/bms/BOF2013ending.zip"]
genre = "opening"
impr = "7"
total = "7"
avg = "1"
regist = "2013/09/01 00:03"
update = "2013/09/28 13:42"

[[entries]]
no = "2"
name = "اٹوٹ"
team = "唐 突 に 読 め な い"
title = "そえちあぢりお"
size = "20 KB"
addr = ["https://www.dropbox.com/s/u0oup5zq0f092c7/%E3%81%9D%E3%81%88%E3%81%A1%E3%81%82%E3%81%A2%E3%82%8A%E3%81%8A.png"]
genre = "申し訳ありませんでした"
impr = "0"
total = "0"
avg = "0"
regist = "2013/09/01 00:03"
update = "2013/09/20 22:53"

[[entries]]
no = "3"
name = "A Piece of MM"
team = "ABE YUTA"
title = "Precociousness"
size = "54478 KB"
addr = [
    "http://sdrv.ms/15ID63M",
    "http://www.mediafire.com/download/t6hd42n67vv379r/%5BPoMM%5DPrecociousness.rar",
]
genre = "INFLUX"
impr = "2"
total = "2"
avg = "1"
regist = "2013/09/01 00:06"
update = "2013/09/03 14:35"

[[entries]]
no = "4"
name = "q/stol"
team = "クラブミュージック飽きた"
title = "願い（piano ver.）"
size = "0 KB"
addr = ["http://atsites.jp/lordlessgrief/"]
genre = "公式特設サイト"
impr = "2"
total = "2"
avg = "1"
regist = "2013/09/01 00:07"
update = "2013/09/01 22:30"

[[entries]]
no = "5"
name = "HUYU"
team = "HUYUSION"
title = "pomp it"
size = "57488 KB"
addr = ["https://www.dropbox.com/s/ligydah1fcn1gs8/%5BHUYU%5Dpomp%20it.bms.zip"]
genre = "TECHNO"
impr = "0"
total = "0"
avg = "0"
regist = "2013/09/01 01:31"
update = "2013/09/12 17:58"

[[entries]]
no = "6"
name = "er"
team = "杉浦さん"
title = "puppy love"
size = "8213 KB"
addr = ["http://dl.dropboxusercontent.com/u/28765267/er_puppylove.zip"]
genre = "CUTIE POP"
impr = "2"
total = "2"
avg = "1"
regist = "2013/09/01 17:43"
update = "2013/09/21 21:14"

[[entries]]
no = "7"
name = "Antonio.D"
team = "17観"
title = "Mono Leviathan"
size = "8509 KB"
addr = ["https://www.dropbox.com/s/kf4dv86f233ee6o/Mono%20Leviathan%20-%20Antonio.D.zip"]
genre = "Happy core"
impr = "0"
total = "0"
avg = "0"
regist = "2013/09/01 23:32"
update = "2013/09/09 18:26"

[[entries]]
no = "8"
name = "S.Percentage"
team = "The Worlds of Electronical"
title = "Frostline"
size = "5588 KB"
addr = ["https://dl.dropboxusercontent.com/u/48004314/frostline.mp3"]
genre = "Cold core"
impr = "2"
total = "2"
avg = "1"
regist = "2013/09/03 00:53"
update = "2013/09/15 19:38"

[[entries]]
no = "9"
name = "All Members"
team = "To+Mo+Rrow=Create"
title = "『To+Mo+Rrow=Create』trailer movie"
size = "0 KB"
addr = ["http://www.nicovideo.jp/watch/sm21748296"]
genre = "trailer movie"
impr = "0"
total = "0"
avg = "0"
regist = "2013/09/04 00:19"
update = "2013/09/04 00:20"

[[entries]]
no = "10"
name = "Ixia"
team = "the Chronoscoper"
title = "My Bittersweet 5 AM"
size = "5904 KB"
addr = ["https://soundcloud.com/ixia-1/my-bittersweet-5-am"]
genre = "Downtempo"
impr = "1"
total = "1"
avg = "1"
regist = "2013/09/08 01:32"
update = "2013/09/08 13:39"

[[entries]]
no = "11"
name = "Team SMAF"
team = "SMAFブラザーズ！！ & SMAFしすたーず！！"
title = "Team SMAF crossfade demos"
size = "20000 KB"
addr = [
    "SMAFブラザーズ！！",
    "https://soundcloud.com/ayashiki/bof2013-smaf",
    "SMAFしすたーず！！",
    "https://soundcloud.com/ayashiki/bof2013-smaf-1",
]
genre = "若い"
impr = "0"
total = "0"
avg = "0"
regist = "2013/09/09 00:15"
update = "2013/09/23 05:02"

[[entries]]
no = "12"
name = "Seossi's Life☆"
team = "おかしいおかし"
title = "Sweet Candy Land"
size = "2867 KB"
addr = ["https://soundcloud.com/tjtjsrhks/sweet-cookie-land"]
genre = "Cookie Song"
impr = "1"
total = "1"
avg = "1"
regist = "2013/09/09 05:18"
update = "2013/09/21 00:25"

[[entries]]
no = "13"
name = "Next-ream"
team = "AZUREVIATION"
title = "Simple Mechanism"
size = "37986 KB"
addr = ["http://www1.axfc.net/uploader/so/3023081"]
genre = "ENERGETIC TRANCE"
impr = "1"
total = "1"
avg = "1"
regist = "2013/09/09 18:35"
update = "2013/09/15 19:38"

[[entries]]
no = "14"
name = "dusKape"
team = "音楽制作サークル ラムレーズン"
title = "Be-Virtual!!"
size = "5320 KB"
addr = ["http://www1.axfc.net/uploader/so/3033103.zip"]
genre = "8bit journey"
impr = "1"
total = "1"
avg = "1"
regist = "2013/09/19 10:29"
update = "2013/09/28 13:41"

[[entries]]
no = "15"
name = "Arch / Reku"
team = "Destiny"
title = "fragile crystal"
size = "56000 KB"
addr = ["http://www.nicovideo.jp/watch/sm21865140"]
genre = "UK HARDCORE"
impr = "1"
total = "1"
avg = "1"
regist = "2013/09/19 21:57"
update = "2013/09/19 23:43"

[[entries]]
no = "16"
name = "Figyu"
team = "OCOREの楽しい作り方、そしてOCOREを聴くことによるその効果。"
title = "Just Go Now!!"
size = "70000 KB"
addr = [
    "https://www.dropbox.com/s/tvaicu40m04c9ic/Just%20Go%20Now.zip",
    "（低圧縮率 約51MB）",
    "https://www.dropbox.com/s/t0d9qlga4m20hk8/Just%20Go%20Now.rar",
    "（高圧縮率 約40MB）",
]
genre = "Happy Hardcore"
impr = "1"
total = "1"
avg = "1"
regist = "2013/09/22 07:06"
update = "2013/09/27 10:09"

[[entries]]
no = "17"
name = "KI"
team = "Qpic Sound Complexman Side R"
title = "Hello DJ"
size = "2320 KB"
addr = ["https://www.dropbox.com/s/b73tqocjqqzjlmk/Hello%20DJ~KI.MP3"]
genre = "House"
impr = "1"
total = "1"
median = "0"
avg = "1"
regist = "2013/09/23 13:33"
update = "2013/09/24 14:55"

[[entries]]
no = "18"
name = "フィエラ"
team = "南国九州沖縄連盟"
title = "Mirror Yard"
size = "4910 KB"
addr = ["http://sdrv.ms/17WaKmx"]
genre = "UPLIFTING TRANCE"
impr = "0"
total = "0"
median = "0"
avg = "0"
regist = "2013/09/23 16:56"
update = "2013/09/23 16:57"

[[entries]]
no = "19"
name = "長沼浩太と愉快な仲間たち"
team = "長沼浩太"
title = "長沼浩太（ラジオやりまーす）"
size = "0 KB"
addr = ["http://ustre.am/15oTC"]
genre = "Ustream"
impr = "1"
total = "1"
median = "0"
avg = "1"
regist = "2013/09/25 14:10"
update = "2013/09/28 01:12"
