[[entries]]
no = "1"
name = "daisuke@92"
title = "終着駅その先までも"
size = "13213 KB"
addr = ["http://docs.google.com/uc?id=0ByS9Wlo7KZbxd2tXcUZSLWE4clk&export=download"]
genre = "ナツミロック"
impr = "11"
total = "24"
median = "2"
avg = "2.18"
regist = "2013/11/23 00:02"
update = "2013/12/16 11:40"

[[entries]]
no = "2"
name = "daisan"
title = "ClowN CrowN"
size = "25518 KB"
addr = [
    "http://clockxellox.sakura.ne.jp/BMS/ClowNCrowN.zip",
    "(BMS差分同梱済み)",
    "http://clockxellox.sakura.ne.jp/BMS/Sabun/ClowNCrowN_bms.zip",
    "(BMS差分のみ)",
]
genre = "ジャジービート"
impr = "15"
total = "43"
median = "3"
avg = "2.86"
regist = "2013/11/23 00:02"
update = "2014/02/24 20:41"

[[entries]]
no = "3"
name = "o.s.gateと重音テト姫"
title = "直角スライドガール"
size = "6290 KB"
addr = ["https://www.dropbox.com/s/a54wf3ybpmdrlow/%E7%9B%B4%E8%A7%92%E3%82%B9%E3%83%A9%E3%82%A4%E3%83%89%E3%82%AC%E3%83%BC.zip"]
genre = "パイルサウンド"
impr = "13"
total = "29"
median = "2"
avg = "2.23"
regist = "2013/11/23 00:02"
update = "2013/12/16 01:47"

[[entries]]
no = "4"
name = "litmus*"
title = "陽炎Blaze"
size = "20275 KB"
addr = ["https://drive.google.com/file/d/0B0a6-fXyD9ZET2xxN2Z6WlQtN3M/view?usp=sharing"]
genre = "ハード ダンス"
impr = "13"
total = "38"
median = "3"
avg = "2.92"
regist = "2013/11/23 00:05"
update = "2015/11/12 18:35"

[[entries]]
no = "5"
name = "litmus*"
title = "Memetic Kill Agent"
size = "4168 KB"
addr = ["https://www.dropbox.com/s/af6v77tckxshhfe/litmus_memetickillagent_ogg.zip"]
genre = "終末"
impr = "12"
total = "25"
median = "2"
avg = "2.08"
regist = "2013/11/23 00:07"
update = "2013/12/15 21:45"

[[entries]]
no = "6"
name = "戒斗"
title = "VY Canis Majoris"
size = "16588 KB"
addr = ["http://www1.axfc.net/u/3095721.zip"]
genre = "プラネットランス"
impr = "9"
total = "22"
median = "3"
avg = "2.44"
regist = "2013/11/23 02:09"
update = "2013/12/15 21:45"

[[entries]]
no = "7"
name = "er"
title = "Lemming"
size = "8449 KB"
addr = ["https://dl.dropboxusercontent.com/u/28765267/er_lemming.zip"]
genre = "テレパシー"
impr = "16"
total = "45"
median = "3"
avg = "2.81"
regist = "2013/11/23 15:51"
update = "2015/10/25 08:55"

[[entries]]
no = "8"
name = "q/stol"
title = "薄葉陽炎"
size = "60642 KB"
addr = ["https://dl.dropboxusercontent.com/u/60669795/usuba_kagerou.zip?dl=1"]
genre = "カレッジポップ"
impr = "10"
total = "27"
median = "3"
avg = "2.7"
regist = "2013/11/23 17:34"
update = "2013/12/15 21:46"

[[entries]]
no = "9"
name = "Snack"
title = "Plastic Bird"
size = "15418 KB"
addr = ["https://dl.dropboxusercontent.com/s/sjnfvuemecwewmo/snack_plasticbird_ogg.zip?dl=1"]
genre = "プラスチックジャズ"
impr = "9"
total = "19"
median = "2"
avg = "2.11"
regist = "2013/11/23 19:26"
update = "2013/12/15 21:46"

[[entries]]
no = "10"
name = "DJ_VIXEM"
title = "CHROME"
size = "1740 KB"
addr = ["http://www1.axfc.net/u/3096903.zip"]
genre = "チェイサー"
impr = "8"
total = "16"
median = "2"
avg = "2"
regist = "2013/11/24 11:15"
update = "2013/12/15 21:47"

[[entries]]
no = "11"
name = "P4koo"
title = "LUNAR FACTORY"
size = "13005 KB"
addr = ["https://skydrive.live.com/redir?resid=C9FE89A646FB0230%21137"]
genre = "インダストリアルトランスコア"
impr = "13"
total = "37"
median = "3"
avg = "2.84"
regist = "2013/11/24 12:40"
update = "2013/12/15 21:47"

[[entries]]
no = "12"
name = "火龍騎士 / ゴミ大魔獣 / 魔導一角獣"
title = "この赤い大地と星空の中での褪色流星"
size = "4672 KB"
addr = ["https://dl.dropboxusercontent.com/u/107664546/BMS%20dropbox/fire_charge.zip"]
genre = "ファイアチャージ"
impr = "13"
total = "30"
median = "2"
avg = "2.3"
regist = "2013/11/24 20:42"
update = "2013/12/16 00:15"

[[entries]]
no = "13"
name = "Power Of Nature Arrange:Yosk!"
title = "少年は空を辿る -8bit mix-"
size = "1002 KB"
addr = ["https://drive.google.com/open?id=0B7qCw4hNijr4amxmY2N0R1l6d28"]
genre = "ムラクモ－８ｂｉｔミックス"
impr = "13"
total = "26"
median = "2"
avg = "2"
regist = "2013/11/25 20:58"
update = "2018/02/14 03:30"

[[entries]]
no = "14"
name = "Neun_jack a.k.a. uet"
title = "Get the Pride"
size = "15668 KB"
addr = ["https://dl.dropboxusercontent.com/u/60346274/Neunjack/neun_jack_GtP_ogg.rar"]
genre = "トリロジーコア"
impr = "9"
total = "25"
median = "3"
avg = "2.77"
regist = "2013/11/27 00:09"
update = "2013/12/16 00:59"

[[entries]]
no = "15"
name = "polysha feat.Eir&Sasara"
title = "Forbidden Prayer"
size = "4650 KB"
addr = ["http:www.dropbox.com/s/0xgduwgrysg8m8p/FP_polysha.zip"]
genre = "ハイパーエレクトロ"
impr = "11"
total = "27"
median = "2"
avg = "2.45"
regist = "2013/11/28 01:51"
update = "2013/12/21 00:28"

[[entries]]
no = "16"
name = "CR2032"
title = "Dark Ritual"
size = "9300 KB"
addr = ["http://aspr8192.secret.jp/bms/Lamantasy.zip"]
genre = "ファンタジーディレイラマ"
impr = "11"
total = "21"
median = "2"
avg = "1.9"
regist = "2013/11/28 04:22"
update = "2013/12/15 23:27"

[[entries]]
no = "17"
name = "かゆき"
title = "首輪を付けた猫"
size = "9160 KB"
addr = ["h"]
genre = "ソロウ"
impr = "12"
total = "31"
median = "3"
avg = "2.58"
regist = "2013/11/28 20:20"
update = "2015/08/23 17:09"

[[entries]]
no = "18"
name = "髭姫 feat.しゆ"
title = "キミを守る剣"
size = "23797 KB"
addr = [
    "http://higehime.main.jp/bms/hige-turugi.rar",
    "修正画像",
    "http://higehime.main.jp/bms/hige-turugi-syuse.zip",
]
genre = "ブレイブソング"
impr = "12"
total = "31"
median = "3"
avg = "2.58"
regist = "2013/11/28 20:35"
update = "2013/12/15 21:49"

[[entries]]
no = "19"
name = "Yosk!"
title = "スケルツォ"
size = "14679 KB"
addr = ["https://drive.google.com/open?id=0B7qCw4hNijr4QzBZaXlDQVdwczg"]
genre = "ソナチネ"
impr = "10"
total = "27"
median = "3"
avg = "2.7"
regist = "2013/11/29 05:51"
update = "2018/02/14 03:34"

[[entries]]
no = "20"
name = "ccgc"
title = "brightness"
size = "25179 KB"
addr = ["https://www.dropbox.com/s/ibgllbx2f6ug1mc/c01_brightness.rar"]
genre = "ラピッド"
impr = "9"
total = "23"
median = "3"
avg = "2.55"
regist = "2013/11/30 04:30"
update = "2014/01/12 17:39"

[[entries]]
no = "21"
name = "Y.W"
title = "あきいろ アルバム"
size = "9361 KB"
addr = ["http://www.yw-works.com/data/bm/akiiro_album_ogg.zip"]
genre = "ポップリスニング3"
impr = "13"
total = "38"
median = "3"
avg = "2.92"
regist = "2013/11/30 13:53"
update = "2013/12/15 23:44"

[[entries]]
no = "22"
name = "ccgc"
title = "holiday"
size = "11673 KB"
addr = ["https://dl.dropboxusercontent.com/s/sz9xapycbn2a73q/c02_holiday.rar"]
genre = "ストリートフュージョン"
impr = "10"
total = "28"
median = "3"
avg = "2.8"
regist = "2013/11/30 21:59"
update = "2014/01/12 17:38"

[[entries]]
no = "23"
name = "siqlo"
title = "underground dancefloor"
size = "20956 KB"
addr = [
    "[wav] -",
    "https://www.dropbox.com/s/2abium952epz31s/siqlo%20-%20underground%20dancefloor%5Bwav%5D.zip",
    "[ogg] -",
    "https://www.dropbox.com/s/5n1m20muxe4svdj/siqlo%20-%20underground%20dancefloor%5Bogg%5D.zip",
]
genre = "トラップ"
impr = "7"
total = "16"
median = "2"
avg = "2.28"
regist = "2013/11/30 22:30"
update = "2013/12/15 21:50"

[[entries]]
no = "24"
name = "ドリームグライダー Arranged by Holidra.K"
title = "Dream Glider -Night Parade Mix-"
size = "22580 KB"
addr = ["https://www.dropbox.com/s/nndza1s54g59xt4/%5B16%5DDreamGliderRemix.zip"]
genre = "ナイトパレード"
impr = "8"
total = "18"
median = "2.5"
avg = "2.25"
regist = "2013/11/30 22:31"
update = "2013/12/15 23:28"

[[entries]]
no = "25"
name = "ROKINA feat.うぴ"
title = "あきはのうた"
size = "9862 KB"
addr = ["https://dl.dropboxusercontent.com/s/jw024ti9kteuavp/LNB37-autumn_ogg.zip?token_hash=AAFkdhG6bVJilTKgfNNCXgxVKpoKtcRDjkn1PyzLTpq8Kg"]
genre = "サニーステップ"
impr = "11"
total = "29"
median = "3"
avg = "2.63"
regist = "2013/11/30 22:41"
update = "2020/06/11 23:33"

[[entries]]
no = "26"
name = "TEKINA"
title = "地下街"
size = "63139 KB"
addr = ["https://www.dropbox.com/s/6xp0zbe3o6gqgk5/%5BRUINOUS%20GHOST%5D%E5%9C%B0%E4%B8%8B%E8%A1%97.zip"]
genre = "ルイナスゴースト"
impr = "10"
total = "27"
median = "3"
avg = "2.7"
regist = "2013/12/01 05:13"
update = "2013/12/30 01:09"

[[entries]]
no = "27"
name = "ファントムP"
title = "ひかげもの（自己嫌悪ミックス・ゲームバージョン）"
size = "16168 KB"
addr = ["http://docs.google.com/uc?id=0ByS9Wlo7KZbxUVhFcVI0dFRYRG8&export=download"]
genre = "ボーカロック"
impr = "11"
total = "25"
median = "2"
avg = "2.27"
regist = "2013/12/01 11:48"
update = "2013/12/15 23:27"

[[entries]]
no = "28"
name = "No.Ⅸ"
title = "Obsidian"
size = "15165 KB"
addr = ["http://www1.axfc.net/u/3107991"]
genre = "コンパウンド"
impr = "9"
total = "21"
median = "2"
avg = "2.33"
regist = "2013/12/01 11:52"
update = "2013/12/16 18:45"

[[entries]]
no = "29"
name = "ぽんきち"
title = "winged dolphin"
size = "11625 KB"
addr = ["http://www.yw-works.com/data/bm/winged_dolphin_ogg.zip"]
genre = "ファンタジックネイション"
impr = "12"
total = "34"
median = "3"
avg = "2.83"
regist = "2013/12/01 12:35"
update = "2013/12/15 23:25"

[[entries]]
no = "30"
name = "ume"
title = "Rebellion's Blue"
size = "26000 KB"
addr = [
    "http://www42.tok2.com/home/umeboz/Rebellionsblue%20pms.zip",
    "http://fast-uploader.com/file/6941441370178/",
]
genre = "エレクトロビートロック"
impr = "9"
total = "25"
median = "3"
avg = "2.77"
regist = "2013/12/01 14:11"
update = "2013/12/15 23:27"

[[entries]]
no = "31"
name = "abysalla"
title = "Drown"
size = "14020 KB"
addr = [
    "http://symphonian.aquz.biz/bms/Drown.rar",
    "(HQ OGG)",
]
genre = "トリップホップ"
impr = "9"
total = "19"
median = "2"
avg = "2.11"
regist = "2013/12/01 19:37"
update = "2013/12/15 23:28"

[[entries]]
no = "32"
name = "totsumal vs Ziken Akahane"
title = "The Mystery Word"
size = "9700 KB"
addr = ["http://l.bitcasa.com/mC1YViOO"]
genre = "ポストジューク"
impr = "12"
total = "28"
median = "2"
avg = "2.33"
regist = "2013/12/01 20:46"
update = "2013/12/15 23:27"

[[entries]]
no = "33"
name = "A than_Lily"
title = "Club Killed the Rock Star"
size = "50893 KB"
addr = ["http://bit.ly/18f6DjN"]
genre = "プログレッシブラメント"
impr = "11"
total = "30"
median = "3"
avg = "2.72"
regist = "2013/12/01 22:18"
update = "2013/12/15 23:26"

[[entries]]
no = "34"
name = "自称ガールズダンスポップユニット・BATS (produce by JUMPER桃山)"
title = "MOJA"
size = "3244 KB"
addr = ["https://dl.dropboxusercontent.com/u/59483835/BMS/moja.rar"]
genre = "金の亡者ポップ"
impr = "9"
total = "19"
median = "2"
avg = "2.11"
regist = "2013/12/01 23:09"
update = "2013/12/15 21:52"

[[entries]]
no = "35"
name = "Ivy project"
title = "Catch my dream"
size = "15000 KB"
addr = ["http://kie.nu/1w9J"]
genre = "オータムブリーズ"
impr = "10"
total = "24"
median = "2.5"
avg = "2.4"
regist = "2013/12/01 23:19"
update = "2013/12/15 23:40"

[[entries]]
no = "36"
name = "犬"
title = "Sonic Cannon"
size = "70738 KB"
addr = ["http://www.dropbox.com/s/flug5mmaekaxu2x/Sonic_Cannon.zip"]
genre = "ハイギア"
impr = "9"
total = "18"
median = "2"
avg = "2"
regist = "2013/12/01 23:36"
update = "2013/12/15 21:52"

[[entries]]
no = "37"
name = "Clotho"
title = "天花の地・アートネシア"
size = "49500 KB"
addr = ["https://db.tt/FlXPhcKE"]
genre = "カンタールム"
impr = "16"
total = "46"
median = "3"
avg = "2.87"
regist = "2013/12/01 23:43"
update = "2013/12/16 00:11"

[[entries]]
no = "38"
name = "東風屋 梓"
title = "ALBUS IMPERATOR"
size = "148 KB"
addr = ["http://ux.getuploader.com/otofu_original/download/34/%E3%81%97%E3%82%8D%E3%81%84%E3%81%BF%E3%81%8B%E3%81%A9%E3%81%A8%E6%9B%B8%E3%81%84%E3%81%A6%E7%A7%8B.zip"]
genre = "アートノミック"
impr = "11"
total = "22"
median = "2"
avg = "2"
regist = "2013/12/01 23:48"
update = "2013/12/15 21:53"

[[entries]]
no = "39"
name = "橘花音 かなえゆめ composed by nmk"
title = "図書室のエルザ(A9S Remix)"
size = "24976 KB"
addr = [
    "http://miohosina.moe.hm/nmk_ELZARemix.zip",
    "7key差分を作成しました。",
    "http://miohosina.moe.hm/elzaremix_7key.zip",
]
genre = "ラブバラード"
impr = "11"
total = "27"
median = "3"
avg = "2.45"
regist = "2013/12/01 23:54"
update = "2013/12/15 21:53"

[[entries]]
no = "40"
name = "Blue-J vs. Ruby.G"
title = "Unexpected Encounter"
size = "52000 KB"
addr = ["https://dl.dropboxusercontent.com/u/51977836/bj_rg_unexpected_encounter.zip"]
genre = "世知辛イズドテクノX"
impr = "12"
total = "34"
median = "3"
avg = "2.83"
regist = "2013/12/01 23:55"
update = "2013/12/15 23:45"

[[entries]]
no = "41"
name = "Süßigkeiten"
title = "lethal rutabaga"
size = "13625 KB"
addr = ["http://ux.getuploader.com/otofu_original/download/35/%E3%81%AF%E3%81%A3%E3%81%B4%E3%83%BC%E3%81%AF%E3%82%8D%E3%81%86%E3%81%83%E3%82%93.zip"]
genre = "シンフォニックテラーコア"
impr = "9"
total = "19"
median = "2"
avg = "2.11"
regist = "2013/12/01 23:56"
update = "2013/12/15 21:53"
