[[entries]]
no = "1"
name = "甘党産"
title = "STREETKING"
size = "2769 KB"
addr = ["http://homepage2.nifty.com/omt/e&r/strklq.zip"]
genre = "house"
impr = "46"
total = "56"
avg = "1.21"
update = "2003/05/07 23:27"

[[entries]]
no = "2"
name = "DJ obelisk"
title = "君を乗せて -Blue Trance Remix-"
size = "7800 KB"
addr = ["----"]
genre = "J-Trance"
impr = "49"
total = "47"
avg = "0.95"
update = "2003/05/11 19:48"

[[entries]]
no = "3"
name = "Az7"
title = "Deep Bule -Trancetic Style-"
size = "4600 KB"
addr = ["http://www.comcarry.net/~akifumix/bms/db_t.zip"]
genre = "Trance"
impr = "32"
total = "32"
avg = "1"
update = "2003/05/07 23:00"

[[entries]]
no = "4"
name = "PEASE MAN"
title = "Lisfy"
size = "3060 KB"
addr = ["http://www.ismusic.ne.jp/08294432/lisfy.zip"]
genre = "TECHNO"
impr = "29"
total = "37"
avg = "1.27"
update = "2003/05/07 23:06"

[[entries]]
no = "5"
name = "Velna"
title = "involved..."
size = "3370 KB"
addr = ["http://www.eonet.ne.jp/~psk/involved.rar"]
genre = "Techno Dance"
impr = "30"
total = "14"
avg = "0.46"
update = "2003/05/07 23:15"

[[entries]]
no = "6"
name = "SOA"
title = "A steller dancer"
size = "1560 KB"
addr = [
    "http://homepage3.nifty.com/freeze_soa_31/",
    "[SOA]A_steller_dancer.rar",
]
genre = "BAROQUE DANCE"
impr = "45"
total = "74"
avg = "1.64"
update = "2003/05/07 23:30"

[[entries]]
no = "7"
name = "卯月赤也"
title = "Hell Scaper(nightmare mix)"
size = "2090 KB"
addr = ["http://www40.tok2.com/home/LunaticRay/files/nightmaremix.zip"]
genre = "gabba"
impr = "34"
total = "41"
avg = "1.2"
update = "2003/05/10 23:44"

[[entries]]
no = "8"
name = "veet"
title = "Magnitude300"
size = "275 KB"
addr = ["http://www.geocities.co.jp/Playtown/6336/"]
genre = "speedcore"
impr = "37"
total = "23"
avg = "0.62"
update = "2003/05/07 23:37"

[[entries]]
no = "9"
name = "はむ"
title = "REspEcT"
size = "8008 KB"
addr = ["http://www.katch.ne.jp/~bm-hama/respect.rar"]
genre = "Happy Eurocore"
impr = "53"
total = "84"
avg = "1.58"
update = "2003/05/07 23:43"

[[entries]]
no = "10"
name = "Mishe"
title = "遮光-かげり-"
size = "7550 KB"
addr = ["http://haltrance.hp.infoseek.co.jp/bms/kageri.lzh"]
genre = "Pop Trance"
impr = "36"
total = "56"
avg = "1.55"
update = "2003/05/07 23:54"

[[entries]]
no = "11"
name = "dj @pple"
title = "Par@bola"
size = "5105 KB"
addr = [
    "http://freeomega.hp.infoseek.co.jp/top/data/para",
    "@bola.lzh",
]
genre = "House"
impr = "31"
total = "30"
avg = "0.96"
update = "2003/05/07 23:17"

[[entries]]
no = "12"
name = "micron"
title = "nine"
size = "645 KB"
addr = ["http://www.ismusic.ne.jp/micron/nine.zip"]
genre = "minimal"
impr = "41"
total = "78"
avg = "1.9"
update = "2003/05/07 23:49"

[[entries]]
no = "13"
name = "mask"
title = "Break!Break?"
size = "5881 KB"
addr = [
    "http://www.ismusic.ne.jp/osc_fullscreen/bms/braek",
    "braek.zip",
]
genre = "Break Beat"
impr = "30"
total = "43"
avg = "1.43"
update = "2003/05/07 22:07"

[[entries]]
no = "14"
name = "ポポス"
title = "floud"
size = "4290 KB"
addr = ["http://mp.digitaljunk.net/popos_okiba/popos_floud.rar"]
genre = "drumnbass"
impr = "25"
total = "31"
avg = "1.24"
update = "2003/05/07 23:23"

[[entries]]
no = "15"
name = "Celas"
title = "Zipped"
size = "928 KB"
addr = ["http://celas-bms.hp.infoseek.co.jp/bms/mumei.shtm"]
genre = "techno"
impr = "34"
total = "45"
avg = "1.32"
update = "2003/05/07 22:27"

[[entries]]
no = "16"
name = "SE-JI"
title = "cheer up!"
size = "2125 KB"
addr = ["http://shi-row-web.hp.infoseek.co.jp/cheer_up.zip"]
genre = "happy hardcore"
impr = "30"
total = "18"
avg = "0.6"
update = "2003/05/07 23:38"

[[entries]]
no = "17"
name = "EEVEE MANIA"
title = "A.X.O.N."
size = "908 KB"
addr = ["http://lionel.hp.infoseek.co.jp/axon.rar"]
genre = "ELECTROSHOCK"
impr = "25"
total = "18"
avg = "0.72"
update = "2003/05/07 23:39"

[[entries]]
no = "18"
name = "Syatten"
title = "Nebula Drive"
size = "6560 KB"
addr = ["http://syatten.hp.infoseek.co.jp/bms.html"]
genre = "Space Trance"
impr = "48"
total = "91"
avg = "1.89"
update = "2003/05/07 23:40"

[[entries]]
no = "19"
name = "dockymc2"
title = "HAPPY SUMMER BEACH"
size = "4049 KB"
addr = ["http://www60.tok2.com/home/dockymc2/"]
genre = "EUROBEAT"
impr = "32"
total = "48"
avg = "1.5"
update = "2003/05/07 23:53"

[[entries]]
no = "20"
name = "GiNT@"
title = "永遠という名の媚薬 -Diabolic MIX-"
size = "2819 KB"
addr = ["http://ginta.dragon-inside.jp/music.html"]
genre = "Techno"
impr = "28"
total = "47"
avg = "1.67"
update = "2003/05/10 19:59"

[[entries]]
no = "21"
name = "Simple One"
title = "space debris"
size = "5500 KB"
addr = ["http://soma25.tripod.co.jp/spacedebris1.zip"]
genre = "drum'n'bass"
impr = "22"
total = "14"
avg = "0.63"
update = "2003/05/07 23:42"

[[entries]]
no = "22"
name = "amorphinism/あも"
title = "spring has come"
size = "5570 KB"
addr = ["http://homepage3.nifty.com/amo_terra/spring_lq.rar"]
genre = "EasyListening"
impr = "45"
total = "75"
avg = "1.66"
update = "2003/05/07 23:43"

[[entries]]
no = "23"
name = "嶋ノ上波良"
title = "Brain Labyrinth"
size = "5125 KB"
addr = ["http://goodwave.s15.xrea.com/bms/ach/B_Labyrinth.zip"]
genre = "Drum'n Bass"
impr = "24"
total = "15"
avg = "0.62"
update = "2003/05/08 00:03"

[[entries]]
no = "24"
name = "Raynoa"
title = "SEPIA (Raynoa's new departure remix)"
size = "5123 KB"
addr = ["http://sound.jp/raynoa/sepiaremix.zip"]
genre = "Epic trance"
impr = "43"
total = "55"
avg = "1.27"
update = "2003/05/07 23:47"

[[entries]]
no = "25"
name = "satire"
title = "幻影の碧水"
size = "2927 KB"
addr = ["http://satire1942.hp.infoseek.co.jp/geneinohekisui.zip"]
genre = "Drum'n Bass"
impr = "22"
total = "27"
avg = "1.22"
update = "2003/05/09 19:06"

[[entries]]
no = "26"
name = "RAY"
title = "mirage"
size = "7230 KB"
addr = ["http://ray5121.hp.infoseek.co.jp/mumeisen3.html"]
genre = "epic nostalgia"
impr = "30"
total = "19"
avg = "0.63"
update = "2003/05/07 23:51"

[[entries]]
no = "27"
name = "NH Sound Studio"
title = "S.S.I."
size = "1226 KB"
addr = ["http://page.freett.com/nhss/ssi.html"]
genre = "TRANCE"
impr = "25"
total = "30"
avg = "1.2"
update = "2003/05/07 23:56"

[[entries]]
no = "28"
name = "Roll/fity"
title = "be frontier"
size = "4690 KB"
addr = ["http://rollfity.hp.infoseek.co.jp/"]
genre = "Light pop"
impr = "30"
total = "44"
avg = "1.46"
update = "2003/05/07 23:49"

[[entries]]
no = "29"
name = "rocket digger"
title = "stratosquare"
size = "10503 KB"
addr = ["http://glass-ripper.hp.infoseek.co.jp/event.shtml"]
genre = "drill'n bass"
impr = "23"
total = "26"
avg = "1.13"
update = "2003/05/07 23:58"

[[entries]]
no = "30"
name = "k6m3"
title = "a^^9"
size = "932 KB"
addr = ["http://briefcase.yahoo.co.jp/k6m3"]
genre = "hip hop"
impr = "23"
total = "38"
avg = "1.65"
update = "2003/05/07 23:53"

[[entries]]
no = "31"
name = "Mt-H"
title = "Lively Bar"
size = "5234 KB"
addr = ["http://mt-h.hp.infoseek.co.jp/event.html"]
genre = "Piano music"
impr = "26"
total = "14"
avg = "0.53"
update = "2003/05/07 23:56"

[[entries]]
no = "32"
name = "Sopranotrom"
title = "ひまわり"
size = "3405 KB"
addr = ["http://www.zugyuun.org/himawari.rar"]
genre = "broken beats"
impr = "40"
total = "54"
avg = "1.35"
update = "2003/05/07 23:58"

[[entries]]
no = "33"
name = "Chikuwa"
title = "Substance of C"
size = "431 KB"
addr = ["http://chikuwa3.hp.infoseek.co.jp/arc-box/chik_substance.rar"]
genre = "Acid Techno / Noise"
impr = "27"
total = "30"
avg = "1.11"
update = "2003/05/07 23:53"

[[entries]]
no = "34"
name = "sanan"
title = "DoomZday-(my)justice 2nd-"
size = "349 KB"
addr = ["http://san-adon.hp.infoseek.co.jp/bms/doomzday.zip"]
genre = "SPEEDCORE"
impr = "36"
total = "49"
avg = "1.36"
update = "2003/05/07 23:53"

[[entries]]
no = "35"
name = "O-SE"
title = "桃源郷"
size = "5050 KB"
addr = ["http://www.kcc.zaq.ne.jp/dfamr600/tougen.lzh"]
genre = "Dream House"
impr = "35"
total = "54"
avg = "1.54"
update = "2003/05/07 23:55"

[[entries]]
no = "36"
name = "ring"
title = "P.A.R.A.D.I.S.E."
size = "8800 KB"
addr = ["http://www.kit.hi-ho.ne.jp/kocora/paradise_hqver.zip"]
genre = "hard house"
impr = "24"
total = "31"
avg = "1.29"
update = "2003/05/07 23:54"
