[[entries]]
no = "1"
name = "asahi3"
title = "nonsense"
size = "390 KB"
addr = [
    "https://dl.dropboxusercontent.com/s/fgsccq4yd7m5sst/nonsense.zip?d1=1",
    "https://dl.dropboxusercontent.com/s/aoxkzsl1yngx1oo/nonsense_lq.zip?d1=1",
    "(LQ+)",
]
genre = "techno"
impr = "10"
total = "10"
median = "0"
avg = "1"
regist = "2014/01/11 00:01"
update = "2014/01/26 23:45"

[[entries]]
no = "2"
name = "yoa"
title = "pop you take"
size = "4650 KB"
addr = [
    "(LQ wav 5MB)",
    "http://docs.google.com/uc?id=0ByS9Wlo7KZbxaW1Peng2bGVzRGs&export=download",
    "(HQ ogg)",
    "http://docs.google.com/uc?id=0ByS9Wlo7KZbxOHdpVGZuWTZOUnM&export=download",
]
genre = "Aufheben"
impr = "10"
total = "17"
median = "1"
avg = "1.7"
regist = "2014/01/11 00:01"
update = "2014/01/27 09:59"

[[entries]]
no = "3"
name = "Centain"
title = "Snow festival"
size = "4989 KB"
addr = [
    "http://dl.dropboxusercontent.com/s/hk73xvzsj8qby09/Snow_festival_LQ.rar",
    "(HQ ogg [7659kB])",
    "http://dl.dropboxusercontent.com/s/6akzelermr6icym/Snow_festival.rar",
]
genre = "EUROBEAT"
impr = "12"
total = "24"
median = "1"
avg = "2"
regist = "2014/01/11 00:02"
update = "2014/01/29 10:05"

[[entries]]
no = "4"
name = "Est"
title = "Ponytail"
size = "5037 KB"
addr = ["https://dl.dropboxusercontent.com/u/38773828/bms/est118_ponytail.zip"]
genre = "J-CORE"
impr = "14"
total = "38"
median = "0"
avg = "2.71"
regist = "2014/01/11 00:02"
update = "2014/01/26 23:56"

[[entries]]
no = "5"
name = "URY"
title = "OES"
size = "1322 KB"
addr = ["http://www.dropbox.com/s/0zut2pwa8jjnzce/URY_OES.rar?dl=1"]
genre = "CUT UP"
impr = "5"
total = "1"
median = "3"
avg = "0.2"
regist = "2014/01/11 00:07"
update = "2014/01/27 00:01"

[[entries]]
no = "6"
name = "kngate"
title = "Cole-Do-D-SKA?"
size = "2993 KB"
addr = ["https://www.dropbox.com/s/8odmclx1p5rg05z/ColeDDS.zip"]
genre = "diSKA"
impr = "8"
total = "15"
median = "1"
avg = "1.87"
regist = "2014/01/11 00:14"
update = "2014/01/26 23:57"

[[entries]]
no = "7"
name = "435nm"
title = "Bad Apple!!(8bitMix)"
size = "840 KB"
addr = ["https://www.dropbox.com/s/4an21hn53p0j2we/Bad_Apple_8bit.rar"]
genre = "Arrange"
impr = "6"
total = "4"
median = "0"
avg = "0.66"
regist = "2014/01/11 00:18"
update = "2014/01/26 23:19"

[[entries]]
no = "8"
name = "suna"
title = "rainbow road"
size = "4844 KB"
addr = [
    "L Q  :",
    "https://www.dropbox.com/s/k4zxjf2rmqkgb4h/RR64L9.zip",
    "4844kb",
    "HQwav:",
    "https://www.dropbox.com/s/ud5nou0vy1q12zo/RR64H9wav.zip",
    "62562kb",
    "HQogg:",
    "https://www.dropbox.com/s/sflrdsl2c49qujy/RR64H9ogg.zip",
    "13745kb",
]
genre = "game music"
impr = "6"
total = "6"
median = "2"
avg = "1"
regist = "2014/01/11 01:25"
update = "2014/01/26 23:59"

[[entries]]
no = "9"
name = "nob undestructed"
title = "Distorted Mind (for collapsed Mix)"
size = "4769 KB"
addr = [
    "http://scytheleg.sakura.ne.jp/tempyou/bms/bms/",
    "[nob]distortedmind_lq.rar",
]
genre = "BREAKCORE"
impr = "8"
total = "15"
median = "1"
avg = "1.87"
regist = "2014/01/11 02:18"
update = "2014/01/27 00:42"

[[entries]]
no = "10"
name = "Lapsa (fkRadish×Lasque)"
title = "District:Distrust"
size = "737 KB"
addr = [
    "http://nekokan.dyndns.info/~anonymous/bms/fuki1755/dd_lq.rar",
    "(LQ : 737KB)",
    "http://nekokan.dyndns.info/~anonymous/bms/fuki1755/dd_hq.rar",
    "(HQ : 3637KB)",
]
genre = "Artcore"
impr = "11"
total = "33"
median = "0"
avg = "3"
regist = "2014/01/11 20:10"
update = "2020/02/13 22:14"

[[entries]]
no = "11"
name = "t-soach"
title = "マチイス"
size = "1964 KB"
addr = ["https://dl.dropbox.com/u/34278850/machiis_LQ.lzh"]
genre = "electronica"
impr = "5"
total = "8"
median = "0"
avg = "1.6"
regist = "2014/01/12 04:06"
update = "2014/01/26 23:46"

[[entries]]
no = "12"
name = "かにかまとむーくん"
title = "うんこそんぐ にせんじゅうよん"
size = "2181 KB"
addr = ["https://www.dropbox.com/s/h28w8nn8298qdw2/unko2014_BGA.zip"]
genre = "はーど みにまる うんこ"
impr = "8"
total = "11"
median = "0"
avg = "1.37"
regist = "2014/01/13 01:34"
update = "2014/01/26 23:42"

[[entries]]
no = "13"
name = "ボテ旨 ぽふまろえ"
title = "放課後魔王"
size = "4380 KB"
addr = ["https://www.dropbox.com/s/7w5oxihlj9gvtwo/houkago.zip"]
genre = "GAME MUSIC"
impr = "11"
total = "20"
median = "0"
avg = "1.81"
regist = "2014/01/13 02:08"
update = "2014/01/26 23:44"

[[entries]]
no = "14"
name = "Sho Fish"
title = "Kompakt Loudness"
size = "3160 KB"
addr = ["http://www.mediafire.com/download/l045r2da8g8bywg/Sho+Fish+-+Kompakt+Loudness.zip"]
genre = "GABBER"
impr = "6"
total = "4"
median = "0"
avg = "0.66"
regist = "2014/01/13 06:17"
update = "2014/01/26 23:56"

[[entries]]
no = "15"
name = "秘密"
title = "Above the clouds"
size = "4653 KB"
addr = ["https://dl.dropboxusercontent.com/s/719rx2xre4wbrp1/Above%20the%20clouds.rar?dl=1&token_hash=AAFnxDNkC3W59yBC1YXJi7UAcCs9sUd5cF__ffZXGPQEjg"]
genre = "jungle"
impr = "5"
total = "4"
median = "0"
avg = "0.8"
regist = "2014/01/13 11:41"
update = "2014/01/26 22:52"

[[entries]]
no = "16"
name = "ume"
title = "Skyblue Heart"
size = "1400 KB"
addr = ["http://kie.nu/1BFC"]
genre = "98's House"
impr = "8"
total = "21"
median = "0.5"
avg = "2.62"
regist = "2014/01/13 11:47"
update = "2014/01/26 23:57"

[[entries]]
no = "17"
name = "kazuNOcobit"
title = "tunnel"
size = "550 KB"
addr = ["http://ux.getuploader.com/kazunoco/download/3/%5BkazuNOcobit%5Dtunnel.zip"]
genre = "Electronic"
impr = "15"
total = "34"
median = "1"
avg = "2.26"
regist = "2014/01/13 16:45"
update = "2014/01/26 23:51"

[[entries]]
no = "18"
name = "Basso"
title = "Fatal Pulse"
size = "3765 KB"
addr = ["https://dl.dropboxusercontent.com/u/95913775/files/Fatal_Pulse.rar"]
genre = "FOOTWORK"
impr = "21"
total = "62"
median = "0"
avg = "2.95"
regist = "2014/01/13 17:57"
update = "2014/01/26 23:57"

[[entries]]
no = "19"
name = "dj KLAVIA"
title = "BeatriX"
size = "4950 KB"
addr = ["http://cineraria-studio.com/bms/klavia_beatrix.rar"]
genre = "OLDSKOOL RAVE"
impr = "14"
total = "32"
median = "0"
avg = "2.28"
regist = "2014/01/13 18:52"
update = "2014/01/26 23:54"

[[entries]]
no = "20"
name = "polysha"
title = "unconventional"
size = "1500 KB"
addr = [
    "https://dl.dropboxusercontent.com/s/6drj2tdv3kxk5pv/unconventional.zip?dl=1&token_hash=AAGKQV4lwgTx52Q4BNPs_z9nVdT1W6uBtGmI8tX-nQLchA",
    "(LQ)",
    "https://dl.dropboxusercontent.com/s/m3kvz5c3r8xgugf/Unconventional_LQ.zip?dl=1&token_hash=AAGdKOtMTSg7pxlqbcq1GPHLpIlk93nKdU_4eO0CnJ7OpA",
]
genre = "POWERSTOMP"
impr = "7"
total = "9"
median = "2"
avg = "1.28"
regist = "2014/01/13 20:23"
update = "2014/01/26 22:39"

[[entries]]
no = "21"
name = "Juggle Second"
title = "Pirouette"
size = "2148 KB"
addr = ["-"]
genre = "NU STEP"
impr = "6"
total = "15"
median = "0.5"
avg = "2.5"
regist = "2014/01/13 20:24"
update = "2014/11/28 23:54"

[[entries]]
no = "22"
name = "Trish"
title = "XTC"
size = "3584 KB"
addr = [
    "(HQ_wav)",
    "https://www.dropbox.com/s/j0f89e44we3tcoa/Trish_XTC_HQ.zip",
    "(5MB版)",
    "https://www.dropbox.com/s/mqcojmohd17icnk/Trish_XTC.zip",
]
genre = "Juke/Footwork"
impr = "8"
total = "11"
median = "2"
avg = "1.37"
regist = "2014/01/13 20:56"
update = "2014/01/27 04:40"

[[entries]]
no = "23"
name = "MIX-MAX"
title = "This World Is Dead!"
size = "5118 KB"
addr = [
    "http://freett.com/mixmax412/deadworld.html",
    "(LQ: 5118KB , HQ+APPEND: 7777KB)",
    "ページ内の文字をクリックしてダウンロード",
]
genre = "TECHNO"
impr = "10"
total = "28"
median = "0"
avg = "2.8"
regist = "2014/01/13 22:15"
update = "2014/02/09 23:58"

[[entries]]
no = "24"
name = "Bit Upper"
title = "Happy Retro!"
size = "2490 KB"
addr = ["http://uprdeco.littlestar.jp/happyretro_mq.rar"]
genre = "HAPPY LABELCORE"
impr = "6"
total = "12"
median = "1.5"
avg = "2"
regist = "2014/01/13 22:39"
update = "2014/01/26 23:47"

[[entries]]
no = "25"
name = "Nitrix"
title = "Monkey Brain"
size = "3425 KB"
addr = ["http://page.freett.com/nitrix/letro_bms.html"]
genre = "JUMP UP / RAGGA JUNGLE"
impr = "8"
total = "19"
median = "0"
avg = "2.37"
regist = "2014/01/13 23:36"
update = "2014/01/26 23:50"

[[entries]]
no = "26"
name = "LU"
title = "From Finger to Brain,Stomach and Anus VIP"
size = "3535 KB"
addr = [
    "http://gensoukyousoukyoku.nekokan.dyndns.info/6-LU-From_Finger_to_Brain",
    ",Stomach_and_Anus_VIP.rar",
]
genre = "JUMP UP MIX"
impr = "5"
total = "11"
median = "0"
avg = "2.2"
regist = "2014/01/13 23:56"
update = "2014/01/26 23:52"

[[entries]]
no = "27"
name = "CRUNCH"
title = "Alive"
size = "4410 KB"
addr = ["https://dl.dropboxusercontent.com/u/80495475/Alive.rar"]
genre = "NU PROG"
impr = "5"
total = "12"
median = "0"
avg = "2.4"
regist = "2014/01/13 23:58"
update = "2014/01/26 23:56"
