[[entries]]
no = "1"
name = "TexuilA"
title = "WILDSHOX!!"
size = "43392 KB"
addr = ["https://dl.dropboxusercontent.com/u/262853010/WILDSHOX_ogg.zip"]
genre = "JAG BREAK"
impr = "22"
total = "95"
median = "5"
avg = "4.31"
regist = "2014/02/01 00:02"
update = "2014/02/23 22:26"

[[entries]]
no = "2"
name = "Εσοπτρον"
title = "Απομνημονευμαι"
size = "52511 KB"
addr = ["http://copy.com/IO0k7KupPWku/Apomnhmoneumai.zip"]
genre = "αποφθεγμα"
impr = "25"
total = "105"
median = "4"
avg = "4.2"
regist = "2014/02/01 00:10"
update = "2014/02/23 23:59"

[[entries]]
no = "3"
name = "PSYCHO SYSTEM 響-HIBIKI-"
title = "Connected Dawn"
size = "21504 KB"
addr = ["http://www1.axfc.net/u/3160441"]
genre = "PSY TRANCE(MORNING)"
impr = "18"
total = "58"
median = "3"
avg = "3.22"
regist = "2014/02/01 00:13"
update = "2014/02/23 23:23"

[[entries]]
no = "4"
name = "schwarzekugel"
title = "卍-OVER Verzerrung"
size = "47709 KB"
addr = ["https://dl.dropboxusercontent.com/s/85ihh9phqgw57oi/wp3_schwarzekugel_xover.rar"]
genre = "HARD TECHNO / GABBA"
impr = "19"
total = "75"
median = "4"
avg = "3.94"
regist = "2014/02/01 00:13"
update = "2014/02/23 22:35"

[[entries]]
no = "5"
name = "渋垣茉理 / 橘ちひろ"
title = "Sunny☆girL"
size = "0 KB"
addr = ["http://dl.dropboxusercontent.com/u/86897153/sunny_girl.zip"]
genre = "Girl's Rock"
impr = "0"
total = "0"
median = "2.5"
avg = "2.7"
regist = "2014/02/01 00:17"
update = "2014/02/23 22:27"

[[entries]]
no = "6"
name = "Yuri. vs Rin."
title = "Collide Sound"
size = "45880 KB"
addr = [
    "wav 46MB",
    "https://www.dropbox.com/s/amt8sk7r496vyk2/YR_Collide%20Sound_wav.rar",
    "ogg 14mb",
    "https://www.dropbox.com/s/j39ocmeytvc96o4/YR_Collide%20Sound_ogg.rar",
]
genre = "Energetic Trance"
impr = "13"
total = "40"
median = "3"
avg = "3.07"
regist = "2014/02/01 00:44"
update = "2014/02/24 08:06"

[[entries]]
no = "7"
name = "Rolamet"
title = "【BGA追加】Painkiller"
size = "125373 KB"
addr = [
    "https://www.dropbox.com/s/d7otqh3szo0e0qv/Rolamet_Painkiller.rar",
    "https://www.dropbox.com/s/iobivdmznj814uf/painkiller_bga.mpg",
]
genre = "EDM"
impr = "17"
total = "62"
median = "3"
avg = "3.64"
regist = "2014/02/01 00:57"
update = "2014/02/24 00:32"

[[entries]]
no = "8"
name = "solitaire"
title = "On A Rainy Night"
size = "16560 KB"
addr = ["http://firestorage.jp/download/2e1912e5ffe030ab98397b89f2e74a509877a790"]
genre = "Drum & Bass"
impr = "18"
total = "64"
median = "4"
avg = "3.55"
regist = "2014/02/01 01:23"
update = "2014/02/23 23:42"

[[entries]]
no = "9"
name = "Astronaut K*"
title = "Sky Higher"
size = "15946 KB"
addr = ["http://kie.nu/1E7m"]
genre = "TranceCore"
impr = "13"
total = "39"
median = "3"
avg = "3"
regist = "2014/02/01 02:53"
update = "2014/02/23 22:53"

[[entries]]
no = "10"
name = "重巡洋艦 羽黒/BGA:長崎造船所"
title = "【BGA追加しました】BlackFeather"
size = "23648 KB"
addr = [
    "BGA同梱版です。",
    "https://docs.google.com/uc?id=0B97xj9Ow1Tu8VmR5eEZXSEFpNms&export=download",
    "BGAだけの追加は、こちらです。",
    "https://docs.google.com/uc?id=0B97xj9Ow1Tu8WmFva3lRYWtBME0&export=download",
]
genre = "Art/Breaks"
impr = "23"
total = "91"
median = "4"
avg = "3.95"
regist = "2014/02/01 03:54"
update = "2014/02/23 23:48"

[[entries]]
no = "11"
name = "TetraElemental"
title = "Ultimate Weapon"
size = "18260 KB"
addr = ["https://www.dropbox.com/s/oaoja6q5r3dsi1f/UltWpn_tetra.zip?dl=1"]
genre = "EMOTIONAL TRANCECORE"
impr = "25"
total = "107"
median = "4"
avg = "4.28"
regist = "2014/02/01 04:07"
update = "2016/08/20 16:03"

[[entries]]
no = "12"
name = "ハル×puia"
title = "死んであげない"
size = "25871 KB"
addr = [
    "http://docs.google.com/uc?id=0ByS9Wlo7KZbxTXhleFdocnZ2WDg&export=download",
    "（差分全部入り）",
]
genre = "TECHNO POP"
impr = "23"
total = "102"
median = "4"
avg = "4.43"
regist = "2014/02/01 08:48"
update = "2019/05/31 12:00"

[[entries]]
no = "13"
name = "SRK34"
title = "Electric Darkness"
size = "41900 KB"
addr = ["http://www1.axfc.net/u/3157692"]
genre = "Electro / Trance"
impr = "0"
total = "0"
median = "2"
avg = "2.4"
regist = "2014/02/01 11:08"
update = "2014/02/23 22:54"

[[entries]]
no = "14"
name = "Thous"
title = "Artificial destruction"
size = "10977 KB"
addr = ["http://docs.google.com/uc?id=0B_ACOCjd9IgBekNzRkJLelBtNE0"]
genre = "Hard Techno"
impr = "14"
total = "51"
median = "4"
avg = "3.64"
regist = "2014/02/01 15:22"
update = "2014/02/24 23:15"

[[entries]]
no = "15"
name = "young leaves"
title = "fregre -FRESH GREEN ENDLESS-"
size = "1230 KB"
addr = ["https://dl.dropboxusercontent.com/s/mx6uypbaq84yy2m/young_leaves-fregre-ogg.rar"]
genre = "Trancestep"
impr = "13"
total = "42"
median = "3"
avg = "3.23"
regist = "2014/02/01 15:34"
update = "2014/02/24 00:58"

[[entries]]
no = "16"
name = "鳥海改"
title = "Seabird"
size = "29286 KB"
addr = ["http://www1.axfc.net/u/3160245"]
genre = "HEAVY CRUISER HARDSTYLE"
impr = "21"
total = "65"
median = "3"
avg = "3.09"
regist = "2014/02/01 18:02"
update = "2014/02/23 23:50"

[[entries]]
no = "17"
name = "cinnaluv"
title = "A Lightless Star"
size = "3316 KB"
addr = ["http://www.yw-works.com/data/bm/%5Bcinnaluv%5Da_lightless_star.zip"]
genre = "TRANCE"
impr = "12"
total = "35"
median = "3"
avg = "2.91"
regist = "2014/02/01 22:42"
update = "2014/02/24 11:08"

[[entries]]
no = "18"
name = "豁後→蛹悶▼縺代ｉ繧後◆谿狗蕗諤晏ｿｵ"
title = "縺薙・豁後↓菴懆€・・縺・↑縺・€√≠繧九・縺ｯ雋縺ｮ豼€諠・□縺代□縲・"
size = "22723 KB"
addr = ["xxxxxxxxxxxxxxx"]
genre = "・ｿ蜻ｪ縺・・豁・"
impr = "17"
total = "51"
median = "3"
avg = "3"
regist = "2014/02/02 00:15"
update = "2014/02/24 00:17"

[[entries]]
no = "19"
name = "Trish"
title = "Blooming"
size = "40140 KB"
addr = [
    "https://www.dropbox.com/s/rruzl6g2v5x3fn3/Trish_Blooming_wav.zip",
    "ミラー",
    "http://firestorage.jp/download/f8860486fa307e4b572d1b528911ff34f794c381",
]
genre = "New Age"
impr = "33"
total = "161"
median = "5"
avg = "4.87"
regist = "2014/02/02 04:31"
update = "2014/06/15 01:16"

[[entries]]
no = "20"
name = "全日本Ninjaテニス協会"
title = "The Flame"
size = "42000 KB"
addr = [
    "http://firestorage.jp/download/0b98079ce416c4af6d98dc04e0b2c39a549f6cf4",
    "http://kie.nu/1EfI",
]
genre = "ELECTRO TRANCE"
impr = "19"
total = "73"
median = "4"
avg = "3.84"
regist = "2014/02/02 14:19"
update = "2014/02/23 23:52"

[[entries]]
no = "21"
name = "menue"
title = "past"
size = "18226 KB"
addr = ["http://firestorage.jp/download/6fefa91eba66306cc7d1085b30b839572fc0e207"]
genre = "Ambient"
impr = "15"
total = "53"
median = "3"
avg = "3.53"
regist = "2014/02/02 15:44"
update = "2014/02/24 00:24"

[[entries]]
no = "22"
name = "Tsukurillex"
title = "KieLek"
size = "25574 KB"
addr = ["http://kie.nu/1EhH"]
genre = "Brostep"
impr = "15"
total = "47"
median = "3"
avg = "3.13"
regist = "2014/02/02 16:18"
update = "2014/02/23 23:47"

[[entries]]
no = "23"
name = "Sound Crucible"
title = "散桜"
size = "42291 KB"
addr = ["http://www1.axfc.net/u/3161700"]
genre = "Ethnic"
impr = "14"
total = "49"
median = "4"
avg = "3.5"
regist = "2014/02/02 17:03"
update = "2014/02/23 23:48"

[[entries]]
no = "24"
name = "RU"
title = "Helium"
size = "6300 KB"
addr = ["http://ndk.nekokan.dyndns.info/wp3/8-RU-Helium.rar"]
genre = "DEEP DNB"
impr = "15"
total = "43"
avg = "2.86"
regist = "2014/02/02 19:24"
update = "2014/02/24 18:51"

[[entries]]
no = "25"
name = "Project TS"
title = "Pure Light"
size = "7900 KB"
addr = [
    "http://firestorage.jp/download/e90bd63f3a3201d31721f1d72ef51700d0c1a568",
    "http://www1.axfc.net/u/3161366",
    "(Mirror)",
]
genre = "UPLIFTING TRANCE"
impr = "13"
total = "35"
median = "3"
avg = "2.69"
regist = "2014/02/02 21:02"
update = "2015/12/19 20:51"

[[entries]]
no = "26"
name = "kyu8"
title = "birthmark"
size = "20000 KB"
addr = ["http://ndk.nekokan.dyndns.info/wp3/8-kyu8-birthmark.rar"]
genre = "JUMP UP"
impr = "21"
total = "81"
median = "4"
avg = "3.85"
regist = "2014/02/02 22:17"
update = "2014/02/23 23:49"

[[entries]]
no = "27"
name = "反社会デモクラシー"
title = "隠蔽リアルタワー"
size = "4680 KB"
addr = [
    "http://firestorage.jp/download/09a8b09419caabe8c8d07be208b53eaab5e370b5",
    "http://xfs.jp/ktwtQ9",
]
genre = "SHIJI ROCK"
impr = "16"
total = "47"
median = "3"
avg = "2.93"
regist = "2014/02/02 22:18"
update = "2014/02/24 02:39"

[[entries]]
no = "28"
name = "Die Under Shore"
title = "Valentine Breaker"
size = "43528 KB"
addr = [
    "wav:",
    "http://www1.axfc.net/u/3161701.zip",
    "ogg:",
    "http://www1.axfc.net/u/3161767.zip",
]
genre = "(Don't) Happy"
impr = "14"
total = "41"
avg = "2.92"
regist = "2014/02/02 23:31"
update = "2014/02/24 00:20"

[[entries]]
no = "29"
name = "dolphing"
title = "Blue Stream"
size = "5870 KB"
addr = ["http://www1.axfc.net/uploader/so/3161609"]
genre = "LIQUID FUNK"
impr = "12"
total = "37"
median = "3"
avg = "3.08"
regist = "2014/02/02 23:49"
update = "2014/02/24 22:20"

[[entries]]
no = "30"
name = "Brownie"
title = "Night..."
size = "2686 KB"
addr = ["http://1drv.ms/1ncy8n2"]
genre = "AMBIENT"
impr = "12"
total = "29"
median = "2.5"
avg = "2.41"
regist = "2014/02/02 23:51"
update = "2014/03/06 00:42"

[[entries]]
no = "31"
name = "赤城"
title = "to Firmament"
size = "16000 KB"
addr = ["http://www1.axfc.net/u/3161858?key=shidenkaini"]
genre = "エナジェテック"
impr = "13"
total = "45"
median = "4"
avg = "3.46"
regist = "2014/02/02 23:54"
update = "2014/02/23 23:51"

[[entries]]
no = "32"
name = "Wyno"
title = "Wired Wadge"
size = "13414 KB"
addr = [
    "http://firestorage.jp/download/a96f66b0600113833d83649386444b068d1e970b",
    "(本データ)",
    "http://firestorage.jp/download/fbee52b15ed28bb7dcc24291d321429b319ce5af",
    "(NH譜面差分)",
]
genre = "TECH TRANCE"
impr = "12"
total = "38"
median = "3"
avg = "3.16"
regist = "2014/02/02 23:58"
update = "2014/02/25 00:26"

[[entries]]
no = "33"
name = "+45"
title = "B e l i - R"
size = "35680 KB"
addr = ["http://www1.axfc.net/u/3161956"]
genre = "PSY-ANTHEM"
impr = "15"
total = "57"
median = "4"
avg = "3.8"
regist = "2014/02/02 23:59"
update = "2014/02/24 03:41"

[[entries]]
no = "34"
name = "Movement Point P"
title = "Crazy Casher"
size = "3000 KB"
addr = ["http://www1.axfc.net/u/3161642"]
genre = "techno"
impr = "0"
total = "0"
median = "3"
avg = "2.37"
regist = "2014/02/03 00:01"
update = "2014/03/20 04:12"
