[[entries]]
no = "1"
name = "TiS&KLAVIA"
title = "ICE SHOCK!!"
size = "15700 KB"
addr = ["http://cineraria-studio.com/bms/ice_shock.zip"]
genre = "SPEED RAVE"
impr = "8"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/01 00:00"
update = "2014/03/16 22:34"

[[entries]]
no = "2"
name = "litmus* as Ayano_quasar"
title = "Vermilion Breeze"
size = "9919 KB"
addr = ["https://drive.google.com/file/d/0B0a6-fXyD9ZEN1ducUxvZ0doc2M/view?usp=sharing"]
genre = "World / Electronica"
impr = "7"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/01 00:03"
update = "2015/11/12 18:37"

[[entries]]
no = "3"
name = "o.s.gate"
title = "逆サマ譜面のイデオロギー"
size = "5889 KB"
addr = ["https://www.dropbox.com/s/nk8484cjwbbs3rh/%E9%80%86%E6%A7%98%E9%82%AA.zip"]
genre = "Eroc Esrever"
impr = "9"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/01 00:03"
update = "2014/03/18 11:39"

[[entries]]
no = "4"
name = "ZUN remixed by bbangsami"
title = "Hyper Prismriver"
size = "72153 KB"
addr = [
    "http://dl.dropboxusercontent.com/u/23821865/bbangsami_fuente_Hyper_Prismriver.rar",
    "(mirror)",
    "http://www1.axfc.net/u/3182789.rar",
]
genre = "Touhou Orgel Core"
impr = "7"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/01 00:03"
update = "2014/03/17 21:31"

[[entries]]
no = "5"
name = "yoa"
title = "Library Rules"
size = "27927 KB"
addr = ["http://docs.google.com/uc?id=0ByS9Wlo7KZbxYUlONHJWRG5IQk0&export=download"]
genre = "LIQUIDFUNK MIX"
impr = "5"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/01 00:03"
update = "2014/03/17 09:49"

[[entries]]
no = "6"
name = "Ｆ／Ａ１８"
title = "天衣無縫"
size = "28700 KB"
addr = ["http://fa18af.sakura.ne.jp/"]
genre = "東方緋想天"
impr = "7"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/01 00:03"
update = "2014/03/17 19:25"

[[entries]]
no = "7"
name = "b-UMB"
title = "HH judgement"
size = "22600 KB"
addr = ["http://colorfulumbrella.sakura.ne.jp/bms/hhj.rar"]
genre = "MAINSTREAM HARDCORE"
impr = "5"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/01 00:06"
update = "2014/03/17 19:15"

[[entries]]
no = "8"
name = "average"
title = "Bad Apple!!"
size = "23023 KB"
addr = ["https://drive.google.com/open?id=1kyCae-MB9IOKS3Jb5nDU_vSYjY9Jd1uu"]
genre = "東方幻想郷"
impr = "6"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/01 00:08"
update = "2019/02/06 09:32"

[[entries]]
no = "9"
name = "アクジ"
title = "VENGENCE SPARK"
size = "7000 KB"
addr = ["http://kie.nu/1Ida"]
genre = "HARDCORE MIX"
impr = "3"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/01 00:10"
update = "2014/03/17 19:34"

[[entries]]
no = "10"
name = "Ｆ／Ａ１８"
title = "テーレッテー妖恋談"
size = "17000 KB"
addr = ["http://fa18af.sakura.ne.jp/"]
genre = "東方非想天則"
impr = "4"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/01 00:12"
update = "2014/03/17 20:45"

[[entries]]
no = "11"
name = "out rage"
title = "ragnarok the clock"
size = "5400 KB"
addr = ["http://ux.getuploader.com/zaqlo_bms/download/3/clock_wav.rar"]
genre = "SPEED GABBA"
impr = "3"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/01 00:14"
update = "2014/03/17 20:56"

[[entries]]
no = "12"
name = "435nm/BGA:雪餅*なちまろ"
title = "Rompere Moon"
size = "77590 KB"
addr = ["https://www.dropbox.com/s/iwxyxtbv4yh66am/Rompere%20Moon.rar?dl=0"]
genre = "Breakbeats Trance"
impr = "3"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/01 00:15"
update = "2015/07/07 20:44"

[[entries]]
no = "13"
name = "EBIMAYO"
title = "2Rock"
size = "36454 KB"
addr = ["https://dl.dropboxusercontent.com/s/ocfty9xcckkhx77/2Rock.zip?dl=1&token_hash=AAGZKbN2mSJKS1AZt5SWvOPeQKc9wXT6-HkzZbokHFHMXA"]
genre = "Breakbeats"
impr = "6"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/01 00:46"
update = "2014/03/17 22:58"

[[entries]]
no = "14"
name = "uet vs Neun_jack"
title = "U.F.O."
size = "54580 KB"
addr = [
    "https://dl.dropboxusercontent.com/u/60346274/Neunjack/uet_vs_Neun_jack_mov_RoaringFlame_ufo_ogg.rar",
    "https://copy.com/hcfwNE0oETAr/uet_vs_Neun_jack_mov_RoaringFlame_ufo_ogg.rar",
]
genre = "FREEFORM HARDCORE"
impr = "5"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/01 01:56"
update = "2014/03/21 02:15"

[[entries]]
no = "15"
name = "Aiel Eltlinde"
title = "Starrise midnight"
size = "42722 KB"
addr = [
    "https://dl.dropboxusercontent.com/s/d53cijxq90eyg38/ae_srmn.zip?dl=1&token_hash=AAE7G4tDRb7_ZWrrOCOJNotkvaTWFdLr9SowIEhmmGK9aQ",
    "(Dropbox)",
    "https://drive.google.com/uc?export=download&confirm=iL0j&id=0B9c0ec4cGUpFVmU2aWJfc3ppalU",
    "(GoogleDrive) (Mirror)",
]
genre = "jazzin dance"
impr = "5"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/02 01:58"
update = "2014/03/17 21:39"

[[entries]]
no = "16"
name = "nmk feat.かなえゆめ"
title = "繋いで！Miracle☆Wish"
size = "82831 KB"
addr = ["https://docs.google.com/uc?export=download&confirm=dVmZ&id=0B97xj9Ow1Tu8NGFFVkNrOVRxVkk"]
genre = "EUROBEAT"
impr = "6"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/02 02:46"
update = "2014/03/17 21:45"

[[entries]]
no = "17"
name = "RYO-K"
title = "遠い春を告げるあの娘の足音"
size = "7412 KB"
addr = ["https://www.dropbox.com/s/gqp2vy3dml2a38p/%E3%80%90RYO-K%E3%80%91%E9%81%A0%E3%81%84%E6%98%A5%E3%82%92%E5%91%8A%E3%81%92%E3%82%8B%E3%81%82%E3%81%AE%E5%A8%98%E3%81%AE%E8%B6%B3%E9%9F%B3.zip"]
genre = "Elec-Chill Out"
impr = "4"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/02 03:03"
update = "2014/03/18 02:48"

[[entries]]
no = "18"
name = "polysha"
title = """It's "alice" dream"""
size = "7880 KB"
addr = ["https://www.dropbox.com/s/j7nocksf0h067r6/%5Bpolysha%5D%20Itsalicedream.zip"]
genre = "HARDCORE"
impr = "7"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/02 03:16"
update = "2014/03/17 23:59"

[[entries]]
no = "19"
name = "er"
title = "死霊の夜桜 - er edit"
size = "12404 KB"
addr = ["https://dl.dropboxusercontent.com/u/28765267/er_yozakura.zip"]
genre = "ARRANGE"
impr = "5"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/02 05:48"
update = "2015/10/25 08:52"

[[entries]]
no = "20"
name = "average"
title = "古明地姉妹のカノン"
size = "53619 KB"
addr = ["https://drive.google.com/open?id=16uRnt6vqzvVM5SDznIEaJX-euP_PwGuY"]
genre = "Canon in C"
impr = "5"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/02 20:08"
update = "2019/02/06 09:31"

[[entries]]
no = "21"
name = "urimu"
title = "Bicolor Spirit"
size = "39000 KB"
addr = ["https://dl.dropboxusercontent.com/u/87285618/Bicolor%20Spirit_ogg.zip"]
genre = "HARD TRANCE"
impr = "7"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/02 22:46"
update = "2014/03/17 22:15"

[[entries]]
no = "22"
name = "P4koo"
title = "INFINITE BEATS"
size = "20787 KB"
addr = ["http://1drv.ms/1cmxZfN"]
genre = "Touhou Arrange"
impr = "4"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/03 12:03"
update = "2014/03/17 22:21"

[[entries]]
no = "23"
name = "nmk vs. b-UMB"
title = "Emotional Breaker"
size = "59567 KB"
addr = ["https://docs.google.com/uc?export=download&confirm=kRaZ&id=0B97xj9Ow1Tu8aHNjRll4blYya1k"]
genre = "HARDCORE"
impr = "5"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/03 16:43"
update = "2014/03/17 23:43"

[[entries]]
no = "24"
name = "yosy"
title = "appp"
size = "73113 KB"
addr = ["http://www1.axfc.net/u/3186998"]
genre = "GAME MUSIC"
impr = "3"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/05 17:03"
update = "2014/03/17 22:31"

[[entries]]
no = "25"
name = "A.S-Leaf"
title = "Sphere"
size = "163840 KB"
addr = [
    "(BGA有)",
    "https://www.dropbox.com/s/mocfqxh5cthbfuo/%5B%E6%9D%B1%E6%96%B9%E9%9F%B3%E5%BC%BE%E9%81%8A%E6%88%AF6%5DSphere%5B%E8%81%96%E5%BE%B3%E4%BC%9D%E8%AA%AC%5D.zip",
    "(BGA無)",
    "https://www.dropbox.com/s/iisoupdpo12me3u/%5B%E6%9D%B1%E6%96%B9%E9%9F%B3%E5%BC%BE%E9%81%8A%E6%88%AF6%5DSphere-nomovie.ver%5B%E8%81%96%E5%BE%B3%E4%BC%9D%E8%AA%AC%5D.zip",
]
genre = "DRUM'N'BASS"
impr = "4"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/05 20:06"
update = "2014/03/17 22:38"

[[entries]]
no = "26"
name = "toro"
title = "NEDE"
size = "22738 KB"
addr = ["https://dl.dropbox.com/s/w97v9rweqdowqad/NEDE-toro.zip"]
genre = "Energetic Trance"
impr = "4"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/07 00:46"
update = "2014/03/17 22:45"

[[entries]]
no = "27"
name = "A.S-Leaf"
title = "AKATSUKI"
size = "107520 KB"
addr = ["https://www.dropbox.com/s/42ei78tg5u7r91g/%5B%E6%9D%B1%E6%96%B9%E9%9F%B3%E5%BC%BE%E9%81%8A%E6%88%AF6%5DAKATSUKI%5B%E6%87%90%E3%81%8B%E3%81%97%E3%81%8D%E6%9D%B1%E6%96%B9%E3%81%AE%E8%A1%80%5D.zip"]
genre = "TRANCE"
impr = "2"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/07 22:53"
update = "2014/03/17 22:51"

[[entries]]
no = "28"
name = "oni56shi"
title = "Ogre Killer"
size = "58880 KB"
addr = ["https://dl.dropboxusercontent.com/u/38466798/Ogre%20Killer.zip"]
genre = "CROSSBREED"
impr = "5"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/07 23:28"
update = "2014/03/17 23:22"

[[entries]]
no = "29"
name = "ZUN remixed by daph"
title = "Drive 100"
size = "52862 KB"
addr = ["https://dl.dropboxusercontent.com/u/75920885/%5Bdaph%5DDrive_100.zip"]
genre = "Drum'n'Bass / Chiptune"
impr = "5"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/08 22:56"
update = "2014/03/17 23:52"

[[entries]]
no = "30"
name = "sa10"
title = "Sling Beat"
size = "23316 KB"
addr = ["http://nekokan.dyndns.info/~lobsak/bms/slingbeat_ogg.zip"]
genre = "Glitch Hop/EDM"
impr = "4"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/09 00:27"
update = "2014/03/17 23:07"

[[entries]]
no = "31"
name = "奏"
title = "夢違十字軍"
size = "247808 KB"
addr = ["https://dl.dropboxusercontent.com/u/107679068/crusader.rar"]
genre = "秘封輪舞曲"
impr = "5"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/09 00:55"
update = "2014/03/17 23:13"

[[entries]]
no = "32"
name = "HALLPBESTUDIO"
title = "Nice to Nine"
size = "3071 KB"
addr = ["http://ux.getuploader.com/hallpbestudio/download/22/Nice+to+Nine%5BHALLPBESTUDIO%5D.zip"]
genre = "ROTTERDAM TECHNO"
impr = "5"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/09 13:51"
update = "2014/03/17 23:17"

[[entries]]
no = "33"
name = "紅梔子 composed by TiS"
title = "約束-romantic children-"
size = "18800 KB"
addr = ["http://cineraria-studio.com/bms/tis_yakusoku_rc.zip"]
genre = "DRUM'N ROCK"
impr = "5"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/11 01:15"
update = "2014/03/17 23:22"

[[entries]]
no = "34"
name = "sa10"
title = "rebeltraitor"
size = "10311 KB"
addr = ["http://nekokan.dyndns.info/~lobsak/bms/rebeltraitor_ogg.zip"]
genre = "SPEED DANCE"
impr = "3"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/11 23:24"
update = "2014/03/16 16:27"

[[entries]]
no = "35"
name = "U-hey"
title = "Wind God Fist"
size = "10500 KB"
addr = ["https://www.dropbox.com/s/wkdcaaqiov29zmf/Wind%20God%20Fist.zip"]
genre = "HARD AYA"
impr = "3"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/12 18:34"
update = "2014/03/17 23:30"

[[entries]]
no = "36"
name = "er"
title = "年中夢中な好奇心"
size = "11243 KB"
addr = ["https://dl.dropboxusercontent.com/u/28765267/er_kouki.zip"]
genre = "やるきファンク"
impr = "6"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/12 22:57"
update = "2015/10/25 08:52"

[[entries]]
no = "37"
name = "Ark-Z"
title = "Singing of Night birds"
size = "34666 KB"
addr = ["http://sparrows-nest.net/~mmaki/singing.zip"]
genre = "Hard Mystic"
impr = "3"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/13 04:42"
update = "2014/03/17 03:27"

[[entries]]
no = "38"
name = "H.J.Nue"
title = "Hell Fire"
size = "97894 KB"
addr = ["https://copy.com/eqr9rQPCVjtR"]
genre = "INDUSTRIAL HARDCORE"
impr = "2"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/13 19:44"
update = "2014/03/17 23:53"

[[entries]]
no = "39"
name = "loz"
title = "Alice Color"
size = "48615 KB"
addr = ["http://1drv.ms/1fuTbL1"]
genre = "HARDCORE"
impr = "3"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/14 09:06"
update = "2014/03/16 10:57"

[[entries]]
no = "40"
name = "REX"
title = "Scarlet Double Dance"
size = "74000 KB"
addr = ["https://www.dropbox.com/s/uc7aljucvvtccw6/Scarlet%20Double%20Dance.lzh"]
genre = "DOUBLE ARRANGE"
impr = "5"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/15 00:45"
update = "2014/03/17 23:33"

[[entries]]
no = "41"
name = "siqlo"
title = "Acid Icicle"
size = "7995 KB"
addr = [
    "[wav]",
    "https://www.dropbox.com/s/ss31fjdbs24c5j2/siqlo%20-%20Acid%20Icicle%5Bwav%5D.zip",
    "[ogg]",
    "https://www.dropbox.com/s/bb0tx3dob3rb7b3/siqlo%20-%20Acid%20Icicle%5Bogg%5D.zip",
]
genre = "HARDCORE"
impr = "3"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/15 09:00"
update = "2014/03/17 23:52"

[[entries]]
no = "42"
name = "shio"
title = "Qronostasis -GABBA vs. Speedcore mix-"
size = "9555 KB"
addr = ["https://www.dropbox.com/s/gq8f430jk0fp10o/Qronostasis.zip"]
genre = "Epic J-SPEED"
impr = "4"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/15 10:30"
update = "2014/03/17 23:57"

[[entries]]
no = "43"
name = "8-Run-A"
title = "Missing ERROR"
size = "1840 KB"
addr = ["http://www1.axfc.net/u/3194769"]
genre = "frenchcore"
impr = "3"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/15 17:08"
update = "2014/03/17 23:36"

[[entries]]
no = "44"
name = "nmk"
title = "sola"
size = "78372 KB"
addr = ["https://docs.google.com/uc?export=download&confirm=2fCw&id=0B97xj9Ow1Tu8Z0VnZVNhLTVWV1U"]
genre = "ArtCore"
impr = "4"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/16 01:13"
update = "2014/03/17 23:59"

[[entries]]
no = "45"
name = "54cm"
title = "wobbled sea-sickness"
size = "5840 KB"
addr = ["https://dl.dropboxusercontent.com/s/7ar04j63b6iyx6l/wobbled_sea-sickness_ogg.zip?dl=1&token_hash=AAHwduXgrCfeO8WV_5azfMD9lCEnvdPfPbgbF59ivH8N2A"]
genre = "ELECTRO"
impr = "1"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/16 03:23"
update = "2014/03/17 11:55"

[[entries]]
no = "46"
name = "Limstella"
title = "Altar of Ancient"
size = "19285 KB"
addr = ["https://www.dropbox.com/s/biy1mngjoa0ztxn/Altar_of_Ancient.zip"]
genre = "CINEMATIC"
impr = "2"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/16 08:56"
update = "2014/03/17 23:39"

[[entries]]
no = "47"
name = "sa10"
title = "VII"
size = "30803 KB"
addr = ["http://nekokan.dyndns.info/~lobsak/bms/VII_ogg.zip"]
genre = "TOUHOU ARRANGE"
impr = "4"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/16 16:47"
update = "2014/03/19 20:37"

[[entries]]
no = "48"
name = "ヴォストク"
title = "PRINЦESSA TUNDRA"
size = "15684 KB"
addr = ["http://harutori.yu-yake.com/bms.html"]
genre = "SIBERIAN TECHNO POP"
impr = "1"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/17 20:00"
update = "2014/03/17 23:11"

[[entries]]
no = "49"
name = "itaojirou"
title = "Chinese Tea"
size = "104000 KB"
addr = ["http://www1.axfc.net/u/3196949.zip"]
genre = "BUCHIAGE Trance"
impr = "0"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/17 23:50"
update = "2014/03/17 23:50"

[[entries]]
no = "50"
name = "MajesticPeriod"
title = "迷ヒ猫"
size = "9010 KB"
addr = ["http://www1.axfc.net/u/3196912/Orinrin"]
genre = "Ethnic Mixture Jig"
impr = "0"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/17 23:54"
update = "2014/03/17 23:55"

[[entries]]
no = "51"
name = "Ωμεγα"
title = "XCIX"
size = "19000 KB"
addr = ["https://dl.dropboxusercontent.com/u/69517401/022_%5B%CE%A9%CE%BC%CE%B5%CE%B3%CE%B1%5DXCIX.rar"]
genre = "ART"
impr = "0"
total = "--"
median = "--"
avg = "--"
regist = "2014/03/17 23:59"
update = "2014/03/17 23:59"
