[[entries]]
no = "1"
name = "daisan / zue-row /けろちゃんの臀部とゆっちゃんの尻尾"
team = "けろちゃんの臀部とゆっちゃんの尻尾"
title = "雪解け色フラワーズ"
size = "11 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1137.zip"]
genre = "Euphoric Artbreaks"
impr = "5"
total = "399"
median = "80"
avg = "79.8"
regist = "2014/05/26 00:53"
update = "2014/06/30 20:22"

[[entries]]
no = "2"
name = "NIKITA (movie : misokabocha) / けろちゃんの臀部とゆっちゃんの尻尾"
team = "けろちゃんの臀部とゆっちゃんの尻尾"
title = "夢、幻。"
size = "19 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1138.zip"]
genre = "SYMPHONIC BREAK BEATS"
impr = "4"
total = "336"
median = "85.5"
avg = "84"
regist = "2014/05/26 01:03"
update = "2014/06/30 20:30"

[[entries]]
no = "3"
name = "LeaF (movie : Optie) / Looker & Unity"
team = "Looker & Unity"
title = "Evanescent"
size = "15 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1139.zip"]
genre = "POST DRUM'N'BASS"
impr = "3"
total = "213"
median = "75"
avg = "71"
regist = "2014/05/26 01:10"
update = "2014/06/30 20:16"

[[entries]]
no = "4"
name = "Ino / Looker & Unity"
team = "Looker & Unity"
title = "White book"
size = "6 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1141.zip"]
genre = "MEMORY"
impr = "5"
total = "382"
median = "80"
avg = "76.4"
regist = "2014/05/26 01:17"
update = "2014/06/30 20:55"

[[entries]]
no = "5"
name = "cybermiso / 優ちゃんと春香"
team = "優ちゃんと春香"
title = "burned down the ghost house and escaped spooks"
size = "10 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1142.zip"]
genre = "GLITCH HOP"
impr = "5"
total = "407"
median = "82"
avg = "81.4"
regist = "2014/05/26 01:25"
update = "2014/06/30 23:21"

[[entries]]
no = "6"
name = "p_d (movie : ふりっと★) / 優ちゃんと春香"
team = "優ちゃんと春香"
title = "Dandelion Sparkle!!"
size = "16 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1143.zip"]
genre = "SPRING CORE"
impr = "5"
total = "410"
median = "85"
avg = "82"
regist = "2014/05/26 01:31"
update = "2014/06/30 22:33"

[[entries]]
no = "7"
name = "ぜらにも / Lilium & Rosa"
team = "Hortus Conclusus"
title = "Decolora"
size = "9 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1144.zip"]
genre = "Postclassical"
impr = "3"
total = "243"
median = "80"
avg = "81"
regist = "2014/05/26 01:36"
update = "2014/06/30 20:19"

[[entries]]
no = "8"
name = "Forced Leaving(a.k.a.RYO-K) (movie : NI-X2)Hardcore Rave / Lilium & Rosa"
team = "Hortus Conclusus"
title = "Fascinating Laser"
size = "16 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1145.zip"]
genre = "Hardcore Rave"
impr = "4"
total = "322"
median = "81"
avg = "80.5"
regist = "2014/05/26 01:39"
update = "2014/06/30 22:34"

[[entries]]
no = "9"
name = "REX / 弘法の二本目の筆"
team = "弘法の二本目の筆"
title = "FLOATED CALM -BMS Edition-"
size = "47 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1146.zip"]
genre = "PACAPACA PASSION"
impr = "6"
total = "507"
median = "88.5"
avg = "84.5"
regist = "2014/05/26 03:09"
update = "2014/06/30 20:24"

[[entries]]
no = "10"
name = "q/stol ft. rebecca/obj:ゆゆゆ！vsDJ YUU"
team = "DPBMS差分作成初心者が物申す！"
title = "蓄積×フラストレーション"
size = "50 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1147.zip"]
genre = "J-ROCK"
impr = "4"
total = "277"
median = "72.5"
avg = "69.25"
regist = "2014/05/26 09:04"
update = "2014/06/30 20:05"

[[entries]]
no = "11"
name = "REX obj:ゆゆゆ！vsDJ YUU"
team = "DPBMS差分作成初心者が物申す！"
title = "FLOATED CALM -BMS Edition-"
size = "50 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1148.zip"]
genre = "PACAPACA PASSION"
impr = "4"
total = "304"
median = "76.5"
avg = "76"
regist = "2014/05/26 09:17"
update = "2014/06/30 22:35"

[[entries]]
no = "12"
name = "ume / obj:LvsZ"
team = "じゃがいもパン"
title = "Good beginning"
size = "10 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1150.zip"]
genre = "Electro pop"
impr = "3"
total = "205"
median = "75"
avg = "68.33"
regist = "2014/05/26 23:27"
update = "2014/06/30 22:36"

[[entries]]
no = "13"
name = "Arranged by Y.W (movie : kotomi) / obj:LvsZ"
team = "じゃがいもパン"
title = "Rainbowful Gates"
size = "9 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1151.zip"]
genre = "HOUSE POP"
impr = "3"
total = "189"
median = "69"
avg = "63"
regist = "2014/05/26 23:40"
update = "2014/06/30 22:36"

[[entries]]
no = "14"
name = "L.K. / obj:TK&FM"
team = "酩酊兄弟"
title = "Lumos (BMS Edit)"
size = "6 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1152.zip"]
genre = "2 Step / Chill Out"
impr = "5"
total = "383"
median = "83"
avg = "76.6"
regist = "2014/05/27 01:00"
update = "2014/07/01 23:33"

[[entries]]
no = "15"
name = "awi / obj:TK&FM"
team = "酩酊兄弟"
title = "HELLO"
size = "15 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1153.zip"]
genre = "TECHNO"
impr = "5"
total = "338"
median = "73"
avg = "67.6"
regist = "2014/05/27 01:01"
update = "2014/07/01 23:31"

[[entries]]
no = "16"
name = "くるぶっこちゃん / Love & Pain"
team = "Love & Pain"
title = "Rainy City(What did you say?)"
size = "10 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1155.zip"]
genre = "Instrumental"
impr = "3"
total = "217"
median = "75"
avg = "72.33"
regist = "2014/05/27 21:46"
update = "2014/06/30 22:37"

[[entries]]
no = "17"
name = "Ujico* / To7 (movie : To7) / Love & Pain"
team = "Love & Pain"
title = "MagicCity"
size = "12 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1156.zip"]
genre = "Fantasic Fusion"
impr = "3"
total = "199"
median = "65"
avg = "66.33"
regist = "2014/05/27 21:49"
update = "2014/06/30 22:37"

[[entries]]
no = "18"
name = "L.K. obj:ザイルvsゆゆゆ！"
team = "δ難易度表vsごった煮難易度表"
title = "Lumos (BMS Edit)"
size = "50 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1157.zip"]
genre = "2 Step / Chill Out"
impr = "2"
total = "168"
median = "84"
avg = "84"
regist = "2014/05/27 23:29"
update = "2014/06/30 22:37"

[[entries]]
no = "19"
name = "くるぶっこちゃん obj:ゆゆゆ！vsザイル"
team = "δ難易度表vsごった煮難易度表"
title = "Rainy City(What did you say?)"
size = "50 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1158.zip"]
genre = "Instrumental"
impr = "3"
total = "233"
median = "80"
avg = "77.66"
regist = "2014/05/27 23:42"
update = "2014/06/30 22:38"

[[entries]]
no = "20"
name = "○△□ obj:雷と電"
team = "第六駆逐隊"
title = "パズルボブルDS-BGM.01-"
size = "50 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1161.zip"]
genre = "GAME MUSIC"
impr = "4"
total = "306"
median = "76.5"
avg = "76.5"
regist = "2014/05/28 23:11"
update = "2014/06/30 22:38"

[[entries]]
no = "21"
name = "mommy obj:暁と響"
team = "第六駆逐隊"
title = "66A"
size = "50 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1159.zip"]
genre = "HOUSE"
impr = "5"
total = "340"
median = "70"
avg = "68"
regist = "2014/05/28 23:16"
update = "2014/06/30 20:09"

[[entries]]
no = "22"
name = "Richard Roe / o.c. + 、"
team = "ぼっち"
title = "Cancer cells"
size = "4 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1165.zip"]
genre = "ELEKTRONIKA"
impr = "4"
total = "313"
median = "84"
avg = "78.25"
regist = "2014/06/02 19:13"
update = "2014/06/30 23:44"

[[entries]]
no = "23"
name = "Est feat. 雪歌ユフ / obj:江ノ島次男vs江ノ島三男"
team = "江ノ島兄弟"
title = "Hello Hello"
size = "9 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1169.zip"]
genre = "ELEPOP"
impr = "4"
total = "307"
median = "83.5"
avg = "76.75"
regist = "2014/06/05 19:22"
update = "2014/06/30 22:40"

[[entries]]
no = "24"
name = "Ras / obj:江ノ島三男vs江ノ島次男"
team = "江ノ島兄弟"
title = "Blue Shock"
size = "9 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1170.zip"]
genre = "LIQUID FUNK"
impr = "5"
total = "418"
median = "95"
avg = "83.6"
regist = "2014/06/05 19:30"
update = "2014/06/30 20:31"

[[entries]]
no = "25"
name = "er/obj:元美月会長と楓次期副会長"
team = "美里西高校生徒会"
title = "Baby Baby Frenzy"
size = "191 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1172.zip"]
genre = "TECHNO POP"
impr = "5"
total = "399"
median = "90"
avg = "79.8"
regist = "2014/06/05 22:35"
update = "2014/06/30 22:42"

[[entries]]
no = "26"
name = "髭姫 feat. えみゅう。 /obj:元美月会長と楓次期副会長"
team = "美里西高校生徒会"
title = "貴女と秘密の…"
size = "677 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1173.zip"]
genre = "SECRET SONG"
impr = "5"
total = "410"
median = "80"
avg = "82"
regist = "2014/06/05 22:39"
update = "2014/06/30 20:32"

[[entries]]
no = "27"
name = "EBIMAYO / obj:hi-low & u2"
team = "利き手は逆でも利き恋人は同じ！"
title = "Into the Blue"
size = "168 KB"
addr = ["https://dl-web.dropbox.com/s/ze7ho2newmn50fm/IntotheBlue_hirouu2DP.zip"]
genre = "J-Core"
impr = "3"
total = "206"
median = "71"
avg = "68.66"
regist = "2014/06/08 00:59"
update = "2014/06/30 22:42"

[[entries]]
no = "28"
name = "er / obj:u2 & hi-low"
team = "利き手は逆でも利き恋人は同じ！"
title = "Baby Baby Frenzy"
size = "8 KB"
addr = ["https://dl-web.dropbox.com/s/p7nthhq52yvh7y6/_BabyFrenzy_dp_u2hirou.zip"]
genre = "TECHNO POP"
impr = "4"
total = "282"
median = "70"
avg = "70.5"
regist = "2014/06/08 01:00"
update = "2014/06/30 22:43"

[[entries]]
no = "29"
name = "NIKITA (movie : misokabocha) / コトネとしずくちゃん"
team = "コトネとしずくちゃん"
title = "夢、幻。"
size = "50 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1178.zip"]
genre = "SYMPHONIC BREAK BEATS"
impr = "5"
total = "371"
median = "78"
avg = "74.2"
regist = "2014/06/08 20:36"
update = "2014/06/30 22:43"

[[entries]]
no = "30"
name = "polysha (movie : zue-row) / コトネとしずくちゃん"
team = "コトネとしずくちゃん"
title = "Castor(BMS Edit)"
size = "40 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1179.zip"]
genre = "TRANCE"
impr = "4"
total = "353"
median = "86.5"
avg = "88.25"
regist = "2014/06/08 20:38"
update = "2014/06/30 20:34"

[[entries]]
no = "31"
name = "CRUNCH / obj: u2 & hzr"
team = "うどん vs そば"
title = "SAMBA TRANCE!!"
size = "8 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1188.zip"]
genre = "SAMBA TRANCE"
impr = "5"
total = "428"
median = "90"
avg = "85.6"
regist = "2014/06/09 00:21"
update = "2014/06/30 22:43"

[[entries]]
no = "32"
name = "er / note: hzr & u2"
team = "うどん vs そば"
title = "Baby Baby Frenzy"
size = "10 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1187.zip"]
genre = "TECHNO POP"
impr = "3"
total = "237"
median = "72"
avg = "79"
regist = "2014/06/09 00:22"
update = "2014/06/30 22:44"

[[entries]]
no = "33"
name = "itaojirou / ゆ～兎 vs 檻"
team = "Rabbit Cage"
title = "Imperial Strike"
size = "9 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1192.zip"]
genre = "happy hardcore"
impr = "3"
total = "242"
median = "82"
avg = "80.66"
regist = "2014/06/10 00:24"
update = "2014/06/30 22:44"

[[entries]]
no = "34"
name = "er / ゆ～兎 vs 檻"
team = "Rabbit Cage"
title = "Baby Baby Frenzy"
size = "11 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1193.zip"]
genre = "TECHNO POP"
impr = "5"
total = "395"
median = "85"
avg = "79"
regist = "2014/06/10 00:26"
update = "2014/06/30 22:44"

[[entries]]
no = "35"
name = "daisan / zue-row / ゆずと澄と理奈"
team = "なのじゃ！"
title = "雪解け色フラワーズ"
size = "30 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1196.zip"]
genre = "Euphoric Artbreaks"
impr = "4"
total = "319"
median = "91"
avg = "79.75"
regist = "2014/06/15 11:43"
update = "2014/06/30 20:37"

[[entries]]
no = "36"
name = "nmk / ゆずと澄と理奈"
team = "なのじゃ！"
title = "Syogun"
size = "19 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1197.zip"]
genre = "戦國EUROBEAT"
impr = "4"
total = "293"
median = "74.5"
avg = "73.25"
regist = "2014/06/15 11:45"
update = "2014/06/30 20:37"

[[entries]]
no = "37"
name = "Thefur Celtridorn / obj:馬 vs 鹿"
team = "CRAZY ANIMALS"
title = "ねこせっくす！"
size = "5 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1198.zip"]
genre = "HYPER TRENDING SPEED SEX"
impr = "7"
total = "270"
median = "30"
avg = "38.57"
regist = "2014/06/15 17:59"
update = "2014/06/30 20:40"

[[entries]]
no = "38"
name = "髭姫 feat. えみゅう。 obj:ユキとタツキ"
team = "★SWEET BITTER★"
title = "貴女と秘密の…"
size = "10 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1202.zip"]
genre = "SECRET SONG"
impr = "3"
total = "205"
median = "70"
avg = "68.33"
regist = "2014/06/15 19:37"
update = "2014/06/30 00:49"

[[entries]]
no = "39"
name = "ume obj:ユキとタツキ"
team = "★SWEET BITTER★"
title = "Good beginning"
size = "10 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1201.zip"]
genre = "Electro pop"
impr = "1"
total = "67"
median = "67"
avg = "67"
regist = "2014/06/15 19:43"
update = "2014/06/30 22:45"

[[entries]]
no = "40"
name = "ぜらにも obj:海馬瀬人と四糸乃"
team = "海馬ランド四糸乃支店"
title = "Decolora"
size = "26 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1199.zip"]
genre = "Postclassical"
impr = "3"
total = "230"
median = "75"
avg = "76.66"
regist = "2014/06/15 19:54"
update = "2014/06/30 20:40"

[[entries]]
no = "41"
name = "Est feat. 雪歌ユフ obj:四糸乃と海馬瀬人"
team = "海馬ランド四糸乃支店"
title = "Hello Hello"
size = "25 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1200.zip"]
genre = "ELEPOP"
impr = "4"
total = "293"
median = "72.5"
avg = "73.25"
regist = "2014/06/15 20:03"
update = "2014/06/30 20:41"

[[entries]]
no = "42"
name = "siqlo obj:老師vs司令官"
team = "老師と司令官"
title = "Cielo azul"
size = "10 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1206.zip"]
genre = "Trance"
impr = "5"
total = "384"
median = "85"
avg = "76.8"
regist = "2014/06/15 21:04"
update = "2014/06/30 23:30"

[[entries]]
no = "43"
name = "Q-Kys obj:老師vs司令官"
team = "老師と司令官"
title = "Last Mission"
size = "10 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1205.zip"]
genre = "Electro"
impr = "3"
total = "206"
median = "68"
avg = "68.66"
regist = "2014/06/15 21:11"
update = "2014/06/30 23:34"

[[entries]]
no = "44"
name = "Figure Four obj:派遣の人とバイトの人"
team = "即席野郎Dチーム"
title = "A.C.I.D. (Sengoku Mix)"
size = "40 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1209.zip"]
genre = "ACID HOUSE"
impr = "5"
total = "345"
median = "70"
avg = "69"
regist = "2014/06/15 21:40"
update = "2014/06/30 23:47"

[[entries]]
no = "45"
name = "8 to 7 feat.Zero-Infinity obj:派遣の人とバイトの人"
team = "即席野郎Dチーム"
title = "lack(and imperfect nerve)"
size = "40 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1207.zip"]
genre = "POSTROCK / POETRY READING"
impr = "4"
total = "238"
median = "62.5"
avg = "59.5"
regist = "2014/06/15 21:43"
update = "2014/06/30 23:51"

[[entries]]
no = "46"
name = "Est feat. 雪歌ユフ / obj:2y vs 225"
team = "きのこたけのこ戦争中立派"
title = "Hello Hello"
size = "24 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1210.zip"]
genre = "ELEPOP"
impr = "4"
total = "308"
median = "83.5"
avg = "77"
regist = "2014/06/15 22:26"
update = "2014/06/30 23:46"

[[entries]]
no = "47"
name = "OXYGEN / obj:2y vs 225"
team = "きのこたけのこ戦争中立派"
title = "CARTOOOOON CIRCLE"
size = "11 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1211.zip"]
genre = "BEATS"
impr = "4"
total = "325"
median = "82.5"
avg = "81.25"
regist = "2014/06/15 22:26"
update = "2014/06/30 22:46"

[[entries]]
no = "48"
name = "er obj:筆と桶と野菜"
team = "筆と桶と野菜"
title = "Baby Baby Frenzy"
size = "10 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1212.zip.html"]
genre = "TECHNO POP"
impr = "2"
total = "165"
median = "82.5"
avg = "82.5"
regist = "2014/06/15 23:21"
update = "2014/06/30 20:42"

[[entries]]
no = "49"
name = "Centain obj:筆と桶と野菜"
team = "筆と桶と野菜"
title = "Skywalk"
size = "15 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1213.zip.html"]
genre = "House"
impr = "4"
total = "318"
median = "80"
avg = "79.5"
regist = "2014/06/15 23:32"
update = "2014/06/30 20:43"

[[entries]]
no = "50"
name = "RearDawn(mov:zue-row) / obj: 634kとt.t.とおるさん"
team = "スミダ部長"
title = "Objection to the vortex"
size = "21 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1216.rar"]
genre = "BIG BEAT"
impr = "4"
total = "333"
median = "83"
avg = "83.25"
regist = "2014/06/15 23:52"
update = "2014/07/01 18:34"

[[entries]]
no = "51"
name = "daph + Klavistr (Renovamen) (movie : 篠乃ちよ) / k vs ゆ～兎"
team = "あ！"
title = "Luminarie"
size = "10 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1214.zip"]
genre = "Anthem Trance"
impr = "4"
total = "362"
median = "91"
avg = "90.5"
regist = "2014/06/15 23:53"
update = "2014/06/30 22:47"

[[entries]]
no = "52"
name = "Yosk! / k vs ゆ～兎"
team = "あ！"
title = "Cirrus Resort"
size = "14 KB"
addr = ["http://www42.tok2.com/home/dpbms/cgi-bin/uploader/src/dpbms_1215.zip"]
genre = "DREAM"
impr = "4"
total = "350"
median = "85"
avg = "87.5"
regist = "2014/06/15 23:53"
update = "2014/06/30 22:47"
