[[entries]]
no = "1"
name = "asahi3"
title = "3amba cat [5keys]"
size = "1376 KB"
addr = ["http://dl.dropboxusercontent.com/s/rv6nas68ccd174c/%5Basahi3%5D3amba_cat_5keys.rar"]
genre = "GAME MUSIC SAMBA"
impr = "52"
total = "206"
median = "4"
avg = "3.96"
regist = "2014/07/19 00:01"
update = "2014/08/16 19:33"

[[entries]]
no = "2"
name = "dm R2"
title = "B.B.K.K.B.K.K.-ReR2mix-"
size = "80000 KB"
addr = ["http://1drv.ms/1sxIHpJ"]
genre = "HARDCORE"
impr = "40"
total = "115"
median = "3"
avg = "2.87"
regist = "2014/07/19 00:02"
update = "2014/08/11 00:26"

[[entries]]
no = "3"
name = "アクジ"
title = "BAD NEWS"
size = "3008 KB"
addr = ["https://dl.dropboxusercontent.com/u/272956039/BAD%20NEWS.zip"]
genre = "Nu-Style GABBA"
impr = "71"
total = "310"
median = "4"
avg = "4.36"
regist = "2014/07/19 00:05"
update = "2014/10/20 10:38"

[[entries]]
no = "4"
name = "fumakura"
title = "DeglitcheR -Radio Edit-"
size = "22200 KB"
addr = ["https://dl.dropboxusercontent.com/u/119339721/deglitcher.zip"]
genre = "Uplifting Trance"
impr = "32"
total = "108"
median = "3"
avg = "3.37"
regist = "2014/07/19 00:11"
update = "2014/08/10 23:59"

[[entries]]
no = "5"
name = "LechE"
title = "翳月"
size = "46295 KB"
addr = ["https://www.dropbox.com/sh/zhfgbkt8vkg2opk/AABjzO2jc_jMjzZtCRMS2Hzfa"]
genre = "romantic"
impr = "33"
total = "99"
median = "3"
avg = "3"
regist = "2014/07/19 00:11"
update = "2014/08/10 23:59"

[[entries]]
no = "6"
name = "LiA"
title = "世界殺戮ブラッドローズ"
size = "12230 KB"
addr = [
    "wav版 (88,844KB)",
    "https://www.dropbox.com/s/3s3tfexvdsj8ne1/%5BLiA%5DBLOODROSE-wave.zip",
    "ogg版 (12,230KB)",
    "https://www.dropbox.com/s/bbip8598qvy2307/%5BLiA%5DBLOODROSE-ogg.zip",
]
genre = "HAPPY HARD GENOXIDE"
impr = "50"
total = "204"
median = "4"
avg = "4.08"
regist = "2014/07/19 00:14"
update = "2014/08/11 01:37"

[[entries]]
no = "7"
name = "Re:gats&"
title = "The Crepuscular Rays(BMS edit)"
size = "17427 KB"
addr = ["http://1drv.ms/1yBTeAV"]
genre = "Uplifting Trance"
impr = "34"
total = "125"
median = "4"
avg = "3.67"
regist = "2014/07/19 00:18"
update = "2017/05/30 23:34"

[[entries]]
no = "8"
name = "SMNX"
title = "central dogma"
size = "5830 KB"
addr = ["http://www1.axfc.net/u/3296217.rar"]
genre = "Strings Techno"
impr = "34"
total = "87"
median = "2"
avg = "2.55"
regist = "2014/07/19 00:22"
update = "2014/08/13 22:59"

[[entries]]
no = "9"
name = "黄泉路テヂーモ"
title = "エーデルワイス"
size = "55802 KB"
addr = ["http://docs.google.com/uc?id=0B6s6DlYD--zvNWQ3N18wbjg0X1k&export=download"]
genre = "echolocation"
impr = "76"
total = "369"
median = "5"
avg = "4.85"
regist = "2014/07/19 00:38"
update = "2014/08/11 16:37"

[[entries]]
no = "10"
name = "tc-taka"
title = "Autumn illusions"
size = "61852 KB"
addr = ["https://www.dropbox.com/s/pjsm8a91b5rrxbm/Autumn_illusions.zip"]
genre = "Trancecore"
impr = "42"
total = "186"
median = "4.5"
avg = "4.42"
regist = "2014/07/19 01:12"
update = "2014/08/16 19:40"

[[entries]]
no = "11"
name = "やくも"
title = 'System "C"'
size = "4581 KB"
addr = ["https://drive.google.com/file/d/0B3N7edSn9KBFTTdMbTI0RjE1ZjA/edit?usp=sharing"]
genre = "System"
impr = "34"
total = "91"
median = "3"
avg = "2.67"
regist = "2014/07/19 04:45"
update = "2014/08/10 23:07"

[[entries]]
no = "12"
name = "U-hey"
title = "The Festival Of Night"
size = "13445 KB"
addr = ["https://www.dropbox.com/s/mp5cktba481kgk3/The%20Festival%20Of%20Night.zip"]
genre = "HARD TRANCE"
impr = "41"
total = "147"
median = "4"
avg = "3.58"
regist = "2014/07/19 11:26"
update = "2014/08/10 23:08"

[[entries]]
no = "13"
name = "daph"
title = "Μαινάδη"
size = "22840 KB"
addr = ["https://dl.dropboxusercontent.com/u/75920885/%5Bdaph%5Dmaenad.zip"]
genre = "－"
impr = "53"
total = "234"
median = "4"
avg = "4.41"
regist = "2014/07/19 16:49"
update = "2014/08/11 03:04"

[[entries]]
no = "14"
name = "54cm"
title = "optics 1 : interference"
size = "16332 KB"
addr = ["https://www.dropbox.com/s/7rdh6i4do89qqxk/optics1interference.zip?dl=1"]
genre = "ELECTRIC DANCE POP"
impr = "41"
total = "171"
median = "4"
avg = "4.17"
regist = "2014/07/20 04:15"
update = "2014/08/11 04:37"

[[entries]]
no = "15"
name = "tetorimino"
title = "The deadline"
size = "56000 KB"
addr = ["https://drive.google.com/open?id=1pCXiMlMvEN02SKfbFofviuqygU9_yz3p"]
genre = "Big beat"
impr = "31"
total = "110"
median = "3"
avg = "3.54"
regist = "2014/07/20 16:58"
update = "2018/01/03 15:21"

[[entries]]
no = "16"
name = "ξ青龍ξ"
title = "Turmeric"
size = "19500 KB"
addr = ["https://www.dropbox.com/s/r8csm6zfnw1d75a/Turmeric.zip"]
genre = "Arabian Core"
impr = "38"
total = "134"
median = "3.5"
avg = "3.52"
regist = "2014/07/20 18:02"
update = "2014/08/10 23:38"

[[entries]]
no = "17"
name = "CLONE"
title = "Make Some Noiz !"
size = "79016 KB"
addr = ["https://docs.google.com/uc?id=0B2VRchzUR6alWWNBQWNFLXlyMTg&export=download"]
genre = "HyperElectroEuroTrancecoreRave"
impr = "54"
total = "245"
median = "5"
avg = "4.53"
regist = "2014/07/20 21:29"
update = "2014/08/10 23:17"

[[entries]]
no = "18"
name = "Sho Fish"
title = "Excited State"
size = "8225 KB"
addr = [
    "http://www.mediafire.com/download/s89s1o13muyhsb1/Sho_Fish_-_Excited_State_ogg.zip",
    "(更新適応済み)",
    "http://www.mediafire.com/download/tehtl4p4sviplgl/Excited+State+Parch+20140726.zip",
    "(修正パッチ 2014.07.26 17:41)",
]
genre = "UK Hardcore"
impr = "42"
total = "159"
median = "4"
avg = "3.78"
regist = "2014/07/20 23:24"
update = "2014/08/11 20:56"

[[entries]]
no = "19"
name = "suna"
title = "LaT"
size = "25876 KB"
addr = [
    "https://www.dropbox.com/s/oxy9kwsggj932co/suna_LaT_ogg.rar?dl=1",
    "↓修正差分です。7月21日11:00以前に落とされた方はこれを上書きしてください。なお本アーカイブは適用済です。",
    "https://www.dropbox.com/s/l40yodri1siaopa/suna_LaT_ogg_syusei.rar?dl=1",
]
genre = "Hard Techno"
impr = "40"
total = "170"
median = "4"
avg = "4.25"
regist = "2014/07/21 00:25"
update = "2014/11/14 20:06"

[[entries]]
no = "20"
name = "翡乃イスカ"
title = "Groovin Groovin!!"
size = "89608 KB"
addr = ["https://www.dropbox.com/s/x564g8eispolzyw/Groovin%20Groovin%21%21%20-%20%E7%BF%A1%E4%B9%83%E3%82%A4%E3%82%B9%E3%82%AB.zip?dl=1"]
genre = "HAPPY HARDCORE"
impr = "58"
total = "273"
median = "5"
avg = "4.7"
regist = "2014/07/21 00:43"
update = "2015/03/28 02:27"

[[entries]]
no = "21"
name = "EFB37-1"
title = "4<0μ§†!℃"
size = "37610 KB"
addr = [
    "https://www.dropbox.com/s/h7f442yzy4ujoa3/acoustic.zip",
    "(修正版)",
]
genre = "Techno"
impr = "32"
total = "102"
median = "3"
avg = "3.18"
regist = "2014/07/21 01:48"
update = "2014/08/14 00:03"

[[entries]]
no = "22"
name = "K's-traX"
title = "MAXIMUM DELTA FORCE"
size = "10757 KB"
addr = ["http://kstmusic.sakura.ne.jp/MAXIMUMDELTAFORCE.zip"]
genre = "SPEEDCORE"
impr = "39"
total = "138"
median = "4"
avg = "3.53"
regist = "2014/07/21 12:55"
update = "2014/08/10 23:43"

[[entries]]
no = "23"
name = "FICY"
title = "Loop the beep"
size = "4026 KB"
addr = [
    "ogg版(4026KB)",
    "http://fictionfactory.if.land.to/BMS/Loop_the_beep_ogg.rar",
    "wav版(4229KB)",
    "http://fictionfactory.if.land.to/BMS/Loop_the_beep_wav.rar",
]
genre = "break beats"
impr = "34"
total = "115"
median = "3"
avg = "3.38"
regist = "2014/07/21 21:49"
update = "2014/08/10 23:59"

[[entries]]
no = "24"
name = "435nm"
title = "Anti Literal."
size = "49676 KB"
addr = ["https://www.dropbox.com/s/s38abiyz66qz3yy/Anti%20Literal.rar?dl=1"]
genre = "Trance Core"
impr = "33"
total = "98"
median = "3"
avg = "2.96"
regist = "2014/07/22 00:33"
update = "2014/08/10 23:47"

[[entries]]
no = "25"
name = "ボテ旨 ぽふまろえ"
title = "BLOODY ROSE"
size = "6780 KB"
addr = ["https://dl.dropboxusercontent.com/u/106928624/BMS/BLOODY%20ROSE.zip"]
genre = "RENAISSANCE DANCE"
impr = "51"
total = "204"
median = "4"
avg = "4"
regist = "2014/07/22 00:38"
update = "2014/08/11 13:44"

[[entries]]
no = "26"
name = "lazward"
title = "Lacernella rubra"
size = "63200 KB"
addr = ["https://www.dropbox.com/s/jbbq9fjvn25o0wv/Lacernella%20rubra.rar"]
genre = "TRANCE CORE"
impr = "42"
total = "192"
median = "5"
avg = "4.57"
regist = "2014/07/22 20:16"
update = "2014/08/11 04:09"

[[entries]]
no = "27"
name = "Rizna"
title = "Scarlet Step"
size = "9667 KB"
addr = ["https://www.dropbox.com/s/fdtd3zsdo1xf9l1/Scarlet_Step.zip"]
genre = "NU STYLE GABBA"
impr = "28"
total = "76"
median = "3"
avg = "2.71"
regist = "2014/07/23 06:02"
update = "2014/08/10 23:23"

[[entries]]
no = "28"
name = "L.K."
title = "Larix (BMS Edit)"
size = "4352 KB"
addr = ["https://dl.dropboxusercontent.com/s/fdb2ok86dm225cj/Larix_ogg.zip"]
genre = "House Pop"
impr = "49"
total = "231"
median = "5"
avg = "4.71"
regist = "2014/07/24 12:36"
update = "2014/08/10 23:51"

[[entries]]
no = "29"
name = "TEKINA"
title = "H.A.L. X-Form"
size = "80000 KB"
addr = ["https://www.dropbox.com/s/8dz2o3rpel2b9wj/%5BHUMANOID%20CORE%5DH.A.L.%20X-Form.rar"]
genre = "HUMANOID CORE"
impr = "37"
total = "154"
median = "4"
avg = "4.16"
regist = "2014/07/24 21:06"
update = "2014/08/10 23:52"

[[entries]]
no = "30"
name = "Napo"
title = "Crystallia"
size = "21823 KB"
addr = ["https://www.dropbox.com/s/rdt9aha0krfbx4k/napo_crystallia_ogg.rar"]
genre = "Drum'n Bass"
impr = "42"
total = "181"
median = "4"
avg = "4.3"
regist = "2014/07/24 22:46"
update = "2014/08/10 23:59"

[[entries]]
no = "31"
name = "102missile"
title = "Regen"
size = "30620 KB"
addr = ["https://www.dropbox.com/s/wbfipsz4wa1b98o/Regen.zip?n=320937629"]
genre = "Drum'n'Bass"
impr = "34"
total = "128"
median = "4"
avg = "3.76"
regist = "2014/07/24 23:57"
update = "2014/08/12 12:37"

[[entries]]
no = "32"
name = "dj koishi"
title = "Amyurina"
size = "77943 KB"
addr = ["https://www.dropbox.com/s/ibbym08pljlp3td/Amyurina.zip"]
genre = "trance"
impr = "41"
total = "113"
median = "3"
avg = "2.75"
regist = "2014/07/25 05:08"
update = "2014/08/10 23:56"

[[entries]]
no = "33"
name = "⑮"
title = "FearlessFortress"
size = "30173 KB"
addr = ["https://www.dropbox.com/s/0xpkqnus195i3oc/FearlessFortress.rar"]
genre = "None"
impr = "31"
total = "132"
median = "4"
avg = "4.25"
regist = "2014/07/25 12:13"
update = "2014/08/11 02:45"

[[entries]]
no = "34"
name = "Klavistr"
title = "Burn Out, Fire!! 2014"
size = "37547 KB"
addr = [
    "https://www.dropbox.com/s/hyavgcyyx5xq19q/__b_o_f_2014.zip",
    "https://www.dropbox.com/s/f9nep9vo5flosq8/upper_027.ogg",
]
genre = "HANDZ UP"
impr = "33"
total = "93"
median = "3"
avg = "2.81"
regist = "2014/07/25 23:46"
update = "2014/08/14 23:15"

[[entries]]
no = "35"
name = "TKR"
title = "Meaning of Existence"
size = "60000 KB"
addr = [
    "https://www.dropbox.com/s/m1hgtos5jmnn5i3/MoE_TKR.zip",
    "(ノイズ修正前の譜面です。7/26/20:45以前にDLされた方はお手数ですが下のファイルをDLして上書きしてください。）",
    "https://www.dropbox.com/s/3l84ln2kwu3y5qd/MoE_TKR_fixed.zip",
    "（ノイズ修正+BEGINNER譜面同梱）",
    "発狂譜面の難易度がぶっとんでるので中間くらいの発狂譜面を追加するかもしれません。",
]
genre = "Progressive House"
impr = "33"
total = "149"
median = "5"
avg = "4.51"
regist = "2014/07/26 01:26"
update = "2020/03/25 06:13"

[[entries]]
no = "36"
name = "スタスタ"
title = "Plasma Sphere"
size = "9658 KB"
addr = ["https://dl.dropboxusercontent.com/u/74200759/PlasmaSphere.zip"]
genre = "FULL ON"
impr = "53"
total = "248"
median = "5"
avg = "4.67"
regist = "2014/07/26 01:37"
update = "2014/08/10 23:58"

[[entries]]
no = "37"
name = "doumoku"
title = "puka-puka"
size = "7361 KB"
addr = ["https://www.dropbox.com/s/x1ym1kx6n6dcmdh/puka-puka.zip?dl=1"]
genre = "house"
impr = "29"
total = "91"
median = "3"
avg = "3.13"
regist = "2014/07/26 15:50"
update = "2014/08/11 00:22"

[[entries]]
no = "39"
name = "市川"
title = "Gorgon"
size = "14000 KB"
addr = ["https://www.dropbox.com/s/c5zyw0txnwqphkg/Gorgon.zip"]
genre = "CHIP TECH"
impr = "30"
total = "85"
median = "3"
avg = "2.83"
regist = "2014/07/27 00:41"
update = "2014/08/10 23:32"

[[entries]]
no = "40"
name = "tanacoro"
title = "ブロケン"
size = "19400 KB"
addr = ["http://www1.axfc.net/u/3285011"]
genre = "TRANCECORE"
impr = "29"
total = "56"
median = "2"
avg = "1.93"
regist = "2014/07/27 04:24"
update = "2014/08/11 12:51"

[[entries]]
no = "41"
name = "すとろ～"
title = "Champagne stemware"
size = "40700 KB"
addr = ["http://www1.axfc.net/u/3285103"]
genre = "TECHNO"
impr = "26"
total = "65"
median = "2.5"
avg = "2.5"
regist = "2014/07/27 09:57"
update = "2014/08/10 23:34"

[[entries]]
no = "42"
name = "Cream P.P."
title = "Sunday Forever"
size = "16215 KB"
addr = [
    "☆本体パッケージ 約16,000KB",
    "https://dl.dropboxusercontent.com/s/56zh0axrea3qlns/%5BCream%20P.P.%5DSunday%20Forever_ogg.zip",
    "(ミラー)",
    "https://drive.google.com/file/d/0B15_ofoFKOEgcUtXUDFUNHNrcDQ/edit?usp=sharing",
    "☆差分パッケージ",
    "・2014.07.27公開 7keys Another-2 42KB",
    "https://dl.dropboxusercontent.com/s/7x2yz9halid1emx/20140727sabun_sundayforever_creampp.zip",
    "・2014.08.11公開 DP(14keys)差分 136KB",
    "https://dl.dropboxusercontent.com/s/gaq59mopqz6ypu8/20140811sabun_sundayforever_creampp.zip",
]
genre = "Pop"
impr = "37"
total = "165"
median = "4"
avg = "4.45"
regist = "2014/07/27 12:41"
update = "2014/08/12 22:52"

[[entries]]
no = "43"
name = "srps02"
title = "鳥の詩(ReMix)"
size = "24500 KB"
addr = ["http://www1.axfc.net/u/3285376"]
genre = "TRANCE"
impr = "32"
total = "107"
median = "3"
avg = "3.34"
regist = "2014/07/27 17:05"
update = "2014/08/11 09:40"

[[entries]]
no = "44"
name = "Reversa"
title = "Νύξ"
size = "25300 KB"
addr = ["https://dl.dropboxusercontent.com/u/59988778/Reversa-Nyx.zip"]
genre = "Τέλος"
impr = "34"
total = "137"
median = "4"
avg = "4.02"
regist = "2014/07/27 21:09"
update = "2014/08/12 16:52"

[[entries]]
no = "45"
name = "maru"
title = "幻月"
size = "13341 KB"
addr = ["https://dl.dropboxusercontent.com/u/34120259/%E5%B9%BB%E6%9C%88%20-%20maru%5Bogg%5D.zip"]
genre = "神楽 - Juke/Footwork"
impr = "42"
total = "177"
median = "4"
avg = "4.21"
regist = "2014/07/27 22:32"
update = "2014/08/10 23:52"

[[entries]]
no = "46"
name = "Cutos"
title = "Prospect"
size = "3740 KB"
addr = ["https://www.dropbox.com/s/gqfyq6wfbmhuzte/Cutos%20-%20Prospect.zip?dl=1"]
genre = "Drum & Bass"
impr = "39"
total = "176"
median = "5"
avg = "4.51"
regist = "2014/07/27 22:51"
update = "2014/08/10 23:40"

[[entries]]
no = "47"
name = "ex§tream"
title = "歪↓"
size = "5240 KB"
addr = ["http://ux.getuploader.com/exStreamers_BMS/download/1/%E6%AD%AA%E2%86%93%28ex%C2%A7tream%29.zip"]
genre = "魔χ流 ILLEGAL DISTORTION"
impr = "28"
total = "72"
median = "3"
avg = "2.57"
regist = "2014/07/27 23:01"
update = "2014/08/10 23:42"

[[entries]]
no = "48"
name = "yuutee"
title = "Gather the Wind"
size = "9000 KB"
addr = ["https://www.dropbox.com/s/l0rd5xivnrnolnt/ogg.zip?dl=1"]
genre = "Aerial Trance"
impr = "36"
total = "162"
median = "5"
avg = "4.5"
regist = "2014/07/27 23:02"
update = "2014/08/10 23:58"

[[entries]]
no = "49"
name = "HALLPBESTUDIO"
title = "Feeling of floating (non name edition)"
size = "17132 KB"
addr = ["http://ux.getuploader.com/hallpbestudio/download/27/Feeling+of+floating.zip"]
genre = "ROTTERDAM TECHNO"
impr = "31"
total = "113"
median = "4"
avg = "3.64"
regist = "2014/07/27 23:25"
update = "2014/08/10 23:44"

[[entries]]
no = "50"
name = "Liet."
title = "Nopea"
size = "11983 KB"
addr = [
    "[ogg](11.9MB)",
    "https://www.dropbox.com/s/bdi7417wfv7c79p/Liet_nopea_ogg.zip?dl=1",
    "[wav](85.6MB)",
    "https://www.dropbox.com/s/avyb8tjtln9lqcw/Liet_nopea_wav.zip?dl=1",
]
genre = "FREEFORM / TRANCECORE"
impr = "37"
total = "145"
median = "4"
avg = "3.91"
regist = "2014/07/27 23:58"
update = "2014/11/08 22:36"
