[[entries]]
no = "1"
name = "アクジ"
team = "KerberoStyle"
title = "Party PeoPle"
size = "2700 KB"
addr = ["https://dl.dropboxusercontent.com/u/272956039/KerberoStyle%20-%20Party%20PeoPle.zip"]
genre = "たのしいガバキック"
impr = "9"
total = "7666"
median = "950"
avg = "851.77"
regist = "2014/10/20 01:01"
update = "2014/11/25 05:51"

[[entries]]
no = "2"
name = "asahi3"
team = "AA(A)AAAやっぱり出ません"
title = "2001年くらいのBMSイベントの下の方で埋もれてそうな曲"
size = "1681 KB"
addr = ["https://www.dropbox.com/s/hqcwh36bqfu08gu/2001_event_shitanohou_bms.rar?dl=0"]
genre = "TRANCE"
impr = "8"
total = "5319"
median = "590"
avg = "664.87"
regist = "2014/10/20 01:04"
update = "2014/11/24 23:20"

[[entries]]
no = "4"
name = "yuki."
team = "野良チーム"
title = "impulse"
size = "30300 KB"
addr = ["https://onedrive.live.com/?cid=2DA399F016445665&id=2DA399F016445665%21105"]
genre = "UK HARDCORE"
impr = "6"
total = "5037"
median = "860"
avg = "839.5"
regist = "2014/10/20 01:35"
update = "2014/11/24 23:20"

[[entries]]
no = "5"
name = "Neun_jack"
team = "KerberoStyle"
title = "demaetchmanbot"
size = "3001 KB"
addr = ["http://db.tt/NUXz6xjD"]
genre = "出前テクノ"
impr = "6"
total = "5770"
median = "961.5"
avg = "961.66"
regist = "2014/10/20 01:46"
update = "2014/11/24 23:20"

[[entries]]
no = "6"
name = "tetorimino"
team = "SIMPLE1500シリーズ vol.2014 THE テト勢"
title = "Shouter"
size = "32400 KB"
addr = ["https://drive.google.com/open?id=1EnX0K3HBQ7aeyzWhzbJfkG0-hKzDC9CR"]
genre = "Rock"
impr = "5"
total = "4573"
median = "920"
avg = "914.6"
regist = "2014/10/20 23:33"
update = "2018/01/03 15:42"

[[entries]]
no = "7"
name = "ねこみりん feat.小宮真央×みゆ×えみゅう。"
team = "のらねこさい"
title = "オトゲラヴ！ [反省してるところ]"
size = "2 KB"
addr = [
    "http://www.nekomirin.com/bms/nekomirin_otogelove_add_hansei.zip",
    "※解凍したBMEファイルは↓のBMSと同じディレクトリにいれてください",
    "http://manbow.nothing.sh/event/event.cgi?action=More_def&num=201&event=96",
]
genre = "A-POP"
impr = "6"
total = "4465"
median = "757"
avg = "744.16"
regist = "2014/10/21 01:44"
update = "2014/11/24 23:21"

[[entries]]
no = "9"
name = "Y-ItoO"
team = "三十路"
title = "kjaox"
size = "10694 KB"
addr = ["https://docs.google.com/uc?id=0B8-paTC0Lv48NE81d3MwSXBNcmc"]
genre = "hardminimal"
impr = "7"
total = "6104"
median = "872"
avg = "872"
regist = "2014/10/22 14:38"
update = "2014/11/26 18:59"

[[entries]]
no = "10"
name = "dawn-system Vocal by 小宮真央"
team = "魔界都市ニイガタ"
title = "アラガエナイ"
size = "10137 KB"
addr = [
    "http://docs.google.com/uc?id=0ByS9Wlo7KZbxM05BeHBBci1HdVk&export=download",
    "(BMS ogg)",
    "http://docs.google.com/uc?id=0ByS9Wlo7KZbxbFQ1OG5aVlhrb28&export=download",
    "(K-Shoot MANIA)",
]
genre = "VORTEX"
impr = "9"
total = "8764"
median = "1000"
avg = "973.77"
regist = "2014/10/22 14:44"
update = "2014/11/24 23:30"

[[entries]]
no = "11"
name = "illusion sonic"
team = "2052～The reunion from startline～そうだ！俺たちのチーム名は！"
title = "Explosion Floor 2014"
size = "42853 KB"
addr = ["公開終了"]
genre = "Eurobeat"
impr = "8"
total = "7314"
median = "930"
avg = "914.25"
regist = "2014/10/22 21:21"
update = "2019/08/09 23:36"

[[entries]]
no = "12"
name = "シャカチキ"
team = "ああ…翡翠茶漬け…"
title = "マックのフライヤーの音 (ああああ`s 『(休符)ソファソ』派mix )【BMS edit】"
size = "10342 KB"
addr = [
    "https://www.dropbox.com/s/zdgio7x3zsu105k/%E3%83%9E%E3%83%83%E3%82%AF%E3%81%AE%E3%83%95%E3%83%A9%E3%82%A4%E3%83%A4%E3%83%BC%E3%81%AE%E9%9F%B3%20",
    "(%E3%81%82%E3%81%82%E3%81%82%E3%81%82%60s%20%E3%80%8E(%E4%BC%91%E7%AC%A6)%E3%82%BD%E3%83%95%E3%82%A1%E3%82%BD%E3%80%8F%E6%B4%BEmix%20)%E3%80%90BMS%20edit%E3%80%91.zip?dl=0",
]
genre = "ポティトォオオオオオオオオオオオオオオ"
impr = "7"
total = "4852"
median = "700"
avg = "693.14"
regist = "2014/10/22 22:27"
update = "2014/11/24 23:22"

[[entries]]
no = "13"
name = "ホイマン"
team = "魔界都市ニイガタ"
title = "越後より愛を込めて〜反省版〜"
size = "5500 KB"
addr = ["http://docs.google.com/uc?id=0B0VmuCNXc4xYaVhVVHdnX2ZXdFk&export=download"]
genre = "かゆき"
impr = "8"
total = "7002"
median = "883"
avg = "875.25"
regist = "2014/10/22 23:33"
update = "2014/11/24 23:50"

[[entries]]
no = "14"
name = "Nuribit (feat:genesik)"
team = "野良チーム"
title = "Breeze From Southern Island"
size = "3200 KB"
addr = ["https://www"]
genre = "Epic"
impr = "4"
total = "3687"
median = "965"
avg = "921.75"
regist = "2014/10/23 04:19"
update = "2015/11/02 01:50"

[[entries]]
no = "15"
name = "suna"
team = "野良チーム"
title = "204"
size = "4239 KB"
addr = [
    "http://www1.axfc.net/u/3348649",
    "なるべく上の方からダウンロードをしていただけると助かります",
    "https://www.dropbox.com/s/cv75b59mbjvzki6/suna_204.rar?dl=1",
]
genre = "Hard Techno"
impr = "12"
total = "11211"
median = "940"
avg = "934.25"
regist = "2014/10/24 00:34"
update = "2014/11/26 23:08"

[[entries]]
no = "16"
name = "xarva"
team = "労働八号"
title = "Forty-Four"
size = "11602 KB"
addr = ["https://dl.dropboxusercontent.com/u/59626843/xrv_44.rar"]
genre = "Psytrance"
impr = "19"
total = "18594"
median = "999"
avg = "978.63"
regist = "2014/10/26 17:29"
update = "2014/11/24 23:59"

[[entries]]
no = "17"
name = "Yie Ar Kung-Fu(EFB37-1)"
team = "E.G.O."
title = "中家"
size = "68349 KB"
addr = ["https://www.dropbox.com/s/61npv0d4kkk634u/tyu-ka.zip?dl=1"]
genre = "Imitation Chinese Piano House"
impr = "5"
total = "4303"
median = "860"
avg = "860.6"
regist = "2014/10/26 22:33"
update = "2014/11/30 02:45"

[[entries]]
no = "18"
name = "Kanata.S"
team = "僕らの見た原点（ROOTS）"
title = "Miracle 出前っちympho X↑X↓"
size = "6888 KB"
addr = ["https://www.dropbox.com/s/d5ja5t50zwf1jsi/orehamoudamee.rar?dl=0"]
genre = "FRENCHCORE"
impr = "5"
total = "4338"
median = "931"
avg = "867.6"
regist = "2014/10/30 07:04"
update = "2014/11/24 23:24"

[[entries]]
no = "19"
name = "アニヨコーズ"
team = "野良チーム"
title = "ビミョーなPOSITION(Mince-Saw Zoo of Cocaine Bootleg)"
size = "2721 KB"
addr = ["https://dl.dropboxusercontent.com/u/59462259/G2R2014/ANIYOKO_EXTRATONE_RYAKUSITE.zip"]
genre = "A-EXTRATONE"
impr = "4"
total = "3664"
median = "902"
avg = "916"
regist = "2014/11/01 00:51"
update = "2014/11/24 23:24"

[[entries]]
no = "20"
name = "LU"
team = "野良チーム"
title = "our headsVIP"
size = "4987 KB"
addr = ["http://gensoukyousoukyoku.nekokan.dyndns.info/ourheadsVIP.rar"]
genre = "BOOTY TRANCE"
impr = "4"
total = "3766"
median = "943"
avg = "941.5"
regist = "2014/11/01 01:07"
update = "2014/11/24 23:25"

[[entries]]
no = "21"
name = "赦瞑 a.k.a SMNX (Illust：mizu.)"
team = "愛 know"
title = "Blind Fate"
size = "11100 KB"
addr = ["https://www.dropbox.com/s/kn6gulqpd5nwkze/%5BSMNX%5DBlind%20Fate.rar?dl=0"]
genre = "HEAVEN CORE"
impr = "6"
total = "5012"
median = "825"
avg = "835.33"
regist = "2014/11/07 23:23"
update = "2014/11/25 03:52"

[[entries]]
no = "22"
name = "Qga"
team = "野良チーム"
title = "animaranz"
size = "6868 KB"
addr = ["https://www.dropbox.com/s/zrrq2k2vgad29wb/animaranz.zip?dl=0"]
genre = "ZOO"
impr = "5"
total = "2933"
median = "810"
avg = "586.6"
regist = "2014/11/08 15:22"
update = "2014/11/24 23:25"

[[entries]]
no = "23"
name = "LeaF"
team = "カタストロフィー理論"
title = "テールストーリー物語Ⅱ"
size = "600000 KB"
addr = ["http://nekokan.dyndns.info/~anonymous/bms/leaf/talestory/story_story_story_LeaF.zip"]
genre = "ROLE-PLAYING MUSIC"
impr = "16"
total = "16000"
avg = "1000"
regist = "2014/11/09 21:12"
update = "2014/11/25 07:40"

[[entries]]
no = "24"
name = "Sho Fish"
team = "天涯孤独"
title = "HFAPP"
size = "10768 KB"
addr = [
    "http://www.mediafire.com/download/q3dxvu6mqgfyofq/Sho_Fish_-_HFAPP_ogg.zip",
    "DP差分[SMNXさん]:",
    "https://www.dropbox.com/s/ddub467t2hiq1zq/Sho%20Fish%20-%20HFAPP%20ogg%20DP.zip?dl=0",
    "上記DLリンクのzipには同梱済み",
]
genre = "Electronic Dance"
impr = "9"
total = "7376"
median = "871"
avg = "819.55"
regist = "2014/11/11 02:22"
update = "2014/11/27 23:35"

[[entries]]
no = "25"
name = "Aglaia"
team = "野良チーム"
title = "Gremlin"
size = "8724 KB"
addr = ["http://goo.gl/mQCTzC"]
genre = "HARDCORE"
impr = "4"
total = "3239"
median = "830"
avg = "809.75"
regist = "2014/11/17 00:14"
update = "2015/10/24 01:55"

[[entries]]
no = "26"
name = "schwarzekugel"
team = "KerberoStyle"
title = "Dunkelheit:Verstärker"
size = "9554 KB"
addr = ["https://dl.dropboxusercontent.com/s/ae3ewbnbw6llrl6/LNB53-dunkel.rar"]
genre = "HARD TECHNO"
impr = "7"
total = "6581"
median = "970"
avg = "940.14"
regist = "2014/11/20 23:53"
update = "2020/06/11 23:41"

[[entries]]
no = "27"
name = "ケドメ with 初音ミク (原曲:Depeche Mode)"
team = "野良チーム"
title = "NEW LIFE"
size = "6503 KB"
addr = [
    "http://mikihara.cheap.jp/bms/new_life_ogg.zip",
    "-ogg版",
    "http://mikihara.cheap.jp/bms/new_life_wav.zip",
    "-wav版（超容量）",
]
genre = "ELECTRO POP CLASSIC"
impr = "6"
total = "5738"
median = "963.5"
avg = "956.33"
regist = "2014/11/21 17:44"
update = "2014/11/26 01:21"

[[entries]]
no = "28"
name = "aysk_gm（ヤサイアブラマシ魚粉ニンニクマシマシチョイウス豚T）"
team = "自家製麺 ドカ盛りマッチョ"
title = "家系ラーメン作りたかった"
size = "12000 KB"
addr = [
    "http://kie.nu/2jjh",
    "(来年まで)",
]
genre = "Disco House"
impr = "5"
total = "4265"
median = "840"
avg = "853"
regist = "2014/11/22 16:05"
update = "2015/01/02 14:34"

[[entries]]
no = "29"
name = "ZUMMER"
team = "Team ZUMMER"
title = "Tavatar Of Darkness -fw. MC TUMMER-"
size = "70000 KB"
addr = ["http://team-zummer.info/bms/G2R/Z_TOD_ogg.zip"]
genre = "SHAZAI CORE"
impr = "5"
total = "4258"
median = "810"
avg = "851.6"
regist = "2014/11/24 13:48"
update = "2014/11/24 23:27"

[[entries]]
no = "30"
name = "Thefur Celtridorn Remixed by メガバンギラス"
team = "野良チーム"
title = "のらねこせっくす！"
size = "16241 KB"
addr = ["終了"]
genre = "FREEFORM GABBA GABBA"
impr = "5"
total = "3464"
median = "800"
avg = "692.8"
regist = "2014/11/24 22:21"
update = "2014/11/25 00:03"
