[[entries]]
no = "1"
name = "JourneyCat"
title = "Lunartic Predication"
size = "41284 KB"
addr = [
    "https://db.tt/1jUvCAJE",
    "(Dropbox)",
    "http://1drv.ms/1vRuRl8",
    "(OneDrive)",
]
genre = "Hard Nocturne"
impr = "25"
total = "2291"
median = "95"
avg = "91.64"
regist = "2014/11/29 00:01"
update = "2014/12/28 23:56"

[[entries]]
no = "2"
name = "ROKINA"
title = "Fiore Tempesta"
size = "34189 KB"
addr = ["https://dl.dropboxusercontent.com/s/98svgsilcihwe62/LNB52-tempesta.rar"]
genre = "HARD WALTZ"
impr = "31"
total = "2808"
median = "95"
avg = "90.58"
regist = "2014/11/29 00:01"
update = "2020/06/12 00:07"

[[entries]]
no = "3"
name = "suna"
title = "Dar"
size = "7587 KB"
addr = [
    "BMS:",
    "http://fast-uploader.com/file/6972875811707/",
    "HQBGA:",
    "http://www1.axfc.net/u/3365620",
    "なるべく上の方からDLしていただけると助かります",
    "BMS:",
    "https://www.dropbox.com/s/uigy952xgc9d8x9/%5Bsuna%5Ddar.rar?dl=1",
    "HQBGA:",
    "https://www.dropbox.com/s/vpbvvb48yypj9zs/%5Bsuna%5Ddar_hqpng.rar?dl=1",
]
genre = "Techno"
impr = "26"
total = "2296"
median = "90"
avg = "88.3"
regist = "2014/11/29 00:02"
update = "2014/12/29 18:09"

[[entries]]
no = "4"
name = "竜。"
title = "夢うつつ"
size = "56210 KB"
addr = [
    "wav45.11MB",
    "https://www.dropbox.com/s/0a1yrhe1r35js00/Ryu0316_yuu_wav.rar?dl=1",
    "ogg11.10MB",
    "https://www.dropbox.com/s/kjovjdfqjh72w5p/Ryu0316_yuu_ogg.rar?dl=1",
]
genre = "Instrumental"
impr = "18"
total = "1546"
median = "87.5"
avg = "85.88"
regist = "2014/11/29 00:03"
update = "2015/04/25 02:13"

[[entries]]
no = "5"
name = "Neun_jack+tcheb"
title = "Gaoth an Sliabh"
size = "27034 KB"
addr = [
    "https://dl.dropboxusercontent.com/u/60346274/gassaku_tcheb/Neun_jack%2Btcheb%2Bikao_Gaothansliabh_ogg.rar",
    "https://dl.dropboxusercontent.com/u/60346274/gassaku_tcheb/Celtcore_syusei.zip",
    "https://dl.dropboxusercontent.com/u/60346274/gassaku_tcheb/Neun_jack%2Btcheb%2Bikao_Gaothansliabh_hqogg.rar",
    "(HQ版)",
]
genre = "Celtcore"
impr = "26"
total = "2209"
median = "90"
avg = "84.96"
regist = "2014/11/29 00:03"
update = "2015/01/01 02:58"

[[entries]]
no = "6"
name = "Snack_X"
title = "STAKK OVERFLOW"
size = "10543 KB"
addr = [
    "http://korsnack.kr/bms/141129_STAKK_OVERFLOW.zip",
    "http://meme.korsnack.kr/bms/141129_STAKK_OVERFLOW.zip",
]
genre = "Hardcore"
impr = "18"
total = "1363"
median = "78"
avg = "75.72"
regist = "2014/11/29 00:24"
update = "2014/12/28 23:27"

[[entries]]
no = "7"
name = "babun"
title = "Abandoned mine"
size = "8380 KB"
addr = [
    "・Axfc",
    "http://www1.axfc.net/u/3367205",
    "・Dropbox",
    "https://www.dropbox.com/s/esf1vfho1yyqcnb/abandoned%20mine%20ogg.zip?dl=0",
]
genre = "religion"
impr = "19"
total = "1432"
median = "77"
avg = "75.36"
regist = "2014/11/29 01:46"
update = "2014/12/28 23:53"

[[entries]]
no = "8"
name = "SMNX (Illust：mizu.)"
title = "Demise"
size = "9530 KB"
addr = ["https://www.dropbox.com/s/9d2jzk14mjyppm4/%5BSMNX%5DDemise.rar?dl=0"]
genre = "Roman Waltz"
impr = "18"
total = "1326"
median = "73.5"
avg = "73.66"
regist = "2014/11/29 02:03"
update = "2014/12/28 23:51"

[[entries]]
no = "9"
name = "R→eCycle"
title = "Delicious Rabbit"
size = "19665 KB"
addr = ["http://www1.axfc.net/u/3365748"]
genre = "HAPPY WALTZCORE"
impr = "27"
total = "2511"
median = "95"
avg = "93"
regist = "2014/11/29 02:57"
update = "2014/12/28 23:51"

[[entries]]
no = "10"
name = "D632"
title = "D632"
size = "640 KB"
addr = ["https://www.dropbox.com/s/kf3v5hrcodg1qug/D632.zip?dl=1"]
genre = "Hard Techno (Re-Compounded)"
impr = "18"
total = "1451"
median = "81.5"
avg = "80.61"
regist = "2014/11/29 08:29"
update = "2017/03/14 23:54"

[[entries]]
no = "11"
name = "isz"
title = "SwitchBack3"
size = "80000 KB"
addr = [
    "wav→",
    "https://www.dropbox.com/s/s3vvyo3jh5qyyzb/switchback3_isz_wav.zip?dl=0",
    "ogg→",
    "https://www.dropbox.com/s/q0xofz4qmi5re8j/switchback3_isz_ogg.zip?dl=0",
]
genre = "DnB"
impr = "21"
total = "1914"
median = "92"
avg = "91.14"
regist = "2014/11/29 13:30"
update = "2014/12/29 07:20"

[[entries]]
no = "12"
name = "週刊硅砂"
title = "少女と道化師の死劇場"
size = "6015 KB"
addr = ["https://www.dropbox.com/s/dqi8b37kh5hvvew/%E5%B0%91%E5%A5%B3%E3%81%A8%E9%81%93%E5%8C%96%E5%B8%AB%E3%81%AE%E6%AD%BB%E5%8A%87%E5%A0%B4.zip?dl=1"]
genre = "ALICE CORE"
impr = "18"
total = "1455"
median = "80"
avg = "80.83"
regist = "2014/11/29 13:47"
update = "2014/12/28 23:53"

[[entries]]
no = "14"
name = "Re:gats&"
title = "Signal:RED"
size = "11146 KB"
addr = ["http://1drv.ms/15KiNGI"]
genre = "HARD NRG MEETS TRANCECORE"
impr = "18"
total = "1442"
median = "80"
avg = "80.11"
regist = "2014/11/29 21:49"
update = "2016/02/08 01:08"

[[entries]]
no = "15"
name = "kenzoooo"
title = "Skull & Witch"
size = "21939 KB"
addr = ["https://www.dropbox.com/s/max37w8ccsiw6dr/%5BTRIDENT%5Dsaw.rar?dl=0"]
genre = "GABBASTEP WALTZ"
impr = "24"
total = "2187"
median = "94"
avg = "91.12"
regist = "2014/11/29 22:04"
update = "2014/12/30 14:32"

[[entries]]
no = "16"
name = "asahi3"
title = "冬の街、雪の音"
size = "5143 KB"
addr = ["http://dl.dropboxusercontent.com/s/5uu2ja6sro66r35/%5Basahi3%5Dfuyunomachi_yukinooto.rar?dl=0"]
genre = "winter pop"
impr = "24"
total = "2088"
median = "89.5"
avg = "87"
regist = "2014/11/30 12:23"
update = "2014/12/28 23:54"

[[entries]]
no = "17"
name = "Lairy"
title = "Short Revival"
size = "10170 KB"
addr = ["https://www.dropbox.com/s/skb8lgwqiymcx35/Lairy_Short%20Revival_ogg.rar?dl=1"]
genre = "Emotional"
impr = "16"
total = "1324"
median = "85.5"
avg = "82.75"
regist = "2014/11/30 20:00"
update = "2015/04/25 02:13"

[[entries]]
no = "18"
name = "赦瞑"
title = "綺麗だった"
size = "6000 KB"
addr = ["https://www.dropbox.com/s/w7w1ynegqpi0rzi/sm_kirei.rar?dl=0"]
genre = "IDM"
impr = "24"
total = "1968"
median = "82.5"
avg = "82"
regist = "2014/11/30 20:12"
update = "2014/12/28 23:42"

[[entries]]
no = "19"
name = "EFB37-1"
title = "!satisfied"
size = "51323 KB"
addr = ["https://www.dropbox.com/s/8rmoyxydrxf4h6z/%28not%29satisfied.zip?dl=1"]
genre = "drum'n'bass"
impr = "19"
total = "1572"
median = "83"
avg = "82.73"
regist = "2014/11/30 20:55"
update = "2014/12/29 19:34"

[[entries]]
no = "20"
name = "FIFTH ELEMENT"
title = "Fairyland in Moonlight Shadow"
size = "24307 KB"
addr = ["http://www.mediafire.com/download/i41p7whj6h1gm61/Fairyland_in_Moonlight_Shadow.zip"]
genre = "FAIRY TALE OVERTURE"
impr = "26"
total = "2366"
median = "94"
avg = "91"
regist = "2014/12/05 00:48"
update = "2014/12/28 23:33"

[[entries]]
no = "21"
name = "Cure p7"
title = "Ceeker Gate"
size = "4232 KB"
addr = ["http://www.dropbox.com/s/k5cspzx1eo66a2p/Ceeker%20Gate%5Bogg%5D.zip?dl=1"]
genre = "TECHNO"
impr = "18"
total = "1407"
median = "79"
avg = "78.16"
regist = "2014/12/05 20:43"
update = "2014/12/28 23:55"

[[entries]]
no = "22"
name = "Ogu"
title = "夕焼け"
size = "44152 KB"
addr = [
    "http://ogut.sakura.ne.jp/temp/bms_yuuyake.zip",
    "DP差分",
    "http://ogut.sakura.ne.jp/temp/bms_yuuyake_dp.zip",
]
genre = "Jazz"
impr = "20"
total = "1727"
median = "88"
avg = "86.35"
regist = "2014/12/06 23:44"
update = "2014/12/29 22:06"

[[entries]]
no = "23"
name = "Cloudy Boy"
title = "Is there 'the end' exists? (Dreaming the sky Pt.3)"
size = "65310 KB"
addr = [
    "1411kbps WAV",
    "https://www.dropbox.com/s/kfh83rjx9o26s8d/CB_Is%20there%20the%20end%20exists%20WAV.zip?dl=0",
    "256kbps OGG",
    "https://www.dropbox.com/s/33i9egcfd4280vl/CB_Is%20there%20the%20end%20exists%20OGG.zip?dl=0",
    "※ファイルサイズはWAVの解凍後の数値を表記しています。",
]
genre = "Drum'n'Bass"
impr = "21"
total = "1863"
median = "90"
avg = "88.71"
regist = "2014/12/07 00:08"
update = "2015/01/03 23:39"

[[entries]]
no = "24"
name = "Kanata.S feat.Salita"
title = "片翼のライカ-BMS Remaster-"
size = "31889 KB"
addr = ["https://www.dropbox.com/s/7poszl6hjruv9r4/trident_kanatas_raika.zip?dl=0"]
genre = "Celtic"
impr = "20"
total = "1696"
median = "85"
avg = "84.8"
regist = "2014/12/07 03:29"
update = "2014/12/28 23:55"

[[entries]]
no = "25"
name = "U-hey"
title = "Fairy of Dawn"
size = "80000 KB"
addr = ["https://www.dropbox.com/s/a9yagiaa895u3c1/Fairy%20of%20Dawn.rar?dl=0"]
genre = "HEALING MUSIC"
impr = "21"
total = "1758"
median = "85"
avg = "83.71"
regist = "2014/12/07 06:19"
update = "2014/12/28 23:56"

[[entries]]
no = "26"
name = "ORC"
title = "Trident"
size = "18368 KB"
addr = ["http://firestorage.jp/download/5b868dcf15e0adfb713893dfbb9093019f93a68d"]
genre = "WALTZCORE"
impr = "16"
total = "1439"
median = "93"
avg = "89.93"
regist = "2014/12/07 06:45"
update = "2014/12/28 23:50"

[[entries]]
no = "27"
name = "犬"
title = "夜の命数"
size = "86595 KB"
addr = ["https://www.dropbox.com/s/8c0fo9allsevjdb/%E5%A4%9C%E3%81%AE%E5%91%BD%E6%95%B0.zip?dl=0"]
genre = "DIGITAL MIXTURE"
impr = "21"
total = "1911"
median = "92"
avg = "91"
regist = "2014/12/07 07:51"
update = "2014/12/28 23:56"

[[entries]]
no = "28"
name = "⑮"
title = "マボロシ街道"
size = "45440 KB"
addr = ["https://www.dropbox.com/s/evavihva61ph2gr/maboroshi.rar"]
genre = "FantasicScroll"
impr = "25"
total = "2238"
median = "92"
avg = "89.52"
regist = "2014/12/07 10:03"
update = "2014/12/28 23:56"

[[entries]]
no = "29"
name = "analogUntena"
title = "Lar"
size = "1359 KB"
addr = ["http://fast-uploader.com/file/6973478651006/"]
genre = "minimal"
impr = "19"
total = "1362"
median = "70"
avg = "71.68"
regist = "2014/12/07 12:42"
update = "2014/12/28 23:53"

[[entries]]
no = "30"
name = "daisan feat. えみゅう。 / zue-row"
title = "Dance Doll Dream"
size = "78479 KB"
addr = ["http://clockxellox.sakura.ne.jp/BMS/daisan_DanceDollDream.zip"]
genre = "Waltz"
impr = "37"
total = "3429"
median = "98"
avg = "92.67"
regist = "2014/12/07 17:47"
update = "2014/12/31 23:32"

[[entries]]
no = "31"
name = "Se-U-Ra"
title = "Trysil"
size = "71862 KB"
addr = ["https://www.dropbox.com/s/7gt3d5l3x1w5n74/Trysil.zip?dl=0"]
genre = "End"
impr = "20"
total = "1712"
median = "87.5"
avg = "85.6"
regist = "2014/12/07 18:50"
update = "2014/12/28 23:57"

[[entries]]
no = "32"
name = "polysha remixed by tcheb"
title = "Castor -tcheb HD-WLZ Remix-"
size = "29908 KB"
addr = ["https://dl.dropboxusercontent.com/s/km53390k4hyhtu6/CastorRMX%5Bogg%5D.zip?dl=0"]
genre = "HARD WALTZ / DUBSTEP"
impr = "24"
total = "2001"
median = "85"
avg = "83.37"
regist = "2014/12/07 22:23"
update = "2014/12/28 23:58"

[[entries]]
no = "33"
name = "mommy"
title = "Twinkle"
size = "12332 KB"
addr = ["https://www.dropbox.com/s/x3sosh6pipprvbh/Twinkle.rar?dl=0"]
genre = "3 STEP"
impr = "29"
total = "2741"
median = "98"
avg = "94.51"
regist = "2014/12/07 23:35"
update = "2014/12/31 23:46"

[[entries]]
no = "34"
name = "Yu^ta"
title = "Rainy"
size = "16626 KB"
addr = ["https://www.dropbox.com/s/ov4pe1qvixxa475/yuta_rainy.zip?dl=1"]
genre = "Instrumental"
impr = "31"
total = "2928"
median = "95"
avg = "94.45"
regist = "2014/12/07 23:43"
update = "2014/12/28 23:59"

[[entries]]
no = "35"
name = "kazunocobit"
title = "komogomo"
size = "16600 KB"
addr = [
    "http://ux.getuploader.com/kazunoco/download/7/%5Bkazunocobit%5Dkomogomo.zip",
    "https://www.dropbox.com/s/b6eiu6qgf9tkmit/%5Bkazunocobit%5Dkomogomo.zip?dl=0",
]
genre = "Electronica"
impr = "21"
total = "1821"
median = "91"
avg = "86.71"
regist = "2014/12/07 23:53"
update = "2014/12/29 18:11"

[[entries]]
no = "36"
name = "Colorfurythm (C_N-extage feat. Atrium Designer)"
title = "Asign Around The Nature"
size = "6800 KB"
addr = ["https://www.dropbox.com/s/a59lvxppftyt6q4/%5BColirfurythm%5DAsign_Around_The_Nature.zip?dl=0"]
genre = "PIANO ELECTRO WORLD GROOVE SESSION"
impr = "19"
total = "1529"
median = "80"
avg = "80.47"
regist = "2014/12/07 23:58"
update = "2014/12/28 23:59"
