[[entries]]
no = "1"
name = "T(re)*2y-U"
title = "PUPA"
size = "16773 KB"
addr = [
    "https://www.dropbox.com/s/ie0lz5iw1wt22fs/PUPA_BGA.zip?dl=0",
    "※12/03修正",
]
genre = "HARD RENAISSANCE"
impr = "4"
total = "9"
median = "1"
avg = "2.25"
regist = "2014/11/30 00:35"
update = "2014/12/28 23:13"

[[entries]]
no = "2"
name = "いかお"
title = "Batrachotoxin"
size = "19800 KB"
addr = ["https://www.dropbox.com/s/2dv020b47a0h74r/yadoku_ogg.zip?dl=0"]
genre = "Raggatek"
impr = "5"
total = "14"
median = "0"
avg = "2.8"
regist = "2014/12/02 11:07"
update = "2014/12/28 23:23"

[[entries]]
no = "3"
name = "HALLPBESTUDIO"
title = "PUPA"
size = "40274 KB"
addr = ["https://www.dropbox.com/s/sjy33mh4ayy1zrw/PUPA%E3%81%A7%E3%83%97%E3%83%91%E3%83%97%E3%83%91.zip?dl=0"]
genre = "HARD RENAISSANCE"
impr = "4"
total = "9"
median = "0"
avg = "2.25"
regist = "2014/12/15 13:33"
update = "2014/12/28 23:29"

[[entries]]
no = "4"
name = "umtk"
title = "Sherbet Cube"
size = "26469 KB"
addr = [
    "BMS：",
    "http://manbow.nothing.sh/event/event.cgi?action=More_def&num=214&event=96#tabs-1",
    "BGA本体：",
    "https://onedrive.live.com/redir?resid=3F2FA32F01292CDF!979&authkey=!APZx0nxNbW2Zk68&ithint=file%2czip",
    "BGAミラー：",
    "https://www.dropbox.com/s/2824tel7f6kcfnc/Sherbet_Cube_BGA.zip?dl=1",
]
genre = "FULL ON"
impr = "9"
total = "27"
median = "0"
avg = "3"
regist = "2014/12/19 20:00"
update = "2014/12/28 23:45"

[[entries]]
no = "5"
name = "紅狐"
title = "二進法の天使"
size = "69900 KB"
addr = ["https://www.dropbox.com/s/uhcqa4pzycvr3c3/binaryangel_rf.zip?dl=0"]
genre = "Abstract DNB"
impr = "7"
total = "21"
median = "0"
avg = "3"
regist = "2014/12/20 00:09"
update = "2014/12/28 23:47"

[[entries]]
no = "6"
name = "水鳥みぞれ"
title = "Space Diving"
size = "40806 KB"
addr = ["https://onedrive.live.com/redir?resid=952E5FEB47188918!34159&authkey=!APgf-OxwJ9QptqU&ithint=file%2czip"]
genre = "Rockin' Drum'n'Bass"
impr = "4"
total = "12"
median = "0"
avg = "3"
regist = "2014/12/20 17:20"
update = "2014/12/29 00:26"

[[entries]]
no = "8"
name = "成宮由愛"
title = "追憶"
size = "7440 KB"
addr = ["https://www.dropbox.com/s/svza2jehxr71l7a/tuioku-bga.zip?dl=0"]
genre = "Fragment"
impr = "2"
total = "5"
median = "0"
avg = "2.5"
regist = "2014/12/20 22:21"
update = "2014/12/29 00:07"

[[entries]]
no = "9"
name = "出前×篠乃ちよ"
title = "ロリキート"
size = "26631 KB"
addr = ["https://dl.dropboxusercontent.com/u/202644775/Ted_Lorikeet_ogg.zip"]
genre = "Flat Design"
impr = "12"
total = "36"
median = "0"
avg = "3"
regist = "2014/12/20 22:47"
update = "2014/12/28 23:48"

[[entries]]
no = "10"
name = "わっふゑ"
title = "Angel Wing"
size = "18101 KB"
addr = ["https://www.dropbox.com/s/hfq79xc151f11oi/angelwing.zip?dl=0"]
genre = "Progressive Hardcore"
impr = "3"
total = "8"
median = "0"
avg = "2.66"
regist = "2014/12/20 23:48"
update = "2014/12/28 23:56"

[[entries]]
no = "11"
name = "クロエ・ルメール"
title = "Medjed"
size = "26072 KB"
addr = ["https://www.dropbox.com/s/58a8s2qtt9bql5b/chloe_lemaire_Medjed_BGA.zip?dl=0"]
genre = "PSYCHEDELIC/DRUM'N'BASS"
impr = "1"
total = "2"
median = "0"
avg = "2"
regist = "2014/12/21 23:26"
update = "2014/12/28 23:48"

[[entries]]
no = "12"
name = "karoeya"
title = "Notebook"
size = "23541 KB"
addr = [
    "BMS+動画",
    "https://www.dropbox.com/s/tz6rg9aaqzxoyn1/Sho%20Fish%20-%20Notebook_bga.zip?dl=0",
    "BMS+音楽+動画",
    "https://www.dropbox.com/s/x529af6zqs60ihl/Sho%20Fish%20-%20Notebook.zip?dl=0",
]
genre = "UK HARDCORE"
impr = "4"
total = "12"
median = "0"
avg = "3"
regist = "2014/12/21 23:50"
update = "2014/12/28 23:51"
